---
title: "Mittwochs im Stadion"
date: "2008-11-21T23:53:37"
categories: [gewesen]
---

Handschuhe - ***check***
Mütze und Schal - ***check***
extra warme Socken vom Bund - ***check***
Strickjacke über Pullover unter Winterjacke - ***check***
zwei Power-Cocktails intus für die Wärme von innen - ***check***

Ich war also vorbereitet für das erste Länderspiel meines Lebens; im diesmal ausverkauften Berliner Olympiastadion (das hatte ich zuvor noch nicht erlebt). Trotzdem haben die Briten meist mehr Stimmung gemacht als die zahlenmäßig deutlich überwiegenden Deutschen im Stadion. Wenn 10000 Engländer *God save the Queen* oder *Rule, Britannia* singen, dann ist die Atmosphäre überwältigend. Da kann es noch so kalt, nass und zugig sein.

Das Spiel hat mit der Stimmung nicht mithalten können. Auf Seiten der Gäste war nur eine B-Elf angereist, die dann auch noch dank der besseren Offensivaktionen den Sieg mit nach Hause nahm. Die Deutschen hatten mehr vom Spiel, kamen aber zu selten in den gegnerischen Strafraum und deshalb nur zu einem Glückstor. Viele Experimente, kaum Erkenntnisse.

Aber wer weiß, wann ich mal wieder die Chance auf ein Länderspiel habe (vielleicht 2012, wenn Berlin und Leipzig für die Ukraine bei der EM einspringen); das muss man einfach mitgemacht haben, gerade am [Welttoilettentag](http://de.wikipedia.org/wiki/Welttoilettentag). Das Bier (angeblich Warsteiner) war allerdings eine Zumutung und hat noch schlechter geschmeckt als das bei Hertha-Spielen ausgeschenkte Heineken...
