---
title: "Die Bahn und schnelle Verbindungen (suchen)"
date: "2007-08-09T19:56:20"
categories: [gedacht,gefunden]
---

Seit einiger Zeit hat [die Bahn](http://www.bahn.de/) ihre Verbindungssuche etwas optimiert. Auf der Startseite befindet sich jetzt prominent platziert in der Mitte der Page ein Formular, über dieses man neben den üblichen Angaben (Start, Ziel, Datum) auch sofort eine Auswahl bezüglich der Bahncard und der Anzahl Passagiere treffen kann. Nach Klick auf *Suchen* erscheint dann sofort das Ergebnis ohne den vorher notwendigen Schritt über die erweiterte Suchmaske.

So weit so gut. Doch leider fand ich bei den letzten Suchen auf meiner Standardstrecke Berlin - Halle nur noch Angebote, die mindestens einen IC oder ICE beinhalteten - mit den damit verbundenen höherpreisigen Tarifen.

Die Ursache war schnell gefunden: Die neue Schnellsuche wird automatisch mit der Option "schnelle Verbindungen bevorzugen" durchgeführt. Und diese ist wohl falsch betitelt, denn scheinbar werden alle Verbindungen herausgefiltert, welche keinen der schnellen, aber auch teuren InterCity-Züge enthalten. So bekomme ich zwar als Auswahl die Option, für 32,25€ in 2:40 Stunden mit RE, IC über Magdeburg zu fahren, aber die fast gleichzeitig startende Verbindung mit RE, RB für 19,80€ sehe ich nicht - und diese ist mit 2:38 Stunden sogar zwei Minuten schneller.

Das ist leider ein Extrembeispiel - ich fahre normal die Strecke mit dem IC in unschlagbaren 1:19h - doch jeder Benutzer der Schnellsuche sollte sich darüber im Klaren sein, dass ihm vielleicht Ergebnisse unterschlagen werden, die eher dem Geldbeutel des Kunden nützen als dem der Bahn. Diese Option als Standard zu aktivieren ist jedenfalls nicht kundenfreundlich.
