---
title: "Dies ist ein Herbstag, wie ich keinen sah"
date: "2005-10-14T16:00:55"
categories: [gedacht]
---

Es hat schon seine ganz eigene Atmosphäre, so ein vernebelter Herbstmorgen. Wenn man auf dem Weg nach Leipzig das heimische Sachsen-Anhalt verlässt und plötzlich die Nebelschwaden den Blick freigeben auf die morgendliche Sonne mit ihrer großen, orangenen Aura...

Leider kann Leipzig selber die Atmosphäre sehr schnell wieder zerstören. Sie haben scheinbar von Halle gelernt und bauen gleichzeitig an allen Ecken der Stadt für die WM - Die Welt zu Gast auf der Baustelle. Dazu ändert sich jede Woche die Verkehrsführung, so dass ich wirklich froh bin, nicht mehr täglich pendeln zu müssen.

Auch die Uni will sich für ihr Jubiläum neu einkleiden und baut momentan nicht nur eine neue Mensa, sondern auch das Hörsaalgebäude um. Danach folgen die alte Haupt-Mensa und das Hauptgebäude mit der Marx-Skulptur, die einem neuen Prachtbau weichen müssen. Bis dahin ist aber hoffentlich mein Diplom in trockenen Tüchern und ich kann der Baustelle Leipzig den Rücken kehren - Karten für die WM habe ich ja nicht bekommen...
