---
title: "Mauern"
date: "2009-03-13T15:18:43"
categories: [gedacht,gefunden]
---

Mit Mauern kennt man sich aus in Halle. Ob es sich nun um [Nachbauten der Berliner Mauer für einen Film](http://www.mz-web.de/servlet/ContentServer?pagename=ksta/page&atype=ksArtikel&aid=1236150453832&calledPageId=987490165154) handelt oder bewegliche Exemplare aus Polizisten ([Beitrag von TV-Halle vom 09.03.2009](http://www.tvhalle.de/index.php?option=com_content&task=view&id=404&Itemid=84)), in der Saalestadt findet man sie alle.

Doch das Derby Halle gegen Magdeburg steht sinnbildlich für das gespannte Verhältnis zwischen den beiden größten Städten Sachsen-Anhalts, die Mauer in den Köpfen. Dies ist wohl in dem Selbstverständnis von Halle begründet, als größte Stadt und kulturelles Zentrum des wiedergegründeten Bundeslandes nach der Wende nicht Hauptstadt geworden zu sein ([ein Argument, dass Magdeburg mit seiner Geschichte wiederum nicht versteht](http://sanity.madcynic.com/2009/01/26/wie-man-eine-stadt-vor-den-kopf-stost/)). Seitdem wird jede Entscheidung des Landes für eine der beiden Städte von den Magdeburgern und Hallensern auf die Goldwaage gelegt ([auch von mir](/blog/2008/09/25/eu-bestatigt-it-always-rains-on-me/)) und das gute Verhältnis der Oberbürgermeister kann nicht darüber hinwegtäuschen, dass gerade in den Stadträten diese Befindlichkeiten aus politischem Interesse öfters bedient werden.

Aktuelles Thema sind dabei die [Magdeburger Halbkugeln](http://www.flickr.com/photos/7891209@N04/3314619976/), ein Geschenk der Landeshauptstadt zum Hallenser Stadtjubiläum. Diese wurden von den in meiner Heimatstadt allgegenwärtigen Sprayern verunstaltet und werden im Zuge der ~~Restauration~~ Neugestaltung [an einen weniger öffentlichen Platz verlegt](http://www.halleforum.de/Halle-Nachrichten/Halbkugeln-kommen-in-EinsteinKita/19798), was Diskussionen in der lokalen Presse hervorrief.

Nun könnte man, ohne über die o.g. Mauer zu blicken, den Standpunkt vertreten, dass dieses Geschenk selber schon eine Unverschämtheit war und nie öffentlich ausgestellt gehörte. Denn das [Kunstwerk](http://www.magdeburger-halbkugeln.de/) ist in seiner Intention eine Erinnerung an ein Magdeburger Jubiläum, also Werbung für die schenkende Stadt. Und während in Magdeburg Exemplare herumstehen, die von Künstlern gestaltet wurden (eine Aktion, die von [Berlin mit seinem Bären](http://www.buddy-baer.com/de.html) und [Leipzig mit dem Löwen](http://de.wikipedia.org/wiki/Tierparaden) abgeschaut wurde), ist die Schenkung an Halle von Kindern gestaltet und könnte bösartig als Herabwürdigung der selbsternannten Kulturhauptstadt interpretiert werden.

Der Magdeburger OB will kein Öl in das Feuer gießen und hat geäußert, dass an das Geschenk keine Bedingungen geknüpft sind, er also kein Problem darin sieht, wenn die Halbkugeln aus dem halleschen Stadtbild verschwinden. Und das ist vielleicht sogar die beste Lösung für alle. Denn zum Einen werden die Hallenser nicht mehr an diese unglückliche Schenkung erinnert, und zum Anderen lernen die Kinder der Kita, kreativ mit dem Präsent der Landeshauptstadt umzugehen und so zu verhindern, dass sie die vorherrschenden Denkmuster übernehmen.

Wie man sieht, ist Mauern aufzubauen einfach, sie einzureißen aber schwierig. Seit ich Halle in Richtung Berlin verlassen habe, schaue ich etwas gelassener auf die Städtebeziehung, und dies wünsche ich allen Sachsen-Anhaltern (oder -Anhaltinern) zum Wohle des gesamten Landes.
