---
title: "Berlinale-Stimmungsbild"
date: "2011-02-13T19:23:06"
categories: [gedacht]
---

Heute hatte ich zwischenzeitlich schon einmal die Nase gestrichen voll von der Berlinale. Es fing damit an, dass ich meine Tram und einen Ausweichbus verpasst habe und so statt 9:45 erst zwei Minuten vor 10Uhr am Potsdamer Platz ankam. Dementsprechend lang war die Schlange vor den Ticketkassen und so habe ich es nicht geschafft, bis zum Beginn meines ersten Films um 11Uhr an die Reihe zu kommen und bin umsonst so zeitig aufgestanden!

Dabei ist Schlaf ein kostbares Gut während der Berliner Filmfestspiele. So war meine Laune erst einmal am Tiefpunkt angelangt. Zum Glück stellten sich die Schlangen später am Tage als deutlich kürzer heraus und nach einer halben Stunde Warten hatte ich doch noch meine gewünschten Karten ergattert. Mission erfüllt, Laune verbessert. Zumindest für heute. 

---

Vielleicht bekomme ich auch noch heraus, warum mir die BVG nie Verbindungen mit der U2 heraussucht, obwohl dies die direkte und zudem kürzeste Verbindung ist. Zum Potsdamer Platz muss ich schließlich noch oft genug.

---

Eine Erfahrung habe ich heute am Ende meines Japanese Sunday noch gemacht: Es gibt immer eine Person im Publikum die sich traut zu fragen, [ob der Film einen tieferen Sinn hat](http://www.festivalblog.com/archives/2011/01/post_6.php5).
