---
title: "Schrödinger's Cat Trilogy"
date: "2011-06-26T01:20:56"
categories: [gelesen]
---

**The universe next door - The Trick Top Hat - The Homing Pigeons**

*von Robert Anton Wilson,
herausgegeben von Dell Publishing, ISBN 978-0-440-50070-4, 20$*

Gleich zu Beginn muss ich zugeben, dass ich eine wichtige Ebene des Buches nicht verstanden habe. *Schrödingers Katze* behandelt in seinen drei Teilen jeweils ein Problem der Quantenmechanik, und bis auf das erste davon, die Theorie der Paralleluniversen in *The universe next door*, habe ich keines richtig deuten können und das Buch hauptsächlich als Satire wahrgenommen. Dies ist es auch vordergründig, wie es ausgehend von einer drogenreichen Party das Land Unistat entwirft, das von Geheimdiensten und Geheimbünden mit den wildesten Verschwörungstheorien geprägt wird. Doch da soll eben auch mehr sein...

In sehr kurzen, dialoglastigen Kapiteln führt Robert Anton Wilson eine große Anzahl von überdrehten Charakteren ein, die sich auf der schon genannten Party treffen. Angefangen mit der Gastgeberin der Party, Epicene Wildeblood, einer stadtbekannten Transsexuellen (deren präparierter Penis ständig den Besitzer wechselt), über Dr. Dashwood, einem Orgasmusforscher, dem Zwerg Markoff Chaney, bis hin zu dem Zauberer Cagliostro der Große reicht die Palette der Figuren.

Zu viel sollte man sich an diese Antihelden jedoch nicht gewöhnen, denn jedes der drei Bücher ist in zwei Hälften unterteilt, die jeweils den Titel *Book One* tragen. Damit wird darauf hingewiesen, dass es einen Sprung in ein Paralleluniversum gab und fortan die Handlung von vorne beginnt. Während sich einige Ereignisse in gewissem Rahmen wiederholen, haben die Charaktere zum Teil ihre Geschlechter gewechselt, füllen komplett andere Rollen aus und Unistat hat wieder einen anderen Präsidenten. Die Spannbreite reicht dabei von einem religiösen Rechten über eine liberale Ökonomin, die durch die Förderung der Forschung die gesamte Gesellschaft in eine Utopie verwandelt. Ebenso wechseln die gerade angesagten Geheimbünde, ihre Mitglieder und Gegenspieler und die von ihnen verfolgten Theorien und eingenommenen Drogen. Verwirrend ist dabei, dass die Handlung teilweise einfach weitergeht und Kontinuität suggeriert, obwohl sich plötzlich die Rahmenbedingungen und Personen komplett verändert haben.

Jedes dieser so beschriebenen Universen (sprich Buchteile) nimmt sich bestimmter Probleme unserer Gesellschaft an, um dieser auf bitterböse Art und ins Extreme überspitzt den Spiegel vorzuhalten. Im letzten Teil zum Beispiel geht es praktisch nur noch um Sex, doch alle die verschiedenen Arten des Geschlechtsverkehrs beschreibenden Begriffe wurden durch Synonyme ersetzt, die meist Eigennamen von Obersten Richtern oder anderen Vertretern zurückgebliebener Ansichten sind. Zum Schluss behandelt sich das Buch sogar auf der Metaebene selber und trifft Aussagen über sich und seinen Autoren.

In all seiner oberflächigen Verwirrtheit ist *Schrödingers Katze* die meiste Zeit über einfach nur komisch. Als ich mich damit abgefunden hatte, der wild zwischen unterschiedlichsten Perspektiven umherspringenden Handlung nicht immer folgen zu können, hatte ich viel mehr Spaß an dem Buch. Und vielleicht gibt es ja irgendwo ein Universum, in welchem ich die Analogien der Quantenphysik darin gefunden und verstanden habe.
