---
title: "Tideland"
date: "2007-08-01T21:53:03"
categories: [gesehen]
---

*Canada/UK (2005)
Regie: Terry Gilliam
Darsteller: Jodelle Ferland (Jeliza-Rose), Brendan Fletcher (Dickens), Janet McTeer (Dell), Jeff Bridges (Noah), Jennifer Tilly (Queen Gunhilda)*
[Offizielle Homepage](http://www.tidelandthemovie.com)

Nach dem Ärger um den mittlemäßigen [Brother Grimm](/blog/2005/10/11/brothers-grimm/) sollte der nächste Film von Terry Gilliam vor allem eines werden: Unabhängig von den großen Studios und deshalb klein und preiswert. Mit nur zwei Drehorten und fünf Hauptdarstellern erfüllt Tideland genau diese Kriterien, ohne aber auf die von Gilliam bekannte visuelle Brillianz zu verzichten. Nachdem anderthalb Jahre nach der ersten Aufführung in Deutschland noch kein offizieller Starttermin feststeht, habe ich mir nun die englische DVD zugelegt.

Der Film handelt von der zehnjährigen Jeliza-Rose. Ihr Vater Noah, ein ehemaliger Rockstar, ist ebenso wie die Mutter drogenabhängig. Nachdem diese einen Drogentod stirbt, ziehen Vater und Tochter aufs Land in das heruntergekommene Haus von Noahs Mutter. Als sich dort auch noch der Vater seinen letzten Schuss gibt, flüchtet sich das Mädchen vor der harten Realität in Traumwelten, aus denen sie nur die verschrobene Nachbarin Dell und ihr zurückgebliebener Bruder Dickens befreien können.

Ein schwer verdauliches Stück Film serviert Gilliam mit Tideland dem Publikum - kein Wunder, dass bis jetzt kein Verleiher Vertrauen in den Erfolg an den Kinokassen zeigt. Zwei ganze Stunden muss der Zuschauer dem tragische Schicksal von Jeliza-Rose folgen. Schon während die Eltern noch lebten, hatte das Mädchen kein normales Leben - die Mutter beschimpfte und beweinte sie abwechselnd, und dem Vater musste sie regelmäßig die Spritze für seine "Urlaubstrips" bereiten. Doch mit deren Tod wird alles nur noch makabrer, denn weil Jeliza-Rose den Tod von Noah nicht wahrhaben will, schläft sie auf dem Schoß des langsam verwesenden Vaters. Dank der guten Maske wirkt dies bizarr realistisch - vor allem als irgendwann die blau gefärbte Zunge aus dem Mund zu hängen beginnt.

Als Puppenersatz besitzt Jeliza-Rose vier Barbieköpfe, die sie auf die Finger steckt und mit denen sie imaginäre Gespräche führt, während sie das Haus der Großmutter und die Umgebung erkundet. Dabei begibt sie sich zuerst auf den Pfad von Alice im Wunderland, da sie dem Vater immer aus diesem Buch vorgelesen hat. Der nach einer Epilepsie-OP zurückgebliebene Dickens kommt da gerade Recht, die ohnehin große Fantasie des Mädchens noch zu beflügeln und sie doch gleichzeitig aus ihren Träumen zu reißen. Denn beide entdecken so etwas wie eine erste Liebe füreinander, während sie die unwirtliche Umgebung wie ein Meer erkunden und einen Zug an der vorbei führenden Bahnlinie als den bösen Hai fürchten. Doch spätestens, als Dell ihren ehemaligen Liebhaber Noah genau wie die eigene tote Mutter zu einer Mumie verarbeitet, um so ihren Trennungsschmerz nicht verarbeiten zu müssen, und Dickens Jeliza-Rose verrät, dass er Dynamit gestohlen hat, um damit den Hai zu erlegen, merkt der Zuschauer, dass der Film auf ein tragisches Ende hinausläuft.

Getragen wird die Geschichte von der jungen Jodelle Ferland, welche genügend kindliche Unschuld mitbringt, um sowohl die aufkeimende Liebe zu Dickens als auch die Verspieltheit und das Abtauchen in die Fantasiewelten glaubwürdig zu vermitteln. Da auch die "reale" Welt um den Vater und Dell und Dickens schon genügend bizarr ist, fallen die ersten Tagträume kaum auf. Erst mit zunehmender Filmdauer, als Jeliza-Rose zunehmden unter Hunger und zu wenig Schlaf zu leiden beginnt, greift Gilliam tiefer in die optische Trickkiste (der Fall in den Hasenbau, das Eintauchen in das Haus), und irgendwann fangen die Puppenköpfe auch an zu sprechen, ohne dass sich der Mund des Mädchens bewegt.

Was mir etwas gefehlt hat an diesem Film ist eine Aussage. Laut einer kurzen Ansage vor dem Film will Gilliam zum Nachdenken anregen, doch mir fehlt die Motivation, um die Tour de Force des Mädchens miterleben zu müssen. Am Ende bleibt ein thematisch schwerer, mit bizarren Rollen ausgestatteter Film übrig, den ich zwar nicht so schnell vergessen kann, aber dessen Sinn sich mir nicht erschließt
