---
title: "Dani Levy über die Wahl"
date: "2005-09-20T09:49:28"
categories: [gedacht,gefunden]
---

Der Regisseur von "Meschugge" und "Alles auf Zucker!" hat in der MZ vom heutigen Tag ein nettes Interview gegeben, welches auch [online](http://www.mz-web.de/servlet/ContentServer?pagename=ksta/page&atype=ksArtikel&aid=1120742675803&openMenu=1013083806110&calledPageId=1013083806110&listid=1018881578428) gelesen werden kann. Vor allem seine Aussage zur Ächtung der PDS durch die anderen vier großen Parteien und seine Abneigung zur Jamaika-Koalition haben mir gefallen, da ich ähnlich darüber denke.

Aber nach den Aussagen sämtlicher Grüner am Montag wird es eine Regierung aus CDU/CSU/FDP und den Grünen wohl nicht geben. Sie begründen dies damit, nicht die ["Steigbügelhalter"](http://www.taz.de/pt/2005/09/20/a0115.nf/text) für Schwarz-Gelb sein zu wollen, und damit stimme ich zu 100% überein. Ich habe diese Partei nicht gewählt, damit sie jetzt die neoliberalen Konzepte mittragen, sondern damit sie ein starke Opposition dagegen bilden. Dies bedeutet aber auch, dass es wahrscheinlich auf eine große Koalition hinausläuft, da mit den Linken ja niemand sprechen will.

Eine Anmerkung noch zu der Karte der Direktmandate von gestern: Ganz Sachsen-Anhalt ist rot (als einziges Bundesland), d.h. in jedem Wahlkreis hat sich der/die SPD-KandidatIn durchgesetzt. Dies ist umso erstaunlicher, als zur letzten Landtagswahl die CDU so stark dominierte. Es zeigt aber wiederum, dass damals bewusst von den Bürgern die Regierung Höppner abgewählt wurde und sie trotzdem der Auffassung blieben, auf Bundesebene sei die SPD die bessere Alternative. Eine spannende Landtagswahl im nächsten Jahr steht uns also bevor, denn Herr Böhmer hat seinen Worten nicht viele Taten folgen lassen, selbst wenn ich ihn als Repräsentant unseres Landes sehr schätze.
