---
title: "A.I. - Künstliche Intelligenz"
date: "2001-09-18T00:00:18"
categories: [gesehen]
---

*USA (2001)
Regie: Steven Spielberg
Darsteller: Haley Joel Osment (David), Frances O'Connor (Monica), Sam Robards (Henry), Jude Law (Gigolo Joe), William Hurt (Dr. Hobby) und andere Roboter*
[Offizielle Homepage](http://aimovie.warnerbros.com/)

Die Zukunft: Nach der großen Flut ist die Geburt von Kindern staatlich reglementiert. Um Eltern trotzdem den Kindeswunsch zu erfüllen, erschafft Dr. Hobby den menschlichsten Roboter, der jemals erschaffen wurde, mit eigenem Bewusstsein und auf die Liebe seiner Mutter fixiert.

Monica und Henry, dessen Sohn aufgrund einer unheilbaren Krankheit im tiefgekühlten Zustand auf die Heilung wartet, werden auserwählt, das Roboterkind David zu testen. Dieser schafft es zunächst, die Liebe seiner Mutter zu gewinnen, doch dann kehrt der leibliche Sohn zurück und die Eltern sind nicht mehr in der Lage, mit beiden Kindern klarzukommen. Um David vor der Abschaltung zu retten setzen ihn Monica und Henry in der Wildnis aus, wo für den Jungen eine Odyssee beginnt, denn David wünscht sich nichts sehnlicher als ein richtiger Junge und damit wieder von der Mutter geliebt zu werden...

Der Film basiert auf einer Kurzgeschichte aus den 60ern und war eigentlich ein Traum des verstorbenen Stanley Kubrick, der jedoch während seiner Lebenszeit nie die Technik für die Verwirklichung des Traumes zu haben glaubte. So gab er das Projekt kurz vor seinem Tod an Steven Spielberg ab, der zumindest den technischen Aspekt perfekt realisierte - die Schauplätze der Handlung wirken durchweg real, der Teddy ist der Star des Filmes und die Roboter scheinen direkt Herrn Kubricks Visionen zu entspringen.

Auch seine pessimistischen Weltsicht findet Platz in einigen Teilen des Films (z.B. das überflutete New York inkl. WTC oder das Fleischfest), doch den Großteil hat Steven Spielberg mit einem Berg aus Schmalz überzogen, der vor allem das viel zu lange Ende zu einer Tortur macht: 148min hätten es nun wirklich nicht sein müssen. Dabei ist die Story über den ersten Roboter, der aus einem eigenen Selbstbewußtsein sein Handeln lenkt, wirklich mehr als einen Gedanken wert und auch die Frage, ob ein Roboter ein echtes Kind ersetzen bzw. sogar ein gleichberechtigter Bruder sein kann - doch Spielberg präsentiert seine Ansichten auf dem Silbertablett und schwelgt viel lieber in zwar tollen, aber wenig aussagekräftigen Bildern.

Fazit: Wegen dieser Thematik, der tollen Umsetzung und den schauspielerischen Leistungen gebe ich diesem Film ein GUT, aber man muss schon Geduld und Sitzfleisch mitbringen, um diesen Spielberg zu verdauen!
