---
title: "Zuschauerräume"
date: "2009-01-28T23:04:51"
categories: [gelesen]
---

*von Giwi Margwelaschwili,
erschienen im Verbrecher Verlag, ISBN 978-3-940426-08-6, 11€*

Nachdem in [Officer Pembry](/blog/2007/10/01/officer-pembry/), dem letzten Werk von Giwi Margwelaschwili, ein Buch Einfluss auf die Welt hatte, in der es geschrieben wurde, geht es in *Zuschauerräume* nun um eine mittelalterliche Theaterwelt, deren handelnde Personen sich ihrer szenischen Natur bewusst sind und zwei verschiedene Verhaltensmuster an den Tag legen.

Auf der einen Seite stehen der König und seine Gefolgsleute, die versuchen, sich der Beobachtung durch das Publikum zu entziehen, indem sie alle als Zuschauerräume identifizierten Handlungsschauplätze dem Boden gleichmachen. Als zweite Strategie strebt der König an, die Machtstrukturen der herrschenden Adelshäuser aufzulösen, um ein Fortschreiten der szenischen Geschichte zu verhindern. Ziel ist, dass die Zuschauer das Interesse verlieren und die Akteure unbeobachtet leben lassen. Der Adel auf der anderen Seite ist mit seiner Entmachtung natürlich ganz und gar nicht einverstanden, und so führt ein Herzog eine Gegenbewegung an, die gerade die Zuschauerräume und damit den Einfluss des Publikums für ihren Sturzversuch des Königs nutzen will.

Passend zu dem sich oft wiederholenden Spiel mit der Doppeldeutigkeit einer Bühne auf der Bühne ist das Buch in Form eines Theaterstücks ausgeführt. Die Handlung ist in Szenen und Akte eingeteilt und wird fast ausschließlich in Dialogen erzählt, nur ab und zu unterbrochen von Regieanweisungen.

Witziges Detail: Obwohl ständig von den handelnden Personen angesprochen und dem Vorwurf des Einflusses auf die Geschichte ausgesetzt, bleibt das Publikum doch immer passiv und der zu Beginn des Buches angesprochene Ausbruch aus der szenischen Realität wird nur einem Kissen und einem Fast-Toten zugebilligt - außer der Sicht in die Szene hat das Publikum also keinen Kontakt zu der Bühnenwelt. Im Gegensatz dazu sind die Bühnencharaktere in der Lage, diese Sicht zu trüben bzw ganz zu verhindern. D.h. es besteht eine offensichtliche Diskrepanz zwischen der von den Figuren wahrgenommenen Welt und den vorherrschenden Gesetzmäßigkeiten, die beschrieben werden.

Besonders gefallen haben mir die gesellschaftlichen Hintergründe, die man aus den Sichtweisen der beiden Parteien ablesen kann. Das eine Extrem ist der durch den König verkörperte Wunsch nach der absoluten Privatsphäre, die zu wahren einen hohen Preis fordert und auch zur Einschränkung der Freiheit, in diesem Fall der Kunst, führen kann. Auf der anderen Seite das Gegenkonzept der totalen Offenheit, die Anpassung an den allgemeinen Durchschnitt mit der Begründung, sich den externen Einflüssen nicht entziehen zu können, quasi fremdbestimmt zu sein. So wird auch die Folter verteidigt als Unterhaltung des Publikums, dass doch nie jemand in der Theaterrealität sehen kann - so ist es wohl mehr eine Projektion des eigenen Sadismus auf eine fremde Kraft, die die Figuren leitet und eine bequeme Ausrede bietet.

Fazit: Giwi Margwelaschwili hat sich mit *Zuschauerräume* dem Medium Theater zugewandt und konfrontiert Figuren einer mittelalterlichen Bühnenszene mit der Tatsache, dass ein Publikum alle ihre Aktionen beobachten kann. Darin versteckt der Autor eine Prise Gesellschaftskritik und einen Diskurs über die persönliche Freiheit. Ein interessantes Experiment, sowohl in Stil als auch Thematik!
