---
title: "BenX"
date: "2008-05-26T22:06:35"
categories: [gesehen]
---

*Belgien (2007)
Regie: Nic Balthazar
Darsteller: Greg Timmermans (Ben), Laura Verlinden (Scarlite), Marijke Pinoy (Bens Mutter), Pol Goossen (Bens Vater), Titus De Voogdt (Bogaert), Maarten Claeyssens (Desmedt), Tania Van der Sanden (Sabine), Johan Heldenbergh (Religionslehrer), Jakob Beks (Werklehrer), Peter De Graef (Psychiater), Ron Cornet (Schuldirektor) und andere Flämen*
[Offizielle Homepage](http://www.benx.kinowelt.de/)

Ben ist ein autistisch veranlagter Jugendlicher, der in der Schule von den Mitschülern malträtiert nur in der Welt des Online-Rollenspiels Archlord zurecht kommt. Doch die dort gesammelten Erfahrungen lassen sich nur bedingt ins echte Leben übertragen, während reale Ereignisse durchaus bis in die virtuelle Realität Einfluss ausüben. Dies muss Ben auf die harte Tour erkennen, als er mit Handy-Videos seiner Mitschüler zugespammt wird, die ihn in peinlicher Pose zeigen. Zudem will seine Online-Bekanntschaft Scarlite ihn im richtigen Leben kennenlernen, doch Ben schafft es nicht, sie anzusprechen. Als er schließlich auch noch von zwei anderen Schülern verprügelt wird, sieht er nur noch einen Ausweg: Den Selbstmord.

Was sich auf den ersten Blick anhört wie eine klassisch einseitige Verarbeitung des Themas virtuelles vs reales Leben, entpuppt sich schließlich als eine argumentativ breit gefächerte Auseinandersetzung mit den Themen Gewalt zwischen Jugendlichen und deren mediale Repräsentanz. Die Quelle für diesen flämischen Film war dabei ein realer Selbstmord eines Schülers; doch Regisseur und Autor Nic Balthazar hat sich einige Freiheiten bei der Darstellung genommen und mit dem Happy-End sogar ein klares Statement hinzugefügt.

Zu Beginn des Films wird der Zuschauer jedoch zuerst von der hervorstechenden Optik gefangen: Um die Sicht von Ben zu vermitteln, werden die Bilder von Interface-Elementen des Onlinespiels überlagert; man erlebt wie der Charakter in seinem täglichen Tun Parallelen zu seinem virtuellen Alter Ego (dem titelgebenden BenX) zieht, wenn er sich anzieht, durch die Stadt bewegt; wie er versucht mit verschiedensten Situationen klar zu kommen, die einem Autisten vor große Probleme stellen. Das Rollenspiel steht hier nicht für eine Sucht (die Online-Zeit wird genau kontrolliert), sondern für die Abwechslung einer Welt, in der Ben die (vereinfachten) Konventionen versteht und in der er sich mit einer größeren Freiheit bewegen kann. Die Übertragung der Macht seines virtuellen Charakters gelingt ihm aber ebensowenig wie das für ihn anstrengende Kopieren realer Verhaltensweisen seiner Mitmenschen.

Doch bald tauchen andere mediale Einflüsse auf: Eltern und Lehrer kommentieren in dokumentarisch anmutenden Sequenzen ein scheinbar tragisches Finale; der auf Video und Handys aufgenommene Beweis von Bens Schikanierung durch die Klassenrowdies taucht bald schon in Bens Mailbox auf, doch auch Ben selber filmt viel mit seiner Kamera. Verdeutlich wird damit die mediale Durchdringung und Verknüpfung unseres gesamten Lebens, in dem es kaum noch medienfreie, private Rückzugsräume für den Menschen gibt. Doch nicht alles ist schlecht an dieser technischen Entwicklung: Das Videohandy erlaubt Ben auch die Kommunikation mit der Mutter und er erhält darüber die Nachricht seiner Online-Bekanntschaft Scarlite. Außerdem missbraucht er selber die Macht des Videos bei seinem inszenierten Selbstmord. Das Fazit sollte also sein, selbstbestimmend mit den Medien umzugehen, sich ihnen nicht unterzuordnen und sich erst Recht nicht abhängig machen.

BenX behandelt jedoch nicht nur das Thema mediale Gewalt, sondern auch Gewalt zwischen Jugendlichen. Diese findet nicht nur physisch statt, und meist sind es Außenseiter wie Ben, die aufgrund ihrer Andersartigkeit und mangelnder Anpassung zu Opfern wider Willen werden. Dabei ist der Autismus nur eine Spielart der Andersartigkeit; stellvertretend für alle gemobbten Außenseiter an den Schulen. Im deren sozialen Geflecht gibt es immer Aggressoren, die sich durch Schikanierung und Demütigung der Schwachen eine gewisse Stellung erarbeiten. Dazu kommt ein unterstützendes Publikum, dass um nicht aufzufallen und in der breiten Masse anonym unterzugehen zustimmend applaudiert, während der Rest solche Aktionen zwar nicht billigt, aber auch nicht eingreift. Bei Ben führt das Gefühl der Hoffnungslosigkeit schließlich zu Aktionen der ungezügelten Gewalt.

Doch anstatt diese letzte Form des Ausdrucks korrekt zu interpretieren, muss Ben vor dem Direktor erscheinen; nicht in der Lage seine Probleme gegenüber den Mitmenschen auszudrücken. Viel lieber will der Rektor den "Problem"-Schüler von der Schule verweisen, denn dies ist die einfachere Lösung gegenüber der Ursachenforschung der eigentlichen Probleme. Genauso haben aber auch Bens Eltern nicht ganz zu Ende gedacht, als sie ihren Jungen tagtäglich damit quälen, in die normale Schule zu gehen. Diese ständige Belastung führt zu einer weiteren Einkehr in sich selbst, die schließlich ein wichtiger Schlüssel für den Selbstmordversuch ist. Erst am Ende haben die Eltern so weit verstanden, dass es für Ben durchaus Lebensformen abseits eines normalen Lebens gibt - anders zu sein muss nicht schlecht sein, es muss nur verstanden und akzeptiert werden.

Das schon erwähnte Happy-End als mediale Befreiungsaktion aus sich selbst hinaus wirkt jedoch etwas deplatziert. Zu sehr hat man als Zuschauer die Denkweise Bens kennengelernt, um ihm diese Planung des vorgetäuschten Selbstmords abzunehmen. Ben scheint eine so ausgeklügelte Racheaktion in der realen Welt nicht planen zu können, eher passt die Online-Ankündigung des Suizids ("Endgame") und die Reaktion der Zeugin Scarlite in die Geschichte. Trotzdem ist BenX ein sehenswerter Film, der sich unter der Oberfläche popkultureller Bild- und Toneinstellungen mit Problemen der Jugend und des Aufwachsens in einem medialen Raum befasst.
