---
title: "Alien vs. Predator"
date: "2004-11-17T00:00:45"
categories: [gesehen]
---

*Tschechien/Kanada/UK/Deutschland (2004)
Regie: Paul W.S. Anderson
Darsteller: Sanaa Lathan (Alexa Woods), Raoul Bova (Sebastian de Rosa), Lance Henriksen (Charles Bishop Weyland), Ewen Bremner (Graham Miller), Colin Salmon (Maxwell Stafford), Tommy Flanagan (Mark Verheiden), Joseph Rye (Joe Connors), Agathe De La Boulaye (Adele Rousseau), Carsten Norgaard (Rusten Quinn), Sam Troughton (Thomas Parks), Petr Jákl (Stone), Pavel Bezdek (Bass), Kieran Bew (Klaus), Carsten Voigt (Mikkel), Jan Pavel Filipensky (Boris), Tom Woodruff Jr (Alien) und andere extraterrestrische Lebensformen*
[Offizielle Homepage](http://www.alien-vs-predator-derfilm.de/)

Charles Bishop Weyland, der Besitzer einer Roboterfabrik, hat in der Antarktis eine unterirdische Pyramide entdeckt, von der seltsame Wärmestrahlung ausgeht. Sofort trommelt er eine Schar der weltbesten Wissenschaftler zusammen, um als Erster dieses Phänomen zu ergründen. Was er nicht weiß: Predatoren haben diese Pyramide angelegt, um dort ihre Nachkommen im Kampf gegen Aliens auszubilden; und Menschen dienen ausschließlich als Wirtskörper...

Der Mensch im Allgemeinen ist nicht immer sehr einfallsreich, und Comiczeichner öfters einmal auch nicht. So kam man im Superhelden-überversorgten Amerika auf die glorreiche Idee, zwei außerirdische Lebensformen aufeinander zu hetzen: Zum Einen den Predator, eine etwas sinnleere Spezies von Jägern mit Hightech-Ausrüstung, deren Existenz nur dazu diente, um Arnie einen würdigen Gegner an die Seite zu stellen. Auf der anderen Seite dann das Alien, eine vom Schweizer Künstler H.R.Giger designte Kreatur (die wie fast alle seine Werke das menschliche Wesen mit seinem innersten animalischen, triebgesteuerten Selbst kombinierte), welche in einem damals revolutionären Science-Fiction-Horror-Film von Ridley Scott die Crew eines interstellaren Raumfrachters dezimierte und am Ende von Überraschungsheldin Ellen Ripley zumindest außer Gefecht gesetzt werden konnte.

Diesem ersten Alien-Teil sollten noch drei Fortsetzungen folgen, welche mit zumindest geichbleibend hoher Qualität unterschiedliche Aspekte des Originals aufgriffen bzw. weiterentwickelten (z.B. das postmoderne Wirtschaftssystem und seine Computer, Roboter und Forscher, aber auch die Aspekte der Lebensform des Aliens). Für den Predator gab es nur einen erneut schlechten Aufguss - "Alien vs. Predator" ist aber weder die Fortsetzung der Alien-, noch die der Predator-Reihe. Vielmehr nahm man nur die Kreaturen für sich (die eigentlich ohne ihre Gegenüber nicht funktionieren) und hetzte sie aufeinander - fertig war die "innovative" Action! Dies funktionierte auch in zwei Spielen für den PC recht gut, also musste für die hungrige Fangemeinde ein Film her.

Ein in Spieleumsetzungen erfahrener Regisseur war mit Paul W.S. Anderson (<a href="">Resident Evil</a>) schnell gefunden, und aus Geldmangel durfte er erneut auch das Drehbuch verfassen. Doch damit fing das Grauen erst richtig an, denn was Herr Anderson dem Zuschauer zumutet ist unbeschreiblich: Die Story mit den jungen, dynamischen Wissenschaftlern ist nicht erst seit "Jurassic Park" altbekannt. Doch in keinem anderen Film durften Wissenschaftler bisher so sinnlose Sätze von sich geben. So kann der Experte für Pyramiden (drei Kulturen stehen dabei stellvertretend für die ganze Welt, beeinflusst von den Predatoren - wahrscheinlich kennt der Regisseur nicht mehr Völker) fließend neuartige Hieroglyphen lesen und weiß natürlich sofort, dass die tollen Verschiebungen der Innenräume sich aller 10 Minuten wiederholen. Der Italiener vergisst dafür in der Hektik und für einen Kalauer schon einmal seine Muttersprache.

Generell zeichnen sich alle menschlischen Akteure durch das Fehlen eines Charakters aus und dienen mit ihren zusammengewürfelten Persönlichkeiten offensichtlich nur dem Zweck, die Handlung durch ihren Tod oder einen schlechten Witz voranzutreiben. Dem passt sich auch die Pyramide an, in der es von Zeichnungen mit Aliens und Predatoren nur so wimmelt und die tolle Verschiebekunststücke wie bei dem Brettspiel "Das verrückte Labyrinth" beherrscht. Doch Mensch und Pyramide stellen ja auch nur Beiwerk für den Kampf der Giganten dar: Alien vs. Predator.

Tricktechnisch haben sich die Produzenten nichts vorzuwerfen. Vom Facehugger bis zur Alien-Queen (am Ende schwanken jedoch ihre Ausmaße von Einstellung zu Einstellung etwas) ist alles toll animiert, auch die Predatoren weisen keine Schwächen in der Umsetzung auf. Allerdings hat Paul W.S. Anderson mit seinem Drehbuch einige Logikfehler produziert: So braucht das erste Alien nur wenige Minuten, um nach dem Einpflanzen in einen Menschenmagen durch den Brustkorb denselben wieder zu verlassen. Und auch danach wächst es zusammen mit seinen Brüdern ohne großes Nahrungsangebot schnell auf Normalniveau. Der verbliebene Predator verzichtet dafür ab der Hälfte des Films komplett auf sein Schutzschild. Das alles hat seinen Grund: Der Regisseur will natürlich Action zeigen, und ein Kampf zwischen einem 20cm großen Alien und einem Unsichtbaren macht dem Zuschauer wahrscheinlich keinen Spaß. Doch auch so wissen die Kämpfe nicht so recht zu überzeugen. Zum Einen sind die Schnitte manchmal viel zu schnell, um überhaupt genau mitzubekommen, was gerade abgeht. Zum Anderen gibt es nicht mehr als drei etwas länger andauernde Auseinandersetzungen, die restlichen sind innerhalb von Sekunden entschieden und alle ziemlich einfallslos inszeniert - da machte das Spielen des Aliens im zugehörigen Spiel deutlich mehr Spaß und war auch abwechslungsreicher.

So bleibt als einzige Pluspunkte neben dem Auftritt der Aliens zu erwähnen, dass der deutlich gealterte Lance Henriksen die Rolle des Erschaffers seiner Roboter aus Teil zwei und drei der Alien-Reihe übernommen hat und das Ende des Films quasi die Vorraussetzung für den ersten Teil schafft.

Fazit: Paul W.S. Anderson hat es nach seiner [Resident Evil](/blog/2002/03/20/resident-evil/)-Gurke geschafft, einen noch schlechteren Film zu drehen. Neben dem miesen Drehbuch können allein der Auftritt der Aliens und die Verweise auf die "Alien"-Filmreihe den Film vor der totalen Blamage retten. Bitte einen großen Bogen um diesen Film machen!
