---
title: "Sinnlos im Weltraum"
date: "2008-11-16T14:13:40"
categories: [gesehen]
---

Einen Film nehmen, den Ton ausstellen und eine eigene (gewollt oder ungewollt) witzige Synchronisation ins Mikrofon sprechen - mit dieser Schiene sind Werke wie [Sinnlos im Weltraum](http://de.wikipedia.org/wiki/Sinnlos_im_Weltraum) zu einiger Berühmtheit im Netz gelangt. Oliver Kalkofe macht so etwas schon länger in seiner Fernsehserie *Kalkofes Mattscheibe*, wobei er dort die Idee ins Visuelle weiterentwickelt hat und alle veralberten Szenen selber nachspielt. Doch einen Serie zu drehen über einen Astronauten und zwei Roboter, die sich über eine Stunde lang einen schlechten 50er-Jahre-Science-Fiction-Film ansehen und vor allem kommentieren - das ist Trash pur.

[Mystery Science Theater 3000](http://de.wikipedia.org/wiki/Mystery_Science_Theater_3000) heißt diese etwas andere Art der Comedy. Nach Deutschland geschafft hat es nur der Film der Serie, oft auch bekannt unter dem Namen des zu sehenden B-Movies *Metaluna IV antwortet nicht* (oder *This Island Earth* im Original). Der Zuschauer sieht fast die gesamten 70 Minuten nur eine Reihe von Stuhllehnen und die drei Kommentatoren am unteren Bildrand und ansonsten den geschändeten Film und darf sich so an der Aneinanderreihung von Zoten, schlechten Witzen und der teilweise absurden Erzeugung von Sound Effects erheitern.

Synchronisiert wurde *Mystery Science Theater 3000* von den Machern des Frühstyxradios, also dem schon genannten Oliver Kalkofe und seinem Partner Oliver Welke, die auch hinter den [Wixxer](/blog/2004/06/03/der-wixxer/)-Filmen stecken. Und diese beiden Radio-erfahrenen Komiker nutzen natürlich ausgiebig die Gelegenheit, sich am Mikrofon auszutoben. Ob dies nun besser ist als das Original weiß ich nicht, *This Island Earth* wird auf jeden Fall so richtig auseinandergenommen und man wird, wenn auch nicht auf höchstem Niveau, über eine Stunde lang gut unterhalten. Wer also Trash mag, der sollte sich den Film auf jeden Fall einmal ansehen!
