---
title: "Sonys Linux-Eigentor - Entschädigungen und Entschuldigungen"
date: "2010-04-12T21:41:05"
categories: [gedacht,gefunden]
---

[Weiter](/blog/2010/03/29/linux-ausgesperrt/) [geht](/blog/2010/04/08/gedanken-zum-thema-firmwareupdates/) es mit der Berichterstattung über Sonys Featurebeschneidung per Firmwareupdate. Denn es hat, [so wird berichtet](http://www.playstationuniversity.com/ps3-owner-refunded-without-return-for-missing-other-os-3555/), eine erste Händlerreaktion auf die Entfernung der Möglichkeit gegeben, alternative Betriebssysteme auf der PS3 zu installieren. Amazon UK soll einem Kunden 20% des Verkaufspreises zurückerstattet haben, als dieser auf ein EU-Gesetz verwies. Diese Nachricht führte zu breiten [Diskussionen](http://www.heise.de/newsticker/meldung/Amazon-zahlt-fuer-Wegfall-der-Linux-Funktion-bei-der-PS3-975486.html), ob dies nur ein Einzelfall war oder alle Besitzer der alten PS3-Versionen von Amazon für Sonys Kastrierung entschädigt werden - vielleicht sollte ich auch einmal mein Glück versuchen. Sony selber soll jedoch nicht für die Entschädigung einstehen.

Interessant ist noch [ein entschuldigendes Statement seitens Sony](http://www.thinq.co.uk/news/2010/4/9/sony-says-sorry-for-other-os-take-down/) über die Hintergründe der Entfernung des *OtherOs*-Features. Demnach soll die Integrität der Playstation bewahrt werden und man sieht sich im Interesse der Mehrheit der PS3-User handeln - eine Argumentation, der ich nicht folgen kann. Denn zum Einen hat man den Privatkrieg mit dem Hacker [George Hotz](http://geohotps3.blogspot.com/) durch das Aussperren von Linux erst eröffnet und damit sich selber einen Bärendienst erwiesen, zum Anderen versteift sich Sony auf die Implikation, dass eine gehackte Playstation einen Nachteil für die Nutzer bedeutet. Dass dies für Sony der Fall ist bleibt unbestritten, aber nicht jeder PS3-Besitzer wird dieser Meinung sein.

Schön an der aktuellen Berichterstattung finde ich, dass Sony weiterhin negativ in den Schlagzeilen bleibt. Dies wird über einen längeren Zeitraum auch zu Umsatzeinbußen führen, und das ist aus meiner Sicht eine gerechte Strafe für diese unsinnige Aktion. Ich werde auf jeden Fall fleißig weiter berichten!
