---
title: "Vorsätze für 2006"
date: "2005-12-31T00:09:19"
categories: [gedacht,getan]
---

Ich wünsche allen Besuchern dieses Blogs einen guten Rutsch in das neue Jahr.

In diesem Zusammenhang habe ich mir Einiges vorgenommen. An erster Stelle steht natürlich das Beenden des Studiums mit einer hoffentlich guten Diplomprüfung und einer anschließenden, erfolgreichen Jobsuche inklusive Umzug (wahrscheinlich notwendig). Deswegen habe ich auch meine "Karrieren" in zwei Browsergames aufgegeben, um mich voll diesem Ziel zu widmen.

Ansonsten ist das angepasste Layout für mein Blog schon fast fertig gestellt und wird hoffentlich bald online gehen. Dann wird es wohl auch ein Update auf WordPress 2.0 geben, da in der neuen Version einige interessante Features fest integriert sind, welche ich momentan noch mühsam über selbst angepasste PlugIns realisiere. Allerdings stehen vor diesem Update noch einige Tests an; eventuell muss ich sogar das neue Design schon wieder anpassen.

Dies sollten dennoch alles umsetzbare Vorsätze sein. Ich sage deshalb *auf Wiedersehen* bis ins neue Jahr, da ich den Übergang weit abseits des Internet feiere.
