---
title: "Snatch - Schweine und Diamanten"
date: "2001-03-14T00:00:17"
categories: [gesehen]
---

*UK/USA (2000)
Regie: Guy Ritchie
Darsteller: Brad Pitt (Mickey O´Neil), Benicio Del Toro (Franky Vier Finger), Dennis Farina (Avi), Adam Fogerty (George), Alan Ford (Brick Top), Robbie Gee (Vincent), Stephen Graham (Tommy), Ade (Tyrone), Lennie James (Sol), Vinnie Jones (Bullet Tooth Tony), Mike Reid (Doug der Kopf), Rade Sherbedgia (Boris die Klinge), Jason Statham (Turkish), Sam Douglas (Rosebud), Austin Drage (Gypsy Kind), Andy Beckwith (Errol), Ewen Bremner (Mullet), Nikki & Teena Collins (Alex & Susi), Sorcha Cusack (Mum O´Neil), Jason Flemying (Darren), GOLDIE (Bad Boy Lincoln) und andere Zigeuner*
[Offizielle Homepage](http://www.snatch-der-film.de/)

Diamantendieb und -kurier Franky "Vier Finger", der im Auftrag des New Yorker Gangsters Avi in Antwerpen einen großen Edelstein geraubt hat, macht auf seinem Weg zurück nach Manhattan in London halt. Er soll kleinere Steine bei Avis Cousin Doug "Der Kopf" und anderen Juwelieren in Hatton Garden abliefern. Doch leider ist er ein Spieler, und bei dem Versuch, eine Wette abzuschließen, ergattern 2 Kleinganoven, die zu dämlich waren, das Wettbüro zu überfallen, die Steine, die Avi jedoch um jeden Preis zurückhaben muss.

Zur gleichen Zeit steht der unerfahrene Boxpromoter Turkish mit seinem Ziehsohn Tommy vor seinem ersten großen Kampf, den er mit dem uneingeschränkten Boss der Gegend, dem Boxpromoter und Schweinefarmbesitzer Brick Top auf die Beine stellt. Ungünstig ist allerdings, dass Turkishs Kämpfer Gorgeous George zuvor bei einem anderen Fight von dem irischen Zigeuner Mickey O´Neil auf die Bretter geschickt worden ist. Kurzerhand setzen Turkish und Tommy Mickey als neuen Schützling für den versprochenen Kampf ein. Doch die Zigeuner sind ein seltsames Volk, und die ganze Situation läuft aus dem Ruder...

Wer *Bube, Dame, König, Gras*, den Erstling von Guy Ritchie gesehen hat, der fühlt sich hier schnell wieder zu Hause. Schauspieler aus diesem Film mischen sich mit Hollywood-Größen, und die schnellen Schnitte hat der Regisseur inzwischen vervollkommt - allzuviel Zeit zum Nachdenken bleibt da nicht, ist aber auch gar nicht nötig, da alle wandelnden Hauptfiguren wirkliche Originale sind, und so ergibt sich in der von Crime gespickten Story das Eine aus dem Anderen und am Ende kommt es wieder zu dem Showdown, bei dem man keinerlei Überlebende erwartet, bis auf... Naja, storytechnisch hat sich in den 2 Jahren zwischen den Filmen kaum etwas getan, es ist ein und dasselbe Rezept. Es macht aber trotzdem Spaß, die Verlierer, die sich so halblegal durchs Leben schlagen und mit einer Aktion endlich daraus ausbrechen wollen, in ihr Verderben stürzen zu sehen. Das Geschichtengewirr kommt an keiner Stelle des Films wirklich zur Ruhe, man erwartet jederzeit das KO der Looser, und doch halten sie bis zum Ende durch, und mit ihnen baut sich die Spannung kontinuierlich auf um am Ende wie ein Pulverfass zu explodieren - inklusive Happy-End. Guy Ritchie hat diese Sparte Film mittlerweile bis zur Perfektion getrieben und bietet dem Zuschauer so einen genialen Mix aus Crime, schwarzen Humor und Trash.

Fazit: Wenngleich der Film nichts wirklich Neues zu bieten hat, wird er aufgrund der Perfektion von Guy Ritchie doch alle Fans von *Pulp Fiction* und *Bube, Dame, König, Gras* zufriedenstellen und einen unvergleichlich witzigen Abend bescheren!
