---
title: "Ich habe sogar 20% auf Tiernahrung bekommen"
date: "2008-11-22T21:30:31"
categories: [gewesen]
---

Wie in meinem Artikel zu [LSD](/blog/2008/10/18/liebe-statt-drogen/) erwähnt, hatte ich eine Freikarte zum [Quatsch Comey Club](http://quatsch-comedy-club.de/berlin/) für den letzten Donnerstag geschenkt bekommen. Also machte ich mich auf zum Friedrichstadtpalast und war erst einmal geschockt, wie voll der Zuschauerraum schon eine halbe Stunde vor Beginn war. Wie sich herausstellte, waren an diesem Abend verschiedene Gruppen von Firmen wie Vattenfall oder Robinson Club zu Weihnachtsfeiern anwesend und schon fleißig am Trinken und Essen.

Damit scheint der QCC neben den gesalzenen Eintrittspreisen zusätzlich Umsatz zu generieren, denn für 3,40€ hätte ich mir schon mehr als ein 0,33er Radeberger aus der Flasche gewünscht. Hinzu kamen ein Euro pro Kleidungsstück an der Garderobe (ich wusste nicht, dass man auch alles mit hineinnehmen kann). [In Leipzig vergangenes Wochenende](/blog/2008/11/16/als-wetter-noch-kein-klima-war/) war die Kleiderabgabe kostenlos und das halbe Liter Flaschenbier kostete 2,50€ - nunja, einem geschenkten Gaul schaut man nicht ins Maul.

Die Show selber bestand aus fünf Comedians; einer davon war Ole Lehmann, der in der Moderatoren-Rolle von Thomas Hermanns durch den Abend führte und neben der Vorstellung seiner Gäste auch eigene Nummern darbot. Dieser war sehr routiniert im Umgang mit dem Publikum, doch die Witze auf Kosten von Minderheiten und die Spiele mit Dialekten waren zu vorhersehbar, um mich vom Hocker zu reißen. Gut gefiel mir dagegen seine Imitation von Louis de Funès, während das Fundstück der Woche (Zitate aus Kinderaufsätzen) aufgrund des Alters des Materials nur peinlich war.

Von den vier Gästen, die nach Wortlaut des Moderators zu Deutschlands besten Stand-Up-Comedians gehören, kannte ich nur genau einen: Robert Louis Griesbach (aus einer schlechten Fernsehserie). Seine Nummer war nett, ohne Höhepunkte oder Schwächen. Serpil Pak, eine Deutsch-Türkin aus Neukölln, war zwar wunderbar selbst-ironisch, aber trotzdem nicht komisch. Und der erste Auftritt von Heino Trusheim hatte an keiner Stelle die Qualität, die man von einem der besten Comedians Deutschlands erwarten könnte.

Dafür entschädigte die letzte Nummer mit Matthias Jung. Der auf der Maddin-Welle schwimmende studierte Medienpädagoge überzeugte durch ein abwechslungsreiches Programm, das sich hier und da zwar Anleihen bei bekannten Stoffen nahm, aber nach dem mittelmäßigen Vorspiel endlich das gesamte Publikum zum Lachen brachte. Nach zwei Stunden inklusive einer viertelstündigen Pause war die Show dann pünktlich 22Uhr zu Ende.

Im versprochenen Vergleich des QCC zu LSD prallen zwei Welten aufeinander. Auf der einen Seite die Hochglanz-Produktion im Friedrichstadtpalast, sehr professionell in der Präsentation und auf der Gegenseite die alternativ angehauchte Übungsbühne in einer Kneipe, die mit Verspätung begann und bei der nicht alle Auftretenden immer pünktlich waren. Hier Entertainer, die in den engen Grenzen der Stand-Up-Comedy ihren eigenen Weg suchen (aber nicht immer finden), da die ebenso zielsicheren Vorträge mit der einzigen Vorgabe, unterhaltsam zu sein für das typische Prenzlauer-Berg-Publikum und den Anspruch der Vorlesenden zu genügen. Am Ende hat wohl jede der beiden Shows ihr Zielpublikum erreicht, ich zähle mich dabei zu den LSD-Anhängern. Aktuelle Themen, keine Woche die selbe Show, dazu der unschlagbare Preis sind nur drei Gründe für mich. Wenn nur im Januar nicht ausgerechnet [Rainald Grebe](/blog/2008/11/16/als-wetter-noch-kein-klima-war/) im QCC auftreten würde...
