---
title: "In time"
date: "2011-12-14T22:18:22"
categories: [gesehen]
---

*USA (2011)
Regie: Andrew Niccol
Darsteller: Justin Timberlake (Will Salas), Amanda Seyfried (Sylvia Weis), Cillian Murphy (Timekeeper Raymond Leon), Vincent Kartheiser (Philippe Weis), Johnny Galecki (Borel), Olivia Wilde (Wills Mutter), Matt Bomer (Henry Hamilton) und andere Uhrenträger*
[Offizielle Homepage](http://www.intime-derfilm.de/)

In einer fernen Zukunft hat sich die Menschheit mit Hilfe der Gentechnik so weit entwickelt, dass das Altern aufgehalten werden konnte. Alle Menschen wachsen und entwickeln sich nur noch 25 Jahre lang und behalten danach ihr Aussehen - so sie denn genügend Zeit haben. Denn die Zeit ist als Währung an die Stelle von Geld getreten, und jeder Mensch trägt am Unterarm eine digitale Uhr, die sein Zeitkonto anzeigt und damit die Menge der ihm verbleibenden Zeit. Läuft diese Uhr ab, stirbt der Mensch.

Doch trotz der Chance, praktisch ewig zu leben, profitiert nicht die gesamte Bevölkerung von diesem Fortschritt. Ganz im Gegenteil ist die soziale Spaltung der Gesellschaft so weit fortgeschritten, dass die Menschen je nach Zeit auf dem Konto in Zeitzonen aufgeteilt sind, die streng voneinander abgeschottet werden. Die Timekeepers, eine Art Polizei, sorgt dafür, dass nicht zu viel Zeit die Zonen wechselt, und zementiert damit die sozialen Verhältnisse.

Will Salas ist in einer der ärmsten Zeitzonen aufgewachsen. Jeden Tag erarbeitet er sich in einer Fabrik die Zeit, um einen weiteren Tag das Überleben zu sichern - auf seiner Uhr sind selten mehr als 24 Stunden zu sehen. Als er von einem Fremden, der kurz danach Selbstmord begeht, einhundert Jahre gutgeschrieben bekommt, macht sich Will auf in die Zeitzone der Reichen, deren Überfluss er kaum glauben kann. Dort lernt er Sylvia kennen, deren Vater eine wichtige Zeitbank führt und die sich deshalb noch nie Gedanken um die Zeit auf ihrer Uhr machen musste. Als die Timekeeper Will aufspüren und zurück in seine Zeitzone bringen wollen, nimmt er Sylvia als Geisel und entführt sie in seine Zeitzone...

Mit *In time* entwirft Andrew Niccol, der schon für *Gattaca* verantwortlich zeichnete, erneut eine interessante Zukunftsvision. Doch sein neuer Film wird vermutlich nie den Status seines Erstlings erringen, zu sehr bedient er sich in seinem Drehbuch bei Filmklassikern von *Metropolis* (die Arbeitsbedingungen in Wills Fabrik) über *Robin Hood* bis *Bonnie und Clyde* (der Überfall auf die Zeitbank). Man spürt förmlich in jeder Szene des Films, wie Niccol ein Statement gegen die immer weiter aufklaffende soziale Schere setzen will und dabei seine Charaktere etwas aus den Augen verliert. Dass sich Will und Sylvia ineinander verlieben werden ist schnell klar, doch *In time* schafft es nicht zu vermitteln, wie dies passiert. Da der Film gleichzeitig noch eine Verfolgungsjagd durch den Timekeeper - Cillian Murphy in Lederkluft ist deutlich unterfordert - mit einer unmotivierten Vatergeschichte verknüpft, ist einfach zu wenig Zeit für eine vernünftige Figurenentwicklung vorhanden.

Überzeugend ist dagegen die Grundidee von *In time*, die aber akzeptiert werden muss. Wer schon die zu Beginn aus dem Off propagierte Prämisse in Frage stellt, wird mit dem folgenden Film nicht glücklich. Und verpasst dabei ein wunderbares Gedankenexperiment, das neben vielen Wortspielen mit "Zeit" und kleinen Details im Hintergrund (99-Sekunden-Shop) vor allem durch seinen Gesellschaftsentwurf besticht.

Nichts ist erschreckender als zu sehen, wie die immer am Limit kalkulieren müssende Mutter von Will stirbt, weil die Busgesellschaft ihre Preise erhöht hat. In der heutigen Gesellschaft bedeutet kein Geld zu haben noch lange nicht den Tod, doch wenn man Geld und Zeit gleichsetzt ändern sich plötzlich die Verhältnisse hin zu denjenigen Kräften in der Gesellschaft, die über die Zeit bestimmen. Es gibt schließlich keine besseren Arbeitnehmer als diejenigen, die nicht mehr streiken können, weil sie keinen Tag ohne ihr Gehalt in Form von weiteren 24h Lebenszeit auskommen können.

Dieses Abhängigkeitsverhältnis ist Sozialdarwinismus extrem, in dem nicht nur mit allem Lebensnotwendigen gehandelt wird, sondern auch das Leben selber zur Ware geworden ist. Und ist dieses System erst einmal etabliert, kann man es wunderbar kontrollieren und somit die Gesellschaft zum Stillstand bringen, wie der Film so eindringlich ausführt.

Im Gegensatz zur Visions des Films hat die Ausstattung bei mir gemischte Gefühle hervorgerufen. Auf der einen Seite malen die scheinbar endlosen Betonflächen der leeren Highways mit ihren Sportwagen und Limousinen im Retrolook das Bild einer stagnierenden, rückwärtsgewandten Luxusgesellschaft. Dazu passen die kalten Farben, in denen die Szenen in der Zeitzone der Reichen gehalten sind, und die im Kontrast zu den warmen Tönen der Armensiedlung stehen. Diese Differenzierung der Zeitzonen setzt sich fort bis hin zu den Frisuren, wo Amanda Seyfried besonders auffällt - wenn auch negativ.

Doch den vielen passenden Details stehen andere Aspekte gegenüber, die nicht zu Ende gedacht wurden oder einfach nur oberflächlich behandelt werden. So sterben im Film einige Figuren, weil ihre Uhr abgelaufen ist. Diese Menschen fallen einfach dort, wo sie sich gerade befinden, tot um. Doch gleichzeitig sind die Straßen leer und aufgeräumt, was genauso wenig passt wie dass die Hochhäuser in den reicheren Zeitzonen stehen und die Armenviertel nur eine niedrige Bebauung haben. In das durchwachsene Bild passt auch, dass ich gefühlt in 90% der Außenszenen immer wieder wieder dieselbe Brücke aus L.A. aus verschiedenen Blickwinkeln sehen musste.

Fazit: *In time* funktioniert als Film eher schlecht als recht. Den Figuren nimmt man ihre Entwicklung nicht ab, weil die Handlung zu viele Baustellen aufreißt und vielen interessanten Details stehen Ideen gegenüber, die nicht zu Ende gedacht wurden. Wer jedoch gesellschaftliche Gedankenspiele mag, sollte ruhig einen Blick wagen, denn die entworfene Zukunftsvision hat ihre Reize, die zudem optisch ansprechend verpackt sind.
