---
title: "Scoop - Der Knüller"
date: "2009-08-22T01:10:37"
categories: [gesehen]
---

Ich mag Woody Allens Filme. An *Scoop* gefällt mir zum Beispiel der romantisch verklärte Blick auf die englische Upper Class und die wunderschöne und doch so falsche Darstellung Londons. Und nicht zu vergessen: Woody Allen spielt wieder selber mit, und davon lebt der Film. Das Traumpaar sind nämlich nicht Hugh Jackman und Scarlett Johansson, sondern der Altmeister und die Blondine. Während Woody in seiner bekannt verschrobenen Art einen Kalauer nach dem anderen herunterstottert, ist Frau Johansson nicht nur Stichwortgeberin, sondern spielt mit sichtbarer Freude die schamlos übertriebene Rolle der naiven Journalistikstudentin. Während Jason Biggs in *Anything else* auf schwache Art und Weise versuchte, Allen zu kopieren, setzt Johansson mit Erfolg alles daran, die Dialoge funktionieren zu lassen. 

Und diese sprühen nur so vor den klassischen Zutaten. Egal ob das Judentum, Amerikaner oder neurotischer Versager, Selbstironie war schon immer die Stärke von Allen. Gut, der Film wirkt manchmal als hätte Woody Allen übrig gebliebene Ideen aus seinen letzten Filmen zu einem neuen zusammengesetzt, doch ich wurde wirklich gut unterhalten, und das zählt am Ende.
