---
title: "Der Ghostwriter oder Wie ein Ende einen ganzen Film zerstören kann"
date: "2010-12-26T23:55:52"
categories: [gesehen]
---

Dieses Spätwerk von Roman Polanski ist eigentlich ein Politthriller der alten Schule. Es wird viel Atmosphäre über die Musik erzeugt, die auf Hochglanz polierten Bilder und die kühlen Farben erzeugen eine Stimmung der ständigen Gefahr und die sicherlich gewollten Parallelen der Hauptfigur Adam Lang zu Tony Blair geben dem Film eine Aktualität, die manchmal vergessen lässt, in wie vielen Variationen diese Geschichte bereits erzählt wurde.

Damit könnte ich als Zuschauer gut leben. Fast zwei Stunden lang habe ich die Nachforschungen des Ghostwriters von Adam Lang verfolgt, um ihn schließlich herausfinden zu sehen, dass die CIA und damit die USA über Jahrzehnte die britische Politik mehr oder weniger direkt beeinflusst haben. So weit nicht unspannend, aber auch nicht spektakulär (wer hätte denn das Gegenteil behauptet?); eben genau in den Film passend. Dann wird Adam Lang erschossen, und theoretisch ist *Der Ghostwriter* damit zu einem Ende gekommen, das zu ihm passt. Das Rätsel ist gelöst und gleichzeitig die Gefahr gebannt, und alle sind glücklich dass die Situation überstanden wurde.

Aber leider meinten Regisseur Polanski und Drehbuchautor Robert Harris es zu gut mit ihrem Film und mussten unbedingt noch einen großen Knall am Ende einfügen. Und noch einen Zweiten. Und beide sind doof. Der erste Knall verschiebt die schon längst gegebene Auflösung einfach auf einen anderen Charakter, und dieser ist ganz überrascht, dass der leichtgläubige Ghostwriter doch noch auf den richtigen Trichter gekommen ist - durch einen codierten Hinweis seines Vorgängers. So einen schlechten Storytwist wie in Spionagethrillern des Kalten Krieges hat der ansonsten um Authentizität bemühte Film einfach nicht verdient. Und als wäre dies nicht genug hat Polanski während der Dreharbeiten noch einen Geistesblitz und lässt direkt eine Szene folgen, die so nicht im Drehbuch stand: Der Ghostwriter hat gerade entdeckt, wer wirklich für die CIA arbeitet, und wird deshalb auf offener Straße von einem Auto überfahren.

Dies passt so wenig in die Kontinuität des Films, dass es alle guten Ansätze des Films nur noch lächerlich wirken lässt. Das Ende zeigt den wahren Charakter des Films, er lässt die Hosten runter und offenbart seinen eigentlichen billigen Plot in schonungsloser Offenheit und ich als Zuschauer muss realisieren, dass ich mir die gesamte Zeit nur gewünscht habe, dass es nicht so ist. Vor 25 Jahren wäre *Der Ghostwriter* wohl schockierend gewesen, aber heute ist er nur ein auf Anachronismus, der dies zeitweilig gut zu kaschieren weiß.
