---
title: "Futurama - The complete Series"
date: "2009-05-08T23:46:49"
categories: [gesehen]
---

Nachdem ich schon die [vier](/blog/2008/04/10/futurama-benders-big-score/) [Futurama](/blog/2008/09/15/futurama-die-ara-des-tentakels/)-[Direct-to-DVD](/blog/2009/01/31/futurama-benders-game/)-[Filme](/blog/2009/04/20/futurama-leela-und-die-enzyklopoden/) erworben hatte, konnte ich mich auch bei der Serien-Komplett-Box nicht zurückhalten. Die 72 Folgen kommen in einem Würfel daher, in dem die 15 DVDs in [einfachen Pappschubern](http://www.fox.de/dvd/futurama_complete_box_season_1_4_15er_disc-set_-12352/12352/) untergebracht sind, die man leider nur sehr schwer herausnehmen kann. Das hätte man auch glücklicher lösen können.

Wichtiger als die Verpackung ist jedoch der Inhalt, und da kann ich mich als Futurama-Fan nicht beschwerden. Die Bildqualität ist gut (vor allem wenn meine PS3 das Bild auf FullHD skaliert) und dank der originalen Tonspur kam ich endlich in den Genuss des ursprünglichen Witzes der Serie. Die Menüs der DVDs können da nicht mithalten: Die Schriftarten sind verpixelt und die Bedienung umständlich. Wenn man die Sonderausstattungen erreichen möchte, muss man erst den Umweg über eine Episode nehmen, erreicht jedoch immer dasselbe Menü.

Ab der dritten Staffel werden die DVDs dann besser. Es gibt statt langweiligen Storyboards entfallene Szenen, die Qualität der Menüs ist deutlich höher (keine JPEG-Artefakte mehr) und man muss sich nach einer Folge nicht erst Warnmeldungen in dreißig Sprachen ansehen, um weiterzuschauen. Besonders gelungen sind die Menüs der letzten Folgen, die gut den Stil der Serie aufnehmen. Witzig fand ich noch die enthaltene Werbung für die Box der ersten Staffel: "Available on DVD and Video" - das letztere Format ist inzwischen quasi ausgestorben.

Fazit: Fans der Serie können ohne zu Überlegen zugreifen; in besserer Qualität kann man alle Episoden momentan nicht erwerben. Doch geärgert habe ich mich über die Menüs und in die Benutzerführung auf den DVDs; die Verpackung macht einen ebenso billigen Eindruck. Es scheint, als hätte man die Boxen der einzelnen Staffeln einfach lieblos zusammengefasst, um zum Anlass der neuen Filme noch ein paar Exemplare abzusetzen. Zumindest passen Preis und Inhalt zueinander, so dass ich den Kauf nicht bereut habe.
