---
title: "Paulette"
date: "2013-07-22T20:01:48"
categories: [gesehen]
---

*Frankreich (2012)
Regie: Jérôme Enrico
Darsteller: Bernadette Lafont (Paulette), Carmen Maura (Maria), Dominique Lavanant (Lucienne), Françoise Bertin (Renée), André Penvern (Walter), Ismaël Dramé (Léo), Jean-Baptiste Anoumon (Ousmane), Axelle Laffont (Agnès), Paco Boublard (Vito) und andere Drogendealer*
[Offizielle Homepage](http://www.paulette-film.de/‎)

Die Achtzigjährige Paulette hat ein glückliches Leben hinter sich. Mit ihrem Mann führte sie eine erfolgreiche Pâtisserie, verbrachte die Urlaube mit der gemeinsamen Tochter an der See. Doch nach dem Tod des Mannes ging alles den Bach hinunter. Sie musste ihren kleinen Laden an Chinesen verkaufen und lebt nun von der Mindestrente in einem Problembezirk von Paris. Zu allem Überfluss hat ihre Tochter auch noch einen Schwarzen geheiratet - in Paulettes Augen sind die Ausländer das Problem allen - und im Speziellen ihres - Übels.

Als ihre Wohnungseinrichtung aufgrund von Mietrückständen gepfändet wird, ergreift Paulette die Initiative. Von ihrem Schwiegersohn bei der Drogenfahndung hat sie erfahren, dass mit Drogenhandel gutes Geld zu verdienen ist. Als per Zufall ein Päckchen Hasch in ihren Händen landet, macht sie dem örtlichen Drogenboss das Angebot, es für ihn zu verticken...

Schwarze Komödien sind eigentlich nicht typisch französisch, sondern eine Spezialität der britischen Nachbarn. Doch womit Paulettes verbittertes Mundwerk unentwegt um sich schießt, das ist bitterböse. Ihren Neffen nennt sie das Negerlein, den "Schlitzaugen" schiebt sie Kakerlaken unter und der dunkelhäutige Pfarrer, bei dem sie regelmäßig beichtet, "hätte eigentlich verdient, ein Weißer zu sein".

Das Drehbuch verfrachtet diese erzkonservative Frau nicht nur in ein Banlieue, wo sie fast ausschließlich von den verhassten Ausländern umgeben ist, sondern auch noch in die Rolle einer Drogendealerin. Diese Ausgangsbasis wird nach allen Regeln der Kunst ausgeschlachtet, von den ersten Versuchen der Drogenoma, das Haschisch zu portionieren und an den Junkie zu bringen, über die Auseinandersetzung mit den Platzhirschen im Viertel (eine Jugendgang) und den Wechsel auf Spacecakes als die gefahrlosere und gewinnbringendere Form des Drogenhandels. Zu der Konstruiertheit des Drehbuchs gehört weiterhin ein Schwiegersohn bei der Drogenpolizei, von dem sich Paulette anfangs noch Informationen zum Handwerk geben lässt und der gerne einmal mit seinem zwergenhaften Kollegen in ihrer Wohnung auftaucht, an dessen Tür die Kunden bald Schlange stehen.

Obwohl *Paulette* durchaus Probleme wie Altersarmut, der Banlieues und des Drogenhandels (bis hin zum Schulhof) anspricht, will er doch niemals richtig weh tun oder gar die Ursachen und Auswirkungen näher beleuchten. Die Drogen sind ausschließlich weich und ihr Konsum hat höchstens lustige Folgen, die Drogenabhängigen sind harmlose Kiffer und ihre Dealer kleine Jungs, die nur ein wenig Essen benötigen. Hinter all den harten Worten versteckt sich eine Komödie klassischen Zuschnitts mit einem fantastisch-verträumten Ende, welches ausschließlich die Probleme von Paulette löst - die restlichen Konflikte lösen sich quasi in Luft auf.

Was den Film sehenswert macht ist also sein konsequent bitterböser Humor (auch nach ihrer Wandlung nennt Paulette ihren Enkel "kleine Buschtrommel") und wie er das Genre des Drogenfilms persifliert. Da gibt es zum Beispiel eine Szene, wo Paulette ihre jugendlichen Dealer-Konkurrenten an den Tisch bittet und mit Spacecakes zu einer Zusammenarbeit überredet. Dabei wandert die Kamera hinter den Rücken der Protagonisten um den Tisch herum, genau wie in *Reservoir Dogs*. Es sind diese unvermuteten kleinen Details und Referenzen, die am Ende aus *Paulette* mehr machen als nur den nächsten Komödienhit aus Frankreich.
