---
title: "Chihiros Reise ins Zauberland"
date: "2003-06-29T00:00:50"
categories: [gesehen]
---

*Japan (2001)
Regie: Hayao Miyazaki
Synchronstimmen: u.a Nina und Cosma Shiva Hagen*
[Offizielle Homepage](http://www.chihirosreise.de/)

Die Eltern der 10jährigen Chihiro ziehen um, und dem Mädchen bleibt nichts anderes übrig als mit ihnen die gewohnte Umgebung zu verlassen. Doch ausgerechnet während der Fahrt zum neuen Haus verfahren sich ihre Eltern und sie landen in einem scheinbar vollkommen verlassenen ehemaligen Vergnügungspark. Doch ein Restaurant scheint noch offen zu haben, und während sich Vater und Mutter die Bäuche vollschlagen erkundet das Mädchen den Park. Als sie zurückkommt muss Chihiro feststellen, dass sich ihre Eltern in zwei fette, verfressene Schweine verwandelt haben und sie in einer Zwischenwelt gefangen ist, in der die Hexe Yubaba ein Badehaus für die vielen tausend japanischen Götter betreibt. Völlig verängstigt trifft das Mädchen auf den Jungen Haku, der ihr hilft, eine Arbeit im Haus zu bekommen, ohne die auch sie verhext werden würde wie die Eltern. Mit immer mehr Problemen wie dem Geist Ohngesicht oder dem Wiederfinden ihres und Hakus wahren Namens beschäftigt versucht sie verzweifelt, ihre Eltern zurückzuverwandeln...

Ich muss ja zugeben, dass ich der japanischen Zeichentrickversion Anime nicht abgeneigt bin. Und doch haben mich nur die sehr guten Kritiken und der Goldene Bär der Berlinale 2002 dazu bewegen können, diesen Film anzusehen, denn Werbung und Handlung vermitteln doch mehr den Eindruck eines Filmes für Kinder. Dementsprechend war etwa die Hälfte des Publikums in meiner Vorstellung im Alter von 0 bis 10 und auch die Werbung war an dieser Zielgruppe ausgerichtet (die späteste Vorstellung in unserem Cinemaxx war 17.30h - hier treffen offensichtlich Vorurteile und ökonomische Bedenken den selben Nenner).

Doch eins kann ich vorwegnehmen - niemand im Saal hatte das falsche Alter für diesen Film, denn das Wunderbare an ihm ist, dass er jede Altersgruppe anspricht und viele Dinge nicht explizit sagt, sondern viel mehr andeutet, so dass man hinterher seinen Kindern keine unangenehmen Fragen beantworten muss und trotzdem mehr mitnimmt als die Kleinen. Chihiros Reise versteckt sich ein bisschen hinter der alles umfassenden Fantasie, mit der diese Welt der Götterbadeanstalt dargestellt wird. Am Anfang stürzen alle diese seltsamen Figuren auf den Zuschauer genauso wie auf die Hauptdarstellerin ein, doch im Gegensatz zur Chihiro bekommt man vom Kinosessel aus die Welt nicht unter Kontrolle. Kaum denkt man dass man weiß wie es nun weitergeht, folgt eine neue Wendung in der Handlung und lässt alles ganz anders aussehen. Nichts ist wirklich gut oder böse, schön oder hässlich, sondern jede Figur hat viele verschieden Seiten, die man erst nach und nach kennen und verstehen lernt.

Doch während die Kinder sich in der vollkommen gewalt- und sexfreien Welt verlieren, werden Erwachsene die vielen Bilder des Films interpretieren. Da treffen sozialkritische Themen (alleine das Badehaus mit den mit Knebelverträgen (Wegnahme des Namens) ausgestatteten Dienern, reichen und reicheren Gästen und der im Keller versteckten Energieanlage) auf ökologische Themen (der Flussgott, der zum Matschgott mutiert und Haku, der als Fluss einbetoniert wurde), und mittendrin total verloren die kleine Chihiro, die ohne Vorbereitung in diese Welt geworfen eine ganze Weile und viel Unterstützung benötigt, um sich darin zurecht zu finden.

Die Bilder sind überaus realistisch verglichen mit anderen Animes; mit Chihiro lernt auch der Zuschauer nach und nach die Badeanstalt kennen und könnte sich problemlos darin zurechtfinden - und genauso wie das Mädchen stellt man sich auch die Frage, wohin der Zug nun eigentlich fährt oder was es mit der Stadt am Horizont auf sich hat. Der Regisseur / Drehbuchautor / Zeichner Hayao Miyazaki folgt dabei nicht den aktuellen Einflüssen des Animes, die mit scharfen Kontrasten und eingebundenen Computeranimationen arbeiten, sondern bleibt seinem seit Jahrzehnten etablierten Stil (z.B. die Zeichentrickversion von "Heidi" stammt von ihm) treu, die Bilder alle per Hand zu zeichnen und aquarellartig zu kolorieren. Dies wirkt sich vor allem positiv auf die Landschaft aus und verhindert, dass die Charaktere getrennt von der Umgebung betrachtet werden - denn diese hat immer einen Einfluss auf die aktuelle Handlung der Personen (oder Götter). Trotzdem wirkt der Stil etwas veraltet, passt sich aber somit dem Gesamteindruck an: Vordergründig ein fantasievoller Kinderfilm, aber mit vielen Details die zum Nachdenken anregen. Nur manchmal wünschte ich mir ich könnte japanisch lesen - außer den Stimmen und dem Titel läuft der Film in der Originalversion, d.h. es wurden keine der Schriftzeichen oder Schilder übersetzt (wobei z.B. das Spiel der Hexe mit dem Namen Sen und Chihiro garantiert auch unübersetzbar ist!).

Fazit: Ein Film für jede Altersgruppe, der hinter der fantastischen Geschichte viele Details und Anregungen für das ältere Publikum bietet - aber man muss sich auch auf den Film einlassen, der trotz eines Audi ein japanischer Anime, also ein Zeichntrickfilm, bleibt!
