---
title: "Nachruf auf Stanislaw Lem"
date: "2006-03-27T20:09:43"
categories: [gedacht,gefunden]
---

Heute ist der aus meiner Sicht beste Science-Fiction-Autor, [Stanislaw Lem](http://de.wikipedia.org/wiki/Stanislaw_Lem), im Alter von 84 Jahren gestorben.

Dank meines Vaters bin ich mit den Werken des in der DDR sehr beliebten Polen aufgewachsen. Anfangs nur fasziniert von den utopischen Fantasien, erkannte ich mit gewachsener Reife auch die philosophischen Aspekte, mit denen sich Lem in all seinen Büchern auseinandersetzte. Immer wieder wurden seine Helden mit ungewöhnlichen Situationen konfrontiert, bei deren Lösung sie nicht selten versagten - doch das Verhalten in diesen Situationen verriet viel über die Psyche der Menschen.

Die Kunst von Lem bestand darin, diese philosophischen Fragen durch technische und auch humoristische Elemente (Ijon Tichy) zu maskieren, so dass seine Bücher im sozialistischen Osten veröffentlicht werden konnten. Seit der politischen Wende erschienen folgerichtig nur noch philosophische Werke, denen jedoch aufgrund der fehlenden Ideen die Faszination der Romane und Kurzgeschichten abging.

Hiermit verneige ich mich vor dem großartigen Autoren Stanislaw Lem, der mit seinen Werken zu meiner Entwicklung beigetragen hat und empfehle seine Bücher allen denjenigen, die mehr von einem Roman erwarten als eine weitere Variation der immer gleichen Elemente.
