---
title: "Der Bergfried im Schloss Schkopau"
date: "2010-07-10T16:54:21"
categories: [gewesen]
---

Manchmal benötigt es ein Ereignis wie eine Hochzeit, um die eigenen Heimat kennenzulernen. Eine Freundin feierte gestern ihre kirchliche Trauung im Schlosshotel Schkopau, nur sechs Kilometer entfernt von der Hallenser Südstadt, in der ich meine Kindheit verbracht habe. Und so bin ich trotz der räumlichen Nähe zum ersten Mal im Schloss Schkopau gewesen, obwohl ich dachte, dass meine Eltern als fleißige Burgen- und Schlossbesichtiger mir bereits jedes Exemplar dieser Gattung in meiner Heimat gezeigt hätten.

Bei der im Rahmen der Hochzeitsfeierlichkeiten angebotenen Führung ergab sich zum Glück die Chance, den Bergfried des Schlosses zu besteigen, der mit seinen 3,5 m dicken Mauern auf die Geschichte des Schlosses als Trutzburg hinweist. Nur knapp 100 Stufen mit wechselnden Schritthöhen (vom Burghof aus gezählt) müssen überwunden werden, und schon eröffnet sich dem Besucher von der zinnenbewehrten Plattform ein Rundblick über Schkopau. Nach Westen dominieren das Chemie-Areal Buna und das Kraftwerk die Sicht und nach Süden reicht der Blick bis Merseburg. Im Norden und Osten dagegen hat sich die Saale-Elster-Aue ihr Grün erhalten können; neuerdings durchschnitten von der ICE-Trasse, für die [Deutschlands längste Brücke](http://de.wikipedia.org/wiki/Saale-Elster-Talbrücke) errichtet wird.

Durch das gute Wetter konnte ich problemlos den Petersberg am Horizont ausmachen und sogar das Kraftwerk Lippendorf südlich von Leipzig war erkennbar - die Lage gleicht die geringe Höhe des Turmes also gut aus. Allerdings ist der Bergfried im Gegensatz zum Hof des Schlosses nicht öffentlich zugänglich, da sich ein kleiner Tagungsraum darin befindet. Interessierte, die die Aussichtsplattform besteigen wollen, müssen somit entweder eine Führung beim Schlosshotel buchen oder den kleinen Saal für eine Veranstaltung mieten.
