---
title: "Trash auf der Berlinale"
date: "2012-01-31T21:20:04"
categories: [gefunden]
---

Es ist endlich soweit - seit heute ist nicht nur der [Wettbewerb der 62. Berlinale komplett](http://www.berlinale.de/de/presse/pressemitteilungen/alle/Alle-Detail_13460.html), sondern auch das vollständige und wie gewohnt total unübersichtliche [Programm](http://www.berlinale.de/de/programm/berlinale_programm/programmsuche.php) der 2012er Ausgabe der Internationalen Filmfestspiele von Berlin online. Nach dem ersten Überfliegen der Filme habe ich ein paar Favoriten in der Panorama-Sektion im Auge, wobei ich vor allem auf [Iron Sky](http://www.ironsky.net/) gespannt bin. Der Nazi-Trash-Sci-Fi-Film setzte von Anfang an auf eine direkte Ansprache und Einbeziehung der potentiellen Zuschauer über das Internet inklusive einer Teilfinanzierung durch Crowdfunding (dazu folgt später ein separater Artikel) und hat so bei mir über die Jahre eine Erwartungshaltung aufgebaut, die es nun zu befriedigen gilt. Etwas seltsam ist es schon, diesen Film auf der Berlinale zu sehen (die Weltpremiere findet im Friedrichsstadtpalast statt!), aber so gibt es einen Grund mehr, sich auf das Festival zu freuen.
