---
title: "Antichrist"
date: "2009-11-22T19:02:42"
categories: [gesehen]
---

*Halb Europa (2009)
Regie: Lars von Trier
Darsteller: Willem Dafoe (Er), Charlotte Gainsbourg	 (Sie)*
[Offizielle Homepage](http://www.antichristthemovie.com/)

Lars von Trier als Mitunterzeichner der [Dogmaregeln](http://de.wikipedia.org/wiki/Dogma_95) gilt eigentlich als Vertreter der realistischen Art von Film; seine Filme *Dogville* und *Manderlay* waren so reduziert, dass sie fast ohne Kulissen mit nur auf den Boden gemalten Umrissen von Gebäuden auskamen. Doch mit *Antichrist* hat von Trier nun einen Film gedreht, der sich von diesen Grundsätzen abwendet. Nicht überraschend, wenn man am Ende des Films liest, dass dieser [Tarkowski](http://de.wikipedia.org/wiki/Andrei_Arsenjewitsch_Tarkowski) gewidmet ist. Denn gerade Tarkowski vertrat in seinen Werken gerne die entgegengesetzte Meinung zu von Trier: Die Bilder sollen neue Einblicke gewähren und nicht nur die Realität abbilden; ein starker Symbolismus und viele Variationen in der Zeitdarstellung prägten seine Filme.

*Antichrist* beginnt deshalb auch mit einer Serie von in schwarz-weiß gehaltenen Einstellungen in extremer Zeitlupe (ähnlich wie in [The Fall](/blog/2009/08/03/the-fall/)), die schon einmal das Motto für den restlichen Film vorgeben: Sex und Gewalt in ungewohnt expliziter Darstellung. Während *Er* und *Sie* sich lieben - Namen werden nicht genannt - öffnet der kleine Sohn des Paares die Tür seines Kinderbettes, klettert auf die Fensterbank und stürzt in den Tod.

*Sie* kann dieses schockierende Ereignis nicht überwinden und Konflikte brechen zwischen den beiden Elternteilen hervor. *Er*, von Beruf Psychotherapeut, versucht deshalb seine Frau mit einer Therapie zu heilen und fährt mit *Ihr* in das Haus im Wald, in dem *Sie* den letzten Sommer zusammen mit dem Kind verbrachte. Dort scheint sich erst *Ihre* Stimmung zu bessern, doch dann entdeckt *Er*, weshalb *Sie* in diesem Sommer *Ihre* Doktorarbeit nicht zu Ende geschrieben hat. *Sie* sah die umgebende Natur als den Teufel an und sich selber sowie alle Frauen als die Gehilfen des Antichristen. Als Beweis dieser Aussage misshandelte *Sie* den Sohn, indem *Sie* ihm die Schuhe falsch herum anzog, und hat es nun auf *Ihn* abgesehen.

Als Ausdruck dieser etwas abstrusen Handlung findet von Trier sehr ausrucksstarke, aber auch drastische Bilder. Er lässt den (deutschen) Wald als Manifestation der Natur durch Zeitlupen, Nebel, dunkle Farben und einen zu vordergründig Spannung aufbauenden Soundtrack bedrohlich erscheinen und fährt mit einem Reh, einem Fuchs und einem Raben die drei fiktiven Bettler als Boten der Geschichte auf. Aus *Ihren* Recherchen entnommen erscheinen sie jeweils an den Übergängen der vier Kapitel in unnatürlicher Form (das Reh mit einer Fehlgeburt, der Rabe als nicht zu tötender Verräter und der sich selbst zerfleischende Fuchs) und am Schluss sowohl als Sternbilder als auch in der tierischen Version, um das Ende zu begleiten. Surrealistische Symbolik für das hintergründige Handlungsgerüst, mag man meinen.

Doch von Trier treibt die Konsequenz aus diesem Gedankengang bis ins Extrem. Die auch in ihrer Nacktheit den Spagat zwischen depressiver Passivität und unglaublicher Konsequenz meisternde Charlotte Gainsbourg muss Willem Dafoe einen Holzklotz in die Weichteile rammen, ihn danach so lange masturbieren, bis er Blut ejakuliert und dann einen Schleifstein mit einer rostigen Schraube an dessen Bein befestigen. Dieser Gewaltexzess gipfelt in einer Szene, in der *Sie* sich die Klitoris abschneidet und *Er* *Sie* schließlich erwürgt. Alle diese Bilder kann man ebenfalls als abstrakte Symbole ansehen, doch so drastisch und realistisch inszeniert konnte ich mich manchmal nur abwenden von diesem [Torture Porn](http://en.wikipedia.org/wiki/Torture_porn#.22Torture_porn.22).

So fällt eine Interpretation ungewöhnlich schwer. Alles deutet darauf hin, dass *Ihre* Ansicht korrekt ist. Die Natur wird als Bedrohung dargestellt (Eicheln regnen auf das Haus, Zecken befallen *Seine* Hand, die Bettler werden verstümmelt dargestellt) und die animalische Form der Fortpflanzung in Form *Ihrer* (Sex-) Lust und *Seiner* männlichen Ausstrahlung und Präsenz als Mittel zur Aufrechterhaltung dieser teuflischen Ordnung. Deshalb müssen die Geschlechtsorgane als direkte Werkzeuge der Schöpfung zerstört werden und natürlich übernimmt die Frau diese Aufgabe. Diese Umkehrung der kirchlichen Symbolik drückt sich auch im Namen *Eden* für die alles andere als paradiesische Waldhütte wieder, wobei die Frau als Ursache der Vertreibung aus dem Paradies wiederum ein der Bibel entnommenes Bild ist. Allerdings wird die Rückkehr nach *Eden* nicht etwa zur erhofften Therapie, sondern führt zu einer noch größeren Katastrophe - der Teufel steckt nicht etwa im Detail, sondern im Paradies.

Damit ist natürlich noch nicht das handlungsgebende Element des Kindstotes und *Ihrer* Depression erklärt, obwohl *Sie* die Frucht der als Gefahr wahrgenommenen Natur scheinbar nicht so liebte, wie man es von einer Mutter erwartet. Hat *Sie* vielleicht sogar in ihrem Wissen um des Kinds nächtlicher Unruhe und seiner Fähigkeiten, das Gitter des Bettes zu öffnen, das Fenster mit Absicht offen gelassen und alles geplant?

Wie man es dreht und wendet - eine Interpretation, die meine Zustimmung findet, kann ich nicht entdecken. Vielleicht ist der Film wirklich nur der Ausdruck des kranken Geistes von von Trier, denn das Drehbuch hat er in einer Phase schwerster Depressionen geschrieben, und die schockierende Darstellung soll von dem halbgaren Inhalt ablenken.

Fazit: Weiterempfehlen kann ich *Antichrist* leider nicht. Zwar kann der Film eine sehr kunstvolle Bildsprache aufweisen, doch diese wird nur genutzt, um eine verworrene Handlung zu einem in seiner Darstellung sehr drastischen Ende zu führen. Wer die Zerstörung von Geschlechtsorganen als reine Symbole betrachten kann, findet vielleicht Interesse an von Triers Schocktherapie - alle anderen sollten sich den Film nicht antun.
