---
title: "Die blaue Grenze"
date: "2008-08-17T21:05:07"
categories: [gesehen]
---

*Deutschland/Dänemark (2005)
Regie: Till Franzen
Darsteller: Antoine Monot, Jr. (Momme Bief), Beate Bille (Lene), Dominique Horwitz (Kommissar Poulsen), Hanna Schygulla (Frau Marx), Jost Siedhoff (der alte Bief), Sebastian Schultz (Morten), Jens Münchow (Teddy), Ole Hedegaard (Dänischer Grenzer) und andere Grenzgänger*
[Offizielle Homepage](http://www.dieblauegrenze.de)

So schnell kann es gehen: Nach [Auf der anderen Seite](/blog/2008/07/16/auf-der-anderen-seite/) gleich der nächste Film mit Hanna Schygulla, die sich ansonsten ja rar macht. Dabei ist mir diese Perle von Film erst jetzt bei der TV-Ausstrahlung aufgefallen. Aber besser spät als nie.

Die Handlung dreht sich rund um Momme, dessen Vater zu Beginn des Films stirbt. Dies bringt den jungen Mann dazu, nach Flensburg zu seinem Großvater zu fahren, wo er die Dänin Lene kennenlernt. Zusammen geraten sie in dier Nacht auf ein Polizeirevier und in ein Verhör mit Kommissar Poulsen, der eigentlich gerade beurlaubt wurde. Während sich die Wege von Momme und Lene nach dieser Nacht trennen, lernt der Kommissar seine neue Nachbarin Frau Marx kennen, die ihn sehr seltsam ansieht. Am Ende wird es alle in Dänemark wieder zusammenführen.

Der Film lebt von seiner herrlichen nordisch-kalten Ausstrahlung. Diese findet Ausdruck in der herbstlich-kargen Landschaft rund um die Flensburger Förde, dem trockenen Humor und dem grandiosen Soundtrack ebenso wie in dem ruhigen Erzähltempo. Thematisch liegt der Schwerpunkt auf einer mystischen Romantik, die sich mit dem Tod beschäftigt. Dies beginnt schon mit den einleitenden Worten aus dem Off, die von einer Zeit erzählen, als die Toten noch zusammen mit den Lebenden auf der Erde weilten. Und Erfahrungen mit dem Tod hat fast jede Figur im Film gemacht. Momme hat den Vater verloren, sein Großvater die Frau. Lenes Eltern sind beide tot und Frau Marx hat den Mann verloren. Zudem wird Momme fast sterben und Lenes Tante träumt von dem Land zwischen Leben und Tod.

Alles in diesem Film spielt sich an so einer Grenze ab, sei es nun zwischen Tod und Leben, Deutschland und Dänemark oder Land und Wasser in der Flensburger Bucht. Und an diesen Grenzen können sich Dinge ereignen, die in der traumgleichen Entwicklung der Handlung auf eine Ende hinauslaufen, dass den Namen vollendetes Happy-End verdient. Doch viel wichtiger sind dem Film seine Figuren und deren Odyssee; viele versuchen lange erfolglos, die eine oder andere Grenze zu überschreiten, andere müssen erst überzeugt werden, sie zu übertreten.

Wer also keine Probleme mit einer mystischen Handlung in Verbindung mit dem trockenen Humor der Norddeutschen hat, der sollte sich *Die blaue Grenze* auf jeden Fall einmal ansehen. Die genannten Elemente verbinden sich zu einer Einheit, die mir sehr gefallen hat und die ich hiermit jedem ans Herz lege.
