---
title: "Das stille Mädchen"
date: "2008-02-15T00:47:30"
categories: [gelesen]
---

*von Peter Høeg,
erschienen im Carl-Hanser-Verlag, ISBN 978-3-446-20824-0, 24,90€*

Ich kann Stille nicht ertragen. Ich brauche ständig eine starke Geräuschquelle um mich herum, um mich wohl zu fühlen. Denn wenn es still ist, hört man plötzlich viele Geräusche, die einem sonst nie auffallen: Das Haus wie es knircht und arbeitet, die Straße außerhalb der Doppelglasfenster oder gar die Vögel davor. Als Mann kann ich mich aber höchstens mit einer Geräuschquelle gleichzeitig beschäftigen, also läuft bei mir ständig Musik oder der Fernseher, auch beim Lesen oder früher beim Lernen.

Für den Clown Kasper Krone dagegen, Kindertherapeut und Held des Buches von *Smilla*-Autoren Peter Høeg, ist die absolute Stille ein Lebenstraum. Seit einem Unfall in der Kindheit hat er ein unglaublich sensibles Gehör, das feiner als alle Messinstrumente ist und Menschen und deren Gefühle am Klang unterscheiden kann. Doch Kasper sehnt sich nach der Ruhe und Entspanntheit, die ihm eine Welt ohne Geräusche verspricht, da er seine Ohren nicht abschalten kann.

Als eines Tages das Kind KlaraMaria zu ihm in die Therapie gebracht wird, das in seinem Inneren von der so ersehnten Stille ausgefüllt wird, scheint seine Suche beendet. Doch leider ist das Mädchen irgendwie in die Fänge eines internationalen Verbrecherringes geraten, der in Kopenhagen mit Immobilien spekuliert, und Kasper steht kurz vor der Auslieferung an Spanien, wo er Steuern im großen Stil hinterzogen hat. Keine guten Voraussetzungen also, hinter das Geheimnis des Kindes zu kommen...

Die Stärke dieses Buches sind wie schon bei "Fräulein Smillas Gespür für Schnee" die spröden skandinavischen Charaktere. Kasper Krone ist ein sympatischer Außenseiter, der es in seinen 42 Lebensjahren und dank des Gehörs zu einiger Menschenkenntnis gebracht hat, diesen Vorteil jedoch meist schamlos ausnutzt. Er ist fasziniert von klassischer Musik und redet ständig von Bach und Gott der Herrin, der er seine Gabe verdankt. Seine Ansichten prägen das Buch und Peter Høeg nutzt die Gabe seines Helden ausgiebig, um mit kleinen philosphischen Diskursen die Seiten zu füllen. Kaspers zwischenzeitliche Lebensgefährtin Stine ist dazu der Gegenpol; wie Smilla ist sie geprägt von der rationalen Wissenschaft. Als Ingeneurin mit Schwerpunkt Seismologie liegt es an ihr, die theoretischen Fakten vorzutragen und durch den unterirdischen Teil der dänischen Hauptstadt zu leiten, die der heimliche Held der Geschichte ist (weshalb auch Auszüge aus dem Stadtplan auf die Innenseiten des Buchbandes gedruckt sind).

Neben den starken Hauptcharakteren fallen die Nebenrollen etwas ab. KlaraMaria weckt zu keinem Zeitpunkt im Buch überhaupt den Eindruck, ein Kind zu sein. Der Bösewicht Kain bleibt bis zum Ende einfach nur diffus. Und in der Terminatorin Gloria sammeln sich so ziemlich alle Eigenschaften, die Kasper irgendwann während der Handlung einmal benötigt. 

Verpackt sind diese Figuren in eine Geschichte um ein Erdbeben mitten in Kopenhagen und eine Gruppe von Kindern mit scheinbar übersinnlichen Fähigkeiten, hinter der die Kirche, Polizei und das organisierte Verbrechen her sind. Das in acht Teile gegliederte Buch springt dabei ständig zwischen vergangener und aktueller Handlung, so dass viele wichtige Punkte erst spät erwähnt werden. Dies führt zu einem extrem übertriebenen Finale, bei dem die vielen Handlungsstränge zu einem unglaubwürdigen Ende zusammengestrickt werden.

Schade, denn bis dahin hat mir das Buch wirklich gut gefallen. Nicht so gut wie "Fräulein Smillas Gespür für Schnee", aber viele sperrige Details links und rechts der sich schnell entwickelnden Geschichte und die trockene Erzählweise des alles andere als perfekten Helden sind genau das, was ich von Peter Høeg erwartet habe. Doch die letzten 30 Seiten zerstören den guten Gesamteindruck und so kann ich das Buch leider nicht uneingeschränkt weiterempfehlen.
