---
title: "Spektrum"
date: "2007-06-24T18:56:47"
categories: [gelesen]
---

*von Sergej Lukianenko,
erschienen bei Heyne, ISBN 978-3-453-52233-6, 14,00€*

Russische Science-Fiction hat eine lange Tradition. Zu Zeiten des kalten Krieges sollte sie den westlichen populären Zukunftsfantasien eine Alternative entgegenstellen und den Sieg des Kommunismus auch in diesem Bereich verbreiten - die meisten Autoren versteckten aber in ihren anspruchsvollen Werken viel der sonst untersagten Kritik am System. Nach dem Fall des eisernen Vorhangs entfiel plötzlich der Zwang, die Aussagen zu verkrypten, und damit fanden immer weniger Werke den Weg in den Westen, wo die meist anspruchslose amerikanische Science-Fiction dominiert.

Doch mit Sergej Lukianenko scheint sich dies zu ändern. Der erfolgreichste russische Film aller Zeiten, [Wächter der Nacht](/blog/2005/11/08/wachter-der-nacht/), weckte auch außerhalb Russlands Interesse an dem Autoren der Buchvorlage, und mittlerweile werden immer mehr seiner Werke in Deutschland veröffentlicht.

So auch "Spektrum", welches mir sehr gut gefallen hat. Aber nicht etwa, weil es in der Tradition der russischen SciFi steht, sondern weil es den popkulturellen Bogen zwischen Russland und dem Westen schafft. Der Held des Buches, Martin Dugin, ist zwar Russe von ganzem Herzen, nutzt aber auch die Möglichkeiten der Globalisierung, ob es nun um schottischen Single-Malt-Whisky oder französische Waterfall-Lautsprecher geht. Aber noch viel mehr ist es die Geschichte des Buches, welche viele bereits aus anderen Büchern oder SciFi-Serien bekannte Ideen aufgreift und zu etwas vollkommen Neuen mit einem angenehmen russischen Touch verbindet - eben die Idee der Popkultur. 

Die Erde ist dabei Teil eines großen Netzwerkes von Planeten, welche alle über die Stationen einer Schließer genannten Rasse miteinander verbunden sind und sofortiges Reisen innerhalb des Netzes erlauben. Wie dies funktioniert, weiß niemand, aber die Schließer verlangen als Wegezoll nur eine Geschichte, die sie noch nicht gehört haben und welche sie interessiert. Und da fängt es an - eine Idee wie die des galaxisweiten Netzwerken bekommt ein ganz neues Gefühl, wenn plötzlich das Mosaikstückchen der seltsamen Währung der Schließer ins Spiel kommt. So geht es dann das ganze Buch weiter. Die humanoiden Rassen und die vielen Theorien zum Hintergrund der Schließer kommen einem meist seltsam bekannt vor, doch jedes Mal wenn man scheinbar den Schlüssel zum Verständnis gefunden hat, wirft der Autor mit einem neuen Detail alles über einen Haufen.

[SPOILER]Dieser grundsätzliche Aufbau wiederholt sich sieben Planeten (= Teile) lang, wobei der Spannungsbogen vor jedem Teil ab-, und in diesem suksessive wieder aufgebaut wird. Gelangweilt habe ich mich auf keiner der rund 700 Seiten, doch das Ende war dann etwas enttäuschend, weil eben nicht wie gewohnt alles über einen Haufen geworfen wird, sondern der Leser erkennen muss, dass es die ganze Zeit gar nicht um das Schicksal der Galaxie ging.[/SPOILER]

Alles in allem aber ein empfehlenswertes Buch für alle SciFi-Fans, welche nicht den höchsten Anspruch erwarten, aber auf angenehm abwechslungsreiche Art unterhalten werden wollen.
