---
title: "Liebe statt Drogen"
date: "2008-10-18T21:08:32"
categories: [gewesen]
---

Hinter diesem [Namen](http://www.liebestattdrogen.de/) verbirgt sich eine der Berliner [Lesebühnen](http://de.wikipedia.org/wiki/Lesebühne), die versucht für den Spar-Eintrittspreis von nur drei Euro jeden Dienstag über zwei Stunden lang die etwa 40 bis 50 in die Kneipe [Lokal](http://www.lokal-berlin.de/) am Rosenthaler Platz passenden Gäste  zu unterhalten. Ich war diesen Dienstag mit ein paar Kollegen vor Ort und werde demnächst den Vergleich mit dem deutlich höhere Gebühren verlangenden [Quatsch Comedy Club](http://quatsch-comedy-club.de/berlin/) ziehen (ich habe jedoch eine Freikarte).

Doch zurück zu LSD. Passend zu der aktuellen Krise der Finanzmärkte drehten sich einige Texte um ebenjenes Thema, aber auch die üblichen Stoffe wie Selbstmord (*"Haben Sie schon einmal versucht, in ihrer Altbauwohnung einen Balken für den Strick zu finden?"*) und Müllmänner kamen zur Sprache. Einige der Vortragenden erinnerten anfangs an bekannte Comedians wie Johann König, doch zeichneten sich alle durch ihren eigenen Stil aus. Da nur Texte vorlesen auf die Dauer keinen Abend füllt, gab es zwischendurch zwei Liedbeiträge und als Gast einen [Luftballonkünstler](http://www.balloonmaestro.com/stage_performance), dessen Highlight ein Led-Zeppelin-Bass-Solo auf einer aus einem Ballon gezogenen Saite war.

Wer mutig genug ist, kann sich vorher für die Show anmelden und einen eigenen Text vortragen und bekommt sogar ein Freigetränk als Belohnung. Der Freiwillige dieser Woche hatte seine eigenen Fans mitgebracht, die dann leider die einzigen waren, die seine Darbietung witzig fanden. Zumindest konnte er frei vortragen und zeigte keine Nervosität oder Spur eines Lampenfiebers - ich hätte dies nicht zustande gebracht.

So war es ein sehr unterhaltsamer Abend, den ich nur weiterempfehlen kann. Man merkte den Vorlesern an, dass sie diese Bühne nicht aus Profitgründen betreiben (so viel Gewinn kommt bei diesem Eintrittspreis nicht heraus), sondern um sich auszuprobieren und aus Spaß an der Darbietung. Nur die späte Zeit (21:30h bis nach Mitternacht inklusive Pausen) wird mich leider davon abhalten, öfters diese oder eine der anderen Lesebühnen zu besuchen.
