---
title: "Mein Milestone 2 frisst Jelly Beans"
date: "2012-12-31T15:52:10"
categories: [gefunden,getan]
---

[Vor knapp einem Jahr habe ich noch glücklich vom offiziellen Gingerbread-Update](/blog/2011/12/03/mein-milestone-2-nascht-lebkuchen/) meines Motorola Milestone 2 berichtet. Aber lange sollte dieses Glück nicht anhalten, denn mit zunehmenden Alter bekam das Gerät immer mehr Macken. Waren die häufiger werdenden zufälligen Neustarts anfangs nur nervig, so wurden sie mit der Zeit zum Problem, als sie einige App-Einstellungen mit sich rissen und ich zum Beispiel den Kalender mit dem Exchange-Konto der Arbeit nicht mehr synchronisieren konnte - das Konto ließ sich weder editieren, noch löschen oder neu anlegen.

Zuletzt gab es immer mehr Freezes und halbstündige Neustart-Orgien, so dass ich zum Handeln gezwungen war. Da sich die Probleme genau zum Ablauf der Gewährleistung verschärften, war also die Zeit zum Rooten und Aufspielen eines Custom-ROMs gekommen. Dank der Linux-Basis von Android stehen weite Teile des Betriebssystems unter einer Open-Source-Lizenz und im Quelltext zur Verfügung. Ein guter Nährboden für die Moddingszene, so dass es sogar für mein zwei Jahr altes Handy noch gepflegte Portierungen gibt.

Die [Anleitung im XDA-Forum](http://forum.xda-developers.com/showthread.php?t=1827801) für ein Aufspielen eines aktuellen [Cyanogen-Mods](http://www.cyanogenmod.org/) ist einfach: Das Handy mittels SuperOneClick (was für ein Name für eine Software!) rooten, im Bootmenü ein Backup des Betriebssystems machen und danach das für das Milestone 2 angepasste [Cyanogen-ROM](http://code.google.com/p/cm-milestone2/downloads/list) aufspielen. Hinter dieser einfachen Prozedur verbirgt sich eine komplizierte Technik: Weil der Bootloader des Milestone nicht offen ist, und dieser nur von Motorola signierte Kernels lädt, muss mittels eines *2ndboot* genannten Verfahrens der Original-Kernel die gemoddete Software laden.

Das Ergebnis überzeugt bisher: Mein Handy läuft wieder stabil (und flüssiger als vorher), ich bin mit dem Jelly-Bean-Android 4.1.2 (Stand 10.10.2012) deutlich näher am aktuellen Entwicklungsstand und profitiere sogar vom einfachen Update-Mechanismus des Cyanogen-Mod. Also Ende gut, alles gut? Ich hoffe es, denn in Europa ist der Markt der Tastatur-Handys sehr übersichtlich - in diesem Jahr ist kein einziges neues Gerät erschienen. So lange sich daran nichts ändert, werde ich mein Milestone 2 behalten. Die Hardware - lässt man die [Tastatur-Probleme](http://www.teltarif.de/motorola-milestone-2-tastatur-serienfehler/news/43426.html) außen vor - ist schließlich noch immer ausreichend für meine Bedürfnisse, und selbst ohne weitere Updates sollte mir Jelly Bean ein weiteres Jahr Gnadenfrist geben.
