---
title: "Wächter der Nacht"
date: "2005-11-08T17:45:33"
categories: [gesehen]
---

Fantasy hat Hochkonjunktur, und der Kampf zwischen Gut und Böse wird nun auch in Russland ausgetragen. Dort soll ein mächtiger Held erscheinen, der mit seiner Wahl für eine der beiden Seiten den ewigen Kampf endgültig entscheiden wird. Bis dahin unterscheidet sich "Wächter der Nacht", der ersten Teil einer Trilogie, nicht großartig von anderen Werken seines Genres. Doch dieses russische Märchen vereint auf bislang ungeahnte Art und Weise Aspekte der klassischen Fantasy wie Hexen, Vampire und Gestaltwandler mit der heutigen Zeit. Sie alle leben unbemerkt unter den Menschen und haben ein Abkommen unterzeichnet, das die ewigen Kriege zwischen Hell und Dunkel unterbindet. Trotzdem beäugen sich beide Seiten sorgsam, um den zerbrechlichen Waffenstillstand zu wahren.

Die Hauptperson des Films, Anton Gorodetsky, hat vor 12 Jahren bei einer Hexe um Hilfe in der Liebe vorgesprochen. Dies hatte zur Folge, dass er seiner übersinnlichen Fähigkeiten bewusst wurde und nun ein "Hüter des Lichts" ist, die die "unlizensierten" Anderen der dunklen Seite aufspüren. So kommt es, dass er den jungen Yegor vor einer Vampirin schützen muss ohne zu wissen, dass dies sein Sohn ist. 12 Jahre zuvor hatte die Hexe ihn mit einer Lüge dazu gebracht, den ungeborenen Sohn im Leib der Mutter von ihr umbringen zu lassen. Dies misslang zwar dank dem Eingreifen der "Wächter der Nacht", doch die Tatsache wird sich trotzdem auf die Entscheidung des kommenden Heldens auswirken, denn nichts anderes ist Yegor.

Eine ansprechende Geschichte bietet also "Wächter der Nacht" - doch leider macht der Film nicht viel aus diesem Potential. Zu wenig wird der Zuschauer über die Hintergründe der Welt aufgeklärt, und zu unsicher windet sich die Storyline durch den Film. Die Nebenhandlung um die sich selbst verfluchende Svetlana implodiert quasi mit einer simplen Auflösung und in der Hauptgeschichte geht es gegen Ende des Film viel zu schnell und chaotisch voran, als dass man die Entscheidungen vor allem von Yegor nach vollziehen könnte.

Was den Film allerdings sehenswert macht sind die optischen Effekte. Die Gestaltenwandler, das Zwielicht und viele andere Elemente sind auf eine ungewohnt neue, aber faszinierende Art umgesetzt, so dass man sich kaum satt sehen kann. So eine optische Brillianz lieferte zuletzt die "Matrix" ab, mit der dieser Film oft verglichen wird.
Doch gute Effekte allein machen noch keinen guten Film, und so muss sich "Wächter der Nacht" vorwerfen lassen, neben all der Innovation das Geschichten-Erzählen etwas stiefmütterlich behandelt zu haben. Schade, denn das Potential dazu ist da. Vielleicht schafft es ja der zweite Teil der Trilogie, mehr aus dem Stoff heraus zu holen.

[Offizielle Homepage](http://www.waechter-der-nacht.de/)
