---
title: "Ruhm"
date: "2009-02-09T20:44:01"
categories: [gelesen]
---

*von Daniel Kehlmann,
veröffentlicht von Rowohlt, ISBN 978-3-498-03543-3, 18,90€*

*Ein Roman in neun Geschichten* ist der Untertitel des neuen Buches von Daniel Kehlmann, von dessen *Die Vermessung der Welt* ich so begeistert war. Und wenig überraschend findet man auch neun Kurzgeschichten vor, die alle im selben Kosmos spielen und durch einzelne Charaktere lose miteinander verbunden sind. Da ist der Techniker Ebling, der auf seinem neuen Handy plötzlich Anrufe bekommt, die für jemanden ganz anders bestimmt sind und durch die er immer mehr in die Rolle des scheinbar berühmten Vorbesitzers der Handynummer schlüpft. Dieser ist, so erfährt der Leser in der zweiten Geschichte, der berühmte Filmstar Ralf Tanner, der aus der Lust heraus an einem Wettbewerb für Doubles teilnimmt und sich selber imitiert. Doch je öfter er sich diesen Spaß erlaubt, desto mehr scheint er die Verbindung zu sich selber zu verlieren, bis er eines Tages feststellen muss, dass jemand anders seinen Platz in der Rolle des Schauspielers eingenommen hat.

Weiterhin lernt man Leo Richter kennen, einem ebenso anerkannten wie verschrobenen Autoren von Kurzgeschichten, der mit Elisabeth, einer Ärztin für Krisengebiete, auf Lesereise durch deutsche Botschaften in Südamerika ist. Neben seiner berühmtesten Schöpfung, Lara Gaspard (ebenfalls Ärztin), ist er vor allem für eine Geschichte über Sterbehilfe in der Schweiz bekannt. Eine andere Form des Suizids hat dagegen Miguel Auristos Blancos gewählt, der sich nach dem Schreiben vieler erfolgreicher Lebenshilfe-Bücher schließlich eine Kugel in den Kopf jagd. Und als wäre dies an Autoren nicht genug, begleitet der Leser auch noch die auf Krimis spezialisierte Maria Rubinstein in ein asiatisches Land, wo sie aufgrund der Verkettung unglücklicher Umstände von ihrer Reisegruppe getrennt wird und sich plötzlich ohne Personalien allein in der Fremde wiederfindet.

Zum Schluss macht das Buch einen Bogen zurück zum Anfang, wenn es um den Internet-Junkie Mollwitz geht, dessen Leben sich hauptsächlich in Celebrity-Foren abspielt und der in der Abteilung für die Handynummernvergabe arbeitet. Sein Chef dagegen hat gleich zwei reale Leben: Eine Frau mit Kind in München und eine Geliebte in Hannover; und er verzweifelt immer mehr daran, diese auf Lügen aufgebaute Konstruktion von Wirklichkeit aufrecht zu erhalten, während sein Arbeitsleben auseinanderbricht...

*Ruhm* ist die Überschrift über dieses Buch, und Ruhm ist oberflächlich betrachtet auch das Hauptthema. Es geht um die Auswirkungen von Ruhm auf die Persönlichkeit und welche Folgen es haben kann, eine Berühmtheit zu kennen. Es werden aber auch die Grenzen von Ruhm aufgezeigt, ob es nun um die Austauschbarkeit aufgrund des öffentlichen Bildes ist (Ralf Tanner) oder die Einsicht, nur in einem begrenzten Raum überhaupt bekannt zu sein.

Des weiteren fällt natürlich die Häufung von Autoren als Figuren der Geschichten auf. Lesereisen, Belästigung durch Fans, Ideenfindung, Selbstreflektion - Daniel Kehlmann verarbeitet hier sicherlich eigene Erfahrungen, ohne gleich autobiografisch zu werden. Doch gerade die nahtlosen Übergänge zwischen Buchrealität und Geschichten, die er den geschilderten Autoren in die Feder legt, führen zum wichtigsten Thema in *Ruhm*, dem Verwischen der Grenze zwischen Fiktion und Realität.

Alle Charaktere haben nämlich mindestens einmal das Gefühl, dass die aktuelle Situation ihnen irreal verkommt. Die Gründe dafür sind mannigfaltig: Mollwig ist zu sehr in die ihn anerkennende Welt des Internet versunken, sein echtes Leben muss sich danach richten und so verwundert es nicht, dass er sich plötzlich so verhält, wie sich andere im Netz aufführen: Er verwüstet Hotelzimmer, belästigt Leo Richter und ist generell nicht in der Lage, seinen Konsum an Alkohol und vor allem Essen korrekt einzuschätzen. Er ist besorgter darüber, seine Anonymität im World Wide Web durch Angabe seiner IP-Adresse aufgegeben zu haben, als die gesellschaftlichen Regeln in der realen Welt verletzt zu haben.

Ebling dagegen schlüpft nur durch die Übernahme des Telefonnummer von Ralf Tanner in die viel spannendere Rolle des Filmstars; eine Erfahrung, die ihn schnell süchtig macht. Er bekommt Einfluss auf wildfremde Menschen und ändert durch kurze Handygespräche anderer Leute Leben. Die moderne Welt, so erfährt man, basiert auf der ständigen Verfügbarkeit ihrer Kommunikationsmedien, die schnellere Kommunikation als jemals zuvor ermöglichen, aber Nähe nur suggerieren. So kann man zwar zwei Beziehungen managen und mit der einen Frau das Zimmer teilen, mit einer anderen telefonieren, doch die beiden Leben müssen sich immer noch ein reales Leben teilen; die jeweils fiktiven Hälften zu koordinieren erfordert viel Geschick und Aufwand.

Am Ende sind es immer Rollen, die eingenommen werden, und man muss wissen, wann man aus einer herausschlüpft und in eine andere hinein. Dieses Problem bekommt auch Ralf Tanner, als er nach und nach mit einem Double die Rollen und damit das Leben tauscht. Am Ende weiß er nicht genau, ob er nicht vielleicht das Double ist und sich zu stark in seine Rolle hineinversteift hat. Elisabeth dagegen hat immer die Angst, in einer Geschichte von Leo Richter zu einer Rolle zu werden und versucht ihr Leben vor ihm zu verstecken. Am Ende findet sie sich doch mit der fiktiven Lara Gaspard in Afrika wieder und der Leser weiß nicht genau: Gab es Elisabeth überhaupt wirklich oder war sie die Vorlage für Lara Gaspard?

Besonders fasziniert hat mich ein Dialog zwischen Rosalie, die in die Schweiz zum Sterben fährt, und ihrem Erfinder Leo Richter. Sie bittet ihn darin, sie nicht sterben zu lassen, und er führt weit und breit aus, dass er sie ja nur erfindet und er die Handlung und damit ihr fiktives Schicksal der Geschichte unterordnen muss. Er gibt die Realität der Erzählung vor und nur er hat die Macht dazu, da er real ist. Dass dies eine falsche Annahme ist zeigt Daniel Kehlmann, indem er Rosalie als junge Frau dem Sterbehaus entweichen lässt.

Diese Spiele mit der wahrgenommen Wirklichkeit sind dann auch das Highlight des Buches. Dafür fehlte mir etwas der humorvolle Schreibstil aus der *Vermessung der Welt*, alles muss sich den einzelnen Geschichten unterordnen. Trotz vieler Unterschiede (Perspektive, Ton, Vokabular) zieht sich doch ein sachlicher Stil durch das gesamte Buch, der die Charaktere zwar schnell plastisch werden lässt, aber nie mit wirklichem Inhalt ausfüllt. Dafür sind die Geschichten und das Buch zu kurz; durch die äußerliche Betrachtung wird nie klar, wo die Grenze zwischen Fiktion und Wirklichkeit verläuft - am Ende ist ein Roman ja immer fiktiv.

Fazit: Daniel Kehlmann spielt mit den Themen Ruhm und Realität, ihren Auswirkungen und Interaktionen und verpackt dies in neun lose miteinander verbundenen Kurzgeschichten. Das Ganze liest sich locker weg, ein paar Denkanstöße und Gedankenspiele unterbrechen den Lesefluss nicht und so bleibt am Ende auch nicht viel an Substanz übrig außer einer netten Lektüre - so etwas nennt man glaube ich postmodern.
