---
title: "The Undutchables"
date: "2007-08-13T21:42:20"
categories: [gelesen]
---

*von Colin White & Laurie Boucke,
erschienen bei White Boucke Publishing, ISBN 978-1-888580-32-1, 14,45€*

In letzter Zeit habe ich jobbedingt oft mit Niederländern zu tun, da mein Arbeitgeber sowohl eine holländische Firma gekauft als auch ein Joint Venture in Amsterdam gegründet hat. Einer der neuen Kollegen hat mir dann dieses Buch empfohlen, um unsere Nachbarn am Rhein besser kennen zu lernen.

Die Autoren sind Exil-Amerikaner, die ihre Erfahrungen mit den Lowlands und Cloggies in humorvoller Form als Überblick über Land und Leute verkaufen. In 21 Kapiteln wird so ziemlich jeder Aspekt der Holländer betrachtet; meist sehr ironisch aber leider aus sehr amerikanischer Sicht. Viele Charakteristika der Niederländer gelten auch für uns Deutsche, so dass doch einiges an Komik verloren geht.

Trotzdem lernt man viel vor allem über die politische Einstellung im Land der legalen weichen Drogen. Viele aktuelle Debatten werden vorgestellt und das Buch ist auch up to date, z.B. werden der Tod von [Theo van Gogh](http://de.wikipedia.org/wiki/Theo_van_Gogh_(Regisseur)) und der Film [Black Book](http://de.wikipedia.org/wiki/Black_Book_(Film)) von Paul Verhoeven thematisiert.

Ich hatte allerdings Schwierigkeiten beim Lesen des Buches. Naturbedingt fehlt so etwas wie Spannung und einige Kapitel haben mich auch weniger interessiert, so dass ich oft über der Lektüre eingeschlafen bin. Am Ende habe ich dann aber die ideale Form des Lesens für mich gefunden: In der Tram auf dem Weg zwischen Arbeit und zu Hause hatte ich zweimal am Tag Zeit und Muße, die kurzen Abschnitte abzuarbeiten und habe so die zweite Hälfte des Buches in deutlich weniger Zeit geschafft.

Fazit: *The Undutchables* bietet einen durchaus interessanter Blick auf unsere Nachbarn an der Nordsee durch die Augen von Amerikanern. Doch nicht jedes Kapitel ist gleich lustig oder informativ, so dass ich das Buch nur solchen Lesern empfehle, die ihr Wissen über die Holländern auf die kurzweilige Art aufbessern wollen.
