---
title: "Der Blumenkrieg"
date: "2008-06-06T21:17:06"
categories: [gelesen]
---

*von Tad Williams,
erschienen bei Heyne, ISBN 978-3-453-53274-8, 9,95€*

Tad Williams hat mit der [Osten-Ard-Serie](http://de.wikipedia.org/wiki/Das_Geheimnis_der_Großen_Schwerter) und dem noch nicht beendeten [Schattenmark](/blog/2005/09/18/shadowmarch-die-grenze/)-[Zyklus](/blog/2007/10/09/shadowmarch-das-spiel/) zwei grandiose Fantasy-Werke weit über dem Niveau der meist ideenlosen zeitgenössischen fantastischen Literatur abgeliefert. Doch schon *Otherland* konnte nicht dieselbe Anziehungskraft erzeugen, und *Der Blumenkrieg* ist leider eine weitere Enttäuschung.

Der Autor bewegt sich auf zu ausgetrampelten Pfaden, um mit seinen Stärken aufzufallen: Ein Mensch, den es dank einer kleinen Elfe in ein märchenhaftes Land Elfien verschlägt, der dort zum Helden wider Willen mutiert und am Ende sogar die Menschheit rettet und sein Glück mit einer hüschen Elfin findet - solche Geschichten gibt es tausendfach in diesem Genre, da heben sich auch die 944 Seiten des Wälzers nicht von der Konkurrenz ab. Dem Buch fehlen einfach die Ideen, auch wenn manche Details wie der musikalische Hintergrund des Helden und der sprichwörtliche Zwang der Elfenwelt, Versprechen und Verträge einzuhalten, sich positiv hervorheben.

Die gleichzeitige Ausführung Elfiens als Kopie unserer Menschenwelt ist jedoch eine Chance, die Tad Williams nicht genutzt hat. Die Kritik (Umweltschutz, Ausnutzung und Unterdrückung von ganzen Volksstämmen) versteckt sich an einigen Stellen, doch meist beschränken sich die Analogien als bloße Spielereien mit der verschobenen Realität. Ob die Ähnlichkeit des Turm-Attentats mit den Anschlägen des 11.September nun gewollt sind oder nicht; der düstere Touch will einfach nicht in das Buch passen. Der Kontrast entwickelt keinerlei erzählerische oder inhaltliche Wirkung außer einer gewissen Surrealität, da der Schwerpunkt der zweiten Hälfte des Buches wieder auf den Regeln der Fantasiewelt liegt.

Die Stärken Williams, eine mit ihren Regeln dem Leser vollkommen unbekannte Welt zu erschaffen und dann Charaktere in eine Geschichte zu werfen, die nach und nach entdecken müssen, dass sie ihre Heimat selber nur zu einem geringen Grade kennen und viele Realitäten niemals welche waren - diese Stärken kommen aufgrund der Perspektivänderung im *Blumenkrieg* gar nicht zur Geltung. Des Heldens Welt, nämlich unsere Realität, kennt der Leser zur Genüge und muss trotzdem mit dem Hauptcharakter durch ein Elfien stolpern, das nicht halb so interessant ist wie Osten Ard oder die Schattenmark. Zudem bekommt man beim Lesen kaum Abwechslung zu dem im Buch treffend als flach bezeichneten Helden Theo geboten. Während sich sonst bei Tad Williams die Geschichte auf mehrere Handlungsfäden aufteilt, gibt es hier ab der Mitte des Buches keine Abstecher zu den Nebencharakteren mehr, die am Ende auch nicht die Rollen spielen die man von ihnen erwartet hatte, als sie aufwendig in einzelnen Kapiteln vorgestellt wurden.

Fazit: Ein langweiliger Held, eine weitgehend ideenlose Geschichte und nur wenige interessante Details auf fast 1000 Seiten - viel gibt es nicht, dass einem zum Lesen dieses Buches bewegen sollte. Schade, denn Tad Williams hat auch viele gute Bücher geschrieben - ich warte sehnsüchtig auf den Abschluss der Shadowmarch-Trilogie!
