---
title: "Be kind rewind"
date: "2008-04-13T12:33:34"
categories: [gesehen]
---

*USA (2008)
Regie: Michel Gondry
Darsteller: Jack Black (Jerry), Mos Def (Mike), Danny Glover (Elroy Fletcher), Melonie Diaz (Alma), Mia Farrow (Miss Falewicz), Sigourney Weaver (Miss Lawson) und andere Laiendarsteller*
[Offizielle Homepage](http://www.abgedreht.senator.de/)

Wenn man eines dem Sender Tele5 nicht unbedingt glaubt, diesem Film aber umso mehr, dann ist es die Aussage "Wir lieben Kino". Denn *Be Kind Rewind* (oder auf deutsch *Abgedreht*) handelt von dem Spaß, den man beim Filmemachen haben kann, von der Kreativität der Autoren, Regisseure, Spezialeffekte-Crew und Schauspieler und hat auf der Meta-Ebene auch einiges über das Filmbusiness zu sagen.

Die Handlung spielt in einem Vorort von New York, genauergesagt in und um eine alte Videothek (die ausschließlich VHS verleiht) im Geburtshaus des Jazz-Musikers Fats Waller. Der Besitzer Elroy Fletcher hat sowohl mit dem zurückgehenden Kundenstamm als auch mit der Stadt zu kämpfen, die seinen Altbau durch einen modernen Apartmentkomplex ersetzen möchte. Als dann noch Stammgast und Verschwörungstheoretiker Jerry durch eine starke magnetische Ladung sämtliche Inhalte der Videokassetten löscht, scheint das Geschäft endgültig am Ende.

Um die wenigen Stammkunden nicht zu verprellen beschließen Jerry und der in der Videothek angestellte Mike, die angeforderten Filme auf VHS nachzudrehen. Die ersten als "geschwedet" bezeichneten Filmkopien von *Ghostbusters* und *Rush Hour 2* entwickeln sich aber innerhalb kürzester Zeit zu echten Rennern - bald können sich Jerry, Mike und die als weibliche Hauptdarstellerin engagierte Alma vor Anfragen nach "geschwedeten" Filmen nicht mehr retten und kommen mit der Produktion kaum noch hinterher. Die gesteigerte Aufmerksamkeit führt aber auch die Hüter des Copyrights in die kleine Videothek...

Michel Gondry war einmal der Haus- und Hof-Regisseur von Björk und den White Stripes und hat es in [Markus Kavkas Liste der besten 100 Musikvideos](http://zuender.zeit.de/kavka_dir/2008/kavka-11-musikvideo?page=all) fünfmal unter die Top25 geschafft. Mit *Be kind rewind* kehrt er nach so tollen Filmen wie *Vergiss mein nicht!* (Drehbuch Charlie Kaufmann) wieder zu seinen Wurzeln zurück, denn der Film lebt weniger von einer durchgehenden Handlung (fast alle Handlungstränge verbleiben zum Ende offen) als von den vielen teilweise skurilen Ideen, die vor allem bei den Dreharbeiten der In-Film-Remakes den Einfallsreichtum des Regisseurs zeigen. Dabei wird geschickt zwischen den verschiedenen (Meta-) Ebenen gesprungen: *Be kind rewind* handelt vom dem fiktiven Nachdreh realer Filme, deren Schauspieler teilweise Cameo-Auftritte in fiktiven Rollen haben (Mia Farrow aus *Rosemaries Baby*, Sigourney Weaver aus *Ghostbusters*) und wandelt sich schließlich zu einer Wiedergabe des fiktiven Drehs über das fiktive Leben des realen Fats Waller.

Ganz nebenbei werden zudem spielerisch technische Details des Filmdrehs vermittelt: Masken werden aus einfacher Pappe geschnitten und vor die Kamera gehalten, die [Umaufblende](http://www.movie-college.de/filmschule/kamera/kamerasucher.htm) wird mit einem Ventilator simuliert, Perspektivverzerrung und [Mattepaintings](http://de.wikipedia.org/wiki/Matte_Painting) mit ebenso einfachen Mitteln umgesetzt wie Miniaturnachbauten für die Special Effects - bei der "geschwedeten" Variante von Ghostbusters besteht der Marshmallow-Mann im Gegensatz zum Original sogar wirklich aus Marshmallows. Allen diesen Details ist jedoch eins gemeinsam: Auf den ersten Blick wirkt es komisch, mit welchen skurilen Mitteln die Effekte erzeugt werden, doch mit dem nötigen Hintergrundwissen erkennt man, dass die meisten Techniken noch heute beim Filmdreh verwendet werden, nur auf viel höherem Niveau. *Be kind rewind* nutzt also die vereinfachende Abstraktion des Filmemachens für die Komik, während auf der Meta-Ebene eine Verbeugung vor der Gründerzeit des Kinos erfolgt und den Pionieren der Trick- und Aufnahmetechnik mit ihren begrenzten Ressourcen und dem ausgleichenden Ideenreichtum Respekt gezollt wird. Es scheint als wollte uns Michel Gondry sagen: Dreht selber Filme, seid kreativ, ihr seht mit welchen einfachen Mitteln dies möglich ist - Ideen sind mehr wert als ein großes Budget.

Dies müssen auch die Helden des Films erfahren, als mit Sigourney Weaver plötzlich eine Vertreterin der großen Hollywood-Studios in der Videothek steht und aufgrund der missachteten Kopierrechte alle "geschwedeten" Filme von einer Walze vernichten lässt. Dies ist eine Anspielung auf eine Aktion in Asien, in der tausende von gesammelten Raubkopien öffentlichkeitswirksam vernichtet wurden, und erweckt den Eindruck, dass von den Hütern des Copyights (wohlgemerkt nicht von den Kreativen, die die Originale erschufen) mit Kanonen auf Spatzen geschossen wird - gegen den Willen der Konsumenten. Doch *Be kind rewind* verweigert sich so einer eindeutigen Aussage zu der aktuellen Debatte um Urheberrechte und zeigt dem Zuschauer lieber die Vor- und Nachteile des aktuellen Systems auf.

Zum Einen wäre es niemals zu dem Fats-Waller-Film gekommen, wenn nicht jemand die Remakes unterbunden hätte. Wenn man sich nur auf das Kopieren erfolgreicher Werke verlässt, dann kommt es schnell zum langweiligen aber zeitweise profitablen Fortsetzungswahn (Zitat: "Was wollen wir als nächstes drehen?" - "Wie wäre es mit *Rush Hour 5*, den gibt es noch nicht!"). Eigene Ideen und deren Einmaligkeit sind wichtiger als austauschbare Kopien (ein Schlag gegen die großen DVD-Videotheken, die Langeweile begünstigen), will uns der Film damit sagen.

Auf der anderen Seite müssen aber auch [popkulturelle Variation](http://de.wikipedia.org/wiki/Andy_Warhol) erlaubt sein, damit eine Auseinandersetzung mit der Alltags- und Massenkultur erfolgen kann. Umgekehrt argumentiert zum vorherigen Absatz wäre es niemals zu dem Fats-Waller-Film gekommen, wenn die Helden des Films nicht vorher ihre Erfahrungen mit den Remakes gemacht hätten. Gondry zeigt dies am Beispiel des Graffiti von Jerry und Mike, welches diese zu Beginn des Films in einer Unterführung anbringen. Durch Jerrys Fehler ist es nicht gerade ansehnlich geworden, doch im Laufe des Films wird es angenommen und variiert - andere Sprayer verarbeiten es weiter zu einem gemeinsamen Kunstwerk, das besser ist als das Original. Genauso wird der Fats-Waller-Film erst durch die gemeinsame Arbeit aller Beteiligten zu dem großen Wurf, der einen ganzen Stadtteil sich vor der Videothek versammeln lässt.

Fazit: *Abgedreht* ist oberflächlich betrachtet eine witzige Komödie über Nerds, die Hollywood-Filme nachdrehen. Auf dieser Ebene wird man aber nicht glücklich mit dem Film, denn die meisten Handlungsstränge werden nicht zum Abschluss geführt und gegen Ende lässt der Humor nach. Nimmt man jedoch die Meta-Ebene eines Films über das Filmedrehen dazu und ist bereit, sich mit etwas Vorwissen auf die Auseinandersetzung mit der Thematik einzulassen, dann bekommt man eine wundervolle Hommage an alle Filmemacher dieser Welt geliefert und geht mit dem glücklichen Gefühl aus dem Kino, den Film eines Regisseurs gesehen zu haben, der das Kino mindestens genauso liebt wie man selber.
