---
title: "Britannica & ich"
date: "2008-03-11T21:54:41"
categories: [gelesen]
---

*von A.J. Jacobs,
erschienen bei List, ISBN 978-3-548-60775-7, 9,95€*

Eigentlich sollte man Büchern mit so hochtrabenden Untertiteln wie *Von einem, der auszog, der klügste Mensch der Welt zu werden* aus dem Weg gehen - doch das in Anlehnung an die [Britannica](http://store.britannica.com/shopping/product/anotherview.jsp?&picindex=1&img=local/products/viewlarger/print07w08_lg.jpg&iProductID=822) mit Gold und Distel verzierte Cover und die skurile Idee, ein 32-bändiges Lexikon am Stück durchzulesen, weckten dann doch Interesse in mir.

Zum Glück nimmt der Autor sein Projekt nicht so ernst, wie es der Untertitel vermuten lässt. Und zum Glück hat er auch schnell gemerkt, dass man nicht ein ganzes Buch mit abgeschriebenen Anekdoten füllen kann. So findet sich unter den diversen Begriffen, die wie im Lexikon nach dem Alphabet geordnet sind (das Buch hat ebenfalls ein nettes Register am Ende), eine interessante Mischung aus persönlichen und familiären Erlebnissen in Zusammenhang mit dem Mammutprojekt und kleinen Artikeln über Auswirkungen des Lesemarathons. Wie es sich für einen Journalisten gehört wird dabei das Thema Enzyklopädie von verschiedenen Seiten beleuchtet: Was steckt eigentlich hinter der Britannica, wer schreibt die Artikel und wie sieht die Geschichte dieses weltbekannten Lexikons aus?

Am Interessantesten sind jedoch die Beiträge auf der Metaebene. Der Autor fragt sich, ob er wirklich klüger wird durch die Lektüre, was Intelligenz eigentlich ausmacht und führt deshalb auch einige "Experimente" durch. Er besucht ein Treffen von Mitgliedern des [Mensa](http://de.wikipedia.org/wiki/Mensa_International)-Clubs, trifft sich mit ein paar der laut IQ-Test intelligentesten Menschen Amerikas und versucht sein erlerntes Wissen bei Fernsehsendungen wie *Jeopardy* und *Who wants to be millionaire* gewinnbringend unterzubringen.

Alles in allem ist *Britannica & ich* eine nette, anspruchslose Lektüre für zwischendurch, die den Weg als Ziel ansieht und auf diese Art und Weise unterhalten will - Lernen tut man durch dieses Buch bestimmt nicht.
