---
title: "Auf der anderen Seite"
date: "2008-07-16T21:31:27"
categories: [gesehen]
---

*Deutschland/Türkei (2007)
Regie: Fatih Akın
Darsteller: Baki Davrak (Nejat Aksu), Nurgül Yeşilçay (Ayten Öztürk), Tunçel Kurtiz (Ali Aksu), Nursel Köse (Yeter Öztürk), Patrycia Ziolkowska (Charlotte Staub), Hanna Schygulla (Susanne Staub) und andere Reisende zwischen Deutschland und der Türkei*
[Offizielle Homepage](http://www.auf-der-anderen-seite.de/)

Wenn es abends 21 Uhr in Berlin noch 25 Grad warm ist und die aufziehenden Wolken keine erfrischend kühle Nacht vermuten lassen, dann kann man eigentlich nur in den Biergarten oder ins Open-Air-Sommerkino gehen. Ich habe letzteres getan und mir den schon ein Jahr alten Film von Fatih Akın im [Freiluftkino Friedrichshain](http://www.freiluftkino-friedrichshain.de/) angesehen. *Auf der anderen Seite* ist der zweite Teil einer Filmtrilogie von Fatih Akın, deren erster Teil [Gegen die Wand](/blog/2004/05/08/gegen-die-wand/) mich sehr interessiert hat und deshalb Lust auf mehr machte.

Erneut geht es um die Probleme von Deutsch-Türken zwischen den Gesellschaften, diesmal an Hand dreier Kind-Elternteil-Paare. Nejat ist Germanistik-Professor in Deutschland, sein Vater Ali Rentner in Bremen. Da der alte Mann etwas einsam ist, überredet er die Hure Yeter, ihre Arbeit aufzugeben und zu ihm zu ziehen. Doch dann fällt Yeter bei einer häuslichen Auseinandersetzung so unglücklich, dass sie stirbt. Sie hinterlässt eine Tochter, Ayten, in der Türkei, der Nejat als Wiedergutmachung ein Studium finanzieren will und sich deshalb auf die Suche nach ihr macht.

Doch während Nejat in die Türkei reist, ist Ayten vor der türkischen Justiz nach Deutschland geflohen und hat sich dort in Lotte verliebt. Da sie keine Aufenthaltsgenehmigung besitzt, wird sie schließlich wieder in die Heimat und dort in das Gefängnis abgeschoben. Lotte reist ihr hinterher, kann der Freundin jedoch nicht helfen. Allein im fremden Land, von der eigenen Mutter verstoßen, stirbt Lotte schließlich durch einen unglücklichen Zufall in einem Hinterhof. Durch diesen Tod lernen sich Lottes Mutter Susanne und Nejat kennen, und auch Ali verschlägt es dank Abschiebung wieder in die Heimat...

So wenig die Handlung von *Auf der anderen Seite* der von *Gegen die Wand* ähnelt, so viele Parallelen gibt es doch. In beiden Filmen sind es ungewollte Morde, die entscheidende Wendungen mit sich bringen, und beides Mal ist es das zu Passivität verurteilende Element der Haft, das andere Charaktere zu entscheidenden Reaktionen zwingt. 

Der Unterschied findet sich jedoch in der finalen Aussage: Es ist egal, in welchem Land und in welcher Kultur etwas passiert, die Menschen sind in der Lage, in ihren Umgang jegliche Grenzen hinter sich zu lassen. Sehr schön verdeutlicht dies auch das Bild der beiden Särge, die in Flugzeuge eingeladen werden. Die erste Szene spielt in Deutschland, die zweite in der Türkei, doch für den Betrachter ist kein Unterschied zu erkennen.

Dies ist dann auch die Erkenntnis der Charaktere: Susanne unterstützt am Ende Ayten, wie sie es vorher bei Lotte versäumt hat und überwindet sich dabei selber. Und auch Nejat erkennt, was ihm sein Vater zeitlebens gegeben hat, und was er jetzt davon zurückzahlen kann. In die zutiefst schönen Bilder Istanbuls und der Schwarzmeerküste hüllt Fatih Akın diesmal also trotz zweier Todesfälle eine positive Aussage: Grenzen gibt es nur in den Köpfen der Menschen, und dort kann man sie auch überwinden!
