---
title: "Plagiatus oder von der Stange?"
date: "2008-08-15T21:58:43"
categories: [gedacht,gefunden]
---

Schon seit einiger Zeit langweilt mich das Theme meines Blogs. Zu sehr Standard, zu blass der Kontrast und technisch überholt - nach 2,5 Jahren kann es ruhig etwas Neues werden. Also habe ich im Mai begonnen, auf Basis des [Codelog-Themes](http://www.codelog.net/codelog-theme) mit der [Yahoo UI CSS Library](http://developer.yahoo.com/yui/grids/) herumzuspielen, die es erlaubt, CSS-Styles komplett frei von absoluten Größenangaben wie Pixel zu halten und nur die relative Einheit *em* zu nutzen. Dies impliziert auch den totalen Verzicht auf Bilder im Layout, wodurch ein auf das Nötigste reduzierte Design möglich wird. Doch dann kamen der schöne Sommer und einige Probleme dazwischen, die zu lösen mir einfach nach der Arbeit der Elan fehlt.

Und nun stoße ich beim [Popkulturjunkie](http://www.popkulturjunkie.de/wp/index.php) auf ein zumindest optisch ins selbe Horn stoßende [Theme](http://wpzone.net/free-wordpress-themes/elite/) mit einer noch harmonischer wirkenden Farbpalette. Obwohl ich eigentlich nicht zurück zu heller Schrift auf dunklem Grund wollte, reizt mich ein fertiges Theme zu installieren und alle Probleme hinter mir zu lassen. Schließlich steht auch noch [ein lange verschobenes Upgrade](/blog/2008/07/24/das-verhinderte-upgrade/) an...
