---
title: "Return to Monkey Island"
date: "2022-09-30T09:50:59"
categories: [gespielt]
---

Über 30 Jahre nach [meiner ersten Berührung mit Monkey Island](/blog/2010/09/11/me-monkey-island/) und 12 Jahre nach [dem letzten Spiel](/blog/2010/09/11/tales-of-monkey-island/) kommt mit *Return to Monkey Island* nun der je nach Zählweise dritte oder sechste Teil der Serie.

Seit der Ankündigung vor nicht einmal einem halben Jahr gab es viel Buzz um das Spiel. Für viele Gamer ist die Serie der Inbegriff des Adventure-Genres und wie bei mir mit vielen Erinnerungen verbunden. Gleichzeitig hat sich eine internet-typische extreme Diskussion um den Art-Style entwickelt.

Dieser gefällt mir auch nicht besonders. Er schließt gefühlt bei *Day of the Tentacle* an, nur viel eckiger. Allerdings wirken die Animationen sehr ungelenk und abgehackt. Und die eigenwillige Farbgebung macht es manchmal schwer zu erkennen, was hier eigentlich dargestellt werden soll. Bestes Beispiel: Das Plateau auf Monkey Island, das irgendjemand auch als Hintergrund für das Spielmenü auf der Switch erkoren hat. Bis ich im Spiel dorthin kam hielt ich es für abstrakten Farbmatsch. Oder der Lagerraum auf LeChucks Schiff: Dadurch dass die Grafik jegliche Tiefenwirkung missen lässt sieht es so aus, als ob ein riesiges Geisterhuhn in der Ecke sitzt - dabei soll es nur ganz nah an der "Kamera" sein.

Doch die Grafik ist gar nicht das größte Problem von RtMI. Viel mehr hat mich das Recycling von Orten und Personen gestört. Bis zum vierten von fünf Kapiteln spielt die Handlung auf Melee Island und Monkey Island, wobei die Inseln zwar im neuen Grafikstil gehalten sind, aber ansonsten 1:1 wie in den alten Spielen aussehen. Dazu kommen viele bekannte Charaktere: Elaine, Wally, die Voodoo-Lady, Stan, Otis, Carmen, Lookout, Murray. Und das sind nicht nur Gags am Rande für Eingeweihte, sondern elementare Handlungsorte und wichtige Ansprechpartner.

Das wirkt irgendwie ideenarm, wie ein lauwarmer Aufguss der vorangegangenen Spiele. Wie der Opa, der aus seiner Jugend erzählt (womit das Spiel ja auch kokettiert). Hier haben Neulinge der Serie einen Vorteil, da sie nicht den Ballast des Wissens um die vorherigen Teile mitschleppen. Ich aber wollte ein neues Monkey Island Spiel spielen (wie fünf mal zuvor) und nicht ein Best-Of. Erst mit Kapitel 4 darf ich neue Inseln erkunden, und dieses (längste) Kapitel ist dann auch das Highlight des Spiels: Mehr Freiheit, mehr insel-überspannende Rätsel, und neue Absurditäten. Hier zeigen die beiden Adventure-Veteranen Gilbert & Grossman noch einmal, was sie drauf haben, wenn sie nicht nur in Erinnerungen schwelgen oder Fan-Service betreiben.

Das Finale fällt dagegen wieder ab, weil zum Einen die Rätsel (gefühlt) gemein werden und zum Anderen das Ende erneut eine Wiederholung ist und zugleich alles offen hält. Das hat mir schon an Teil 2 nicht gefallen - wobei Monkey Island auch immer mit den Konventionen des Genres spielte, da sollte es mich nicht überraschen, dass sich auch die Spielehandlung auf die Metaebene veirrt.

Spannend fand ich, das Spiel auf der Switch zu spielen. Im Gegensatz zu Tales of Monkey Island ist die Steuerung wieder indirekt, aber statt den Bildschirm nach Pixeln abzusuchen, darf ich mich diesmal durch alle Punkte mit Interaktionen durchtabben. Zumindest solange sie ungefähr in der Nähe von Guybrush sind. Und Guybrush nicht stillsteht.

Am Ende ist RtMI ein gutes, aber nicht überragendes Adventure geworden, mit einem Grafikstil, über den man gespaltener Meinung sein kann. Es ist zwar sehr unterhaltsam, greift aber inhaltlich wie bei der Steuerung viel von den ersten Teilen der Serie auf, und diese Wiederholung hat mir etwas den Spaß genommen.