---
title: "The door in the floor"
date: "2004-11-22T00:00:37"
categories: [gesehen]
---

*USA (2004)
Regie: Tod Williams
Darsteller: Jeff Bridges (Ted Cole), Kim Basinger (Marion Cole), Jon Foster (Eddie O'Hare), Elle Fanning (Ruth Cole), Bijou Phillips (Alice), Mimi Rogers (Evelyn Vaughn), Louis Arcella (Eduardo Gomez) und andere Bewohner von Long Island*
[Offizielle Homepage](http://www.tuerderversuchung.de/)

Der Kinderbuchautor Ted lebt mit seiner Frau Marion und Töchterchen Ruth seit dem Tod der beiden Söhne auf Long Island. Die Mutter hat die Tragödie nie ganz verkraftet und so geht die Ehe langsam in die Brüche; die Tochter muss mit dem schweren Erbe der vielen Erinnerungen und Bilder der Brüder aufwachsen. Da taucht Eddie auf, der mit einem Praktikum bei Ted Einblicke in den Schaffungsprozess eines Buches gewinnen will. Doch der Künstler amüsiert sich lieber mit einem seiner Aktmodelle, anstatt sich um den Jungen zu kümmern. Dies übernimmt deshalb Marion und muss bald feststellen, dass der unerfahrene Eddie Gefühle für sie entwickelt...

Litertaurverfilmungen kann man immer besser beurteilen, wenn man die Vorlage gelesen hat - ist dann aber auch meistens enttäuscht. Leider habe ich die "Witwe für ein Jahr" von John Irving nicht gelesen (trotz meiner Zuneigung für den Autoren), so dass ich nicht genau sagen kann, ob die Qualitäten des Films nun dem literarischen Werk zuzuschreiben sind oder der Regisseur genügend eigene Ideen eingebracht hat. Denn eigentlich kann man Bücher im Allgemeinen und Irving-Werke im Besonderen ("Details sind wichtig!") aufgrund ihrer Komplexität schlecht in einem Film umsetzen, ohne auf weite Teile der Vorlage zu verzichten und gleichzeitig den verbliebenen Rest visuell so auszuschmücken, dass die Lücken gar nicht auffallen. Die sehr bildreichen Schreibweise Irvings erleichtert es dabei scheinbar den Regisseuren, seine Bücher auf die Leinwand zu portieren - anders kann man die durchgängig hohe Qualität seiner Buchumsetzungen nicht erklären ("Hotel New Hampshire", "Garp und wie er die Welt sah", "Gottes Werk und Teufels Beitrag",...).

Auch "The door in the floor" lebt natürlich von den Bildern. Das Wichtigste davon ist sicherlich die titelgebende "Tür im Boden", die einem immer wieder im Laufe des Films begegnet. Sie steht für ein Drinnen und ein Draußen, für das Geborgene und das Schreckliche, welches jedoch ständig eine Anziehungskraft auf die sichere Seite ausübt. So geht es den Jungen und dem Mädchen in der Kindergeschichte von Ted (seine Art der Verarbeitung des Familiendramas), wobei Ted gerade die Metapher mit der Vagina (für das ungeborene Kind die Tür im Boden) so fasziniert, dass er dieses Körperteil am Liebsten portraitiert. Aber so geht es auch Marion, die nach dem Unfall unbedingt noch den Schuh ihres Sohnes aufheben will und dabei den Schock ihres Lebens erlebt, als sie durch die Tür (diesmal des Wagens) das Bein ihres Sohnes erblickt. Und als wäre das nicht genug, endet der Film auch noch mit der visuell klarsten Tür im Boden, nämlich der von Teds selbstgebauten Squashraum. Hier ist seine Zuflucht, sein Ort der Geborgenheit, wo er sich von all den lockenden Einflüssen der anderen Seite (seinen Schwächen) verschanzen kann und im Umgang mit Schläger und Ball absolut sicher ist - was man von Umgang mit seiner Frau in Bezug auf das Familiendrama nicht behaupten kann.

Ein eher optisch und akustisch geprägtes Bild ist dagegen der Blinker des Autos, welches sich so stark in das Gehirn von Marion eingebrannt hat, dass sie jedes Mal von neuem die Ereignisse des Unfalls mitmachen muss, wenn sie es sieht. Der Regisseur schafft es dabei, dass der Zuschauer am Ende ihre Qualen deutlich versteht, als er zum letzten Mal den Blinker zeigt. Ansonsten ist es gerade aber die Figur der Marion, deren Innerstes dem Zuschauer erst am Schluss und nur durch die Eindrücke von Ted und Eddie etwas klarer wird. Davor wirkt der Charakter eher blass und die Beweggründe für ihr Verhalten bleiben meist im Ungewissen. So spielt auch die überzeugende Kim Basinger ihre Rolle zwar ansprechend, aber sehr zurückhaltend.

Ganz anders dagegen Jeff Bridges. Er kann sich in der Rolle des extrovertierten Künstlers Ted Cole (mal wieder) so richtig austoben. Die Bandbreite reicht vom einfühlsamen, aber nicht immer erfolgreichen Vater über den eiskalt die Scheidung planenden Ehemann bis hin zu dem extremen Stimmungschwankungen unterliegenden Künstler (ohne Führerschein). In der Beziehung zu seiner Ehefrau wirkt er ebenso unsicher: Zwar kann er nicht mehr mit der traumatisierten Marion leben, doch versucht er auch, sie aus diesem Zustand zu befreien. Gleichzeitig klammert er sich jedoch extrem an ihre gemeinsame Tochter, die er auf keinen Fall verlieren will wie seine Söhne, an deren Tod er sich die Schuld gibt.

So gerät die dritte Hauptfigur Eddie in die Geschichte. In einem letzten Versuch, die Ehe zu retten, nimmt Ted den Jungen als Praktikanten an, da er nicht nur am selben College wie früher die toten Söhne studiert, sondern einem der Beiden auch noch ziemlich ähnlich sieht (und einen Führerschein hat). Eddie ist zwar anfangs mit der Situation in der Familie und Teds Verhalten überfordert, jedoch bewirkt der unerfahrene Junge mit seinen Gefühlen (oder nur seinem Verlangen?) für Marion in ihr etwas anderes, als der Künstler geplant hat. Sie überwindet zwar nicht den Tod der Söhne, aber zumindest findet sie ihre Lebenslust zurück und lässt das (gescheiterte) Kapitel "Neuanfang mit Ruth" hinter sich, um einen anderen Weg der Bewältigung zu gehen (inklusive der Bilder der Söhne).

Diese hingen im oberen Flur des Hauses im scherzhaft genannten Horrorkabinett. Der gesamte Flur war mit den Aufnahmen der toten Jungen in allen Stadien ihres kurzen Lebens ausgehängt, und Ted nutzt jede Gelegenheit um seiner Tochter eine Geschichte darüber zu erzählen. So wächst die kleine Ruth in einer Welt der Geschichten um imaginäre Geschwister als Ersatz für reale Freunde auf. Das führt dazu, dass für sie der Verlust der Bilder schlimmer ist, als der Weggang der Mutter - nur ist der Film genau an der Stelle zu Ende, wo man sich fragt, wie denn das Mädchen damit klarkommt. Wer dies wissen will, muss wohl die Vorlage lesen, denn dort ist Ruth die Hauptfigur und das Buch begleitet sie auch im weiteren Leben (habe ich mir sagen lassen).

Neben den Charakteren merkt man auch der Handlung deutlich die Handschrift von John Irving an. Scheinbar alltägliches offenbart sich bei der Betrachtung von Einzelheiten oftmals als sehr skuril; und die Charaktere sind vor keiner Peinlichkeit gefeit. So wird Eddie bei jedem seiner Versuche zu onanieren erwischt (das Bild mit den Füßen, die Unterwäsche von Marion) oder wird ungewollt zum Lustobjekt, als er der Inhaberin des Fotoladens die Geschichte von seiner Liaison mit Marion aufschreibt, damit die daneben stehende Ruth nichts mitbekommt. Am Witzigsten ist jedoch die Fluchtszene von Ted, der in Jesuslatschen und weitem Morgenmantel vor seinem mit einem Messer bewaffneten Aktmodell durch halb Long Island fliehen muss. Aus solchen Situationen entwickelt sich jedoch meist eine ungeahnte Wendung - Eddie wird z.B. von Marion mit Unterwäsche bedient und Ted findet in einem Buchladen sofort die nächsten willigen Modelle.

A propos Long Island: Die Insel wird vom Regisseur meist von ihrer schlechten Wetterseite gezeigt. Nur selten scheint die Sonne, was dem Film jedoch nicht zum Nachteil gereicht. Ansonsten verhält sich die Kamera sehr konservativ und lässt den Schauspielern lieber den Freiraum, sich in der Vordergrund zu spielen, als sie in experimentelle Enstellungen zu zwängen. Die oben angesprochenen Bilder werden jedoch sehr elegant und unaufdringlich umgesetzt, so dass der Film auch handwerklich überzeugen kann. 

Fazit: Wer John Irving und seine Bücher mag wird auch diesen Film mögen. Den Zuschauer erwartet eine lustig-dramatische Geschichte, getragen von sehr guten Schauspielern und erzählt von einem Regisseur, der die Vorlage in einer bildreichen Sprache sehr ansprechend auf der Leinwand adaptiert. Nur das etwas lose Ende und die blass wirkende Figur der Marion verhindern die Bestnote!
