---
title: "Aus den Augen, in den Sinn: Hereafter"
date: "2012-03-18T12:30:18"
categories: [gedacht,gesehen]
---

Manche Filme, die ich gesehen habe, entfalten ihre Wirkung erst lange nach der Betrachtung. Der Kopf arbeitet weiter mit den Bildern, während die Erinnerungen an die meisten Szenen aus dem Gedächtnis verschwinden, und so ändert sich auch mein Eindruck des Gesehenen mit der Zeit. In der Rubrik *Aus den Augen, in den Sinn* möchte ich Filme vorstellen, die mir aus irgendeinem Grund zurück ins Gedächtnis gerufen wurden, und darüber berichten, an was ich mich von ihnen erinnere. Ich fange an mit Clint Eastwoods vorletztem Film *Hereafter*.

Der Altmeister beschäftigt sich darin mit der Frage um ein Leben nach dem Tod. Gleich zu Beginn darf der Zuschauer deshalb in einer tricktechnisch beeindruckenden Sequenz beobachten, wie die großartige Cécile de France von der Flutwelle in Phuket erfasst wird, durch die Straßen der Stadt gespült wird und schließlich mit einem Stück Holz kollidiert. Dieser wuchtige Einstieg stellt den Kontrapunkt zu einem ansonsten ruhigen Film dar und lässt den Zuschauer folgend die Nahtod-Erfahrung der Figur erleben, so dass die Fronten für den thematischen Schwerpunkt schnell gesetzt sind. Viel mehr als ihre Rolle im Film hat mich jedoch an dieser Szene beeindruckt, dass sie technisch absolut perfekt ist: Ich konnte trotz mehrfachen Ansehens nicht erkennen, wie dieser Effekt erzielt wurde. Erst im Making-Of wurde näher darauf eingegangen, ohne jedoch die Illussion des Ergebnisses zu zerstören. Clint Eastwood ist einfach ein großartiger Regisseur, wie er die Technik in den Dienst der Handlung stellt und trotzdem handwerkliche Höchstleistungen sicherstellt.

DIe zweite in meinem Gedächtnis haften gebliebene Szene dreht sich um das von Matt Damon gespielte Medium George Lonegan. Er sieht seine Gabe, mit den Toten reden zu können (diese Fähigkeit wird innerhalb des Films nicht in Frage gestellt), als Bürde, und lässt sich doch immer wieder überreden, sie einzusetzen. In einem Kochkurs hat er eine Frau kennengelernt, die bald von seiner Fähigkeit erfährt. Doch die Kontaktaufnahme mit ihrem toten Vater bricht schlimme Wunden in ihr auf: Sie wurde als Kind vom Vater missbraucht, der erst nach seinem Tod den Mut findet, sich über George bei ihr zu entschuldigen. Es ist wirklich großartig anzusehen, wie Bryce Dallas Howard als Melanie darauf reagiert. Nach der ersten Leugnung kann George sie zwar überzeugen, dass er ihr nicht nur etwas vorspielt und das Wissen über den Missbrauch irgendwie in Erfahrung gebracht hat. Doch die Akzeptanz der überbrachten Nachricht entblößt das eigentliche Problem der Situation. Der bisher privat gebliebene Missbrauch, ein Geheimnis zwischen Vater und Tochter, hat nun einen Mitwisser. Dieser Einblick in das Innerste von Melanie belastet nicht nur die Beziehung zu George, sondern zwingt die junge Frau auch dazu, sich ihrer Vergangenheit zu stellen - ein schwerer Schritt, den sie bisher ohne einen lebenden Zeugen gut verdrängen konnte.

Wie sensibel Clint Eastwood diese Szene inszeniert nötigt mir ebenso Respekt ab wie die Leistungen der beiden Darsteller. Leider hat der Film nicht viele solcher Szenen zu bieten, so dass die zugrunde liegende Annahme, dass es ein Leben nach dem Tod und eine Kommunikation damit wirklich gibt, ins Leere läuft. Aber für die zwei erwähnten Highlights hat sich das Sehen schon gelohnt.
