---
title: "HDTV - ein holpriger Start"
date: "2010-02-13T20:49:03"
categories: [gesehen,getan]
---

Pünktlich zu den olympischen Winterspielen in Vancouver haben es die Öffentlich-Rechtlichen Sender [ARD](http://www.ard-digital.de/HDTV/Startseite-HDTV) und [ZDF](http://www.unternehmen.zdf.de/index.php?id=29) geschafft, ihre HDTV-Ausstrahlung in den Regelbetrieb übergehen zu lassen. Während arte schon seit über einem Jahr hochauflösend auf Sendung ist, haben die beiden ersten Programme erst ein paar Showcases wie zur Leichtathletik-WM und über Weihnachten ausprobiert, bevor der große Schritt gewagt wurde.

Trotzdem ist natürlich nicht alles HD, was auf den HDTV-Versionen der Sender läuft. Der Löwenanteil der Sendungen wird immer noch in SD produziert und für die HD-Ausstrahlung einfach nur hochgerechnet. Neben Mischformen wie der Bundesliga-Sportschau, deren Studioaufnahmen hochauflösend sind, die Spielzusammenfassungen jedoch nicht, gibt es aber bereits einige Programmformate in HD. In der [ARD-Programmübersicht](http://programm.ard.de/Programm/Sender?sender=28106) sind diese als solche markiert; [beim ZDF kann man gezielt nach HD suchen](http://www.zdf.de/ZDFdeEPG/include-extended-searchform.jsp). In den nächsten vierzehn Tagen dominiert die Olympia-Berichterstattung diesen Bereich.

Technisch hat man sich bereits vor Jahren für 720p50 entschieden, d.h. für 50 Bilder pro Sekunde in der kleineren der beiden HD-Auflösungen. Begründet wird dies mit dem angeblich besseren Bild durch die höhere zeitliche Auflösung gegenüber dem weitverbreiteten 1080i50, also 50 Halbbildern in voller HD-Größe. So richtig ich die Entscheidung gegen das Interlaced-Format finde, dass als Relikt aus analogen TV-Tagen zu Zeiten von LCD-Fernsehern eigentlich längst ausgestorben sein sollte, so ärgerlich finde ich die Wahl der geringeren Auflösung. Denn zum Einen hat sich 1080p als Standardformat auf Blu-Rays längst durchgesetzt, zum Anderen wird weltweit das meiste HD-Material in 1080i produziert. Dies bedeutet, dass das gewählte Format nur eine Zwischenlösung darstellt und vermutlich bald wieder abgelöst wird. Bis dahin entsteht viel Konvertierungsaufwand, wenn fremdproduzierte Sendungen ausgestrahlt werden sollen wie aktuell die olympischen Spiele. Und selbst internationale Großereignisse wie die Leichtathletik-WM letztes Jahr in Berlin wurden von ARD/ZDF in 1080i produziert und nur dem eigenen Publikum in 720p50 präsentiert...

Neben dem höher aufgelösten Bild bringt der HDTV-Start auch Dolby Digital als Standardtonformat für die Öffentlich-Rechtlichen. Ob das abseits der Filme, bei denen dies bereits üblich war, wirklich Vorteile bringt, muss ich jedoch anzweifeln. Bei den Olympia-Übertragungen bedeutet dies nur, dass der Kommentator auf den Center-Lautsprecher gelegt wird und alle anderen Umgebungsgeräusche wie die Zuschauer auf den Surroundboxen erscheinen. Leider ist die Abmischung nicht optimal, der Kommentator geht teilweise in den Umgebungsgeräuschen unter, und beim Wechsel auf die nicht in 5.1 produzierte Werbung stören die großen Lautstärkeunterschiede.

Dennoch ist es wichtig, dass der Schritt zu HD endlich vollzogen wurde und ich verspreche mir einen wichtigen Impuls für die gesamte Fernsehlandschaft in Deutschland. Der Unterschied zum analogen Fernsehen und selbst zum digitalen SD-Bild ist deutlich zu sehen; endlich kann ich die Fähigkeiten meines HD-Fernsehers einmal ausnutzen.

Dabei standen die Chancen bis vor kurzem noch schlecht, dass ich als [Zwangskunde von Kabel Deutschland](/blog/2009/02/20/wer-nicht-horen-will/) das HDTV-Signal überhaupt eingespeist bekomme. Denn entgegen anderer Kabel-Monopolisten wollte Kabel Deutschland von den Sendern Geld dafür verlangen, dass es dem für den Anschluss zahlenden Kunden die hochaufgelösten Kanäle anbietet. Erst [Ende Januar](http://kabel-blog.de/2010/01/28/hdtv-start-bei-kabel-deutschland/) hatte das Pokerspiel ein Ende und Kabel Deutschland lenkte ein; seit einer Woche kann man das Signal nun empfangen und dies sogar ohne die ansonsten übliche Grundverschlüsselung.

Zum HD-Glück fehlte jetzt nur noch ein HD-Receiver. Denn mein Samsung-LCD besitzt keinen eingebauten DVB-C-Tuner wie der Philips meiner Eltern, bei denen ich über Weihnachten bereits erste Erfahrungen mit ARD/ZDF HD machen konnte. Da Kabel Deutschland bis vor kurzem außer Premiere/Sky, die eigene Receiver anbieten, keine HD-Sender im Programm hatte, fehlt noch jegliches HD-Angebot an die eigenen Kunden. Das bestmögliche angebotene Gerät war bisher ein digitaler Festplattenrekorder, der jedoch nicht einmal einen HDMI-Ausgang besaß sondern das digitale Signal über Scart an den Fernseher weitergab. Ein qualitativ hochwertiges Bild liegt eindeutig nicht im Fokus des Kabelanschlussanbieters - einige digitale Sender wie Eurosport 2 wurden mit einer geringen Bitrate eingespeist, die Erinnerungen an die ersten Internetvideos weckte. Erst im Sommer zur Fußball-WM soll das Angebot erweitert werden; mit etwas Glück kann ich dann gleich auf einen [HD-Festplattenrekorder wie bei Kabel-BW](http://kabel-blog.de/2010/02/10/festplatten-receiver-fuer-hdtv-bei-kabel-bw/) wechseln.

So blieb mir nichts anderes übrig, als mir selbständig einen Receiver zuzulegen. Die Auswahl an preiswerten Geräten ist klein, und so kurz vor dem olympischen Spielen waren auch die Lager der Händler leer. Ich entschied mich für den Philips DCR-5000, der gerade rechtzeitig zum Regelbetrieb von ARD und ZDF HD per [Firmware-Update](http://www.hdtv-pro.de/hdtv-news/firmware-update-fuer-hdtv-kabelreceiver-philips-dcr-50009000-verfuegbar-5193.html) überhaupt einen fehlerfreien Empfang der Sender ermöglicht. Anschluss und Einrichtung verliefen problemlos und so kann ich nun seit gestern die Winterolympiade in HD verfolgen.

Die Umschaltzeiten des Philips sind relativ gering und Bild und Ton können überzeugen; die Integration in meinen HiFi-Stack stellte keine Probleme dar. Zudem hat das Gerät eine tolle Fernbedienung und einen Stromsparmodus für das Standby, der aber auch die Aktualisierung des EPG verhindert. Probleme in Sachen Zukunftssicherheit sehe ich in der Beschränkung des HDMI-Ausgangs auf 1080i; Vollbilder in der großen HD-Auflösung sind so nicht möglich. Dies ist zwar momentan ausreichend für alles, was in Deutschland an HD-Fernsehen gesendet wird, aber wie gesagt gehört die Zukunft ganz klar dem 1080p-Format.

So muss man also vielerorts noch einige Hürden überwinden und den üblichen Preis der Early Adopters zahlen, um an der Zukunft des Fernsehens teilhaben zu können. Doch für mich hat sich die Investition ganz klar gelohnt und ich freue mich auf zwei Wochen Olympia in HD!
