---
title: "ELLING - Nicht ohne meine Mutter"
date: "2004-06-27T00:00:54"
categories: [gesehen]
---

*Norwegen (2003)
Regie: Eva Isaksen
Darsteller: Per Christian Ellefsen (Elling), Grete Nordrå (Mutter), Helge Reiss (Oberst Bugge-Høvik), Christin Borge (Mag), Per Schaaning (Georg), Lena Meieran (Grete Iversen), Kit (Erna) und andere Norweger in südlichen Gefilden*
[Offizielle Homepage](http://www.arsenalfilm.de/elling-mutter/index.html)

Der Mittdreißiger Elling ist ein Muttersöhnchen, das sich das gesamte Leben hat bedienen lassen. Dementsprechend unselbständig ist er, den Kopf voller Neurosen und keine Ahnung von der Welt außerhalb der heimischen Wohnung. Als die Mutter eines Tages erfährt, dass sie nicht mehr lange zu leben hat, beschließt sie kurzerhand, nach Mallorca zu fliegen um auf den Spuren ihrer Eltern zu wandeln. Dieser Ausbruch aus seinem normalen Leben passt Elling natürlich gar nicht, doch widerwillig lässt er sich schließlich überreden, mit zu fliegen - nur um allen Leuten im Urlaub inklusive seiner Mutter mit seiner eigenwilligen Art das Leben schwer zu machen...

Ich ging in diesen Film, weil mir immer so vom ersten Elling-Streifen vorgeschwärmt wurde. Dass trotz des Ansatzes als Prequel einige Anspielungen auf den eigentlichen Nachfolger vorkamen, erfuhr ich erst hinterher. Jedoch kann man Elling auch ganz gut ohne Vorwissen ansehen (es wurde u.a. die Regie gewechselt), und meine Kritik geht auch von diesem Standpunkt aus. Jedoch warne ich gleich vorneweg: Wer eine typisch skandinavische, schwarze Komödie erwartet, wird von diesem Film wahrscheinlich enttäuscht - so wie ich.

Warum Elling mit fast 40 Jahren noch bei Muttern wohnt, wird nicht so recht klar, jedoch scheint ihm diese lange Zeit im Hotel Mama recht eigensinnig gemacht zu haben. Neurosen und schlechte Angewohnheiten, geduldet durch die seit Ellings Geburt alleinerziehende Mutter, haben dazu geführt, dass der "Junge" nicht imstande ist zu telefonieren oder anderen Kontakt zur "Außenwelt" jenseits der heimischen Wohnung zu pflegen. Seine Goldfische sterben, weil er nicht in der Lage ist zu akzeptieren, dass sie nur unter Wasser atmen können - dafür reagiert er selber aber umso allergischer auf alles, was nicht in seinen gewohnten oder gewollten Bahnen abläuft. Spontane Reaktionen sind ihm ein Greuel, und die Mutter will er mit keinem teilen.

Nicht gerade die besten Voraussetzungen also für einen Mallorca-Urlaub, doch diesmal setzt sich die Mutter durch, denn sie weiß um ihr Lebensende und will nur einziges Mal das Winterquartier der Eltern besuchen, von dem diese auf Postkarten immer so geschwärmt haben. Also erträgt sie auch mit Engelsgeduld, wie Elling an jeder Ecke Schlechtes in den Menschen vermutet, sei es nun die Reiseleiterin, der Oberst a.D., der sich versucht der Mutter zu nähern oder gar diese selber. Und sie hat die Kraft, sich von ihm zu lösen und eine Liaison mit dem Oberst anzufangen - quasi eine schnelle Vorbereitung Ellings auf den baldigen Tod der Mutter.

Aus der resultierenden Konfrontation Ellings mit der Umwelt besteht dann der gesamte Film. Tragikomisch stolpert unser Antiheld durch die Handlung und verdient sich nur selten einmal Sympathiepunkte beim Zuschauer. An einigen Stellen mag man noch lachen können über die Schrullen, doch während er wie ein Kind die Welt entdeckt findet leider keinerlei Entwicklung der Figur statt. Erst am ziemlich abrupten Ende muss er endlich einmal über seinen Schatten springen - die Mutter ist nicht mehr da und Elling muss nun für sich selber sorgen, zum ersten Mal in seinem Leben.

Erzählt wird dem Zuschauer die Handlung aus dem Off von Elling höchstpersönlich, so dass man einigermaßen (jedoch nicht an jeder Stelle) nachvollziehen kann, was in diesem Kopf vorgeht. Doch genau deshalb versanden viele der komischen Elemente, da sie aus Sicht von Elling eben nicht lustig, sondern ernst gemeint sind. Vielleicht wird auch deshalb Mallorca nicht gerade von der besten Seite gezeigt, denn Elling hält nicht viel von den Spaniern und muss der Mutter bei jeder bietenden Gelegenheit vorhalten, dass es dort auch nicht schöner als zu Hause ist.

Dass man dem Film die Figur des Elling dennoch abnimmt, trotz der zum Teil recht unterschiedlichen Charakterzeichnung, liegt am Hauptdarsteller Per Christian Ellefsen. Egal ob er seiner Mutter den geplanten Inzest vorwirft oder die Schulter für die vollbusige Zimmernachbarin Mag hinhält, jederzeit bringt er den eigenwilligen Charakter glaubhaft auf die Leinwand. Leider kann er damit aber nicht die Längen überspielen, die der Film manchmal dem Zuschauer zumutet.

Fazit: Als Fortsetzung einer Komödie enttäuscht dieser Film seine Zuschauer; und auch die Tragik offenbart sich erst ganz am Ende. Doch sieht man über diese konzeptionellen und storytechnischen Fehler hinweg, so entdeckt man eine ungewöhnliche Tragikomödie mit guten Schauspielern.
