---
title: "Juno"
date: "2008-04-13T15:58:02"
categories: [gesehen]
---

*USA (2007)
Regie: Jason Reitman
Darsteller: Ellen Page (Juno MacDuff), Jason Bateman (Marc Loring), Jennifer Garner (Vanessa Loring), Olivia Thirlby (Leah), Michael Cera (Paulie Bleeker), J.K. Simmons (Mac MacDuff), Allison Janney (Bren MacDuff) und andere Kleinstädter in kurzen, gelben Shorts*
[Offizielle Homepage](http://www.juno-derfilm.de/)

Juno ist 16, hat ein ungeheuer loses Mundwerk und sich dummerweise gleich beim ersten Mal eine Schwangerschaft eingefangen. Mutter zu sein kommt für sie noch nicht in Frage, also muss zwischen Abtreibung und Freigabe zur Adoption entschieden werden. Nach einem kurzen Besuch in der Abtreibungsklinik wird diese Option jedoch schnell verworfen und Juno macht sich auf die Suche nach den richtigen Eltern für ihr Kind. Diese scheinen mit Vanessa und Jason schnell gefunden, doch bis zur Geburt liegen noch einige Wochen vor allen Beteiligten...

Einen Oscar für das beste Original-Drehbuch hat dieser Film eingeheimst - dies muss eindeutig an den messerscharfen Dialogen dieser auf Independent getrimmten Komödie liegen. Diese waren es auch, die mich in einem Trailer überzeugten, den thematisch nicht auf meiner Wellenlänge liegenden Film doch im Kino anzusehen. Und ich muss sagen, Regisseur Jason Reitman hat sich zu *Thank you for smoking* noch gesteigert und der Besuch hat sich gelohnt.

Das Tempo und die Schärfe der Dialoge liegt durchgängig auf Woody-Allen-Niveau und gerade der unbekümmerte Umgang mit dem Thema junge Schwangerschaft überzeugt. Allerdings unterbricht der Film nur selten den Wortschwall um kurz anzuhalten und den Charakteren einmal Zeit zu geben, kurz zu resümieren. So sieht man Juno nie auch nur den geringsten Ansatz an Problemen mit der Schwangerschaft an; dieses Thema wird außer bei Oberflächlichkeiten wie dem gestiegenen Bauch- und Brustumfang nie angesprochen. Auch die Frage, ob man ein Kind neun Monate lang in sich wachsen lassen und es dann sofort weggeben kann, bleibt bis zu Junos Tränen am Ende des Films unbeantwortet. Die Schwangerschaft ist also eher Auslöser als Inhalt der Dialoge mit Freundin, Eltern und der Adoptivfamilie.

Der Umgang aller Beteiligten untereinander und deren Konstellation dagegen überzeugt, wobei der Film ständig in der Nähe Junos bleibt. Sie ist die treibende Kraft und weiß ihre Schwächen sehr gut hinter einem für das Alter ungewöhnlichen Wortwitz zu verstecken. Und wenn ihr dabei "Fehler" wie die Schwangerschaft unterlaufen, dann versucht sie diese mit derselben Kraft zu korrigieren. Interessant wird dies bei der Beziehung zu dem zukünftigen Vater ihres Kindes, Marc. Dieser scheint auf den ersten Blick wie geschaffen für die Rolle, gibt es doch so viele Interessen, die sich überschneiden. Erst viel zu spät bemerkt sie, dass er genau wie sie nicht bereit für das Kind ist, und steht jetzt vor der folgenschweren Entscheidung: Soll sie ihre Träume von der idealen Familie für das Kind aufgeben und Vanessa glücklich machen, die zumindest mitten im Leben steht, oder kurz vor der Geburt den "Fehler" mit der Adoptivfamilie rückgängig machen?

Fazit: *Juno* ist eine erfrischende Komödie, bei der alles zusammenpasst: gute Darsteller, ein pointiertes Drehbuch, nette Musik und ein Regisseur, der genau das richtige Gefühl für die Handlung hat. Dafür fehlt es etwas an Tiefgang und die jugendliche Schwangerschaft wird zu wenig thematisiert, um den Film zu etwas Besonderem zu machen. Da *Juno* dies aber gut überspielt, sollte man die Gelegenheit auf einen unterhaltsamen Abend nicht ungenutzt lassen.
