---
title: "Nicht ohne Fernbedienung"
date: "2007-12-20T23:30:56"
categories: [gedacht]
---

Mein MP3-Player [iRiver H10](http://www.iriver.eu.com/harddisc_player.html?p_id=801&L=1&view=features&color=2) (keine drei Jahre alt) macht in der letzter Zeit immer mehr Probleme. Zum Einen geht dem Akku manchmal schon nach fünf Stunden die Puste aus, zum Anderen spinnt die Kabelfernbedienung öfters einmal. Die Ausgangsbuchse an der Fernbedienung hat zudem einen Wackelkontakt und die Übertragungsgeschwindigkeit der Minifestplatte war von anfang an mies (teilweise unter 1MB/s beim Schreiben).

Also werde ich mir demnächst wohl einen neuen MP3-Abspieler zulegen. Der [Apple iPod Touch](http://www.apple.com/de/ipodtouch/) mit 16GB ist zwar richtig cool, aber ich will mich nicht an iTunes binden und bin auch nicht bereit, fast 400€ zu bezahlen. Dann doch lieber das Geld für den [Cowon iAudio 7](http://www.cowonglobal.com/product/product_i7_feature.php) ausgeben, der mit seinem (kleinen) OLED-Display und dem Riesenakku 60 Stunden Musik-Abspielen durchhalten soll und fast alles abspielt, was man auf ihn kopiert. Das preisliche Gegenstück dazu stellt SanDisk her, den neuen [Sansa View](http://www.amazon.de/SanDisk-Sansa-Tragbarer-Video-Player-schwarz/dp/B000WP1LZ6) für 200€ mit ebenfalls 16GB, dafür aber nicht so überzeugenden Kritiken. Diese sprechen dagegen für den [Sony  NWZ-A818](http://www.sony.de/view/ShowProduct.action?product=NWZ-A818&site=odw_de_DE&pageType=Overview&imageType=Main&category=NWA+WMT) mit nur 8GB. Der braucht neuerdings nicht mehr Sonys Software zum Aufspielen der Musik und ist per Drag&Drop zu befüllen - genau das, was ich brauche.

Mit der Entscheidung werde ich mir noch etwas Zeit lassen, doch eines ist all den Playern (bis auf die Apple-Modelle) gemeinsam: Es gibt im Lieferumfang und leider auch beim Zubehör keine Kabelfernbedienung. Gerade bei Sony wundert mich das, da mein alter MiniDisc-Player mich erst von den Vorteilen einer Fernbedienung überzeugt hat. Man muss nicht ständig den Player vorkramen, wenn man nur die Lautstärke an die SBahn anpassen oder kurz pausieren will, weil im Zug eine Durchsage kommt. Nur das Wechseln eines Albums oder einer Playlist beherrscht meine aktuelle [iRiver Remote](http://www.amazon.de/iRiver-Fernbedienung-f%C3%BCr-H10-schwarz/dp/B0009JK5S4) nicht, dafür ist sie gleichzeitig eine gute Verlängerung für das Kopfhörerkabel.

Also, liebe MP3-Player-Hersteller, wer mich von seinem Gerät überzeugen will sollte in den nächsten drei Monaten eine Kabelfernbedienung dazu anbieten!
