---
title: "Wallace & Gromit auf der Jagd nach dem Riesenkaninchen"
date: "2005-10-31T19:26:13"
categories: [gesehen]
---

Filme für Kinder haben im Cinemaxx eine nette Begleiterscheinung: Das Kino zeigt keinerlei Zigarettenwerbung. Damit beschränken sich die Werbespots auf gut ein Drittel und es geht schneller los mit dem eigentlichen Film. Bei W&G gab es allerdings noch eine kleine, sehr unterhaltsame Verzögerung, die durch einen weihnachtlichen Kurzfilm mit den Pinguinen aus "Madagascar" verursacht wurde. Die heimlichen Hauptdarsteller durften in gewohnt chaotischer Manier die Mission "Rettet Private" angehen und ihren vierten ~~Mann~~ Pinguin aus den Fängen einer sehr resoluten Oma und ihres Kampfpudels befreien. Rasant inszeniert und politisch unkorrekt war diese Episode genau die richtige Einstimmung für den Hauptfilm.

Nicht dass dieser es nötig gehabt hätte, denn Wallace und Gromit haben den Sprung auf die große Leinwand unbeschadet überstanden. Die Detailverliebtheit und der englische Humor in Wort, Bild und Aktion wissen auch in Kinofilmlänge und Leinwandgröße zu überzeugen. Von den seltsamen Lippen der Aristokraten über die flauschigen Ohren von Riesen-Wallace bis hin zu den kleinen Kaninchen (von denen nur das im Abspann während der Dreharbeiten zu Schaden kam) ist die gesamte Knetwelt mit einer Fülle von Details gespickt, an denen man sich gar nicht satt sehen kann.

Dazu kommen die vielen schrulligen Charaktere, die die Welt von Wallace und Gromit erst so richtig lebendig machen. Das Aardman-Studio hat seine Knettechnik inzwischen bis zur Perfektion getrieben, so dass man als Zuschauer gar nicht glauben mag, dass jedes Bild einzeln fotografiert und jede Bewegung Bild für Bild nachgebildet wurde. Nur einige wenige Effekte wie die Gehirnwellen stammen wahrscheinlich aus dem Computer.

Die Geschichte selber ist ganz gelungen, es sind aber vor allem die vielen verrückten Ideen und Anspielungen, die den Charme des Films ausmachen. Von den Wallace'schen Erfindungen, mit der "Anti Pesto" die Gärten überwacht, bis zu dem Munitionsarsenal des Vikars reicht die Palette des skurilen Inventars. Dass Wallace dann ausgerechnet für den Vorschlag, für das Riesen-Kaninchen eine Riesen-Falle zu bauen, den meisten Applaus bekommt, zeigt, dass sich der Film selber nicht zu ernst nimmt. Daneben wissen aber auch die Anspielungen auf Monster-Filme wie "Jurassic Park" oder "King Kong" zu gefallen und die rasanten Verfolgungsjagden z.B. in den Flugzeugen des Kinderkarussells (die nur mit Klötzern unter den Pedalen gegen das Davonfliegen gesichert sind).

Nur an der Auflösung des Plots hätten die Autoren noch etwas feilen können. Dass das tote Wallace-Riesenkaninchen sich nur durch den Käsegeruch wieder in Wallace zurück verwandelt, ist doch etwas übertrieben bzw einfallslos - während gleichzeitig der Erzählstrang mit der Reparatur des Gehirnwellenmanipulators total versandet. Wenigstens hat Karlchen seine Eigenschaften alle behalten, wenngleich er jetzt vielleicht andere Ambitionen als das Herumhüpfen auf der Wiese haben dürfte.

Sehr gelungen ist auch die deutsche Fassung: Die Übersetzungen von Schildern und anderen knetigen Schriftzügen passen sich nicht nur optisch sehr gut in den Film ein. Leider sind nicht alle Schriftzüge eingedeutscht wurden, was aber nur bei wenigen Schildern auffällt. Auch die Synchronsprecher wissen zu überzeugen, wobei mir vor allem Benjamin Völz als Victor aufgefallen ist (dieser ist ebenfalls die Synchronstimme von Keanu Reeves und David Duchovny).

[Offizielle Seite zum Film](http://movies.uip.de/wallaceandgromit/)
