project:
  type: website
  output-dir: docs

website:
  title: "The KingOli Blog"
  site-url: "https://kingoli.net/blog/"
  favicon: k-typewriter.png
  navbar:
    right:
      - icon: github
        href: https://github.com/TheGoodCartman
format:
  html:
    theme: minty
    css: styles.css
    date-format: "DD.MM.YYYY HH:mm"



