project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/TheGoodCartman
format:
  html:
    theme: minty
    css: styles.css



