---
title: "Machinarium"
date: "2012-11-04T22:09:59"
categories: [gespielt]
---

[Machinarium](http://amanita-design.net/games/machinarium.html) ist ein bereits 2009 erschienenes Point-and-Klick-Adventure der unabhängigen tschechischen Entwickler von [Amanita Design](http://amanita-design.net/games.html), die mir mit ihrem fantasievollen Minispielchen *Samorost* aufgefallen waren. Trotz des dank Eigenvertriebes niedrigen Preises von \$10 habe ich jedoch nicht zugegriffen, bis ich vor kurzem erfuhr, dass das Spiel auch im [PSN](http://blog.de.playstation.com/2012/09/12/game-store-update-12-september-2012/) und für iPhones und Android-Handys (besser -Tablets) veröffentlicht wurde. Und da ich gerade eine Probemitgliedschaft Playstation Plus genieße, entfielen sogar die acht Euro für das Spiel.

Dabei bin ich froh über jedes gute Adventure-Spiel, das heutzutage noch entwickelt wird. Und *Machinarium* ist eine besonderes Kleinod im übersichtlichen Angebot des Genres. Der Spieler hat die Aufgabe, einen kleinen Roboter dabei zu unterstützen, die Zerstörung der Stadt Machinarium durch eine Bande böser Androiden zu verhindern. Die Stadt ist - nomen est omen - nur von Maschinen bewohnt, wobei sich das Design eher am Steampunk orientiert und weniger futuristisch wirkt, als das Setting glauben lässt.

Die große Kunst von *Machinarium* besteht darin, diese Grundidee einer mechanischen, nur von Öl und Elektrizität lebenden Stadt in allen Aspekten des Spiels durchzuhalten. Es fängt an mit den Rätseln, die zu großen Teilen aus Logikpuzzlen bestehen, setzt sich fort beim Userinterface, das aufs Nötigste reduziert wurde, und spiegelt sich vor allem in den liebevoll designten Schauplätzen und Animationen im Retrolook wider, die zusammen mit der großartigen Soundkulisse die leicht befremdlich wirkende Atmosphäre der Maschinenstadt erzeugen.

Besonders gelungen finde ich die Idee, dass sich Sichtweite und Interaktionen am Aktionsradius des kleinen Roboters orientieren. So sind Knöpfe erst drückbar, wenn die Figur in ihre Nähe bewegt wurde und die Ärmchen lang genug dafür sind - dazu kann der Roboter sich ein wenig strecken oder zusammenfahren, um in kleine Ecken zu gelangen. Ein paar Mal nimmt der Raum, in dem sich der Roboter aufhält, nur einen Teil des Bildschirms ein. Dann ist klar, dass sich nebenan noch andere Räume befinden, die erst dann eingeblendet werden, wenn sie durch eine Tür oder ähnliches gesehen wurden.

Auf der Playstation führte die Detailfülle der Schauplätze leider dazu, dass ich auf meiner Couch näher an den Fernseher rücken musste, um jedes Detail zu erkennen. Da das Spiel komplett ohne gesprochene oder geschriebene Sprache auskommt, ist es manchmal schwer zu erkennen, was ein Gegenstand im Inventar eigentlich darstellt. Auf dem PC oder Tablet, wo der Spieler automatisch näher am Bildschirm dran ist, ist *Machinarium* besser aufgehoben.

Ein weiteres nettes Detail im Design ist das übersichtliche Inventar, das meist nur sehr wenige Gegenstände enthält. Die meisten Rätsel sind zudem auf wenige Bildschirme beschränkt - so renne ich nicht ständig in der Gegend herum weil ich nicht weiß, ob ich vielleicht irgendwo einen Gegenstand übersehen habe. Diese motivierende Eigenart der Casual Games, die ihr Erlebnis in kleine Happen zerteilen und damit auch bei wenig Zeit zwischendurch gespielt werden können, hat *Machinarium* gut auf ein mittellanges Adventure portiert.

Wer jetzt noch nicht überzeugt ist, der sollte einfach die [Demo](http://machinarium.net/demo/) ausprobieren und dann entscheiden, ob *Machinarium* die acht Euro Wert ist. Ich sage ja, denn ich hatte ein paar Stunden wirklich Spaß mit dem kleinen Roboter und seinen Knobeleien!
