---
title: "Weihnachten im Gesundheitssystem"
date: "2013-01-07T23:56:22"
categories: [gedacht,getan]
---

Dass Weihnachten mit seinen Feiertagen ein ungünstiger Zeitpunkt für Zwischenfälle ist, habe ich bereits eine Woche vorher gemerkt, als mir meine Brille herunterfiel und kein Optiker mir im alten Jahr ein neues Glas einsetzen konnte. Doch zumindest konnte ich die Brille abgeben und gemütlich zu Hause auf die Reparatur warten - mit einer Augenentzündung geht das nicht.

Genauer gesagt war nicht das Auge entzündet, sondern der Tränenkanal im Bereich des Tränensacks. Die ersten Schmerzen traten schon am 23. auf, doch bis zum 24. hatten sich die Entzündung auf das untere Lid ausgebreitet, so dass ich ärztlichen Rat konsultieren wollte. Da ich in Halle bei meinen Eltern weilte und deren Hausarzt (wie fast alle Ärzte) über Weihnachten geschlossen hatte, ging ich vormittags direkt zum kassenärztlichen Notdienst im Krankenhaus St. Elisabeth und St. Barbara, den ich noch von meinem Kahnbeinbruch im Jahr 2004 kannte (damals war ich einer der ersten, der eine Praxisgebühr bezahlen durfte - zu Weihnachten war ich einer der letzten, die 10€ abdrücken mussten).

Dort war es erwartungsgemäß sehr voll. Ich musste mich an einer Arztzimmertür anmelden und nach einer Stunde Wartezeit - vorsorglich hatte ich genügend Lektüre eingepackt - wurde ich einer Ärztin vorgestellt. Diese war Allgemeinärztin und verwies mich deshalb an eine niedergelassene Augenärztin, die Weihnachtsnotdienst hatte. Deren Praxis lag in der kleinen Marktstraße, die mir kein Begriff war. Also griff ich zu Google Maps auf dem Handy und wurde - leider falsch - zur Brüderstraße geleitet. Dort konnte mir zum Glück eine Apothekerin den Weg weisen: Die kleine Marktstraße liegt gar nicht direkt am Markt, sondern hinter der Händelpassage.

Angekommen an dieser zweiten Station meiner weihnachtlichen Ärztetour schaute sich die Augenärztin das Problem an und konnte mir eine erste Diagnose geben: Die Tränenkanäle hatten sich entzündet, vermutlich weil die Abflusswege über die Nase verstopft sind. Eigentlich sollte sich dabei auch Eiter bilden, doch bei mir gab es keine Anzeichen dafür, so dass mich die Ärztin zur Sicherheit weiterüberwies: Im Krankenhaus Kröllwitz gibt es einen Notdienst mit Augen- und HNO-Arzt; für eine sichere Diagnose könnte ich dort auch geröntgt werden.

Also machte ich mich auf zu Station 3 am Heiligabend. Inzwischen war es Mittag geworden, so dass mir etwas der Magen knurrte - auch in der Notaufnahme schien nur eine Pausenbesetzung anwesend zu sein. So durfte ich mich an eine Schlange von vielleicht zwanzig Patienten anstellen, die nur schleppend vorankam. Es gab keine schnelle Anmeldung, sondern ich musste tatsächlich die ganze Zeit über stehen. Als ich endlich den Zettel anbringen konnte, den mir die niedergelassene Augenärztin mitgegeben hatte, ging es schließlich ganz schnell. 

Eine weitere Augenärztin bat mich in das letzte Zimmer am Gang und schaute sich meine Entzündung genau an. Sie bestätigte die Diagnose und wollte mich sofort ins Krankenhaus einweisen, damit ich die benötigten Antibiotika intravenös erhalte - ansonsten könnte die Entzündung durchaus gefährlich werden. Ein Krankenhausaufenthalt zu Weihnachten ist natürlich etwas, was ich gerne verhindern wollte (die haben ja nicht einmal WLAN!), und so konnte ich die Ärztin überreden, mir die Antibiotika in anderer Form zu verschreiben. Dafür musste ich versprechen, bei einer Zunahme der Entzündung sofort ins Krankenhaus zu gehen und mich nach der Rückkehr nach Berlin noch 2012 bei meiner Augenärztin zur Kontrolle zu melden.

Inzwischen war es 14Uhr, also schon kurz vor der Bescherung, und ich begab mich zur Apotheke am Franckeplatz - eine von drei Apotheken in Halle mit Notdienst zu Weihnachten. Diese hatte die zwei verschriebenen Antibiotika (lokal und systemisch) vorrätig, nicht jedoch die zusätzlich für Umschläge verschriebene Lösung. Da Rezepte aber nur komplett einlösbar sind, musste ich noch eine weitere Apotheke aufsuchen. Doch erst einmal begab ich mich nach Hause zu meinen Eltern für ein verspätetes Mittagessen und ließ mich danach zur Stephanus-Apotheke am Reileck fahren.

Diese konnten zwar die verschriebene Lösung liefern, aber nur in einer Konzentration von 20% (verschrieben waren 0,04%, ich hätte also 500fach verdünnen müssen) und auch erst mit einer Eilbestellung für den Abend. Da ich langsam genug hatte von Krankenhäusern und Apotheken ließ ich mir nur die Antibiotika geben und verzichtete auf die Umschläge. Jetzt konnte ich endlich zur Ruhe kommen am Heiligabend und Weihnachten mit meiner Familie feiern - wenn auch mit schmerzendem Auge und aufgrund der Antibiotika komplett ohne Alkohol.

Zurück in Berlin - ich musste am 27./28.12. arbeiten gehen - rief ich bei meiner Augenärztin an, um mich zu vergewissern, dass ihre Praxis zwischen den Feiertagen geöffnet hatte. Doch auch hier das aus Halle gewohnte Bild: Bitte wenden Sie sich an die Augenklinik im Virchowklinikum oder in Mahrzahn; wir sind ab 7.1. wieder für Sie da. Da die in Kröllwitz verschriebenen Antibiotika-Tabletten schon zur Neige gingen, entschied ich mich für das besser erreichbare Klinikum Virchow und begab mich in meiner Mittagspause am 27.12. nach Wedding.

Dort herrschte noch mehr Andrang als zu Weihnachten in Halle, so dass die Oberschwester jeden Patienten persönlich musterte, damit nur echte Notfälle bei den diensthabenden Ärzten landen. Ich konnte sie überzeugen, dass ich trotz zurückgegangener Schwellung noch ein Problem hätte, und durfte mich in den Wartesaal setzen. Es kann durchaus Stunden dauern, wurde ich vorgewarnt, doch am Ende vergingen gerade einmal 60 Minuten, bevor ich zur Vorkontrolle gebeten wurde und danach noch einmal 20 Minuten, bis ich im Zimmer der Augenärztin saß.

Diese bestätigte mir, dass die Medikamente angeschlagen hatten. Ich sollte jedoch noch eine weitere Woche die Antibiotika schlucken, damit die Entzündung komplett zurückgeht. Danach solle meine niedergelassene Augenärztin mit einer Kochsalzlösung testen, ob die Tränenkanäle frei sind. Denn als Damoklesschwert schwebte eine OP über mir, um die verstopften Kanäle von sich eventuell dort gebildeten Steinen zu befreien.

Im Gegensatz zu meinem Besuch im Hallenser Kröllwitz-Krankenhaus konnte mir die Ärztin im Virchowklinikum jedoch kein Kassenrezept für die Antibiotika geben, sondern nur ein Privatrezept auf eigene Rechnung. Dies hätte den Hintergrund, dass ich ohne Termin in die Augenklinik gekommen sei. Die Logik dahinter erschloss sich mir zwar nicht - ganz abgesehen von den mangelnden Alternativen - aber sie riet mir, ich könne das Rezept bei meinem Hausarzt in ein Kassenrezept umwandeln lassen. Also verließ ich das Virchowklinikum nach etwas über zwei Stunden mit dem guten Gefühl, dass die Entzündung gut verheilte, und dem ersten Privatrezept meines Lebens in der Hand.

Mein Hausarzt war an diesem Tag natürlich nicht mehr in der Praxis, aber laut Pförtner sollte er am folgenden Freitag, den 28.12., Sprechstunde haben. So stand ich am nächsten Morgen im Ärztehaus Friedrichshain nur um festzustellen, dass der Arzt doch nicht da war, und seine Vertretung erst später am Vormittag seine Praxis öffnet.

Für den Fall der Fälle hatte ich bereits die Ärztin im Virchowklinikum gefragt, was mich denn die Antibiotika auf eigene Rechnung kosten würde. Ich war davon ausgegangen, dass Mediziner Zugriff auf eine Arzneimitteldatenbank oder ähnliches haben. Doch die Ärztin gab die Bezeichnung des Präparats einfach bei Google ein und konnte so einen Preis von um die 30€ ermitteln. Für diesen Betrag wollte ich nicht meine Gesundheit aufs Spiel setzen und so ging ich eben ohne den Umweg über meinen Hausarzt direkt in die Apotheke. Dort musste ich erst einmal feststellen, dass auf dem Privatrezept nur der Name des Antiobiotikas stand, nicht aber die verschriebene Menge.

Auf die Frage nach Preis kam so die Gegenfrage, welche Packungsgröße ich benötige. Im Nachhinein war diese Frage überflüssig, da nur eine Größe überhaupt vorrätig war, aber die Apothekerin war scheinbar sehr genau. Dafür gab sie mir den Hinweis, die Rechnung einfach bei der Krankenkasse einzureichen - damit würde ich mir einen weiteren Arztbesuch ersparen. Ich verließ also die Apotheke mit genügend Antibiotika für eine Woche - das erste alkoholfreie Silvester seit über fünfzehn Jahren war gesichert.

Inzwischen habe ich einen Schlussstrich unter die weihnachtlichen Freuden mit meiner Entzündung gezogen. Die Antibiotika sind aufgebraucht, das Auge komplett schmerzfrei, und laut meiner Augenärztin sind die Tränenkanäle frei, so dass ich nicht operiert werden muss. Die Brille ist auch repariert und ich hoffe, dass für eine lange Zeit keine weiteren Arztbesuche nötig werden - mein Bedarf danach ist vorerst gedeckt.
