---
title: "Die Verarbeitung des Völkermords in Ruanda im populären Kinofilm amerikanischer und europäischer Prägung"
date: "2008-04-15T21:36:45"
categories: [gedacht,gesehen]
---

Eigentlich schreibe ich ungern über Filme, die ein so ernster Thema wie den [Genozid in Ruanda](http://de.wikipedia.org/wiki/Völkermord_in_Ruanda) behandeln. Meist reicht es aus, die Ereignisse sich einfach selber erzählen zu lassen, um der Ernsthaftigkeit und Eindrücklichkeit der noch so jungen Geschichte gerecht zu werden. Sowohl [Hotel Uranda](http://www.mgm.com/ua/hotelrwanda/) als auch [Shooting Dogs](http://www.shootingdogs-derfilm.de/), die in den letzten Wochen im Fernsehen liefen, haben sich da nichts vorzuwerfen. Es gibt jedoch Details, die mir beim Sehen auffielen und die ich kurz besprechen will.

Beiden Filmen ist gemein, dass sie reale Geschichten aus fast dem selben Zeitrahmen in Ruanda erzählen, vom Abschuss des Präsidentenflugzeugs über den Rückzug der Ausländer bis zum fast vollständigen Abzug der Blauhelmsoldaten, weil sich der UN-Rat der Betitelung als "Völkermord" verweigert. Ebenso spielen sie jeweils in einem Zufluchtsort der Tutsis, die durch die Präsenz der Blauhelme dort zeitweise vor den Milizen der Hutus in Sicherheit waren. Die Kritik am Rückzug der UN-Truppen mit seinen Konsequenzen ist demtsprechend deutlich und wird jeweils durch einen Befehlshaber mit Gewissensbissen repräsentiert (Colonel Oliver/Capitaine Charles Delon in Anlehnung an General Roméo Dallaire). Als Zuschauer ist man zudem in keinem der Filme vor einigen expliziten Mordszenen oder dem Anblick hunderter Leichen sicher; die Greuel des Genozids werden zehn Jahre nach den Ereignissen mehr als deutlich.

Die Unterschiede finden sich unter anderem in den Hauptcharakteren. *Hotel Uranda* hat einen unfreiwilligen Helden, der hollywood-typisch eine "guter" Hutu ist und damit auch ein Happy-End vergönnt ist, während bei *Shooting Dogs* die Rollen nicht so klar verteilt sind. Christopher, lange Zeit schon in christlicher Mission in Afrika unterwegs, versucht sein Möglichstes zur Rettung der Flüchtlinge und bleibt auch nach Abzug der Truppen im Land, bezahlt dies aber auch mit dem Leben. Der junge Lehrer Joe dagegen nutzt die letzte Chance, das Land zu verlassen, wird jedoch fünf Jahre später als gebrochener Mann gezeigt, der sein eigenes Leben rettete und dabei das Versprechen gegenüber einer Tutsi-Freundin brach. In diesem Charakter spielt sich der Vorwurf gegenüber der UN im Kleinen wieder ab - das Versprechen der Friedenssicherung wurde gebrochen, und sehr viele Menschen bezahlten dies mit dem Leben.

Auch in der Nebenrolle der CNN-Reporterin wird ein Vorwurf gegenüber der westlichen Welt laut. In einer Szene sitzt sie mit Joe zusammen und erzählt ihm verstört, dass dieser Massenmord im Gegensatz zum Bosnienkrieg ihr Mitleid nicht weckt, weil in Ruanda die Toten durch ihre Hautfarbe nicht so an eigene Verwandte erinnern wie die toten Europäer in Jugoslawien. Dass sich aber unabhängig von der Hautfarbe so ein Völkermord nur mit Duldung einer passiven Mehrheit der Bevölkerung durchführen lässt, zeigen die Eltern des Nebencharakters François, eines Freundes von Joe. Dieser steigt innerhalb der Milizen schnell auf und befehligt Morde, während seine Eltern gleichzeitig auf der Terasse sitzen und Bier trinken.

Am Eindruckvollsten ist jedoch die Szene, die zum Titel *Shooting Dogs* führte. Capitaine Charles Delon (Dominique Horwitz) darf aufgrund der Friedensmission nur den Schießbefehl erteilen, wenn er angegriffen wird. Als die ersten streunenden Hunde sich an den Leichen der toten Tutsis bedienen, will er diese jedoch erschießen, um die Verbreitung von Krankheiten zu verhindern. Da fragt Christopher ihn zu Recht, ob die Hunde denn auf ihn geschossen hätten.

Der europäische Film legt also mehr Wert auf vielschichtigere Charaktere und die Verarbeitung des Genozids in Dialogen. *Hotel Ruanda* als amerikanischer Beitrag setzt dagegen eine einfachere Geschichte mit teilweise glücklichem Ende an, hat dafür aber mehr im Vorfeld des Konfliktes zu bieten. So wird gezeigt, wie massenweise Macheten als billige Mordwaffen importiert und über Radio die Hutus mit Propaganda mobilisiert werden. Schließlich wird auch deutlich, wie die organisierten Milizen zu Beginn gezielt nach vorher vorbereiteten Listen die einflussreichsten Tutsis umbrachten. Somit haben beide Filme ihre Daseinsberechtigung und ergeben zusammen einen erschütternden Einblick in den Völkermord in Ruanda.
