---
title: "The Aviator"
date: "2005-02-07T00:00:43"
categories: [gesehen]
---

*USA/Japan/Deutschland (2004)
Regie: Martin Scorsese
Darsteller: Leonardo DiCaprio (Howard Hughes), Cate Blanchett (Katharine Hepburn), Kate Beckinsale (Ava Gardner), John C. Reilly (Noah Dietrich), Alec Baldwin (Juan Trippe), Alan Alda (Senator Brewster), Ian Holm (Professor Fitz), Danny Huston (Jack Frye), Gwen Stefani (Jean Harlow), Jude Law (Errol Flynn), Adam Scott (Johnny Meyer), Matt Ross (Glenn Odekirk), Kelli Garner (Faith Domergue), Frances Conroy (Mrs. Hepburn), Brent Spiner (Robert Gross), William Dafoe (Roland Sweet) und andere Stars und Sternchen*
[Offizielle Homepage](http://www.movie.de/filme/aviator/)

Howard Hughes erbte schon als Jugendlicher die Werkzeugfabrik des Vaters. Doch anstatt dessen Arbeit weiterzuführen, steckt er alles Geld in seine wahre Liebe, das Filme drehen. Doch schon sein erstes Projekt, der Fliegerfilm "Hell's Angels", droht aufgrund der ewigen Produktion der teuerste Flop Hollywoods und der Bankrott von Hughes zu werden. Aber dann triumphiert der Film überraschend an den Kinokassen und macht seinen Regisseur zu dem begehrtesten Junggesellen der Filmmetropole. Affären mit Katharine Hepburn, Ava Gardner und etlichen Sternchen folgen; Howard Hughes ist sich für keinen Skandal zu schade. Um seiner Leidenschaft für das Fliegen unbegrenzt huldigen zu können, kauft er sich außerdem eine Fluglinie und entwickelt die schnellsten Flugzeuge der Welt.

Doch hinter all dem Glamour stecken auch dunkle Seiten. Howard entwickelt sich immer mehr zu einem Paranoiker und sein Erfolg ist vielen der etablierten Oberschicht ein Dorn im Auge. So wird er Opfer einer beispiellosen Verunglimpfungskampagne und muss sich schließlich sogar vor Gericht verantworten, als er einem Senator das Gefolge verweigert...

Ich weiß nicht, was Scorsese an Leonardo di Caprio gefressen hat, aber nach [Gangs of New York](/blog/2003/03/03/gangs-of-new-york/) darf der ehemalige Frauenschwarm erneut eine wichtige Hauptrolle in einem Film des Meisters übernehmen. Doch diesmal schafft er es auch, seinem Charakter Kontur zu geben und die Rolle des Howard Hughes auszufüllen. Man nimmt ihm sowohl den jungen, aufstrebenden Regisseur und Produzenten ab als auch die Wandlung hin zum immer mehr in sich gekehrten Eigenbrötler, den nur noch seine Sturheit aus dem kleinen, privaten Kinosaal hevorlocken kann. Di Caprio findet dabei für alle Seiten des Multitalents den richtigen Ausdruck und macht dem Zuschauer klar, wie Howard Hughes hin und her gerissen ist zwischen der Kraft, Dinge zu bewegen und der Unsicherheit, die er dank der Erziehung durch seine Mutter seit der Kinheit mit sich herum trägt. 

Doch dieser Film hat mehr zu bieten als nur einen gut aufgelegten Hauptdarsteller. Im Vergleich der Biographien der großen Regisseure kann Scorsese gegen Stones [Alexander](/blog/2005/01/10/alexander/) in allen Aspekten punkten. Von der gewohnt detailierten Ausstattung über die hervorragend agierenden Schauspieler bis hin zu Drehbuch, Auswahl der Szenen und Umsetzung (die drei Stunden Film fliegen förmlich an einem vorbei) ist *The Aviator* dem Konkurrenten in allen Belangen überlegen.

Neben dem oben schon lobend erwähnten di Caprio spielt sich vor allem Cate Blanchett in den Vordergrund. Wie sie die Eigenheiten der Hepburn darstellt, ihr Verhalten imitiert und es dem Zuschauer vermittelt, ist einfach phänomenal. Doch auch in den weniger wichtigen Nebenrollen kann Scorsese fast ausschließlich auf große Namen vertrauen, wobei vor allem Jude Law als streitlustiger Errol Flynn und Ian Holm als Professor für Meterologie (der die Unterschiede von Brüsten vor dem Filmausschuss darlegen soll) im Gedächtnis bleiben.

Generell ist dem Film eine sehr angenehme Art der Komik eigen, die man von Scorsese so nicht gewohnt ist. Auf der anderen Seite fehlt *The Aviator* etwas die Konsequenz und die Ausage, die die bisherigen Filme des Meisters so eindringlich machten. Die Verfilmung des Lebens von Howard Hughes ist zwar spannend und die vielen Seiten des Charakters sind durchaus interessant, aber der Handlungsstrang rund um den Glamour von Hollywood gibt dem Film einen etwas oberflächigen Touch.

Thematisch ist der Film hervorragend ausgearbeitet. Die drei zentralen Aspekte von Hughes, der Film, die Frauen und die Flugzeuge, bekommen in etwa die selbe Zeit zugestanden; und in allen zeigt sich die mit dem Alter zunehmende und von Scorsese chronologisch dokumentierte Zerrüttung des Charakters. Schon während des Schnittes zu "Hell's Angels" wird der kleine private Vorführraum zur Zuflucht für Hughes; später wird er sich aufgrund seines Sauberkeitswahns kaum noch daraus hervorwagen. Seine Ehe mit der Hepburn wird schließlich scheitern, weil er einfach nicht von den Frauen lassen kann und sich immer neue Gespielinnen sucht - nur wenige werden wie Ava Gardner am Ende trotz seines Verfolgungswahns noch zu ihm stehen. Seine vom Perfektionswahn getriebenen Flugzeugprojekte und sein Hang, sich von niemanden aufhalten zu lassen, werden ihn schließlich zur Zielscheibe der etablierten Mächtigen machen. Doch Howard Hughes zieht noch einmal Kraft aus dieser Herausforderung und lässt sich nicht kleinkriegen, so wie er noch nie vor einer Herausforderung zurückgeschreckt ist. An diesem Zwiespalt des Charakters, der trotz oder gerade wegen seiner Willensstärke innerlich so von der Paranoia zerfressen wird, dass er am Ende bei seinem größten Triumpf von den Freunden vor der Öffentlichkeit beschützt werden muss, hangelt sich Scorsese durch die erfolgreichsten Jahre des bewegten Lebens von Howard Hughes, der bis zu seinem Tod nur noch in Hotelzimmern versteckt gelebt haben soll.

Zum Schluss will ich noch kurz auf die digitalen Effekte eingehen. Davon gibt es für einen Scorsese-Film erstaunlich viele, was wahrscheinlich auf Druck des Filmstudios zurückzuführen ist, dem die Detailliebe des Regisseurs auf dem herkömmlichen Wege wohl etwas zu teuer ist. So ist zum Beispiel das größte Flugzeug der Welt nur ein Modell im Computer, was man ihm leider aufgrund der schlechten Anpassung an die Umgebung deutlich ansieht. Ob dies nun an der mangelnden Erfahrung Scorseses liegt oder auch nicht, es fällt zumindest negativ auf. Besser gefallen können dagegen die modischen Farbspielereien, mit denen die jeweilige Filmepoche angedeutet werden soll (scheinbar eine kleine Hommage Scorseses an die Pioniere des alten Hollywood). Wenn z.B. Hughes und die Hepburn auf einem nicht wirklich grünen Golfplatz schreiten oder in den Hof des Hepburn-Anwesens fahren, so wirkt dies sehr authentisch. Seinen Teil dazu bei trägt die perfekte Ausstattung, die hinter dem eingefärbten Schleier dafür sorgt, dass auch die Details gewohnt stimmig sind.

Fazit: Eine überzeugende Filmbiographie braucht nicht nur einen spannenden Hintergrund, sondern auch eine ansprechende Umsetzung. *The Aviator* kann beides bieten: Glamour und amerikanischer Aufstiegsmythos treffen auf einen zerrütteten Charakter, der über die Jahrzehnte hinweg von Perfektionismus und Ehrgeiz getrieben immer tiefer in seiner Paranoia versinkt. Regisseur Scorsese verpasst dieser Biographie den passenden Anzug, indem er unzählige namhafte Schauspieler in einer grandiosen Ausstattung auflaufen und so das Leben des Howard Hughes in Bildern festhalten lässt. Nur ein paar mäßige digitale Effekte und die trotz der straffen Inszenierung zeitweise etwas oberflächig wirkende Handlung schmälern den Gesamteindruck und verhindern die Bestnote!
