---
title: "Slacker uprising"
date: "2008-09-28T02:55:34"
categories: [gesehen]
---

*USA (2007)
Regie & Hauptdarsteller: Michael Moore*
[Offizielle Homepage](http://slackeruprising.com/)

Dies ist die Erfolgs-Geschichte von Michael Moore, erzählt von Michael Moore: Wie er 2004 durch sechzig amerikanische Städte zog, um den Ausgang der anstehenden Präsidentenwahl zu beeinflussen. Der Film zeigt dem Zuschauer, wie der große dicke Mann in Stadien und Universitäten die Menschen zum Jubeln brachte und so viele Jugendliche wie noch nie beeinflusste, ihr Wahlrecht wahrzunehmen. Er zeigt die Freunde und Unterstützer von Michael wie Roseanne oder R.E.M., er zeigt wie Moore den Medien Moralpredigten hält, wie er mit den Anhängern der Bush-Administration umgeht und dass er sich nicht von der katholischen Kirche oder republikanischen Unternehmern einschüchtern oder von seinen Reden abhalten lässt.

Dumm nur, dass trotz dieser unglaublichen Erfolgsstory der aus Moores Sicht falsche Mann Präsident wurde. Das primäre Ziel also eindeutig verfehlt wurde. Womit sich die Frage stellt: Warum gibt es diesen Film eigentlich? Weil sich Michael Moore gern selber filmt? Und warum kommt dieser Film drei Jahre später erst in die Kinos? Auch mit der aktuellen kostenlosen Verbreitung über Tauschbörsen wird der Film das Manko nicht los, dass er genauso wie seine Wahl-Werbe-Tournee einfach das falsche Zielpublikum anspricht. Von den vielen tausend Besuchern seiner Auftritte haben sich bestimmt keine Handvoll von ihren politischen Ansichten getrennt: Die Menschen gehen zu Moore, weil sich politisiert sind, nicht weil sie sich politisieren lassen wollen. Er mag sicherlich einigen jungen Amerikanern bewusst gemacht haben, ihr Wahlrecht auch aktiv zu nutzen, aber objektiv kann dies niemand belegen. Und vor allem wird dieser Film noch viel weniger Einfluss auf die anstehende Wahl haben, denn die Bürger der USA sind [selbstbestimmtere Wähler](http://usaerklaert.wordpress.com/2008/09/16/wahlen-teil-6-gewaltenteilung-als-faktor-bei-der-prasidentenwahl/) als der Regisseur den Zuschauer wahrhaben lassen will.

Und da seine Dokumentations-Stilmitteln [bekannt](/blog/2003/06/16/bowling-for-columbine/) wie [begrenzt](/blog/2004/08/03/fahrenheit-911/) sind (den Gegner im Gegensatz zu sich selber möglichst schlecht dastehen zu lassen), gibt es eigentlich keinen Grund, diese überpatriotische Selbstbeweihräucherung überhaupt anzusehen. Teilweise treibt es Moore sogar auf die Spitze mit der ansonsten zielgruppengerechten Musikuntermalung, wenn er zum Beispiel einen seiner Auftritte mit der *Ode an die Freude* untermalt.

Fazit: Pseudo-Doku über die Wahl-Werbe-Tournee von Michael Moore 2004. Der Film beschränkt sich darauf, trotz des offensichtlichen Misserfolges den Filmer gut dastehen zu lassen. Dies ist allzu durchschaubar und deshalb lohnt sich auch bei einem kostenlosen Download das Ansehen nicht.
