---
title: "Schullektüre - eine Retrospektive"
date: "2010-01-23T20:19:57"
categories: [gelesen]
---

Abseits der Diskussionen um ein Zentralabitur durfte ich schon zu meinen Schulzeiten feststellen, dass die im Unterricht gelesenen Bücher zwar teilweise von den Empfehlungslisten des jeweiligen Bundeslandes stammen, aber zumeist die ganz subjektive Auswahl des Lehrers sind. Nur wenige Bücher des [Blogger-Kollegen]( http://sanity.madcynic.com/2010/01/13/schullekture/) aus Magdeburg wurden in meiner Klasse gelesen, aber das galt ebenso für die Parallelklasse. Der Artikel hat mich jedoch dazu angeregt, die zwangsgelesenen Bücher noch einmal hervorzukramen (ich werfe ja kein Buch weg) und die Erinnerungen daran aufzufrischen.

Los ging es auf dem Gymnasium mit Kinderbüchern, die mich genervt haben, da ich schon weitaus früher anspruchsvollere Werke aus dem Bücherschrank der Eltern gelesen habe. *Pippi Langstrumpf*, *Emil und die Detektive*, [Titus kommt nicht alle Tage](http://www.dtv.de/buecher/titus_kommt_nicht_alle_tage_70176.html) und [Die Insel der blauen Delphine](http://de.wikipedia.org/wiki/Insel_der_blauen_Delphine) haben mich weitgehend gelangweilt und deshalb keinen bleibenden Eindruck hinterlassen.

Danach kam die Phase der [Hamburger Lesehefte](http://www.verlagsgruppe.de/index.php?section=verlage&pages=lesehefte) - deutsche Klassiker in echtem Paperback, die man zu Preisen von wenigen DM erwerben konnte. So gut wie keine Erinnerungen habe ich an Gottfried Kellers *Romeo und Julia auf dem Dorfe* (*Kleider machen Leute* haben wir möglicherweise auch gelesen) und Georg Büchners *Woyzeck*. Umso mehr haben mich aber Goethes *Die Leiden des jungen Werther* und *Faust* verschreckt, da mich die Figuren nicht ansprachen und der anstrengende Stil demotivierte. Beide Werke habe ich nach ein paar Seiten weggelegt und die inhaltliche Auseinandersetzung aufgrund von Inhaltsangaben geführt.

Schon besser gefiel mir Theodor Storms *Der Schimmelreiter*. Die Novelle trumpft mit viel Atmosphäre und recht klaren Motiven der Protagonisten auf und ist nicht so auffällig wie Goethes Werke ein Kind ihrer Zeit. Damit hat sie viele Punkte bei mir gesammelt und ist in angenehmer Erinnerung geblieben. Auf ganz andere Weise hat dies Lessings *Nathan der Weise* geschafft. Der humanistische Gedanke der Toleranz als wichtigstes Thema des Dramas ist zeitlos, Jerusalem zu Zeiten der Kreuzzüge als Handlungsort interessant und eine gewisse Komik lässt sich nicht verleugnen - wie anders soll man das Ende auffassen, wo ein Liebespaar sich darüber freut, dass sie Bruder und Schwester sind. Warum aber so viel Aufhebens um die Ringparabel gemacht wird, blieb mir unerklärlich.

Verweigert habe ich mich danach Schillers *Kabale und Liebe*. Die Thematik kombiniert mit der Versform haben mich so abgeschreckt, dass ich das Büchlein einfach nicht gelesen habe und trotzdem irgendwie durch die Klassenarbeit kam.

Weiter ging es mit Hermann Hesse, der mir mit *Unterm Rad* verleidet wurde und an dessen wichtigere Werke ich mich seitdem nicht herangetraut habe. Ich habe es nicht geschafft, mich in die Hauptperson hinein zu versetzen, und so quälte ich mich durch den Absturz des jungen Helden und eine Welt, die ich nicht begreifen konnte. Erst wenn ich Zugang zu einem Roman gefunden habe, kann ich mich auch tiefer damit auseinandersetzen, doch für *Unterm Rad* war ich noch nicht reif genug und so habe ich mich dem Buch verschlossen und es sich mir.

Viel besser gefiel mir dagegen Max Frischs *Homo Faber*, schon allein weil es die erste Schullektüre seit langem war, die noch keinen Staub angesetzt hatte und in der Welt spielte, die ich selber kannte. Als mathematisch begabter Schüler habe ich mich zudem sofort mit Walter Faber identifiziert und dadurch die Handlung nicht als das wahrgenommen, was sie ist, nämlich eine Konstruktion. Dies führte zu ausgedehnten Diskussionen mit den Lehrern über die Interpretation von Fabers Schuld, die ich mit Herzblut aber ohne Argumente geführt habe. Im Nachhinein war dies eine wichtige Lektion, die ich nicht missen möchte.

Langsam war es auch an der Zeit, im Englischunterricht das eine oder andere Buch durchzunehmen. Die Lehrer waren jedoch mit Morton Rhues *The Wave* (das wir auch in Deutsch lesen mussten) und *Dead Poets Society* sehr konservativ. Beide Bücher zeichnen sich als Jugendbücher durch ihre in Schulen spielenden und deshalb für Schüler leicht verständlichen Handlungen aus, auch wenn ein wenig der Anspruch fehlte. Allerdings empfahl mir meine Englischlehrerin bereits 1997 ein Buch namens *The Lord of the Rings*, ein paar Jahre vor dem großen Hype...

Kurz vor dem Abitur durfte dann endlich Bert Brecht gelesen werden mit der Standardlektüre *Leben des Galilei*. Für mich eine dankbare Aufgabe, da sich Struktur und Inhalt dem Leser offen präsentieren. Insgesamt war die Literaturliste meiner Schulzeit aber eher langweilig, wenn auch mit positiven Ausreißern, und weitaus länger, als ich es vor dem Schreiben dieses Artikels in Erinnerung hatte. Herumgekommen bin ich um *Effi Briest*, *Die Physiker* und *Antigone*, die die schon erwähnte Parallelklasse dafür durchnahm, und den *Vorleser*, den mein Bruder fünf Jahre später an derselben Schule las - ob dies Glück oder Pech war, kann ich nicht beurteilen. Etwas neidisch bin ich dafür auf einen Berliner Kollegen, der George Orwell in Deutsch (*1984*) und auf Englisch (*Animal Farm*) lesen <del datetime="2010-01-22T22:20:25+00:00">musste</del> durfte.

Interessant aus heutiger Sicht ist vielleicht noch die Tatsache, dass die Lehrer auf der Suche nach etwas Aufmerksamkeit ihrer Schüler oft die Verfilmungen der Bücher der Klasse vorführten. Zwei Lehrer haben dabei auch versucht, den Blick auf Details der Kameraarbeit und Szenengestaltung zu lenken und mich damit animiert, mich intensiver mit dem Medium Film zu befassen. Ein großes Dankeschön dafür!
