---
title: "Paranoia"
date: "2010-11-26T21:33:46"
categories: [gedacht,gefunden]
---

Zu der aktuellen Panikmache in Sachen Terror ist schon viel gesagt worden. Doch [ein Artikel im Tagesspiegel](http://www.tagesspiegel.de/berlin/eltern-gruenden-anti-terror-einheit/3266606.html) zeigt deutlich, welche Blüten das Schüren von Ängsten treiben kann. Darin wird berichtet, wie Eltern für die JFK-Schule in Zehlendorf einen Wachdienst gegründet haben, um auf dem Pausenhof zu patrouillieren und verdächtige Personen zu befragen.

Wenn man also gegen die eigenen schwer be- wie ergründbaren Ängste nicht ankämpfen kann, dann widmet man sich einfacheren Zielen. Man steckt seine Kinder in goldene Käfige und fährt eine Überwachungsmaschine hoch, die zwar keinerlei Auswirkungen hat (die Polizei bewacht bereits die deutsch-amerikanische Schule), aber plakativen Aktionismus zeigt und so zumindest das Gefühl verleiht, etwas getan zu haben gegen die nur schwer greifbare Gefahr des weltweiten Terrorismus.

In großem Maßstab wird sich dies dann in der Wiedereinführung der Vorratsdatenspeicherung widerspiegeln. Ein teures Mittel, welches Ermittlungen nur unwesentlich unterstützt, aber die Grundrechte der Bürger massiv einschränkt und trotzdem von sogenannten Sicherheitsexperten unentwegt gefordert wird. Die wirkenden Mechanismen im Großen wie im Kleinen sind dabei die Gleichen. Ich finde es traurig, dass immer noch Menschen erhört werden, die nichts anderes können als [Wolf zu schreien](http://de.wikipedia.org/wiki/Der_Junge,_der_Wolf_schrie)...
