---
title: "Halle und seine Fußball-\"Fans\""
date: "2008-08-10T22:01:23"
categories: [gedacht,gewesen]
---

Halle ist im bundesdeutschen Fußball ein unbeschriebenes Blatt. Die Zweitligazeiten nach der Wiedervereinigung liegen lange zurück und seitdem ist selten konstant gewirtschaftet worden, so dass der HFC mit dem Aufstieg in die vierte Liga (Regionalliga) und dem Gewinn des Landespokals Erfolge wie lange nicht mehr aufweisen kann. So ein Landespokal berechtigt zum Start im DFB-Pokal, für dessen erste Runde mit Hannover 96 ein Erstligist zugelost wurde.

Die Chance also, etwas Werbung für die Stadt zu machen, denn die Partie wurde als Zusammenfassung in der ARD und sogar live auf Premiere gezeigt. Doch Halle ist ebenso wie viele andere Vereine der ehemaligen DDR-Oberliga für seine "Fans" berücksichtigt; Fanfeindschaften mit Magdeburg und Leipzig nötigen bei Spielen der Vereine gegeneinander immer ein großes Polizeiaufgebot zu Einsätzen, um Prügeleien zu verhindern. Doch gegen Hannover sollte so etwas eigentlich nicht notwendig sein, schließlich haben die Vereine erst zum dritten Mal gegeneinander gespielt.

Das Spiel lief ganz gut an; ein Drei-Klassen-Unterschied war nicht erkennbar. Halle spielte ordentlich mit, sah in direkten Zweikämpfen immer etwas schlecht aus, hatte aber auch seine Chancen. Leider war Hannover zu klever und abgeklärt, so dass nach 80 Minuten und ein paar unglücklichen Entscheidungen gegen den HFC (viele passive Abseitsstellungen, ein Elfmeter wurde nicht gegeben) es leider 4:0 für Hannover stand - bei nur sechs Chancen für den Bundesligisten.

Und dann ging es los. HFC-Fans aus der Kurve waren über die Trennzäune in den Sitzbereich der Gegentribüne geklettert und lieferten sich ein Schreiduell mit ein paar der etwa tausend angereisten Hannover-Fans über den Trennblock hinweg. Dann flogen die ersten Gegenstände zwischen den Kontrahenten, Fahnenstöcke und später auch zerstörte Schalensitze wurden geschmissen; schließlich kletterten die HFC-Fans auch noch in den Trennblock, um direkten Kontakt zu den Hannoveranern zu bekommen. Da Ordner, Stadionsprecher und die Kapitäne der Mannschaften die Unruhestifter nicht beruhigen konnten und auch Feuerwerkskörper flogen, unterbrach der Schiedsrichter die Partie und die Polizei lief als Puffer zwischen den Blöcken auf. Mit Einlauf der Polizei tauchten die randalierenden HFC-Anhänger aber schnell wieder unter in der sie deckenden Masse der Fankurve. Das Spiel konnte nach zehn Minuten Pause fortgesetzt werden und endete 5:0 für Hannover.

Damit war ausgerechnet Halle als Wiederholgungstäter die unrühmliche Ausnahme der ersten Runde des DFB-Pokals. Nirgendwo anders musste ein Spiel unterbrochen werden; die Randalierer die sich auch nach dem Spiel noch mit der Polizei anlegten haben dem Verein einen Bärendienst erwiesen. Nicht nur die Außenwahrnehmung der Stadt Halle hat durch die Berichte gelitten, sondern der HFC muss sich auch auf [Sanktionen](http://www.dfb.de/index.php?id=500014&no_cache=1&tx_dfbnews_pi1[showUid]=15310&cHash=3465bb62e6) einstellen. Nach den Punktabzügen der letzten Saison kann dies böse sportliche Folgen haben. Zudem kann man die "Fans" ja nicht ernst nehmen, die sich vor dem Spiel für den Erhalt und die Sanierung des Kurt-Wabbel-Stadions einsetzen und danach Teile davon mutwillig zerstören.

Ein trauriger Nachmittag für Halle also. Jetzt heißt es abwarten, was der DFB für eine Strafe erteilt. Der HFC, der so abhängig ist von seinen vielen Fans, die gleichzeitig die wenigen Extremisten unter ihnen decken, hat keine große Wahl. Denn wenn er gegen die Randalierer vorgeht, bleiben auch die anderen Ultras den Spielen weg. Die Hoffnung ist also immer, dass die Strafen und Aufräumarbeiten dem Verein weniger kosten, als die Einbußen bei den Eintrittsgeldern ausmachen würden. Ich persönliche verstehe diese Menschen nicht; Fans sind sie jedenfalls in keinem Fall!
