---
title: "Geheime Botschaften"
date: "2011-10-10T22:45:02"
categories: [gelesen]
---

**Die Kunst der Verschlüsselung von der Antike bis in die Zeiten des Internet**

*von Simon Singh,
erschienen im Deutschen Taschenbuch Verlag, ISBN 978-3-423-33071-8, 12,90€*

Die [Kryptografie](http://de.wikipedia.org/wiki/Kryptographie) als Kunst der Ver- und Entschlüsselung hat eine lange Tradition. Schon in der Bibel wurden einzelne Wörter durch eine einfache Geheimschrift codiert. Doch erst mit dem Ende des Mittelalters und der zunehmenden Bedeutung von Spionage und Geheimdiensten erlebte die Kryptografie ihren großen Aufschwung. In den Weltkriegen hatte sie schließlich ihre Bedeutung so weit gesteigert, dass sie Einfluss auf deren Ausgang hatte und mit dem zunehmenden Grad der Automatisierung ist sie inzwischen ein wichtiger Teil unser aller Leben geworden.

Diese Geschichte bringt Simon Singh dem Leser in einer angenehm zu lesenden Mischung aus praktischen Beispielen und historischen Anekdoten näher. Er beschreibt die Entwicklung der Kryptografie dabei als fortlaufenden Wettstreit zwischen Chiffrierern und Codeknackern und nennt für jeden Evolutionsschritt auf beiden Seiten die verantwortlichen Personen. Darunter sind so illustre Persönlichkeiten wie [Maria Stuart](http://www.phil.uni-passau.de/histhw/TutKrypto/tutorien/chiffre-stuart.htm) und [Alan Turing](http://de.wikipedia.org/wiki/Turing-Bombe), aber auch viele Köpfe, die einen weniger großen Bekanntheitsgrad haben. Und dies hat seinen Grund, wie Simon Singh gleich im Vorwort erläutert: Nur selten durften die Menschen hinter den Fortschritten in der Kryptografie darüber frei reden. Zu wichtig waren ihre Forschungsergebnisse, als dass sie dem jeweiligen Feind in die Hände fallen durften, so dass viele Kryptologen Zeit ihres Lebens nicht die Anerkennung erhielten, die ihnen eigentlich zustand.

Zumindest für die heute bekannten Verfahren holt Simon Singh dies mit seinem Buch nun nach, erläutert jede neue Erkenntnis mit der notwendigen Tiefe und schiebt ablenkende Details in den Anhang. Gerade wenn es um die Errungenschaften der modernen Verschlüsselung im Internet geht, findet er gute Bilder, um die komplexe Materie dem Leser näher zu bringen. An dieser Stelle muss ich auch die Übersetzung loben, die trotz der Schwierigkeit, dass das Knacken von Verschlüsselungen viel mit dem Wissen über die verwendete Sprache zusammenhängt, die Beispiele da, wo es notwendig ist, in der Originalform belässt und ansonsten sehr gute Übertragungen ins Deutsche gefunden hat.

So sind die unterhaltsamen 420 Seiten schneller vorbei gewesen, als mir lieb war. Ich hätte mir an der einen oder anderen Stelle noch etwas mehr Details gewünscht, wie zum Beispiel dass im zweiten Weltkrieg auch Desinformation ein probates Mittel im Informationskrieg war. Gerade bei der Erwähnung von [Ian Fleming](http://de.wikipedia.org/wiki/Ian_Fleming) hätte dieser Aspekt ein wenig mehr Beachtung verdient - schließlich ist das Streuen falscher Informationen ein Weg der Verschlüsselung der korrekten Nachricht. Doch im Endeffekt ist die Geschichte der Kryptografie - so weit heute bekannt - eine sehr kurze und gleichzeitig überraschende, die dank Simon Singhs großartiger Recherche nun allen interessierten Lesern offensteht. Ich kann dieses Buch deshalb nur empfehlen!
