---
title: "Virale Comedy"
date: "2009-11-01T23:16:17"
categories: [gesehen,gefunden]
---

[Stromberg](/blog/2009/10/29/linkschleuder/) ist natürlich nicht die erste Serie, die mit einem witzigen Homepage-Plagiat auf sich aufmerksam macht. Die englische Comedy [The IT Crowd](http://www.theitcrowd.co.uk/) hat mit [Reynholm Industries](http://www.reynholm.co.uk/) eine komplette Firmenwebsite inklusive Intranet online gestellt, auf der der geneigte Surfer auch Merchandise erwerben kann, welches nicht sofort verrät, dass es zu der Serie gehört.

Deren erste zwei Staffeln habe ich in den letzten Wochen angesehen und bin begeistert. Eigentlich weniger aufgrund des Nerd-Faktors, den eine Serie über eine IT-Support-Abteilung automatisch hat, sondern weil die Serie keine Grenzen kennt. Alles wird mit feinstem englischen Humor ins Extreme gesteigert, die nur jeweils sechs Folgen pro Staffel haben als einzigen Zusammenhang die drei Hauptpersonen. Ansonsten geht es um Dinnerparties, skurile Chefs, Goths, Frauenprobleme, Kannibalismus - alles Handlungen, die ebenso in jeder anderen Comedy und mit anderen Charakteren denkbar wären.

Doch nur die *IT Crowd* traut sich, die wilde Mischung aus Klischees und Übersteigerungen durchzuhalten und eben nicht auf den Serieneffekt zu setzen und die Charaktere zu entwickeln. Das funktioniert dank der geringen Episodenanzahl prima, und genau in der Grauzone zwischen "So stelle ich mir unsere IT vor" und "So würde man in der IT gerne arbeiten" (ich sage nur Roys [T-Shirts](http://hideyourarms.com/tag/it-crowd/)) finden sich vermutlich auch die begeisterten Zuschauer.

Wer die Serie nicht im englischen Original erleben kann (was man allerdings sollte), der hat momentan auf [Comedy Central](http://www.comedycentral.de/index.php/Shows/Detail/id/1583388/name/The%2BIT%2BCrowd) die Gelegenheit, eine deutsche Ausstrahlung zu sehen.
