---
title: "Die Straßen von Berlin"
date: "2007-12-09T17:27:32"
categories: [gedacht]
---

... machen nachts im feucht-kalten Herbst so richtig Spaß. Spiegelnder Fahrbahnbelag, mit Regenwasser gefüllte Spurrillen und die Kombination aus normalen Spurmarkierungen, gelben Baustellenstreifen und den vom Asphalt gekratzten, aber bei solchem Wetter noch deutlich sichtbaren alten Markierungen machen das Finden der richtigen Fahrspur zur Glückssache.

Noch dazu beachten Berliner auswärtige Kennzeichen nicht so wie andere Städte, was vermutlich mit dem Selbstverständnis der Hauptstädter begründet ist. Wo ein Hallenser Auto in Leipzig mit erhöhtem Sicherheitsabstand gewürdigt wird, neigt der Berliner höchstens zu einem verärgerten Hupen, wenn der vor einem fahrende Verkehrsteilnehmer nicht die selbe Zielstrebigkeit auf dem Weg nach Hause zeigt oder sich gar erdreistet, 30er-Zonen zu beachten. Dies führte auch dazu, dass ich an meinem ersten Tag mit unterschriebenem Arbeitsvertrag bei eben solchem Wetter Opfer eines Auffahrunfalls wurde - seitdem versuche ich, Kreuzberg mit dem PKW zu vermeiden.

Die Polizei dagegen weiß, wie man mit Besuchern der Stadt umgeht, und hat meinen Vater mit 58 km/h bei erlaubten 50 km/h geblitzt. Ich fühle mich in Berlin meist schon als rollendes Verkehrshindernis, wenn der Tacho keine 60 anzeigt und ich dementsprechend oft überholt werde...
