---
title: "Monsieur Ibrahim und die Blumen des Koran"
date: "2004-05-31T00:00:19"
categories: [gesehen]
---

*Frankreich (2004)
Regie: François Dupeyron
Darsteller: Omar Sharif (Monsieur Ibrahim), Pierre Boulanger (Momo/Moses), Gilbert Melki (Momos Vater), Isabelle Renauld (Momos Mutter), Lola Naymark (Myriam), Anne Suarez (Sylvie), Mata Gabin (Fatou), Céline Samie (Eva), Isabelle Adjani (Filmstar) und andere Anhänger verschiedenster Religionen*
[Offizielle Homepage](http://www.publics-pr.de/ibrahim)

Der pubertierende Jude Moses wächst im Paris der 60er Jahre auf. Seine Mutter verließ ihn und den Vater als er noch klein war, und der Vater zeigt kein Interesse an der Erziehung seines Sohnes. So führt Moses den Haushalt der beiden im Alleingang, doch mit seinen Problemen muss er selber fertig werden. Die Nutten im Bordell der Straße werden kurzzeitig zum Mutterersatz, doch dann lernt Moses den "Araber" kennen, einen Türken, der ein kleines Lebensmittelgeschäft gegenüber von Moses Wohnung führt. Ist es anfangs noch reine Neugier seitens des Jungen, so entwickelt sich bald eine väterliche Beziehung zwischen Ibrahim und Moses, die dieser so zwingend nötig hat.

Abseits von Hollywood und vor allem in Frankreich entwickelt sich wieder eine Kino-Kultur, die sich dem Geschichten-Erzählen verschrieben hat und viel Wert auf die Charaktere legt. Immer mehr dieser Filme finden mittlerweile auch den Weg in die kleinen, alternativen Kinos von Halle, und damit auch in meinen Einzugsbereich. Denn als ich Omar Sharif im Trailer sagen hörte, dass er sein Glück in der Langsamkeit gefunden hat, wusste ich dass ich diesen Film sehen muss.

Doch eigentlich dreht sich die Geschichte gar nicht um den titelgebenden Monsieur Ibrahim, sondern um Moses. Die Mutter verließ die Familie als der Sohn noch klein war, und der Vater vergleicht Moses ständig mit einem Bruder, den es nie gab, um zu zeigen, dass Moses nicht seine Vorstellungen eines Sohnes erfüllt (wobei er aber mehr mit seinem Leben nicht zurecht kommt). Trotz dieser Tatsache, ein ungewünschtes Kind zu sein, versucht er doch ständig die Aufmerksamkeit des Vaters zu gewinnen (er lässt z.B. immer das Licht in der Bibliothekt an). Erst als der Vater schließlich weg ist, kann er sich davon lösen, doch noch dessen Erwartungen zu erfüllen. An dieser Stelle wird der Einfluss von Ibrahim am stärksten, denn er nimmt fortan die Vaterrolle ein. Im Gegensatz zum alten Vater kann er dem Jungen Ratschläge erteilen, die dieser so dringend benötigt und auch erfolgreich anwendet. Nicht alle Ratschläge versteht Moses, und nicht alle begründet Ibrahim, doch für Momo ist es nur wichtig dass sich einer ihm angenommen hat und einen Pfad aufzeigt.

Doch gerade in dieser Zeit der Pubertät versucht er auch die Welt zu verstehen (und seinen Platz darin zu finden) und hinter den für einen jüdischen Franzosen so ungewöhnlichen Lebensstil des Türken zu kommen. Dieser ködert ihn mit ständigen kleinen Happen über seine Religion (den Sufismus - auch Islam ist nicht gleich Islam), schenkt ihm sogar einen Koran, um ihn dann doch wieder zu verwirren indem er angibt, seine Weisheit daraus zu haben und trotzdem nicht zwangsweise danach zu leben. Trotz allem hat er dem Jungen aber wahrscheinlich genau in dem leicht beeinflussbaren Stadium der Entwicklung den entscheidenden Hinweis gegeben, so dass dieser am Ende beschließt wie der neue Vater zu leben und dessen Rolle als "Araber" im kleinen Laden einzunehmen bzw. zu erben.

Davor steht jedoch noch die Reise der beiden in die Heimat von Ibrahim an, die dieser vor Jahrzehnten verließ. Dass sich die morgenländische Art zu leben nicht unbedingt mit der mitteleuropäischen Auffassung von strikt geregeltem Straßenverkehr verträgt, weiß jeder der schon einmal dort Urlaub gemacht hat. Dementsprechend schwer fällt es auch Ibrahim, den Führerschein für die Fahrt zu erwerben, wobei er gerade von der jüdischen Natur Moses profitiert. Denn nicht nur der Junge ist der Profiteur der ungewöhnlichen Beziehung, auch der alte Türke blüht sichtlich auf neben der Jugend und hätte die Reise in die eigene Vergangenheit wohl nie ohne Momo angetreten. Ob er dem Jungen bei seinem Abschied nun genug beigebracht hat oder nicht, auf jeden Fall hat der trotzdem recht kurze Einfluss des neuen Vaters den Weg von Moses entscheidend geprägt und ihn das Erbe des ungewünschten Kindes vergessen lassen.

Von der Optik und der der Musik ist alles in dem Film auf die 60er zugeschnitten. Die von Amerika herüberschwappende Rock'n'Roll-Musik umgibt den Zuschauer in jeder Szene, das Paris mit den engen Gassen voll von alten Autos und zeitgenössischen Filmdreharbeiten wirkt sehr authentisch. Doch am Meisten in Erinnerung bleibt die schauspielerische Leistung von Omar Sharif: Das Lächeln der alten Zähne, die leichten, vielsagenden Handbewegungen und die routinierte Mimik füllen die Figur des Ibrahim auch abseits der Dialoge mit Leben und tragen viel zum Gelingen des Films bei - der ganz nebenbei in einer Zeit des Kampfes gegen den islamistischen, fundamentalistischen Terror auch eine Lanze bricht für eine vielfältige Religion und das tolerante Zusammenleben mit ihr.

Fazit: Eine filmische Geschichte über eine interkulturelle, interreligiöse Ersatzvater-Beziehung, die von einem grandiosen Omar Sharif getragen wird. Vielen Dank für die Aussage, dass manchmal in der Langsamkeit das Glück liegt!
