---
title: "Alles so wie vorher"
date: "2008-11-03T23:30:56"
categories: [gedacht]
---

So kam es mir jedenfalls vor, als ich letztes Wochenende zur Abwechslung die Hallenser Kneipen besuchte. Die selben verqualmten Klamotten wie vor einem Jahr, die selben Probleme mit den Kontaktlinsen aufgrund der verrauchten Luft. Denn die [Entscheidung des Landesverfassungsgerichts von Sachsen-Anhalt](http://www.mz-web.de/servlet/ContentServer?pagename=ksta/page&atype=ksArtikel&aid=1224651546012&calledPageId=987490165154) hat dazu geführt, dass in den vorwiegend kleinen Kneipen meiner Heimatstadt wieder geraucht werden darf. Da die Wahl, alle Raucher auszusperren, aus Sicht der Kneipenbesitzer keine ist, wurde also nur die Essenskarte beschnitten und ein Raucherschild an die Tür gepappt; fertig ist der Status Quo von 2007.

Irgendwie verstehe ich nicht, wieso die eingeschränkte Berufsfreiheit der Betreiber die guten Ansätze eines Gesetzes zum Schutz der Gesundheit so komplett hinwegfegen kann. Iterative Verbesserungen sind wohl nicht möglich? Bis das Land das Gesetz überarbeitet hat ist meine Freiheit, abends rauchfrei weg zu gehen, auf jeden Fall deutlich eingeschränkt - vielleicht sollte ich ja auch klagen. Es bleibt zu hoffen, dass es nach diesem Rückschritt demnächst wieder vorwärts geht mit dem Schutz der Nichtraucher.
