---
title: "Inglourious Basterds"
date: "2009-09-13T22:56:04"
categories: [gesehen]
---

*USA/Deutschland (2009)
Regie: Quentin Tarantino
Darsteller: Brad Pitt (Aldo Raine), Mélanie Laurent (Shosanna Dreyfus/Emmanuelle Mimieux), Christoph Waltz (Hans Landa), Daniel Brühl (Fredrick Zoller), Diane Kruger (Bridget von Hammersmark), Til Schweiger (Hugo Stiglitz), Gedeon Burkhard (Wilhelm Wicki), Eli Roth (Donny Donowitz), Michael Fassbender (Archie Hicox), Jacky Ido (Marcel), August Diehl (Dieter Hellstrom), Sylvester Groth (Joseph Goebbels), Martin Wuttke (Adolf Hitler), Mike Myers (Ed Fenech) und andere Basterds*
[Offizielle Homepage](http://movies.universal-pictures-international-germany.de/inglouriousbasterds/)

Quentin Tarantino liebt das Kino. Bisher drückte er dies vornehmlich durch eine Unmenge an Verweisen aus, die in seinen Filme eine wichtige Rolle spielen, und der Kombinierung von Versatzstücken jeglicher Art seiner Vorbilder. Mit *Inglourious Basterds* spielt nun erstmals die zentrale Handlung in einem Kino, und dies nutzt der Meister des Trashs auf breiter Front.

Da wäre zum Einen die Liebeserklärung an die klassischen Lichtspielhäuser. Der Zuschauer wird Zeuge, wie Shosanna als Betreiberin des französischen Kinos *Le Gamaar* die Buchstaben ihrer Werbetafeln austauscht, wie sie das Filmband lagert, schneidet und im Projektorraum wechselt und wie es hinter der bestrahlten Leinwand aussieht. In der wohl schönsten Szene des Films sieht man Shosanna im Profil vor dem im Projektor durchlaufenden Film; das grelle Licht der Projektorlampe und das rote Kleid der Akteurin führen zu einem wundervollen Kontrast, der mir bis heute als Bild im Gedächtnis hängen geblieben ist. So schön kann Kino sein, und so schön kann man Kino im Kino nur präsentieren, wenn es man liebt wie Tarantino.

Die andere Seite dieser Liebeserklärung ist das Spiel mit dem Film im Film. Kinofilme können etwas bewirken, sie können sogar die Geschichte verändern. Der von Goebbels gedrehte und im *Le Gamaar* uraufgeführte Film *Stolz der Nation* ist dagegen ein billiger Propagandaschinken, ausschließlich aus Kugeleinschlägen bestehend und stinklangweilig. Dafür ist das Kino nicht geschaffen, will Tarantino sagen und spricht dabei vermutlich die aktuellen Actionblockbuster mit ihren Alibihandlungen an. Deshalb hat Shosanna für ihre Rache an den Nazis nicht nur einen Plan ausgearbeitet, wie sie mit Unterstützung des Nitrofilmbandes das gesamte Kino und damit die versammelte Naziprominenz verbrennen kann, sondern sich selber auf Film in Szene gesetzt. Wie ein Racheengel erscheint sie auf der Leinwand; die von unten auf sie gerichtete Kamera macht sie umso bedrohlicher und als das umgreifende Feuer auch von der Leinwand Besitz ergreift und ihr bedrohliches Gesicht schließlich nur noch auf den zunehmenden Rauch projiziert wird, entsteht ein erschreckend schönes Bild.

So anachronistisch dieses Ende des Films ist, so sehr verwundert der hohe Detailgrad, mit dem Tarantino den Anschein eines echten Weltkriegsfilms erweckt. Im *Le Gamaar* laufen die deutschen Propagandafilme dieser Zeit, auf den Plattenspielern singt Zarah Leander, Ausstattung und Drehorte erzeugen französisches Flair ohne aber dort gedreht worden zu sein. Die Vielsprachigkeit des Films (in der von mir gesehenen Originalversion) unterstützt diesen Eindruck ebenso wie die Auswahl der Schauspieler: Die amerikanischen Basterds werden von Amerikanern gespielt, die Nazis von Deutschen (Sylvester Groth spielt nicht zum ersten Mal Goebbels) und auch bei den Franzosen hat Tarantino zum Beispiel mit dem Glücksgriff Mélanie Laurent auf einheimische Akteure gesetzt.

Trotz der Thematik und des Zeitrahmens ist *Inglourious Basterds* aber defintiv kein (Anti-)Kriegsfilm. Vielmehr hat sich Tarantino diesmal den Italowestern als Vorbild genommen und dessen zentrale Aspekte rahmen den Film ein. Da ist natürlich das Thema Rache, welches in Form von Shosanna und dem Mörder ihrer Eltern, Hans Landa, zu Beginn eingeführt wird. Diese Rache durch die einsame Waise wird mit dem großen Feuer am Ende des Films zumindest teilweise ausgeführt und erinnert wie viele Details (z.B. dem Kapitelnamen *Once upon a time in Nazi-occupied France*, Aldo Raine als der Apache und die Skalpierung der Nazis) an die großen Werke von Sergio Leone. Passend dazu besteht der Soundtrack aus verschiedenen Stücken von Ennio Morricone, die diese Wirkung kongenial unterstützen.

Doch Tarantino wäre nicht Tarantino, wenn er diese referenzielle Perfektion nicht gleich wieder für trashige Einlagen opfern würde. So wird das drehbuchgerechte Spiel mit den drei Sprachen an einigen Stellen zu Gunsten von absichtlichen Fehlern unterlaufen. Zum Beispiel besitzen beim Wechsel vom Film-im-Film *Stolz der Nation* zu Shosannas Racheengeldarstellung plötzlich beide eine englische Tonspur, und der vielsprachige Landa kokettiert öfters einmal mit den gelogenen Aussagen, die jeweils gesprochene Sprache nicht ausreichend zu beherrschen. Im Soundtrack findet sich neben den Morricone-Stücken auch der Klassiker *Cat People* von David Bowie, der natürlich aus einem anderen Filmsoundtrack stammt. Und immer wieder gibt es krakelige Einblendungen, die dem Zuschauer einzelne Personen vorstellen. Bei Hugo Stiglitz ist diese Einführung im Stile des Blaxploitationkinos gehalten; gefolgt von einer wunderbar sinnlosen Sequenz, die seine Inhaftierung und anschließende Befreiung durch die Basterds zeigt.

Generell ist die Charakterzeichnung so falsch wie unglaubwürdig, quasi eine Ausgeburt der hintersten Trashhölle und damit in diesem Nazifilm schon wieder unglaublich cool. Aber wer wie Tarantino die Geschichte umschreibt, der benötigt auch keine Charakterzeichnung und kann ebenso Brad Pitt als brandoesken Südstaatennuschler mit Indianerfaible oder Mike Myers als englischen Geheimdienstoffizier besetzen und den von letzterem entsandten Spion in der nächsten Szene gleich wieder umkommen lassen.

Diese in einem wirren Schusswechsel gipfelnde Szene in einer französischen Kellerkneipe ist das Highlight in der Mitte des Films. Dies liegt an der fast schon klassischen Tarantino-Montage, in der in diesem Fall fünf Nazis um einen Tisch herum sitzen und "Wer bin ich" mit an den Kopf geklebten Namen spielen. Die zu erratenden Namen besitzen natürlich alle einen Filmkontext - von Edgar Wallace über Winnetou bis King Kong werden Anachronismen als popkulturelle Spielereien aneinandergereiht und zugleich das Kino der jeweiligen Dekade gehuldigt.

Fazit: Tarantino bleibt sich auch weiterhin treu. Der an den Italowestern angelehnte Rachefilm gegen die deutschen Besetzer Frankreichs lebt von seinen trashigen Charakteren und den üblichen Tarrantino-Einfällen. Im besonderen ist dieser Film aber eine Liebeserklärung an das Kino, und das macht ihn richtig gut!
