---
title: "Irgendwann in Mexico"
date: "2003-09-30T00:00:30"
categories: [gesehen]
---

*Mexiko/USA (2003)
Regie: Robert Rodriguez
Darsteller: Johnny Depp (Sands), Antonio Banderas (El Mariachi), Salma Hayek (Carolina), William Dafoe (Barillo), Mickey Rourke (Billy), Enrique Iglesias (Lorenzo), Marco Leonardi (Fideo), Rubén Blades (Jorge), Eva Mendes (Ajedrez), Danny Trejo (Cucuy), Gerardo Vigil (Marquez), Cheech Marin (Belini) und andere Mexikaner*
[Offizielle Homepage](http://www.movie.de/filme/once/)

Barillo, der Führer eines mexikanischen Drogenkartells, will den Präsidenten des Landes mit Hilfe von General Marquez und seinen Truppen stürzen. Der korrupte C.I.A.-Agent Sands will jedoch eine Militärdiktatur verhindern und spürt deshalb den Mariachi auf, den sagenumwobenen Gitarrenspieler, der noch eine Rechnung offen hat mit Marquez. Doch ausgerechnet Cucuy, die rechte Hand von Sands, läuft zum Feind über und verrät El Mariachi und plötzlich ist es Marquez, der eine alte Rechnung endlich begleichen kann...

Es ist schon lange her, dass ich den direkten Vorgängerfilm "Desperados" gesehen habe, aber Regisseur Robert Rodriguez hat ja mit "From Dusk till Dawn" ein Ausrufe-Zeichen bei mir setzen können und deshalb saß ich nun in "Irgendwann in Mexico" (wörtlich übersetzt müsste es "Es war einmal in Mexiko" heißen...).

Im Gegensatz zu seinem Vorläufer steht aber diesmal der Mariachi gar nicht so im Vordergrund. Vielmehr scheint auch er ein Spielball in den Auseinandersetzungen um den mexikanischen Präsidenten zu sein. Hier wirken nicht nur der Drogenbaron Barilla (Dafoe souverän, aber nicht überragend) und der putschende General Marquez, sondern auch das C.I.A. (Johnny Depp erneut glänzend als korrupter Agent) und das F.B.I., diverse mexikanische Gruppen inklusive der Staatspolizei und auch der Berater des Präsidenten mit. C.I.A.-Agent Sand scheint dabei im Hintergrund die Fäden zu ziehen und alles im Griff zu haben, doch am Ende muss auch er sich zugestehen, dass er die Mexikaner unterschätzt hat.

Denn der Film ist eine fantasievolle Homage des Regisseurs an sein Heimatland. Barilla mag noch so viele Sympathien im Volk haben, aber militärisch übernehmen durch das Drogenkartell lassen sich die Mexikaner deshalb noch lange nicht. Ebenso ist der amerikanische Ex-F.B.I.-Agent der Einzige, der sich wirklich von Sands manipulieren läßt, Cucuy, Ajedrez und der Mariachi dagegen haben immer noch eine Überraschung in der Hinterhand und vor allem ihren eigenen Willen.

Doch leider fehlt der recht komplexen Story eine führende Linie; Rodriguez springt gern von Charakter zu Charakter, streut Rückblenden ein und macht es dem Zuschauer vor allem im Mittelteil unnötig schwer, der Geschichte zu folgen. Außerdem wirkt der Showdown mit den üblichen wenigen Überlebenden arg konstruiert; auch hier kommt der Mariachi viel zu kurz - die eigentlichen Helden des Films sind vielmehr die Mexikaner, die dem Tag der Toten alle Ehre erweisen und den Putsch vereiteln. Ansonsten hält sich der Anteil an Action-Szenen in Grenzen, die meisten sind schnell entschieden (zum Teil zu Ungunsten des Mariachi...), aber dafür wird auch einiges Unangenehmes geboten (Augen ausstechen, Kniescheiben wegschießen etc) - die Freigabe ab 18 verdient sich der Film wirklich.

Doch auch der typische Rodriguez-Humor kommt nicht zu kurz, alleine Sands hat mehr als genug Lacher auf seiner Seite (ich sage nur der falsche Arm oder sein Lieblingsessen), wobei einige "Gags" doch sehr makaber sind, aber es liegt gar nicht im Interesse des Regisseurs, realistisch zu sein. Menschen springen einfach einmal 5 Meter in die Tiefe, ohne Schaden zu nehmen oder fliegen angeschossen erst mal durch die gesamte Vorhalle einer Kirche. Aber genau das sind die Elemente, die Rodriguez Filme so cool machen; der Regisseur, Drehbuchautor und Kameramann in Personalunion weiß immer, wie er seine Charaktere wirksam in Szene setzen und genügend Dynamik erzeugen kann.

Fazit: Die Fortsetzung der Geschichte um den schießenden Gitarrenspieler El Mariachi wurde zur Geschichte über Mexiko und einen Putschversuch. Eine Story mit Schwächen in der Umsetzung, weniger, aber dafür härteren Actionszenen und mit einem überzeugenden Schauspielerensemble!
