---
title: "Monokulturen und Einzelstücke"
date: "2009-03-12T14:48:34"
categories: [gedacht,gehört]
---

MySpace hat es endlich geschafft. Es ist für mich wieder möglich, Lieder über den eingebauten Musicplayer abzuspielen; also quasi die Seite überhaupt zu nutzen (die Social-Network-Funktionen benötige ich nicht). Ein ganzes halbes Jahr lang war mir dies verwehrt; die Gründe waren unklar. Es lag nicht am Browser, das Problem bestand über **alle** installierten Progamme (IE, FF, Opera, Safari, Chrome) hinweg. Wahrscheinlich ist ein Quereffekt meines Windoof in Zusammenspiel mit dem Flash-PlugIn (verschiedene Versionen machten keinen Unterschied) die Ursache. Beim Googeln habe ich diverse ähnlich gelagerte Fälle gefunden, auch bei MySpace war man sich der Problematik bewusst. Doch offensichtlich waren es nicht genügend verhinderte Nutzer, so dass erst jetzt mit einer neuen Version des Players alles wieder läuft.

Das wäre eigentlich ein Grund zur Freude, denn MySpace ist inzwischen aufgrund des eigenen Erfolgs ~~das Google~~ ~~die Wikipedia~~ die zentrale Community für Bands und wenn man kurz in das Repertoire einer Neuentdeckung hineinhören möchte, dann gibt es keine Alternativen: MySpace hat so ziemlich jede individuelle Bandhomepage abgelöst. Das ist sicherlich der Qualität der Features und einfachen Einrichtung einer eigenen Seite geschuldet, doch mit jedem Zentralismus steigt auch das Risiko. Zum Einen wäre bei einem Ausfall von MySpace plötzlich eine Unmenge von (vor allem kleinen) Künstlern nicht mehr im Netz vertreten, zum anderen ermöglicht MySpace es, aktiv oder passiv Kontrolle über die Inhalte auszuüben.

Ich war nur ausgesperrt, weil mein Rechner in seiner Konfiguration von der breiten Masse abweicht - er ist eben ein Einzelstück, im Rahmen der Möglichkeiten an meine Bedürfnisse angepasst. Doch Monokulturen wie bei MySpace führen dazu, dass mit steigender Zahl an Nutzern entweder mehr Energie investiert werden muss, damit auch alle erdenklichen Soft- und Hardware-Kombination unterstützt werden, oder aber eine bestimmten Konfiguration einfach vorausgesetzt wird - als Monopol könnte man sich so etwas leisten (aus genau diesem Grund besitze ich überhaupt ein Windows).

Ganz so weit ist MySpace zum Glück noch nicht, aber die erschreckend niedrige Zahl an kreativen Band-Homepages zeigt: Fast alle Künstler nehmen für das kostenlose Angebot in Kauf, dass das Portal nur den größten gemeinsamen Nenner anbietet. Ich habe sogar das Gefühl, dass es momentan Pflicht für eine Band ist, eine Seite dort zu haben. Ob sich dies positiv auf die ~~Plattenverkäufe~~ MP3-Downloads auswirkt, weiß ich nicht. Vielleicht gibt es ja sogar MySpace-Verweigerer, Rebellen des Web 2.0, die nicht Teil dieser Monokultur sein wollen. Ich hoffe es, denn je größer das Musikportal wird, desto schwerer wird es für neue Ideen, sich dagegen durchzusetzen. Und Monopole schaffen keine Innovationen...
