---
title: "Rafa - Mein Weg an die Spitze"
date: "2012-08-26T15:37:49"
categories: [gelesen]
---

*von Rafael Nadal und John Carlin,
erschienen bei Edel, ISBN 978-3-8419-0123-1, 19,95€*

Am morgigen Montag beginnen in New York die US Open, und leider fehlt ein wichtiger Spieler beim letzten Grand-Slam-Turnier des Jahres: Rafael Nadal, Sandplatzkönig und Sieger von 2010 und Finalist 2011 in Flushing Meadows. Wieder einmal fordert die hohe körperliche Belastung ihren Tribut, so dass Nadal eine längere Zwangspause einlegen muss.

Ich bin ein großer Fan von Rafa, seit er gleich bei seinem ersten Auftritt mein Lieblingsturnier, die French Open, gewinnen konnte. Im Gegensatz zu Spielern wie Federer oder Djokovic kann Nadal nicht auf ein Set von perfekten Schlagtechniken zurückgreifen, macht dies jedoch mit einer unglaublichen Physis und seinem nicht zu brechenden Willen wett. Zu Beginn seiner Karriere hat ihm niemand zugetraut, mit seinem für Sandplätze optimierten Top-Spin-Spiel auch auf anderen Belägen erfolgreich spielen zu können, doch inzwischen hat er den Lifetime-Grandslam erreicht und 2008 die Olympischen Spiele gewonnen.

Wie er dies geschafft hat erzählt er in seiner ersten Biographie, die selbst für einen Tennisspieler im Alter von gerade einmal 26 Jahren und einer noch laufenden Karriere sehr frühzeitig erscheint. Ich habe sie mir trotzdem gekauft, um mehr über diesen Menschen zu erfahren, der so toll Tennis spielt und so höflich ist, aber teilweise auf dem Platz fast autistisch wirkt und 2011 in sechs Finals gegen Novak Djokovic sechs Mal verlor und dabei - so sah es jedenfalls aus meiner Perspektive aus - jedes Mal dieselben Fehler machte.

Das Buch lässt dabei abwechselnd Nadal selber in der Ich-Form und den Journalisten John Carlin zu Wort kommen. Während Nadal sehr ausführlich von seinem ersten Wimbledon-Triumph erzählt, dabei seine Art des Tennisspiels genau erläutert und jedes Detail mit Abschnitten seines Lebens verknüpft, ergänzt Carlin viele Punkte aus Interviews mit der Familie und den wenigen anderen Freunden und Begleitern, die Nadal nahe stehen. Das Prinzip Familie des mallorcinischen Clans bestimmt auch heute noch das Leben des Tennisstars, was ihn von dem Großteil der anderen Profis fundamental unterscheidet. Noch heute wie vor 20 Jahren wird Rafa von seinem Onkel trainiert, und er wohnt weiterhin im Haus der Familie.

Erscheint es anfangs noch eine gute Idee, die Kapitel dem Spannungsbogen des Wimbledonfinals Federer - Nadal 2008 anzulehnen, ändert sich dies im letzten Drittel des Buches. Denn weiter reicht dieser rote Faden nicht und macht stattdessen Platz für andere Themen, die wild zusammengemischt erscheinen. Rafa erzählt so von seinen Siegen bei den Australian Open, US Open und Olympia. Das sind alles Themen, die mich interessiert haben, aber für die Struktur des Buches sind sie Gift.

Etwas ärgerlich finde ich zudem, dass die deutsche Übersetzung gerade bei Tennisfachbegriffen nicht immer perfekt ist, und sich auch in der von mir gelesenen zweiten Auflage einige Fehler bei Namen wie Djokovic oder del Potro eingeschlichen haben.

Als Fan des Spaniers gibt es dennoch viel zu lernen über seine Motivation, seine Ängste und sogar sein Privatleben. Wer also den Menschen und Tennisspieler Rafael Nadal verstehen möchte, der kann ruhig zugreifen. Alle anderen sollten besser warten, bis der noch junge Mann seine Karriere beendet hat und seiner Biographie etwas mehr Struktur geben kann.
