---
title: "The Hours - Von Ewigkeit zu Ewigkeit"
date: "2003-03-31T00:00:35"
categories: [gesehen]
---

*USA (2002)
Regie: Stephen Daldry
Darsteller: Nicole Kidman (Virginia Woolf), Meryl Streep (Clarissa Vaughan), Julianne Moore (Laura Brown), Ed Harris (Richard Brown), Stephen Dillane (Leonard Woolf), John C. Reilly (Dan Brown), Miranda Richardson (Vanessa Bell), Linda Bassett (Nelly Boxall), Toni Collette (Kitty), Allison Janney (Sally Lester), Claire Danes (Julia Vaughan), Jeff Daniels (Louis Waters), Eileen Atkins (Blumenhändlerin Barbara) und andere Künstler*
[Offizielle Homepage](http://www.thehoursmovie.com/)

1923: Die Schriftstellerin Virgina Woolf arbeitet an ihrem Buch "Mrs. Dalloway", einem der ersten emanzipierten Werke der Weltliteratur, doch gesundheitliche und geistige Probleme belasten ihre Arbeit immer mehr. 30 Jahre später wird genau dieses Buch von Laura Brown gelesen, die nach außen hin das perfekte Leben mit Kind, Haus und Mann lebt, doch darin nicht ihre Lebenserfüllung sieht. Beeinflusst durch das Buch will sie aus dieser ungewollten Idylle ausbrechen. 2001 schliesslich versucht Clarissa Vaughan eine kleine Party für einen befreundeten Schriftsteller zu organisieren, der an jenem Tag einen bedeutenden Preis erhalten soll. Dieser hat sie immer seine "Mrs. Dalloway" genannt und nun versucht sich Clarissa klar zu werden, wieviel davon wirklich in ihr steckt und ob ihr Leben überhaupt das ist, was sie leben möchte...

Unerwarteterweise stammt dieser Film aus Hollywood, der Traumfabrik der seichten Unterhaltung; noch dazu von Miramax, die ihre Megabudgets ansonsten eher in Explosionen anlegen. Nichtsdestotrotz ist "The Hours" anspruchsvolles Künstlerkino, garniert mit der ersten Garde an Schauspielern, die durchweg auf hohem Niveau agieren und trotzdem alle hinter der verdienten Oscar-Gewinnerin Nicole Kidman zurückbleiben. Denn diese ist nicht nur wegen der Nase, der Frisur und den weiten Klamotten nicht wieder zu erkennen, sondern weil sie so vollkommen in ihrer Rolle aufgeht und alles vorher von ihr gesehene vergessen lässt. Keine Ahnung ob die echte Virginia Woolf wirklich so war, aber das sind Fragen die sich das Drehbuch stellen musste, welches eine Adaption des Romans "Die Stunden" ist, den ich genau wie "Mrs. Dalloway" nicht gelesen habe und deshalb hier eine reine Rezension des Films vornehmen werde.

Der Film läuft parallel auf den 3 oben beschriebenen Ebenen ab, die alle mehr oder weniger nah an den Roman "Mrs. Dalloway" angelehnt sind: Es soll eine Party geben (Virginia Woolf erwartet ihre Schwester, Laura Brown feiert den Geburtstag ihres Mannes, Clarissa Vaughan möchte den Erfolg ihres Freundes Richard Brown zusammen mit seinen Freunden würdigen) und der Film beschreibt die Ereignisse dieses Tages.

Virginias größtes Problem ist dabei wohl ihr aufgewühlter Verstand, der exzentrischer nicht sein könnte und doch die Romane hervorgebracht hat, die ihren Weltruhm ausmachen. Ihr Mann versucht vieles, um den Verstand seiner Frau wenigstens in geregelte Bahnen zu lenken, doch Virginia möchte frei sein in allen Entscheidungen und wählt am Ende aufgrund der für sie nicht zu ertragenden Eingeschränktheit den Freitod.

Laura dagegen hat nie den Wunsch ihrer Freundinnen nach Haus, Kind und Mann verspürt und ist doch genau in diesen "Traum" geraten. Doch erst die Lektüre von "Mrs. Dalloway" zeigt ihr einen Ausweg aus diesem ungewollten Leben, der sie schließlich wegführt von ihrer Familie und den Verplichtungen als Hausfrau und es ihr ermöglicht, ein selbstbestimmtes Leben zu führen. Dieser Teil des Films ist wohl der seltsamste von allen dreien, denn Julianne Moore agiert anfangs, als sei sie geistig zurückgeblieben. Erst die Unterhaltung mit ihrer Freundin bringt Licht in die Situation und löst Laura auch etwas aus ihrer Resignation, dieses Leben leben zu müssen.

Tragischerweise wird gerade die starke Abhängigkeit ihres Sohnes von ihr schließlich Clarissa entscheidend beeinflussen. Denn diese war ihr Leben lang unter Künstlern zu Hause und wählte nach verschiedenen ausprobierten Lebensarten eine lesbische Beziehung inklusive Adoption einer Tochter, während sie nebenbei als Lektorin arbeitet und sich um ihren AIDS-kranken Ex Richard Brown kümmert. Doch dieser ist nicht davon überzeugt, dass Clarissa wirklich ihr Leben gefunden hat und versucht sie mit verschiedenen Sticheleien (wie sie "Mrs. Dalloway" zu nennen) dazu zu bewegen, ihren Lebensweg noch einmal zu überdenken. Doch wenngleich die Auseinandersetzung mit vielen Problemen der Vergangenheit ihr sehr zu schaffen macht, ist sie doch stark genug, nicht von dem einmal gewählten Weg abzuweichen - im Gegensatz zu Richard. Ein Leben in vollkommener künstlerischer Freiheit gewählt ist er jetzt in einer Situation der Abhängigkeit angelangt, die er nach den Enttäuschungen mit seiner Mutter nicht mehr bewältigen kann. Und da Clarissa nicht freiwillig aus seinem Leben tritt übernimmt er diesen Schritt. Dies führt dann auch zu einem Treffen von Clarissa und der alten Laura am Ende, deren beider Leben unbewusst von Virginias Buch beeinflusst und verknüpft war und die trotz ihrer sich jetzt auswirkenden Fehler in der Vergangenheit zufrieden mit dem Schritt sind, den sie gemacht haben.

Fazit: Eine Roman-Umsetzung, die vor allem handwerklich und schauspielerisch voll überzeugen kann, jedoch sehr hohe Ansprüche an den Zuschauer stellt - manchmal wäre ein Satz mehr wünschenswert gewesen, so ist eine weitere Auseinandersetzung mit dem Film auch nach dem Ende der Vorstellung unerlässlich. Nur für Intellektuelle und Künstler zu empfehlen!
