---
title: "Von Crowdfunding bis Eichinger - Gedanken zum Kinofilm"
date: "2012-07-30T23:45:05"
categories: [gedacht]
---

Ich habe es getan - ich habe zum ersten Mal auf [Kickstarter](http://www.kickstarter.com) Geld ausgegeben. Für einen Film natürlich, wie es sich für einen Filmfreak gehört. Der Film hört auf den schönen Namen [Anomalisa](http://www.kickstarter.com/projects/anomalisa/charlie-kaufmans-anomalisa) und soll ein Stop-Motion-Trickfilm nach einem Drehbuch von Charlie Kaufman werden - wenn das nicht vielversprechend klingt. Da ich der Meinung bin, es kann gar nicht genügend Stop-Motion-Filme gebe, habe ich 20$ für die Option auf einen Download investiert und warte jetzt sehnsüchtig auf das Ergebnis. Die anvisierten 200.000$ hat das Projekt auf jeden Fall schon eingesammelt.

Da wird es Zeit, dass ich mich etwas mit dem Thema Crowdfunding auseinandersetze, welches längst sein Nischendasein hinter sich gelassen hat: [Iron Sky](/blog/2012/01/31/trash-auf-der-berlinale/) wurde damit teilfinanziert und selbst scheinbare Selbstläufer wie der [Stromberg-Kinofilm](http://www.myspass.de/myspass/specials/stromberg-kinofilm/) haben diesen Weg gewählt, um das Studiosystem zu umgehen und die eigene kreative Freiheit nicht einschränken zu lassen. Oberflächlich betrachtet ist Crowdfunding also eine Art globale Befreiung der Künstler: Wer genügend Aufmerksamkeit unter den sieben Milliarden Menschen dieser Welt auf sich ziehen kann, so dass diese die Finanzierung aufbringen, muss sich keinen Beschränkungen mehr unterwerfen.

Im Umkehrschluss bedeutet dies aber auch, dass über Crowdfunding nur Filme finanziert werden, die bereits vor dem Dreh Erfolg versprechen - entweder weil bereits bekannte Persönlichkeiten daran mitwirken oder das Thema ausreichend interessant ist, um genügend Unterstützer zu mobilisieren. Mussten vorher nur wenige Menschen mit viel Geld überzeugt werden, heißt es nun möglichst viele, dafür aber kleinere Geldgeber auf die eigene Seite zu ziehen. Eperimente haben so kaum eine Chance, finanziert zu werden. Am anderen Ende der Produktionskostenskala haben es Blockbuster allerdings ebenso schwer, wie [die Schwierigkeiten von MGM](http://www.filmstarts.de/nachrichten/18469334.html) beweisen, die zeitweise nicht einmal mehr Geld für ihre Cashcows *James Bond* und die *Hobbit*-Verfilmung aufbringen konnten (Banken können so doof sein!).

Und damit bin ich bei einer kleinen Laudatio auf Bernd Eichinger angelangt, der leider letztes Jahr von uns gegangen ist. Der bekannteste deutsche Filmproduzent und -händler hat neben Blockbustern wie *Die unendliche Geschichte* und deutschen Erfolgskomödien im Stile von *Manta, Manta* auch viele Literaturverfilmungen produziert und sperrige Werke der deutschen Autorenfilmer finanziert. Viele dieser Filme waren risikoreiche Finanzierungen und hätten niemals ein vergleichbares Interesse und damit Budget über Crowdfunding gefunden, doch Eichinger zog seine Strategie durch und war erfolgreich. Einfach weil er nicht nur auf die sichere Nummer setzte und die Einspielerlöse sofort in neue Projekte investierte.

Dieses Eingehen unternehmerischer Risiken fehlt momentan auf internationaler Ebene fast vollständig. Nur so konnte sich überhaupt die Marktlücke entwickeln, die Crowdfunding ausfüllt. Doch wo im Studiosystem in Hollywood neben den Blockbustern immer noch Geld für kleinere Independentproduktionen ohne Erfolgsdruck abfiel, herrscht heute dieser Druck schon vor der Produktion. Dies erschwert es vor allem Filmen, die lokal beschränkte Geschmäcker ansprechen, auf ausreichende Finanzierungen zu kommen. Nicht überall auf der Welt gibt es eine derart ausgeprägte Filmförderung wie hierzulande, die noch dazu demokratischen Kriterien genügt. Und demokratisch heißt in diesem Fall, auch Minderheiten zu berücksichtigen und nicht nur den Geschmack der Massen.

Crowdfunding führt meiner Meinung nach also nur dazu, dass die Kriterien für Blockbuster, nämlich ein möglichst breites Publikum anzusprechen, auch auf kleinere Filme angewendet werden. Mit sieben Milliarden Menschen auf dieser Welt mag dies zwar Chancen eröffnen, aber der Raum für Experimente und das Sammeln erster Erfahrungen unter der schützenden Hand eines erfahrenen Produzenten fällt damit weg. Über kurz oder lang wird es der Nachwuchs in der Filmbranche also schwerer haben, sollte sich dieser Erfolgsdruck weiter verschärfen. So spannende Ergebnisse Crowdfunding bisher hervorgebracht hat, so sehr ist es doch ein Indiz für den Wandel in der Filmbranche. Ob zum Guten oder Schlechten, wird die Zukunft zeigen. Ein Bernd Eichinger hätte dem Film auf jeden Fall gut getan.
