---
title: "Terry Pratchett's Hogfather"
date: "2007-07-13T21:51:27"
categories: [gesehen]
---

*UK (2006)
Regie: Vadim Jean
Darsteller: Michelle Dockery (Susan Sto Helit), Marnix Van Den Broeke (Death), Ian Richardson (Voice of Death), David Jason (Albert), Marc Warren (Jonathan Teatime), Joss Ackland (Mustrum Ridcully), Nigel Planer (Mr Sideney), Nicholas Tennant (Corporal Nobbs), Shend (The Hogfather), Terry Pratchett (Toymaker), uvm*
[Offizielle Homepage](http://www.skyone.co.uk/hogfather/)

Seit dem überragenden Erfolg der drei Herr-der-Ringe-Filme sitzt das Geld bei den Produzenten etwas lockerer, wenn es um die naturgemäß etwas aufwendigeren Verfilmungen von Fantasythemen geht. Dieser Trend ist nun auch bei den Privatsendern angekommen, und so verdanken die Fans von Terry Pratchett dem englischen Kanal [Sky One](http://www.skyone.co.uk/) die erste Realverfilmung eines Scheibenweltromans (zwei Zeichentrickfilme gibt es bereits). Um eine größtmögliche Akzeptanz auch unter Nicht-Fans zu erreichen, wurde das "Weihnachts"-Buch *Hogfather* (auf deutsch *Schweinsgalopp*) ausgewählt und der Film an den Weihnachtsfeiertagen ausgestrahlt. Dank Globalisierung habe ich nun die englische DVD des TV-Zweiteilers bei mir zu Hause stehen, noch bevor wahrscheinlich Pro7 die deutsche Fassung zeigt. 

Die Geschichte, mit Terry Pratchetts Hilfe für den Film adaptiert, bleibt sehr nah an der Buchvorlage: Hogfather, der titelgebende Weihnachtsmann der Scheibenwelt, ist verschwunden, und so muss Tod seine Rolle übernehmen, damit Hogswatch (Weihnachten) nicht ausfällt und die Menschen ihren Glauben verlieren. Gleichzeitig schickt Tod seine Enkelin Susan in die Spur, die Ursache für das Verschwinden des Hogfathers zu finden und ihn schnellstmöglich zurück auf seinen Posten zu befördern. Mehr Details will ich hier gar nicht erzählen - Scheibenwelt-Fans kennen die Geschichte und alle anderen verwirre ich wahrscheinlich nur.

Dank der Länge von über drei Stunden und einem 6-Millionen-Pfund-Budget kann es sich der Film leisten, viele Details aus dem Buch zu übernehmen. So gibt es zwei Auftritte von Nobby Nobbs, der <del datetime="2007-07-13T20:20:48+00:00">leider</del> zu sehr wie ein Mensch aussieht, und neben dem Lehrpersonal der Unsichtbaren Universität haben auch Ponder Stibbons und seine Denkmaschine HEX ihre eigenen Szenen. Dagegen ist der Rattentod nur einmal kurz zu sehen und die meisten Szenen mit dem Raben wurden herausgeschnitten.

Tricktechnisch wurde ebenfalls nicht gespart; die Spezialisten für visuelle Effekte der Harry-Potter-Filme lassen auch die Scheibenwelt real werden. Nur wenige Kulissen wie das Knochenschloss des Hogfathers fallen da negativ aus der Reihe. Die Schauspieler können ebenfalls überzeugen, auch wenn manche Figuren nach dem Lesen sicherlich andere Bilder im Kopf erzeugt haben, als sie nun der Regisseur präsentiert. An die seltsam steife Maske von Tod musste ich mich aber erst gewöhnen; zumindest Bewegungen des Kiefers hätte ich schon erwartet. Doch die Stimme von Ian Richardson macht dies wieder wett, indem sie der schwarzen Kutte mit Totenlopf-Maske <del datetime="2007-07-13T20:20:48+00:00">Leben</del> Gestalt verleiht und dem Zuschauer vermittelt, was es bedeutet, in GROSSBUCHSTABEN ZU SPRECHEN. Trotzdem fand ich das HOHOHO von Tod gar nicht schlecht - der Hogfather ist schließlich auch ein alter Brummbär (genau wie Joss Ackland als Mustrum Ridcully, dessen Genuschel mir einige Schwierigkeiten bereitet hat).

Die DVD bietet neben der normalen TV-Version (leider nicht die HD-Variante) die üblichen Goodies wie Deleted Scenes und Doku/Bilder von der Produktion. Das Highlight sind jedoch die "12 days of Hogswatch": 12 kurze Episoden, in denen Tod in Gespächen mit Menschen rund um das Discworld-Franchise die wichtigsten Fakten zur Scheibenwelt erklärt - für Anfänger sicherlich ein toller Einstieg.

Fazit: Allen Fans der Scheibenwelt kann ich den Film nur ans Herz legen. Der mit einem Gastauftritt als Spielwarenhändler gewürdigte Terry Pratchett hat darauf geachtet, dass der Witz und das Flair seiner Bücher auch auf dem Bildschirm erhalten bleiben. Und so hoffe ich, dass es nicht bei diesem einen Film bleibt und ich eines Tages vielleicht sogar Rincewind auf der ganz großen Leinwand sehen darf!

