---
title: "Weekender"
date: "2007-08-12T22:20:36"
categories: [gedacht,gewesen,getan]
---

Das Wochenende fing damit an, dass ich gleich im Zug bemerkte, wo sich mein Laptop-Netzteil befand - nämlich zu Hause. Mit einem Akkuladestand von ca. 5% habe ich dann das Notebook ~~vollkommen~~ fast umsonst von Berlin nach Halle und wieder zurück geschleppt - das Wordpress-Update muss wohl noch etwas warten.

---

Samstag bin ich über Umwege bei einer Geburtstagsparty gelandet, für die die Gastgeber einen Teil des Volksparkes gemietet hatten. Nicht schlecht war auch die eingeladene Band [Back to Mama](http://www.backtomama.de), die aus Halle stammt und Stoner Rock mit psychedelischen Einflüssen spielt. Die Luft war schlecht, der Club war klein und die Band hatte ein Problem mit Rückkopplungen und zu viel tiefen Tönen, so dass nur wenige es vor der Bühne ausgehalten haben. Trotzdem haben sie mich gut unterhalten, auch weil Sänger Olli eine Stimme wie [Lemmy](http://de.wikipedia.org/wiki/Motorhead) hat.

---

Sommerbiathlon ist verwirrend, wenn man die Biathletinnen plötzlich in Shorts und ärmellosen Tops durch eine Stadt flitzen sieht. Das will irgendwie nicht passen, und ich persönlich mag auch keine Wintersportarten im Sommer...
