---
title: "Die Träumer"
date: "2004-01-19T00:00:43"
categories: [gesehen]
---

*Frankreich (2003)
Regie: Bernardo Bertolucci
Darsteller: Michael Pitt (Matthew), Louis Garrel (Theo), Eva Green (Isabelle), Robin Renucci (Der Vater), Anna Chancellor (Die Mutter) und andere Leinwandhelden*
[Offizielle Homepage](http://www.the-dreamers.com/)

Paris 1968: Als der Kultusminister Frankreichs das Kino "Cinemathèque" schließt, gehen die Studenten auf die Straße um dagegen zu protestieren. Bei einer Demonstration lernen sich auch der schüchterne amerikanische Student Matthew und die Zwillinge Theo und Isabelle kennen. Über die gemeinsame Liebe zur Leinwand lernen sie sich besser kennen und als die Eltern der inzestuös veranlagten Geschwister länger verreisen, zieht Matthew bei ihnen ein. Doch während sich andere Studenten auf den Straßen Schlachten mit der Polizei und dem Staat liefern, versinken die drei immer tiefer in ihren Spielen um Kino, sexuelle Entdeckungen und gegenseitige Abhängigkeiten...

So aktuell die Thematik der Studentenproteste von 1968 gerade wieder ist, so elegant rückt der Film genau dieses Thema in den Hintergrund. Die Demonstrationen und Straßenschlachten sind vielmehr nur der Auslöser und das Ende einer menage-à-trois, in der zwar auch über Politik philosophiert wird, aber diese nicht immer im Vordergrund steht.

Ganz im Gegenteil zum Kino, denn *Die Träumer* versteht sich auch als Hommage an die eigene Kunstform. Die beiden Zwillinge stecken voller Erinnerungen an gute und schlechte Filme; ständig spielen sie Ausschnitte nach damit der andere sie errät. Dies tuen sie jedoch nicht nur privat, sondern auch ganz öffentlich wie z.B. beim Rennen durch den Louvre, vorgemacht in "Die Außenseiterbande". Dazu spielt der Regisseur dann auch immer Original-Ausschnitte ein und versucht, die Kamera-Einstellungen zu übernehmen. 

So wird schnell klar wie wichtig der Film als Realitätsflucht für die drei Studenten ist und weshalb die 68er Unruhen in Paris gerade durch das Versperren dieser Fluchtmöglichkeit ausgelöst wurden - nimm' dem Volk Brot und Spiele, und es wird sich gegen Dich erheben! Doch die Hauptdarsteller finden sich selber eine Zuflucht vor der Realität, nämlich die elterliche Wohnung von Theo und Isabelle. Die tägliche Hausarbeit wird liegen gelassen und sich statt dessen den Experimenten hingegeben. Zu den guten Weinen des Vaters wird diskutiert, geliebt und gestritten; Matthew und Isabelle verlieren ihre Unschuld und die ungewöhnlich starke, inzestuöse Beziehung zwischen den Geschwistern wird strapaziert. Zwischen diesem Ausprobieren der im Bürgertum ungewohnten Freiheiten kommt es nur selten zum Kontakt mit der Außenwelt und den Unruhen in Paris. Doch die Proteste erreichen schließlich jeden, und so fliegt gerade dann, als Isabelle für die drei den Freitod als letzte noch auszutestende mögliche Freiheit beschließt, ein Stein durch das Fenster und plötzlich ist alles wie vorher. Die Zwillinge folgen dem Weg der Revolution, während Matthew die Gewalt für sich ausschließt und die beiden schließlich auf der Straße aus den Augen verliert.

Fazit: Ein Film über die Studentenproteste 1968, über die Liebe zum Kino und über bürgerliche und sexuelle Freiheiten. Verpackt in den Kosmos von drei Studenten lässt der Regisseur im Kleinen und Privaten die Motive und Wege der Unruhen nachvollziehen. Mit einer Prise Humor und viel Verehrung für die Kinogeschichte, aber auch schon fast pornografischer Offenheit gewürzt wird ein Stück noch relativ junge Geschichte erzählt; leider jedoch manchmal etwas zu langatmig.
