---
title: "Ein gutes Herz"
date: "2011-06-29T22:55:04"
categories: [gesehen]
---

*USA (2009)
Regie: Dagur Kári
Darsteller: Brian Cox (Jacques), Paul Dano (Lucas), Isild Le Besco (April)*
[Offizielle Homepage](http://www.eingutesherz.de/)

Jacques ist ein alter, miesgrämiger Kneipenbesitzer, der nach seinem vierten Schlaganfall im Krankenhaus aufwacht. Dort teilt er das Zimmer mit dem jugendlichen Obdachlosen Lucas, der versucht hat sich die Pulsadern aufzuschneiden, weil er sich in seiner Gutmütigkeit nicht den Anforderungen der Welt gewachsen sieht. Jacques nimmt sich dem Jungen an mit dem Ziel, dass dieser später seine Kneipe weiterführt. Doch bald schon stoßen die so verschiedenen Charaktere aneinander, denn Lucas will einfach nicht verstehen, wie Jacques mit seinen Gästen umgeht und wieso dieser so viel Wert auf seine Prozedur zum Kaffeezubereiten legt. Als Lucas dann auch noch aus Mitleid die an Flugangst leidende Stewardess April aufnimmt und kurz danach heiratet, sieht Jacques seine Zukunftspläne den Bach hinuntergehen und erleidet einen weiteren Schlaganfall...

Melancholie und ein dezenter, teils schwarzer Humor gehen in *Ein gutes Herz* eine sympathische Symbose ein. Wenn die zwei so unterschiedlichen Sichtweisen von Jacques und Lucas aufeinandertreffen, dann steht der Zuschauer als dritter Pol immer daneben und wünscht, dass sich keiner der Beiden durchsetzt. Klar ist die Konstruktion hinter den Konflikten ebenso einfach gestrickt wie das doppelte Spiel mit dem Filmtitel, aber die Sammlung an schrägen Charakteren und Handlungselementen (da sei nur die erhängte Katze genannt) lässt die skandinavische Skurilität auch in der tristen New Yorker Kneipe wirken. Da passt es ganz gut, dass das Filmende aus einem Tod ein Happy End macht und mit dem Ortswechsel nach Martinique auch farblich optimistisch abschließt.

Fazit: *Ein gutes Herz* ist kein herausragender Film, er ist einfach nur sympathisch. Ein wenig Melancholie, skurile Charaktere und etwas dunkler Humor tun niemanden weh, unterhalten aber ganz gut und wirken positiv nach.
