---
title: "Der Dativ ist dem Genitiv sein Tod"
date: "2006-03-06T23:20:53"
categories: [gelesen]
---

*von Bastian Sick,
erschienen bei Kiepenheuer & Witsch, ISBN 3-462-03448-0, 8,90€*

Dieses Buch hätte ich während meine Diplomarbeit gebraucht. Denn wie lange habe ich versucht, die Regeln der neuen Rechtschreibung (jetzt noch neuer!) zu erfahren und anzuwenden, bis ich merkte, dass mein Deutsch vielmehr von den Auswirkungen schlechter Umgangssprache und angenommener Dialekte geprägt ist. "Der Dativ ist dem Genitiv sein Tod" will dem Leser dabei helfen, solcherart Fehler zu erkennen und künftig zu vermeiden.

Doch eigentlich habe ich das Buch gar nicht in die Hand genommen, um etwas zu lernen, sondern um mich während der Lernphase für meine Abschlussprüfung etwas abzulenken. Ein Büchlein, welches nur aus kurzen Kolumnen besteht, schien da die ideale Wahl für kleine Lesehäppchen zu sein. Und da der Autor seine Aufklärung auch noch humorvoll und sprachgewandt verpackt, habe ich mich beim Lesen gut amüsiert.

Natürlich haben nicht alle Kolumnen diesselbe textliche Qualität, und manchmal habe ich mich gefragt, ob Bastian Sick einige Aspekte nicht zu genau nimmt. Schließlich gab es auch Kapitel, in denen Fehler angeprangert werden, die ich selber nie begangen oder gelesen habe. Aber insgesamt schärft das Buch die Aufmerksamkeit des Lesers auf unterhaltsame Art und Weise.

Ein wenig bemängeln möchte ich aber das Layout der Paperback-Ausgabe. Im Internet mag es dem Lesen zuträglich zu sein, dass Absätze mit einem größeren Abstand voneinander getrennt werden - in Buchform unterbricht dies den Textfluss jedoch unnötig. Zu allem Überfluss gibt es auch normal umgebrochene Absätze, ohne dass ein logischer Unterschied zu erkennen wäre. Und wo sich die Einleitung auf der [Webseite](http://www.spiegel.de/zwiebelfisch) durch Fettschrift von dem eigentlichen Kolumnentext absetzt, muss im Buch eine serifenlose Schriftart herhalten und die Unterscheidung grundlos erschweren.

Fazit: Eine Auseinandersetzung mit der deutschen Sprache muss nicht immer trocken sein. Bastian Sick beweist, wie viel Unterhaltungswert der Umgang mit Deutsch haben kann. Wer die 8,90€ jedoch nicht gleich investieren will, kann auch im Netz die aktuellen Kolumnen probelesen und dann immer noch die Sammlung zum Nachschlagen erwerben.
