---
title: "Futurama: Bender's Big Score"
date: "2008-04-10T21:52:08"
categories: [gesehen]
---

Ich bin ja ein großer Fan der Simpsons. Doch für Futurama habe ich sogar Vorlesungen geschwänzt und war dementsprechend am Boden zerstört, als die Serie eingestellt wurde. Umso mehr begeisterte mich die Idee, vier neue Folgen in Spielfilmlänge auf DVD zu veröffentlichen, und habe mir die erste davon sofort bei Veröffentlichung zugelegt ([leider besteht die deutsche Version nur aus Hülle und DVD](http://futurama-blog.de/2008/02/06/deutsches-dvd-cover/)).

Die Handlung dreht sich um eine Rasse von nackten Außerirdischen, die ein Sinnesorgan für wertvolle Informationen besitzen und es schaffen, innerhalb kürzester Zeit den Planeten Erde unter ihre Kontrolle zu bringen. Dabei entdecken sie auf Frys Hintern einen Code in der Form von Benders Kopf, der es ermöglicht, eine Zeitreiseblase zu öffnen und sich per One-Way-Ticket in die Vergangenheit zu begeben. In Anspielung auf [Marvin den depressiven Roboter](http://de.wikipedia.org/wiki/Personen_und_Lebewesen_aus_dem_Roman_Per_Anhalter_durch_die_Galaxis#Marvin) darf Bender für die Besatzer sämtliche wertvollen Gegenstände aus der Geschichte der Erde stehlen. Doch als er schließlich den vor den Außerirdischen zurück ins Jahr 2000 geflohenen Fry liquidieren soll, bekommt sogar der Roboter Gewissensbisse...

Da Co-Produzent [David X. Cohen Stanislaw Lem als eine Inspirationsquelle nennt](http://www.andreas-rauscher.de/futurama.htm), war es nur eine Frage der Zeit (und des Geldes), bis sich die Serie noch einmal ausgiebig mit dem Thema Zeitreisen beschäftigte. Gewitzt spielt *Bender's Big Score* mit verschiedenen Aspekten dieser Logikspielerei wie dem nur für die Zeit der Handlung existierenden Tattoo auf Frys Allerwertesten (siehe dazu [Sterntagebücher / Aus Tichys Erinnerungen IV](http://www.hp-gramatke.de/time/german/page0300.htm)) oder der immer weiter aufgeblähten Szene um Frys Pizzalieferung 2000 im cryogenischen Labor.

Daneben überzeugt die Analogie der Rasse der nackten Aliens mit ihren aufgeblähten Hälsen, in denen ein Organ zur Wahrnehmung von wertvollen immateriellen Daten sitzt, die jedem deutlich zeigen, dass man selbst splitternackt noch Dinge zu verbergen hat. Sie überschwemmen die Erde erst mit einer Flut von personalisierter Werbung, um danach Zugang zu den wirklich wichtigen Daten zu erlangen. Eine Auseinandersetzung mit dem Thema informationelle Selbstbestimmung in Futurama - das ist mehr, als ich erwartet hätte.

Dazu gibt es noch eine Nebenhandlung um die Beziehung von Fry und Leela; Nibbler und Zapp Brannigan wurden in die Story eingebaut und für Fans wie mich gibt es Anspielungen zu Hauf auf andere Episoden. Groening konnte sich zudem nicht verkneifen, mit der Entscheidung von Fox zur Einstellung der Serie abzurechnen. Alles in allem ist Bender's Big Score eine überdurchschnittliche Folge der Serie, wenngleich gerade am Anfang das Timing noch nicht ganz filmreif ist. Dies bessert sich aber gegen Ende, wenn die parallelen Handlungsstränge auseinander und wieder zusammen laufen, und der typische Humor der Serie muss an keiner Stelle vermisst werden. Fans können also bedenkenlos zugreifen!
