---
title: "Alice in Wonderland"
date: "2010-03-31T23:05:18"
categories: [gesehen]
---

*USA (2010)
Regie: Tim Burton
Darsteller / Sprecher: Mia Wasiskowska (Alice), Johnny Depp (Mad Hatter), Anne Hathaway (White Queen), Helena Bonham Carter (Red Queen), Stephen Fry (Cheshire Cat), Michael Sheen (White Rabbit), Alan Rickman (Blue Caterpillar) und andere Wunderländer*
[Offizielle Homepage](http://www.disney.de/DisneyKinofilme/alice/)

25 Verfilmungen (inklusive dieser) gibt es inzwischen von Lewis Carrolls Kinderbuchklassiker *Alice im Wunderland* und dessen Fortsetzung *Alice hinter den Spiegeln*; die erste Adaption erblickte bereits [1903](http://www.youtube.com/watch?v=zeIXfdogJbA) das Licht der Leinwand. Von allen diesen Filmen hat es aber nur die Disney-Zeichentrick-Version von 1951 geschafft, sich nachhaltig im pupkulturellen Gedächtnis unserer Gesellschaft festzubeißen. Da muss die Frage erlaubt sein, wie eine weitere Adaption, noch dazu erneut produziert von Disney, ihr Dasein rechtfertigt.

Auf der Habenseite findet sich auf jeden Fall Regisseur Tim Burton, der dem Film seinen unvergleichlichen Gothic-Look aufdrückt. Dieser harmoniert wunderbar mit der viktorianischen Hintergundgeschichte, die sich Drehbuchautorin Linda Woolverton ausgedacht hat, um ihrer Version des Alice-Stoffes einen Rahmen zu geben. Leider ist es nicht bei dieser Anpassung geblieben.

Alice ist nun ein neunzehnjähriges Mädchen, das mit dem Sohn eines Lords verheiratet werden soll. Doch kurz vor dem Antrag folgt sie einem in Anzug gekleideten Riesenkaninchen aus ihren Träumen in dessen Bau und gelangt so in das Wunderland. Dort gibt es nicht nur sprechende Tiere, sondern auch die Prophezeiung, dass eine Alice kommen wird um das böse Monster Jabberwocky zu besiegen und damit die Regentschaft der roten Königin zu beenden. Alice ist von der Aussicht, gegen Ungeheuer zu kämpfen, gar nicht begeistert, und begibt sich auf eine Flucht durch das Wunderland - doch Prophezeiungen kann man nicht so einfach entfliehen...

Es wurde also einiges verändert an der klassischen Geschichte. Wo Alice im Original ein kleines Mädchen ist, welches mit Unwissenheit durch eine eingebildete Fantasiewelt voller Unlogik und Absurditäten stolpert, muss sie hier einem vorbestimmten Heldenmythos folgen und am Ende in einer großen Schlacht ein Drachenwesen erschlagen. Der kindhafte Nonsens der Vorlage ist vollständig auf der Strecke geblieben und musste einem dramatischen Handlungsbogen der Mainstreamfantasy weichen. Die rote Königin ist zudem eine Mischung aus der Kartenkönigin des ersten Buches und der Schachkönigin von Teil zwei (ähnlich der ersten Disneyverfilmung), wobei das Thema des jeweiligen Spiels total untergeht.

Dies ist schon etwas enttäuschend, aber Tim Burton macht das Beste aus dem auf Massenkompatibilität getrimmten Drehbuch. Er spielt vor allem mit dem Element der ständig wechselnden Größe von Alice und ihrer Kleidung bzw den sich daraus ergebenden Perspektiven. Das ist ebenso wie die vielen verrückten Charaktere, die das Wunderland bevölkern, sehr unterhaltsam. Erstaunlich gut harmonieren diese hauptsächlich am Computer entstandenen Figuren mit den wenigen echten Schauspieler; nur selten sind die Animationen wie bei den beiden Schlössern sofort als solche zu erkennen und das erhöht die Glaubwürdigkeit des Wunderlandes doch enorm.

Ich empfehle jedoch, den Drang zu widerstehen, sich den Film in 3D anzusehen. Nur selten gibt es Aha-Erlebnisse mit der Tiefenwirkung, denn *Alice im Wunderland* wurde klassisch in 2D gedreht und erst im Nachhinein mit diesen Effekten ausgestattet. Als Konsequenz finden sich einige ständig wiederholte Kameraeinstellungen, die zwar für mehr Dreidimensionalität sorgen, aber gleichzeitig auch in ihrer Primitivität langweilen. Mir scheint es, als ob 3D-Kino momentan eher eine Einschränkung darstellt, als den Regisseuren ein neues kreatives Werkzeug in die Hand zu geben. 

Fazit: Auch wenn die neuste *Alice im Wunderland*-Verfilmung weit weg ist von Lewis Carrols Kinderbüchern und das Drehbuch stark mit gängigen Fantasy-Klischees flirtet, so hat Tim Burton doch seinen eigenen Stil in die Produktion eingebracht und dieser überzeugt wie gewohnt - skurile Charaktere und ein abgedrehtes Setting sorgen für gute Unterhaltung mit ein paar Einschränkungen.
