---
title: "A serious man"
date: "2010-01-31T23:41:32"
categories: [gesehen]
---

*USA (2009)
Regie: Joel und Ethan Coen
Darsteller: Michael Stuhlbarg (Larry Gopnik), Sari Lennick (Judith Gopnik), Aaron Wolff (Danny Gopnik), Richard Kind (Onkel Arthur), Fred Melamed (Sy Ableman), Jessica McManus (Sarah Gopnik), Adam Arkin (Scheidungsanwalt), Simon Helberg (Rabbi I), George Wyner (Rabbi II), Alan Mandell (Rabbi III) und andere Dybbuks*
[Offizielle Homepage](http://www.seriousman.de/)

Der Film beginnt mit einer Szene, die in einem mittelalterlichen, jüdischen Dorf im heutigen Polen spielt. Ein Mann kommt nach Hause und berichtet seiner Frau, dass sein Karren eine Panne hatte und ihm von einem zufällig vorbeikommenden, entfernten Verwandten geholfen wurde. Er hat den Helfer daraufhin auf eine Suppe eingeladen, doch seine Frau erklärt ihm, dass sie sicher sei, dass der Verwandte vor drei Jahren gestorben ist und er einem Dybbuk, einem bösen Geist, begegnet ist. Als dieser kurz darauf die Hütte betritt, rammt sie ihm als Beweis einen Eispickel in die Brust. Der Verwandte ist zuerst amüsiert, doch dann fängt die Wunde an zu bluten - dennoch richtet er sich auf, verabschiedet sich und verlässt das Haus.

Danach beginnt der eigentliche Film. Der Zuschauer lernt Larry Gopnik kennen, einen jüdischen Professor der Physik im Amerika der späten 60er Jahre. Er hat Haus, Frau, Kinder und einen Job, doch hinter der Fassade kriselt es: Seine Frau will ihn verlassen, räumt vorsorglich sein Konto leer und schmeißt ihn aus dem Haus. Der Sohn, kurz vor der Bar Mizwa, raucht lieber einen Joint nach dem anderen und schließt in Vaters Namen teure Platten-Abonnements ab, während die Tochter die Schule verlassen hat und sich nur noch in Discos herumtreibt.

Um das noch nicht abbezahlte Haus zu finanzieren, benötigt Gopnik dringend die Festanstellung an der Universität. Doch die mit der Entscheidung beauftragte Kommission bekommt anonyme Briefe, die ihn diskreditieren, und ein koreanischer Student will sich seine Noten bei ihm erkaufen. Zu allem Überfluss muss er auch noch seinen Bruder unterbringen, der wegen Glücksspiel und Sodomie mit der Polizei in Konflikt geraten ist. Verstört durch diese vielen Probleme sucht Larry Gopnik schließlich Rat bei drei verschiedenen Rabbis...

... und das dies bei einem Film der Coen-Brüder nicht gut ausgehen kann, sollte bekannt sein. Doch wie schon bei deren letzten Film, [Burn after reading](/blog/2008/10/12/burn-after-reading/), verweigern die Coens dem Zuschauer auch diesmal den Spaß, das fatale Ende auf der Leinwand mit zu erleben. Während im Vorgänger zumindest noch berichtet wird, wie sich das Ableben der übrig gebliebenen Figuren gestaltet, sieht man in *A serious man* das Unheil in Form eines Wirbelsturms nur noch am Horizont auftauchen. Larry Gopnik hat sich gerade dafür entschieden, das Geld des Studenten anzunehmen, und bekommt genau in diesen Moment einen Anruf von seinem Arzt.

Und an dieser Stelle findet der Film sein Ende. So ungewöhnlich sich der Einstieg mit der zusammenhangslosen Vorgeschichte gestaltet, so abrupt entlässt der Film seine Zuschauer. Hat Gopnik Krebs, wird die Bestechung aufgedeckt und stirbt sein Sohn? Der Kinogänger bleibt im Ungewissen, muss sich selbst ein Ende zusammenreimen oder akzeptieren, das die Coens einmal wieder einen kompletten Film einem Thema unterwerfen.

Denn zweimal sieht man Gopnik im Hörsaal stehen und seine Studenten unterrichten, und beide Male lehrt er ein Thema: [Schrödingers Katze](http://de.wikipedia.org/wiki/Schrödingers_Katze). Dies ist ein Bild für ein physikalisches Phänomen auf Teilchenebene, wonach eine Katze, die sich in einem geschlossenen Karton befindet, entweder tot oder lebendig ist. Wenn man nachschaut, kann man dies mit Sicherheit entscheiden, doch vorher hat die Katze das Potential, beide Zustände zugleich einzunehmen.

Übertragen auf den Film bedeutet dies, dass mit Absicht nicht offen dargestellt wird, ob der Verwandte wirklich ein Dybbuk ist oder durch den Eispickel stirbt. Und ein ausformuliertes Ende hätte ebenso Gewissheit geschaffen, also machen sich die Coens den Spaß und lassen die Katze im Karton. Dieses Prinzip findet sich im Kleinen auch in Form des Briefes mit dem Bestechungsgeld wieder. Anfangs lässt Larry ihn in seiner Schreibtischschublade, später träumt er davon, das Geld seinem Bruder zu übergeben. Und zum Schluss, mit der ersten eigenen Entscheidung, nämlich die Bestechung anzunehmen, treibt er die bis dahin zumindest unentschlossene Handlung (seine Frau kehrt gerade zurück zu ihm, der Sohn hat die Bar Mitzwa absolviert) in die fatale (?) Richtung.

Denn Larry Gopnik ist natürlich wieder ein typischer fremdbestimmter Coen-Charakter (Zitat: "Ich habe doch gar nichts getan"), ein Spielball der restlichen Figuren, welche für ihn die Entscheidungen treffen, die er aber ausbaden muss. An dieser Stelle schlägt der Film doch noch den Bogen zur Einleitung, denn auch dort ist es nicht der Mann, der herausfinden möchte, ob der Verwandte ein Dybbuk ist, sondern die Frau. Und diese möchte den Geist lieber austreiben, als mit der Ungewissheit zu leben. Larry hätte dagegen lieber nicht herausgefunden, was seine Frau, sein Bruder und seine Kinder treiben, doch anstatt damit zu leben, wie es eine anfangs genannte jüdische Weisheit empfiehlt, sucht er verzweifelt nach einem Sinn hinter den Schicksalsschlägen. So eindeutig Schrödingers Katze für ihn auf physikalischer Ebene ist, so wenig kann er mit den Potentialen in seinem Leben umgehen.

Hinter dieser sich dem Konzept unterwerfenden Handlung ist *A serious man* zumindest zeitweise eine jüdische Komödie. Allein die Besuche bei den drei Rabbis oder die bekiffte Bar Mitzwa quellen nur so vor schwarzem Humor; viele Themen des jüdischen Lebens werden von den ebenfalls jüdischen Coen-Brüdern ironisch aufgegriffen. Doch wie schon bei [The man who wasn't there](/blog/2002/01/07/the-man-who-wasnt-there/) geht dies merkbar unter in der sorgsam arrangierten Inszenierung, die zu wenig Freiraum für eine verständliche Handlung lässt. Gerade anfangs will der Funke nicht überspringen - und dann ist der Film schon vorbei, wenn er gerade in Fahrt kommt.

Fazit: Die Coen-Brüder gönnen dem Zuschauer keinen Spaß mehr im Kino. In *A serious man* muss sich alles einem Konzept unterordnen: Handlung, Humor und sogar Anfang und Ende des Films. Dies ist zwar zeitweise ganz unterhaltsam anzuschauen, verwirrt aber die restliche Zeit und hinterlässt einen zwiegespaltenen Eindruck.
