---
title: "Informationen zu Touren und anderen Einzelteilen - Ein Wir sind Helden-Tagebuch"
date: "2008-07-26T21:05:38"
categories: [gelesen]
---

*von Wir sind Helden,
erschienen bei Fischer Taschenbuch Verlag, ISBN 978-3-596-17754-7, 12,95€*

Das ist Popkultur in Reinform: Eine Band berichtet anekdotenhaft über ihren Aufstieg in den Pophimmel und bietet damit eine ungewöhnliche Perspektive auf ihre akustischen als auch visuellen Werke - in geschriebener Form. Entstanden ist dieser Überfall auf das Medium Buch aus den Online-Reportagen, die vor allem Sängerin Judith über die Jahre für die Band-Website geschrieben hat. Zwei Journalisten haben diese aufbereitet und die einzelnen Mitglieder noch einmal dazu befragt.

Herausgekommen sind dabei immerhin 400 sehr kurzweilige und unterhaltsame Seiten, die von der sympathisch-frischen Art der Helden leben. Man liest, wie die Band zusammenfand, sich in Studios verkroch, Videos drehte und vor allem viel über die Demokratie, mit der sie alle Entscheidungen durchdiskutieren (und deshalb bis heute kein Management haben). Und ich habe erfahren, wie sie sich vor dem Highfield Festival 2003 gefühlt haben, als ich sie zum ersten Mal live gesehen habe - damals, als sie auf dem Festival-Shirt noch ganz klein in der vorletzten Zeile aufgeführt wurden und kurz nach Mittag antreten mussten. Ein Jahre später waren sie schließlich an gleicher Stelle Headliner, so schnell kann es gehen.

Ab und zu lockern Bilder die Berichte und Kommentare auf. So erhält der Leser Einblicke in die Entstehung der Album-Artworks, kann die Storyboards zum Zeichentrick-Video von *Von hier an blind* bewundern und mittels Fotos sich ganz nah der Band fühlen. Ab und zu kommen auch Begleiter der Helden wie der Produzent, Roadie & Lichttechniker und sogar Thees Uhlmann von Tomte zu Wort. Letzterer trägt einen netten Vergleich zwischen den Touralltagen der beiden Bands bei (Stichwort Streichelzoo vs Rock'n'Roll).

Gegen Ende des Buches schleicht sich dann etwas Verbitterung in die Seiten, wenn der fortschreitende Untergang des klassischen CD-Musikvertriebs thematisiert wird. Dabei hat man bis dahin immer das Gefühl gehabt, dass gerade diese Band von ihren Touren und Live-Auftritten lebt. Und gleichzeitig wird einem bewusst, dass die Helden es geschafft haben, persönliche Informationen (bis auf das Baby) dem Leser über all die Seiten vorzuenthalten. Wenn man dann im Nebensatz liest, dass zwei der drei Bandhochzeiten ohne eine Erwähnung einfach übergangen wurden, dann ist man doch etwas überrascht. Da scheint es für die vier während all der Zeit also doch mehr gegeben zu haben als nur die Band. Beinahe hätten sie es geschafft, dies den Leser gar nicht merken zu lassen - so viel Privatspäre sei ihnen aber gegönnt.

Fazit: Wer schon immer einmal wissen wollte, wie der Alltag einer Popband aussieht, der sollte bei diesem Buch zuschlagen. Denn es ist sowohl authentisch als auch sehr unterhaltsam, selbst wenn nicht aus jeder Seite der Rock'n'Roll schreit. Wenn man also die Musik und vor allem die Texte der Band mag, dann kann man bedenkenlos zugreifen - Wir sind Helden sind einfach zu sympathisch, live wie in Buchform!
