---
title: "Gegen die Wand"
date: "2004-05-08T00:00:06"
categories: [gesehen]
---

*Deutschland/Türkei (2004)
Regie: Fatih Akin
Darsteller: Sibel Kekilli (Sibel Güner), Birol Ünel (Cahit Tomruk), Güven Kirac (Seref), Meltem Cumbul (Selma), Cem Akin (Yilmaz Güner), Demir Gökgöl (Yunus Güner), Aysel Iscan (Birsen Güner), Catrin Striebeck (Maren), Stefan Gebelhoff (Nico), Hermann Lause (Dr. Schiller) und andere Deutsch-Türken zwischen den Gesellschaften*
[Offizielle Homepage](http://www.gegendiewand.de/)

In einer Hamburger Klinik für Selbstmörder treffen sich Sibel und Cahit. Sie wollte dem Gefängnis der türkischen Familientradition durch Aufschneiden der Pulsadern entfliehen, er kommt mit dem Leben allgemein nicht zurecht und fuhr deshalb mit dem Auto gegen eine Wand. Widerwillig lässt er sich zu einer Schein-Hochzeit mit Sibel überreden, damit diese endlich von ihrer Familie weg und frei leben kann. Doch nach und nach krempelt sie das Leben des Einzelgängers um, bis der Ehemann sich schließlich in die Ehefrau verliebt - und wegen Morders hinter Gittern muss...

Alles in diesem Film dreht sich mehr oder weniger um die Beziehung von Deutschland (bzw. dem westlichen Europa) und der Türkei. Alle Akteure sind auf verschiedene Art und Weise davon betroffen. So singt in den Zwischensequenzen eine Gruppe auf türkisch ein Lied um einen Mann und seine unerwiderte Liebe, doch steht sie dabei vor dem Bosporus in Istanbul - der symbolischen Grenze zwischen Europa und dem nahen Osten, zwischen zwei total unterschiedlichen Gesellschaften.

Cahit, in der Türkei geboren, lebt inzwischen so lange in Deutschland, dass er seine Muttersprache nicht mehr flüssig spricht, und hat auch ansonsten den türkischen Traditionen abgeschworen - ob dies nun mit seiner Frau Katharina zu tun hat, über die nicht mehr als ein paar Worte im gesamten Film fallen, wird dem Zuschauer nie erklärt. Auf jeden Fall kommt er jedoch mit seinen Problemen der Vergangenheit nicht klar, und ist deshalb gesellschaftlich zum typischen Säufer und Drogenabhängigen abgestiegen; nur noch der Name verrät seine Herkunft. Trotz allem hat er jedoch einen Türken als besten Freund und wichtigen Gesprächspartner - ganz los lässt ihn die Heimat niemals.

Sibel dagegen lebt zwar in Deutschland, doch ihre Familie, geprägt von den fundamentalistischen Vater und Bruder, erzieht sie als lebten sie in einem türkischen Subkosmos. Zu Hause wird Türkisch gesprochen, Sibel muss die Haare geschlossen tragen und schon Händchen-Halten wird verboten. Doch gerade in dem freien Land Deutschland unfrei zu leben ist nicht Sibels Ding, und so sucht sie verzweifelt nach einem Ausweg aus diesem Leben. Nach dem versuchten Selbstmord (es wird nie richtig klar, ob sie sich bewusst immer unprofessionell verletzt oder wirklich bereit ist, aus dem Leben zu scheiden) schlägt sie jedoch einen Weg ein, der mit den Traditionen in Einklang steht - die Hochzeit mit einem anderen Türken.

An dieser Stelle kommt nun Bewegung in die Entwicklung der beiden Figuren. Sibel hat endlich die lang ersehnten Freiheiten und nutzt diese auch ausgiebig, während Cahit gerade diese Freiheit verliert, die ihn bewog sich das Leben zu nehmen. Denn eine Sibel wohnt nicht nur einfach bei jemanden, sie krempelt das gesamte Leben des Einzelgängers um. Erst wird die Wohnung eingerichtet und für ein vorzeigbareres Äußeres gesorgt, dann nimmt sie immer mehr Einfluss auf sein Leben. Sie schleppt ihn zu ihrer Familie (die ihn nur wieder in seinen Vorurteilen gegenüber der türkischen Tradition stärken, auf der anderen Seite jedoch den Wunsch nach einer Familie wecken) und mit in Kneipen und Diskos. Langsam erwacht Cahit mit neuer Lebenskraft, er schläft wieder mit Maren, die er vor seinem Selbstmordversuch noch ablehnte. Trotzdem kann er sein aufbrausendes Gemüt nicht unter Kontrolle bringen, zu schwer fällt ihm der Ausbruch aus den gewohnten Bahnen. Bis er irgendwann erkennt, dass er von Sibel akzeptiert wird und sie sein neues Leben ist, und er in einem letzten Ausbruch alles zerstört und einen Liebhaber von Sibel im Affekt tötet.

An dieser Stelle (nach immerhin schon anderthalb Stunden) verliert der Film etwas seine Linie. Der plötzliche Sprung aus Hamburg nach Istanbul und das durch die Haft bedingte Fehlen des einen Hauptcharakters bringt die Handlung aus dem Gleichgewicht. Sibel fühlt sich in der neuen Rolle als Hotelputzfrau wieder eingeengt und entflieht erneut der Familie, diesmal zu ihrer Cousine Selma, deren früher einmal bewundertes Leben als Single und Hotelmanagerin sie jetzt abschreckt. Auf der Suche nach Drogen und Exzessen übernimmt sie sich dann und muss schmerzvoll erleben, dass die Mentalität in der Türkei eine andere ist als in Deutschland.

Das Geschehen im Film wird reichlich linear erzählt, jedoch kommt es immer wieder zu Sprüngen in der Zeit. An dieser Stelle des Films erfolgt schließlich ein inhaltlicher Sprung, denn als Cahit aus der Haft entlassen wird und nach Istanbul kommt um Sibel zu suchen, hat diese geheiratet und ist inzwischen Mutter. Aus dem Neuanfang im Land ihrer Eltern, die sie aus Deutschland verstießen und am liebsten töten würden um die Familienehre zu retten (Ironie des Schicksals: Aus traditioneller Familiensicht hat Cahit richtig gehandelt, als er den Liebhaber der "ehebrechenden Frau" erschlug), wurde ein Einfügen in die klassischen türkischen Strukturen. Die selbstzerstörerische Sibel hat sich angepasst und mit der geringeren Freiheit abgefunden, jetzt wo sie das liberalere Deutschland nicht jeden Tag vor der Tür hat. Die Entwicklung der Figur ist mit dem letzten Sträuben der verdrängten Wünsche (zwei durchliebte Nächte mit Cahit) abgeschlossen. Und auch Cahit zieht es zu einem Neubeginn in die Heimat seiner Geburtsstadt, mit oder ohne Sibel. Sie hat ihm die Kraft gegeben und den Weg aufgezeigt, sein Leben zu ändern; und nun klinkt auch er sich wieder ein in die ständig kritisierte Enge der türkischen Gesellschaft. Beide Figuren sind am Ende also gescheitert - der Regisseur gönnt dem Publikum kein Happy-End im Sinne der ursprünglichen Intentionen der Hauptcharaktere.

Nach der Interpretation der Handlung will ich nun noch etwas zu der Umsetzung sagen. Der türkisch-stämmige Fatih Akin sagt über seinen Film, dass Teile seines eigenen Lebens und das seiner Haupdarsteller mit in das Drehbuch eingeflossen sind. Daher resultiert sicherlich die Authentizität, die ihn so spannend macht. Die Charaktere sind den Schauspielern so ähnlich, dass es ihnen scheinbar spielend leicht fällt, solche herausragenden darstellerischen Leistungen abzuliefern. Trotzdem ist es teilweise schwer nach zu vollziehen, wie sich die Liebe der beiden zueinander entwickelt. Der Mord im Affekt, von Cahit in Unwissenheit von Sibels Drohung an Nico ausgeführt, zeigt dass die Beziehung immer nur von außen dargestellt wird; die direkten Interaktionen der beiden enden eigentlich immer im Fiasko. Doch gerade gegen Schluss des Films, wenn alles auf ein (positives) Ende in Deutschland hindeutet, weicht der Regisseur dann von der bis dahin kraftvollen, intensiven Inszenierung ab und beendet die Entwicklung der Charaktere abrupt mit einem gewaltigen Sprung, der vom Zuschauer erst einmal verdaut werden muss.

Fazit: Ein rasanter Film über das Leben der Türken in Deutschland mit all ihren Problemen, entstanden am Treffpunkt von Tradition und neuer Liberalität, die zu Konfliktsituationen aber auch zu Liebe führen kann. Leider hat der Film kurz vor dem Ende einen kleinen Knick und auch die Charakterzeichnung ist nicht immer schlüssig.
