---
title: "Sternfahrt"
date: "2011-06-05T23:57:48"
categories: [getan]
---

Wer einmal in Berlin (legal) mit dem Fahrrad auf der Autobahn fahren möchte, dem bleiben eigentlich nur zwei Optionen: Der kürzlich ausgetragene [Velothon](http://www.skoda-velothon-berlin.de/) mit seiner ökonomischen und leistungsorientierten Ausrichtung oder die an Alltagsfahrer gerichtete und einer politischen Aussage verpflichtete [Sternfahrt](http://www.adfc-berlin.de/aktionenprojekte/sternfahrt.html) am [Tag der Umwelt](http://de.wikipedia.org/wiki/Tag_der_Umwelt). Schon allein aufgrund meines Leistungsstandes und des schlechten Zustandes meines Rades (und weil ich 60€ Startgeld zur Quersubventionierung des ProRace unverschämt finde), habe ich mich heute ab dem S-Bahnhof Landsberger Allee der Sternfahrt unter dem Motto *Freie Fahrt für freie Räder!* angeschlossen.

Die Idee des Mottos unterstütze ich dabei voll und ganz, aber die Anspielung auf *Freie Fahrt für freie Bürger* finde ich etwas misslungen. Obwohl Berlin sicherlich eine der fahrradfreundlichsten Städte Deutschlands ist, es viele Fahrradwege gibt und auch die Autofahrer auf die anderen Verkehrsteilnehmer Rücksicht nehmen, so gibt es doch immer wieder Konfliktpotential im Spannungsfeld zwischen der prekären Parkplatzsituation und den einladend freien Fahrradwegen. Dem folgt ein Verdrängungswettbewerb, meist auf Kosten der Fußgänger, denn die Fahrradfahrer müssen bei blockierten Wegen ja irgendwohin ausweichen. Dies könnte verhindert werden, wenn sich alle Teilnehmer am Straßenverkehr einfach mehr Respekt entgegenbringen und nicht versuchen, die bestehenden Probleme auf Kosten der Schwächeren zu lösen.

Heute waren die Fahrradfahrer nun diejenigen, die überall Vorfahrt hatten. Es gab keine Ampeln zu beachten und die Avus und der Britzer Tunnel auf der A100 durften befahren werden. Es musste nur das vorfahrende Polizeifahrzeug beachtet werden. Um die Sperrungen der wichtigen Verkehrsadern möglichst kurz zu halten, werden die Straßen nur während der Durchfahrt des Fahrradfeldes gesperrt und danach sofort freigegeben. Ein paar Probleme gab es am Kottbusser Tor - dort wurden Autofahrer zwischen zwei sich treffenden Korsos eingeschlossen - und an der Auffahrt zur A100 am U-Bahnhof Grenzallee. Die Sperrung der Autobahn dauerte etwas, doch nach einer halben Stunde Wartezeit in der brütenden Mittagshitze durfte ich endlich auf den Innenstadtring und durch den Britzer Tunnel mit seiner Schwarzlichtblitzanlage heizen.

Von da an gab es keine Unterbrechungen mehr und so rollte die Demo ungestört bis zu ihrem Ziel, dem großen Stern und dem auf der Straße des 17. Juli stattfindenden [Umweltfest](http://www.umweltfestival.de/). Für mich war es spannend, ein paar neue Seiten von Berlin kennenzulernen (v.a. von Kreuzberg & Neukölln) und in einem so großen Feld zu fahren. Teilweise musste ich an die Pelotons bei der Tour de France denken, bei denen es eine Kunst ist, sich an der richtigen Position zu halten - man wird schnell abgedrängt und findet sich etliche Reihen weiter hinten wieder. So habe ich fast die [gesamte Strecke](http://www.gpsies.com/map.do?fileId=pemyidlxsioroqwj) von der A100 bis zum Ernst-Reuter-Platz benötigt, um mich nach vorne bis kurz hinter die Polizeiwagen vorzukämpfen. Ironie der Situation: Ich bin oft auf die Fahrradwege ausgewichen, um weiter nach vorne zu gelangen. Doch im Gegensatz zu den 300 Fahrern der Tour de France fuhr ich in einem Feld von insgesamt 150'000 Radlern, die ich leider nie alle komplett gesehen habe - die Demo muss am Ende eine Gesamtlänge von mehreren Kilometern gehabt haben!

Am Ende hatte ich 30km inklusive der Heimfahrt auf dem Rad zurückgelegt und war ob die ungewohnten Belastung ganz schön geschafft - aber auch glücklich, an so einem Ereignis teilgenommen zu haben. Nächstes Jahr werde ich wohl einmal die Strecke über die Avus ausprobieren, die landschaftlich etwas schöner als die A100 in Tempelhof ist.

![sternfahrt_1.jpg](sternfahrt_1.jpg)
![sternfahrt_2.jpg](sternfahrt_2.jpg)
![sternfahrt_3.jpg](sternfahrt_3.jpg)
![sternfahrt_4.jpg](sternfahrt_4.jpg)
