---
title: "Der Herr der Ringe - Die Gefährten"
date: "2001-12-19T00:00:10"
categories: [gesehen]
---

*Neuseeland/USA (2000)
Regie: Peter Jackson
Darsteller: Elijah Wood (Frodo Beutlin), Sir Ian McKellen (Gandalf), Viggo Mortensen (Aragorn), Sean Astin (Sum), Sean Bean (Boromir), John Rhys-Davies (Gimli), Orlando Bloom (Legolas), Liv Tyler (Arwen), Hugo Weaving (Elrond), Cate Blanchett (Galadriel), Sir Ian Holm (Bilbo Beutlin), Christopher Lee (Saruman) und viele Bewohner Mittelerdes mehr*
[Offizielle Homepage](http://www.derherrderringe-film.de/)

Einst wurden in Mittelerde 19 Ringe geschmiedet, Zauberringe, und als Zeichen ihrer Macht an die Herrscher der Welt verteilt - die Elben, die Zwerge und die Menschen. Doch der böse Zauberer Sauron schmiedete einen weiteren Ring, in den er all seine Kraft bündelte und der ihm half, die Welt zu unterjochen. In der alles entscheidenten Schlacht gegen ihn jedoch gelang es dem Anführer der Menschen, Isildur, Sauron den Ring zu entreißen und so das Dunkle Zeitalter zu beenden. Doch anstatt den Ring zu vernichten nahm ihn Isildur an sich.

Über viele verschlungene Pfade kam der Ring schließlich 3500 Jahre später in die Hände des Hobbits Bilbo, der keine Ahnung von der Macht des Ringes hatte. Doch als er ihn an seinem 111. Geburtstag benutzt, um unsichtbar seine Heimat Auenland zu verlassen, wird das Böse in Form von Sauron, der als Geist die Jahre überdauert hat, wieder auf ihn aufmerksam. Mit diesen Ring könnte er seine Macht wiedererlangen und ein neues Zeitalter der Dunkelheit anbrechen lassen. Dies erkennt auch der Zauberer Gandalf, der ein Freund der Hobbits ist, und so beschließen die Völker von Mittelerde, dass der Ring vernichtet werden muss; im Feuer des Schicksalsberges, wo er geschmiedet wurde. 

Frodo, der den Ring von seinem Ziehvater Bilbo erhielt, muss also losziehen um die schwierige Aufgabe zu erfüllen; unterstützt von einer Gemeinschaft aus Menschen, Zwergen und Elben - den Gefährten...

An der sehr langen Story erkennt man schon - "Der Herr der Ringe" ist ein sehr komplexer Stoff, und so hatte ich einige Zweifel, ob der Film der literarische Vorlage von J.R.R. Tolkien gerecht werden kann. Und das kann er natürlich nicht, dazu ist die Welt von Mittelerde einfach zu detailliert und die Geschichte zu ausschweifend - dies alles in geplanten 9 Stunden (3 Teile) darzustellen ist einfach nicht möglich.

Umso überraschter bin ich, wie gut es Peter Jackson gelungen ist, den Stoff zu kürzen, ohne wirklich wichtige Teile wegzulassen, und das erste Buch der Trilogie in einem 3-stündigen Film unterzubringen. Klar werden einige meckern, Arwen taucht da am Anfang gar nicht auf, was ist mit Tom Bombadil, usw. - Schwamm drüber. Der Film enthält alle wichtigen Elemente des Buches, die Dialoge der deutschen Fassung sind direkt aus der ersten Übersetzung entnommen und Mittelerde ist dermaßen realistisch dargestellt, dass man nur eins sagen kann: Peter Jackson hat wahnsinnigen Respekt vor dem wahrscheinlich größten Fantasy-Werk aller Zeiten gezeigt und der Vorlage ein Äußeres verpasst, bei dem viele sagen werden: Ja, so oder so ähnlich habe ich es mir beim Lesen auch vorgestellt. 

Die Masken wirken alle sehr natürlich und stellen die verschiedenen Völker mit ihren unterschiedlichen Eigenheiten ohne aufwendige Effekthascherei dar, die Schauspieler füllen die Charaktere mit Leben und die Effekte unterstützen, ohne dass man es merkt, vortrefflich die toll eingefangenen Szenen. Mittelerde erwacht so vor den Augen des Kinogängers zu Leben, wie es sich vielleicht sogar Tolkien selber vorgestellt hat, ohne die schlechten Dialoge und die stupiden Kampfszenen aktueller Hollywood-Filme. 

Das einzige was man Peter Jackson vorwerfen kann ist, dass es alles nicht von ihm stammt, sondern dem Geiste eines Engländers entsprungen ist, der die Fantasy beeinflusst hat wie kein Zweiter. (Und das man 1 bzw. 2 Jahre auf die Fortsetzungen warten muss!)

Fazit: Das Filmhighlight des Jahres, die ewige Geschichte von Gut und Böse, verpackt in eine epochale Story und eine Fantasy-Welt, die den Zuschauer in ihren Bann zieht - was will man mehr?! Muss man gesehen haben!!!!!
