---
title: "Was Frauen wollen"
date: "2001-02-22T00:00:55"
categories: [gesehen]
---

*USA (2000)
Regie: Nancy Meyers
Darsteller: Mel Gibson (Nick Marshall), Helen Hunt (Darcy McGuire), Marisa Tomei (Lola), Mark Feuerstein (Morgan), Lauren Holly (Gigi), Ashley Johnson (Alex), Delta Burke (Eve), Valerie Perrine (Margo), Alan Alda (Dan Wanamaker) uvm.*
[Offizielle Homepage](http://www.movie.de/Frauen)

Nick Marshall ist sehr erfolgreich in der Werbebranche und steht kurz vor der Beförderung zum Abteilungsleiter. Und er ist ein Weiberheld, der selten morgens mit der gleichen Frau aufwacht wie am Tag zuvor. Doch dann ändert seine Firma plötzlich ihre Strategie und vergibt "seinen" Job an eine Frau. Nick kann es kaum fassen, dass er nun unter Darcy McGuire arbeiten soll. Und das "männermordende Biest" heizt in ihrem ersten Meeting allen Anwesenden ganz schön ein. 

Nick und sein Kollege Morgan sind nicht gerade begeistert, dass sie nun über Nacht Vermarktungsstrategien für Lippenstift, Enthaarungswachs, Schwangerschaftstest usw. entwickeln sollen. Es kostet Nick einige Überwindung, sich überhaupt mit dem Thema zu beschäftigen. Aber als er einmal loslegt, macht er es richtig - richtig intensiv. Beim Ausprobieren der einzelnen Produkte landet er aber unverhofft in der Badewanne - zusammen mit einem angeschlossenen Fön. Nick überlebt, aber irgendetwas scheint mit ihm passiert zu sein, denn er kann plötzlich die Gedanken der ihn umgebenden Frauen hören. Nach anfänglicher Panik begreift Nick, wie er diese Gabe dazu einsetzen kann, Darcy ihren Job wieder wegzunehmen. Er muss nur lange genug in ihrer Nähe bleiben, um ihre Gedanken und Pläne zu "hören" und sie dann als seine eigenen zu verkaufen und damit der Firma zu beweisen, dass er viel besser zu dem Job passt. Doch je mehr sich Nick mit Darcy beschäftigt, um so mehr wachsen die Gefühle der beiden füreinander, und er steckt mächtig in der Zwickmühle...

Gut, (Liebes-)Komödien brauchen halt einen Aufhänger, und der wird hier mit dem Hören der Gedanken geliefert. Ansonsten bekommt man aber die gleiche Kost, wie schon in etlichen anderen Komödien zuvor und auch das Hollywood-übliche Happy-End. So weit, so gut, doch zwischen Aufhänger und Happy-End gestaltet sich der Film wirklich witzig, es werden sowohl die Männer als auch die Frauen aufs Korn genommen, Mel Gibson spielt wieder mal Mel Gibson und Helen Hunt spielt Helen Hunt und damit komme ich schon zum

Fazit: Ein Film ohne Schwächen, manchmal echt witzig, aber halt auch vorhersehbar, eine typische Liebeskomödie amerikanischer Schule, bei der man sich nicht langweilt, die man aber auch nicht zweimal sehen muss.
