---
title: "Die Ringe der Macht - Staffel 2"
date: "2024-10-09T23:55:00"
categories: [gesehen]
---

{{< video
https://www.youtube.com/embed/EqniPax8LGE
>}}

Sie ist die teuerste Fernsehserie aller Zeiten; gestartet mit dem Versprechen, uns Zuschauern zu zeigen, unter welchen Umständen die Ringe der Macht einst geschmiedet wurden. Mit reizvollen Nebenfiguren aus _Der Herr der Ringe_ wie Galadriel und Elrond, aber vor allem dem vielschichtigen Sauron ist eigentlich eine perfekte Basis für tolle Fantasy gegeben - und doch schaffen es die Macher bisher nicht, neben all dem Production value auch eine glaubhafte Geschichte zu erzählen.

Dabei gibt es immer wieder tolle Momente, die zeigen, was eigentlich möglich wäre. Schon am Ende von Staffel 1 traf Sauron in Gestalt von Halbrand auf Celebrimbor, und man konnte greifen, wie beide als begeisterte Schmiede sich gegenseitig mit Plänen und Ideen befruchteten. Tolkien motivierte in wenigen Sätzen, dass Celebrimbor an den Ringen mitgewirkt hat, um seinen Vorfahren Feanor zu übertreffen, und deshalb erst spät den Einfluss Saurons erkannt hat. Aber auch Sauron hatte anfangs noch keinen vollständigen Plan und musste erst lernen, welche Wirkung sein Blut in den Ringen hat - die Serie zeigt dies wunderbar in einem Dialog zwischen den beiden. Als endlich Saurons Hülle als Annatar gefallen ist und beide sich auf Augenhöhe unterhalten können, erfährt auch der Zuschauer schlussendlich, was beide antrieb.

### Warum machen die das jetzt?

Allerdings kommt dies ganz schön spät. Ich habe während der Serie viel in meiner Ausgabe von _Lord of the rings_ geblättert, um zu verstehen, was gerade auf dem Bildschirm passiert. Wie sollen jedoch Zuschauer ohne dieses Wissen verstehen, was die Charaktere antreibt, wenn es selten so offen dargelegt wird? 

Generell wirken viele Entscheidungen konstruiert; die Serie opfert nicht nur einmal die Glaubwürdigkeit ihrer Figuren um sie in Situationen zu bringen, die der Plot erfordert.

Beispiele gefällig?

* Elrond hat Durin überzeugt, ihn bei der Verteidigung von Eregion mit einem Heer zur Seite zu stehen. Doch Durin muss sich um den immer wahnsinniger werdenden Vater kümmern, also bricht er sein Versprechen. Doch warum kann er nicht einfach die Armee schicken und selber bleiben? Genau das passiert ja auch später...
* Als der Balrog auftaucht, schnappt er sich mit seiner Peitsche Durins Vater - und lässt ihn kurz vor dem Abgrund wieder los. Gandalf hatte Jahre später nicht so viel Glück. Und nach der bis dahin gezeigten Entwicklung konnte ich den Entschluss, den Ring abzulegen und allein gegen den Balrog zu kämpfen, nicht nachvollziehen. 
* Galadriel wird am Ausgang des geheimen Zwergenganges nach Eregion von Orks empfangen. Wenn diese jedoch wissen, dass es so einen Gang gibt, warum haben sie dann erst eine Belagerung begonnen?
* Als Adar sich gegen Ende der Schlacht den Ring von Elrond schnappt und die Mauer Eregions durchbrochen ist, steht ihm scheinbar nichts mehr im Weg, um Sauron entgegen zu treten. Doch was macht Adar, trotz des Wissens um Saurons Fähigkeiten? Er schickt Orks, den großen Täuscher gefangen zu nehmen, und zieht sich in sein Lager zurück, das plötzlich oberhalb der Stadt liegt. Das muss ich nicht begreifen, oder?

### Show don't tell

... gilt nicht nur für das geschriebene Wort. Peter Jackson hatte vor zwanzig Jahren eine Vision und hat mit seinen Bildern die Sicht vieler Zuschauer auf Mittelerde geprägt. _Die Ringe der Macht_ wollen dies einfach nur reproduzieren und scheitern daran, eigene Bilder zu entwickeln.

Die Elben sollen eigentlich elegante Krieger und die besten Schmiede ihres Zeitalters sein. Doch was zeigt uns _Die Ringe der Macht_? Schwere Metallrüstungen, die scheppern wie bei römischen Legionen. Und Celebrimbor skizziert seine Designs mit Kohle auf Papier und feilt an den Ringen, während er sie in der Hand hält. Das ist alles sehr unterwältigend; den Machern scheint es an Fantasie zu fehlen, Tolkiens Welt abseits des Bekannten in Bilder zu transformieren. 

Elben sind nur noch Menschen mit spitzen Ohren, im Verhalten ist kein Unterschied zu sehen. So blieb mir vollkommen unklar, wie man die gut befestigte Stadt Eregion so schlecht verteidigen kann. Der Vorteil der Höhe wird nicht ausgenutzt, Leitern an der Mauer nicht zurückgestoßen, und als die Orks nach etlichen Versuchen endlich die Mauer durchbrochen haben gibt es keinen Elfen, der dahinter auf sie wartet (außer den nach stundenlanger Belagerung immer noch chaotisch durch die Stadt laufenden Zivilisten).

Das mag im Drehbuch in wenigen Sätzen sehr gut geklungen haben, aber auf dem Schirm wirkt es einfach nur unglaubwürdig. 

### Fanservice / Es muss eine epische Schlacht sein

Die _Herr der Ringe_ Trilogie hat Maßstäbe gesetzt, wie Fantasy auf der großen Leinwand aussehen kann: Episch, bildgewaltig, voller großer Helden und Gesten. Weniger geht seitdem nicht mehr. Wie war ich dann Jahre später geflasht, als _Game of Thrones_ mit all dem brach und in der ersten Staffel eine Schlacht zwischen den Starks und Lannisters einfach im Off abhandelte.

Die _Ringe der Macht_ traut sich das nicht und zitiert alle Klischees, die man sich nur vorstellen kann. Bis hin zum Elben, der von mehreren Pfeilen getroffen noch einen wichtigen Schuss ansetzt.

### Reisefieber

Ein großer Kritikpunkt der letzten Staffeln von _Game of Thrones_ war, dass die sorgfältig vorher aufgebaute Welt von Westeros mit ihren Entfernungen plötzlich nichts mehr galt, weil die Charaktere an bestimmten Orten gebraucht wurden.

Auch _Die Ringe der Macht_ kann sich nicht ganz einigen, ob und wie schnell man von Lindon nach Eregion kommt. Briefe in die eine Richtung werden abgefangen, Trupps von zerstörten Brücken zu tagelangen Umwegen gezwungen, während Arondir und ganze Heere scheinbar schnell reisen. Zeit und Raum müssen sich hier leider vollkommen der Geschichte unterordnen. Bei Tolkien hat sich das Schmieden der Ringe über hundert Jahre hingezogen, was schön die Zeit betont, die Elben sich für wichtige Dinge nehmen - aber solche Zeitspannen will man dem Zuschauer wohl nicht zumuten.

### Letzte Gedanken

Jetzt habe ich mich natürlich auf die Fehler konzentriert, die mich immer wieder rausgerissen haben. Wer nicht so genau hinschaut wie ich, kann sicherlich auch viel Spaß mit der Serie haben - z.B. ist Rory Kinnear ein wirklich ausgezeichneter Tom Bombadil.

Zum Schluss will ich noch kurz erklären, was es mit dem eingebetteten Video von _Within Temptation_ auf sich hat: Die vorletzte Episode der zweiten Staffel, _Doomed to Die_, endet mit dem sehr martialischen Metal-Song _The Last Ballad of Damrod_ über den Troll, der in der gezeigten Schlacht um Eregion gefallen ist. Ich fand dies sehr passend an der Stelle, aber der Song verfehlt ohne die Bilder leider etwas seine Wirkung. Doch da Sauron am Ende oft der große Täuscher genannt wurde, fiel mir der Song _Deceiver of Fools_ ein, dessen Text dem Herrn der Ringe wie auf den Leib geschneidert scheint. Vielleicht hören wir ihn in einer der nächsten Staffeln; noch muss der eine Ring ja geschmiedet werden...