---
title: "Agile Retrospectives"
date: "2007-09-13T22:16:30"
categories: [gelesen]
---

*von Esther Derby & Diana Larsen,
erschienen bei Pragmatic Programmers, ISBN 978-0977616640, 21,95€*

Zur Abwechslung will ich hier kurz über ein Buch schreiben, welches ich für meine Arbeit gelesen habe. Es geht um die Durchführung von Retrospektivmeetings nach dem Ende einer iterativen Projektarbeit, wie z.B. dem [Scrum-Modell](http://de.wikipedia.org/wiki/Scrum). Da wir auf Arbeit Scrum als agilen Prozess zu leben versuchen, gibt es großes Interesse an dem Thema der ständigen Verbesserung der Prozesse, wofür Retrospektiven ein wichtiger Grundstein sind.

Die beiden Autorinnen stellen in ihrem Buch einen grundsätzlichen Aufbau für Retrospektiven vor und versuchen sich danach an der Vorstellung von Techniken für die effiziente Umsetzung. Dabei halten sie sich kurz; zwei bis drei Seiten reichen für jede Technik aus und das Ganze hat einen reinen Rezeptcharakter. Hintergründe werden nicht vermittelt, und die meisten Beispiele bedürfen für den typischen Mitteleuropäer einer Anpassung, um überhaupt akzeptiert zu werden - und dies ist schließlich das Wichtigste an der Retrospektive. Wenn die Mitarbeiter keine Motivation für den Verbesserungsprozess aufbringen, ist das gesamte Modell zum Scheitern verurteilt.

Am Ende bleiben ein guter Vorschlag für die Struktur von Retrospektiven und ein paar wenige interessante Techniken für die Durchführung, die jedoch erst einmal von der amerikanischen Unternehmenskultur auf die hiesigen Arbeitsverhältnisse transformiert werden müssen. In der langen Literturliste findet sich sicher ein besseres weil informativeres Buch zu dem Thema.
