---
title: "N.V.A."
date: "2005-10-06T17:36:03"
categories: [gesehen]
---

Leider war es mir am Wochenende in Ulms [Xinedome](http://www.xine-dome.de/) nicht möglich, Leander Haußmanns neuesten Film zu sehen - er lief schlicht und ergreifend dort nicht. Als ich dann einen Bericht im Jugendsender "Das Ding" hörte, der sich nur um Kim Frank drehte und den Filmtitel zu J.V.A. umdichtete, wurde mir klar, dass sich das Interesse im Westen dieser Republik an den 40 Jahren DDR wahrscheinlich darauf beschränkt, ehemalige StaSi-Spitzel zu entlarven. Also ging es wieder in das heimische Cinemaxx, welches für einen Mittwoch-Abend auch gut gefüllt war.

Erfahrungen mit der NVA habe ich als Jahrgang 1981 zwar keine - außer dass der Vater zweimal zur Reserve weg war. Doch auch "Sonnenallee" konnte man genießen, ohne die vielen kleinen Anekdoten zu verstehen, also ging ich hoffnungsfroh in den Film. Dieser versuchte nun anderthalb Stunden lang, die Sinnlosigkeit der Institution Volksarmee und die daraus entstehenden Strukturen aufzuzeigen, wobei die Geschichte noch mit ein wenig Liebe gewürzt wurde. Doch leider fehlt eine durchgängige Handlung - es sei man akzeptiert den Grundwehrdienst als Storyline. So entwickelt sich der Film episodenartig bis zu dem überdrehten Ende, welches leider keinem N.V.A.-Soldaten widerfahren sein dürfte. Dies ist zwar alles ganz lustig, aber zwischendurch fehlt es N.V.A. einfach an der nötigen Dynamik.

Dazu bei trägt auch Hauptdarsteller Kim Frank, ehemals Frontjunge der Band Echt, an dem eindeutig kein Schauspieler verloren gegangen ist - den ausdruckslosen Blick der Volkssoldaten muss der Zuschauer fast den ganzen Film über an ihm ertragen. Die anderen Soldaten sind da viel interessantere Charaktere, die trotz ihrer Beschränkung auf meist wenige Eigenschaften gefallen können. Vor allem Krüger, gespielt von Oliver Bröcker, ist der eigentliche Held des Films und so langweilen die Minuten ohne ihn deutlich. Daran kann auch Produzent Detlev Buck nichts ändern, dessen autoritäre Fassade diesmal erst am Ende des Film bröckeln darf. Die Liebesgeschichten der beiden Hauptakteure beschränken sich, dem Episodenkonzept folgend, ebenfalls auf jeweils zwei Szenen, bilden aber den Anlass für das übertriebene Ende des Films.

Fazit: Das Ziel, die Sinnlosigkeit der N.V.A. aus heutiger Sicht aufzuzeigen, gelingt dem Film durchaus. Die meisten Charaktere wissen auch zu gefallen, nur leider können Hauptrolle und Hauptdarsteller nicht überzeugen. Erschwerend hinzu kommt die Episodenform des Films, so dass ich ihn nicht uneingeschränkt empfehlen kann!

[Offizielle Seite zum Film](http://www.nva-derfilm.de/)
