---
title: "Kaffeesatzlesen: Gothic III bekommt ein Addon"
date: "2008-04-16T21:40:20"
categories: [gedacht,gefunden,gespielt]
---

So "schnell" kann es gehen: Anderthalb Jahre nach Erscheinen des Originalspiels und einen Monat nach dem [offiziellen Ende der Differenzen](http://www.worldofgothic.de/gothic4/index.php?go=interview21) zwischen den Entwicklern von Piranha Bytes und Publisher JoWood wurde ein Addon für das Spiel mit dem Namen [Forsaken Gods](http://www.jowood.com/?lang=de&site=1&iid=12833) angekündigt. Offiziell heißt es:

> Die Story von Gothic 3 – Forsaken Gods wird offene Fragen aus Gothic 3 beantworten und einen nahtlosen Übergang zu dem bereits angekündigten vierten Teil der Serie schaffen.

Nun wird natürlich an vielen Stellen darüber diskutiert, was dies für meine Lieblings-Rollenspiel-Serie bedeutet. Bei [Gamona](http://www.gamona.de/pc/article/detail/id-ein_add_on_zu_gothic_3_wer_macht_denn_so_629389/start-1.htm) hat man ein paar Statements von JoWood bekommen und nun will ich mich auch kurz im Kaffeesatzlesen betätigen. Hier kurz die wenigen Fakten:

<ol>
  <li>das Addon wird nicht von Piranha Bytes entwickelt, das bestätigen sie selber und JoWood</li>
  <li>JoWood sagt: "Gothic 4 und das Addon werden beide parallel entwickelt" und es "sitzen ja neue Entwickler an der Entwicklung"</li>
  <li>Spellbound entwickelt offiziell Gothic 4 für JoWood, wahrscheinlich mit einer gekauften 3D-Engine (optimistischer Releastermin: 02.01.2010)</li>
  <li>Spellbound hat am letzten Community-Patch 1.6 für Gothic III technisch mitgearbeitet</li>
</ol>

Dies deutet für mich darauf hin, dass Spellbound an dem Addon arbeitet, denn warum sollten sie sich sonst in die Technik des dritten Teils einarbeiten - der vierte wird schließlich mit einer komplett neuen Grafikengine entwickelt. Trotzdem stellt sich die Frage, warum nach all der Zeit noch ein Addon kommen sollen. Und da denkt JoWood wahrscheinlich zuerst an eine Aufrechterhaltung des Franchise *Gothic* bis zum Erscheinen des vierten Teils. Sollte dieser sich verspäten, gäbe es mehr als drei Jahre lang kein neues Spiel aus der Serie. Dies wäre ein längerer Zeitraum als zwischen *Die Nacht des Raben* und Teil 3. In dieser Zeit hätten die Fans genügend Zeit, andere Spiele wie *The Witcher* zu spielen, die der *Gothic*-Serie nicht nur spielerisch, sondern auch in Sachen Bugs einiges voraus haben. Wenn man jetzt jedoch, nachdem *Gothic III* mit den Community-Patches langsam rund wird, darauf aufbauend noch ein gutes Addon hinterherschiebt und dieses vor allem mit einem richtig guten Cliffhanger enden lässt, dann würde sich wohl automatisch eine positive Erwartung bei den Fans aufbauen, die bis 2010 reichen sollte und die Investitionen in das Addon rechtfertigt.

Ich jedenfalls freue mich auf *Forsaken Gods* (mir hat auch der dritte Teil sehr gut gefallen), werde es definitv kaufen und nach ein, zwei Patches auch spielen. Aber vielleicht werde ich in dieser Hinsicht ja auch einmal positiv überrascht...
