---
title: "Family Guy presents Blue Harvest"
date: "2008-03-24T17:04:50"
categories: [gesehen]
---

> That's the story of Star Wars - let's begin with Part IV.

Irgendwann gibt es in jeder amerikanischen Zeichentrickserie eine Parodie auf *Star Wars*, den Überfilm der 80er-Jahre-Nerds. *Family Guy*, das zu weiten Teilen nach dem Prinzip der Referenzierung funktioniert, hat mehr als einmal auf George Lucas SciFi-Saga zurückgegriffen und nun den großen Schritt gewagt, *Star Wars IV - A new hope* komplett nachzuspielen.

Und dies ist durchaus wörtlich zu verstehen: Fast jede Szene der Handlung ist 1:1 aus der Vorlage entnommen; Kamerafahrten und Einstellungen kopieren mit einer Detailtreue die Originalmontagen, die weit über den üblichen Fanmovie hinausgeht. Das dies nur mit der Zustimmung von George Lucas zu realisieren war, sollte jedem klar sein. Doch leider ist diese Anbiederung an das Vorbild auch das große Problem von *Blue Harvest*, denn bis auf wenige Ausnahmen hätte es auch ausgereicht, das Original einfach neu zu synchronisieren - kopierte CGI-Szenen ohne jedes komische Element haben in einer Parodie einfach nichts zu suchen.

Nicht dass ich falsch verstanden werde: Blue Harvest ist eine teilweise echt komische Parodie, die vor allem aufgrund des Hinterfragens vieler kleiner Details links und rechts der Handlung überzeugt. Aber da man sich zu 90% an das Originaldrehbuch hält und sich daran aufgeilt, eine technisch aufwendige Trickfilm-Kopie zu produzieren, geht dem Serienspecial die Originalität fast vollkommen abhanden. Mal sehen, ob sich das mit den geplanten Fortsetzungen ändern wird.

