---
title: "Eisbären in Friedrichshain"
date: "2009-02-25T22:40:00"
categories: [gewesen]
---

Mein letzter Besuch eines Eishockey-Spiels liegt bereits [dreieinhalb Jahre zurück](/blog/2005/09/10/krefelder-pinguine-vs-kolner-haie/), doch die neue [Spielstätte](http://www.o2world.de/) der [Eisbären](http://www.eisbaeren.de/) in meiner Wahlheimat Friedrichshain musste zwangsläufig zu einem weiteren Anlauf führen. Nachdem die Kölner Haie diese Saison aber nicht die Playoffs erreichen, fehlte mir ein richtiger Gegner als Anreiz, um für ein Spiel Geld auszugeben. Zum Glück habe ich Kollegen, über die man ab und zu an Freikarten kommt, und so saß ich Dienstag gegen die <del datetime="2009-02-26T20:47:43+00:00">Nürnberger</del> Sinupret Ice Tigers in der O2 World.

Sportlich war die Partie nicht der Rede wert, zu groß war der Unterschied zwischen dem neuen Tabellenführer und dem insolventen Klub aus Franken. Nach dem ersten Drittel sah es gar so aus, als würden die Hausherren einen zweistelligen Kantersieg einfahren, doch angesichts des wichtigeren Spiels gegen die Adler Mannheim nur einen Tag später wurde schnell der Spieltrieb auf das Nötigste begrenzt, so dass die letzten zwanzig Minuten zum Einschlafen langweilig waren.

Dies hinderte die Fans nicht daran, die gesamte Zeit über Stimmung zu machen, die natürlich aus dem Block mit den Stehplätzen kam. Die Sitzplatzbesucher (inklusive mir) ließen sich davon dirigieren, die große Halle fängt jedoch einiges an Atmosphäre ab. Dafür ist sie schön hell und weitläufig, es gibt ausreichend Fressstände und Toiletten und für die Raucher ist auf dem komplett um die Halle herumlaufenden Balkon genügend Platz. Nur die Organisation des Einlasses sollte überarbeitet werden. Durch die strengen Einlasskontrollen haben es viele der 12000 Besucher nicht pünktlich zum Anpfiff hinein geschafft, auch ich musste eine halbe Stunde in der Kälte stehen.

Insgesamt war es aber ein lohnender Abend. Über die Rolle der O2 World im Kampf um die [MediaSpree](http://de.wikipedia.org/wiki/Mediaspree) kann man streiten, sie ist aber eine tolle, moderne Veranstaltungshalle. Die Eisbären könnten es damit wirklich schaffen, sich einen größeren Fankreis abseits der alten Dynamo-Ultras zu sichern. Nur die Terminkonflikte durch die vielfältige Nutzung der Halle ([ALBA](http://www.albaberlin.de/) ist da noch das geringste Problem) wie bei der [Echo-Verleihung](http://www.o2world.de/event/tickets/ECHO-2009-/270.htm) letzten Samstag könnten auf die Dauer zu sportlichen Problemen führen - schließlich will man dauerhaft um die Meisterschaft mitspielen.
