---
title: "Mein neues Spielzeug"
date: "2009-02-21T15:13:29"
categories: [gedacht,getan]
---

Als ich mir die Playstation 3 letztes Jahr zulegte, verband ich damit die Hoffnung, neben einer Spielekonsole und einem Blu-Ray-Player auch einen Mediacenter für meinen Full-HD-Fernseher zu erwerben. Doch die Ernüchterung ließ nicht lange auf sich warten. Das PS3-eigene Betriebssystem hat zwar einen tollen Foto-Browser, spielt jedoch nur wenige Videoformate ab und erkennt die Dateien auf meiner externen Festplatte nicht. Und mein installiertes Linux-System hat keinen Zugriff auf die Grafikkarte und damit zu wenig Power für die Wiedergabe von HD-Videos.

Blieb noch mein PC als Abspielgerät. Doch leider besitzt mein Laptop nur einen DVI-Anschluss, so dass ich entweder zwei Kabel (jeweils eines für Ton und Video) zum Fernseher legen muss oder alternativ alles per WLAN und UPnP auf die PS3 streame, wobei der Rechner beim Umkodieren am Anschlag läuft - was wiederum andere parallele Nutzungen erschwert.

So traf ich schweren Herzens die Entscheidung, meinen HiFi-Stack um ein weiteres Element zu erweitern. Das Angebot reicht dabei von echten Mediacenter-PCs am oberen Ende der Preisskala bis hin zu Multimedia-Festplatten mit Fernsehausgang. Der HDMI-Ausgang für Full-HD-Wiedergabe schränkte die Auswahl schnell auf wenige Produkte ein, und meine Preisvorstellung für ein reines Medienabspielgerät grenzte das Angebot nach oben ab.

Auf der [CES](http://de.wikipedia.org/wiki/Consumer_Electronics_Show) Anfang diesen Jahres wurden zwei interessante Produkte vorgestellt, die meinem Anforderungskatalog erfüllten: Der [EVA9150](http://www.netgear.com/Products/Entertainment/DigitalMediaPlayers/EVA9150.aspx) vom Netzwerkspezialisten Netgear und die [LaCinema Black MAX](http://www.lacie.com/de/products/product.htm?pid=11223), die sogar einen DVB-T-Tuner mit Rekorderfunktionalität besitzt. Beide Geräte bringen auch einen Internetzugang und viele Schnittstellen mit, außerdem ist eine große Festplatte bereits eingebaut. Diese für mich unnötigen Features treiben dafür den Preis in Richtung 400€.

Doch in einem Forum stieß ich dann auf das Gerät, dass sowohl den preislichen Rahmen einhielt als auch alle meine Wünsche erfüllte: Der [WD TV HD Media Player](http://www.wdc.com/de/products/products.asp?driveid=572) für knapp 100€. Ich kann meine bereits vorhandenen externen Platten an die kleine Box anschließen und sie spielt anstandslos alles an Filmen ab, was sie darauf findet. Mein Testparcour inklusive Full-HD-MKVs wurde in perfekter Qualität wiedergegeben, besser als es mein Laptop je geschafft hat. Die Benutzeroberfläche und Fernbedienung sind hübsch und zweckmäßig, wenngleich sie gegenüber der PS3 natürlich abfallen. Dafür verbraucht das Gerät aber auch keine 200W, benötigt keinen Lüfter und ist somit flüsterleise.

Mit dem letzten Firmware-Update sollen auch die meisten Kompatibilitätsprobleme behoben sein, von denen ich aber nicht betroffen war. Trotzdem arbeitet WD weiter an Verbesserungen - vorbildlich. Einziges Manko: Die Hardware der Box scheint nicht leistungsfähig genug zu sein, um Mehrkanalton in Stereo zu konvertieren. Trifft sie auf einen solchen Stream im Video, wird dieser nur auf den digitalen Audioausgang gelegt und man benötigt einen Receiver mit entsprechender Decoder-Funktionalität, um etwas zu hören.

Fazit: Der WD TV ist genau das, was ich suchte: Ein Player für die komplette Bandbreite an Video-Material auf meinen externen Festplatten, der Full-HD über HDMI beherrscht. Dazu ist er klein, leise und vergleichsweise preiswert. Die Anschaffung habe ich nicht bereut.
