---
title: "Schlösser, Schlüssel und Nachrichten toter Väter"
date: "2012-06-17T21:55:34"
categories: [gesehen]
---

Zwei Filme, die ich zuletzt gesehen habe, wiesen überraschend viele Gemeinsamkeiten auf, so dass ich sie in einem Artikel besprechen will. Den Anfang macht *Extremely loud & incredibly close* von [Stephen Daldry](/blog/?s=Stephen+Daldry) nach einem Buch von Jonathan Safran Foer, dessen Erstling *Alles ist erleuchtet* bereits sehr ansprechend verfilmt wurde.

*Extremely loud & incredibly close* beschäftigt sich mit den den Auswirkungen von 9/11 auf die Bürgern New Yorks aus der Sicht eines leicht autistischen Kindes. Dessen Vater schickte ihn immer auf rätselumwobene Erkundungstouren durch die Stadt, um ihn seine Ängste überwinden zu lassen. Doch dann stirbt der Vater in einem der Türme des WTC und sowohl Oskar als auch dessen Mutter sind am Boden zerstört.

Ein Jahr nach dem traumatischen Ereignis findet der Junge im Zimmer seines Vaters einen Umschlag, auf dem der Name Black steht und der einen Schlüssel enthält. Der Junge sieht darin ein weiteres Rätsel seines Vaters und versucht herauszufinden, zu welchem Schloss der Schlüssel gehört. Dazu plant er er einen Besuch sämtlicher Blacks von NYC und lernt auf seiner Suche viele verschiedene Persönlichkeiten kennen, die alle auf ihre eigene Weise von 9/11 betroffen sind. Hilfe bekommt er dabei vom Untermieter seiner Großmutter, der seit dem Verlust seiner Eltern im zweiten Weltkrieg nicht mehr gesprochen hat und nur über Papierzettel mit der Umwelt kommuniziert.

Für einen Film voller traumatisierter Menschen ist *Extremely loud & incredibly close* überraschend leicht verdaulich. Dies liegt zu weiten Teilen am Tonfall der Vorlage, der gut auf die Dialogebene übertragen wurde und die fehlende Empathie des Jungen vermittelt. Gleichzeitig schafft es der Film zu Beginn, die verängstigte Weltsicht von Oskar zu visualisieren und seine Ausgleichshandlungen (wie das Tamburinspielen) zu erklären. Wie er seine Ängste schließlich überwindet sieht der Zuschauer dagegen nur aus der Perspektive des Beobachters. Hier ist der Film etwas inkonsequent in seiner Erweiterung der Erzählperspektive auf Mutter und Großmutter.

Am Ende findet Oskar sein Schloss, doch weder stammt der Inhalt von seinem Vater noch war es ein für ihn bestimmtes Rätsel. Die Suche war jedoch nicht umsonst. Zum Einen hat es den Jungen aus seiner Schockstarre befreit, zum Anderen hat es ihn und seine Mutter einander näher gebracht. Denn während Oskar sich in der Wohnung versteckte, musste die sensibel von Sandra Bullock gespielte Linda nicht viel auf ihn Acht geben und konnte sich ihrer eigenen Trauer hingeben. Als ihr Sohn jedoch auf die Straße hinausgeht um das Rätsel zu lösen, muss sie sich zwangsläufig damit beschäftigen. So erwacht sie aus der eigenen Lethargie und findet schließlich sogar Zugang zu ihrem Sohn.

Während Oskar ein Schloss für seinen Schlüssel gesucht hat, besitzt *Hugo Cabret* dieses bereits und benötigt den passenden Schlüssel dazu. Das Schloss gehört zu einem Automaton, einer Art mechanischen Roboter, der das einzige Erbstück von Hugos totem Vater ist. Dieser war Uhrmacher und gleichzeitig Lehrmeister von Hugo, so dass der Junge ohne Probleme nach dem Verschwinden seines Onkels an dessen Stelle die großen Uhren des Pariser Bahnhofs Gare Montparnasse warten kann.

Eines Tages lernt Hugo einen älteren Herren kennen, der einen Reparaturladen für Spielzeug im Bahnhof betreibt. Zuerst hält dieser Hugo für einen Dieb, doch als er bei ihm ein Notizbuch von Hugos Vater entdeckt, in welchem die fehlenden Ersatzteile für den Automaton gezeichnet sind, bietet er dem Jungen eine Stelle in seinem Laden an. Über Isabelle, die Ziehtochter des Ladenbesitzers, entdeckt Hugo nach und nach, wer dieser alte Herr in Wirklichkeit ist und was ihn mit dem Automaton verbindet, von dem er sich so sehnsüchtig eine Nachricht des toten Vaters erhofft.

An dieser Stelle wandelt sich der Film etwas. Hat Regisseur Scorsese vorher das Innenleben von Bahnhof und Uhrwerken in den Mittelpunkt gestellt, wird nun klar, dass er eigentlich eine Liebeserklärung an die Anfänge des Kinos inszeniert. Denn der alte Mann ist niemand anders als Georges Méliès, der Pionier der filmischen Tricktechnik, und ab da an wird ungehemmt dem Kino gehuldigt - Méliès Ideen, seiner eigenen Kameraentwicklung, seinem Studio und seiner Tricktechnik.

Dass *Hugo Cabret* die Verfilmung eines Kinderbuches ist geht dabei aber nie unter. Zu märchenhaft ist der Bahnhof inszeniert, zu prototypisch agieren die Nebenfiguren, allen voran Sacha Baron Cohen als herrlich böser Stationsaufseher mit Hund, der gerne kleine Kinder fängt, um sie ins Waisenhaus zu verfrachten.

Genauso einfach, wie die Konflikte gestrickt sind, werden sie am Ende auch aufgelöst. Da positioniert sich *Extremely loud & incredibly close* als deutlich erwachsenerer Film, ohne jedoch das Happy End zu verweigern. Trotz der verschiedenen Zielgruppen und des unterschiedlichen Umgangs mit den gleichen Kernthemen wissen aber beide gut zu unterhalten - und das ist eine weitere Gemeinsamkeit.
