---
title: "Within Temptation - Black Symphony"
date: "2009-09-06T21:56:24"
categories: [gesehen,gehört]
---

Im Februar 2008 haben Within Temptation zusammen mit einem Orchester und einem klassischen Chor ein einmaliges Konzert in Rotterdam gegeben, welches u.a. für diese Bluray aufgezeichnet wurde. Im Gegensatz zu der folgenden [Tour](/blog/2008/07/22/rock-harz-2008/) hatte die Band so die Möglichkeit, den eigenen Sound komplett live auf der Bühne zu erzeugen. Dabei gehen die Gitarren total unter, aber zumindest Sängerin Sharon den Adel hatte einen guten Tag und trägt wie immer die Musik.

Unterstützt wird sie dabei von Keith Caputo, der seinen Teil von *What have you done* singt, und Anneke van Giersbergen, die wie schon auf dem letzten Agua-de-Annique-Album *Somewhere* im Duett begleitet. Als weiteres Highlight hat sich ein alter Song der Band in die Tracklist verirrt (*The other half of me*), bei dem noch Gegrunze die Musik der Band bereicherte.

Diese liegt auf der Blueray erfreulicherweise in umkomprimierten, 96khz/24bit-PCM vor, wahlweise in Stereo oder 5.1. Den Unterschied zur Dolby-Digital-Spur hört man, die Instrumente des Orchesters sind deutlich besser differenzierbar. Dabei nerven die Bläser auf den Surroundspuren etwas, wie auch die gesamte Abmischung für meinen Geschmack zu wenig Bass zeigt und eher die Höhen betont.

Alles in allem also ein gutes Konzert, doch mit dem Ton kann das Bild nicht mithalten. In den seltensten Fällen wird die FullHD-Auflösung ausgereizt, meist sieht man keinen Unterschied zu einer DVD. Erschwerend kommt hinzu, dass die Kameras es einfach nicht schaffen, bei Bewegungen eine konstante Schärfe zu halten (siehe auch [das Review auf AreaDVD](http://www.areadvd.de/blu-ray_disc-reviews/2008/Within_Temptation_Black_Symphony_BD.shtml)). Dabei ist das Problem vermutlich hausgemacht, denn meist ist die Bühne in ein bläuliches Licht gehüllt, das zwar für viel Atmosphäre sorgt, aber auch wie ein Weichzeichner wirkt.

Fazit: Gutes Konzert, guter Ton, aber kein HD-Bild - da ist das Medium nicht ausgereizt worden.
