---
title: "Belfast"
date: "2022-09-02T00:12:00"
categories: [gesehen]
---

Eine protestantische Familie steht im Belfast der 80er zwischen allen Stühlen: Bleiben mitten im zunehmend militarisierten Konflikt, um die Familie und die Kinder nicht zu entwurzeln, oder in das mit wirtschaftlichem und gesellschaftlichem Aufstieg lockende England umziehen.

Kenneth Branagh erzählt aus der autobiografischen Sicht eines etwa zehn Jahre alten Jungen. Dabei bleibt die Kamera stets auf der niedrigen Augenhöhe des Protagonisten, weshalb selten mehr als Häusern, Mauern und Himmel zu sehen ist - selbst als der Junge mal auf eine Barrikade klettert.

Dies wirkt auf die Dauer ganz schön einengend, was die Eltern vielleicht auch so empfunden haben, aber eben nicht der Perspektive und Wahrnehmung des Jungen entspricht. Und diese Nicht-Übereinstimmung zwischen der Perspektive der Hauptfigur und der szenischen Umsetzung hat mich den ganzen Film über genervt.

Denn es setzt sich fort bei der Entscheidung, den Film in schwarz-weiß zu drehen und nur bei Kino- und Theaterbesuchen oder im TV zur Farbe zu schwenken. Ich weiß, Kenneth, dass es Deine Kunst und Liebe ist. Aber der Film erzählt eben auch andere positive Episoden aus der Kindheit, die schwarz-weiß bleiben.

Zudem ist das schwarz-weiß wie vieles an dem Film einfach zu künstlich. Vielleicht mag in Branaghs Erinnerung so oft die Sonne geschienen haben, aber im Film bleibt davon kein Kontrast und kein HDR übrig, sondern alles ist mit Gegenlicht weichgespült. Realismus war kein Anspruch.

Das setzt sich fort bei der (vermutlich im Studio stehenden) Straße, in der sich ein Großteil des Films abspielt. Alles ist total clean und die Kamera darf sich nie erheben oder ausbrechen aus ihrer strengen Kinderperspektive. Im Haus der Eltern gibt es zumindest ein paar spannende Schwenks, aber auch hier atmet alles hochauflösendes Studio. Da war ich schon dankbar, dass die gewählten Filmausschnitte etwas Abwechslung in das Kamera-Einerlei bringen.

Allein die Hinterhof-Szenen zeigen den Dreck und die Enge der Industriestadt mal halbwegs realistisch, so dass ich sehr verwundert war, dass der Mutter so viel an ihrer Heimat liegt. Aber auch hier bleibt der Film sehr inkonsequent - diese Verbundenheit wird an keiner Stelle des Films sichtbar, weil der einzige erzählte Ausbruch der Mutter aus der als Dreh- und Angelpunkt dienenden Straße Briefe an die Steuerbehörde sind.

Fazit: Kenneth Branagh träumt sich zurück in seine Kindheit in Belfast, aber sowohl erzählerisch als auch vor allem künstlerisch will für mich nicht viel zusammenpassen. Zu viel bühnenhaftes Theater lässt die Magie der Leinwand vermissen, auch wenn schauspielerisch einiges zu bewundern ist.