---
title: "Sieben Tage Portugal"
date: "2009-11-29T23:12:03"
categories: [gewesen]
---

... sind eindeutig zu wenig. Dennoch habe ich viel mitgenommen auf meiner ersten großen Urlaubsreise seit langem und will meine Erfahrungen und Empfehlungen nun in ein paar Artikeln festhalten. Dabei werde ich mich jeweils auf bestimmte Aspekte und Ziele wie das landestypische Essen oder die Stadt Lissabon konzentrieren und einen Mittelweg zwischen Reiseführer und -tagebuch einschlagen.

Dieser Artikel stellt dafür das Inhaltsverzeichnis dar. Anfangen werde ich mit einem Ausflug in die [Spezialitäten und Eigenheiten der portugiesischen Küche](/blog/2009/11/29/portugal-essen/). Danach folgt ein Bericht von der Ein-Tages-Tour meiner kleinen Reisegruppe durch die Metropole [Lissabon](/blog/2009/12/07/portugal-lissabon/). Nach einem Artikel über die Stadt  [Portimão](/blog/2009/12/29/portugal-portimao-und-ferragudo/), in der wir untergekommen waren, handel ich den Rest der [Algarve](/blog/2009/12/26/portugal-algarve/) mit einem einzigen Beitrag ab.

Final kann ich sagen, dass mir der Urlaub sehr gefallen hat. Ich denke, viel vom Land gesehen und kennengelernt zu haben und kann nun die Faszination verstehen, die die Algarve auf einige Bekannte von mir ausübt. Ein wenig mehr Zeit als ich sollte man sich aber gönnen, damit auch die Entspannung nicht zur kurz kommt.
