---
title: "Sackgasse der Evolution?"
date: "2008-03-12T22:18:30"
categories: [gedacht,gefunden]
---

Ein kürzlich erschienener Artikel zum Thema [Historische Formatflops](http://www.manager-magazin.de/it/artikel/0,2828,539888-3,00.html) bringt mich nun dazu, eine Lanze für die [MiniDisc](http://de.wikipedia.org/wiki/MiniDisc) zu brechen. Entgegen der Meinung der Autoren sehe ich das Sony-Format nämlich nicht als Flop, sondern als wichtigen Zwischenschritt zwischen der CD und den heutigen Platzhirschen, den MP3-Playern - mit ihrer [ATRAC](http://de.wikipedia.org/wiki/ATRAC)-Kodierung war Sony sogar deutlich früher am Markt als das vergleichbare MP3-Format, und die magneto-optischen MiniDisc-Medien boten von Anfang an digitale Informationen über die Musik vergleichbar mit den [ID3-Tags](http://de.wikipedia.org/wiki/ID3-Tag).

Als ich Anfang 2000 mein erstes MD-Gerät erwarb, einen tragbaren [MZ-R70](http://www.minidisc.org/part_Sony_MZ-R70.html), war vor allem das Format der MiniDisc ausschlaggebend. Ich wollte kein so großes und schweres Gerät wie einen CD-Player mit mir herumschleppen und erst Recht nicht unzählige CD-Medien, die nicht ausreichend robust für den täglichen Transport in einem Rucksack waren. MiniDisc-Player stellten zu diesem Zeitpunkt das kleinstmögliche Stück audiophiler Hardware dar, das man erwerben konnte, und die schmalen MD-Medien hielten nicht nur einem Rucksack stand, sondern theoretisch auch Nässe, Hitze und Druck - ich habe dies nie überprüft.

Zudem war es ein qualitativer Quantensprung von Kassetten auf MiniDiscs umzusteigen. Kein Rauschen mehr, dafür dauerhafte CD-Qualität - was wollte ich mehr? Über den digitalen Ausgang meiner PC-Soundkarte konnte ich außerdem die ersten Dateien meiner größer werdenden MP3-Sammlung überspielen. Dies dauerte zwar genauso lange wie das Abspielen (CDs konnten schneller überspielt werden), aber an tragbare MP3-Player und USB 2.0 war noch lange nicht zu denken. Als ein Jahr später ein Auto mit einem neuen Radio ausgerüstet werden musste, fiel die Entscheidung für ein MD-Radio ebenfalls nicht schwer - die allerersten MP3-Autotuner kosteten noch über 1000,-DM (mein [Kenwood](http://www.minidisc.org/part_Kenwood_KMD-673R.html) nur 450,-DM) und waren weit von einer benutzerfreundlichen Bedienung entfernt.

Wenn man sich um die Jahrtausendwende also die Frage stellte, wie man seine Musiksammlung auf möglichst kleinstem Raum mobil halten wollte, dann gab es nur eine Antwort: MiniDisc. Als Ablösung für das vorherrschende Musik-Verkaufs-Format Compact-Disc war die MD schon aufgrund der Größe ungeeignet, sie daran zu messen ist aus meiner Sicht also ungerecht - selbst wenn Sony selber mit vorbespielten MD-Alben und dem Festhalten an den 74/80min-Größen scheinbar diesen Anspruch hatte. Ein Ersetzen der Magnetbandkassette wurde dagegen teilweise erreicht. Aber selbst die MP3-Player haben die CD noch lange nicht aufs Altenteil geschoben, sondern präsentieren sich als logische Weiterentwicklung der MiniDisc. Aus dieser Perspektive betrachtet (und mit Darwins Theorie über die Evolution) ist Sonys MD zwar eine Sackgasse in der Enwicklung der Musik-Transport-Medien (wie die Kassette und Schallplatte ebenfalls), aber gerade durch ihre Konkurrenz konnten sich die MP3-Player erst zu ihrer aktuellen Übermacht entwickeln.

Man darf die Geschichte eben nicht ausschließlich aus der Perspektive der Sieger betrachten. Auch die HD-DVD hatte mit ihrer Idee, bestehende Technologien möglichst preiswert weiterzuentwickeln, ihre Daseinsberechtigung. Am Ende war es ironischerweise Sony, das eine Entscheidung zum anspruchsvolleren Format herbeiführte: Das Blu-ray-Laufwerk verzögerte erst den Start der PlayStation3 und verteuerte deren Hardware, doch mittlerweile gibt es dank dieser Konsole eine so breite Basis an Blu-ray-Playern in den Wohnzimmern, dass sich das gesamte Format durchsetzte. Bis jemand etwas besseres entwickelt...
