---
title: "Ubuntu 7.04 oder Die verwirrende Versionsnummer"
date: "2007-06-25T20:46:27"
categories: [gedacht,getan]
---

Nach mittlerweile einem halben Jahr hatte ich meinen Laptop nun so weit (Backupstrategie, Festplattenimage), dass ich mittels [GParted](http://gparted.sourceforge.net/) die Umformatierung der Festplatte angehen konnte - 60GB Systemplatte und eine versteckte 2GB Restore-Partition brauche ich wirklich nicht. Außerdem sollte es für Windows XP nun NTFS statt des vorinstallierten FAT32 sein. Das beim Kauf versprochene Vista-Upgrade hat sich nach dem Ärger mit Moduslink (siehe auch den [c't-Beitrag](http://www.heise.de/ct/tv/artikel/90328)) wahrscheinlich erledigt, aber zumindest ein Linux sollte als Zweitsystem mit auf den Rechner.

Die Wahl fiel schließlich auf [Ubuntu](http://www.ubuntu.com/) 7.04 (das *lebhafte Rehkitz*), was ich bis jetzt nicht bereut habe. Vor allem der 3D-Fenstermanager [Beryl](http://wiki.ubuntuusers.de/Beryl) läuft erstaunlich stabil, das sah unter SUSE ganz anders aus. Sogar an GNOME habe ich mich inzwischen gewöhnt. Ubuntu ist außerdem viel aufgeräumter mit der Standardinstallation, nur die vielen Spiele stören etwas diesen Eindruck. Aber dies lässt sich mit Synaptics ja schnell beheben, dessen Einsatz als zentralen Paketmanager mich ebenfalls in der Entscheidung pro Ubuntu bestätigte.

Aber was bitte denken sich die Ersteller der Distribution mit der Vergabe der Versionsnummer? Die Schreibweise 7.04 suggeriert ein Majorrelease 7 in der Version 4 (wie z.B. bei [openSUSE](http://de.opensuse.org)), doch es gibt keinen Vorgänger 7.03 (dieser ist 6.10) und der Nachfolger wird wahrscheinlich die Bezeichnung 7.10 tragen. Klar, die Ziffer vor dem Punkt steht für das Jahr (7 = 2007) und die zweite für den Monat (04 = April) des Releases, doch auf den ersten Blick sind die Nummern verwirrend. Da lobe ich mir doch [Gentoo](http://www.gentoo.de/) (aktuelle Version 2007.0) oder [Fedora](http://fedoraproject.org/) (aktuell 7), da ist die Systematik wenigstens sofort erkennbar.

Trotzdem habe ich nun ein produktiv laufendes Linux-System, unter dem auch gerade dieser Artikel entstand, und bin ganz zufrieden damit. Demnächst werde ich noch etwas über die diversen kleinen Probleme schreiben, welche ich dank Google schnell gelöst habe.
