---
title: "Heaven's Story"
date: "2011-02-18T23:29:49"
categories: [gesehen]
---

[Berlinale-Filmdatenblatt](http://www.berlinale.de/de/programm/berlinale_programm/datenblatt.php?film_id=20116083)

Auf der Berlinale gibt es neben vielen internationalen Filmen, die wohl niemals im Kino laufen werden, auch viele Experimente und extreme Filme zu sehen. In letztere Kategorie fällt der japanische Beitrag *Heaven's Story*, der mit ingesamt 278 Minuten eine Laufzeit von fast 5 Stunden (inklusive einer Pause nach 120 Minuten) besitzt und dem Zuschauer einiges an Sitzfleisch abverlangt.

Dabei beschreibt der Film eigentlich nur eine Rachegeschichte, welche die meisten Beteiligten ins Unglück stürzt. Doch diese Geschichte wird erzählt über einen Zeitraum von fast zehn Jahren und in sicher einem Dutzend paralleler Handlungsstränge, die sich naturgemäß ständig kreuzen und am Ende zusammenlaufen. Dreh- und Angelpunkt sind dabei Sato und Tomoki, die beide ihre Familie durch Morde verloren haben. Der Mörder von Satos Eltern und Schwester hat sich danach selber umgebracht, während der junge Mitsuo, der Frau und Baby von Tomoki erschlug, ins Gefängnis wanderte. Tomoki leistet daraufhin im TV einen Racheschwur, welcher die junge Sato stark beeindruckt und fortan am Leben hält.

Jahre später hat sich Mitsuo von einer an Alzheimer erkrankten Puppenmacherin adoptieren lassen und darf für die Pflege seiner Adoptivmutter das Gefängnis verlassen. Sato sucht deshalb Tomoki auf, der inzwischen ein neues Leben mit Frau und Kind aufgebaut hat, um ihn an seine Rache zu erinnern. Gemeinsam machen sie sich auf die Suche nach Mitsuo, doch damit besiegeln sie nicht nur das Schicksal des Jungen.

Diese Stellvertreterrache ist der zentrale Plot von *Heaven's Story*, doch um diese Hauptstoryline gibt es noch mehr Charaktere, denen viel Zeit gewidmet wird. So lernt der Zuschauer den Polizisten Kaijima kennen, der nebenbei als Auftragskiller arbeitet, um die Familie eines Kriminellen zu unterstützen, den er im Einsatz getötet hat. Dabei vernachlässigt er jedoch seinen Sohn, der immer wieder durch Diebstähle auffällt, und am Ende mit einer jungen, schwangeren Frau im Krankenhaus landet.

In diesem Teil der Handlung finden sich die schönsten Bilder, die der Film komponiert. So muss Kaijima einen Mann ermorden, der sich in einer winterlich verschneiten und verlassenen Siedlung in den Bergen verschanzt hat und ihm eine Schneeballschlacht liefert, während er später in einem Zoo einem angeschossenen Wächter hinterherläuft. Dabei werden ständig die Tiere in ihren Gehegen gegengeschnitten, so dass eine fast surreale Atmosphäre entsteht.

Doch hinter den schönen Bildern steckt nicht immer genügend Substanz, um die lange Laufzeit zu rechtfertigen. So blieb mir die Motivation von Kaijima verborgen, der einen Mord in Notwehr damit büßen will, indem er für die Hinterbliebenen sorgt. Doch warum hat er sich dann ausgerechnet einen Nebenjob als Auftragskiller ausgesucht, in welchem er noch mehr morden muss? Ganz abgesehen davon, dass den Film nicht einmal die Frage interessiert, wie man zu so einem Job kommt, und den Charakter dann in einer sehr kurzen Szene einfach entfernt, ohne nähere Details zu erläutern. Zeit dafür wäre genügend vorhanden gewesen.

Aber so bewegt sich *Heaven's Story* in seinen ganz eigenen Erzähltempo und -strukturen und versucht viel über seine Bilder zu erzählen. So sieht der Zuschauer wiederholt die Jahreszeiten an sich vorbeiziehen. Über die fünf Stunden Laufzeit wirkt jedoch die eingesetzte Handkamera, die niemals zur Ruhe kommt und ständig schwankt, anstrengend ermüdend. Da nützen auch die optischen Spielereien wie die animierte Möwe nichts, die als Überleitung zum Möwe genannten Hauskomplex dient, dem wichtigsten Handlungsplatz der zweiten Filmhälfte.

Ich bin mir auch ein paar Tage nach der Sichtung noch nicht sicher, was ich genau von *Heaven's Story* halten soll. Tolle Filmmomente wechseln sich ab mit langen, verwackelten Einstellungen, deren Bedeutung mir unverständlich blieb. Dies kann an meinem teilweise fehlenden Verständnis für die japanische Kultur liegen, aber eine übertriebene und unnötige Länge kann ich dem Film nicht absprechen. Mit stärker fokussierten Handlungssträngen hätte der Regisseur die Laufzeit sicherlich halbieren können und damit sogar die Seherfahrung intensiviert. So bleibt nur die unangenehme Erfahrung, fünf Stunden in einem Kinosessel gesessen zu haben, die ich ungern wiederholen möchte.
