---
title: "Die fabelhafte Welt der Amélie"
date: "2001-10-01T00:00:05"
categories: [gesehen]
---

*Frankreich (2001)
Regie: Jean-Pierre Jeunet
Darsteller: Audrey Tautou (Amélie), Mathieu Kassovitz (Nino), Rufus (Vater), Lorella Cravotta (Amandine Fouet), Claire Maurier (Suzanne), Isabelle Nanty (Georgette), Dominique Pinon (Joseph), Serge Merlin (Raymond Dufayel), Jamel Debbouze (Lucien), Yolande Moreau (Madeleine Wallace), Urbain Cancelier (Collignon) und andere fabelhafte Darsteller*
[Offizielle Homepage](http://www.amelie-lefilm.com/english/intro.htm)

Die junge Amélie wird aufgrund der falschen Annahme ihres Vaters, sie hätte einen Herzfehler, nur zu Hause aufgezogen und kommt so selten mit Gleichaltrigen in Berührung, was zu der Entwicklung einer beachtlichen Fantasie führt. Mittlerweile zur jungen Frau gereift, findet sie in ihrer Wohnung in einem Mietshaus in Montmartre eine Schatulle, die ein Vormieter versteckt hatte, was in ihr den Entschluß reifen läßt, ihre Fantasie einzusetzen, um positiv auf das Leben der Leute um sie herum einzuwirken. Doch dann trifft sie Nino, einen ebenfalls zurückgezogen aufgewachsenen jungen Mann, der Bilder aus Fotoautomaten sammelt, die andere Leute weggeworfen haben, und verliebt sich in ihn. Doch so leicht es ihr fällt anderen Gutes zu tun, so schwer erscheint es ihr den eigenen Traum zu erfüllen...

Als ich mich vom Kinosessel erhob war mein erstes Problem: Wohin mit all der positiven Energie, die der Film in einem erzeugt?! Amélie ist einfach der schönste, optimistischste und fantasievollste Film des Jahres! Und zumindest letzteres ist man gewöhnt von JP Jeunet, der sich schon für die skurilen Kinoperlen "Stadt der verlorenen Kinder" und "Delikatessen" verantwortlich zeigte (bei Alien 4 ist er ja leider - oder zum Glück für Europa? - gescheitert). Auch "Amélie" stattet er mit der Fantasie und den genialen Bildcollagen und Kameraeinstellungen aus, die jedem seiner Filme zu einem optischen Leckerbissen machen.

Aber im Gegensatz zu den bisherigen Filmen gestaltet sich Amélie sehr lebensfroh und optimistisch, auch wenn der scharze Humor seinen verdienten Anteil hat (der Tod der Mutter z.B.). Es ist fast wie ein Märchen, das Erwachen von Amélie mitzuerleben und die Einflüsse, die sie auf das Leben ihrer Mitmenschen nimmt - seien es nun die Mitbewohner ihres Mietshauses, ihre Gäste und Kollegen im Café oder ihr Vater. Und das alles geschieht mit einer großen Leichtigkeit und mit so vielen fantastischen Einfällen, dass man nur sagen kann: Danke Jeunet, danke, für dieses Kunstwerk!

Fazit: Dieser Film ist ein Meisterstück: Der schönste Liebesfilm und die skurilste schwarze Komödie des Jahres! Wer jedoch beide Genres nicht mag bzw. sich nur noch vom amerikanischen Fast-Food-Kino ernährt, dem sei mein Mitleid ausgesprochen.
