---
title: "Das verhinderte Upgrade"
date: "2008-07-24T21:19:26"
categories: [gedacht,getan]
---

Die [unendliche Geschichte](/blog/2007/09/30/lost-in-updates/) geht weiter: Mit jedem Major-Release meiner Blogsoftware Wordpress gibt es neue Probleme, die ein schnelles Update verhindern. Diesmal betrifft es die [Permalinks, die nicht funktionieren](http://wordpress.org/support/topic/189058). Damit wären alle Links innerhalb meiner Beiträge defekt, da nur noch die Standardeinstellungen ziehen. Sehr unschön.

Also muss das Upgrade noch etwas warten. Ein Glück, dass ich ein gebranntes Kind bin und vor der Serverinstallation lokal teste. Ärgerlich ist jedoch, dass eine zentrale Funktion einer Blogsoftware überhaupt defekt ist. Dies wirft ein schlechtes Licht auf die Qualitätssicherung im Projekt, und bei einem solchen Mängel sollte entweder das Release sofort zurückgezogen werden oder ein schneller Patch veröffentlicht werden. Die Vorschläge im Forum hatten jedoch bei mir keine Auswirkungen und selbst manuelle Patches nach dem Bugticket brachten keinen Erfolg. Also muss ich auf Version 2.6.1 warten und bis dahin mit der älteren Version leben - manche Dinge ändern sich einfach nie...
