---
title: "Making History"
date: "2008-11-14T00:04:48"
categories: [gelesen]
---

*von Stephen Fry,
veröffentlicht von arrow books, ISBN 0-09-945706-7, 11,62€*

Schon lange stehen die Bücher von Stephen Fry auf meinem Wunschzettel. Denn der Autor hat nicht nur eine witzige Einleitung zu Douglas Adams letzten unvollendeten Roman geschrieben, sondern mich auch als Schauspieler überzeugt. Zudem schwärmen die Kritiken von seinen Werken, so dass ich sofort zugriff, als ich eines seiner Bücher in der Fremdsprachenabteilung eines Berliner Händlers fand.

*Making History* spielt mit der schon oft behandelten Idee der Veränderung der Geschichte. Was wäre, wenn ich die Macht besäße, ein Detail in der Vergangenheit zu ändern, um sagen wir die Geburt von Adolf Hitler zu verhindern. Würde ich es tun? Der Hauptcharakter des Buches, Michael Young, nimmt die Chance natürlich wahr und findet sich plötzlich in einer vollkommen anderen Welt wieder. In Frys Parallelwelt wurde das Verlangen des deutschen Volkes nach einem Führer durch einen intelligenteren Menschen als Hitler befriedigt, der nicht die Fehler des Diktators machte und deshalb ganz Europa unter seine Kontrolle bringen konnte. So entwickelte sich ein Kalter Krieg zwischen Nazi-Europa und Amerika, der beiden Kontinenten nichts Gutes brachte. Dies muss auch Michael Young erkennen, der plötzlich eine vollkommen andere Identität hat und sich nur schwer in der verschlimmbesserten Welt zurecht findet.

Um seine erfundene Realität realistisch wirken zu lassen, hat Stephen Fry den ersten Teil des Buches mit Kapitel aus dem Leben von Adolf Hitler gespickt. Mit der Veränderung der Vergangenheit wechselt dies zu bekannten Episoden in der Entwicklung des Führers, nur mit seinem Ersatz Rudolf Gloder in dessen Rolle. Leider sind diese Episoden weder unterhaltsam noch spannend, so dass sie wie Fremdkörper im Buch wirken. Zudem sind sie in einer seltsamen Mixtur von Englisch mit deutschen Begriffen geschrieben, was noch befremdlicher wirkt wenn man bedenkt, dass eigentlich Dialoge zwischen Deutschen beschrieben werden.

Als sich Anti-Held Michael dann plötzlich als Englishman in Amerika wiederfindet, spielt Fry auch noch mit den Unterschieden zwischen British und American English - leider habe ich damit wenig Leseerfahrung, so dass sicherlich die meisten Sprachwitze an mir unerkannt vorüber gezogen sind. Dafür habe ich zumindest das eine oder andere Filmzitat erkannt; wenigstens etwas. Warum jedoch zwei Kapitel in Form von Drehbüchern gehalten sind, hat sich mir nicht erschlossen ("Weil's geht" zieht hier nicht!).

Alles in allem war ich enttäuscht von dem Buch. Es ist nur selten witzig, die Geschichte ist zu lang gestreckt und die Kapitel über Adolf Hitler bzw sein Alias sind einfach nur langweilig und zerstören unnötig den Lesefluss. Die für mich als SciFi-Fan verlockenden Spielereien mit der Parallelwelt beschränken sich auf wenige Ausnahmen, da stellt Fry lieber seine homosexuelle Liebesgeschichte in den Vordergrund. Vielleicht waren meine Erwartungen einfach zu hoch, aber so schnell werde ich nicht wieder zu einem Roman des Autoren greifen.

So, damit habe ich es geschafft, drei parallel gelesene Bücher abzuschließen. Da dies keinem der drei Werke gut bekam, werde ich dieses Experiment nicht wiederholen und lieber brav ein Buch nach dem anderen lesen. Zugfahrten für dieses Muße habe ich aktuell ja wieder zur Genüge.
