---
title: "Sunshine Cleaning"
date: "2009-11-23T22:25:04"
categories: [gesehen]
---

Wer mit *Die Feel-Good-Komödie des Sommers* und *von den Produzenten von Little Miss Sunshine* wirbt, der versucht oft, einem Film ein Image zu beschaffen, dass er ohne die Werbung nicht hätte. Mit letzterem Erfolgsfilm verbindet ihn aber nicht nur Name und Produzenten, sondern auch der Oscar-prämierte Alan Arkin, der sich wieder als leicht skuriler Opa verdingen darf.

Passend zum Zeitgeist wird das [Thema Tod](/blog/2008/10/22/pushing-daisies/) hier von seiner schmutzigen Seite aus betrachtet. Die junge Mutter Rose hat sich mit ihrer Schwester Norah im Bereich der Tatortsäuberung selbständig gemacht und findet darüber ihren Platz in der Gesellschaft. Das ist auch schon der gesamte Aufhänger der behäbigen Handlung, die sich voll auf die leider inkonsequente Charakterentwicklung verlässt. In den entfallenen Szenen finden sich viele alternative Sequenzen, die aufzeigen, dass das Drehbuch noch während er Dreharbeiten weiterentwickelt wurde. Gerade die interessante angedeutete lesbische Beziehung von Norah versandet unmotiviert, und so ergeht es auch den Nebenplots um den Großvater und die Beziehung zum einarmige Besitzer eines Reinigungsfachgeschäftes.

Ein wenig mehr Planung anstatt nach *Little Miss Sunshine* sofort nachlegen zu wollen hätte dem Film gut getan. Genauso wie mehr von dem beworbenen schwarzen Humor, der sich leider trotz des Potentials so gut wie gar nicht findet und etwas mehr Mut, als den zu mehr fähigen Alan Arkin in einer Kopie seiner Oscarrolle einzusetzen.

Wer den Film dennoch sehen möchte, braucht nicht das Geld für eine Blu-Ray ausgeben. Die höhere Auflösung bringt keine neuen Details zum Vorschein, der Sound besteht hauptsächlich aus Dialogen von der Front, so dass keinerlei Mehrwert aus der besseren Technik gezogen wird.
