---
title: "Der Dämon in mir"
date: "2008-02-17T19:20:19"
categories: [gesehen]
---

Die Welt ist schlecht. Dies jedenfalls vermitteln die Autoren des Films *The Woodsman*. Da wird der wegen Kindesmissbrauchs verurteilte Walter (grandios Kevin Bacon) einmal schwach und gerät dann ausgerechnet an ein 11jähriges Mädchen, das scheinbar vom eigenen Vater missbraucht wird. In diesem Fall ist dies jedoch ausgerechnet das Zeichen, dass der Mann gebraucht hat. Zu viel in seiner Umgebung ist aufgrund von verkorksten Kindheiten nicht in Ordnung, woraus Walter schließlich die Kraft zieht seine inneren Triebe unter Kontrolle zu halten.

Der Film ist geprägt von einer sensiblen Auseinandersetzung mit dem Thema Wiedereingliederung von straffällig gewordenen Pädophilen, immer aus der Sicht des ehemaligen Täters. Die Umgebung traut Walter nicht zu, dass er wieder ein normales Mitglied der Gesellschaft wird, und so gehen seine Kollegen sofort auf ihn los, als sie aufgrund der Recherche der Sekretärin von seinem Geheimnis erfahren. Hier wird eindeutig Stellung genommen zu der Idee, dass freigelassene Pädophile allen Menschen in ihrem Umkreis über die Tat informieren müssen - die Chancen auf Erfolg werden dadurch zumindest minimiert, impliziert der Film, als Walter den Druck nicht mehr aushält und von der Arbeit verschwindet.

Auch der als Bewährungshelfer zugeteilte Sgt. Lucas (Mos Def) glaubt nicht an seinen Schützling, steht ihm am Ende aber zumindest nicht im Weg. Es sind schließlich die wenigen Beziehungen von Walter, die sich nach der Freilassung bilden und ihm den notwendigen Halt geben. Zum Einen ist da der Mann seiner Schwester, der ihn ab und zu trifft und später auch eine erste Annäherung zwischen den Geschwistern initiiert. Zum Anderen weckt Walter das Interesse von Vicki (Kyra Sedgwick), die in ihrer Kindheit von ihren Brüdern missbraucht wurde und deshalb einen Antrieb hat, den Kern hinter der abweisenden Fassade zu finden. Und schließlich ist es die Beobachtung eines anderen Pädophilen, der direkt vor Walters Fenster Schulkinder beobachtet, die ihm einen Blick von außen auf sich selber erlaubt.

Alles in allem ist eine Wiedereingliederung in die Gesellschaft also ein komplizierter Prozess, der von vielen Faktoren abhängig ist, aber auch mehr Chancen auf Erfolg hat, als die Betroffenen selber denken. Dies ist die Botschaft, die *Der Dämon in mir* vermitteln will, und dies sehr eindrücklich erreicht.


