---
title: "Resident Evil"
date: "2002-03-20T00:00:13"
categories: [gesehen]
---

*USA/Deutschland (2001)
Regie: Paul Anderson
Darsteller: Milla Jovovich (Alice), Michelle Rodriguez (Rain), Eric Mabius (Matt), James Purefoy (Spence), Heike Makatsch (Lisa) und andere Zombies*
[Offizielle Homepage](http://www.resident-evil-film.de/)

Der Umbrella-Konzern, seineszeichens Marktführer für IT- und Gentechnik in den USA, entwickelt in seinem geheimen Forschungszentrum Hive 1 km unter der Erdoberfläche Kriegswaffen. Doch dann kommt es zu einem Zwischenfall, und der Zentralcomputer Red Queen flutet das gesamte Zentrum mit einem tödlichen Gas. Eine Gruppe von Soldaten soll den Computer abschalten, um wenigstens die Ergebnisse der Forschungen zu retten. Dabei werden sie von zwei Mitarbeitern des Zentrums begleitet, die zwar die Gasattacke überlebt, aber dummerweise dabei ihr Gedächtnis verloren haben; und auch ein angeblicher Polizist gehört zu der Gruppe, der jedoch in Wirklichkeit daran interessiert ist, Beweise für die illegalen Forschungen der Umbrella-Gruppe zu finden.

Doch schon beim Abschalten des Computers geht die Hälfte der Soldaten drauf, und bald muss der Rest der Gruppe nicht nur feststellen, welche Rollen sie im Umbrella-Konzern gespielt haben, sondern auch, woran hier wirklich geforscht wurde: Der T-Virus, der Menschen auch nach dem Tod noch lebendig hält, mit nur einem Ziel: Zu töten. Und das gesamte Labor ist voll von scheinbar Toten...

Es gibt ihn immer noch, den guten alten Splatterfilm! Und da er als eine Verfilmung eines beliebten Videospiels herkommt, hat sich mit Herrn Eichinger auch jemand gefunden, der dem B-Movie mal schnell ein A-Budget spendierte (was uns auch Heike Makatsch in einer kurzen Nebenrolle als Zombie beschert). Dementsprechend wartet der Film mit sehr guten Masken (vor allem der Zombies) auf, und auch die Kulissen können überzeugen, allein die Computereffekte (vor allem des letzten Monsters) müssen sich da etwas verstecken. Und auch bei den Darstellern konnte man auf bekannte Gesichter zurückgreifen, allen voran das 5. Element Milla Jovovich, die diesmal Amnesie-gestraft und meist nur leicht bekleidet nach und nach die Wahrheit um den Hive aufdecken darf, dabei jedoch keine Seite Text auswendig lernen musste.

Doch leider wurde an einer anderen Seite des Filmes Geld gespart: Der Regisseur Paul Anderson durfte nämlich auch gleich noch das Drehbuch schreiben, und das hat die genretypischen Logikfehler, die einen dann in den ruhigen Phasen fragen lassen, wieso kein anderer das Script mal wenigstens durchgelesen hat vor dem Dreh. Zwar gibt es ein paar hübsche Handlungswendungen, aber die Dialoge sind einfach mies und zum Teil auch gar nicht zum Geschehen passend ("Wir bilden jetzt eine Kette"). Ganz abgesehen davon, dass die aus dem Videospiel stammende Hauptidee mit dem Zombie-T-Virus ganz abstruser Schwachsinn ist - aber das dient einfach nur als Aufhänger für die vielen Horror-Action-Szenen, die dann auch gut gelungen sind und es dem Zuschauer etwas erleichtern, den Film zu überstehen. Und das Ende gibt schließlich einen Ausblick darauf, wie es weitergeht in Teil 2: Alice kämpft sich mit Pumpgun und noch weniger Bekleidung durch eine ganze Stadt von Zombies, wobei mangels Gesprächspartnern die Dialoge komplett gestrichen werden...

Fazit: Es gibt nur 3 Gründe, um sich diesen Film anzusehen. Der erste ist, ganz klar, dass man Fan des Spieles und damit auch des Genres Splatterhorror ist - dann fallen die schlechten Dialoge und die zusammengeschusterte Hintergrundstory gar nicht auf, da sie aus der Vorlage bekannt sind. Der zweite Grund ist natürlich Milla Jovovich - noch freizügiger als im *Fünften Element* und mit noch weniger Dialogzeilen ist sie klar das Highlight des Films. Und auch als Zombie sollte man *Resident Evil* gesehen haben...
