---
title: "Kein Heimwerker-King"
date: "2007-12-09T18:14:47"
categories: [gedacht,getan]
---

Möbel zusammenbauen und Lampen aufhängen gehört definitiv nicht zu meinen Lieblingsbeschäftigungen. In 3 Metern Höhe überkopf (die Leiter ist scheinbar zu klein für meine Altbauwohnung) dünne, kleine Drähte festschrauben und gleichzeitig die daran hängende Lampe zu balancieren artete zu einer für mich ungewohnten Balastung aus.

Dabei hatte ich mir extra den Akkuschrauber der Eltern ausgeliehen. Doch 1cm unter der Decke horizontal Schrauben festdrehen ist für dieses Werkzeug einfach nicht machbar. Bessere Dienste leistete das Gerät dann beim Zusammenbauen der Schublade meines neuen Badschrankes. Da hatten die Konstrukteure doch leider vergessen, Löcher vorzubohren. So musste ich aufwendig 5cm lange Schrauben ins Holz drehen, die sich standhaft dagegen gewehrt haben.

Manchmal lohnt es sich wahrscheinlich, mehr Geld auszugeben und sich dafür den Stress zu Hause zu ersparen. Dann bekommt man sicher auch eine vernünftige Anleitung mitgeliefert, auf der die zwei Meter langen Seitenteile nicht nur auf 3cm abgebildet sind und man deshalb auch erkennt, wie herum die Schubladen-Schienen montiert werden müssen. Und mit etwas Glück sind die Spaltmaße dann so passend, dass zwischen Schublade und Schiene nicht auf jeder Seite 5mm Platz bleiben bzw die Schrauben mit entsprechender Länge mitgeliefert werden.

Nunja, die Lampe hängt und funktioniert, der Badschrank erfüllt ebenfalls seine Zweck und ich werde dieses Jahr nicht noch einmal Werkzeug in die Finger nehmen...

