---
title: "Gravity"
date: "2013-11-19T22:02:38"
categories: [gesehen]
---

*USA/UK (2013)
Regie: Alfonso Cuarón
Darsteller: Sandra Bullock (Dr. Ryan Stone), George Clooney (Matt Kowalski)*
[Offizielle Homepage](http://www.gravity-derfilm.de/)

Die Astronauten Dr. Ryan Stone und Matt Kowalski sind im Einsatz am Hubble-Teleskop, als Trümmerteile von Satelliten ihr Shuttle zerstören. Ihre einzige Chance auf eine Rückkehr zur Erde besteht darin, mit den Antriebsdüsen von Kowalskis Raumanzug bis zur ISS zu fliegen - wenn denn der Treibstoff und die Luftreserven reichen...

Ganz am Ende des Films mehren sich Szenen, die prototypisch für *Gravity* sind. Da sieht der Zuschauer in einer beeindruckenden Plansequenz wie Sandra Bullock sich schwimmend aus einem See rettet um am schlammigen Ufer erschöpft liegen zu bleiben. Kurz darauf rafft sie sich jedoch auf und erhebt sich mit letzter Kraft, von der Kamera aus Bodenperspektive festgehalten.

Technische Perfektion trifft hier auf einen plakativen Verweis auf den Filmtitel. Bullocks Figur darf stellvertretend für die gesamte Menschheit deren Evolution in Sekunden nachvollziehen und damit den gewonnenen Kampf gegen die Schwerkraft noch einmal ausfechten. Denn die Raumfahrt ist in *Gravity* nichts anderes als die Überwindung der Bindung an den Erdenkörper - die jedoch in der Sehnsucht der Raumfahrer weiterlebt und so niemals komplett gekappt wird.

Von diesem Thema erzählt der Film in einer minimalen Figurenkonstellation und gleichzeitig technisch brillianten Materialschlacht. Diese Extreme setzen sich auch beim Soundtrack fort, der wiederholt in dramatischen Situationen als Ersatz für die fehlende Akustik des Weltraums crescendo-artig in den Vordergrund drängt, nur um dann minutenlang zu schweigen und den Zuschauer mit den Funksignalen allein zu lassen

Als Ergebnis hatte ich zum ersten Mal seit *2001* wieder das Gefühl, eine realistische Darstellung der Raumfahrt zu sehen. Cuarón schafft es, die Gefahren des Weltraums greifbar zu machen, die Hilflosigkeit des an dieses Habitat nicht angepassten Menschen intensiv zu verdeutlichen. Der Zuschauer erlebt, was es bedeutet, ohne Orientierung in der Leere zu treiben, weil in der Schwerelosigkeit ein Impuls ausreicht, um für immer im unendlichen Raum zu treiben. Er sieht aus der Perspektive von Ryan die Folgen der Luftlosigkeit, die der Mensch nicht nur zum Atmen benötigt sondern auch als Träger von Wärme, Sprache und anderen Geräuschen. Die Zerstörungen der diversen Raumstationen und -kapseln werden dadurch, dass sie nicht zu hören sind, umso intensiver und vor allem gefährlicher wahrgenommen.

Doch *Gravity* funktioniert nur in dieser engen Umarmung von Handlung und -ort. Wenn ich mir das Weltall wegdenke, dann bleibt auf der Handlungsebene die Odyssee eines Menschen durch undenkbare Katastrophen übrig, die in ihrer ständigen Steigerung des Schleifencharakters (Aufbruch zum nächsten Rettungsanker -› Probleme auf dem Weg dahin -› Ankunft und Ernüchterung) fast schon kafkaesk wirkt. Nur dass die Reise hier auf ein Ziel hinausläuft und am Ende Ermüdungserscheinungen durch den repetativen Charakter zeigt.

Dies liegt auch daran, dass Sandra Bullock den größten Teil des Films ohne jegliche Interaktion mit anderen Schauspielern auskommen muss - ein schweres Unterfangen, vor allem bei Bluescreenaufnahmen, denen zusätzlich das Szenenbild fehlt. Dies funktioniert in den Situationen gut, in denen sie aufgrund der unglaublichen Pechsträhne am Verzweifeln ist und ihre Wut in eine kleine Raumkapsel hinausschreit oder mit den vielen chinesisch beschrifteten Knöpfen eines Bedienpultes klarkommen muss. Da habe ich ihr die im Grenzbereich agierende Astronautin abgenommen. Wenn sie jedoch ihre allzu dramatische Hintergrundgeschichte im Dialog mit einem sie nicht verstehenden Funker auf der Erde aufarbeiten oder die plakative Aussage "Es liegt alles an Dir, die Situation zu verändern" transportieren muss, dann wirkte es auf mich nur aufgesetzt. Letztere Szene nutzt Cuarón aber sehr geschickt, um die Auswirkungen von zu viel CO₂ in der Luft zu demonstrieren und gleichzeitig George Clooney noch einmal ins Bild zu holen - eine willkommene Abwechslung, trotz seines kaum ausgearbeiteten Charakters.

In all seiner technischen Brillianz, die bis auf die Ausstattung des Raumstationen durchschlägt (welche jeweils kaum eine Minute von innen zu sehen sind), leistet sich *Gravity* doch ein paar Unglaubwürdigkeiten. Nehme ich die Verkettung von unglücklichen Umständen noch als Handlungsgrundlage hin, so glaube ich jedoch nicht, dass Drucktüren immer so extrem aufspringen wie gezeigt - sonst müssten ständig Astronauten im All verloren gehen. Und was Cuarón an Vorurteilen über Russen und Chinesen auftischt kratzt ganz schön an der ansonsten realistischen Fassade des Films: Die Russen werden mit ihrer Raumkapsel und der nicht funktionierenden Treibstoffanzeige als inkompetent dargestellt, haben aber natürlich einen versteckten Vodka an Bord, während in der chinesischen Station Tischtennisschläger durch die Gegend schweben.

Visuell bombastisch, akustisch übertrieben, beklemmend dramatisch - mit feinen Tönen hält sich Regisseur Cuarón nicht auf. Am Ende bleibt trotz der vielen Ecken ein sehr intensiver Film in Erinnerung, der vor allem mit seiner beeindruckend realistischen Abbildung des Weltraums überzeugen kann.
