---
title: "Die zehn schlechtesten Filme"
date: "2010-04-19T23:23:11"
categories: [gedacht,gesehen,gefunden]
---

... die man je gesehen hat, soll der geneigte Blogger nennen, um an der [Blogparade von Gilly's playground](http://blog.gilly.ws/2010/03/19/blogparade-die-zehn-schlechtesten-filme-die-ihr-je-gesehen-habt) teilzunehmen. Da mache ich das doch einfach:

**Striptease**
Als Erstes die Standardausrede, die ich bei fast jedem Film heranziehen muss: Ich war jung und wusste es nicht besser. Mehr als die grottenschlechten 115 Minuten, die scheinbar nur gedreht wurden, um einmal die künstlichen Brüste einer alten Frau zu zeigen, hat mich im Nachhinein jedoch geärgert, dass wir damals im Kino standen und die Wahl zwischen dieser Gurke und *Trainspotting* hatten...

**Streetfighter - Die entscheidende Schlacht**

Ja, ich mag Videospiele. Und Anfang der 90er mochte ich auch einmal die Streetfighter-Serie, die jedoch bei ihrer Leinwand-Adaption nicht nur unter [JCVD](http://de.wikipedia.org/wiki/JCVD) und Kylie Minogue zu leiden hat. Denn man hat um die Charaktere des Spiels eine selten schlechte Handlung gewoben und fast jede Ähnlichkeit mit der Vorlage vermieden.

**Species**

Apropos Handlung: Eine sinnvolle Geschichte geht *Species* leider vollkommen ab, was aufgrund der tollen Besetzung (Ben Kingsley, Michael Madsen, Alfred Molina, Forest Whitaker) sehr ärgerlich ist. Auch hier schienen die Produzenten damit zufrieden zu sein, Nerds mit viel nackter Haut anzulocken. Die schlechten Dialoge ruinieren aber alles.

**Alien vs. Predator**

Die Alien-Serie gehört zu den Klassikern des Sci-Fi-Kinos, doch in diesem Mash-Up mit Arnies Predatoren bleibt von der zugleich anziehenden wie abstoßenden Gefährlichkeit der Aliens nicht viel übrig, stattdessen wird viel gekämpft und geschossen und zwei faszinierende Rassen werden in einer sinnfreien Ruinenstory verheizt.

**Fantastic Four**

Nachdem es mit den *X-Men* und *Spiderman* so gut lief im Kino, durften auch die Fanta 4 auf der großen Leinwand antreten. Doch neben schlechten Schauspielern (Jessica Alba ist wirklich unterirdisch) nervt die Blaupausen-Story. Zum Glück hatte ich Premieren-Freikarten, denn sein Geld ist der Film definitiv nicht wert!

**Iznogud**

Auch die Franzosen können Comicverfilmungen in den Sand setzen. Als Fan der Vorlage war ich schon von der Zeichentrickserie enttäuscht, aber der Film schafft es, noch schlechter zu sein und vor allem mit voranschreitender Laufzeit immer mehr an Niveau zu verlieren. Ich denke, deshalb war er im Nachmittagsprogramm von RTL ganz gut aufgehoben.

**Van Helsing**

CGI-Action der allerschlimmsten Sorte, da kann auch Kate Beckinsale in Leder nichts daran ändern.

**Otto - Der Katastrofenfilm**

Otto war schon 2000 nicht mehr lustig; auch das erfolgreiche deutsche Konzept der Parodie ging mit diesem Film nicht auf. Allerdings hat er die Welle der Pinguin-Filme quasi losgetreten - das ist doch zumindest etwas, selbst wenn der Running-Gag schon vor dem Ende versandet.

**Spice World - Der Film**

Ich war jung und wusste es nicht besser. Und der Film, trotz seiner Anlehnung und in direkter Fortführung der Beatles-Filme, war noch schlechter als aus heutiger Sicht die Musik der Girlgroup.

**Der Geist und die Dunkelheit**

Ich war jung und ... Menschen, Tiere, Sensationen. So schön literarisch der Titel klingt, so platt ist der Film umgesetzt. Zwei unmotivierte Schauspieler dürfen in Afrika Rachegelüste an Löwen auslassen. Ganz schwaches Kino!


Diese Filme sind natürlich nur eine Auswahl, aber bei jedem habe ich mich definitiv geärgert, die Zeit und teilweise sogar das Geld investiert zu haben. Aber vielleicht gewinne ich ja einen Amazon-Gutschein, der dies wieder ausgleicht!
