---
title: "Die Welt zu Gast bei Abzockern"
date: "2005-11-04T10:22:55"
categories: [gedacht,gefunden]
---

Momentan ist es dem gemeinem Fan möglich, sich für die Fußball-WM nächstes Jahr in eine Warteliste für Optionstickets einzutragen. Das sind Tickets, die möglicherweise von Sponsoren und Verbänden zurück gegeben werden, weil diese sie nicht nutzen. Positiverweise will das WM-OK die Option auf so ein Tickets an die Fans weiter verkaufen, aber jetzt kommt der Hammer:

Es gibt neue [Ticket-Geschäftsbedingungen für das Optionsticketprogramm](http://tickets.fifaworldcup.com/contexthelp/wmd/atgb.htm#batgb), in denen sich das WM-OK das Recht nimmt, die Ticketpreise sofort ab zu buchen und erst bei Nicherteilung der Tickets kurz vor dem registrierten Spiel zurück zu buchen - natürlich ohne die Optionsticketgebühr von 5 Euro. D.h. auch wenn einem die Tickets nicht zugeteilt werden, zahlt man trotzdem eine Gebühr von 5 Euro und gibt dem WM-OK einen kostenlosen Kredit bis zum jeweiligen WM-Spiel.

Dabei zeigt sich erneut, als was die Organisatoren die Zuschauer im Stadion ansehen: Zu melkende Geldkühe, auf deren Kosten die neusten Technologien und Sicherheitsmaßnahmen ausgetestet werden. Dabei arbeiten Staat, Veranstalter und Privatwirtschaft Hand in Hand und der Verbraucherschutz bleibt außen vor. Das WM-OK schafft es mit der neuen Regelung sogar, das gesamte geschäftliche Risiko auf die Kunden ab zu wälzen. Wo bezahlt man sonst für Monate im Voraus eine Gebühr für eine Option und schießt den Produktpreis gleich mit vor? 

Aber warum funktioniert das Ganze? Weil sich die Organisatoren sicher sein können, dass die dummen Fans trotzdem alles daran setzen werden, um Karten für dieses einmalige Ereignis zu erhalten - egal zu welchem Preis. Das sie dies so schamlos ausnutzen wirft einen dunklen Schatten auf die Veranstalter. Nur scheint dies nicht auf die prominenten Mitglieder des WM-OK wie Franz Beckenbauer zurück zu fallen, die in den Medien nie mit diesen Missständen konfrontiert werden. Am Ende bleibt alles an den Verbrauchern hängen, die scheinbar keine Chance haben, sich gegen diese Abzockermethoden zu wehren.
