---
title: "Why does it always rain on me"
date: "2008-09-07T16:04:11"
categories: [gewesen,getan]
---

Es wird Herbst. Und mit dieser Jahreszeit hält auch das nasse Wetter wieder Einzug; mich hat es die gesamte Woche über begleitet.

Dabei war es zum Glück nur ein kurzer Schauer, der am Donnerstag nieder ging, als ich zur Verabschiedung eines Kollegen mit dem Team von der Arbeit im [Hochseilgarten am Ostkreuz](http://www.teamventure.de/index_home_TVSP.htm) war. Dort kann man in 10 Metern Höhe von Plattform zu Plattform über verschiedene Hindernisse und Seilkonstruktionen balancieren. Eigentlich kein Problem, wenn da nicht die Höhe wäre und damit meine Höhenangst ins Spiel kommt. So stand ich gut gesichert auf einer schwankenden Plattform und hatte weiche Knie, während ich den Instruktionen des Personals lauschte.

Doch manchmal braucht es nur einen kleinen Schubser, um die eigenen Ängste zu überwinden oder zumindest zeitweilig zu vergessen. So bin ich einfach einem Kollegen hinterhergeklettert (Gruppenzwang) und habe versucht, nicht nach unten zu schauen. Die Sache mit dem Gleichgewicht hat dann auch so gut funktioniert, dass ich mir nach und nach alle Strecken zugetraut habe und jetzt ziemlich stolz auf mich bin. Diese Erfahrung kann ich jedem ans Herz legen.

Weniger Spaß gemacht hat dagegen das Beachvolleyball-Spielen am Montag in strömendem Regen. Dabei sind die sich mit Wasser vollsaugenden Klamotten weniger das Problem als der nasse Sand, der an allem kleben bleibt - inklusive dem Ball. So hat man den Sand bei oberen Zuspielen schnell auch in den Augen und kein sauberes Stück Kleidung mehr, um ihn heraus zu reiben. Die Erkenntnis lautet also, beim nächsten Regen lieber das Spiel abzusagen.

Und eine weitere Erkenntnis ist, dass man Samstag nacht (bei mal wieder strömenden Regen) nicht im FlowerPower absacken sollte, jedenfalls nicht mit einer Gruppe Raucher. Memo an mich: Diesmal diese Erkenntnis nicht wieder vergessen.
