---
title: "Ich bin kein Berliner"
date: "2007-09-16T15:46:55"
categories: [gelesen]
---

*von Wladimir Kaminer,
erschienen bei Goldmann Manhattan, ISBN 978-3-442-54240-6, 8,95€*

Eigentlich wollte ich mein Blog nach dem Umzug in die Hauptstadt umbennenen. Doch dann fehlte mir die Zeit zum Bloggen und als ich wieder damit anfing, gab es plötzlich dieses Buch des [Russendisko](http://de.wikipedia.org/wiki/Russendisko)-Autoren Wladimir Kaminer, der auf den selben nicht sehr originellen Gedanken gekommen war. Da damit die ersten 100 Seiten der Google-Suche mit Verweisen auf Buchhändler belegt sind, habe ich das Umbennen erst einmal auf Eis gelegt.

Doch zurück zum Buch. Da ich mich in meiner Wahlheimat alles andere als heimisch fühle, hat mich der Buchtitel sofort angesprochen. Nach der Lektüre habe ich jedoch Angst, dass es mir genauso ergeht wie dem Autoren: Berlin ist nur als Durchgangsstation gedacht, doch Wladimir Kaminer ist mittlerweile 17 Jahre dort und kommt nicht so richtig fort.

Der Untertitel "Ein Reiseführer für faule Touristen" ist dagegen nur als Alibi zu verstehen - Kaminer schreibt wieder einmal über seine Stadt und ihre Bewohner, egal wie das Buch heißt. Dazu gliedert er seinen "Reiseführer" in kurze Kapitel, die sich mit Themen wie Berliner Geschichte, Berliner Mode, Berliner Wirtschaft usw befassen. Jedoch wird alles aus dem zum Glück nicht sehr objektiven Blickwinkel des Autoren beschrieben, auch die kurzen Hinweise für die Touristen am Kapitelende, die im Anhang etwas ausführlicher beschrieben werden. Bis auf die Gedächtniskirche fehlen jedoch die Haupttouristenattraktionen, so dass der Reiseführer wohl eher für Berliner gedacht ist, die wissen über was geschrieben wird.

So hangelt sich Kaminer anhand verschiedener Eigenschaften der Berliner durch die nicht sehr ernstgemeinte Geschichte der Stadt, erzählt Anekdoten aus seiner Zeit beim ZDF und vor allem seine eigenen Erfahrungen mit der Stadt. Dies liest sich ganz amüsant und lebt vor allem von der Kombination der bekannten Vorurteile gegenüber Stadt und Einheimischen und den skurilen Schlüssen, die er mit seinem russischen Hintergrund und der Beobachtung seiner Mitmenschen daraus zieht.

Die 215 Seiten ohne Anhang (in großer Schrift auf kleinen Seiten) sind jedenfalls schnell geschafft und ein paar neue Informationen über meine Wahlheimat habe ich auch gewonnen. Jetzt dürstet es mich aber wieder nach einem richtigen Roman und nicht nur Popkultur in kleinen Häppchen.

