---
title: "Harry Potter and the Deathly Hallows"
date: "2008-11-23T01:05:59"
categories: [gelesen]
---

*von Joanne K. Rowling,
erschienen bei Bloomsbury, ISBN 978-0-7475-9105-4, 18,90€*

Die ersten sechs Harry-Potter-Bücher hatte ich Anfang 2006 noch fast ohne Unterbrechung gelesen. Doch als 2007 der letzte Teil erschien, war der Kontakt zu meinem Dealer leider seltener geworden und so bekam ich Band Sieben erst diesen Monat von einem Kollegen ausgeliehen. Und es war, als hätte ich keine zwei Jahre Pause gehabt. Sofort waren die Erinnerungen wieder da und das Buch fesselte mich dermaßen, dass ich neben Arbeit und abends Weggehen in fünf Tagen mit den 600 Seiten durch war.

Harry Potter steht diesmal vor dem endgültigen Duell mit Lord Voldemord, um die Prophezeihung zu erfüllen, dass keiner von beiden überleben kann, solange der andere noch lebt. Davor muss er die Aufgabe erfüllen, die Dumbledore ihm vor seinem Tod aufgetragen hat: Die vier verbleibenden Horcruxes zerstören, die Voldemorts Existenz absichern. Doch wie findet man diese kostbaren Objekte, und was hat das mit der Geschichte im die Heiligtümer des Todes zu tun, die Dumbledore Hermione vererbt hat?

So weit die Ausgangsbasis und die Fragen, die sich alle Fans gestellt haben. Wie kann der noch nicht einmal erwachsene Harry Potter ohne die Hilfe von Dumbledore gegen Voldemort ankommen? Und wie können die vielen begonnenen Handlungsfäden zu einem Abschluss geführt werden? Doch anstatt die Fragen zu beantworten, schickt Frau Rowling ihre drei Helden erst einmal auf eine spannende Flucht vor den Death Eatern und wirft neue Fragen auf. Ab der Mitte des Buches zieht dann das Tempo enorm an, wenn sich erste Zusammenhänge erschließen und fortan konnte ich den Band nicht mehr weglegen.

Leider muss es mit einem heroischen Kampf, einer Riesenschlacht vor Hogwarts, enden. Nach all den wunderbaren Spielereien mit den Gewohnheiten des Genres fühlt sich dies irgendwie unpassend an. Zudem gibt es sehr viele Tote unten den liebgewonnenen Charakteren, so dass es verständlich ist, dass eine Kinderfassung des Buches gibt. Aber auch die Erwachsenen-Fassung fühlt sich teilweise wieder wie ein Kinderbuch an, zu geradlinig verläuft die Handlung.

Dazu bei trägt das total ungewohnte Happy-End zum Schluss. Nach sechs Bänden, in denen Voldemort einfach nicht unter die Erde zu bekommen war, ist die Buchreihe jetzt wirklich zu Ende. Und um etwaigen weiteren Fortsetzungen einen Riegel vorzuschieben, hat Joanne K. Rowling ein Kapitel zwanzig Jahre später hinterhergeschoben, dass eine so glückselige Zukunft ausmalt, dass es schon wieder unangenehm ist. Dafür gibt es in der Vergangenheit noch viele Lücken in der Geschichte. Zum Beispiel hätte ich gerne mehr über [Grindelwald](http://www.harrypotterwiki.de/index.php/Gellert_Grindelwald) und seine Verbindungen zum Zweiten Weltkrieg erfahren. Vielleicht bekommen wir ja auch noch eine Dumbledore-Biografie nachgeliefert.

Wenn ich nicht wüsste, dass die Verfilmung bereits in der Vorproduktion ist, hätte ich vermutlich das Buch für unverfilmbar erklärt. Zwar wird inhaltlich nicht ganz so viel geboten wie im [fünften Teil](/blog/2007/07/22/harry-potter-und-der-orden-des-phoenix/), doch fast alle Handlungsorte der ersten sechs Bücher plus einige neue werden, wenn meist auch nur kurz, im Verlauf besucht. Ähnlich verhält es sich mit den vielen Nebencharakteren, die die Serie bisher angehäuft hat. So erscheint die Aufteilung auf zwei Filme sinnvoll, und um die Refinanzierung des Goldesels muss man sich bei Warner ja keine Sorgen machen.

Fazit: *Harry Potter and the Deathly Hallows* ist der verdiente Abschluss für eine große Fantasy-Buchreihe, aber nicht deren bester Teil. Der Leser bekommt ein Happy-End und endlich alle Fragen beantwortet, muss dafür aber auch einen großen Endkampf, viele Tote (das Fantasy-Standard-Schema also) und ein schmalziges Happy-End in Kauf nehmen.

Nur eine Frage blieb für mich unbeantwortet: Warum fliegt auf der [Rückseite des Buches](http://images.ociotakus.com/harry-potter-deathly-hallows2.jpg) eigentlich die Enterprise hinter Hogwarts entlang?
