---
title: "Schillers sämtliche Werke ... leicht gekürzt"
date: "2010-12-18T00:35:36"
categories: [gewesen]
---

Was haben *Don Carlos* und *Der Pate*, *Wallenstein*, Bruno Ganz und Goethe gemeinsam? Eigentlich gar nichts. Und doch mischt das Kabarettstück *Schillers sämtliche Werke ... leicht gekürzt* alle diese Themen zu einem zweistündigen unterhaltsamen Theaterabend zusammen. Ursprünglich am [Altonaer Theater in Hamburg](http://www.schillerban.de/) aufgeführt, hat es eine sanft lokalisierte Fassung des Stückes nun nach Halle geschafft und wird von der [Kulturreederei](http://www.kulturreederei.de/) im alten Fernsehstudio gespielt.

Als Hommage an den großen deutschen Dichter gedacht, wechseln sich auf der Bühne vier Akteure dabei ab, Episoden aus Schillers Biographie und kurze Auszüge aus seinen Werken vorzutragen und deren mögliche Einflüsse auf moderne Unterhaltungswerke aufzuzeigen. Dabei sind die Übergänge zwischen den einzelnen Rollen und Stücken fließend und es gibt eine weitere inhaltliche Ebene, in der die vier Akteure eigene Schauspielercharaktere verkörpern, die jedoch sehr klischeehaft angelegt sind. So nervte mich die im Original von Hilmi Sözer dargestellte Rolle, die nur auf Vorurteilen gegenüber Ausländern basiert, und ständig unpassend zwischen Pseudo-Slang und Hochdeutsch pendelt. Das passt innerhalb des Stückes nicht, und zu Schillers Werken schon gar nicht.

Vorbildung in Sachen Schiller ist ansonsten nicht notwendig - alle Szenen werden in ihren inhaltlichen wie zeitlichen Kontext gesetzt. Etwas popkulturelle Bildung kann dagegen nicht schaden, um u.a. die Dialoge aus dem Paten zu erkennen. Klassische Hochkultur ist also nicht erwarten, eher postmodernes Referenzentheater. So schafft es das Stück, gleichzeitig unterhaltsam zu sein und beim Publikum Interesse für das Werk von Schiller zu wecken, das seine Dramen betreffend vollständig abgehandelt wird.
