---
title: "Deutschland macht dicht"
date: "2012-01-08T00:01:04"
categories: [gelesen]
---

*von Dietmar Dath,
erschienen im Suhrkamp Verlag, ISBN 978-3-518-42163-5, 17,80€*

Um das Land vor negativen Einflüssen aus dem Ausland zu schützen, hat der Bundeskanzler beschlossen, Deutschland dicht zu machen und von der Außenwelt abzuschotten. Dazu werden die Grenzen in einem komplexen Prozess einfach von außen nach innen umgestülpt und das Land vom Rest der Welt abgenabelt. Doch leider hat das Geld diese Aktion mitbekommen und sich in den Prozess eingemischt, da es um seinen Einfluss fürchtet. So geht die ganze Aktion fürchterlich schief und Deutschland verwandelt sich in ein chaotisches Labyrinth, in dem plötzlich alles umgedreht ist. Kein Weg führt mehr an sein Ziel, kaum ein Stein blieb auf dem anderen. Der aus einer Idee manifestierte Plüschhase Mandelbaum muss sich zusammen mit den jugendlichen Helden Hendrik und Rosalie und dem ältesten Kommunisten Deutschlands auf den Weg machen, um die Dinge wieder zu richten. Dazu müssen sie einen Weg in das Schloss des Geldes finden, ein Hochhaus in Frankfurt, vorbei an der Bestie Sumsilatipak und einem fanatischen Terrorkäse...

War die [Abschaffung der Arten](/blog/2011/05/08/die-abschaffung-der-arten/) noch eine wilde Mixtur der unterschiedlichsten Genres und Stile, so ist [Deutschland macht dicht](http://rosalievollfenster.de/) zwar eine weitere Stilübung von Dietmar Dath, aber dafür eine durchgängige. Er wendet sich dem Jugendroman zu und erzählt seine märchenhafte Parabel aus Sicht der jugendlichen Protagonisten. In dazu passender Form gibt es kurze Kapitel mit kurzen, einfach gebauten Sätzen, die von Illustrationen begeleitet überraschend leicht zugänglich und vordergründig verständlich sind. Doch Dath wäre nicht Dath, wenn er nicht selbst in den engen Grenzen des Genres seinen ganz eigenen Stil einer technologisierten Kunstsprache verfolgen würde. Ebenso typisch ist der breite Kanon an angerissenen Themen wie Religion, Kultur, Journalismus bzw Medien allgemein und die niemals fehlende politische Systemkritik mit starker Linkstendenz.

Diese ist mal fantasievoll polemisch wie bei der Bestie Sumsilatipak (rückwärts lesen), mal scharf und direkt wie bei den vom Geld manipulierten Halbmenschen und anderen Systemunterstützern mit ihrer ewig gleichen Litanei. Die Welt ist jedoch durchgehend einfach gestaltet und passend zum Genre sind Gut und Böse schnell zu erkennen. Dath wagt sich sogar an pubertäre Probleme heran und lotet das Genre aus bis zum Abenteuerroman, ohne jedoch über eine oberflächige Imitation desselben hinauszukommen.

Das Buch mündet schließlich in einem actionreichem Finale, dass vielleicht etwas zu stark aufträgt mit einem Kung Fu kämpfenden Jesus und verworrenen Traumzeitreisen. Ich hatte zum Schluss das Gefühl, dass Dath sich schwer daran tat, aus der Fülle der Ideen eine funktionierende Handlung herauszuschälen. Meist wachsen in Jugendbücher die jungen Helden über sich hinaus; hier dagegen werden sie von einer gottgleichen Kraft gerettet, die sämtliche vorherigen Bemühungen und Erfahrungen an Wert verlieren lässt - die primitivste aller Lösungen für einen Konflikt.

Trotzdem ist *Deutschland macht dicht* durch die Vermischung von Daths Dauerthemen mit dem Genre des Jugendromans sehr unterhaltsam zu lesen; allein die Grundidee mit dem umgestülpten Land und die überzeichneten Charaktere sorgen für einen sehr heiteren Charakter des Buches. Da verzeihe ich auch gerne, dass sich Dath um ein vernünftiges Ende herumgestohlen hat und sich hinter all der phantastischen Kunstsprache doch nur die vom Autor bekannten plakativen Aussagen verstecken.
