---
title: "Linkschleuder"
date: "2009-10-29T22:29:11"
categories: [gefunden]
---

Eigentlich wollte ich selber einen Artikel schreiben über die Anmaßung unseres neuen Außenministers Westerwelle, der alle diejenigen hirnverbrannt nannte, die hinter den Placebo-Geschenken im Koalitionsvertrag auch die mit der geplanten Einführung der Kopfpauschale weiter voranschreitende Umverteilung von unten nach oben erkennen. Aber dies hat jemand anderes schon getan, also verweise ich auf [dessen Blog](http://www.24stunden.de/index.php/2009-10/gestatten-hirnverbrannt/).

Am nächsten Dienstag startet endlich die vierte Staffel der grandiosen Serie *Stromberg*, und als kleinen Werbegag hat ProSieben eine Homepage für das fiktive Dorf [Finsdorf](http://www.finsdorf.de/) erstellt, die ausschließlich aus Webdesign-Sünden aus der Anfangszeit des Internet zu bestehen scheint: Viele blinkende Icons, extreme Farb- und Schriftartenkontraste, eine nervende Hintergrundmusik, ein Gästebuch (durfte ebenso wie der Besucherzähler auf keiner Seite fehlen) und eine selten langweilige Webcam. Sogar ein eigenes Wappen mit Atomkraftwerk hat man entworfen - als grausige Vorlage hat wohl [Friesdorf](http://www.friesdorf.de) gedient. Eine sehr gelunge Aktion, wie ich finde, die meine Vorfreude auf die neue Staffel noch weiter erhöht.
