---
title: "Biutiful"
date: "2011-06-08T23:05:30"
categories: [gesehen]
---

*Mexiko/Spanien (2010)
Regie: Alejandro González Iñárritu
Darsteller: Javier Bardem (Uxbal), Maricel Álvarez (Marambra), Eduard Fernández (Tito, Uxbals Bruder), Hanaa Bouchaib & Guillermo Estrella (Uxbals Kinder), Cheikh Ndiaye (Ekweme), Diaryatou Daff (Ige, Ekwemes Frau) und andere mehr oder weniger schöne Menschen*
[Offizielle Homepage](http://www.biutiful-derfilm.de/)

Uxbal ist ein Kleinkrimineller in Barcelona, der auf der einen Seite sich illegal aufhaltende Senegalesen mit Plagiaten für den Verkauf auf der Straße versorgt und gleichzeitig asiatische Einwanderer schwarz an Bauunternehmer und andere Geschäftspartner vermittelt. Parallel verdient er sich noch ein Zubrot, indem er den Seelen Verstorbener beim Abschied von ihrem irdischen Daseins hilft. Seinen beiden Kindern will er damit eine bessere Kindheit verschaffen, als er selber sie hatte, denn die Mutter Marambra kann aufgrund ihrer bipolaren Störung nicht für sie sorgen.

Doch dann erfährt Uxbal, dass er an Krebs erkrankt ist und nur noch zwei Monate zu leben hat. Verzweifelt versucht er, sein Leben zu ordnen, damit vor allem seine Kinder behütet aufwachsen. Doch die Versuche, wieder mit Marambra zusammen wie eine Familie zu leben, scheitern letztendlich ebenso wie seine Bemühungen, den asiatischen Hilfskräften ein besseres Leben zu ermöglichen...

Uxbal ist wohl die zerissenste Gestalt, die ich seit langem im Kino gesehen habe. Es gibt so viele verschiedene Seiten an diesem Charakter, dass es schon einen Javier Bardem benötigt, diesen auch glaubhaft auf die Leinwand zu bringen. Vor allem die an *Sixth Sense* erinnernden Szenen, bei denen Uxbal die Verstorbenen sieht, wollen anfangs gar nicht zu der ansonsten dreckig-düster-realistischen Darstellung des sozialen Milieus passen, in welchem sich die Figuren bewegen. Denn wenn *Biutiful* in einem wirklich konsequent ist, dann in der Abbildung der hässlichen Seiten sowohl Barcelonas als auch der Charaktere.

Hübsch ist hier nicht einmal die [Ramblas](http://de.wikipedia.org/wiki/Ramblas), geschweige denn die Unterkünfte, in denen die Senegalesen und Asiaten hausen müssen - sogar das im Filmtitel verwendete Wort wird von Uxbals Tochter falsch geschrieben. Uxbals Wohnung findet ebenso nur in dunklen Ansichten statt, allein die Wohnung Marambras lässt mit ihrer zusammengewürfelten Buntheit zwischendurch etwas Farbe aufblitzen. Dies fällt passend in die Phase des Films, in der Uxbal eine rosige Zukunft für seine Familie am Horizont zu sehen glaubt.

Doch alle Planungen, alle gute Vorsätze und alle Versuche, das Leben in etwas Schönes zu verwandeln, werden sich am Ende gegen den tragischen Helden wenden. Dabei wird die Handlung für Regisseur Iñárritu ungewohnt kontinuierlich erzählt, wodurch der Fokus stärker auf den Charakteren liegt. Nur die letzte Szene, der Tod von Uxbal, ist gleichzeitig die erste Szene des Films und legt sich damit wie ein Band um das Zwischenhoch der Handlung. Der strahlend helle Winterwald und der Tonfall, mit dem der sichtbar glückliche Uxbal mit seinem Vater redet, lässt das deprimierende Ende in einem positiveren Licht erscheinen und damit ausgerechnet den wohl schlimmsten Moment Uxbals, nämlichen seinen Tod ohne alles ins Reine gebracht zu haben, so schön wirken.

Fazit: *Biutiful* ist eine zeitweise bittere Charakterstudie, die bewusst mit dem Filmtitel "Schönheit" spielt und dessen Bedeutung bis ins Deprimierende verdreht. Ein Javier Bardem im Topform verleiht dem Drama jedoch die nötigen Erdung, um sowohl die übersinnlichen Aspekte als auch das verwirrende Ende zu einem funktionierenden Ganzen verschmelzen zu lassen.
