---
title: "Niagara Falls"
date: "2012-05-21T23:04:25"
categories: [gewesen]
---

Schon aufgrund ihrer Größe sind die USA an Naturwundern reich gesegnet. Eines davon sind die Niagara-Fälle, die sich die Amerikaner jedoch mit den Kanadiern teilen müssen. Der Hufeisenfall genannte Teil liegt genau auf der Grenze zwischen den beiden Staaten; der Amerikanische Fall befindet sich ganz auf amerikanischem Staatsgebiet. Als Ausgleich für diese Verteilung haben die Kanadier den besseren Blick auf die Fälle.

Der die Fälle speisende Niagarafluss, die Verbindung zwischen dem Erie- und Ontariosee, bildet die Staatsgrenze zwischen Kanada und den USA. Auf beiden Seiten des Flusses liegt jeweils eine Stadt namens Niagara Falls, doch trotz dieser direkten Nachbarschaft könnten die Städte verschiedener nicht sein. Niagara Falls, New York, ist eigentlich nur der von Industrie geprägte Vorort von Buffalo, der zudem von einem Kongresszentrum mit angeschlossenen Hotels lebt. Alles in allem ist dies eine recht leb- und trostlose Stadt, vor allem wenn die kanadische Seite als Vergleich herangezogen wird. Denn diese ist ein einziger bunter Vergnügungspark, in welchem der Tourismus ins gnadenlose Extrem getrieben wird.

Hotels, Casinos, Restaurants, Aussichtstürme und ein Riesenrad buhlen um den besten Ausblick auf die Fälle. In der Nähe der Uferpromenade drängt sich ein Geschäft an das nächste und alle wetteifern mit bunter Leuchtreklame und einer unglaublichen Lautstärke um die vorbeilaufenden Touristen. Für meinen Geschmack hat das kanadische Niagara Falls zu viel von dem, was der amerikanischen Seite fehlt. Aber schon der Aussicht wegen sollte der Weg über die Grenzbrücke angetreten werden. Die Kanadier heißen jeden Besucher willkommen, während die Amerikaner auf dem Rückweg sowohl eine Gebühr verlangen als auch ihre üblichen Fragespielchen an den Einreisenden durchexerzieren, die teilweise wie ich gerade ein paar Stunden vorher die USA auf dem selben Wege verlassen hatten.

Doch zurück zu der eigentlichen Attraktion, den Fällen. Durch den Fluss [fließen pro Sekunde gigantische 2400m³](http://en.wikipedia.org/wiki/List_of_waterfalls_by_flow_rate), die an den Niagarafällen bis zu 50m in die Tiefe stürzen und dabei eine riesige Gischtwolke erzeugen, die schon aus großer Entfernung zu sehen ist. Neben den Fällen zu stehen und diese unvorstellbaren Mengen Wasser in Greifweite an sich vorbeirauschen zu sehen ist einfach unglaublich. Die beste Möglichkeit bietet sich dazu auf Goat Island im [Niagara Falls State Park](http://www.niagarafallsstatepark.com/map.html) auf amerikanischer Seite; der Observation Tower kann dabei ruhigen Gewissens rechts liegen gelassen werden.

Noch direktere Erfahrung mit den Wassermassen können Touristen machen, wenn sie mit Booten bis an den Fuß des Hufeisenfalls fahren oder Wanderungen in den Höhlen hinter und unter den Fällen unternehmen, was sowohl von amerikanischer als auch kanadischer Seite aus möglich ist. Mir waren diese Exkursionen aber deutlich zu nass, also habe ich mir das Schauspiel nur von oben angeschaut, was beeindruckend genug war.

Nachts und in touristenarmen Zeiten wird der Großteil des Wassers aus dem Niagarafluss durch ein Wasserkraftwerk umgeleitet, wodurch die Fälle etwas an Imposanz verlieren, jedoch zu einer umweltfreundlichen Energieversorgung beitragen. Dies wird durch eine von kanadischer Seite ausgehende Beleuchtung der Fälle ausgeglichen, die sehr schöne Farbspiele auf dem tosenden Wasser erzeugt.

Zu guter Letzt noch ein Tipp für alle Autoreisenden auf dem Weg von den Niagarafällen zur Ostküste: Albany ist keinen Stopp wert!

[gallery link="file"]
