---
title: "1Q84"
date: "2011-02-04T23:39:43"
categories: [gelesen]
---

*von Haruki Murakami,
erschienen bei Dumont, ISBN 978-3-832-19587-8, 32,00€*

Hätte ich mich vorher etwas mehr über das Buch informiert, dann hätte ich wohl mitbekommen, dass die deutsche Veröffentlichung nur die Bücher 1 & 2 des Gesamtwerkes *1Q84* enthält. Das dritte Buch soll hierzulande erst Ende des Jahres als eigener Band erscheinen - darauf hingewiesen werden die Leser im Buch selber aber nicht. Dabei mag ich es gar nicht, mit einem Cliffhanger zurückgelassen zu werden und darauf warten zu müssen, die Auflösung zu erfahren. Doch zum Glück ist das Ende weit weniger offen, als ich es befürchtet habe. Viele Handlungsstränge werden sogar zu einem befriedigenden Ende gebracht, so dass *1Q84* durchaus auch für sich allein stehen kann.

Es geht darin um Aomane und Tengo, die als Kinder kurzzeitig dieselbe Schule besucht haben und einen gemeinsamen Moment teilen, der beide noch 20 Jahre später beschäftigt. Aomane ist inzwischen eine erfolgreiche Profikillerin, die mit einem Eispick Männer umbringt, die sich an Frauen vergangen haben. Tengo dagegen ist Mathematik-Lehrer und Nachwuchsautor, der noch kein eigenes Buch veröffentlicht hat. Sein Verleger bringt ihn deshalb dazu, das Buch eines jungen Mädchen zu überarbeiten, um dessen Chancen auf einen Nachwuchspreis zu erhöhen.

Doch schnell stellt sich heraus, dass die Fantasien des Mädchens über die *Little People* genannte Wesen, die eine Sekte manipulieren, einen wahren Kern besitzen, und Tengo sich mit seiner Beteiligung an der Veröffentlichung des Buches gefährliche Feinde gemacht hat. Ebenso wie Aomane, die als letzten Auftrag den *Leader* genannten Anführer der Sekte töten soll. Und beide müssen erstaunt feststellen, dass sich die Welt um sie herum verändert, als neben dem bekannten Mond ein zweiter Erdtrabant am Himmel erscheint.

Mehr will ich gar nicht verraten über die verschlungene Handlung von *1Q84*. Den Namen hat das Buch übrigens von seiner Protagonistin, die ihrer veränderten Welt diese Bezeichnung gibt (Q und 9 haben dieselbe Lautschrift im Japanischen, und die Handlung spielt 1984), um sie vom Original mit nur einem Mond zu unterscheiden, an die scheinbar nur sie sich erinnern kann. Diese leicht mystische Parallelwelt hat aber nur wenige Auswirkungen in der Handlung, bis auf wenige Ereignisse in der nahen Vergangenheit und den zweiten Mond scheint sie sich nicht großartig von der uns bekannten Erde zu unterscheiden.

Vielmehr ist sie ein Ausdruck des Einflusses der ebenso mystischen *Little People*. Diese aus einer noch anderen Welt stammenden Wesen können ihre Größe und Anzahl verändern und sind in der Lage, eine Puppe aus Luft zu spinnen, aus der danach Doppelgänger von Menschen schlüpfen. Warum sie dies machen bleibt Protagonisten wie Lesern im Unklaren, doch ihr Einfluss auf Gesellschaft wie Welt scheint groß zu sein.

*1Q84* lebt von dieser Ungewissheit nicht zu wissen, was da eigentlich vorgeht. Zwischenzeitlich habe ich die verschiedensten Theorien entsonnen und verworfen, wie das Gelesene zu interpretieren ist. Schreibt Tengo nun ein Buch im Buch und Aomane ist nur eine Figur darin, oder geht es hier um die große Frage der Moral und wird der Profikillerin mit der Parallelwelt ein Spiegel vorgehalten, dass ihre geordnete Welt und die gewählten Gründe für ihr Profession gar nicht so real sind, wie sie es gerne hätte?

Vordergründig spielt sich natürlich die Liebesgeschichte ab, die unerfüllten Sehnsüchte von Tengo und Aomane nacheinander. Beide leben ein typisches Großstadt-Single-Leben und wissen doch, dass es da mehr gibt. Sie wissen sogar sehr genau, wie dieses Mehr aussieht, und doch hat noch keiner von beiden versucht, den jeweils Anderen zu finden. Fast könnte man meinen, dass all die seltsam märchenhaften Ereignisse um die *Little People* nur passieren müssen, damit sich Aomane und Tengo finden. 

Haruki Murakami erzählt dies in einem strengen Wechsel zwischen Kapiteln, die Aomanes Handlung vorantreiben, und Abschnitten, in denen der Leser Tengo folgt. Durch diese doppelte, aber ähnliche Perspektive wiederholen sich viele Details, wie zum Beispiel die Entstehungsgeschichte der Sekte, und wirken so als Bestätigung der Information. Doch gerade, als ich dachte, dies alles schon einmal gelesen zu haben, fanden sich plötzlich störende Details, die sich zum Fremdkörper im bisher vermittelten Bild entwickeln und deshalb Zweifel aufkommen lassen, ob das Gelesene richtig eingeordnet wurde.

Viele weitere Themen des Buches drehen sich in konzentrischen Kreisen um Handlung wie Akteure. So wächst kein Kind glücklich bei seinen Eltern auf; vielmehr haben alle Charaktere starke Einschnitte in ihrer Kindheit hinter sich. Aomane flüchtete vor den Zwängen der Zeugen Jehovas, denen ihre Eltern angehörten, und hat diese seitdem nicht mehr wiedergesehen. Tengo lief vor seinem Vater weg, da dieser ihm eine Kindheit verwehrte, und die Kinder der Sekte scheinen missbraucht zu werden und deshalb weg zu rennen. Doch die eingeschränkte Sichtweisen, in denen diese Episoden erzählt werden, lassen vermuten, dass die Erinnerungen der Personen zumindest unvollständig sind. Gerade die Wahrnehmung von Kindern ist oft extrem eingeschränkt und subjektiv, und oft genug lässt Murakami dies den Leser spüren.

*1Q84* ist also eine Art Parabel über Perspektiven und Sichtweisen auf unsere Welt. Es gibt viel Böses in der geschilderten Parallelwelt, aber eigentlich unterscheidet sie sich gar nicht großartig von unserer gewohnten Welt, wenn man sie von allen Seiten betrachtet. Mit dem zweiten Mond scheint den Figuren daher ein zweites Auge geöffnet worden zu sein, mit dem sie zwar mehr Greuel und Probleme unserer Gesellschaft erkennen, aber andererseits auch neue Perspektiven gewinnen und vor allem sich gegenseitig endlich wahrnehmen. Ich bin wirklich gespannt, welche Richtung der dritte Teil des Romans schließlich einschlagen wird - genug offene Fragen habe ich auf jeden Fall. Nur ob sie mir beantwortet werden, steht auf einem ganz anderen Blatt.
