---
title: "The Elder Scrolls V Skyrim – Mein Tagebuch, Teil 2"
date: "2012-01-22T15:30:57"
categories: [gespielt]
---

Ich habe jetzt knapp 27 Stunden *Skyrim* gezockt - da gelangen andere Spiele langsam an ihr Ende - und bin auf Level 17 noch weit davon entfernt, die Hauptquest abzuschließen. Zeit also, über die Spielerfahrung dieser ersten Stunden zu schreiben.

Der Einstieg in das Spiel war nicht optimal. Erst bestätigte das Intro alle meine Befürchtungen in Sachen Kollisionsabfrage, dann begann der spielbare Teil der Einführung mit einer hektischen Flucht vor einem Drachen, bei der ich oft nicht wusste, wem ich wohin folgen muss. Nach einer Stunde Kraxeln durch eine Höhle entließ mich das Spiel endlich in die Freiheit, und von da an ging es bergauf mit der Motivation.

Denn die Freiheit, im Rahmen der Spielgrenzen tun und lassen zu können, was der Spieler möchte, ist die große Stärke von *Skyrim*. Nach dem Tutorial kann zum Beispiel die Hauptquest komplett vernachlässigt werden; das Questbuch füllt sich auch so fast von alleine. In vielen Siedlungen gibt es ein Gasthaus, in welchem die Wirte und Gäste nur zu gern vorbeikommenden Abenteurern Aufträge ans Bein binden. So erfährt der Spieler von noch nicht besuchten Orten in Himmelsrand, die dann auf der Karte mit ihrer Position vermerkt werden. Wurde ein Ort bereits besucht, ermöglicht das Schnellreisesystem, direkt dorthin zu springen.

Orte können zudem einfach entdeckt werden, indem der Spieler Straßen oder Anzeigen im Kompass folgt. Es gibt unglaublich viel zu entdecken in der großen, offenen Welt von *Skyrim*; allein die Anzahl der Dungeons (meist alte Gräber, aber auch unterirdische Wälder) liegt im dreistelligen Bereich. Bereits abgeschlossene Dungeons werden auf der Karte speziell markiert, damit der Spieler bei der großen Menge nicht die Übersicht verliert. Die Karte selber ist ganz nett gestaltet, weil sie die gesamte Welt als 3D-Modell darstellt - allerdings würde ich mir wünschen, dass ich weiter hineinzoomen könnte oder Wege eingeblendet werden. So sind nur die ungefähren Abstände der Orte ablesbar und etwaige dazwischenliegende Hindernisse. Zudem nerven die darüber ziehenden Wolken, die oftmals nicht erkennen lassen, wie die Küstelinie verläuft oder sich Inseln im Sumpf verteilen und damit einen klaren Mehrwert vereiteln.

Im Gegensatz zur Karte ist das Inventar nüchterner geworden (dies scheint allerdings gerade Mode zu sein, wenn ich [DA2](http://ps3.ign.com/dor/objects/80341/dragon-age-ii/images/dragon-age-2-20110112105203881.html?page=mediaimgviewer) oder [The Witcher 2](http://hexer.wikia.com/wiki/The_Witcher_2_Inventar) zum Vergleich heranziehe). Es besteht nur noch aus Listen, wobei das ausgewählte Item in der rechten Bildschirmhälfte angezeigt wird. Eine Übersicht, was der eigene Charakter gerade ausgerüstet hat, gibt es nicht. Eine Statuszeile am unteren Bildschirmrand informiert über den aktuellen Rüstungs- und Angriffswert und bei der Auswahl neuer Items wird in rot oder grün angezeigt, wie sich diese Werte bei der Auswahl ändern würden.

Um nicht die immer länger werdenden Listen komplett durchscrollen zu müssen, gibt es eine Favoritenliste, deren Inhalt der Spieler frei bestimmen kann. Diese kann während eines Kampfes aufgerufen werden und hält dabei die Zeit an. So kostet das Umrüsten des Charakters oder das Trinken eines Tranks keine Zeit. Realistischer geht es bei der Größe des Inventars zu. Der Charakter kann nur ein begrenztes Gewicht tragen (dies hängt von der Ausdauer ab, lässt sich aber nur in engem Rahmen ausbauen) und so steht der Spieler ständig vor der schwierigen Wahl, welches kostbare Item er im Dungeon liegen lassen muss - ich mit meinem Sammeltrieb kann so etwas gar nicht leiden. Aber zum Glück ist der Spieler in *Skyrim* selten ohne Begleiter unterwegs, und diese können als Packesel missbraucht werden. Später im Spiel lohnt es sich, ein Haus zu kaufen, um schwere Gegenstände wie die Drachenknochen zwischen zu lagern, die mit entsprechender Skillausbaustufe zu mächtigen Rüstungen verarbeitet werden können.

Und da bin ich auch schon bei der Charakterentwicklung, die in Skyrim etwas anders abläuft als in [vergleichbaren](/blog/2011/01/29/two-worlds-ii/) [Spielen](/blog/2010/10/24/risen/). Der Charakter bekommt keine Erfahrungspunkte für besiegte Gegner oder abgeschlossene Quests, sondern erhält Erfahrung in einer von 18 Fertigkeiten, indem er diese ausführt. D.h. wenn der Charakter mit Einhand-Waffen kämpft, dann steigert er auch diese Fertigkeit mit jedem erfolgreichen Schlag - und nicht nur, wenn der Gegner dabei besiegt wird. Jede Fertigkeit kann so individuell um 100 Stufen gesteigert werden.

Über alle Fertigkeiten hinweg hat der Charakter eine Gesamtstufe, die sich abhängig von den Fertigkeitenstufen erhöht. Bei so einem Stufenaufstieg darf der Spieler einen von nur drei Grundwerten des Charakters verbessern (Magicka, Gesundheit, Ausdauer) und einen Talentepunkt vergeben. Talente sind Spezialfähigkeiten in den Fertigkeiten, die zum Beispiel den Schaden von Einhandwaffen um 20% steigern. Sie bilden pro Fertigkeit einen Talentebaum und hängen von der Stufe der Fertigkeit ab.

Wie oben schon beschrieben ist mein Charakter gerade einmal auf Gesamtstufe 17. Gefühlt dauert es inzwischen eine halbe Ewigkeit, meine benutzten Fertigkeiten (Einhandwaffen, Blocken, Schwere Rüstung) so stark zu steigern, dass ein Gesamtstufenaufstieg dafür herausspringt, so dass ich momentan mit Nebenperks wie Schmieden und Alchemie experimentiere, um die Talentepunkte für meine Hauptfertigkeiten zu erhalten.

Dabei bin ich auf eine Inkonsequenz in den Auswirkungen der Talente auf das Inventar gestoßen. Verbesserungen der Effekte von Waffen oder Rüstungen verändern die angezeigten Werte derselben. D.h. wenn ein Schwert 10 Punkte Schaden im Inventar anzeigte und ich das Talent der 20%igen Steigerung erlerne, dann ändert sich die Anzeige auf 12 Punkte Schaden. Änderungen der Redekunst haben jedoch keine vergleichbaren Auswirkungen. Mit dieser Fertigkeit senken sich die Einkaufs- und erhöhen sich die Verkaufspreise. Das Inventar zeigt jedoch immer denselben Preis an - und zwar einen, den man beim Händler nie erzielt.

Aber dies ist eines von wenigen kleinen Details, die beim Spielen so gut wie keine Auswirkungen zeigen. Viel stärker faszinieren mich bisher die riesige Welt und die vielen kleinen Quests, die mich ständig von der eigentlichen Geschichte ablenken. Denn obwohl die Kämpfe gegen die Drachen das Adrenalin zum Kochen bringen, habe ich inzwischen genug davon (alleine bin ich noch chancenlos gegen die Lindwürmer) und auch der Hintergrundquest um den Kampf der Kaiserlichen gegen die Rebellen der Sturmmäntel gehe ich bewusst aus dem Weg. Mein nächstes Ziel ist es, ein paar mehr Gilden beizutreten (bisher bin ich nur ein Gefährte) und meine Fertigkeiten endlich auf ein konkurrenzfähiges Niveau zu bringen - dazu später mehr.
