---
title: "Ja ist denn heut' schon Weihnachten?"
date: "2005-12-05T16:23:12"
categories: [getan]
---

Der alte 15" Monitor meiner Eltern hat nach sieben Jahren endlich ausgedient und wird zu Weihnachten durch einen TFT (Samsung Syncmaster 730BF) ersetzt - ein Quantensprung in der Technik. Damit sind meine Eltern noch vor mir Besitzer eines Flachbildschirms. Dieser Umstand kratzt schon ein wenig am Selbstbewusstsein, da sie ansonsten die ausrangierten Teile meines PCs weiter nutzen. Ich habe aber anno 2000 mit dem 17" Belinea 103040 auf Qualität gesetzt, wodurch sich die Anschaffung eines TFTs auf den Zeitpunkt verschiebt, an dem die Röhre erste Macken zeigt (momentan nicht absehbar).

Heute kam das gute Stück nun per UPS an der Haustür an und musste natürlich sofort ausprobiert werden, bevor er bis Weihnachten wieder weggeschlossen wird. Die Installation verlief problemlos; nach dem Versetzen eines Hakens im NVIDA-Treiber ließen sich auch Spiele starten. Der erste Eindruck ist äußerst positiv: Neben der tollen Schärfe weiß auch die Darstellung von Spielen (wegen der hohen nativen Auflösung von 1280 x 1024 meist mit Interpolation) und Filmen (getestet an Tomb Raider II in HD) zu gefallen. Eine nette Funktion im On Screen Menu lässt die Farben stärker strahlen und wird wohl bei der Präsentation von digitalen Fotos Anwendung finden. Einen schwarzen Pixelfehler habe ich leider auch gefunden, aber damit muss man in der Pixelfehlerklasse II leben (und in der linken oberen Ecke fällt er auch nur auf, wenn man danach sucht).

Nach der Einrichtung fiel jedoch die Rückkehr zu meiner Röhre sehr schwer. Zu klein erscheint auf einmal das sichtbare Display, zu unscharf die Darstellung von Schriften. Und plötzlich fällt mir auch wieder die leichte Wölbung der Oberfläche auf...
