---
title: "Pushing Daisies"
date: "2008-10-22T21:43:09"
categories: [gesehen]
---

Willkommen in der Fernsehserien-Bäckerei: Man nehme einen Esslöffel voll mit schwarzem, aber liebevollen Humor wie bei [Big Fish](/blog/2004/04/17/big-fish/) oder [Amélie](/blog/2001/10/01/die-fabelhafte-welt-der-amelie/), verpacke dies in ebenso bunten Bildern und gebe schlussendlich die aktuelle Geheimzutat des amerikanischen Fernsehens dazu: Den Tod mit einer Prise Fantasy. Heraus kommt dann eine Serie wie *Pushing Daisies*, die seit heute ProSieben dem deutschen Fernsehvolk zu verkaufen versucht.

Darin geht es um den jungen Kuchenbäcker Ned, der mit einer Berührung tote Menschen wieder zum Leben erwecken kann. Mit einer zweiten Berührung ist es dann jedoch endgültig aus mit dem Leben, und wenn diese zweite Berührung nicht innerhalb einer Minute passiert, muss jemand anderes sterben. Aus dieser Fähigkeit hat der Privatdetektiv Emerson Cod eine Geschäftsidee entwickelt, indem er Ned die Opfer von Verbrechen nach ihren Mördern befragen lässt. Die obligatorische Frauenrolle ist die Sandkastenfreundin von Ned, Chuck, die schon einmal tot war, wiedererweckt wurde und deshalb Ned nicht mehr berühren darf, obwohl sich zwischen den beiden eine Liebesbeziehung anbahnt. Zu dritt versuchen sie nun, ihren Lebensunterhalt mit der Lösung von Mordfällen zu verdienen.

Die erste Episode nach diesem Schema war auf jeden Fall lustig, aber irgendwie auch glattpoliert - optisch wie inhaltlich. Die Figuren hatten noch keinen Raum, an Kontur zu gewinnen, dafür gab es genügend skurile Nebenrollen. An [Death like me](http://www.deadlikemedvd.com/) (momentan immer Samstag nachmittags auf RTL2), dem Vorgängerprojekt von Autor Bryan Fuller, reicht das noch nicht heran. Dort kann ich mit den Charakteren deutlich mehr anfangen und nicht alles ist mit einer dicken Schicht Zuckerguss überzogen. Aber was nicht ist kann ja noch werden - ich gebe der Serie ein paar Episoden Zeit, sich zu entwickeln, und werde dann wieder einen Blick wagen. So viele gute Sendungen kennt das deutsche Fernsehen ja leider nicht.
