---
title: "Der Reiher ist gelandet"
date: "2008-04-26T20:27:32"
categories: [getan]
---

Pünktlich nach sechs Monaten ist das neue Ubuntu veröffentlicht wurden, welches den Namen *Hardy Heron* (zäher Reiher) trägt. Und diesmal gab es überraschenderweise gar keine Probleme beim Upgrade: Die Option erschien automatisch im Update-Manager, das Repository hatte keine Performance-Probleme und seit dem Aktivieren der neuen Version läuft mein System stabiler als je zuvor. Keine PCI-Probleme beim Start, keine DBus-Fehler beim Herunterfahren. Mit dem neuen ACPI-Modul `asus_laptop` (ersetzt `asus_acpi`) funktioniert sogar das Einstellen der Display-Helligkeit über die Funktionstasten in beide Richtungen.

Ansonsten sind hauptsächlich kleinere Updates in diese Version mit Long time support geflossen: [Neuerer Kernel, neueres Gnome, aktuelles XOrg, aktuelles OpenOffice](http://wiki.ubuntuusers.de/Hardy_Heron) und überraschend Firefox 3.0b5. Eine Betaversion in einem Linux für den Produktiveinsatz hätte ich nicht erwartet (Version 2 ist aber parallel installiert). Das immer noch fehlende Eclipse-Update auf die Europa-Version 3.3 scheint dagegen ein Debian-Politikum zu sein; zum Glück reicht ein Download mit anschließendem Entpacken (leider auf der Kommandozeile, das Entpackwerkzeug von Ubuntu weigerte sich), damit die aktuellste Version auch ohne Repository läuft.

Ich bin also nach wie vor sehr zufrieden mit dieser Distribution und werde mich als Nächstes einmal an einer 64Bit-Parallel-Installation wagen, selbst wenn ich noch keinen Usecase dafür habe.
