---
title: "Start von DVB-T in Mitteldeutschland"
date: "2005-12-05T10:09:18"
categories: [gefunden]
---

Seit heute hat auch in meiner Heimat ["die Zukunft des Fernsehens"](http://www.dvbt-mitteldeutschland.de/) begonnen. Damit auch jeder Hallenser die neuen analog-digitalen Signale empfangen kann, wurde eine neue, wunderschöne [Antenne](http://www.dvbt-mitteldeutschland.de/Projektchronik/pics/gross/Antennenmontage_Halle.jpg) errichtet (Halles zweithöchstes Bauwerk nach dem danebenliegenden Kraftwerksschornstein).

Einen ersten Eindruck konnte man bereits vor dem offiziellen Startschuss in den einschlägigen Elektronik-Fachmärkten gewinnen, wo der Testbetrieb zu Vorführungszwecken genutzt wurde. Ganz überzeugen konnte mich das Bild dort aber nicht; zu viele Blockartefakte störten den Bildgenuss. Ob dies nun am Testbetrieb lag oder am [Multiplexing](http://www.heise.de/ct/05/03/190/), am verwendeten Receiver oder gar an dem angeschlossenen LCD-TV, kann ich nicht beurteilen.

Allenfalls befriedigend fällt aber das Programmangebot aus. Die Privatsender haben sich aus Gründen der "mangelnden Zukunftsfähigkeit und Unwirtschaftlichkeit" gegen eine Einspeisung ihrer Programme ausgesprochen, so dass heute zum Start nur elf öffentlich-rechtliche Sender plus ein Datenkanal (MHP) zu empfangen sind.

Damit ist DVB-T in Mitteldeutschland noch viel weniger eine Konkurrenz für Satelliten- und Kabelnetz-Nutzer als in anderen Gebieten Deutschlands, wo das Digital-TV schon auf Sendung ist. Aufgrund der sehr guten Qualität meines Kabelanschlusses und dem breiten Programmangebot wird also ein Wechsel für mich so schnell nicht in Frage kommen.
