---
title: "Shortcut to Hollywood"
date: "2009-02-14T18:47:44"
categories: [gesehen]
---

*Deutschland (2009)
Regie: Jan Henrik Stahlberg und Marcus Mittermeier
Darsteller: Jan Henrik Stahlberg (John Frederik Selinger), Marcus Mittermeier (Matt Welby), Christoph Kottenkamp (Chrismon), 	Marta McGonagle (Shannon) und andere Pseudo-Berühmtheiten*
[Offizielle Homepage](http://www.short-cut-to-hollywood.de/)

Da ist er also, der lang erwartete neue Film des *Muxmäuschenstill*-Teams. Am 8.2. schon auf der Berlinale gelaufen, habe ich die zweite Aufführung im Zoopalast gesehen, bei der fast die gesamte Filmcrew anwesend war und sich am Ende auf der Bühne feiern ließ. Der offizielle Starttermin 2.7. liegt noch weit in der Zukunft; in Berlin zu wohnen hat manchmal echte Vorteile.

Der Film handelt von drei Versagern, die zusammen eine erfolglose Band bilden. Doch sie wissen: Damit es mit dem Ruhm noch klappt, muss man den Medien extreme Unterhaltung bieten. Und so fliegen sie nach Amerika, um dort ihr Konzept eines modernen Popstars zu verkaufen: John Frederik Selinger lässt sich dabei filmen, wie er von Chrismon zuksessive verstümmelt wird und kündigt damit seinen nahen Tod an. Ein Fernsehsender springt schließlich an, vermarktet die Idee und macht eine große TV-Show daraus. Doch mit dem schnellen Ruhm kommen auch die Gewissensbisse: War das kurz bevorstehende Lebensende noch so gut überlegt, ergeben sich plötzlich Gründe für das Weiterleben. Und auch die Freunde wissen nicht mehr, ob sie das richtige tun und die fünfzehn Minuten Ruhm dies wert sind...

*Shortcut to Hollywood* ist ein weiterer Vertreter der Gattung pseudodokumentarische Mediensatire. Die Kamera steht teilweise außerhalb des Geschehens und nimmt die anderen Kameras auf, teilweise nimmt sie auch deren Perspektive ein und wird Teil der gezeigten Medienwelt. Immer wieder werden TV-Einblendungen eingeschnitten und die Handlung geht an einer Stelle sogar übergangslos in Werbung über.

So weit nichts Neues in Sachen Kritik an zeitgenössischen Fernsehproduktionen, auch an Grenzübertretungen hat es schon weitaus extremere Beispiele gegeben. Was den Film aus der Masse heraushebt ist jedoch sein Soundtrack. Denn Jan Henrik Stahlberg hat ein halbes Dutzend trashige Lieder in Floskel-Englisch geschrieben, die seine Band schließlich zu einem Mega-Abschluss-Konzert führen (bei denen man sich das Publikum der *Ärzte* "ausgeliehen" hat). Diese Songs tragen viel zum Humor des Films bei, ebenso wie der übertriebene Amerikanismus und das ständige, deplatziert erscheinende Trinken von Köstritzer Schwarzbier - normale Schleichwerbung würde gar nicht so stark auffallen.

Generell kokettiert der Film über die gesamte Laufzeit mit dem schlechten Englisch von John Frederik Selinger, das seinem Ruhm in den USA aber keinen Abbruch tut. Bei der ersten Operation wird dazu passend ein Dieter-Bohlen-Hit gezeigt und die Aussage ist klar: Ohne den Hype durch die allgegenwärtige Medienmaschine würde niemand diese künstlich erzeugte Aufmerksamkeitsblase auch nur wahrnehmen. Doch die Produzenten kommen so in die Verlegenheit, ständig für Nachschub zu sorgen, und suchen nicht selten am unteren Ende der Geschmacksskala nach den neuen Stars. Und da es mittlerweile eine Generation von Zuschauern gibt, die in dieser Medienwelt aufgewachsen sind, finden sich darunter auch immer Freiwillige mit der Bereitschaft, die Interessen der Produzenten zu befriedigen um das ihnen aufgezeigte Ideal des Ruhmes zu erreichen. Der Konsument füttert sich quasi selber, und durch die jahrelange Konditionierung ist John Frederik Selinger auch noch zufrieden damit und stellt dieses Leitbild sogar über die Freundschaft.

Fazit: *Shortcut to Hollywood* ist eine böse Abrechnung mit dem niveauarmen Fernsehen unserer Zeit. Ob es Schleichwerbung, Amerikanismus oder die Senkung von Hemmschwellen ist, durch die ständige Übertreibung wird dem Zuschauer bewusst gemacht, wie der Fernseher seine Zuschauer manipuliert. Zusammen mit dem trashigen Soundtrack macht dies eine unterhaltsame Satire, der es zwar etwas an Innovationen fehlt, die dies aber mit viel absurden Humor wieder wett macht.
