---
title: "Künstliche Verknappung"
date: "2005-11-06T16:34:07"
categories: [gedacht,gewesen]
---

~~Der Saalepark~~ Nova eventis im Günthersdorf wird gerade mit großem Aufwand von Grund auf neu gestaltet. Dies wurde nötig, da die Innenstädte von Halle und Leipzig wieder mehr Kunden mit neuen Konzepten und Warenhäusern anlockten und diese damit auf der grünen Wiese ausblieben. Günthersdorf hält nun mit einem neuen Gestaltungskonzept dagegen: Helle Farbtöne, viel Licht und ein einheitliches, edles Ladendesign sollen die Kunden zum Konsumieren anregen. Um die Wege kurz zu halten entstand außerdem ein neues Parkhaus mit direktem Zugang zu den drei oval geformten Abschnitten, von denen mittlerweile zwei fertig gestellt sind.

So weit, so gut. Das Einkaufen macht auch wirklich Spaß und die Läden halten vom Angebot, was die Fassade verspricht. Doch leider musste sich in dem gerade neu eröffneten Fresstempel die Funktionalität der Optik unterordnen. So gibt es zwar ein großes Angebot von McDoof über Döner und Asiaten bis hin zu Griechen, aber die Läden sind jeweils nicht breiter als fünf Meter, so dass sich mittags die Warteschlangen der Hungrigen überlappen. Außerdem teilen sich alle Schnellrestaurants die Tische auf dieser von Durchbrüchen zum Erdgeschoss geprägten Ebene.

So kommt es, dass man als hungriger, müder Konsument vor der Essenswahl erst einmal einen Tisch suchen muss. An fast jeder Sitzgelegenheit stehen jedoch schon die potentiell nächsten Nutzer, und sobald ein Tisch frei wird beginnt die große Rennerei wie bei der "Reise nach Jerusalem". Dank der an dieser Stelle viel zu engen Gänge beginnt hier die natürliche Auslese unter den Homo Shopping: Nur wer schnell und clever genug ist kann sich durchsetzen und einen Tisch ergattern, und damit sein Überleben sichern. Die niedersten Instinkte des Menschen werden geweckt und der Sozialneid beginnt ("Kann der Opa da nicht schneller essen?", "Die sind doch schon fertig, worauf warten die noch?"). Am Ende habe ich die Geduld verloren und bei IKEA einen Hot Dog gegessen...

Das schwedische Möbelhaus ist beim Bau des eigenen Parkplatzes aber ebenfalls dem Konzept der künstlichen Verknappung gefolgt. Viel zu wenige Parkplätze und eine seltsame Zugangsstrategie (alle Autos müssen durch eine Zufahrt hindurch) fördern die regelmäßige Bildung von langen Auto-Warteschlangen, selbst wenn man nur auf einen der freien Plätze will, die mehr als 50m vom Ausgang entfernt sind.

Auch im IKEA-Markt selber gibt es den Konflikt zwischen dem geordnetem Leiten der Menschenmassen vorbei an allen Angeboten und dem großen samstäglichen Ansturm von Kaufwilligen, von denen gestern sicherlich mehr als 10% Schwangere waren. Nach einer halbstündigen Wartephase an der schnellsten Kasse im Markt (mit einer wirklich freundlichen Verkäuferin) war jedoch endlich der Bürostuhl "Allak" mein Eigentum. Im Katalog ist er zwar nicht mehr zu finden, aber ein Mitarbeiter des IKEA Service-Center hatte auf ein Mail-Anfrage meinerseits darauf hingewiesen, dass im Günthersdorfer Markt noch ausreichend Stückzahlen vorhanden sind. Jetzt muss das gute Stück nur noch bis Weihnachten auf seinen Aufbau warten und dann sind endlich alle Haltungsprobleme dahin (hoffe ich).
