---
title: "Slumdog Millionär"
date: "2009-03-30T22:45:16"
categories: [gesehen]
---

*USA/UK (2008)
Regie: Danny Boyle
Darsteller: Dev Patel, Ayush Mahesh Khedekar, Tanay Chheda (Jamal K. Malik), Azharuddin Mohammed Ismail, Madhur Mittal, Ashutosh Lobo Gajiwala (Salim), Freida Pinto, Rubiana Ali, Tanvi Ganesh Lonkar (Latika), Anil Kapoor (Quizmaster Prem Kumar), Irrfan Khan (Polizeiinspektor), Mahesh Manjrekar (Javed), Sanchita Choudhary (Jamals Mutter) und andere Slumdogs*
[Offizielle Homepage](http://www.slumdog-millionär.de/)

Jamal und Salim sind Kinder aus den Slums von Mumbai. Seit dem Tod ihrer Mutter bei Hindu-Islam-Unruhen versucht Salim als der Ältere der beiden Brüder, die Familie zu versorgen. Sie überleben, indem sie sich mit Betteln und kleinen Gaunereien über Wasser halten, u.a. als Dauerfahrgäste auf den Dächern eines Zuges und beim Ausnehmen von Touristen am Taj Mahal. Während sich Salim durch seine Härte und Führungsanspruch hervortut, will Jamal immer nur eins schaffen: Seine Liebe Latika wiederfinden, mit der er sich als kleines Kind eine sorgenfreie Zukunft erträumte...

Ich habe die ersten Danny-Boyle-Filme (*Kleine Morde unter Freunden*, *Trainspotting*, *Lebe lieber ungewöhnlich*, *The Beach*, *28 Days Later*) alle gesehen, bin zumindest immer gut unterhalten worden und so ließ ich mich dazu überreden, den Oscar-Abräumer dieses Jahres im Kino zu sehen, obwohl mich die Vorschau alles andere als ansprach. Schließlich versprach sie einen Bollywood-Film in Hollywood-Optik, und nichts nervt mich mehr als Feel-Good-Musicals.

Doch zumindest in dieser Hinsicht hat mich Danny Boyle "enttäuscht". Erst zum Abspann, nach Abschluss der Filmhandlung, zeigt er, dass er sich diesen Erwartungen bewusst war, sich ihnen aber verschlossen hat und bemüht das landläufige Bild, indem er eine Massen-Tanzeinlage zu indischer Musik inszeniert. Bis dahin aber überzeugte der Film mit einer flinken Handkamera, den immer wiederkehrenden "schiefen" Einstellungen und einem mitreißenden Soundtrack globaler Prägung. Dazu kommt das recht unverbrauchte Setting der Mumbaier Slums und der trotz der teilweise düsteren Elemente sehr unterhaltsamen Handlung, die das Aufwachsen von Jamal in Episodenform zeigt.

Man sieht die Probleme und die Entwicklung in den Slums und zum Glück saß ich zwischen zwei Freunden, die beide schon in Indien waren. Sonst hätte ich zum Beispiel nicht gewusst, dass ein leichtes Kopfschütteln in Indien ja bedeutet - der Film wirkt durch solchen Details auf jeden Fall authentisch. Aber auch ohne Indien-Vorkenntnisse gibt es genug globale, popkulturelle Referenzen (das fängt mit *Wer wird Millionär* an), um den Film zu verstehen und der Handlung zu folgen; mit etwas Vorwissen hat man noch mehr Spaß daran.

Doch hinter der guten Inszenierung und dem originellen Setting kann sich die schwache Story nicht verstecken; zu vorhersagbar ist das Ende. Das als Schicksal verkaufte Happy-End ähnelt in seiner Märchenform doch mehr den Bollywoodfilmen als modernen westlichen Plotstrukturen, da kann auch die realistisch anmutende Darstellung der schwierigen Entwicklungsperspektiven der Slumdogs genannten Kinder nicht helfen. Wieso ausgerechnet *Slumdog Millionär* bei den Oscars so triumphierte wird mir weiterhin ein Rätsel bleiben.

Fazit: Danny Boyle bleibt seinem inszenatorische Stil treu und präsentiert einen Film mit noch unverbrauchten indischen Kulissen und Darstellern. Leider können sich die Schwächen des Drehbuchs nicht hinter der guten Regie verstecken, wenngleich die schlimmsten Befürchtungen nach dem Trailer nicht eingetreten sind und man vor typischen Bollywood-Elementen bis zum Abspann verschont bleibt. Gute Unterhaltung aber auch nicht mehr hat *Slumdog Millionär* zu bieten, der Hype und die vielen Oscars sind allerdings aus meiner Sicht unberechtigt.
