---
title: "Harald Schmidt auf Tour"
date: "2005-11-30T15:36:53"
categories: [gesehen]
---

... durch Talkshows. Nach dem Auftritt bei [Beckmann](/blog/2005/11/15/reinhold-beckmann-vs-harald-schmidt/) und dem Abstecher zu "Wer wird Millionär" war er gestern zu Gast bei der [Münchener Runde](http://www.br-online.de/bayern-heute/artikel/0511/29-harald-schmidt-kurz/index.xml) im BR.

Ich selber kannte die Sendung und ihren Chefredakteur Sigmund Gottlieb vorher nicht, aber das Konzept scheint eher politisch zu sein. Der Moderator bemühte sich dementsprechend, seinen Gast zu kurzen Antworten zu bewegen und unterbrach viel, was aber seinem Gegenüber nicht aus der Ruhe brachte. Mit seiner manchmal ungewohnten Sichtweise und dem hintergründigen Humor konnte Harald Schmidt einige Pointen anbringen und auch geschickt populistische Konzepte in der aktuellen Diskussion hinterfragen. Warum aber ausgerechnet ein Late-Night-Talker in einer Politiksendung zum "Patienten Deutschland" befragt wird, bleibt wohl das Geheimnis des Senders. Auf jeden Fall war der Auftritt wieder sehr unterhaltsam

(Ich habe die Sendung leider erst in einer Wiederholung auf Phoenix kurz vor Mitternacht gesehen, als parallel bei Maischberger eine Frauenrunde über die Probleme der Welt debattierte und JBK als Kontrast mit vier Comedians plauderte - wobei Christoph Maria Herbst dementierte, dass er in Verhandlungen über eine dritte Staffel "Stromberg" stehe.)
