---
title: "Der Schuh des Manitu"
date: "2001-08-15T00:00:58"
categories: [gesehen]
---

*Deutschland (2001)
Regie: Michael Herbig
Darsteller: Michael "Bully" Herbig (Abahachi und Winnetouch), Christian Tramitz (Ranger), Sky du Mont (Santa Maria), Marie Bäumer (Halbblut Uschi), Rick Kavanian (Dimitri) und andere Westernhelden*
[Offizielle Homepage](http://www.derschuhdesmanitu.de)

Abahachi, seines Zeichens Apachenhäuptling, hat von dem Geschäftsmann Santa Maria ein Lokal gekauft, damit sein Stamm endlich auch über ein Stamm-Lokal verfügt. Als Abahachi und sein Blutsbruder Ranger bei der Übergabe jedoch feststellen, daß sie hinterlistig hereingelegt wurden, kommt es zu einem Eklat und Santa Maria erschießt Falscher Hase, der zufällig der Häuptlingssohn der Schoschonen ist, der Stamm also, der Abahachi das Geld für das Lokal geliehen hat. Von den Schoschonen gejagt und um das Geld betrogen, macht er sich mit Ranger auf, die Schuld von Santa Maria zu beweisen und den alten Familienschatz auszubuddeln um die Schulden zu begleichen...

Dieser Film braucht eine dringende Voraussetzung: Man muss den Humor von Bully mögen inklusive aller Anachronismen und man darf nicht alle von Bullys Winnetou-Parodien bereits kennen, denn diese machen ca. 1/3 des Filmes aus. Ist dies gegeben, so bekommt man 90min wirklich guter Comedy, bei der man zwischendurch kaum zum Luftholen kommt vor Lachen.

Doch der Film ist nicht nur reine Comedy, sondern auch eine Hommage an den italienischen Spaghetti-Western mit fantastischer Ausstattung - man meint sich wirklich in den Kino-Wilden-Westen versetzt. Sky Du Mont spielt einen herrlich verkommenen Bösewicht, der aber keine psychologisch ausgearbeitete Rolle verkörpert sondern im Gegenteil einen Querschnitt so ziemlich aller Western-Schurken darstellt - inklusive eigener, reudiger Bande. Auch der Bully-typische Grieche Dimitri (Bruder-Bluter) findet Platz im Film genauso wie ein Musical-Verschnitt und Slapstickeinlagen.

Fazit: Eine humorige Hommage an den Spaghetti-Western; nicht nur aber vor allem für Fans der Bullyparade!
