---
title: "Black Swan"
date: "2011-01-30T22:51:24"
categories: [gesehen]
---

*USA (2010)
Regie: Darren Aronofsky
Darsteller: Natalie Portman (Nina Sayers), Mila Kunis (Lily), Vincent Cassel (Thomas Leroy), Barbara Hershey (Erica Sayers), Winona Ryder (Beth Macintyre) und andere Schwäne*
[Offizielle Homepage](http://www.blackswan-derfilm.de/)

Nina Sayers lebt seit kleinauf den Traum ihrer Mutter, eine berühmte Balletttänzerin zu werden. Es gibt in ihrem Leben nichts neben dem Ballett; durch hartes Training will sie die Perfektion erreichen, die für das große Ziel, eine Hauptrolle zu tanzen, notwendig ist. Als an ihrem Theater eine neue Version von *Schwanensee* inszeniert wird und der Regisseur Thomas sie für die Hauptrolle auswählt, ist Nina zuerst unglaublich glücklich. Doch bald gibt ihr Thomas zu verstehen, dass sie zwar den weißen Schwan perfekt darzustellen weiß, aber für den Part des schwarzen Schwans nicht sinnlich und erotisch genug ist. Da Lily, die Zweitbesetzung der Rolle, genau diese Eigenschaften mitbringt, sieht sich Nina schnell in einer Konkurrenzsituation. Immer stärker wird der auf sie ausgeübte Druck und langsam scheint das Mädchen daran zu zerbrechen...

*Black Swan* ist ein Film, der zwischen den Genres pendelt. Mit seiner Darstellung des Balletts in klassischen Einstellungen und Schnitten ist er fast ein Tanzfilm, doch die gezielt eingestreuten Schockeffekte (die vor allem Verletzungen der Haut, des Oberflächigen betreffen) gepaart mit einem gewissen Humor erinnern mehr an Horrorfilme. Am Besten lässt er sich vielleicht als Psychothriller beschreiben - doch einen Genrefilm kann und will ich von Regisseur Darren Aronofsky gar nicht erwarten.

Interessante Details und Bilder dagegen schon. Die beeindruckend [realen Effekte](http://www.youtube.com/embed/4n71sjmd-bM) wie die wandernde Gänsehaut auf Ninas Körper sind überzeugend, wenn auch inhaltlich allzu plakativ. Der Film kennt keine Abstufungen, kein Grau, sondern nur Schwarz und Weiß, Böse und Gut. So trägt Nina immer helle Farben, wechselt jedoch nach ein paar Drinks in ein schwarzes Top und ist plötzlich nicht mehr das saubere Mädchen, der weiße Schwan, sondern ihr dunkles Gegenstück, ein Abbild der Konkurrentin Lily, die mit ihren dunklen Haaren und dem schwarzen Lidschatten den Gegenentwurf darstellt. Auf der einen Seite das unsichere, unerfahrene Mädchen mit den durch hartes Training perfektionierten Tanzschritten, auf der anderen Seite die laszive, sinnliche Lily, die mit ihrer Anmutung die handwerklichen Schwächen überspielt.

Ebenso offensichtlich finden sich immer wieder Szenen mit Spiegelungen und Abbildungen von Nina. In ihrem Perfektionswahn ("I just want to be perfect") sieht sie sich nur als reines Wesen und blendet alles aus, was an dieser Eigenwahrnehmung Zweifel aufkommen lässt. Sie akzeptiert weder, dass sie ständig an ihrem Ausschlag kratzt, noch dass ihre Mutter sie in dunklen Tönen und nicht als leuchtenden Stern zeichnet. In Spiegeln, Scheiben und an der Wasseroberfläche in der Badewanne kommt es aber wiederholt zu ungewollten Konfrontationen mit ihrem dunklen Ich; genügend zerstörte Gegenstände zeugen von der Spaltung der Persönlichkeit. Das Kratzen am Ausschlag symbolisiert das Bekämpfen des dunklen Schwans, den verdrängten Teil der Persönlichkeit. Denn der Ausschlag sieht aus wie eine gerupfte Geflügelhaut (später sieht Nina dort auch Federn herauswachsen) und ist unbewusst immer hinter der Schulter von Nina vorhanden, wenn auch nur im Spiegel sichtbar. Die Gefahr lauert also im Verborgenen, unter und hinter Oberflächen wie der Haut und Spiegeln, weshalb diese mehr als einmal im Film zerstört werden - in Nina kämpft der Wunsch, das Versteckte herauszulassen, mit dem Perfektionswahn, der die andere Seite unterdrückt.

Um dies zu vermitteln bleibt die Kamera immer ganz nah an Nina, zwängt dem Zuschauer die Perspektive der Protagonistin auf und macht es so schwierig, die Bilder auf der Leinwand richtig einzuordnen. Trotz dieses eingeschränkten Blickwinkels wird sichtbar, wie der Druck Nina langsam durchdrehen lässt, wie die schwer erfüllbaren Anforderungen zu viel werden für das bulimische Mädchen. Zu Wahrnehmungsstörungen gesellen sich Wahnvorstellungen und münden in einer rauschartigen Premierensequenz und einem frenetisch beklatschten Abgang des blutenden Schwans. Doch hat sich Nina nun selbst verstümmelt oder auch das nur eingebildet? Nina weiß es selber nicht und damit leider auch der Zuschauer.

Für den Regisseur ist diese Frage natürlich nicht entscheidend. Wie bereits in seinen [vorangegangen Filmen](/blog/2009/08/30/eine-kleine-darren-aronofsky-retrospektive/) möchte er nur zeigen, wie sich seine Charaktere in ihrer intensiven Lebensweise verlieren, wie sie einen einmal gewählten Weg trotz aller Probleme nicht verlassen können. Das Ende kann nur in der Katastrophe münden, und trotzdem bleibt es unbefriedigend offen.

Für Natalie Portman war dies sicherlich eine der schwierigsten Rollen ihrer Karriere. Schließlich muss sie den Film in den vielen Nahaufnahmen fast alleine auf ihren schmalen Schultern tragen. Dies schafft sie auf jeden Fall, jedoch bewirkt die Maske mehr Veränderung zum schwarzen Schwan als ihr Schauspiel. Da stehe ich an dem schwierigen Scheideweg zu entscheiden, ob dies die subjektive Perspektive des Films unterstützt, also gewollt ist, und Nina so zeigt, wie sich selber sieht - nämlich als perfekter weißer Schwan - oder ob Natalie Portman vielleicht doch daran gescheitert ist, die Abgründe und Schattenseiten der Baletttänzerin glaubhaft darzustellen. Oscarreif nenne ich das auf jeden Fall nicht, trotz der unbestreitbaren physischen Leinwandpräsenz.

Fazit: *Black Swan* ist das Charakterportrait einer an sich und den an sie gestellten Anforderungen scheiternden Balletttänzerin, angesiedelt zwischen Horrorfilm und Psychothriller. Dabei bewegt sich Aronofsky auf dem schmalen Grat zwischen eindringlichen Bildern und plakativen Motiven und kitzelt aus seinen Schauspielern alles heraus. Das Ergebnis ist zwar unterhaltsam, aber zu altbekannt und vorhersehbar und bleibt so vor allem durch seine Ecken und Kanten im Gedächtnis.
