---
title: "Star Trek: Raumschiff Enterprise - Season 1"
date: "2009-05-25T18:24:29"
categories: [gesehen]
---

Nachdem ich vor kurzem den neuen [StarTrek](/blog/2009/05/16/star-trek/)-Film im Kino sah, bin ich auf die Blu-Ray-Veröffentlichung der Originalserie aufmerksam geworden und habe sie bei der Online-Videothek meiner Wahl gleich bestellt (zumindest die erste von sieben Scheiben, der auch dieser Artikel zugrunde liegt).

Wie bitte mögen jetzt einige fragen. Eine über vierzig Jahre alte Fernsehserie wird auf einem HD-Medium veröffentlicht? Der glückliche Umstand, der dies ermöglicht, ist dass die fertig geschnittene Serie mit allen Spezialeffekten auf Filmband erhalten wurde und so mehr Details bewahrte als je im TV zu sehen waren.

Dies gilt natürlich nur für nicht nachbehandelte Szenen. Vor allem die Innenaufnahmen auf der Enterprise oder den Planeten haben nach dem digitalen Remastering ein sehr kontrastreiches Bild mit mehr erkennbaren Details als auf den bereits veröffentlichten DVDs. Nur bei wenigen Szenen ist das Bild verwaschen, wo es der Vorlage an Schärfe mangelte. Diese fallen aber umso deutlicher auf, ebenso wie die "Special Effects"-Aufnahmen im Weltraum, die einfach grauenvoll aussehen. Deshalb hat man alle Außenaufnahmen als 3D-Animationen im Stil der Serie erneuert und als alternativen Blickwinkel neben den Originalszenen auf die Blu-Rays gepackt. Dadurch wird die Trashigkeit der Originalserie erhalten; ich würde auf Full-HD-Fernsehern immer die Neuaufnahmen empfehlen.

Mit der aktuellen Digitalisierung der Filmbänder konnte man jedoch nicht das Format der Serie ändern, so dass das Bild im 4:3-Format vorliegt und auf heutigen 16:9-Fernsehern unschöne schwarze Balken rechts und links erzwingt. Ebensowenig wurde die Serie neu synchronisiert, so dass der deutsche Ton in deutlich rauschendem Mono vorliegt. Die englische Tonspur wurde als 5.1-DTS aufbereitet, hat aber auch nur eine Monospur als Grundlage und damit keinen merklichen Vorteil.

Fazit: So ganz HD ist die Blu-Ray-Version der *Raumschiff Enterprise*-Serie nicht. Zum Einen liegt der Ton nur in Mono vor, zum Anderen ist das Bild im 4:3-Format. Überraschend ist trotzdem, welche Details man dem alten Material noch entlocken konnte - wer als Fan die DVDs noch nicht besitzt, kann hier ohne Bedenken zugreifen.
