---
title: "Anatomie 2"
date: "2003-02-18T00:00:17"
categories: [gesehen]
---

*Deutschland (2003)
Regie: Stefan Ruzowitzky
Darsteller: Barnaby Metschurat (Jo Hauser), Herbert Knaup (Professor Müller-LaRousse), Heike Makatsch (Viktoria), Roman Knizka (Hagen), Wotan Wilke Möhring (Gregor), Frank Giering (Sven), Rosie Alvarez (Lee), Felix Kramer (Kurt), Sebastian Nakajew (Wulf), Joachim Bissmeier (Dr. Schinder), Hanno Koffler (Willi Hauser), Boris Pietsch (Manni/Fred), Franka Potente (Paula Henning), Rosel Zech (Dr. Bamberg), August Diehl (Benny) und andere Antihippokraten*
[Offizielle Homepage](http://www.anatomie-2.de/)

Der junge Arzt Jo Hauser hat seinen Vater durch eine seltene Muskelkrankheit verloren und hat deshalb eine sehr idealisierte Vorstellung von seiner Zukunft als Arzt. So nimmt er gerne die Gelegenheit war, mit dem anerkannten Professor Müller-LaRousse an Muskelimplantaten zu forschen. Doch bald muss er feststellen, dass der Professor und seine "Jünger" dabei nicht ganz ethisch vorgehen und der sogenannten Loge der Antihippokraten angehören. Doch in Anbetracht einer Heilung für seinen kranken Bruder lässt auch Jo sich von der Ausstrahlung des Professors blenden und tritt ebenfalls in die Loge ein. Zu spät erkennt er, dass er damit einen Pakt mit dem Teufel abgeschlossen hat, denn die Anhänger von Müller-LaRousse sind auch zugleich seine Testobjekte und der Professor verlangt immer schneller Ergebnisse. Zudem droht ein Mitglied der Loge mit dem Ausstieg und dem Gang an die Öffentlichkeit, wodurch die Situation langsam aus dem Ruder zu laufen scheint...

Anatomie war damals ein recht unterhaltsamer Film, angesiedelt im Heidelberger Uni-Milieu und mit Franka Potente und Benno Führmann auch ganz angenehm besetzt. Also dachte ich mir: Was einmal klappt kann auch ein zweites Mal gut gehen und setzte mich in die Fortsetzung, die aber außer der grundsätzlichen Thematik und dem (schlechten) Alibi-Auftritt von Frau Potente gar nichts mit Teil 1 gemein hat.

Im Gegensatz zur Vorzeige-Uni in Heidelberg dient diesmal ein heruntergekommenes Berliner Klinikum aus den 60ern als Handlungort, und die ehrenwerten Absichten des Haupdarstellers müssen in der kurz gehaltenen Einführung der ernüchternden Realität des Ärzte-Alltags weichen. Da erscheinen der moderne OP und die Riege an jungen Ärzten um Professor Müller-LaRousse schon eher als erstrebenswerte Zukunft, und so nimmt der Zuschauer Jo Hauser den Beitritt in die Loge durchaus ab. Doch bereits an dieser Stelle hat der Film sein Pulver komplett verschossen - die Story dümpelt fortan auf sehr vorhersehbaren Pfaden dem abzusehenden Ziel entgegen, die Figuren entpuppen sich als Standardcharaktere und die Schauspieler (allen voran Herbert Knaup) übertreiben ihre Rollen maßlos. Dabei nahm man Barnaby Metschurat den mit Idealen beladenen Jungarzt bis dahin wirklich ab und verstand auch, wie seine Kollegen dem Charisma und den Möglichkeiten des Professors erliegen konnten.

Um diese Mängel zu überspielen lässt der Regisseur dafür das Skalpell reichlich oft schwingen, egal ob es nun die Operationen oder die kleinen Scharmützel zwischen den Logenmitgliedern sind (ich sage nur das Hochschnellen des künstlichen Muskels aus Jos Unterschenkel!). Dementsprechend fließt deutlich mehr Blut als im ersten Teil; und damit die Schauspieler dies auch aushalten stehen die Charaktere in der letzten Viertelstunde nur noch unter Drogen - was zumindest eine gute Erklärung für die übliche Auflösungsszene ist, aber nicht die technisch-medizinischen Mängel der Story überspielt. Die drei kurzen Auftritte von Franka Potente wirken dabei nur unpassend und tragen auch in keiner Weise zu Story bei (im Gegensatz zum Schocker mit August Diehl am Anfang) - hier sollten wohl über die Werbung Fans des ersten Teils in die Kinos gelockt werden.

Fazit: Ein trotz der "2" im Titel eigenständiger Thriller im Mediziner-Milieu, der zwar einigermaßen gut unterhält aber in Sachen Story und Schauspielleistung nur TV-Niveau hat.
