---
title: "Gangs of New York"
date: "2003-03-03T00:00:11"
categories: [gesehen]
---

*USA/Italien (2002)
Regie: Martin Scorsese
Darsteller: Daniel Day-Lewis (Bill "The Butcher" Cutting), Leonardo DiCaprio (Amsterdam Vallon), Cameron Diaz (Jenny Everdeane), Jim Broadbent (William "Boss" Tweed), John C. Reilly (Happy Jack), Henry Thomas (Johnny Sirocco), Brendan Gleeson (Walter "Monk" McGinn), Gary Lewis (McGloin), Liam Neeson (Priest Vallon), Stephen Graham (Shang), Eddie Marsan (Killoran), Larry Gilliard Jr. (Jimmy Spoils) und andere Einwanderer*
[Offizielle Homepage](http://www.gangsofnewyork.de/)

1846: In ganz New York toben Bandenkriege, so auch zwischen den einheimischen Natives und den zugewanderten Iren. Bei der finalen Schlacht in den Straßen von Five Points muss der kleine Amsterdam mit ansehen, wie sein Vater, der Anführer der Einwanderer Priest Vallon, von Bill the Butcher, seineszeichens Anführer der Natives, erschlagen wird. 16 Jahre später kehrt der inzwischen erwachsene Amsterdam zurück - nur von dem einen Gedanken beseelt, Rache am Mörder seines Vaters zu üben. Dazu wird er Teil von Bills Gruppe und erlangt immer mehr das Ansehen seines Feindes. Währendessen kommt es verstärkt zu Unruhen in der Stadt, denn Präsidemt Lincoln hat um seine Armee im amerikanischen Bürgerkrieg gegen die Sklaverei und den Süden zu stärken eine allgemeine Wehrpflicht ausgerufen. New York gleicht immer mehr einem Pulverfass, das hochzugehen droht und Amsterdam sieht den Zeitpunkt seiner Rache am Todestag seines Vaters gekommen...

Wie lange musste ich jetzt auf den neuen Film von Scorsese warten! Schon ewig angekündigt nahmen die Dreharbeiten kein Ende (die Produktionskosten explodierten dank der Detailfreudigkeit des Regisseurs), aufgrund mäßiger Liebesszenen (?!) gab es immer wieder Nachdrehs und der Termin der deutschen Veröffentlichung rückte Monat um Monat nach hinten. Nun war es endlich soweit und ich konnte mich persönlich davon überzeugen, ob die Rangeleien mit dem Studio ihre Spuren im Material hinterlassen haben.

Die Hintergrundgeschichte des Films zeichnet den Weg auf, den die Stadt New York nehmen musste um zu dem zu werden, was sie heute darstellt. Der oft zitierte Schmelztiegel aus Einwanderern aus ganz Europa manifestierte sich in zahllosen Gangs, die sich gegenseitig dabei übertrafen, sich das wenig vorhandene Geld in der Stadt unter den Fingern wegzustehlen. Es geht um Macht und Einfluss in den vielen Vierteln wie Five Points, und auch die Politik interessiert sich für die Neuankömmlinge, denn sie braucht die Wählerstimmen und Soldaten für den Bürgerkrieg. In der Inszenierung dieses urbanen Pulverfasses liegt die Stärke von "Gangs of New York" und auch Scorseses eigentliche Intention, denn er wollte zeigen auf welchem Blut diese Stadt gebaut wurde (was die Blende am Ende schön verdeutlicht).

Doch darin eingeschlossen erzählt er die Geschichte um Amsterdam und Bill the Butcher als Vertreter zweier New Yorker Banden, denen es um ihre Abstammung und Identität geht und die doch bald feststellen müssen, dass sie eigentlich auf der selben Seite stehen und die noch jungen und ungefestigten Vereinigten Staaten zur Not auch mit Waffengewalt die Einbindung der neuen und alten Bürger in die Gesellschaft erzwingen. Der Regisseur räumt dabei grandios auf mit dem amerikanischen Traum, der die vielen Einwanderer in die neue Welt trieb.

Neben der tollen Kamera, dem wie immer guten Soundtrack von Howard Shore und der fantastischen Ausstattung ist es vor allem Daniel Day-Lewis, der mit einer oskarreifen Darstellung den Film über die 160 Minuten bringt. Trotz des das halbe Gesicht verdeckenden Bartes gelingt es dem Schauspieler mühelos, die verschieden Facetten des Bill the Butcher glaubhaft darzustellen, die Mimik und Gestik sind einfach überragend und er dominiert nach Belieben die Szenen mit den anderen Darstellern. Unter denen liefert Leonardo DiCaprio eine routinierte Leistung ab, ohne jedoch Day-Lewis ein ebenbürtiger Gegner zu sein (der wäre Liam Neeson wohl eher gewesen), während Cameron Diaz als Jenny Everdeane ziemlich blass bleibt und der Nebenplott um die Ziehtochter von Bill the Butcher, die sich schließlich von ihm abwendet um an Amsterdams Seite zu stehen, den Film unnötig in die Länge zieht und für einige Gähner meinerseits sorgte.

Fazit: Ein Epos mit Längen ist es schließlich geworden, das neue Werk vom Meister Scorsese. Eine Umverteilung der Plots hätte dem Drehbuch gut getan, aber Ausstattung, Kamera, Ton und der grandios aufgelegte Daniel Day-Lewis machen den Film trotzdem äußerst sehenswert (wenn man etwas Sitzfleisch für 160 Minuten mitbringt).
