---
title: "Hurra! Endlich mehr Informatiker!"
date: "2008-02-25T21:25:20"
categories: [gedacht,gefunden]
---

> Hip hip hurra! Alles ist super. Alles ist wunderbar. Hip hip hurra! Alles ist besser als es damals war.

So sangen die Ärzte einmal über die Angewohnheit, auch schlechte Dinge schön zu reden. Und so fühlte ich mich, als ich die Pressemitteilung des Statistischen Bundesamtes las, das mit der Überschrift [13% mehr Hochschulabsolventen in Informatik](http://www.destatis.de/jetspeed/portal/cms/Sites/destatis/Internet/DE/Presse/pm/2008/02/PD08__072__213,templateId=renderPrint.psml) die "aktuellen" Abgängerzahlen als Erfolg zu deklarieren versucht.

Dabei geht es interessanterweise um den Absolventenjahrgang 2006, dem ich auch angehöre und mir deshalb eine Meinung dazu erlauben darf. Immatrikuliert habe ich 2000 auf dem Höhepunkt des IT-Booms noch vor der DotCom-Krise (beides war für mich kein Entscheidungskriterium), und dementsprechend wurden seitdem die [Studienanfängerquoten](http://www.cio.de/_misc/img/detail.cfm?fk=847387&pk=669491) in der Informatik nicht wieder erreicht. Wenn man nun von meinen Erfahrungen ausgeht, dass die Regelstudienzeit von 10 Semestern vor allem an Unis nicht gehalten wird (auch ich habe ein Semester extra eingelegt), dann haben 2006 vor allem die Erstsemester von 2000/2001 ihren Abschluss gemacht.

Vergleicht man nun diese [Grafik](http://www.smart-girls.info/layout/set/print/(image)/11020) und die Ergebnisse des Statistischen Bundesamtes miteinander, dann kommt man zu der erschreckenden Erkenntnis, dass von knapp 37.000 Studienanfängern gerade einmal 15.400 ihr Studium erfolgreich abgeschlossen haben (immer unter der Voraussetzung, dass alle im Schnitt 11 bis 12 Semester gebraucht haben). Das sind weniger als 42%, wobei die Abbrecherquote in einigen Statistiken sogar auf über 60% beziffert wird! Und die Steigerung der Absolventenzahlen von 13% zum Vorjahr erscheint gleich viel weniger optimistisch wenn man sieht, dass es von 1999 zu 2000 einen Anstieg an Immatrikulationen von ungefähr 35% gab. Und als wäre dies nicht genug, sind die Einschreibezahlen seitdem rückläufig, so dass wir gerade die Spitze der Abgängerzahlen erreicht haben und den steigenden Bedarf an IT-Fachkräften in Zukunft nicht ausreichend bedienen können.

Diese Zahlen basieren natürlich nur auf Informationen, die ich im Internet gefunden habe und sind deshalb mit einer gewissen Skepsis zu betrachten. Trotzdem finde ich es erschreckend, dass so viele Kommilitonen den Abschluss nicht schaffen. 2000 mag dies ja noch an der Goldgräberstimmung gelegen haben ("Wer heute anfängt Informatik zu studieren, kann sich sein Gehalt selber aussuchen"), dass sich viele unvorbereitet in das "Abenteuer Informatikstudium" stürzten; mittlerweile dürften jedoch die meisten Abiturienten durch den verbesserten Informatikunterricht an den Schulen ein gewisses Verständnis dafür haben, was sie im Studium erwartet. Und inzwischen dürften sich auch die Hochschulen trotz der massiven Kürzungen auf die immerhin auf einem hohen Niveau stagnierenden Studentenzahlen eingestellt haben. Als ich mit meinem Studium anfing gab es noch einen deutlichen Mangel an Seminarplätzen und viele Vorlesungssäle waren anfangs zu klein gewählt.

Dank der großflächig eingeführten Studiengebühren wage ich nun die Prognose, dass es langfristig keine Verbesserung bei den Absolventenzahlen geben wird (was natürlich automatisch meine Chancen auf dem Arbeitsmark erhöht). Vielmehr werden es sich die Abiturienten angesichts dieser Zahlen zweimal überlegen, Geld in ein Studium mit einer so hohen Abbruchquote zu investieren - das Risiko des Scheiterns ist einfach zu groß. Zusammen mit der starken Verschulung des Studiums (dank des [Bolognaprozesses](http://de.wikipedia.org/wiki/Bologna-Prozess)) und dem gleichzeitigen Zwang, einen Nebenjob für die Finanzierung parallel zu organisieren, sind die Anforderungen an die Studenten in den letzten Jahren also gestiegen, während die Qualität des Studiums selber aufgrund der Sparmaßnahmen vieler (vor allem ostdeutscher) Bundesländer abnahm.

Die Folgen dieser fehlgeleiteten Bildungspolitik werden wir in den nächsten Jahren noch deutlich zu spüren bekommen. Ich freue mich schon auf die Überschriften der Pressemeldungen des Statistischen Bundesamtes in den nächsten Jahren. Und wenn die Poliitik dann endlich reagiert, werden wieder Jahre verstreichen, bis die Änderungen Früchte tragen.

Trotz allem: Ein Informatikstudium lohnt sich; man sollte sich nur vorher ausreichend über die Inhalte informieren, damit man nicht nach zwei Semestern aus allen Wolken fällt (ja, das Grundstudium besteht zu weiten Teilen aus Mathematik). Und wenn die kommenden Erstsemester schließlich ihren Abschluss in der Tasche haben, ist bestimmt auch der nächste [Schweinezyklus](http://de.wikipedia.org/wiki/Schweinezyklus) vorbei...
