---
title: "Meine liebsten Filme 2012"
date: "2012-12-31T22:02:19"
categories: [gedacht,gesehen]
---

Weil es [letztes Jahr](/blog/2012/01/16/meine-liebsten-filme-2011/) ganz nett war, mit etwas Abstand mein persönliches Filmjahr noch einmal Revue passieren zu lassen, habe ich auch für 2012 eine Liste der besten Filme angelegt. 

<ol>
	<li>Drive

Die Buchvorlage ist ein aufs nötigste reduzierter Kriminalroman, den Nicolas Winding Refn kongenial auf die Leinwand hinübergerettet hat. Er erlaubt sich zwar die eine oder andere Länge aufgrund der minimalen Dialoge, dafür sitzt aber jede Einstellung und die Bildsprache und der 80er-Jahre-Synthie-Soundtrack ergänzen sich perfekt. Getragen von der exquisiten Auswahl an Schauspielern (Carey Mulligan, Bryan Cranston, Ron Perlman) passt hier sogar die eingeschränkte Mimik eines Ryan Gosling ebenso wie die einen interessanten Kontrapunkt setzende Gewaltexplosion in der Mitte der Handlung. Der eindeutig beste Film des Jahres!</li>
	<li>[The Descendants - Familie und andere Angelegenheiten](/blog/2012/07/28/more-movies-on-planes/)</li>
	<li>The Artist</li>
<li>[Hugo Cabret](/blog/2012/06/17/schlosser-schlussel-und-nachrichten-toter-vater/)</li>
<li>[We need to talk about Kevin](/blog/2012/07/28/more-movies-on-planes/)</li>
<li>Kriegerin

Ein paar Probleme hatte ich mit dem Nachvollziehen der Charakterentwicklung der beiden Hauptfiguren. Doch davon abgesehen ist *Kriegerin* ein sehr intensiver Film mit zwei sehr guten Schauspielerinnen und einer mutigen Milieuzeichnung. Noch dazu kenne ich einige der Drehorte in Wolfen und Bad Prora - authentischer kann ein Film gar nicht sein.</li>
<li>Cheyenne - This must be the place

Sehr stranges Road-Movie mit einem klasse Sean Penn.</li>
<li>Über uns das All</li>
	<li>[Der Gott des Gemetzels](/blog/2012/07/28/more-movies-on-planes/)</li>
	<li>[Rent-a-Cat](/blog/2012/03/20/rentaneko/)</li>
	<li>[Csak a szél - Just the Wind](/blog/2012/03/01/csak-a-szel/)</li>
	<li>Der Hobbit</li>
<li>Iron Sky</li>
</ol>
