---
title: "Moonrise Kingdom"
date: "2012-06-17T22:53:37"
categories: [gesehen]
---

*USA (2012)
Regie: Wes Anderson
Darsteller: Jared Gilman (Sam), Kara Hayward (Suzy), Edward Norton (Scout Master Ward), Bruce Willis (Captain Sharp), Bill Murray (Walt Bishop), Frances McDormand (Laura Bishop), Tilda Swinton (Das Jugendamt), Bob Balaban (Erzähler), Jason Schwartzman (Cousin Ben), Harvey Keitel (Commander Pierce) und andere Pfadfinder*
[Offizielle Homepage](http://www.moonrisekingdom.de/)

Eigentlich erzählt der Film eine einfache Geschichte: Ein ungeliebter Waise (Sam) und eine stark pubertierende und sich missverstanden fühlende Tochter einer Anwaltsfamilie (Suzy) fliehen zusammen in die Wildnis einer vor der Küste Amerikas liegenden Insel. Während Suzys Eltern, der örtliche Polizist und die Pfadfinder, denen der Junge angehört, die Verfolgung aufnehmen, erleben die beiden ihre erste große Liebe. Doch bald werden sie gefunden und das Mädchen muss zurück zu ihren Eltern, während der Junge von der staatlichen Jugendbehörde in eine Besserungsanstalt gesteckt werden soll. Dieses Schicksal regt den Widerstand der Pfadfinder und so planen sie, das junge Pärchen auf eine andere Insel zu schmuggeln - ausgerechnet während eines der größten Stürme, der je über die Küste der USA hinwegzog...

Wes Anderson paart in *Moonrise Kingdom* klassische Motive des Coming-of-Age mit einer Abenteuergeschichte und dies würde kaum einen Zuschauer in die Kinos locken, wenn der Regisseur eben nicht Wes Anderson wäre. Dieser zieht wie gewohnt alle Register der Verfremdung, um seinen Film zu etwas Besonderem zu machen. Es fängt an mit dem seltsamen Soundtrack, der Stücke von Hank Williams (die Handlung spielt in den 1960er Jahren) mit viel Klassik kombiniert und dabei auch vor Schulstücken von [Benjamin Britten](http://en.wikipedia.org/wiki/The_Young_Person's_Guide_to_the_Orchestra) nicht halt macht - die Musik seiner Kindheit war laut dem Regisseur eine wichtige Inspiration für den Film. Die Charaktere, allesamt von namhaften Schauspielern verkörpert  - Tilda Swinton ist mal wieder grandios, Bruce Willis überraschend gut - sind irgendwo zwischen schrullig und skuril angesiedelt, und wo die Figur noch Reste von Normalität aufweist, ziehen Maske und Kamera das Bild ins Groteske.

Irgendwann haben mich die typischen Wes-Anderson-Kamerafahrten nur noch genervt. Schon die tableau-artigen Perspektiven, oft in der Totalen, finden sich eher in Comics und seltener im Film. Dass die Kamera sich jedoch parallel zum Geschehen seitwärts fortbewegt, erweckt wechselnd den Eindruck, dass ich eine Bühne oder ein Puppenhaus vor mir habe und der Regisseur freiwillig die Freiheit der Mise en scène im Film aufgegeben hat. Nur selten werden diese Kamerafahrten so kreativ eingesetzt wie bei der 360°-Drehung auf einem kleinen Steinplateau (der Junge geht links aus dem Bild und wird von rechts wieder eingefangen) oder wenn Kamera und Szene interagieren. So fährt die Kamera einmal durch den aufklappbaren Essenstisch der Bishops und der Vater klappt nach dem Durchfahren den Tisch wieder zu. In einer anderen Szene knippst der gut in den Film integrierte Erzähler vor einem Schwenk eine Lampe an der Kamera an, um danach von dieser beleuchtet zu werden.

Die kreative Maske und Kostümierung äußert sich vor allem bei den weiblichen Figuren. Suzy darf den ganzen Film über wie ein Vamp mit blau bis dunklen Lidschatten herumlaufen, der selbst bei starkem Tränenfluss nicht verläuft, und wird zwischendurch in stark kontrastierender, weißer Unterwäsche gezeigt. Tilda Swinton, die ganze Zeit nur mit ihrer Funktion angesprochen (das Jugendamt), steckt in einer strengen, blauen Uniform mit einem seltsamen viereckigen Hut - Farben werden in *Moonrise Kingdom* sehr offensiv eingesetzt.

Zwischendurch wähnte ich mich zudem mitten in einem 70er-Jahre-Softporno, als die Bilder auf der Leinwand mit einem extremen Weichzeichner den Eindruck erweckten, durch einen Schleier zu blicken. Mit der kräftigen Pastell-Farbpalette ist die Illusion der späten 60er Jahre auf jeden Fall perfekt.

So verwirrend der Einsatz dieser vielen Stilmittel ist, ihren Zweck verfehlen sie nicht. Denn vor allem in der ersten Stunde ist die Geschichte noch spannend, gleichzeitig jedoch ruhig und bedächtig erzählt und hält sich so genau in einem Schwebezustand zwischen realistisch und fantastisch. Als Beispiel seien Ideen wie das extrem hohe Baumhaus oder der Kampf von Sam und Suzy gegen die Pfadfinder genannt, bei denen das Pendel gerade noch in Richtung "übertrieben, aber denkbar" ausschlägt.

Dies ändert sich leider gegen Ende des Films, wenn die Handlung ins dramatisch-märchenhafte abgleitet und stark an das Finale von *Der fantastische Mr. Fox* erinnert. Eine abenteuerliche Klettertour auf dem Kirchendach mitten in einem Unwetter ist das krönende Finale einer Tour-de-Force, die vielleicht zu einem Kinderbuch gepasst hätte, für mich aber deplatziert wirkt.

So bleiben schöne Momente und Ideen wie die Findung des Filmtitels und ein paar interessante Kamerafahrten auf der Haben-Seite stehen, während ein paar verunglückte Verfremdungseffekte und das übertriebene Finale einen faden Beigeschmack hinterlassen. Wes Anderson hat bestimmt schon bessere Filme gemacht, aber wer einen der wenigen Auftritte von Bill Murray der letzten Jahre sehen will, kann *Moonrise Kingdom* durchaus einmal probieren.
