---
title: "Rock the box"
date: "2008-04-26T20:02:50"
categories: [gehört,getan]
---

Nachdem ich nun endlich einen [neuen MP3-Player](/blog/2008/04/26/sony-hat-mich-wieder/) habe, war es an der Zeit, den aus Angst um das Risiko des Ausfalls verschobenen Test der freien Firmware-Alternative [Rockbox](http://www.rockbox.org/) auf meinem iRiver H10 durchzuführen. Mit dem [RockboxUtility](http://www.rockbox.org/twiki/bin/view/Main/RockboxUtility) ist die Installation inzwischen sogar über eine GUI möglich, und innerhalb von ein paar Minuten konnte ich den Player neu starten und das Menü von Rockbox bewundern.

Dieses unterstützt als wohl wichtigstes Feature die Erstellung der internen Datenbank, so dass man ID3-Tag gesteuert durch die Musiksammlung browsen kann - dazu benötigte ich bisher das von mir übersetzte Tool [easyH10](/blog/2005/10/12/easyh10/). Neben der breiten [Musikformate-Unterstützung](http://www.rockbox.org/twiki/bin/view/Main/FeatureComparison#Other_features) gibt es stark erweiterte Einstellungen betreffend der Musikqualität, von deren Benutzung auf dem H10 aufgrund der schmalen Hardware jedoch abgeraten wird. Das Scroll-Touchpad erweist sich dagegen als nicht so intuitiv bedienbar wie mit der Originalfirmware, während die Akkulaufzeit bei geschätzten 80% liegt.

Ein echtes Highlight ist die Wiedergabe von MPEG-Videos. Ich hätte nie gedacht, dass das winzige 128x128-Pixel-Display so etwas hinbekommt, aber der freie Film [Elephants Dream](http://www.rockbox.org/twiki/bin/view/Main/PluginMpegplayer#Sample_Videos) läuft tatsächlich auf dem H10! Leider ist die Winkelabhängigkeit neben der geringen Auflösung ein echter Spaß-Killer. Generell kann Rockbox über PlugIns mit sinnvollen und -losen Features angereichert werden; die Bandbreite reicht von Minispielen (sogar Doom gibt es!) über Demos bis zu einer "Taschenlampe", bei der einfach nur das Display mit maximaler Helligkeit betrieben wird. Dabei fällt jedoch negativ auf, dass das Bedienkonzept nicht einheitlich ist: Bei einigen PlugIns gibt es Menüs zum Verlassen, bei anderen muss man den Power-Knopf drücken - nur die wenigsten bemerken, dass der H10 schon von Haus aus eine Zurück-Taste mitbringt.

Im Großen und Ganzen bringt Rockbox also einige neue Möglichkeiten auf den iRiver, doch ist die Nutzung aufgrund dessen Hardware meist nicht sinnvoll. Zusammen mit der geringeren Akkulaufzeit und dem subjektiv langsameren Menü würde ich also davon abraten, Rockbox als Standard zu verwenden. Als ausgereifte und stabile Technologiedemo hat es mich aber durchaus überzeugt, und wer [AAC](http://de.wikipedia.org/wiki/Advanced_Audio_Coding) und [OGG](http://de.wikipedia.org/wiki/Ogg) abspielen möchte, hat keine andere Wahl.
