---
title: "Android - das kleinere Übel"
date: "2011-01-05T22:48:11"
categories: [gedacht,gefunden,getan]
---

Nun ist es passiert. Nachdem ich fast elf Jahre lang meine wechselnden Telefone nur zum Telefonieren und Simsen genutzt habe, bin ich seit kurzem stolzer Besitzer eines [Milestone 2](http://www.motorola.com/Consumers/DE-DE/Consumer-Products-and-Services/Mobile-Phones/Milestone-2-DE-DE). Im Kampf der Betriebssysteme von Apple (iOs), Microsoft (Windows Phone 7) und Google (Android) hatte ich mich für die offenste der Plattformen entschieden. Meine Hoffnung war, dass ich unter Android die meiste Kontrolle über meine Daten habe. Schließlich habe ich elf Jahre lang in dem Bewusstsein gelebt, das alle Daten auf meinem Handy auch genau dort bleiben.

Doch mittlerweile weiß ich, dass die Unterschiede marginal sind. Zwar bin ich mit Android nicht an Anwendungen wie iTunes zur Synchronisation der Handydaten gebunden, doch auch Google weiß die Benutzer seiner Handys an sich zu binden. Dies fängt damit an, dass vor der ersten Benutzung des Geräts zwingend ein GMail-Konto angelegt werden muss. Ich besaß bereits ein Google-Konto für die Nutzung einzelner Dienste des Suchmaschinenprimus, doch dies reichte nicht. Ich musste zusätzlich ein Mailkonto anlegen, dass ich effektiv nicht nutze.

Zudem muss der Handybenutzer wissen, dass alle Kontakte per Default mit dem GMail-Konto synchronisiert werden. Ich wusste dies nicht und war nach dem Import total überrascht, als ich alle meine Kontakte bei Google wiederfand. Inzwischen ist die Synchronisation deaktiviert, doch einmal bei Google gespeicherte Daten gibt das Unternehmen nicht wieder her - sie verkaufen es sogar als Feature, dass sie die Kontakte zu jedem beliebigen Zeitpunkt wiederherstellen können.

Vorbei sind auch die Zeiten, wo ein Handy einen eigenen Kalender besaß. Termine müssen bei Android zwingend zu einem Onlinekonto gehören; in meinem Fall also das Exchange-Konto meiner Arbeit oder das GMail-Konto, welches ich eigentlich nicht nutzen wollte. Für die meisten Businessuser oder solche, die ohnehin GMail als zentrale Kontakte- und Terminzentrale einsetzen, mag dies ja ein gutes Vorgehen sein, aber ich habe da andere Vorstellungen. Was mache ich mit Terminen, die weder mein Arbeitgeber noch Google wissen soll?

Für mich ist das Handy als ständiger Begleiter die Zentrale für sämtliche E-Mails, SMS, Kontakte und Termine. Diese synchronisiere ich als Backup gerne mit meinem eigenen Rechner, nicht aber mit Anbietern im Internet, die meine privaten Daten einfach nichts angeht. Für so komplexe Szenarien der Synchronisation ist Android aber nicht geeignet. Und schon die wenigen Einstellmöglichkeiten, die es bietet, sind nicht konsequent ausgeführt. So gibt es verwirrende Einstellungskombinationen bei den Kalenderkonten. Diese können zwar auf *synchronisiert* und *nicht sichtbar*, nicht aber auf *nicht synchronisiert* und *sichtbar* eingestellt werden. Die Synchronisationsoptionen unter Konten wiederum scheinen gar keinen Einfluss auf den Kalender zu haben.

Ein weitere Quelle für munteres Daten-aus-der-Hand-geben sind die herstellerspezifischen Oberflächenanpassungen wie Motorola es mit [Motoblur](http://www.mobiflip.de/2010/11/was-genau-ist-eigentlich-motorola-motoblur/) getan hat. Zum Glück kann das Anlegen eines *My Motoblur*-Kontos, mit dem das Handy überall auf der Welt geortet werden kann, im Gegensatz zum GMail-Konto abgelehnt werden und das Handy kann trotzdem benutzt werden. Nur auf Updates der Systemsoftware muss dabei verzichtet werden. Da mir aber vor dem Kauf des Handys klar war, dass Motorola aufgrund der tiefen Systemeingriffe von Motoblur ohnehin selten Android-Updates überhaupt nachzieht, sehe ich kein Problem darin.

Die angepasste Kontakteverwaltung von Motoblur hat jedoch ein Problem mit den Geburtstagen. Werden diese eingetragen, kann sie keine andere App auf dem Telefon auslesen. Als ich sie jedoch über die externe Software [MyPhoneExplorer](http://www.fjsoft.at/de/home.php) eingepflegt habe, konnte ich sie nicht mehr in der Kontakteverwaltung lesen, aber dafür erkannte [EboBirthday](http://www.ebomike.com/android/ebobirthday/) sie endlich. Es scheint also ein Problem mit dem Speicherformat zu geben. Mit *EboBirthday* in Version 1.7.4 hat sich das Problem aber erledigt, denn es gibt nun einen Motorola-Kompatibilitätsmodus. Wird dieser aktiviert und die Geburtstage anschließend zurück exportiert, zeigt sogar die Kontakteverwaltung die Daten richtig an.

Desweiteren bringt das *Milestone 2* eine Vielzahl von Apps mit, die leider nicht deinstalliert werden können. Da die App-Verwaltung inklusive einer sauberen Installation sonst eine der Stärken von Android ist, konterkariert Motorola damit dieses Konzept. Vor allem, da das *Milestone 2* selber eine Art Taskmanager mitbringt, mit dem gut die laufenden Apps analysiert, beendet oder deinstalliert werden können, verwundert die feste Integration von Anwendungen wie den verschiedenen GoTV-Channels.

Nachdem ich jetzt so viel über die Probleme der Privatsphäre im Einsatz von Googles Betriebssystem geschrieben habe muss ich natürlich zugeben, dass ich mich trotzdem für das *Milestone 2* und Android entschieden habe. Denn sie bieten zusammen eine tolle Mischung aus leistungsfähiger Hardware (die im Gegensatz zum [HTC Desire Z](http://www.htc.com/de/product/desirez/overview.html) auch robust erscheint) und anpassungsfähiger Software. Die Auswahl an Apps im Android Market ist schon beeindruckend, und im Gegensatz zu Apples Marktplatz sind die meisten Anwendungen auch kostenlos.

Ich möchte deshalb ein paar Empfehlungen für Android-Apps aussprechen:

Ein echtes Highlight unter den Widgets ist [Widgetsoid](http://jaumard.android.free.fr/widgetsoid). Dieses bietet einen optisch überzeugenden Zugriff auf viele der wichtigen Funktionen, die ich am Handy schnell ändern will: WLAN an/aus, GPS an/aus, Bluetooth an/aus, Ton an/Vibration/alles aus und vieles mehr. Diese Schalter werden zu einer Leiste verbunden, die sehr ökonomisch mit dem gegebenen Platz auf den Home Screens umgeht, und dabei gleichzeitig noch toll aussieht.

Unter dem MediaPlayern sticht meiner Meinung nach [PowerAmp](http://powerampapp.com/) hervor. Dieses bringt nicht nur eine eigene Decoderlibrary mit, die im Gegensatz zum Android-eigenen Player nicht auf Taktschwankungen des Handyprozessors mit Knacksern reagiert, sondern bietet auch noch einen hervorragenden Equalizer, wie ich ihn in keiner anderen App gefunden habe. Dafür muss man aber auch 5$ ausgeben.

Noch von meinem Vorgängerhandy kenne ich [MyPhoneExplorer](http://www.fjsoft.at/de/home.php), welches sich beim Backup von SonyEricsson-Geräten hervortat. Nun hat der Autor die Zeichen der Zeit erkannt und bietet über eine App die Möglichkeit an, Kontakte und Termine auch zwischen Android-Handys und PCs zu synchronisieren. Im Gegensatz zum identischen Ansatz des von Motorola mitgelieferten Phone Portal erlaubt der MyPhoneExplorer ein komfortableres Editieren der Kontakte und dabei den Zugriff auf wirklich alle Felder - das Phone Portal konnte zum Beispiel keine Geburtstage speichern. Und da sowohl Android selber als auch das Phone Portal kolossal am Import meiner als VCF gespeicherten Kontakte scheiterten, war ich sehr glücklich, einfach das Programm meines alten Handys weiternutzen zu können.
