---
title: "Meine Lieblingsalben 2005"
date: "2005-12-30T15:24:44"
categories: [gedacht,gehört]
---

Im Fernsehen laufen sie seit einem Monat, und in allen Blogs liest sie man sie kurz vor Jahreswechsel: Die Rückblicke mit dem Besten und Schlechtesten, was das Jahr 2005 zu bieten hatte. Da will ich nicht hinten anstehen und werde deshalb (noch einmal) die Musikalben und Filme vorstellen, welche mich dieses Jahr beeindruckt haben. Die schlechten Beispiele dieser Gattungen mag jeder selber herausfinden; ich bin der Meinung dass sie für diese "Leistung" nicht noch mit einem Eintrag in meinem Blog belohnt werden sollten.

Fangen wir nun mit den Musikalben an, bei denen es nur fünf geschafft haben, mich längere Zeit zum Hören zu bewegen. Dies liegt zu Einen daran, dass mir durch die Diplomarbeit etwas die Zeit gefehlt hat und ich deshalb sicherlich viele gute Alben verpasst habe. Andererseits gab es auch eine Fülle von guten Alben, bei denen aber immer etwas gefehlt oder gestört hat, um sie in diese Liste aufzunehmen.

<ol>
	<li>**LAB - Where heaven ends** Für mich stellt dieses Album das absolute Highlight des Jahres dar. Der Ausstoß von Gothic-Rock und -Pop-Bands aus Finnland läuft weiter auf höchster Flamme, und so haben es auch *LAB* auf den deutschen Markt geschafft. Die kraftvolle Mischung aus eingängigen, klavierbetonten Melodien und der Stimme von Sängerin Ana bringt auf einer CD ohne Durchhänger und aus einem Guss eine Vielzahl von hervorragenden Kompositionen zu Stande, welche auch textlich überzeugen können. Die beste Musik für trübselige Herbstmorgen in Bus oder Auto!</li>
	<li>**My chemical romance - Three cheers for sweet revenge** Gothic-Punk scheint das neue Medium für die College-Außenseiter aus Amerika zu werden und damit treten *My chemical romance* in die Fußstapfen von Bands wie *Nada Surf* und *Weezer*, deren letzte Alben etwas die Innovation fehlte. Ganz anders dagegen das Erstwerk der Punker, welches bereits eine Soundkulisse aufbieten kann, wie man sie bisher nicht gehört hat. Explosive Gitarren und der Schrei-Gesang vereinigen sich zu Kompositionen, welche wie Popsongs im Ohr hängen bleiben.</li>
	<li>**System of a down - Mezmerize** Eigentlich sollte man sauer sein auf *SOAD*, weil sie ein Album in zwei (recht kurze) Teile splitten und den Fan doppelt abkassieren wollen. Aber aus meiner Sicht kann *Hypnotize* mit der ersten Hälfte nicht im Ansatz mithalten, welche den bisherigen Höhepunkt der amerikanisch-armenischen Hardrock-Gruppe darstellt. Während früher die Texte im Stakkato-Tempo herausgeschrien wurden, gibt es inzwischen vielschichtigere Arrangements und Songstrukturen und die CD ist bedeutend abwechslungsreicher als die früheren Werke. Deshalb findet sie sich auch bis heute auf meinem MP3-Player und wird immer wieder gerne in die Playlist aufgenommen.</li>
	<li>**Coheed and Cambria - Good Apollo I’m Burning Star IV Volume One** Seit Weihnachten höre ich nur noch dieses Album mit dem eigentlich noch viel längeren Namen. Coheed and Cambria produzieren Progressive Rock zu einer wirren SciFi-Fantasy-Story, welche zum besseren Verständnis auch als Comic erworben werden kann. Es geht in den Songs um eine Familie, welche einen Virus in sich trägt, der den Untergang der Menschheit bedeuten kann. Da erst die Teile 2 bis 4,5 der Saga auf CD erhältlich sind, bleiben die Texte einiger Lieder unverständlich. Der Grundtenor ist aber eher düster und dramatisch, was die Lieder sehr gut transportieren.</li>
	<li>**Leaves' Eyes - Vinland Saga** *Leaves' Eyes* ist die neue Band von der ehemaligen *Theatre of Tragedy*-Frontfrau Liv Kristine, welche eine Gruppe von hauptsächlich deutschen Musikern um sich geschart hat und nun dort weitermacht, wo das letzte Album von *TOT* aufhörte: Sehr melodischer Gothic. Ein wenig hört sich der Sound von *Leaves' Eyes* mit der unterstützenden Männerstimme an wie die frühen *Within Temptation*. 
Das Album kann man ruhigem Gewissens als ein Konzeptalbum beschreiben. Das Thema der nordischen Völker und ihrer Seereisen begleitet den Hörer in allen Songs. Die Hälfte der Lieder sind zwar Balladen fast ohne Metaleinschlag und genau auf Liv Kristine zugeschnitten, aber als Gesamtwerk kann die *Vinland Saga* mehr überzeugen als das ähnlich konzeptierte letzte Album von *Subway to Sally*.</li>
</ol>
