---
title: "Die Polizei, Dein Freund und Wächter"
date: "2008-01-30T22:10:14"
categories: [gedacht]
---

Seit gestern findet in Berlin in unmittelbarer Nähe meiner Arbeitsstelle der [11. europäische Polizeikongress](http://www.euro-police.com/) statt. Dies führte zu einem [Aufmarsch von 1200 Polizisten](http://www.heise.de/newsticker/meldung/102667), um die tagenden Vertreter des Staates vor 400 Demonstranten zu beschützen. Wenn jedoch die Polizei die Polizei beschützen muss - wer beschützt dann die Beschützer der Beschützer???

Natürlich war auch die Forderung nach der heimlichen Online-Durchsuchung Thema auf dem Kongress. Laut [heise](http://www.heise.de/newsticker/meldung/102700) ist diese für den hessischen Innenstaatssekretär [Harald Lemke](http://de.wikipedia.org/wiki/Harald_Lemke)

> [...] wichtiger als die Vorratsdatenspeicherung und alle anderen Maßnahmen, Staatlichkeit in das Internet zu bringen. [...] Es sei längst so, dass Terroristen und die organisierte Kriminalität sich über das Internet koordinieren, ohne dabei E-Mail zu nutzen. Längst würden sie eine End-to-End-Veschlüsselung einsetzen, die nur dadurch zu überwinden sei, dass man vor der Verschlüsselung auf das System zugreift. Die Vorstellung, dass die Festplatte heilig ist, ist eine veraltete Vorstellung.

Aha. Zum Einen wird also gerade massiv in die Grundrechte eines jeden Bürgers eingegriffen und die Unschuldsvermutung außer Kraft gesetzt, ohne dass die Polizei einen wirklichen Nutzen daraus ziehen kann. Da hat sich der undemokratische Weg über den Europarat ja richtig gelohnt. Doch keine Sorge; ich bin mir sicher dass sich bald jemand finden wird, der die Daten jenseits der gesetzlich vorgeschriebenen Zweckbindung zu nutzen weiß.

Zum Anderen sieht es so aus, dass wir keine 20 Jahre nach dem Ende der DDR endlich wieder eine Staatssicherheit bekommen, die die Bürger ihres Staates hemmungslos ausspionieren darf. Denn ein verdeckter Zugriff auf Festplatten ohne Wissen des Besitzers mittels eines Spionagetools ist für mich nichts anderes als das Anbringen von Wanzen in einer Wohnung. Auch die Stasi hatte das Problem, dass durch die gegenseitige Überwachung und das dadurch entstandene Missstrauen viele Gespräche nur noch im Privaten geführt worden. Jetzt hat die bundesdeutsche Polizei durch die ständige Aufrüstung der Verfolgungsmittel die "organisierte Kriminalität" so weit getrieben, dass diese eine technologische Stufe erreicht hat, auf der nur noch der direkte und geheime Zugriff in den Wohnungen zu Erfolgen führt (zumindest sieht dies wie die leichteste Lösung aus).

Doch leider kann nicht jeder normale Bürger dieses Stufe erreichen, sei es nun mangels Devisen oder dem entsprechenden Wissen. Gleichzeitig fehlt es der Polizei aus diesem Grund auch an Beweisen, um überhaupt eine Fahndung einzuleiten, so dass die Überwachung als Beweisbeschaffung herhalten muss und somit wirklich alle Bürger einem Verdacht ausgesetzt werden können. Dass dies einem freiheitlichen Staat widerspricht und zu merklichen Einschränkungen für jeden von uns führt, sollte das Beispiel DDR eindringlich gezeigt haben. Also ist eher die Idee der heimlichen Online-Durchsuchung eine "veraltete Vorstellung", die noch dazu rechtsstaatlichen Prinzipien widerspricht.

Ich kann nur hoffen, dass unsere Abgeordneten, die über dieses Thema entscheiden müssen, wenigstens noch etwas Verstand und Verantwortung besitzen, diesen Staat und seine grundlegenden Prinzipien nicht aus Machtwillen zur Grabe zu tragen
