---
title: "About Schmidt"
date: "2003-04-11T00:00:32"
categories: [gesehen]
---

*USA (2002)
Regie: Alexander Payne
Darsteller: Jack Nicholson (Warren Schmidt), Kathy Bates (Roberta Hertzel), Hope Davis (Jeannie Schmidt), Dermot Mulroney (Randall Hertzel), June Squibb (Helen Schmidt), Len Cariou (Ray Nichols) und andere Rentner*
[Offizielle Homepage](http://www.aboutschmidtmovie.com/)

Für den Versicherungsstatistiker Warren Schmidt ist die Zeit des Ruhestandes gekommen und so gibt er widerwillig seinen Job an einen jüngeren Nachfolger ab. Doch Warren hat kaum Zeit mit der ungewohnten Situation, nicht täglich arbeiten zu müssen, klarzukommen, als überraschend seine Frau Helen verstirbt. Die Beziehung der beiden verdiente zwar den Namen nicht, jedoch war es Helen, die den Schmidtschen Haushalt regelte und so klammert sich Warren an seine Tochter Hope, damit der Übergang für ihn nicht so schmerzlich wird. Doch die Tochter kann ihren Vater als Belastung nicht gebrauchen, erst recht nicht kurz vor der Hochzeit mit dem vom Vater nicht gerade akzeptierten Randall. Um seiner Unfähigkeit den Haushalt zu führen aus dem Weg zu gehen macht sich Warren mit dem neuen Wohnmobil auf, um Stationen seines Lebens noch einmal zu besuchen und am Ende der Reise noch ein Wörtchen über die Hochzeit seiner Tochter mitzureden...

Kann ein Schauspieler allein einen Film tragen? Im Falle von Jack Nicholson kann man diese Frage wohl eindeutig mit ja beantworten; zumindest hat er oft genug mit genialen schauspielerischen Leistungen die anderen Darsteller an die Wand gespielt. Und auch "About Schmidt" ist so eine One-Man-Show, in der sich die Vielseitigkeit des Mimen zeigt, wenn er sich hinter der Maske des verschrobenen Rentners versteckt und nie einen Zweifel an der Authentizität seiner Rolle aufkommen lässt. Da kann der Rest der Besetzung nicht viel dazu beitragen, wenngleich vor allem die herrlich skurile Familie Hertzel mit u.a. Kathy Bates sehr ordentlich besetzt wurde. Aber an Nicholson kommt halt keiner vorbei.

Trotzdem kann mich der Film nicht überzeugen. Das hängt vor allem damit zusammen, dass sich der Regisseur für das Erzählen der Selbstfindung des Warren Schmidt sehr viel Zeit lässt - zu viel Zeit - und der Hauptcharakter diesem Tempo angepasst sehr verhalten agiert. Keine Zweifel, dass der Regisseur dem Zuschauer hier einen authentischen Pensionär präsentiert, aber dies ist zeitweilig weniger aufregend als Kaffee bei Oma und Opa - und dazu geht man nicht ins Kino. Wie schon in [The Hours](/blog/2003/03/31/the-hours-von-ewigkeit-zu-ewigkeit/) wird an Dialogen und dummerweise auch an Inhalt gespart. Erst gegen Ende, wenn sich der Film der Familie Hertzel zuwendet, kommt als Analogie ein bisschen Schwung und Pfeffer auf die Leinwand.

Davor hat der Zuschauer genügend Zeit, sich über die Situation des Ruheständlers klarzuwerden und die vielen kleinen Lügen in der Familie Schmidt aufzudecken, hinter denen sich auch Warren anfangs noch in den Briefen an seinen afrikanischen Patensohn versteckt. Denn am meisten fehlt Schmidt scheinbar der Umgang mit Personen, die ihn zumindest teilweise verstehen mit denen er sich aussprechen kann - mit seiner Frau konnte er das nie und seine Tochter hält ihn lieber auf Abstand. So hat er über die Jahre eine innerliche Distanz zu allen Menschen aufgebaut, die erst die Enttäuschungen nach dem Tod seiner Frau, die Erfahrungen auf seiner Wohnmobilreise und der Umgang mit der sehr unkonventionellen Familie Hertzel aufbrechen können. Zumindest lernt er am Ende des Films seine Situation zu akzeptieren und ehrlicher zu sich selbst zu sein - und der Zuschauer fragt sich, warum er Warren Schmidt dabei auf jeder Etappe so ausgiebig begleiten musste (Ich möchte hierbei betonen: Bitte lasst mich nie wieder den Hintern von Jack Nicholson oder die Brüste von Kathy Bates sehen!).

Fazit: Sehr gute Schauspielerleistungen (allen voran Jack Nicholson) und eine exakte Charakterzeichnung lassen den Film leider genau daran scheitern: Die Selbstfindung des Ruheständlers Warren Schmidts ist arm an Höhepunkten, da hilft auch der sehr dezente Humor nicht. Empfehlenswert ist der Film höchstens für Fans von Nicholson und die Zielgruppe über Fünfzig.
