---
title: "Das zweite VIVA wird aufgegeben"
date: "2006-02-24T20:48:08"
categories: [gedacht,gefunden]
---

Laut einer Meldung der dpa (z.B. [hier](http://www.chart-radio.de/news_artikel.php3?fetchid=207635) zu lesen) und [eines Artikels auf RP-Online](http://www.rp-online.de/public/article/nachrichten/medien/tv/118750) wird der Musiksender VIVA Plus in diesem Jahr seinen Abschied feiern und durch einen Comedykanal ersetzt.

Seit dem traurigen Ende von VIVA ZWEI wurde der zweite Ableger des Kölner Senders VIVA als vom Zuschauer durch SMS finanzierte Video-Jukebox betrieben: Kein Personal und praktisch kein redaktionelles Programm, dafür aber eine Direktfinanzierung über Premium-SMS sollten den Kanal profitabel machen. Scheinbar war dieses Unterfangen nicht von Erfolg gekrönt oder der Imageschaden durch die SMS-Schulden der Jugendlichen war zu groß - jedenfalls wird es in Zukunft nur noch zwei Musiksender in Deutschland geben (MTV & VIVA), welche jedoch beide von einem Unternehmen (Viacom) betrieben werden.

Doch etwas anderes war nach dem Kauf von VIVA durch die MTV-Mutter Viacom nicht zu erwarten. So wurden aus vier Musiksendern innerhalb kürzester Zeit nur noch zwei, wobei die Qualität von VIVA wohl niemanden überzeugen kann: Die besten Shows wurden an MTV abgegeben und eigene Produktionen sind Mangelware. Dafür kommt der Zuschauer in den "Genuss" billiger amerikanischer Sendeformate, die bestenfalls mit deutschen Untertiteln versehen wurden.

Wie VIVA weiter gemolken wird, zeigt auch die Zukunft von VIVA Plus: Die Tochterfirma Brainpool wird einen Teil des Programms für den neuen Comedysenders beisteuern, jedoch werden auch weiterhin die Topformate an die großen Sender verkauft. Dafür sollen "Nachwuchsstars" wie einst Stefan Raab bei VIVA mit eigenen Shows versorgt werden. Den Hauptanteil werden aber wahrscheinlich amerikanische Produktionen stellen, welche zum Teil jetzt schon auf MTV oder Nick laufen. Ein eigener Comedykanal aufgrund der eigenen Kompetenzen ist also ein durchaus logischer Schritt.

Leider geht dies jedoch auf Kosten des quasi nicht mehr existenten deutschen Musiksender-Marktes. Wo einst fünf Sender (MTV, MTV Pop, VIVA, VIVA ZWEI, Onyx) um die Gunst der Zuschauer buhlten und maximale Abwechslung boten, herrscht heute gähnende Langeweile (Ausnahmen wie die Sarah Kuttner Show bestätigen die Regel). Musik abseits des Mainstreams wird, wenn überhaupt, nur nachts gespielt, dafür darf sich der Zuschauer aber mit ausreichend Werbung für Handy-Klingeltöne ~~nerven~~ beschallen lassen.

Als Hauptgrund werden oft fehlende Werbeeinnahmen aufgrund des zu geringen Zielpublikums genannt. Dabei sollten gerade die genau eingrenzbaren Zielgruppen der Werbebranche entgegenkommen. Aus meiner Sicht ist es daher eher die Bestimmung der Einschaltquoten, welche als einzige Metrik für den Zuschauerzuspruch manche ungewünschte Auswirkung nach sich zieht. So werden die Sehgewohnheiten eines geringen, repräsentativen Ausschnitts der Bevölkerung auf alle 80 Millionen Einwohner Deutschlands hochgerechnet. Dieses Verfahren kann jedoch keine ausreichende Genauigkeit in den Nachkommastellen bieten, so dass Entscheidungen über das Wohl von Sendungen und ganzen Sendern bei Einschaltquoten von 0,x (typisch für Musiksender) aufgrund von nicht gesicherten Daten getroffen werden.

Wenn in den Chefetagen der Sender dann auch noch die Rendite als alleiniges Ziel des Unternehmens angesehen wird, kommt es zu der aktuellen Verdichtung des Marktes, da man natürlich keine vier Sender braucht, welche alle dieselbe Mainstream-Musik spielen. Der Kauf von VIVA durch Viacom war also der endgültige Todesstoß für das deutsche Musikfernsehen. Da momentan auch die klassischen Verwerterkanäle (Radio - Musikfernsehen - CD) der Musikindustrie zusammenbrechen, wird es wohl nie wieder die paradiesischen Zustände vom Ende der 90er Jahre geben.

Bleibt zu hoffen, dass nach dem Boom der Internetradios und der Podcast-Blogs demnächst auch moderierte Internet-Videoclip-Streams entstehen. Diese werden zwar verglichen mit den TV-Sendern weniger qualitativ hochwertige Sendungen produzieren, aber wenigstens wird es wieder eine größere Auswahl und ein breiteres Spektrum geben. Dies hoffe ich zumindest!
