---
title: "Shadow of the Vampire"
date: "2001-08-07T00:00:33"
categories: [gesehen]
---

*USA (2001)
Regie: E. Elias Merhige
Darsteller: John Malkovich (F.W. Murnau), William Dafoe (Max Schreck), Udo Kier (Produzent Albin Grau), Cary Elwes (Kameramann Fritz Wagner), Catherine McCormack (Greta), Eddie Izzard (Gustav von Wangenheim) und andere Stummfilm-Stars*
[Offizielle Homepage](http://www.shadow-of-the-vampire.de)

Friedrich Wilhelm Murnau, einer der größten Regisseure des noch jungen Kinos, will den besten, größten und realistischsten Film aller Zeiten drehen und hat sich dafür den Dracula-Stoff in einer umgeschriebenen Version (Nosferatu) ausgewählt. Um einen möglichst hohen Realitätsgrad zu erreichen, soll nur an authentischen Drehorten gefilmt werden und nur die besten Schauspieler sollen für das Meisterwerk vor die Kamera treten. Da wundert es schon, daß Murnau ausgerechnet den unbekannten Max Schreck für die Hauptrolle des Grafen auswählt. Zum ersten Mal bekommt ihn die Filmcrew in der Tschechei zu sehen, wo in einer alten Schloßruine gedreht wird. Laut Murnau lebt sich Max Schreck immer ein paar Monate vor den Dreharbeiten in seine Rolle ein und behält sie auch in Drehpausen bei, um so zu dem Kunstwerk beizutragen. Doch bald passieren erste Vorkommnisse und der Kameramann muß aufgrund von Blutmangel ausgetauscht werden - ist Murnau bei seinem Perfektionswahn etwa so weit gegangen und hat einen echten Vampir verpflichtet...?

Es ist unglaublich, aber ein so fantasievoller Film über die Glanzzeit des deutschen Kinos kommt ausgerechnet aus den USA, der aktuellen Hochburg, von der wir so ein Highlight absolut nicht erwartet haben. Zudem verpflichtete man auch noch 2 Charakterdarsteller, die in dem Film Glanzleistungen zeigen - allen voran William Dafoe, der sich so gut schauspielerisch hinter der Maske versteckt, daß man ihn kaum wiedererkennt.
 
Der Regisseur verlässt sich jedoch nicht allein auf das Spiel seiner Besetzung, sondern setzt den Film mit den vielen Wechseln in die Original-Szenen von "Nosferatu" und dem geschickten Einflechten von schwarzem Humor auf verschiedenen Ebenen an, die zusammen einen Film über die Gründerzeit des Kinos, über einen Regisseur, um den sich noch heute Legenden ranken, ja sogar einen Vampirfilm selber ergeben. Und genau diese Vielschichtigkeit macht den Reiz an diesem Werk aus. Dank der guten Ausstattung bekommt man wirklich das Gefühl, man sei bei den Dreharbeiten zu einem der Meisterwerke des Kinos (der Film machte übrigens das Buch von Bram Stoker erst berühmt - und sorgte so für viele "Remakes") dabei.

Fazit: Ein Film über einen Film - wer leicht abstrakte Handlungsstränge und das Flair der 20er mag, der muss diesen Film gesehen haben. Wer sich jedoch zu sehr an die actionlastigen Drehbücher der heutigen Zeit gewöhnt hat, der kann sich durchaus langweilen!
