---
title: "Zeitgeist"
date: "2009-05-25T17:44:22"
categories: [gesehen]
---

Ein Dialog aus dem Film *Amateur* von 1994:

> Sie: Das Ding hier nennt man Floppy-Disk? Die ist viereckig!
> Er: Ja, aber man sagt dazu Floppy-Disk.
> Sie: Sie ist auch nicht biegsam, sie ist ganz steif!


15 Jahre später und nur vierzig Jahre nach ihrer Erfindung spielt die klassische [Diskette](http://de.wikipedia.org/wiki/Floppy) mittlerweile keine Rolle mehr. Der Film, ganz im Stil der von mir so geliebten [Coen-Loser](http://www.dudeism.com/)-Stories, zeigt sich aber nicht nur bei den biegsamen Datenträgern ganz auf der Höhe des damaligen Zeitgeistes. Auch die ersten Handys und die hübschen Bügelkopfhörer der Walkmen laden aus heutiger Sicht zum Schmunzeln ein und kratzen deshalb an dem ansonsten dreckig-trashigen Film, der zudem einen nicht bei den Farben stehen bleibenden Hang zur Surrealität aufweist.

Eine wilde Melange zwischen Tarantino und Lynch, wie [Roger Ebert](http://rogerebert.suntimes.com/apps/pbcs.dll/article?AID=/19950428/REVIEWS/504280301/1023) schreibt, der jedoch leider die Spannung abgeht und die es einem erschwert, bis zum Ende durchzuhalten. Kann man mal gesehen haben, muss man aber nicht.

