---
title: "Terry Pratchett & Manhattan - eine glücklose Verbindung"
date: "2010-05-02T22:41:39"
categories: [gefunden]
---

Konstanz war noch nie die Stärke bei den Veröffentlichungen der Terry-Pratchett-Bücher in Deutschland. Zuerst fristeten die Scheibenweltromane ein Schattendasein in Goldmanns Paperback-Abteilung; ab 2000 folgten dann endlich Hardcover-Ausgaben bei Manhattan. Diese erschienen mit 200 bis fast 500 Tagen Verspätung zur Originalveröffentlichung und wechselnden Covern - anfangs noch mit den guten Josh-Kirby-Illustrationen, nach dessen Tod mit den englischen Paul-Kidby-Fronten und zuletzt mit den simplen amerikanischen Versionen.

Ab 2007 durfte der oftmals gescholtene Andreas Brandhorst nicht mehr die Übersetzung übernehmen, doch mit keinem seiner [Nachfolger](/blog/2009/05/08/eine-insel/) wurde Manhattan richtig glücklich und so wechselte diese Rolle mit jedem Roman. Nach der zeitgleichen englischen und deutschen Veröffentlichung von [Schöne Scheine](/blog/2007/10/14/schone-scheine/) nahmen die Zeiträume zwischen Original und Übersetzung wieder zu und mit *The Unseen Academicals* (deutsch: *Der Club der unsichtbaren Gelehrten*), das [für den 27.09.2010 angekündigt](http://www.randomhouse.de/book/edition.jsp?edi=275310) ist, ist Manhattan zurück in gewohnten Regionen von fast einem ganzen Jahr Verzögerung.

Nach neun Hardcover-Ausgaben ist mit *Der Club der unsichtbaren Gelehrten* zudem die Ära der von mir geschätzten Festeinbände zu Ende; das Buch erscheint nur noch als Paperback mit Klappenbroschur und einem eigenem deutschen Titelbild, das nur wenig von der amerikanischen Version abweicht. Der neue Übersetzer heißt Gerald Jung und bringt Fantasy-Erfahrung mit; ein erneuter Stilwechsel ist aber wahrscheinlich. Für mich heißt dies, dass ich mir trotz des miesen englischen Papiers das Original von Doubleday zulege, denn diese Spielereien des Verlags mache ich nicht mehr länger mit.

Bessere News gibt es dagegen von der neuen Sky-Verfilmung [Going Postal](/blog/2005/09/04/ab-die-post/), die für diesen Mai angekündigt ist und mit einem [Trailer](http://sky1.sky.com/Going-Postal-new-trailer) beworben wird.
