---
title: "Somewhere"
date: "2011-04-25T01:27:26"
categories: [gesehen]
---

Johnny Marco ist Hollywoodschauspieler. Sein Leben spielt sich ab zwischen Partys in seinem Hotelzimmer, Presseauftritten, Preisverleihungen in Italien und Sex mit ständig wechselnden Frauen, die ihm meist später direkt oder per SMS mitteilen, wie schlecht er war. Abwechslung bringt da nur seine 11jährige Tochter Cleo, die ihn plötzlich für zwei Wochen begleiten muss, weil ihre Mutter sich eine Auszeit nimmt. Als Johnny Cleo schließlich nach dieser Zeit im Tenniscamp abliefert, wird ihm plötzlich überdeutlich, wie leer sein Starleben doch eigentlich ist.

Sofia Coppola versucht sich in *Somewhere* ein wenig daran, das Erfolgsrezept von *Lost in Translation* neu aufzukochen. Johnny verbringt den Großteil seiner Zeit in einem anonymen Hotel, in dem wechselnde halbnackte Models das Nachbarzimmer bevölkern und ist ansonsten ferngesteuert durch seine Managerin, die der Zuschauer immer nur durch den Telefonhörer mitbekommt. Stoisch lässt Johnny dies alles über sich ergehen, aber der Reiz der Partys, schnellen Autos und schönen Frauen ist längst verflogen in all dem Überfluss, der ihm serviert wird, und hat Platz gemacht für eine kleine Paranoia. Diese kalte, oberflächige Seite von L.A. kennt Sofia Coppola als Tochter von Francis Ford Coppola sicherlich zur Genüge, so dass der Film mit der Rolle der Cleo vermutlich autobiografisch angehaucht ist.

Dies rechtfertigt jedoch nicht die enorm in die Länge gezogenen und damit ermüdenden Einstellungen, die die Einsamkeit von Johnny verbildlichen sollen. Allein die ersten drei Minuten des Films sieht der Zuschauer nur in schmalem Blickwinkel auf eine Rennstrecke, auf der Johnny meist außerhalb der Kamera seine Runden dreht. Das Leben als sinnentleerte, sich im Kreise drehende Rennfahrt, die doch in den immergleichen Bahnen abläuft. Fast vierzig Minuten später kommt mit Cleo endlich Bewegung in Johnnys Leben und damit auch in den Film, die Einstellungen werden kürzer, die Kamera wird beweglicher und die Dialoge lebendiger. Am Ende steht die Erkenntnis, dass dies das bessere Leben ist, als bei der Verabschiedung erstmals die Emotionen der Tochter hervorbrechen, für die das Leben des Vaters zwar aufregend ist, die aber schneller als er die Leere hinter der High-Society-Fassade erkannt hat und die Wärme dahinter vermisst. Doch da ist der Film auch schon zu Ende und hat außer dem Weg zur Erkenntnis nichts mehr zu sagen.
