---
title: "An der Saale breitem Strande"
date: "2011-01-29T11:31:11"
categories: [gedacht,gefunden]
---

*... stehen Industrieanlagen stolz und kühn.*

Mit diesem leicht abgeänderten Text eines altes Volkslied kann man die Sichtweise von Manfred Sprinzek, Präsident des *Vereins zur Hebung der Saaleschifffahrt e.V.*, beschreiben. Dieser betreibt seit 15 Jahren Lobbyarbeit für die [im Verein versammelten Firmen](http://www.saaleverein.de/der-verein/mitglieder-und-sponsoren/) mit dem Ziel, die Saale zu einer ganzjährig befahrbaren Wasserstraße für Containerschiffe auszubauen. Dabei kann er persönliche Erfolge wie den [Ausbau des Hallenser Hafens ("ein Hafen ohne Schiffe")](http://www.dradio.de/dkultur/sendungen/laenderreport/823026/) und viele Bauprojekte entlang der Saale zur Verbesserung der Schiffbarkeit vorweisen. Doch eine Wasserstraße ohne direkten Zugang zu einem Seehafen nützt nur, wenn sie durchgängig befahrbar ist, und da hapert es momentan an den letzten Kilometern der unteren Saale kurz vor der Mündung in die Elbe.

Über den Ausbau dieser letzten Kilometer bzw deren Umgehung mittels eines [Kanals](http://de.wikipedia.org/wiki/Saalekanal) wird nun schon seit über zwei Jahren erbittert gestritten. Sprinzek hat es geschafft, das Verkehrsministerium des Landes mit seiner Argumentation zu überzeugen, die Binnenschifffahrt in Sachsen-Anhalt als Alternative zum Gütertransport auf Schiene und Straße aufzustellen. Als Gegenspieler hat sich [Ernst Paul Dörfler](http://www.elbeinsel.de/06kontakt.html) positioniert, der seit Jahren gegen des Ausbau der Elbe kämpft. Als Argument auf seiner Seite wird vor allem genannt, dass die Elbe aufgrund ihrer wechselnden Pegelstände selber keine ganzjährige Beschiffbarkeit aufweist, so dass die großen Containerschiffe gar nicht erst zur Saale kommen.

Nun hat sich aber das Bundesverkehrsministerium als wichtigster Geldgeber [in die Diskussion eingemischt](http://www.mz-web.de/servlet/ContentServer?pagename=ksta/page&atype=ksArtikel&aid=1296110199183&openMenu=1013016724285&calledPageId=1013016724285&listid=1018881578312). Dort soll nach neoliberaler Denkweise nur noch gefördert werden, was ohnehin schon wirtschaftlich arbeitet. Und dies sind in erster Linie die westdeutschen Wasserwege, auf Saale und Elbe gehen die Transportzahlen seit Jahren auf niedrigem Niveau sogar zurück. Damit würde sich der Saaleausbau nicht nur in seiner Umweltverträglichkeit, sondern ganz klar auch wirtschaftlich disqualifizieren.

Aus meiner Sicht sollte von einem weiteren Ausbau der Saale abgesehen werden. Halle hat das diesjährige Hochwasser wie auch viele zuvor gut überstanden, weil im Bereich der natürlichen Überschwemmungsgebiete der Saaleaue so gut wie keine Gebäude stehen. Ein begradigender Ausbau von Flüssen und Einschnitte in die Auen sind deshalb aus Sicht des Hochwasserschutzes negativ zu sehen. Für die Verlagerung von wenigen Tonnen Gütertransporte auf den sicherlich ökologisch sinnvollen Wasserweg müssten dann vielleicht viele Menschen entlag der unteren Saale und der Elbe die Konsequenzen tragen. Dieses Risiko sind die geringen wirtschaftlichen Erfolgsaussichten nicht wert, auch wenn ich die Denkweise des Bundesverkehrsministeriums nicht unterstütze.
