---
title: "Snuff"
date: "2012-02-04T19:58:28"
categories: [gelesen]
---

*von Terry Pratchett,
veröffentlicht von Doubleday, ISBN 978-0-385-61926-4, 18.99£*

Sam Vimes (Mumm im Deutschen) steht vor der größten Herausforderung seiner Karriere: Seine Frau Sybil und Lord Vetinari haben beschlossen, dass der Chef der Stadtwache endlich einmal Urlaub machen soll. Also ist er gezwungen, mit Sybil und Sohn Sam auf den Landsitz zu fahren, auf dem seine adelige Frau einst aufwuchs. Der Stadtmensch Mumm findet es anfangs schwer, sich mit der Natur und den Verhaltensweisen der Landbevölkerung anzufreunden, doch dann schlägt sein untrüglicher Polizeisinn zu: Irgendetwas ist faul in dem kleinen Dorf, wo der örtliche Polizist nicht etwa dem Gesetz, sondern den Ratsmitgliedern verpflichtet ist. Als plötzlich der Schmied verschwindet und versucht wird, Sam den Mord an einem Goblinmädchen anzuhängen, ist es endgültig aus mit der beschaulichen Urlaubsruhe...

Trotz fortschreitender Alzheimer-Erkrankung läuft der Büchermotor von Terry Pratchett weiter rund und so ist Ende 2011 mit *Snuff* ein weiterer Scheibenwelt-Roman erschienen. Doch seit einigen Jahren ist die Vorfreude meinerseits nicht mehr so groß wie früher, weil sich die immergleichen Themen im Kreise drehen und ich mich sattgelesen habe an der Stadtwache, von der auch *Snuff* handelt. In dem übergreifenden Handlungsfaden ist einfach die Luft raus; mit jedem Buch wird nur noch eine weitere Spezies integriert (diesmal Goblins - wie innovativ) und dies läuft in gewohntem Schema F ab.

Dazu macht es das Buch dem Leser zu Beginn nicht gerade leicht. Vermutlicht um das ruhige Landleben zu verdeutlichen beginnt es sehr zaghaft, so dass auf den ersten 100 Seiten so gut wie keine Handlung vorhanden ist, geschweige denn ein Hinweis, worum es eigentlich geht. Da auch die bei Pratchett üblichen Nebenhandlungen erst in der Mitte des Buches einsteigen, sich alles auf Sam Mumm konzentriert und der Humor weitgehend fehlt ([Stolz und Vorurteil](http://de.wikipedia.org/wiki/Stolz_und_Vorurteil) wird anekdotenhaft aufgegriffen), war es anfangs eher eine Qual als ein Vergnügen, *Snuff* zu lesen.

Irgendwann wird klar, dass Sam Mumm auf eine Schleuserbande gestoßen ist, die Goblins entführt, damit diese als billige Arbeitskräfte auf Tabakplantagen schuften. Zusammen mit einer wilden Verfolgungsjagd auf einem Fluss sollte dies eigentlich für eine interessante Geschichte reichen, doch leider clasht sich der Inhalt mit der eingefahrenen Erzählweise und Charakterisierung von Pratchett - es fehlt einfach an Konflikten. Von Anfang an ist klar, dass niemand Sam Mumm gewachsen ist. Er kennt alle Leute und Situationen, gewinnt alle Kämpfe (die Prügelei am Anfang mit dem Schmied ist an den Haaren herbeigezogen); zur Not schreitet eben sein Butler oder seine Frau ein. Das ist langweilig, langweilig, langweilig.

Es fehlt an einem potenten Gegenspieler. Die Mitglieder des Dorfrates als Strippenzieher bleiben durchgängig im Hintergrund und scheiden deshalb aus. Der Leiter der Goblinverschleppung wird erst in der Mitte der Buches kurz aufgebaut und - trotz eines Nachschlags - schnell abserviert und entfaltet so niemals wirklich Gefahr. So verbleibt als einziger zählbarer Konflikt der innere Disput von Hauptmann Mumm über sein verbildlichtes dunkles Ich und die Mittel, mit denen er teilweise seine Ziele erreicht.

Diese immer wieder ab der Oberfläche hervorbrechenden Irritationen sind die Highlights des Buchs und stehen in einer Linie mit den humanistischen Aussagen der Scheibenweltbücher, die ich voll und ganz unterstütze. Schade nur, dass sich *Snuff* im Gegensatz zum klaren Statement gegen Arbeitssklaverei einer eindeutigen Aussage zu Mumms fragwürdigem Vorgehen verwehrt.
