---
title: "Wall on Wall"
date: "2013-06-29T18:00:37"
categories: [gefunden]
---

Vor ein paar Monaten habe ich bei einer [Kultursendung im ZDF](http://aspekte.zdf.de/ZDF/zdfportal/programdata/c736b822-1406-36dd-bbf3-bd196f7c161a/20066070) einen Bericht über den Fotographen Kai Wiedenhöfer gesehen. Der Berliner verbrachte die vergangenen Jahre mit dem Langzeitprojekt, Grenzmauern in aller Welt auf Fotos zu dokumentieren (u.a. den Zaun an der amerikanisch-mexikanischen Grenze und die Friedenslinie in Belfast). Für mich spannend war vor allem der Ansatz, mit einer [Panorama-Film-Kamera aus den 90er Jahren](http://www.hasselbladpages.com/xpan.html) zu arbeiten. Das ungewöhnliche Filmformat (17:6) hat einen großen Einfluss auf die Bildkomposition und spiegelt die [Mauer-Motive](http://www.wallonwall.org/?p=53) in ihren Ausmaßen gut wieder.

In seiner Heimatstadt mit ihrer Mauervergangenheit hat Wiedenhöfer nun das tolle Projekt [Wall on Wall](http://www.wallonwall.org/) gestartet, für das ich hiermit Werbung betreiben möchte. Er hat es geschafft, die East-Side-Gallery als öffentliche Ausstellungsfläche für seine Mauerpanoramen zu gewinnen. Der Wahnsinn von Grenzzäunen abgebildet auf einer der verrücktesten Grenzen des letzten Jahrhunderts! Die Kosten für das Projekt wurden dabei per [Kickstarter](http://www.kickstarter.com/projects/701554058/wallonwall-a-photo-exhibition-on-the-berlin-wall) finanziert.

Ab 10. Juli kann jeder Interessierte die [Fotoausstellung](http://berlin-fotofestival.de/blog/2013/06/25/festival-highlight-wall-on-wall-eroffnung-10-juli/) kostenlos besichtigen. Ich werde sie mir auf jeden Fall ansehen und kann dies jedem Foto- und Panoramafreund nur empfehlen!
