---
title: "Lieber ein Ende als gar keins"
date: "2008-08-04T22:37:05"
categories: [gedacht,gesehen]
---

Da hat man ein schönes Wochenende, kommt am Sonntagabend nach Hause und will einen der Filme schauen, den der DVD-Rekorder während der Abwesenheit aufgenommen hat. Es läuft alles prima, die Sex-Hotline-Werbung der Nacht-Wiederholung wird routinemäßig überspult, und dann, wahrscheinlich fünf Minuten vorm Schluss, ist plötzlich die Aufnahme zu Ende. Und ich weiß nicht, wie *Shaun of the Dead* nun ausgegangen ist. Immer diese Privatsender und ihr falsches VPS-Signal!

Dann heute der nächste Versuch; *High Fidelity* auf einem anderen Sender der Kölner TV-Gruppe aufgenommen. Eine interessante Liebeskomödie (sonst eher nicht mein Fall), bei der englischer Charme dank der Romanvorlage von Nick Hornby, Popkultur in Form von zeitgenössischer alternativer Musik und amerikanische Schauspieler (u.a. Jack Black) eine selten gesehene Verbindung eingehen. Es ist kurz vorm Ende des Films, er stellt ihr die Frage, ob sie seine Frau werden will - und plötzlich wieder Schluss mit der Aufnahme.

Zwei Filme. Kein Ende. Drei Stunden investiert, und nun? Zur Videothek rennen, um die Finals nachzuholen? Darauf warten, den Kumpel wieder zu treffen, der wahrscheinlich beide irgendwo in seiner Sammlung stehen hat? Und bis dahin die Hälfte der Filme schon wieder vergessen zu haben? Life ain't easy!

**Update #1**
Eine Lösung ist immer, sich von Kollegen das Ende erzählen zu lassen. Dabei fehlt zwar meist der Stil des Originals, auf Vollständigkeit darf man auch nicht hoffen, aber wie der Titel schon sagt: Besser ein Ende als gar keins. Und ich mache jetzt einen Haken hinter *Shaun of the Dead*.

**Update #2**
Auch *High Fidelity* hat mir nun sein Ende offenbart inklusive einer Gesangseinlage von Jack Black. Dank der DVD bekam ich zusätzlich noch die herausgeschnittenen Szenen zu sehen und bin weiterhin sehr zufrieden mit dem Film. Denn Enden gut, alles gut!
