---
title: "Terminator 3 - Rebellion der Maschinen"
date: "2003-08-25T00:00:08"
categories: [gesehen]
---

*USA (2003)
Regie: Jonathan Mostow
Darsteller: Arnold Schwarzenegger (T-850), Nick Stahl (John Connor), Claire Danes (Kate Brewster), Kristanna Loken (T-X), David Andrews (Robert Brewster), Mark Famiglietti (Scott Petersen), Earl Boen (Dr. Peter Silberman) und andere Opfer der Apokalypse*
[Offizielle Homepage](http://www.terminator-3.de/)

John Connor muss mit einer schweren Bürde leben: Zweimal schon haben Killerroboter aus der Zukunft, genannt Terminatoren, versucht ihn und seine Mutter zu töten. Und dies nur, weil John angeblich nach der atomaren Apokalypse der Anführer der Widerstandsbewegung gegen die Herrschaft der Maschinen wird. Doch obwohl der prophezeite Tag des jüngsten Gerichts nie eingetroffen ist, lebt John allein und von alptraumhaften Visionen geplagt im Untergrund. Dummerweise läuft er bei der Beschaffung von Drogen genau der neusten Killermaschine über den Weg, die mal wieder versuchen soll die Führungskräfte der späteren Maschinengegner zu eliminieren. Aber auch dieser Widerstand der Zukunft sendet erneut einen Beschützer für John: Den Terminator T-850, der sich durch einen erfolgreichen Mord im Jahre 2035 für diesen Job "beworben" hat und nun umprogrammiert John und seine spätere Frau Kate Brewster an einen sicheren Ort eskortieren soll. Was John nicht weiß ist, dass Kates Vater der Chefentwickler von "Skynet" ist, jener Maschine welche bald die Kontrolle über die atomaren Waffen der USA übernimmt und den Weltuntergang einleiten wird...

Im Kinosommer der Fortsetzungen tritt nun zur Abwechslung mal der dritte Teil einer Serie an. Terminator 1 war mit seinem geringen Budget die Eintrittskarte nach Hollywood sowohl für Hauptdarsteller Arnold Schwarzenegger als auch Regisseur James Cameron; Teil 2 schließlich setzte die erste Messlatte für CGI-Effekte in Actionfilmen. 10 Jahre später nun hat es Cameron nicht mehr nötig, einen weiteren Terminator zu drehen - nach "Titanic", dem erfolgreichsten Film aller Zeiten, kann es nur bergab gehen - doch Schwarzenegger braucht endlich mal wieder einen Erfolg, wenn er weitere Filme rechtfertigen will. Also wurde wieder 6 Stunden täglich trainiert, um dem Terminator die nötige Statur zu bieten, und ein willigerer Regisseur gefunden und los gehen konnte es mit dem vorprogrammierten Erfolg.

Terminator-typisch fängt alles mit der Ankunft des neuen Modells aus der Zukunft an, diesmal einer "Terminatrix", die mit ihrem Aussehen das männliche Publikum in Scharen ins Kino locken soll. Dazu passen auch das enganliegende Lederoutfit und der "Gag" mit dem aufpumpenden Busen. Schauspielerische Leistungen waren dafür nicht erforderlich - ein Roboter hat halt nur einen Gesichtsausdruck.

Als nächstes folgt erwartungsgemäß die Ankunft des Verteidigers Arnie himself, der sich zumindest einer kleinen Weiterentwicklung zum T-850 erfreuen darf, was es dem Regisseur ermöglicht, Dialoge und Erklärungen aus T2 zu recyclen und diese mit den typischen Gags aufzulockern. Ansonsten ist die alte Version nach dem Datenblatt wieder hoffnungslos dem neuen Modell unterlegen, was aber im Laufe des Films zunehmend an Bedeutung verliert, da die T-X ihre tollen Waffen zum Einen kaum einsetzt und zum Anderen auch kaputt macht - der T-1000 aus Teil 2 erschien da viel gefährlicher. Stattdessen lässt der Regisseur die beiden Maschinen in einem Pattspiel sich gegenseitig mit Pick-Ups, Hubschraubern und Kranwagen überrollen und zerstört so nebenbei eine Herrentoilette, einen Friedhof und einen längeren Straßenzug in L.A. inklusive einiger Gebäude. Nach den vielen Martial-Arts-inspirierten Actionfilmen der letzten Zeit kommt der neue Terminator da angenehm bodenständig daher, wenngleich Jonathan Mostow nach "Breakdown" auch in diesem Film den Schwerpunkt auf Straßen-Verfolgungsjagden legt.

Neben den beiden Maschinen agieren die anderen Hauptdarsteller Nick Stahl und Claire Danes eher unglücklich. Während der schmächtige Stahl (wer sieht neben Arnie nicht schmächtig aus?) in keiner Sekunde glaubhaft machen kann, dass er einmal die Menschheit gegen die Maschinen anführen soll, beschränkt sich Danes Rolle darauf, am Anfang ordentlich zu kreischen und nach einer beispiellos kurzen Phase sich mit der Situation abzufinden und mal schnell eine Maschine mit der Schnellfeuerwaffe vom Himmel zu holen. Neben dieser schwachen Charakterzeichnung enthält auch die Story Logiklöcher, dass man sich darin verlaufen kann - der Schwerpunkt wurde ganz klar auf Action gelegt und sehr viel mehr hatte ich von diesem Film auch nicht erwartet.

Dass er trotzdem positiv aufgefallen ist liegt zum Einen daran, dass diesmal nicht dieselbe Geschichte zum dritten Mal erzählt wurde. Der Regisseur spielt vielmehr mit den Terminator-typischen Elementen wie den Blenden in die Zukunft mit der Roboterarmee, deren Flugzeugen und den Widerstand leistenden Menschen und fügt auch ein paar eigene Bilder hinzu, wie zum Beispiel den schönen Kontrast mit den menschlichen Schädeln, die den Grund des Flusses bedecken und am Ende durch Roboterschädel ersetzt werden oder den Vorgängermaschinen T1. Und dann wurde zu meiner Überraschung auch die Trilogie zu einem Ende geführt, denn diesmal stirbt nicht der Terminator am Ende in irgendeiner Schmelze oder Schrottpresse sondern tritt die eigentlich schon längst überfällige Apokalypse ein. Dies führt zu der starken letzten Szene in dem gespenstig leeren Atom-Bunker aus den 60ern, wo John und Kate nicht wie erwartet "Skynet" finden. Dieser Kontrast zu dem brennenden und von Robotern bevölkerten Waffenlabor lässt den Zuschauer wie die Charaktere inne halten bevor dann endlich die schreckliche Gewissheit kommt: Trotz aller Anstrengungen ist der Versuch gescheitert, die atomare Katastrophe zu verhindern. All die Hoffnungen, die in Terminator 2 geschürt wurden, dass die Zukunft schließlich beeinflussbar und damit veränderlich ist, wenn man um sie Bescheid weiß, müssen an dieser Stelle begraben werden und John muss sich schlussendlich seinem zu Beginn der Trilogie prophezeiten Schicksal stellen.

Dieses doch eher negative Bild über den Einfluss des Einzelnen auf die Gestaltung der Zukunft zeigt zwar deutlich die Auswirkungen der Bush-Administration auf die Film-Branche ("Ihr niederes Fußvolk könnt nichts daran ändern aber es wird ein Kriegsheld kommen und Euch in den großen Kampf führen"), bringt die Terminator-Reihe aber zu einem relativ stimmigen Abschluss (oder doch nicht?) und mich zu einem

Fazit: Terminator 3 ist ein mittelmäßiger Action-Film der alten Schule, der aber durch die Variation der Vorgänger und indem er die Trilogie zu einem passenden Ende bringt seine Existenzberechtigung mehr als verdient!
