---
title: "The Others"
date: "2002-02-20T00:00:35"
categories: [gesehen]
---

*Frankreich/Spanien/USA (2001)
Regie: Alejandro Amenábar
Darsteller: Nicole Kidman (Grace), Fionnula Flanagan (Bertha Mills), Alakina Mann (Anne), James Bentley (Nicholas), Eric Sykes (Edmund Tuttle), Elaine Cassidy (Lydia), Christopher Eccleston (Charles) und ein paar Lebende*
[Offizielle Homepage](http://www.theothers-derfilm.de)

Die Kanalinseln direkt nach dem 2.Weltkrieg: Der Ehemann von Grace ist von der Front nicht zurückgekommen und so muss sie allein das alte viktorianische Anwesen hüten und sich um die beiden Kinder kümmern, die sich aufgrund einer extremen Sonnenallergie nie direktem Sonnenlicht aussetzen dürfen. Deshalb müssen in jedem Zimmer die Vorhänge und die Türen geschlossen bleiben um die Gesundheit der Kinder nicht einer Gefahr auszusetzen. Auch die 3 neuen Bediensteten haben sich dem unterzuordnen, doch mit deren Anstellungen halten auch seltsame Ereignisse Einzug in das Haus. Aber die streng christliche Grace will es nicht wahrhaben, was ihre Kinder über im Haus herumlaufende Menschen erzählen und die Wahrheit wird ihren Glauben auf eine harte Probe stellen...

Wichtig: Ich werde hier keinerlei Rücksicht auf eventuelles spoilern nehmen, wer sich den Film also noch ansehen will: Bitte nicht weiterlesen!

Ich bin nur aus einem einzigen Grund 23 Uhr in diesen Film gegangen: Um mich mal wieder richtig zu gruseln. Und genau das hat er auch geschafft, nämlich mir diese unangenehmen Schauer über den Rücken zu jagen und vom Sitz aufschrecken zu lassen. Denn dies ist die Stärke von The Others - seine ständig alles umhüllende Atmosphäre, die nur von den sorgsam eingestreuten Schockeffekten duchbrochen wird bzw. den Boden dafür bereitet. Dem Regisseur gelingt es spielend, die Spannung über die gesamte Zeit hinweg aufrecht zu halten. Dabei greift er auf bewährte und altbekannte, aber immer wieder wirksame Mittel zurück: Das ständig im Dunkeln gehaltene Haus mit den gespenstische Schatten werfenden Öllampen, der erdrückende Nebel in den Außenszenen, verschrobene Menschen, die scheinbar immer mehr wissen als der Hauptakteur. Dabei sieht man im gesamten Film keinen einzigen Tropfen Blut, die Situationen werden jeweils aus der Sicht der Betroffenen gezeigt, der Zuschauer ist gezwungen, mit ihnen alles zu erleben und vor allem zu fühlen!

Getragen wird dieses Kammerspiel von den Darstellern. Alakina Mann brilliert als Tochter, die am Besten mit den Vorfällen klarkommt und als Erstes die richtigen Schlüsse zieht, aber die traurige Wahrheit dann doch nicht wahrhaben will. Und Fionnula Flanagan ist sofort die Chefin im Haus, sowohl die Kinder als auch Grace suchen ihre Nähe in schwierigen Situationen; sie verkörpert den ruhenden Pol und doch kann man es in ihren Augen lesen, daß sie mehr weiß als sie verrät (und am Ende auch reichlich gespenstisch auszusehen vermag!). Und dann wäre da noch die schwerste Rolle des Films, die nach außen hin so starke Grace, die jedoch innerlich ein Wrack ist. Stark gläubig musste sie die Besetzung der Deutschen ertragen und dabei ihr Leben nach den Kindern ausrichten, um für deren Gesundheit zu sorgen - und all dies ohne den starken Mann an ihrer Seite, der sie aufzubauen vermag. Nicole Kidman nimmt man dabei jede Emotion der Grace wirklich ab und auch die Auflösung, die leider gleich dem Ende von "The Sixth Sense" und deshalb allzu vorhersehbar ist, passt da perfekt in das Bild und wie immer in solchen Filmen macht plötzlich alles Sinn.

Fazit: Ein handwerklich perfekter Gespensterfilm für alle, die sich im Kino mal wieder so richtig gruseln wollen. Wer jedoch nicht bereit ist, sich darauf einzulassen und stattdessen eine rasante Story mit mächtig Splattereffekten erwartet, der ist mit diesem Film der klassischen Art falsch bedient!
