---
title: "Hellboy II - Die goldene Armee"
date: "2008-10-24T20:19:05"
categories: [gesehen]
---

*USA (2008)
Regie: Guillermo Del Toro
Darsteller: Ron Perlman (Hellboy), Selma Blair (Liz Sherman), Doug Jones (Abe Sapien), Luke Goss (Prinz Nuada), Anna Walton (Prinzessin Nuala), James Dodd / John Alexander (Johann Krauss), Jeffrey Tambor (Tom Manning) und viele bunte Comic-Kreaturen*
[Offizielle Homepage](http://www.hellboy-film.de/)

Der letzte Film von Guillermo Del Toro, *Pans Labyrinth*, war verdient einer der großen Abräumer der Oscar-Verleihung 2007 und mein persönlicher Favorit des letzten Jahres. Während der Regisseur dort eine grausame Realität mit einer nicht minder gefährlichen Fantasiewelt kombinierte, ließ er in der Comic-Adaption *Hellboy* zwei Jahre vorher einen rothäutigen Helden aus der Hölle mit steinerner Faust sich mit Fabelwesen, Dämonen und Nazis prügeln. Dies war ebenso originell wie unterhaltsam, so dass man mich nicht lange überreden musste, für den zweiten Teil das Kino aufzusuchen.

Diesmal gibt es keine direkte Vorlage aus der Feder des Hellboy-Schöpfers Mike Mignola, doch zusammen mit Del Toro hat er ein Drehbuch entwickelt, in welchem es der rote Antiheld mit dem Prinzen der Elfen zu tun bekommt. Dieser will die titelgebende mechanische Armee wieder zum Leben erwecken, um den Frieden zu brechen, den die Menschen einst mit seiner Spezies geschlossen haben. Die Menschheit hat dies natürlich längst vergessen und benötigt dringend die Hilfe der Behörde zur Untersuchung und Abwehr paranormaler Erscheinungen um Hellboy.

Was sich zuerst wie die übliche Melange aus naturliebenden Elfen und der die Erde zerstörenden Menschheit anhört, verläuft doch in den ganz eigenen Bahnen der Hellboy-Welt. Nichts entwickelt sich so, wie es zuerst den Anschein hat. Dies fängt an bei Hellboys neuem Vorgesetzten, dem nur noch als Geist existierenden Johann Krauss. Als typischer Deutscher eingeführt (Springerstiefel) und mit allerlei Witzen darüber bedacht (ich muss gestehen, ich mag diesen Nazi-Trash-Humor), steht er am Ende doch auf der Seite der Außenseiter und unterstützt den roten Anti-Helden. Zahnfeen sind eigentlich menschenfressende und vor allem schnellverdauende kleine fliegende Biester und Trolle vernaschen gerne Katzen, was Hellboy natürlich nicht zulassen kann. Da passt es ebenso ins Bild, dass der im ersten Teil noch eine Hauptrolle spielende John Myers in einem Nebensatz (in die Arktis versetzt) abgehandelt wird.

Faszinierend ist erneut die visuelle Wucht des Films. Dafür sind weniger die animierten Szenen verantwortlich wie die goldene Armee am Ende oder der Steingolem, der den Eingang zu deren Versteck darstellt, sondern die vielen Figuren, die in Nebenrollen oder einfach nur im Hintergrund der Szenen das Bild beleben. Allen gemein ist die Liebe zum Detail, sei es nun der Kopf des Tresorverwalters mit der Stadt darauf, die in den Flügeln sitzenden Augen des Todesengels oder das Kind an der Brust eines Monsters auf dem Trollmarkt, dass sich selbst als Tumor bezeichnet. Hier hat der Regisseur einen ganz eigenen Stil mit hohem Wiedererkennungswert entwickelt.

Die augenzwinkernde Action wird dagegen dosiert eingesetzt, und das tut dem Film ganz gut. Viel wichtiger sind die Figuren, und denen wird genügend Zeit gewidmet. Denn auch Comicwesen wie Höllenkinder oder Elfenprinzessinnen haben private Probleme, und so bekommt der Zuschauer Hellboy und Abe besoffen Liebeslieder singend zu Gesicht und darf sich schon einmal Gedanken machen, ob die Kinder von Liz und Hellboy nun rote Steinfäuste haben oder ständig in Flammen aufgehen. Hinter der ironischen Fassade bleibt jedoch von den Charakteren und der Story nicht viel übrig, doch so einen Anspruch hat *Hellboy* auch nicht - er will unterhalten und faszinieren, und das tut er auf ganzer Linie.

Fazit: Noch bunter und fastasievoller als der erste Teil ist *Hellboy II* ein sehr unterhaltsamer Film, der einfach funktioniert. Witz und Action ergänzen sich prächtig und visuell erschlägt er den Zuschauer zeitweise. Dafür darf man aber auch keine tiefgründigen Charaktere oder eine ausgefeilte Story erwarten, selbst wenn diese ironisch mit den Konventionen des Genres spielt.
