---
title: "Bis ich Dich finde"
date: "2006-02-09T20:42:37"
categories: [gelesen]
---

*von John Irving,
erschienen im Diogenes Verlag, ISBN 3-257-06522-1, 24,90€*

Ein Teil von John Irving steckte schon immer in den Hauptcharakteren seiner Bücher. Doch mit der Lebensgeschichte von Jack Burns hat sich der Autor fast eine Biografie auf den Leib geschrieben. Denn auch John Irving wurde, wie er auf seiner Promotiontour für das Buch immer wieder betont, als Kind von einer älteren Frau missbraucht. Ich bin mir zwar nicht sicher, ob dieses neue Kapitel im Leben von John Irving nicht nur Marketing ist - sexuelle Erfahrungen von Kindern und jungen Jugendlichen sind schließlich in fast jedem Irving-Werk ein Thema, und auch das Interesse an älteren Frauen wurde nicht zum ersten Mal behandelt. 

Doch in keinem Buch zuvor gab es eine solche Verdichtung von biografischen Einflüssen. Das gesamte Leben von Jack Burns schlängelt sich entlang des Lebensweges des Autoren: Er beginnt als Jugendlicher mit dem Ringen, besucht Exeter und die Universität von New Hampshire und lernt Deutsch als Fremdsprache. Sogar seinen Oscar für die Drehbuchadaption eines Romanes hat John Irving dem Schauspieler angedacht. Nur am Ende darf Jack Burns seinen leiblichen Vater wiedersehen. Dies blieb Irving verwehrt, doch ebenso wie sein Held kennt er inzwischen die anderen Kinder seines Vaters.

Der Roman hangelt sich zudem an sehr vielen anderen realen Schauplätzen und Ereignissen entlang. Viele Figuren des Buches gibt es auch in Wirklichkeit und wurden von Irving während seiner Recherchen interviewt, worüber mich die Danksagungen am Ende der 1140 Seiten aufgeklärt haben (und ein Bericht über Herbert Hoffman im Boulevard-Fernsehen). Und die ausführlichen Beschreibungen des Rotlichtviertels von Amsterdam kennt der Leser vielleicht schon aus der "Witwe für ein Jahr". 

Doch leider fehlt "Bis ich Dich finde" etwas der durchgehende rote Faden. Jack Burns ist Zeit seines Lebens ein Spielball anderer Personen: Angefangen bei seiner Mutter über Emma Oastler bis hin zu seinem Vater hat fast jeder Mensch um den Schauspieler herum diesen von ihm teilweise unbemerkt manipuliert, was sich vor allem in seiner Jugend in vielen Komplexen äußert. Dann stellt sich der ganze erste Abschnitt des Romans, welcher sich in der Kindheit des Buchhelden abspielt, auch noch als eine einzige große Lüge seiner Mutter heraus. John Irving macht es dem Leser wirklich nicht einfach, seinen Helden zu verstehen. Auf der anderen Seite ist die zweite Reise durch Europa auf den Pfaden seiner Mutter der interessanteste Teil des Buches, da der Charakter viele wichtige Erfahrungen macht und sichtbar reift.

Während aber "Witwe für ein Jahr" glücklicherweise viele Lebensabschnitte der Heldin Ruth Cole auslässt, erzählt Irving auch die weniger wichtigen Episoden in der Biografie von Jack Burns. Zusammen mit den vielen Details und Nebencharakteren stellt sich das Buch wie eine Achterbahnfahrt ohne Ziel dar. Dadurch, dass auch der Held eigentlich nie auf der Suche nach seinem Vater ist, ahnt der Leser zwar, dass sie sich doch noch treffen. Doch insgesamt will dieses Ende nicht so richtig passen, auch weil es den Charakter des Jack Burns etwas die Glaubwürdigkeit nimmt. Hier hat John Irving wie oben erwähnt die eigene Biografie um einen Wunsch erweitert, der nicht richtig in das Gesamtbild passen will - ihm blieb dieses letzte Kapitel ja auch verwehrt.

Trotzdem ist das Buch natürlich lesenswert, schon aufgrund der "verdrehten" Romanfiguren, die John Irving rund um seinen eigenen Charakter entworfen und platziert hat. Doch sein bestes Werk ist es meiner Meinung nach nicht, dafür ist "Bis ich Dich finde" zu überladen und unausgeglichen.

(gekauft habe ich das Buch übrigens schon am 21.01. in der Hallenser [Thalia](http://www.thalia.de)-Filiale - an offizielle Verkaufstarts scheint sich niemand mehr zu halten)
