---
title: "Nichtsdestotrotz"
date: "2008-05-04T13:16:48"
categories: [gedacht,gesehen]
---

Manchmal braucht es einen Stein des Anstoßes, damit man sich bewusst wird, was für Wörter man so im täglichen Sprachgebrauch nutzt. In meinen Fall war es die letzte Sendung [Lesen!](http://lesen.zdf.de/) von Elke Heidenreich, in der sich die Moderatorin über einen Übersetzer echauffierte, der das Wort **nichtsdestotrotz** verwendete - bei mir [im Blog findet man vier (ältere) Artikel](/blog/?s=nichtsdestotrotz&submit=+%3F+), die sich dieser "Sünde" bedienen. Dabei steht das Wort sogar im [Duden](http://www.duden-suche.de/suche/abstract.php?shortname=fx&artikel_id=680427330&verweis=1), auch die DDR-Ausgabe von 1981 führt es auf. Was also ist so schlimm daran?

Vermutlich sind es die Kürzel *umg* (DDR) und *ugs.* (aktuelle Ausgabe), die beide für umgangssprachlich stehen. Laut [Wikipedia](http://de.wikipedia.org/wiki/Nichtsdestotrotz) haben uns ein paar Studenten diese Wortschöpfung eingebrockt, und sie hat den Menschen so gut gefallen, dass sie immer häufiger genutzt wird. Ich persönlich kenne das Wort seit Kindheitstagen, kann aber nicht sagen, ob Eltern, Freunde, Erzieher oder Lehrer es an mich herangetragen haben. Aus einem Buch habe ich es bestimmt nicht, meint der [Zwiebelfisch](http://www.spiegel.de/kultur/zwiebelfisch/0,1518,314557,00.html):

> Im gepflegten Deutsch sind nach wie vor die Begriffe "trotzdem", "wenngleich" und "obwohl" zu bevorzugen.

Aha, daher weht also der Wind. Die Hüter der deutschen Sprache sind wieder erwacht und müssen das Deutsch vor den aberwitzigen Wortkreationen übermütiger Studenten beschützen, deren einziges Ziel es ist, unsere Muttersprache bis zur Unkenntlichkeit zu deformieren. Ich sage: Sollen sie ruhig. Wer das Wort mag, soll es gebrauchen. Denn nach einiger Zeit wandert wohl jedes Wort aus dem Bereich Umgangssprache entweder in die Ecke der vergessenen Schöpfungen oder aber in die Elite der akzeptierten deutschen Wörter.
