---
title: "Berlinale-Nachlese"
date: "2009-09-27T18:40:45"
categories: [gesehen]
---

Viele interessante Filme, die [dieses Jahr auf der Berlinale](/blog/2009/02/15/der-vorhang-ist-gefallen/) liefen, konnte ich leider nicht sehen. Bei zweien davon kam nun die Gelegenheit mit etwas Verspätung.

**The Yes Men fix the world**

lief als ARTE-Eigenproduktion vor ein paar Tagen auf eben jenem Sender. Der Film ist eine Dokumentation über zwei Anti-Globalisierungs-Aktivisten, die sich auf Konferenzen als Vertreter von bedeutenden Unternehmen oder Institutionen ausgeben. Dort halten sie entweder Vorträge, in denen sie auf extreme Art den Mechanismen des Kapitalismus den Spiegel vorhalten, oder verbreiten falsche Informationen, wie sie sich eine bessere Welt vorstellen, zum Beispiel durch Wahrnehmung der sozialen Verantwortung von Wirtschaftsunternehmen. So schafften sie es u.a. die BBC zu foppen und den Börsenkurs von Dow abstürzen zu lassen.

Zwischen den Auftritten und der meist schnell folgenden Enttarnung füttert der Film den Zuschauer mit den Informationen rund um die genarrten Firmen und geht auch den Medienberichten über ihre Aktionen nach, um die Verknüpfung zwischen der Wirtschaft und der Darstellung der Welt in den Medien zu erleuchten. Da auch die Vorbereitung der Vorträge gezeigt werden, sind diese meist nicht so lustig, wie sie sein könnten. Trotzdem musste ich manchmal schlucken, wenn ein Konferenzteilnehmer die Ironie nicht verstand und ernsthaft über die gefakten Präsentationen diskutierte.

Eine interessante Idee also, ansprechend und witzig umgesetzt. Traurig, dass die Welt Filme wie *The Yes Men fix the world* überhaupt braucht, aber schön, dass diese Form der Kritik trotzdem möglich ist und hoffentlich auch einige Augen öffnet.

**Der Knochenmann**

ist die dritte Verfilmung eines Brenner-Romans nach [Komm, süßer Tod](/blog/2006/01/05/tv-woche-nummer-1/) und *Silentium* mit dem großartigen Josef Hader. Ex-Kommissar Brenner hat es diesmal aufs Land verschlagen, wo er in eine Geschichte rund um osteuropäische Prostituierte, slowakische Zuhälter und eine verstrittene Wirtshausfamilie gerät. Ein paar gute Absichten und einen Unfall später gerät die Situation außer Kontrolle und die wilde Ansammlung von Kreinkriminellen dezimiert sich zuksessiv, während Brenner mitten drin versucht, selber am Leben zu bleiben und Birgit, die Schwiegertochter des Wirts, näher kennen zu lernen.

Wie alle Brenner-Filme ist auch *Der Knochenmann* schwarzhumorig, lebt jedoch stärker als die Vorgänger von seinen gut ausgearbeiteten Charakteren und ihren hervorragenden Darstellern. Allen voran Josef Bierbichler, der die vielen Seiten des Wirts Löschenkohl glaubwürdig auf die Leinwand bringt: Der leidenschaftliche Koch, der verliebte Mann, aber auch der resolute und eigenbrötlerische Vater; die Figur ist gleichzeitig Ruhepol und treibende Kraft des Films. Wie er versucht, aus eigener Kraft das Ruder rumzureißen, dabei in eine Spirale der Gewalt gerät und sein eigentliches Ziel in immer weitere Ferne verschwinden sehen muss, das ist großes Kino.

Hinzu kommt der ungewöhnliche, aber sehr intensive Score von den Sofa Surfers und die gelungene Kamera, die immer wieder ausdrucksstarke Blickwinkel und Einstellungen findet. Ein sehr guter Film also, den ich in Form der überzeugenden DVD allen Freunden des Kabarettisten Hader oder des schwarzen Humors ans Herz lege.
