---
title: "KILL BILL Vol. 2"
date: "2004-04-29T00:00:24"
categories: [gesehen]
---

*USA (2004)
Regie: Quentin Tarantino
Darsteller: Uma Thurman (Beatrix Kiddo/Die Braut/Die Mutter), David Carradine (Bill), Michael Madsen (Budd), Daryl Hannah (Elle Driver), Perla Haney-Jardine (B.B.), Gordon Liu (Pai Mei), Michael Parks (Esteban Vihaio), Christopher Allen Nelson (Tommy Plympton/Der Bräutigam), Samuel L. Jackson (Rufus), Jeannie Epper (Mrs. Harmony), Bo Svenson (Reverend Harmony) und andere Bewohner aus El Paso*
[Offizielle Homepage](http://www.kill-bill-2.de/)

Nachdem die Braut aus ihrem Koma wieder erwacht ist und bereits zwei ihrer ehemaligen Kollegen getötet hat (siehe [KILL BILL Vol.1](/blog/2003/10/23/kill-bill-vol-i/)), stehen noch drei weitere Namen auf ihrer Todesliste: Budd, Elle Driver und schließlich Bill. Doch leider sind diese nun vorgewarnt und so schafft es Budd die Braut zu überwältigen und in einem Sarg lebendig zu begraben...

Es gab einmal einen Künstler namens Andy Warhol, der einfach bekannte Motive der Popkultur nahm, mit simplen zeitgenössischen Mitteln verfremdete und das Ergebnis Kunst nannte: Die Popart war geboren. Auch Quentin Tarantinos Werke zeichnen sich nicht gerade durch innovative Ideen aus, vielmehr kombiniert er Versatzstücke aus verschiedensten Filmen und erschafft damit neue Filme - nicht gerade Kunst, aber doch mehr als die Summe der Einzelteile, genannt Trash.

Doch wer nun erwartet dass sich dieses Schema schnell abnutzt, der unterschätzt das Talent Tarantinos, der genau weiß, dass er zwar zur weiteren Ausübung seines Jobs einen gewissen Publikumsgeschmack entsprechen muss, aber auf der anderen Seite zu sehr in seine "Kunst" vernarrt ist um immer nur die selben Filme zu drehen. So folgt nach der übertriebenen Splatterorgie des [ersten Teils](/blog/2003/10/23/kill-bill-vol-i/) nun ein Umschwung der Erzählart: Mit Überlänge und ohne Hektik wird dem Zuschauer die Vorgeschichte näher gebracht und endlich geklärt, was es mit Bill und der Braut eigentlich auf sich hat.

Die verbliebenen drei Kämpfe geraten dabei fast vollkommen in den Hintergrund und sind demensprechend kurz inszeniert, wenn auch nicht weniger intensiv. Im Gegenzug wird deutlich mehr miteinander gesprochen, so dass eine Stärke von Tarantino wieder voll ausgespielt werden kann: Die Dialoge über reichlich absurde Themen, die debattiert werden als wären sie Realität (Superman). Dies ist wiederum ein wichtiger Teil der Tarantinischen Pseudowelt, wo Fiktion und Rezitation eine so enge Symbiose eingehen dass es schwer fällt zu sagen, wo der geniale Trash aufhört und der schlechte Film anfängt. So kann sich die Braut diesmal aus einem unterirdischen Sarg befreien, in dem sie lebendig begraben wurde und lernt später bei einem alten Asiaten die 5-Punkt-Pressur-Herz-Explosions-Technik. Doch wer sich auf Handlungselemente dieser Art einlässt, der kann sich wieder einmal an Filmzitaten ohne Ende erfreuen und wird auch den im Vergleich zum Vorgänger schwächeren Soundtrack verkraften.

Fazit: Nach dem rasant inszenierten ersten Teil fällt die Fortsetzung als einzelnes Werk leider ein bisschen ab, denn ohne "Kill Bill Vol. 1" ergibt vieles keinen Sinn. Quentin Tarantino schafft es jedoch, sich nicht zu wiederholen und erfüllt damit wieder einmal nicht die Erwartungen - doch zusammen ergeben die beiden Filme ein großes Ganzes.
