---
title: "The end of Mr.Y"
date: "2009-01-24T23:23:41"
categories: [gelesen]
---

*von Scarlett Thomas,
veröffentlicht von Canongate, ISBN 978-1-84767-070-0, 7,99£*

Dinge nach Äußerlichkeiten auszuwählen ist meist keine gute Entscheidung. Diese Erfahrung habe ich nicht nur mit Weinflaschen gemacht, sondern ebenfalls mit Büchern. Darum informierte ich mich zuerst über *The end of Mr.Y*, obwohl es mich im Buchladen mit seinem orangenen Cover und den schwarzen Seitenrändern geradezu angeschrien hat. Die Rezensionen wischten jedoch alle Bedenken beiseite, dass hier ein schlechtes Werk über die Optik verkauft werden soll.

Die Heldin des Buches trägt den schönen Namen Ariel, hat lange rote Haare und mag Büffelgrasvodka. Damit hat *The end of Mr.Y* schon einmal einen großen Bonus bei mir. Dies mag wieder eine Äußerlichkeit sein, die noch dazu bei einer Romanfigur, deren Aussehen man sich im Kopf ausmalen muss, nebensächlicher nicht sein könnte. Doch aufgrund meiner Obsession für Rothaarige verzeihe ich der Autorin dafür, dass sie ihrem Hauptcharakter ein verkorkstes Leben auf den Leib geschrieben hat und deren Vermögensverhältnisse alles andere als stimmig sind. Auf der einen Seite hat sie nämlich nur ein kleines Einkommen, dass gerade so für eine kalte Wohnung und das Essen im Monat reicht, doch gleichzeitig besitzt sie einen Laptop, einen IPod, ein Auto. Das passt nicht zusammen.

Viel besser passen dagegen die Spielereien mit den sogenannten "Gedankenexperimenten", die Inhalt von Ariels Doktorarbeit sind. Von Schrödingers Katze bis Einsteins relativ zueinander fahrenden Zügen, alles was sich in der Physik einer einfachen Erklärung und der direkten Beobachtung widersetzt wird mit einem bildhaften Gleichnis der Allgemeinheit näher gebracht. Die Tradition dieser Gedankenexperimente reicht zurück bis in viktorianische Zeiten, als damals unerklärliche Phänomene mit aus heutiger Sicht abenteuerlichsten Theorien versucht wurden zu begründen, später jedoch neuen Ideen weichen mussten. Doch wie nah aktuelle Modelle der Wahrheit kommen kann niemand genau sagen, also ist es durchaus interessant zu beobachten, welchen Einfluss die jeweilige Zeit auf die Modelle hat, die das Verhalten unserer Welt erklären. Und haben am Ende vielleicht unsere Wahrnehmungen und Gedankenwelten sogar einen Einfluss auf die physikalischen Grundfeste von dem, was wir als Realität ansehen? Diese Gedankenspielereien sind das Highlight das Buches; einige Ideen ziehen sich durch das gesamte Werk, werden zuksessive weiterentwickelt und lassen das Lesen zu einem spannenden Erlebnis werden.

Über diese Forschung ist Ariel bei Thomas Lumas gelandet, einem exzentrischen Universalgelehrten der viktorianischen Zeit. Er starb, nachdem er ein Buch namens *The end of Mr.Y* veröffentlicht hat, auf dem seitdem ein Fluch liegen soll. Denn jeder, der es gelesen hat, ist anschließend verschieden. Ariel findet per Selbstexperiment heraus, dass das Buch ein homöopathisches Rezept zur Herstellung eines Trankes enthält. Durch dessen Einnahme gelangt man in eine Troposphäre genannte Welt der Gedanken, die den Zugang zu den Bewusstseinen aller Lebewesen und sogar Zeitreisen durch das Springen in Erinnerungen ermöglicht. In der süchtig machenden Troposphäre läuft jedoch die Zeit anders ab als in der realen Welt, so dass die meisten Leser von *The end of Mr.Y* starben, weil sie nicht schnell genug den Weg heraus fanden. Doch als wäre dies nicht gefährlich genug, sind seit dem Lesen des Buches auch noch amerikanische Agenten hinter Ariel her, die unbedingt das Rezept in ihre Hände bekommen wollen.

An dieser Stelle hat das Buch für mich etwas an Reiz verloren, denn die nun folgende thrillerartige Flucht und die etwas aus der Luft gegriffene tragische Liebesgeschichte passen so gar nicht zu dem verspielten Beginn. Ein wenig geht auch die Logik an dieser Stelle verloren; zumindest verliert der Leser total den Überblick, welcher Charakter zu welchen Aktionen in der Troposphäre fähig ist. Erst als diese Flucht ein Ende findet, legt sich auch diese unnötige Hast und die Autorin nimmt sich ausführlich Zeit, ihr eigenes Gedankenexperiment der Gedankenwelt in aller Ruhe zu einem interessanten Ende zu führen.

Fazit: *The end of Mr.Y* ist ein spannendes Buch über Gedankenexperimente, dass über ein namensgleiches Buch im Buch das Konzept der Troposphäre genannten Gedankenweil skizziert. Doch dies hört sich nach mehr Meta-Ebene an, als die Story eigentlich bietet; die Autorin dosiert die erklärenden Informationen die Spannung haltend bis zum Ende des Buches und garniert ihre Geschichte mit Sex and Crime, so dass sich eine recht interessante Mischung ergibt. Nicht immer richtig dosiert, aber zumindest sehr unterhaltsam - wer auf Gedankenexperimente steht, sollte einen Blick riskieren.
