---
title: "Assoziation des Tages"
date: "2007-10-21T19:21:21"
categories: [gedacht,gesehen]
---

Was haben [Knorkator](http://www.knorkator.de) und [Naked Lunch](http://de.wikipedia.org/wiki/Naked_Lunch_(Film)) gemeinsam?

*Die Geschichte vom [Arschloch](http://www.knorkator.de/discography/track_detail.php?releaseid=200&trackid=3), das die Funktion des Mundes übernimmt.*

Ich hätte nie gedacht, dass die Band David Cronenberg in ihren Referenzen führt. Der Film ist auf jeden Fall empfehlenswert für alle diejenigen, die Filme über Drogenexzesse wie *Fear and Loathing in Las Vegas* (lief in derselben Serie auf 3Sat) mögen oder generell den typischen cronenbergschen Spielereien mit Realität und Wahnvorstellungen etwas abgewinnen können.

Wie später auch in [eXistenZ](http://de.wikipedia.org/wiki/EXistenZ) sind insektenartige Wesen die eindeutigen Zeichen, dass man sich gerade in einer Wahnvorstellung des Hauptakteurs befindet, dem Autoren Bill Lee. Diese repräsentieren sein wichtigstes Werkzeug, die Schreibmaschine, und schlagen gleichzeitig den Bogen zu den sexuellen Auschweifungen, die den Autoren neben den Drogen antreiben.

Der Film spielt dabei mit der Idee, den Schriftsteller William S. Burroughs beim Schreiben des gleichnamigen [Buches](http://de.wikipedia.org/wiki/Naked_Lunch_(Roman)) zu beobachten - der Wikipedia-Eintrag hilft dann auch beim Verständnis einzelner Szenen des Filmes. Wer also bereit ist, sich die Wahrnehmung eines Drogensüchtigen zu eigen zu machen, der sollte den Film auf jeden Fall einmal ausprobieren. Die visuelle Brillianz und die verworren-skurile Handlung nötigen mich geradezu zu dieser Empfehlung!

