---
title: "X-Men 2"
date: "2003-05-05T00:00:29"
categories: [gesehen]
---

*USA (2003)
Regie: Bryan Singer
Darsteller: Ian McKellen (Erik "Magneto" Lehnsherr), Hugh Jackman (Logan alias Wolverine), Brian Cox (William Stryker), Patrick Stewart (Professor Charles Xavier), Famke Janssen (Dr. Jean Grey), Alan Cumming (Kurt "Nightcrawler" Wagner), Halle Berry (Storm), Rebecca Romijn-Stamos (Mystique), Anna Paquin (Rogue), Shawn Ashmore (Iceman), Kelly Hu (Lady Deathstrike), James Marsden (Cyclops), Aaron Stanford (Pyro), Bruce Davison (Senator Robert Kelly) und einige Mutanten mehr...*
[Offizielle Homepage](http://www.x-men-the-movie.com/)

Nach einem Anschlag auf den Präsidenten der USA durch einen Mutanten nimmt der Militärforscher Stryker dies zum Anlass, in großem Maßstab gegen die Andersartigen vorzugehen. So kann er Charles Xavier in Gewahrsam nehmen und beim Stürmen von dessen Mutantenschule die Gedankenverstärkungsmaschine Cerebror an sich reißen. Darin will er den manipulierten Xavier dazu bringen, alle Mutanten auf der Erde zu vernichten. Doch die restliche X-Men haben sich inzwischen mit dem entflohenen Magneto zusammengeschlossen und wollen dies mit aller Macht verhindern, geht es doch um ihr aller Leben...

Eine der Grundregeln in Hollywood lautet: Ist ein Film sehr erfolgreich, so kann man mit einer Fortsetzung auch Geld verdienen. Und da Amerika seine Superhelden abgöttisch liebt hat man die Crew des ersten X-Men-Films gleich Verträge für die Fortsetzung mit unterzeichnen lassen - was sich im Nachhinein als kluger Schachzug erweist. Wer weiß, ob sich die mittlerweile mit einem Oscar dekorierte Halle Berry oder die inzwischen etablierten Stars Anna Paquin und Hugh Jackman noch einmal für eine Comic-Verfilmung hergegeben hätten. Und Ian McKellen und Patrick Stewart hätten sich ihre Rollen sicherlich noch fürstlicher belohnen lassen als im Vorgänger. So konnte Bryan Singer, der ebenfalls schon im ersten Teil Regie führte, wieder diesselbe Crew aufbieten und muss dem Zuschauer nicht erst in Nebensätzen erklären, was denn aus dieser oder jener Figur wurde oder jeden Einzelnen und seine Fähigkeiten noch einmal vorstellen.

Dies wurde nur nötig für die neuen Figuren Nightcrawler, Pyro, Iceman, Lady Deathstrike, Stryker usw. - und genau da liegt der Hund begraben. Lebte der erste Teil noch hauptsächlich von der Auseinandersetzung Xavier/Magneto und der Selbstfindung Wolverines, so versucht die Fortsetzung jedem Mutanten die gleiche Menge Action (und wenigen Zeilen Dialog) zuzugestehen, was bei der großen Zahl an Hauptdarstellern unweigerlich schiefläuft. Damit dem Zuschauer aber gar nicht erst die schwache Story und die Logiklöcher darin auffallen, wird 2 Stunden lang ein Action-Feuerwerk abgebrannt, welches allerdings vornehmlich Zweikämpfe bietet und im Gegensatz zum Vorgänger auf bekannte Locations verzichtet. So überzeugen zwar die Teleportationen des Nightcrawlers, aber ansonsten wird eher gewohnte Kost geboten und Pyros Feuer sieht man doch allzu deutlich seine Herkunft im Computer an.

Vieles an diesem Film erinnert zu sehr an einen Comic. Wo im ersten Teil noch die Annäherung an die echte Welt gesucht wurde (deshalb mussten auch die bunten Kostüme cooleren Lederklamotten weichen), wird in der Fortsetzung das Thema Politik zum Beispiel nur noch angerissen. Die Auseinandersetzung Mutanten gegen Menschen stellt sich dann doch nicht als Hauptthema des Filmes heraus; vielmehr werden die Normalsterblichen offensichtlich nur geduldet und die guten Mutanten müssen darüber wachen dass die bösen Mutanten nicht die Menschheit vernichten.

Die besten weil ironischsten Szenen im Film hat dabei noch Sir Ian McKellen, welcher sich auch als einzigster des Ensembles unter seiner Maske hervorzuheben weiß. Alle anderen Rollen sind ausschließlich nach dem Run-And-Fight-Prinzip ausgelegt und damit verkommt der Film zur bloßen sinnleeren Comic-Unterhaltung. Nicht dass ich falsch verstanden werde: X-Men 2 ist auf jeden Fall ein guter Action-Film, bei dem 2 Stunden lang garantiert keine Langeweile aufkommt, doch der Regisseur hat es geschafft noch den letzten Teil Aussage aus dem Stoff zu verbannen und einen geradlinigen Film ohne Ecken zu drehen. So erreicht die Fortsetzung nicht die Qualität des Vorgängers und schon gar nicht die der ersten beiden Batman-Filme von Tim Burton, die für mich die Referenz für Comic-Verfilmungen darstellen.

Fazit: Wer den ersten Teil mochte und sich für Comics und/oder Action interessiert, der wird auch mit diesem Film gut bedient. Aber Innovationen oder eine Auseinandersetzung mit der Thematik sucht man vergeblich.
