---
title: "Back to school"
date: "2008-02-26T22:09:32"
categories: [getan]
---

Heute stand die erste Stunde Rückenschule an, die mein Arbeitgeber netterweise finanziert hat. Und da ich mich schon seit dem Ende des Studiums mit sporadischen Rückenschmerzen herumschlage, mich aber nie dazu bequemen konnte, etwas für den Muskelaufbau zu tun, habe ich die Gelegenheit dankend angenommen.

So stand ich nun mit ein paar Kollegen vor einer leicht kräftigen ehemaligen Sportstudentin, die gleich zu Beginn meine Erwartungen über den Haufen warf, etwas Theorie in Bezug auf Muskelgruppen und deren Training bzw die korrekte Haltung im Büroalltag zu lernen. Sie wolle die Zeit lieber nutzen, unseren Muskeln etwas Arbeit zukommen zu lassen und hat dann über eine Stunde lang Übungen aus der Schnittmenge von Aerobic, Fitness und Yoga verordnet (woanders auch als *Bauch-Beine-Po* deklariert), bei denen ich untrainierter Schreibtischtäter ordentlich ins Schwitzen kam.

Zum Glück war ich dermaßen gefordert mit der ungewohnten Aufgabe, mehrere Gliedmaßen unabhängig voneinander bei gleichzeitig zu kontrollierender Atmung zu bewegen, dass ich der chilligen Musik der Lehrerin keine Aufmerksamkeit widmen konnte. Schlechte Musik kann sonst schnell dazu führen, dass ich genervt bin, was wiederum meine Motivation für sportliche Aktivitäten deutlich senkt. Mal schauen, wie sich die folgenden Schulstunden entwickeln und was mir der Kurs längerfristig bringt (und wieviele meiner Muskeln ich morgen böse spüren werde).
