---
title: "Buchstöckchen"
date: "2011-02-08T23:32:18"
categories: [gelesen,gefunden]
---

Ich habe seit langem mal wieder ein [Stöckchen](http://www.sabrina-kirnapci.com/blogstockchen-buch-bucher-am-buchersten) entdeckt, das in mir den Wunsch weckte, es auszufüllen. Und so folgen deshalb ein paar Informationen über mich und meine Bücher:

**01) Was liest du gerade?**
Eigentlich lese ich gerade nur einen Reiseführer über Japan von Christine Liew und die aktuelle Ausgabe der [Ray](http://ray-magazin.at/) - denn es ist Berlinale, und da habe ich nicht viel Zeit. In zwei Wochen geht es jedoch weiter mit entweder [Turing Test von Chris Beckett](http://www.elasticpress.com/turingtest.htm) oder der [London-Biographie von Peter Ackroyd](http://www.randomhouse.de/book/edition.jsp?edi=213235).

**02) Welches Buch hat dich zuletzt stark beeindruckt?**
Das ist wohl [1Q84 von Haruki Murakami](/blog/2011/02/04/1q84/).

**03) Sammelst du irgendetwas?**
Außer Büchern und meinen Kino-Eintrittskarten?

**04) Schreibst du Widmungen in Bücher?**
Nein, Bücher lasse ich gerne in dem Zustand, in dem ich sie gekauft habe. Dies bedeutet: Keine Eselsecken, keine geknickten Rücken, und vor allem kein Gekrakel auf den Seiten.

**05) Schreibst du deinen Namen in deine Bücher?**
Aus o.g. Gründen nicht. Aber ich hinterlasse meist die Kassenzettel darin, wenn ich nicht gerade aus Faulheit bei Amazon bestellt habe - da sind die Rechnungen einfach zu groß.

**06) Welches Buch hast du doppelt?**
So richtig doppelt besitze ich kein Buch. Allerdings habe ich [Terry Pratchetts Nation](/blog/2009/05/08/eine-insel/) in dem Sinne doppelt, das ich mir die deutsche Hardcoverausgabe gekauft hatte und kurz danach von Freunden das englische Taschenbuch geschenkt bekam.

**07) Von wem würdest du dir gern was vorlesen lassen?**
Von niemandem. Ich bin kein Fan davon, Bücher aufbereitet zu bekommen, ob nun als Hörbuch oder sogar in optischer Form - ich liebe es einfach, mir eine eigene Vorstellung des Buches nur durch das Lesen zu machen, alles andere schränkt diese intensive Wahrnehmung ein.

**08) Sitzt du im Kino lieber am Gang oder in der Mitte?**
Was macht diese Frage denn in einem Bücherstöckchen? Egal, ich sitze gerne zentral in der Mitte auf dem idealen (aber meist nicht existenten) Platz, an dem ich zu allen Ecken der Leinwand denselben Abstand habe. So ist auch mein Fernseher ausgerichtet.

**09) Welche ist deine liebste Romanfigur?**
[Ijon Tichy](http://de.wikipedia.org/wiki/Ijon_Tichy). Oder vielleicht doch [Rincewind](http://www.thediscworld.de/index.php/Rincewind)?

**10) Nach welchem System ordnest du deine Bücher daheim?**
Genre (Belletristik, Sachbuch, SF/Fantasy). Serien (z.B. Scheibenwelt). Autor. Sprache. Teilweise auch Optik und Größe.

**11) Lesen: vor dem ins Bett Gehen oder nach dem Aufstehen?**
Ich komme nur selten dazu, nach dem Aufstehen zu lesen. Also lese ich meist im Bett vor dem Schlafen und täglich in der Tram.

**12) Welches Buch würdest du deinem größten Feind schenken?**
[Zettel's Traum](http://www.suhrkamp.de/buecher/zettel_s_traum-arno_schmidt_80300.html) oder [Auf der Suche nach der verlorenen Zeit](http://www.suhrkamp.de/werkausgabe/auf_der_suche_nach_der_verlorenen_zeit_sonderausgabe_gebunden_in_moirepapier_90.html). Wobei ich beide durchaus einmal selber austesten würde und es sogar eine Freundin gibt, der ich beide Werke schenken würde. Ich gehe einfach davon aus, dass ein Feind von mir nicht viel mit hoher - oder sagen wir extremer - Literatur anfangen kann.

**13) Hardcover oder Paperback?**
Immer Hardcover. Es sei denn, ich bin mir nicht sicher und will den Autor erst einmal testen.

**14) Zeitung aus Papier oder im Netz?**
Lieber auf Papier. Aber News aus dem Netz sind nicht zu verachten aufgrund der Aktualität.

**15) Von welchem Buch bist du zum ersten Mal so richtig gefesselt worden?**
Schwer zu sagen. Seit ich lesen kann, habe ich das Bücherregal meiner Eltern bearbeitet (nach kleinen Abstechern zu den [Trompeterbüchern](http://de.wikipedia.org/wiki/Die_kleinen_Trompeterbücher)) und kann mich nicht an alle Leseerfahrungen erinnern. Aber ich glaube, dass mich vor allem Karl May mit *Der Schatz im Silbersee* gefesselt hat - ich habe das Buch an einem Nachmittag verschlungen.

**16) Deine liebste Literaturverfilmung?**
Vielleicht *Dune* von David Lynch oder *Der Eissturm* von Ang Lee.

**17) Tägliche oder wöchentliche Pflichtlektüre?**
Gar nichts in dieser Häufigkeit.

**18) Bevorzugte Urlaubslektüre?**
Bücher - was sonst?

**19) Verkaufst du gelesene Bücher wieder?**
Niemals. Blasphemie! Alles wird aufgehoben.

**20) Deine meistgelesenen Bücher?**
In jüngster Zeit komme ich aus Zeitmangel nicht mehr dazu, ein Buch öfter als einmal zu lesen. Deshalb muss ich wieder Karl May nennen (als Kind hatte ich viel Zeit und wenige Bücher - genau umgekehrt zu jetzt).

**21) Welches Buch hast du beim Lesen vorzeitig weggelegt und nie wieder angefangen?**
Keines. Dies ist so etwas wie ein selbstauferlegter Zwang, dass ich "Problembücher" zwar gerne für ein paar Wochen auf Eis lege, aber mich schließlich doch bis zum bitteren Ende durch sie hindurchquäle.

Da fällt mir ein: Den [Faust in der Schule](/blog/2010/01/23/schullekture-eine-retrospektive/) habe ich nie durchgelesen - ich fand die Versform zu nervig.

**22) Durch welches Buch musstest du dich durchquälen?**

[John Irving - Owen Meany](/blog/2009/04/20/owen-meany/)
[Douglas R. Hofstadter - Gödel, Escher, Bach - ein endlos geflochtenes Band](/blog/2009/11/05/godel-escher-bach-ein-endlos-geflochtenes-band/)
[Uwe Tellkamp - Der Turm](/blog/2010/05/31/der-turm/)

**23) Bei welchem Buch stutzen die anderen, weil du es besitzt bzw. gelesen hast?**
Ist mir noch nicht passiert.

**24) Welche Bücher erachtest du von den Medien oder der Menschheit als überbewertet?**
Vielleicht die von Stieg Larsson. Generell kümmere ich mich hauptsächlich um das, was ich lesen will, und bekomme deshalb wenig von Büchern mit, die mich gar nicht interessieren.

**25) Welches Buch brachte dich zuletzt zum Lachen?**
Die [Wir-sind-Helden-Biografie](/blog/2008/07/26/informationen-zu-touren-und-anderen-einzelteilen-ein-wir-sind-helden-tagebuch/).

**26) Welches Buch brachte dich zuletzt unfreiwillig zum Lachen?**
So ein schlechtes Buch habe ich zum Glück lange nicht lesen müssen.

**27) Was hältst du von ebooks?**
Für unterwegs oder den Urlaub schon ganz nett, da sie wenig Platz verbrauchen und durch Lesen und Transport keinen Schaden nehmen. Allerdings kann ich sie nicht ins Bücherregal stellen - und damit disqualifizieren sie sich für einen Kauf.

**28) Ebook vs. Buchdruck?**
Ganz klar Buchdruck (ich sage nur Bücherregal). Wobei es ja nur um den Unterschied in der Distribution geht - vom Schreiben bis zum Setzen ist die Entstehungsgeschichte inzwischen identisch.

**29) Welches Buch würdest du gerne noch lesen?**
Carlos Ruiz Zafón - Der Schatten des Windes
~~[Robert Anton Wilson - Schrödingers Katze](/blog/2011/06/26/schrodingers-cat-trilogy/)~~
Dietmar Dath im Dialog mit Stephen Wolfram - Das Ende der Gleichungen?
Sven Regener - Die Lehmann Trilogie

**30) Welches Hörspiel hat dich am meisten gefesselt?**
Da ich keine höre kann ich hierzu keine Antwort geben.

**31) Welche(n) Autor/in hältst du für überbewertet bzw. unterbewertet?**
siehe Antwort auf Frage 24)

**32) Welches Buch hältst du für unverfilmbar?**
Gerade gelesen - [Die Abschaffung der Arten](/blog/2011/05/08/die-abschaffung-der-arten/) von Dietmar Dath. Jeder Versuch, den multidimensionalen Keramikanern ein Bild zu geben, ist ebenso zum Scheitern verurteilt wie der Versuch, die von technischen Utopien und abstrakten Gesellschaftsfragen nur so triefenden Dialoge in einem Film verständlich zu machen.
