---
title: "Die Abschaffung der Arten"
date: "2011-05-08T23:17:54"
categories: [gelesen]
---

*von Dietmar Dath,
erschienen bei Suhrkamp Taschenbuch, ISBN 978-3-518-46145-7, 12,00€*

500 Jahre nach unserer Zeit haben die Tiere die Welt zurückerobert. Die sich selbst Gente nennenden Lebewesen haben die Herrschaft der Menschen beendet und bevölkern nun in drei großen Städten das Gebiet, welches früher einmal Europa hieß. Mittels eines Kommunikationsmediums, dem Pherinfonsystem, können alle Gente ohne zeitlichen Verzug miteinander in Verbindung bleiben und Informationen austauschen; über genetische Verbesserungen kann jedes Mitglied der Gesellschaft sein Aussehen und seine Fähigkeiten an die eigenen Vorlieben anpassen. Über allen aber thront der Löwe Cyrus Golden, der schon beim Sieg der Gente über die Menschen dabei war und seitdem die Geschicke der Tiere lenkt.

Doch auch die Zivilisation der Gente ist nicht perfekt. Es hat sich eine Religion mit unklarem Ziel etabliert, es gibt so etwas wie Rassenideologien und die letzten Nachkommen der Menschen werden wie Tiere in illegalen Clubs zur Schau gestellt. Und in Südamerika hat sich aus zwei riesigen Computern das Keramikmaschinen-Kollektiv Katahomenleandraleal gebildet, das mit multidimensionalen Kreuzungen aus Menschen und Maschine beginnt, die Gente zu vertreiben. Diesen bleibt nur die Flucht ins All, wo sie auf Mars und Venus mit Hilfe von Gendatenbanken neue Zivilisationen ansiedeln mit dem Ziel, irgendwann auf die Erde zurückzukehren...

Was sich auf den ersten Blick wie ein Zukunftsroman, wie Science Fiction im Stile Frank Herberts anhört, fühlt sich weite Teile des Buchs ganz und gar nicht so an. [Dietmar Dath](http://www.cyrusgolden.de) vermischt eine weit ausholende Gesellschaftsvision und Gedanken zur Evolution mit technischen Utopien, die sich ebenso in seiner Sprache voller Wortschöpfungen wiederfinden. Meist ist nicht sofort klar, wofür genau die erfundenen Wortkonstruktionen stehen, doch im Laufe der Handlung erschließt sich über den Kontext vieles, wenn auch nicht alles. Dazu kommt eine Vielzahl teilweise extrem langer Namenskonstruktionen, häufige Wechsel im Erzählstil und zeitliche und örtliche Sprünge innerhalb der Handlung, die einem leichten Lesefluss im Wege stehen. Doch dafür erhält der Leser ein Gedankenexperiment, das in so viele Richtungen seine Fühler ausstreckt, dass sie kaum alle aufzählbar sind.

Für einen linken Autoren wie Dietmar Dath besonders wichtig scheint die Frage nach der Gleichheit in der Gesellschaft. Was für einen Grundbau benötigt eine Gesellschaft, die zu Gleichheit befähigt? Wie gleich können die Mitglieder eines Kollektivs überhaupt sein und wie kann so ein Zustand maximaler Gleichheit erreicht werden? Indem alle Unterschiede aufgehoben werden - von Geschlecht, über Eigenschaften bis zum Aussehen - oder indem Zugang zu allem, was unterschiedlich macht, gewährt wird und damit alle die gleichen Möglichkeiten haben? Beiden Seiten gibt Dath im ersten Teil der *Abschaffung der Arten* mit den Gente und den Keramikanern ein Gesicht, und am Ende der ersten Buchhälfte stellt er sogar einen vorläufigen Sieger im Kampf der Systeme vor.

Doch einfache Lösungen sind in diesem Buch gewiss nicht zu finden. Am Ende haben alle Systeme mehrere Evolutionsschritte hinter sich gebracht und das Erreichte ist schwer zu interpretieren. Kategorien wie Erfolg und Scheitern zählen nicht mehr, sondern die Fragen, die derart fiktionale und vor allem abstrakt artifizielle Gesellschaftsentwürfe aufwerfen. In wie weit ist Leben, die Natur bzw die gesamte Evolution planbar? Hat die natürliche, durch Mutation voranschreitende Entwicklung, wie Darwin sie beschrieb, eigentlich ein Ziel, so dass überhaupt entschieden werden kann, ob Eingriffe durch den Menschen davon abweichen oder innerhalb der erhofften Auswirkungen selber zielführend sind? Oder ist die Idee, alles steuern zu können, vielleicht selber nur eine Illusion?

Die Moral solcher Entscheidungen wie der Genmanipulation wird dagegen vom Buch gar nicht berührt. Wie viele der technischen Hilfsmittel werden sie als gegeben angenommen, um als Grundpfeiler der Zivilisation der Gente eine Basis zu geben, ihr einen gewissen Abstand zu ermöglichen und damit die Diskussion auf einer anderen Ebene zu führen als nur über den Vergleich zur menschlichen Gesellschaft. Trotzdem wirkt die Menschheit in *die Abschaffung der Arten* an vielen Stellen auf ihre Nachfolger als Beherrscher der Erde nach. Dies betrifft sowohl Aspekte wie Religion und Kunst als auch, dass viele der Gente-Charaktere Tierfabeln entnommen sind. Es gibt den Löwen und den Fuchs, Dachse und einen Esel. Wenn sich die Figuren nun selber für ihre äußere Gestalten entschieden haben, liegt dies dann an einem tief im kulturellen Gedächtnis enthaltenen allgemeinen Wissen, quasi im Erbgut codierten Rollenbilder, die selbst die Genmanipulationen nicht vernichten können? Sind im Erbgut sogar die Ursachen für unsere Anfälligkeit für Religionen versteckt, wie Dath mit seinem Wetzelchen unterstellt?

Sind die vielfachen Wahloptionen der Gente also eher eine Illusion und die Grenzen trotz der vielfältigen Möglichkeiten fest abgesteckt? Wird vielleicht immer nur etwas anderes nachgeahmt? Dann muss es jemanden geben, der voranschreitet, der den Weg vorgibt, damit er kopiert werden kann - im Buch sieht sich Cyrus Golden in dieser Rolle. Doch wenn nur einer oder wenige diese Rolle einnehmen, hat die Allgemeinheit dann überhaupt die Freiheit? Oder kaut sie nur das nach, die Einzelne vorgegeben haben?

Beantworten muss diese Fragen jeder Leser für sich selber, die Möglichkeiten zur Interpretation sind vielfältig und ein Verständnis der Handlung nicht einfach. Im zweiten Teil des Buches verläuft sie chaotisch wie die Evolution selber, mit vielen Abzweigungen und Sackgassen, um mit der Beschreibung eines Paradieszustandes zu enden; mit einem Pärchen wie Adam und Eva, nur dass sie nicht die Quelle allen Lebens auf der Erde sind, wie es sich die Christen vorstellen, sondern das Ergebnis desselben, die Sammlung der besten Gene, das Ziel der Planungen von Cyrus Golden.

Ich vermute, dass ich vieles in diesem Buch nicht verstanden habe. So überfrachtet es mit Symbolen, Ideen, Handlungen und sogar Stilen ist, benötigt es schon ein universell-breites Wissen, um sie entschlüsseln - und dieses fehlt mir an vielen Stellen. Und doch hat die *Abschaffung der Arten* im Spiel mit den von mir identifizierten Fragen und den in dieser Form selten gesehenen Gesellschaftsentwürfen einen sehr anregenden Lesegenuss beschert, der mich acht Monate danach noch immer beschäftigt - so lange habe ich an dieser Kritik geschrieben.
