---
title: "Placebo - Meds"
date: "2006-03-17T14:39:35"
categories: [gehört]
---

> Baby, did you forget to take your meds - someone call the ambulance, there's gonna be an accident!

Lange musste ich darauf warten: Nach vielen Touren, einer Live-DVD und einer Art Best-of-Compilation mit nur zwei neuen Songs war die Zeit am 10.03. endlich reif für das fünfte [Placebo](http://www.placeboworld.co.uk)-Studioalbum. Das [kostenlose Konzert in der Columbiahalle](http://www.nicorola.de/?p=1311) und die Autogrammstunde im Saturn habe ich zwar trotz meines Aufenthaltes am Freitag in Berlin verpasst, aber seitdem höre ich die Scheibe in heavy rotation und habe mir auch die Zeit gegönnt, mich parallel zum Hören etwas mit den Texten auseinander zu setzen

Wer dachte, dass es nach *Sleeping With Ghosts* und der letzten Single *Twenty Years* umso elektronischer mit Placebo weitergeht, der wird vielleicht etwas enttäuscht sein von *Meds*. Denn die CD hört sich vielmehr nach einer Mischung von *Black Market Music* und *Without You I'm Nothing* an und die Elektroeffekte werden nur sparsam und gezielt wie in dem Track *Post Blue* eingesetzt. Ich will das Album aber auf keinen Fall als musikalischen Rückschritt bewerten und deshalb auf weitere Vergleiche verzichten.

Vielmehr sind es die Stärken von Placebo, welche wieder in den Vordergrund rücken: Intensives Songwriting und die dosierte Energie von Bass, Gitarre/Piano und Drums. Brian Molko benutzt das Stilmittel Wiederholung oft und gerne, was seine Texte eindringlicher erscheinen lässt. Darin geht es weiterhin düster zur Sache, ob nun Politik, Liebe oder vor allem Obzessionen und Versagen im Mittelpunkt stehen. Zur Verstärkung hat er sich Alison Mosshart ([The Kills](http://www.myspace.com/thekills)) und Michael Stipe ([R.E.M.](http://www.remhq.com)) für zwei Songs eingeladen, doch vor allem der Opener *Meds* bleibt davon nachhaltig in Erinnerung. Dieser gibt das Tempo vor, welches das sehr eingängige *Infra-Red* und der geradlinige Song *Drag* in der Folge hochhalten.

Danach geht es musikalisch etwas abwechslungsreicher weiter. *Space Monkey* irritiert mit einem hypnotischen Sprechgesang, *Follow the Cops back home* ist eine typische Placebo-Ballade und setzt sich mit dem Thema staatliche Gewalt auseinander. Die erste Single-Auskopplung im Königreich *Because I want you* arbeitet dafür mehr mit treibenden Drums und Gitarrengeschrammel und lässt Assoziationen zu *Every me, every you* aufkommen.

Sehr ungewöhnlich klingt die CD aus: Nach dem rockigen *One of a kind* erscheint die Abrechnung mit den durchgezechten Nächten *In the cold light of morning* schon der Auskehrer des Albums zu sein, doch dann folgt schließlich die sehr gelungene deutsche Single "Song to say Goodbye". Der Abschied scheint aber nur der eigenen Jugend zu gelten, so hoffe ich zumindest.

Fazit: Placebo haben (mal wieder) ein fantastisches Album abgeliefert, welches sowohl die Fans als auch neue Hörer mit seinem Abwechslungsreichtum begeistern wird. 48 Minuten sind zwar nicht das beste Preis-/Leistungsverhältnis, aber dafür stimmt zumindest die Qualität. Wer sich für die erste Single und ältere Placebo-Songs begeistern kann, der sollte auf jeden Fall beim Plattendealer zugreifen!


