---
title: "Brütal Legend (Demo)"
date: "2009-10-05T00:07:38"
categories: [gespielt]
---

Was kommt heraus, wenn sich [Tim Schafer](http://www.doublefine.com/) (der kreative Kopf hinter *Day of the Tentacle* und *Monkey Island I & II*) und Jack Black, Schauspieler und Sänger von *Tenacious D*, für ein Videospiel zusammentun? Ganz einfach: *Brütal Legend*, das wohl witzigste und abgefahrenste Action-Adventure seit langem.

Zusammen haben die beiden eine virtuelle Welt erschaffen, die den Covern von Heavy-Metal-Alben entsprungen sein könnte. Der Spieler steuert dabei den Alter Ego von Jack Black, Roadie Eddie Riggs, als Auserwählten, der mit seinen Gitarren-Kräften diese Welt retten oder zerstören muss. Dabei wird der Metal nicht nur gehuldigt, sondern auch gehörig auf die Schippe genommen, wie man es eben von Jack Black gewohnt ist. Und die Witze beschränken sich nicht nur auf die übertrieben vielen Ös und Üs als Anspielung auf Motörhead (Lemmy hat ebenso einen Auftritt wie Ozzy Osbourne).

Das Spiel besitzt mit seiner recht simplen, aber doch vielseitigen Steuerung einen einfachen Einstieg und überzeugt zumindest im Demo-Level mit einem unglaublichen Tempo. Spiel-/Dialogwitz, Leveldesign und natürlich ein Soundtrack voller Metal-Klassiker ergänzen sich dabei kongenial; bereits das Menü in Form einer aufklappenden Langspielplatte deutet an, was den Spieler erwartet. Wer also nur im entferntesten etwas mit der metallischen Musik anfangen kann, sollte dieses Spiel kaufen; beste Unterhaltung ist garantiert!
