---
title: "City Beach Halle 2012"
date: "2012-08-05T23:56:22"
categories: [gewesen]
---

Halle mausert sich langsam aber sicher zur Sportstadt. Der HFC ist zwar gerade erst in die dritte Liga aufgestiegen, hat jedoch [ein schönes neues Stadion](http://www.erdgas-sportpark.de/). Im Damen-Basketball sind die SV Halle Lions nationale Spitze und im Schwimmen ist Paul Biedermann trotz des schlechten Abschneidens bei Olympia das Aushängeschild. Da passt eine Veranstaltung gut ins Bild, die 2012 schon zum vierten Mal stattfindet: Das [City Beach auf dem Marktplatz](http://www.halle-beach.de/).

Vor der Kulisse von Marktschlösschen, Marktkirche, Roter Turn, Stadthaus, Rathaus und unter den wachsamen Augen von Georg Friedrich Händel wurden drei Beachvolleyball-Felder aufgeschüttet und zwei Tribünen aufgebaut, um neben dem City Beach Cup auch die Landesmeisterschaften auszutragen. Dafür wurde die Veranstaltung von einem Wochenende auf zehn Tage ausgedehnt und mit einem breiten [Rahmenprogramm](http://www.vvsa-volleyball.de/images/2012_ablaufplan_city%20beach.pdf) versehen.

Ich konnte am Samstag kurz beim Mixed-Wettbewerb vorbeischauen. Das Niveau auf den Plätzen war durchwachsen, aber das Wetter war super und die Stimmung auf den Tribünen (hauptsächlich durch Aktive des Turniers) ebenso - da hätte ich gerne selber mitgewirkt. Ich finde es super, dass es in Halle eine solche Veranstaltung meiner Lieblingssportart gibt, und hoffe, dass dieses Beispiel Schule macht!

[gallery link="file"]
