---
title: "Bis ich dich kaufe"
date: "2006-01-20T23:18:17"
categories: [gelesen]
---

Am nächsten Dienstag, den 24.01.2006 (warum eigentlich Dienstag?), erscheint endlich der neue Roman von John Irving, "Until I find you",  in der [deutschen Übersetzung](http://www.amazon.de/exec/obidos/ASIN/3257065221/ref=wl_it_dp/302-5692881-1255268?%5Fencoding=UTF8&coliid=I6BOHOQNLBO95&colid=IK14TZWASPDJ). Der Diogenes-Verlag bietet vorab eine mit 18 Seiten erfreulich umfangreiche [Leseprobe](http://www.diogenes.de/4DACTION/web_show_magazin/ID=2872045&cnt=2&md_id=106&path=leser/magazin_neu/106/02.htm) als PDF zum Download; ebenfalls kann man sich einen Ausschnitt aus dem parallel erscheinenden Hörbuch zu Gemüte führen.

Ob "Bis ich dich finde" besser geworden ist als die letzten, etwas schwächeren Bücher von John Irving, kann ich nach dem Lesen der Probe noch nicht beurteilen. Thematisch (Tätowieren, Ringen) liegt mir der Roman jedenfalls nicht, aber vielleicht verleiht ja der Roadmovie-Charakter der Geschichte eine interessante Note. Nächste Woche bin ich auf jeden Fall schlauer, und dann wird auch an dieser Stelle darüber berichtet!
