---
title: "Einer von vielen"
date: "2010-02-02T23:51:56"
categories: [gelesen]
---

*von Norbert Zähringer,
veröffentlicht im Rowohlt Verlag, ISBN 978-3-498-07664-1, 22,90€*

Was haben ein amerikanischer Filmassistent, ein vielsprachiger Exilarmenier und ein deutscher Junge gemeinsam? Ihre Wege werden sich, so erzählt es Norbert Zähringer, in den letzten Tagen des zweiten Weltkriegs in Berlin kreuzen. Doch bis es so weit kommt, musste einiges passieren, und davon berichtet *Einer von vielen* in einer handvoll parallelen Handlungssträngen, die achtzig Jahre umspannen und deren Handlungsorte über die gesamte Welt verteilt sind. Verknüpft sind diese Handlungsstränge, die sich kapitelweise immer einer der Hauptfiguren widmen, durch Treffen dieser Charaktere oder Ereignisse, die Einfluss auf die Entwicklung mehrerer Akteure haben.

Da sich der Autor einige Mühe gegeben hat, diese Zusammenhänge zu verschleiern, gestaltet sich der Beginn des Buches sehr zäh. Viele Nebencharaktere bevölkern die Seiten und in jedem Kapitel muss der Leser erst einmal herauszufinden, welchem der schon bekannten Handlungsstränge nun gefolgt wird. Im Laufe des Buches kristallisieren sich dann fünf Hauptlinien heraus, die sich über zeitliche Sprünge noch vervielfachen. Diese große Menge an Handlungen und die Tatsache, dass sie in den kurzen Kapitel jeweils nur angerissen werden, hat es mir sehr schwer gemacht, ein Interesse an deren Fortgang zu entwickeln. 

Doch zum Glück fokussiert sich der Mittelteil des Buches auf die Figur des Edison Frimm, und damit kommt zum ersten Mal Spannung auf. Der Junge kommt nämlich mit der Filmmetropole Hollywood in Berührung, und alles was mit Filmen zu tun hat, weckt automatisch mein Interesse. Die Beschreibung der Filmindustrie als propagandistisches Werkzeug im zweiten Weltkrieg, aber auch als Geldwäscheinstrument bei gleichzeitiger Mangelwirtschaft empfand ich als sehr reizvoll. Und genau diese Punkte, wo die fiktive Handlung durch reale Ereignisse oder Personen an die Wirklichkeit gebunden ist, machen das Buch interessant.

So taucht als Vertreter der Schauspielergewerkschaft kurz ein gewisser Ronald Reagan auf und der schwerreiche Produzent Gerald G. Hodges erinnert stark an [Howard Hughes](/blog/2005/02/07/the-aviator/). Neben dem zweiten Weltkrieg spielt vor allem ein [Erdbeben aus dem Jahr 1923](http://de.wikipedia.org/wiki/Großes_Kantō-Erdbeben_1923) eine entscheidende Rolle als auslösendes Element. Hinzu kommen die detaillierten Beschreibungen von Los Angeles und Berlin, wobei gerade die Wiedererkennung der Schauplätze in meiner Wahlheimat die Akzeptanz des Buches deutlich erhöht hat. 

Dennoch wirkt die Berliner Handlungslinie um den Kommissar Mauser und seinen Serienmörder zu aufgesetzt. Die Berührungspunkte zu Beginn und Ende des Buches sind zwar als Klammern für die Handlung schön gewählt, aber gerade dadurch wird im Gegensatz zu den sonst leicht und verspielt wirkenden Verknüpfungen der einzelnen Stränge die Konstruktion als ebendiese ersichtlich.

Gegen Ende der knapp 500 Seiten wird schließlich klar, wohin diese führt: Im belagerten Berlin, in einer Nacht der Bombenangriffe, gibt es drei Kapitel, die mit einem nahezu identischen Einstieg das Irren der drei anfangs genannten Charaktere durch die zerstörte Stadt beschreiben. Dies scheint das Ziel zu sein, auf das die gesamte Konstruktion des Buchs ausgelegt ist; eine Art magischer Moment, ein Wendepunkt, in dem sich die Handlungsfäden an einem einzigen Zeitpunkt und Ort überlagern, scheinbar zu einem verschmelzen und an die vielen Ereignisse zurückdenken lassen, die die Figuren hierher geführt haben.

Diese im Aufbau des Buches mit codierte Grundidee, dass [alles](http://de.wikipedia.org/wiki/Schmetterlingseffekt) mit [allem](http://de.wikipedia.org/wiki/Kleine-Welt-Phänomen) zusammenhängt, wird auch direkt in der Nebenhandlung um Edison Frimms Mutter angesprochen, die während ihrer Arbeit in einer Poststation Therorien aufstellt, wie sich Krankheitserreger auf der Welt ausbreiten können.

Was am Ende hängenbleibt ist ein zeitweise unterhaltsames Buch, das vom Spiel mit seinen vielen Handlungsfäden lebt und die Kleine-Welt-Theorie zum zentralen Element und inhaltlichen Leitfaden erhebt. Ein paar weniger Charaktere und ein nicht so abgegrastes Feld wie den Zweiten Weltkrieg hätten dem Buch allerdings gut getan.
