---
title: "Die Bären sind los"
date: "2011-02-10T23:49:32"
categories: [getan]
---

Heute abend ging sie los, die inzwischen 61. [Berlinale](http://www.berlinale.de/de/HomePage.html). Den Eröffnungsfilm stellten dieses Jahr die Coen-Brüder mit ihrem Neo-Western *True Grit*, den ich mir nach seinem offiziellen Deutschlandstart in zwei Wochen ansehen werde. Meine persönliche Berlinale beginnt aber erst am Sonntag mit [Heaven's Story](http://www.berlinale.de/de/programm/berlinale_programm/datenblatt.php?film_id=20116083) und [Vampire](http://www.berlinale.de/de/programm/berlinale_programm/datenblatt.php?film_id=20116179). Für die zweite Woche des Festivals habe ich mir dieses Jahre erstmals Urlaub genommen und hoffe, Karten für ein paar interessante Filme ergattern zu können.

Dies war heute schon schwerer als erwartet. Eventim hat es einfach nicht geschafft, den Ansturm der Ticketkäufer um 10 Uhr zu bewältigen. So hatte ich zwar zwischendurch für beide Sonntagsfilme ein Ticket im virtuellen Warenkorb, doch der Abschluss der Transaktion wollte einfach nicht gelingen - für 1,50€ Ticketgebühr hätte ich eigentlich erwartet, dass sie genügend Server bereitstellen, um für den Ansturm gerüstet zu sein. Deshalb musste ich mich in der Mittagspause wie viele andere Festivalfans im Kino International anstellen und habe mir nach einer Stunde in der Warteschlange die Tickets für Sonntag gesichert. Hoffentlich klappt die Online-Bestellung morgen besser, wenn es um Tickets in der Arbeitswoche, nämlich den Montag, geht. Dann werden auch die ersten Eindrücke hier in diesem Blog folgen. Ich freue mich, dass es endlich losgeht, auch wenn das Berliner Wetter gar nicht so schlecht wie gewohnt ist.
