---
title: "Match Point"
date: "2006-01-26T02:23:50"
categories: [gesehen]
---

*UK, Luxemburg (2005)
Regie: Woody Allen
Darsteller: Jonathan Rhys Meyers (Chris Wilton), Scarlett Johansson (Nola Rice), Emily Mortimer (Chloe Hewett Wilton), Matthew Goode (Tom Hewett), Brian Cox (Alec Hewett), Penelope Wilton (Eleanor Hewett), uvm*
[Offizielle Homepage](http://www.matchpoint-derfilm.de)
	
Den mit *Melinda und Melinda* begonnenen Weg, einen Film nur um eine einzige Frage herum zu drehen und diese vonverschiedenen Seiten zu beleuchten, schreitet Woody Allen auch mit seinem neuem Film fort. Nur fehlen diesmal komplett die gewohnten komödiantischen Elemente, so dass ich *Match Point* als ein Drama bezeichnen will, welches über zwei Stunden lang auf ein Finale zusteuert und dessen Auflösung einen Bogen zurück zum Anfang des Filmes schlägt.

Dort sieht man die Nahaufnahme eines Tennisnetzes bei dem entscheidenten Ballwechsel eines Spieles - der titelgebende Match Point. Der letzte Ball trifft die Netzkante, springt davon senkrecht in die Luft und dann folgt ein Schnitt, so dass der Zuschauer nicht sieht, nach welcher Seite der Ball fällt. Aus dem Off kommentiert die Stimme des Filmhelden Chris Wilton, dass jener Mann Lebensweisheit bewiesen hat welcher sagte, er "hätte lieber Glück als Talent".

Um den Wahrheitsgehalt dieser Aussage genauer unter die Lupe zu nehmen, zeigt Woody Allen dem Zuschauer das Leben eben jenes Chris Wilton, welcher nach einer relativ erfolglosen Profitenniskarriere als Tennislehrer in einem noblen Londoner Club die Familie Hewett kennenlernt. Diese gehört zur High Society des Königreiches und als Trainer des Sohnes Tom macht Chris ziemlich schnell die Bekanntschaft von dessen Schwester Chloe. Aufgrund gemeinsamer künstlerischer Interessen kommen sich die beiden bald näher und da der junge Mann auch hervorragend mit den Eltern Hewett harmoniert, ist die Hochzeit nur eine Frage der Zeit.

Chris hat damit aus ärmeren Verhältnissen kommend den Sprung nach ganz oben geschafft, da Vater Hewett ihn in seiner Firma einen guten Posten besorgt hat. Doch Chris hat heimlich eine Beziehung zu Nola, der ehemaligen Freundin seines Schwagers Tom. Nola ist eine erfolglose, aber sehr anziehende Schauspielerin, und wird schließlich schwanger von Chris. Dieser ist nun in einer Zwickmühle: Ist er bereit, den erreichten Komfort und die gesellschaftliche Stellung für das gemeinsame Kind mit der Geliebten aufzugeben, oder kann er irgendwie aus dieser misslichen Situation entkommen.

Da ich den Film bereits als Drama bezeichnet habe, gibt es natürlich kein Happy End. Doch am Ende entscheidet scheinbar ein kurzer Augenblick des Glückes darüber, ob die Welt über Chris zusammenbricht: In einer Analogie zu der Einführungssequenz des Filmes trifft ein Ring, welcher eigentlich als Beweisstück in der Themse verschwinden sollte, das Geländer am Ufer und springt danach zurück an Land. Doch ist es wirklich nur Glück, welches das Leben von Chris Wilton bestimmt?

Ich meine nein, denn seine gesellschaftliche Stellung hat sich der junge Mann nur durch sein Talent erarbeitet: Zielstrebig und selbstbewusst hat Chris die Stelle als Tennislehrer in dem Londoner Club angenommen, wo er zwangsläufig die High Society treffen würde. Durch den geschickten Umgang mit den künftigen Schwiegereltern und der späteren Braut Chloe gelingt ihm der Einstieg in eben diese Gesellschaftsschichten, welche ihm ein erfolgreiches Leben als Geschäftsmann ohne Geldsorgen einbringen. Nur mit Glück hätte es Chris niemals bis hierher geschafft.

Doch mit der neuen Stellung wächst auch die Fallhöhe bei einer möglichen Entdeckung, dass seine Geliebte ein Kind von ihm erwartet. Und in dieser entscheidenten Situation geht Chris sein Talent der absoluten Selbstsicherheit verloren. Generell ist seine Beziehung zu Nola von wenig Selbstbeherrschung gekennzeichnet, während sie aufgrund ihres fehlenden Glaubens an sich selber von dem standhaften Charakter angezogen wird.

Jonathan Rhys Meyers verkörpert Chris Wilton sehr eindrucksvoll und sicher, was vor allem in den ersten Gesprächen mit Nola deutlich wird: Er erkennt klar ihre Wirkung auf sich und kann mit ihr darüber reden, ebenso wie sie seinen Versuch erkennt, den Einstieg in die High Society zu schaffen. Und trotzdem gibt er dem Verlangen nach ihr nach, bis es fast zu spät für eine Wende ist. Jetzt fällt plötzlich die starre Maske der Selbstbeherrschung von ihm ab, und er macht den entscheidenden Fehler, welcher sich schlussendlich aber als "Glück" herausstellt.

Dieses hat die von Scarlett Johansson souverän verkörperte Nola nicht, denn als sich Chris schließlich aus Not (und Kalkulation?) für seine Ehefrau und gegen die Geliebte entscheidet, steht sie ihm nur noch im Weg. Sogar die Aufklärung des Verbrechens versagt ihr der Film, denn was für Chris mit dem nicht in die Themse fallenden Ring das Glück bedeutet, ist für sie nur noch "Pech", also die Kehrseite der Medaille. Sie, die sich richtig einzuschätzen wusste, hatte also weder Talent noch Glück.

Ein wenig spielt auch die Gesellschaftskritik in diesem Film mit, wenn Woody Allen Chris Wilton auf dem Polizeirevier ständig wiederholen lässt, dass sie doch bitte diskret aufgrund seiner Stellung und seiner Familie ermitteln sollen. Er ist damit endgültig angekommen in den oberen Schichten, welche er ohne viel Arbeit, aber mit dem Talent der Menschenbeeinflussung und seinem zielstrebigen, selbstsicheren Auftreten erreicht hat. Dies erklärt er auch seinem Kumpel aus den Zeiten als Profispieler: Die Fähigkeiten, um die ganz Großen zu schlagen, besaß er. Aber er konnte niemals den Tennissport leben und wollte nicht sein Leben lang dafür arbeiten. Im Gegenteil diente es ihm als Sprungbrett in die High Society. So ist es kein Wunder, dass er in vollkommener Verkennung seines Talentes lieber das Glück auf seiner Seite sieht, welches ironischerweise (oder als Folge?) zu seinem Talent dazu kommt.

Was mich ein wenig gestört hat an *Match Point* war jedoch der Soundtrack, welcher Alfred Hitchcock alle Ehre gemacht hätte und trotzdem etwas übertrieben wirkte. Die von der Hauptperson so gemochten Opern steigern sich im Laufe der zwei Stunden immer mehr, so dass ich kaum ruhig sitzen konnte im Angesicht des zu erwartenden Finales. Dies will jedoch ewig nicht kommen, und immer wieder zeigt Allen die verstörenden Telefonate von Chris mit Nola. An dieser Stelle des Films ist kaum Bewegung in der Handlung, jedoch wird Chris genau wie die Zuschauer durch diese Art Terror immer weiter zermürbt, bis er schließlich zu der verhängnisvollen Lösung schreitet.

Fazit: Ein ungewohnt unkomischer Woody Allen behandelt in diesem Drama die Frage, welchen Einfluss Talent und Glück eigentlich in unserem Leben haben. Mit sehr genauen Charakterstudien der beiden Hauptdarsteller und einem scheinbar eindeutigen Ende präsentiert der Film eine Antwort auf diese Frage, lässt sich dabei aber etwas zu viel Zeit und quält den Zuschauer mit einem an die Nerven gehenden Soundtrack aus klassischen Opern.
