---
title: "Campus Invaders"
date: "2006-03-09T17:59:21"
categories: [gefunden,getan]
---

Seit gestern ist mein Diplom in trockenen Tüchern und ich kann mich nach dem Lernstress der letzten Wochen nun ausgiebig mit Bewerbungen befassen. Dazu bereise ich in den nächsten Wochen auch fleißig die Republik, um mich in Bewerbungsgesprächen so teuer wie möglich zu verkaufen.

Doch bevor am 31.03. mein Studium ausläuft, werde ich mir noch schnell Tickets für die [MTV Campus Invasion](http://www.mtv.de/campus/) besorgen. Diese kommt dieses Jahr nämlich nach Halle und bringt Xavier Naidoo, Fettes Brot, Tomte und Billy Talent am 17.06. mit auf die Ziegelwiese. Studis bezahlen nur 16€, wenn sie die Tickets beim [StuRa](http://www.stura.uni-halle.de/aktuelles/aktuelles.php?aktion=meldung&nummer=113) am Campus der [MLU Halle](http://www.uni-halle.de/) erwerben.

Für das Geld sehe ich mir gerne erneut die Brote an (ich habe für die Einzelkonzerte immer mehr bezahlt), erst Recht wenn ich als Zugabe noch Tomte erhalte. Und bei Herrn Naidoo kann ich die Veranstaltung ja zur Not verlassen...
