---
title: "The Fall"
date: "2009-08-03T23:33:27"
categories: [gesehen]
---

Dieser Film hat wohl einen der besten [Vorspänne](http://www.artofthetitle.com/2009/01/09/the-fall/) der Filmgeschichte. In fast zu Fotographien erstarrten Schwarz-Weiß-Einstellungen mit unglaublich hohem Kontrast präsentiert Regisseur Tarsem die Vorgeschichte seines Leinwandmärchens: Den Unfall eines der ersten Stuntmänner der Filmgeschichte, als dieser von einer Eisenbahnbrücke auf ein Pferd springen will. Der weiße Dampf der Lokomotive, das klare unter der Brücke dahin strömende Wasser, die Spielereien mit Lichtreflexionen und vor allem die Zeitlupendarstellung zeigen dem Zuschauer, was er die nächsten zwei Stunden zu erwarten hat: Perfekt eingefangene Bilder, von vorne bis hinten ein Kunstwerk.

Wer *The Cell* vom selben Regisseur gesehen hat, kennt dies bereits. Damals war es das Innenlebens eines Serienmörders, die Tarsem mit sehr wirkungsvollen Bildcollagen für das Kino aufbereitete. In *The Fall* erfinden der lebensmüde Stuntman Roy und das kleine Mädchen Alexandria während ihres gemeinsamen Aufenthalts in einem Krankenhaus eine Geschichte, in der sie ihre jeweilige Situation verarbeiten. Roy versucht das Mädchen als Gehilfin für einen Selbstmord einzuspannen, Alexandria dagegen muss die Vertreibung aus der Heimat und den Tod des Vaters verarbeiten.

Daraus entsteht ein Bilderreigen, wie man ihn lange nicht gesehen hat. Doch leider vertraut Tarsem zu stark auf seine zwar wirkungsvollen, aber auf die Dauer des Films doch ermüdenden Einstellungen. Viele Totalen und Panoramen lassen kaum Platz für die Figuren oder Dialoge, zeitweise führt die analog zu Roys Gesundheitszustand dahintröpfelnde Geschichte zu einer Art minutenlangem Stillstand. Dann wiederum führt ein (weiterer) Sturz von Alexandria zu einer schnell geschnittenen Sequenz von Stopmotion-animierten Trick, und auch das Ende mit seiner Huldigung an die Pioniere des Filmstunts passt in seiner Geschwindigkeit so gar nicht zum Rest des Films.

*The Fall* ist also eine visuell überragende Huldigung an das Kino, an seine hinter den Masken versteckten Stuntmänner, Regisseure, Drehbuchautoren und anderen Künstler. Allerdings führt der Entwurf der inneren Geschichte, die den jeweiligen Zustand der beiden Erzähler widerspiegelt, zeitweise zum Stillstand der Handlung und nach zwei Stunden verlieren auch die grandiosen Landschaftsaufnahmen und die kongeniale Farb- und Musikgestaltung an Reiz.
