---
title: "Verliebt in eine Hexe"
date: "2005-09-12T16:27:46"
categories: [gesehen]
---

Eine Lektion, die ich wohl nie lernen werde: Ein guter Trailer macht noch keinen guten Film. Und den Rezensenten der [MZ](http://www.mz-web.de) kann man nicht trauen! Ich hatte mich ja schon darauf eingestellt, eine schleimige Liebeskomödie zu sehen, hoffte jedoch, dass das Hexenthema und Michael Caine den Film für mich retten würden. Doch wie schon so oft wurden im Trailer die besten Szenen des Films vorweg genommen und dem Zuschauer ein Erzähltempo versprochen, welches der eigentliche Film nicht durchzuhalten vermag.

Da kann auch Nicole Kidman sich so nett wie nur möglich geben (für mich wirkte sie einfach nur naiv), die Liebe zu dem übertriebenen Charakter Jack Wyatt scheint keine erkennbare Basis zu haben. Dabei dauert es im Mittelteil des Films länger, dem Glück mit Zauberei auf die Sprünge zu helfen, als es auf die harte Tour mit dem Anschreien zu versuchen - Jacks Verhalten ist in beiden Versionen gleich. Michael Caine ist in seiner Rolle als Hexenmeister und Vater leider sichtlich unterfordert. Seine Auftritte auf Verpackungen und hinter Türen verlieren genauso schnell ihren Reiz wie sich das Hexenthema nach dem Verschwinden der Tante verbraucht hat und bis dahin auch nur auf altbackene Gags setzt. Die witzigen Szenen liegen fast alle zu Beginn des Filmes, danach hat es sich auch mit den Ideen aus der Film-im-Film-Handlung (die männerfeindliche Nina, die Wohnwagen, die Studiocrew). Lieber dürfen Hexe Isabel und Jack viel zu lange in schlechten Dialogen ihre Beziehung ausdiskutieren und vor dem Fernseher Herzschmerzen ausheulen, welches scheinbar ein Standardschema der Regisseurin ist und deshalb zwangsweise in den Film übernommen wurde.

Dazu kommt noch ein abruptes Ende, welches durch einen nicht weiter erklärten Auftritt des halbwegs witzigen Onkel Arthur eingeleitet wird und sämtliche Nebenhandlungen gleich mit abschneidet (Nigel und Iris, Maria und Ritchie). Hier wurde also eine nette Idee trotz einer hervorragenden Besetzung gründlich in den Sand gesetzt. Vielleicht sollte ich in Zukunft solche Filme komplett meiden...
