---
title: "Waldi und Harry und das Tonproblem"
date: "2006-02-22T11:02:44"
categories: [gesehen]
---

Seit Montag ist die spätabendliche ["olympische Zugabe der besonderen Art"](http://sport.ard.de/spe/turin/radiotv/waldi-und-harry.jhtml) der ARD noch unerträglicher als bereits zuvor. Denn auf einmal haben die Toningenieure ihre Mikrofone nicht mehr im Griff, was sich durch extreme Lautstärkeschwankungen äußert. Zeitweilig konnte ich Waldemar Hartmann kaum verstehen, so leise kam der Ton aus dem Fernseher, während noch im selben Satz plötzlich die Lautstärke anschwoll, dass man damit das gesamte Viertel hätte wecken können. Und wer dachte, dass die Sendung vom Montag ein bedauerlicher Aussetzer gewesen sei, der wurde gestern abend eines besseren belehrt. Weitere Aussetzer bei Schnitt und Regie runden das Bild einer billig produzierten Sendung ab, welche der Zuschauer von der ARD nicht gewöhnt ist.

Doch nicht nur die Produktion, sondern auch das Konzept und die Moderation leiden unter Qualitätsmängeln. Grundsätzlich ist die Idee ja nicht schlecht, nach fast 14 Stunden Live-Berichterstattung von den Olympischen Spielen in Turin den Tag mit einigen ironischen Seitenblicken auf die Ereignisse abzuschließen. Doch die präsentierten, redaktionellen Beiträge unterscheiden sich kaum von denen, die der Olympia-Fan schon den ganzen Tag vorgesetzt bekommen hat - das gesamte Olympiaprogramm der öffentlich-rechtlichen Fernsehsender besteht hauptsächlich aus Redundanz, da Randsportarten wie Eishockey oder Curling weniger Zuschauer anziehen als die dritte Wiederholung der Biathleten.

Waldemar Hartmann kann als Hauptwortführer der Sendung jedoch den Sportjournalisten nicht verbergen und sein Stammtischhumor nach Holzfällerart lässt die Interviews mit den erfolgreichen Sportler weder informativ noch witzig geraten. So sitzen die Gäste meist müde und gelangweilt in den unbequem aussehenden Sesseln mit niedrigen Beinen und fragen sich, ob die Fragen nun ernst gemeint sind und warum man sie nach der Medaillenverleihung in Turin auch noch um Mitternacht in das Deutsche Haus nach Sestriere verschleppt hat.

Lichtblicke der Sendung waren bisher nur diejenigen Gäste, welche selber einen gewissen Sinn für Humor mitbrachten (wie Georg Hackl, Hubertus von Hohenlohe oder Rainer Schönfelder). Dann blühte auch Harald Schmidt sichtbar auf, denn belanglose Interviews der unterhaltsamen Art sind seine Stärke. Ansonsten beschränkt er sich meist auf seine Rolle als Waldi-Andrack, die ihm als jahrelanger Chef aber schwer fällt, und unterbricht seinen Co-Moderator immer wieder mit mäßigen Einwürfen. Auch die "Harry avanti" getauften Einspieler, in denen Schmidt Episoden seines Tages präsentiert, sind meist mäßiger Natur. In der ersten Sendung ließ er sich sogar dazu hinreißen, sich ungepflegt vor dem Fernseher sitzend filmen zu lassen. So möchte ich mein Geld auch verdienen...

Dass die Athleten zum Abschied in Anlehnung an einen alten Harald-Schmidt-Witz einen ARD-Schal als Andenken erhalten (ich finde die Schneekugeln viel origineller), passt genau in das Gesamtbild der mäßigen Umsetzung einer guten Idee. So bleibt mir nur zu hoffen, dass Schmidts Rückkehr in den eigenen Chefsessel nicht unter dieser Olympia-Erfahrug leidet!
