---
title: "Die Stadt der träumenden Bücher"
date: "2012-10-03T23:58:21"
categories: [gelesen]
---

*von Walter Moers,
erschienen im Piper Verlag, ISBN 3-492-04549-9, 24,90€*

Hildegunst von Mythenmetz ist ein Lindwurm, und darum will er sein Leben wie alle Bewohner der Lindwurmfeste der Literatur widmen. Als ihm sein Onkel und Dichtpate ein Manuskript vererbt, das Hildegunst als ein perfektes Stück Literatur erkennt, macht sich der junge Drache auf den Weg nach Buchhaim, der Stadt der träumenden Bücher, um den Autoren ausfindig zu machen. Buchhaim besteht fast ausschließlich aus Buchdruckereien, Antiquariaten und Buchhandlungen, doch unter der Oberfläche spannt sich ein jahrhundertealtes Labyrinth, in welchem nicht nur Bücherjäger nach verschollenen Bücher von unschätzbarem Wert suchen, sondern auch die gefährlichen Buchlinge und vor allem der Schattenkönig dem unbedarften Abenteurer nach dem Leben trachten. Auf seiner Suche nach dem Autoren des Manuskripts gerät Hildegunst jedoch in genau diese Katakomben und muss fortan mit all den Gefahren Bekanntschaft machen, vor denen er vorher gewarnt wurde...

*Die Stadt der träumenden Bücher* ist mein erster Walter-Moers-Roman. Doch aufgrund seiner spielerischen Auseinandersetzung mit dem Thema Literatur erwies er sich als idealer Einstieg in die Welt von Zamonien, in der schon die Geschichten von Käpt'n Blaubär spielten. Was Moers dem Leser alles an Ideen auftischt, ist ungemein komisch und sehr unterhaltsam. Allein die Grundidee, dass in Zamonien Bücher einen viel gewichtigeren Teil der Welt darstellen, führt zu unterhaltsamen Analogien wie den Buchimisten und den Bücherjägern. 

Zudem schwelgt Moers viel in Zitaten. Beim Schattenkönig wurde ich an die Golemlegende erinnert, die Buchlinge weckten angenehme Erinnerungen an [Fahrenheit 451](/blog/2010/04/05/ein-tag-funf-filme/). Die Stärke des Buches ist es, diese vielen Ideen zu einer halbwegs funktionierenden Welt zu vereinen, die durch die vielen Illustrationen auch optisch im Gedächtnis hängen bleibt.

Zu schade, dass sich hinter all den Ideen nur die Handlung eines Jugendbuches, eines einfachen Run-and-Hide-Abenteuerromans versteckt. Als Leser möchte ich eigentlich mehr erfahren über die Katakomben, über die Buchlinge, über den Schattenkönig, über die fantastische Welt von Buchhaim - stattdessen schickt mich Moers auf einer Tour-de-Force immer tiefer in das Labyrinth, wo doch von Anfang an klar ist, wo die Reise hingehen wird. Eine weniger geradlinige Handlungsführung hätte dem Roman gut getan; so bleibt am Ende ein gespaltener Eindruck zurück.
