---
title: "Da war mal was..."
date: "2009-08-12T22:36:23"
categories: [gewesen]
---

Der 9. November rückt näher und damit auch der zentrale Termin für den Großteil der [Feierlichkeiten zum 20jährigen Jubiläum des Mauerfalls](http://www.mauerfall09.de). Berlin als ehemaliges Symbol für die Trennung Deutschlands ist das Zentrum für Veranstaltungen aller Art; auf dem Alex kann man bereits eine [Open-Air-Dauerausstellung über die friedliche Revolution](http://www.revolution89.de/) besuchen und ich freue mich besonders auf [die kleine Riesin](http://www.riesen-in-berlin.de), die am Tag der deutschen Einheit ihren Auftritt haben wird, und die [Dominoaktion](http://www.mauerfall09.de/dominoaktion/) am 9.November.

Seit einer Woche nun stellt der [Flix](http://www.der-flix.de) integriert in die [Gedenkstätte Berliner Mauer](http://www.berliner-mauer-gedenkstaette.de/) an der Bernauer Straße Teile seines Comicbandes [Da war mal was...](http://dawarmalwas.de/) aus. Dessen kurze Strips erzählen Episoden aus Zeiten des getrennten Deutschlands, von deutsch-deutschen Schicksalen auf beiden Seiten der Mauer. Es geht um Republikflüchtlinge, Schwule in der DDR und auch Veränderungen, die die Wende mit sich brachte.

Präsentiert werden die acht Comicstrips auf Plakatwänden, weshalb sie mir vor einer Woche aus der Straßenbahn gar nicht aufgefallen sind. Heute jedoch bin ich nach dem Beachvolleyball einfach die eine Tramstation gelaufen und habe mir die Ausstellung angesehen. Es ist schon cool, Comics auf dieser Größe zu sehen, und durch die Integration in die frei begehbare Gedenkstätte wird auch einem großem Publikum die Chance gegeben, sich auf diese spannende Weise mit der noch jungen Vergangenheit auseinanderzusetzen. In kleinerer Form (in der rechten unteren Ecke) finden sich alle Strips auch mit englischen Texten für die nicht wenigen internationalen Gäste meiner Wahlheimat.

Eine tolle Idee also mit einer interessanten Umsetzung. Die schlechte Erkennbarkeit als Ausstellung durch die Ähnlichkeit mit echten Werbeplakatwänden (vor allem aufgrund der Platzierung am Rand des Bürgersteigs) relativiert sich zum Glück durch die vielen davor anhaltenden Besucher. Ich empfehle: Hingehen, Anschauen, Wirken lassen!
