---
title: "Technik, wie sie sein sollte"
date: "2009-03-29T16:50:26"
categories: [getan]
---

Man darf sich nicht auf die Informationen verlassen, die man im Internet findet. Vor dem [Kauf meiner Playstation3](/blog/2008/09/21/kubuntu-runs-my-playstation/) habe ich nämlich ausgiebig nach den Fähigkeiten des eingebauten WLAN-Chips gegoogelt und bin immer wieder bestätigt worden, dass [WPA2](http://de.wikipedia.org/wiki/WPA2) nicht möglich ist. Also habe ich die Konsole über ein Netzwerkkabel angeschlossen - mein WLAN-Router wird bei WPA2 bleiben - und das Thema als abgeschlossen betrachtet.

Doch nach der [Installation eines selbstkompilierten 2.6.28er Kernels](http://psubuntu.com/forums/viewtopic.php?f=4&t=758) und dem Folgen dieser [Anleitung](http://psubuntu.com/forums/viewtopic.php?f=4&t=688) konnte ich mich plötzlich unter Ubuntu an mein drahtloses Netzwerk anmelden. Und siehe da, dies funktioniert auch unter dem PS3-Betriebssystem und seit heute nachmittag ist ein weiteres Kabel in meinem Wohnzimmer Geschichte.

Für alle Suchenden im Netz hier also die gute Nachricht: Ja, die PS3 beherrscht WPA2.

Und mit dem neuen Kernel war es ebenfalls möglich, das Image einer Blu-Ray zu ziehen. Mit 1,8 MB/s dauerte der Kopiervorgang der über 40 GB zwar unglaublich lange, aber so war ich endlich in der Lage, die UK-Version von [The Colour of Magic](/blog/2008/08/17/the-colour-of-magic/) auch in der enthaltenen 1080i-Version auf meinem [WD TV](/blog/2009/02/21/mein-neues-spielzeug/) zu betrachten - die PS3 verweigerte mir dieses Vergnügen und spielte ausschließlich 576p ab. Jetzt muss ich es nur noch schaffen, dass das Ubuntu auf meiner Konsole vollständig herunterfährt und sich dabei nicht aufhängt. Aber irgendetwas ist ja immer...
