---
title: "Louise hires a Contract Killer"
date: "2009-08-22T20:50:34"
categories: [gesehen]
---

*Frankreich (2008)
Regie: Gustave de Kervern & Benoît Delépine
Darsteller: Yolande Moreau (Louise Ferrand), Bouli Lanners (Michel Pinchon) und andere Auftragsmörder*
[Offizielle Homepage](http://www.koolfilm.de/LouiseMichel/louisemichel.php4)

[Louise Michel](http://de.wikipedia.org/wiki/Louise_Michel), so der Originaltitel dieses Films, ist eigentlich eine französische Anarchistin. Dies passt ganz gut zu dieser schwarzen Komödie, in welcher der Name auf zwei Hauptdarsteller aufgeteilt wird.

Louise ist eine Fabrikarbeiterin, deren Arbeitsplatz von einem Tag auf den anderen nach Asien verlagert wird. Von ihrer Abfindung will sie nun aus Rache einen Auftragskiller beauftragen, den Ex-Chef zu ermorden. Da so ein Assassine nicht leicht aufzutreiben ist landet Louise schließlich bei Michel, der zwar nicht selbst abdrücken kann, aber immer jemanden auftreibt, der die Aufträge für ihn ausführt. Doch schnell muss das ungleiche Paar feststellen, dass der Chef selber einen Chef hat und dieser wiederum einen anderen...

Eine ungewöhnliche Mischung für eine französische Komödie fahren die beiden Regisseure hier auf. Da sind auf der einen Seite die schrullig-doofen Charaktere (Grundzutat des schwarzen Humors), die nicht nur durch die verwirrenden Geschlechterrollen auffallen, sondern auch durch ihre Gegensätze. Louise ist einsilbig, aber direkt und entschlossen, wo hingegen Michel quatscht ohne Ende aber sich nicht durchzusetzen weiß.

Auf der anderen Seite kann man den Film durchaus sozialkritisch nennen. So, wie er das Umfeld seiner Unterschichtencharaktere zeichnet, ist dies nicht nur skuriler Hintergrund der Geschichte, sondern durchaus ein Anprangern der Verhältnisse. Allein gelassene Rentner, Sozialwohnungsghettos, Flüchtlingsschmuggler und im Krankenhaus unmenschlich dahinsiechende Todkranke die nur noch sterben wollen - der Film geht überall dort hin, wo es weh tut. Zudem wird über eine Gegenüberstellung der Gewinner der Globalisierung das gesamte Ausmaß der auseinanderklaffenden Schere zwischen Armut und Reichtum deutlich. Die abgehobenen Firmenkonstrukte mit ihren Finanzjongleuren lassen keine Sympathien bei den Zuschauern aufkommen. Die Charaktere sind zwar alle als Karikaturen angelegt, aber es steckt dennoch viel Wahrheit dahinter.

Und wie es sich für das Genre gehört gibt es neben dem trockenen Dialogwitz auch das eine oder andere unnatürliche Ableben zu belächeln. Dabei gibt es keine Tabus für das Regie-/Autorenduo, wie die Wahl des Filmtitels schon ankündigt. Dies ist vielleicht der Grund, warum der Start in Deutschland sich um fast ein Jahr verzögert hat. Manche Szenen bleiben trotzdem im Kontext der Filmhandlung unverständlich, so die Einäscherung zu Beginn und die Nachstellung der Anschläge auf das WTC. Nur in der Lesart der Globalisierungskritik ist ein Sinn erkennbar, der sich aber ganz gut zu verstecken weiß.

Fazit: Wer böse, schwarze Komödien mag, der sollte sich auch *Louise Michel* ansehen. Schrullige Charaktere, trockener Humor und dazu noch Gesellschaftskritik sind die Zutaten für diesen unterhaltsamen Mix. Wenn auch einige Szenen nur in letzterem Kontext überhaupt einen Sinn ergeben, der Film ist auf jeden Fall sehenswert.
