---
title: "The Elder Scrolls V Skyrim – Mein Tagebuch, Teil 3"
date: "2012-02-04T13:00:00"
categories: [gespielt]
---

Ich muss [alle meine Bedenken](/blog/2011/12/26/the-elder-scrolls-v-skyrim-mein-tagebuch-teil-1/), die ich vor dem Spielen über *Skyrim* hatte, revidieren. Abgesehen von der eher trostlosen nordischen Umgebung ist das Spiel sehr abwechslungsreich und die Welt alles andere als tot. Im Gegenteil, selbst im einsamsten Sumpf ist noch ständig etwas los. Ob nun Kuriere dem Spieler eine Nachricht überbringen, Assassinen oder Diebe ihre Fähigkeiten überschätzen, eine angeheuerte Bande Raufbolde den Spieler für einen Diebstahl bestrafen soll oder er kurz hintereinander einem Fremdem mit einem gestohlenen Schild und danach dessen Verfolger begegnet - auf der Suche nach Mitstreitern gegen starke Gegner wie den Riesen oder einem Drachen wird man schnell fündig.

Außer in der umfangreichen Oberwelt ist der eigene Charakter sicherlich die Hälfte der Spielzeit in Dungeons unterwegs. In Sachen Gegner und Namen sind diese meist austauschbar (Bruchzahnhöhle, Grauwassergrotte, usw), jedoch verbindet das Spiel die meisten Quests mit seiner dichten Hintergrundgeschichte und macht damit jede Höhlenerfahrung zu einem einzigartigen Erlebnis. Meine Highlights waren bisher die Ausräucherung eines Vampirversteckes (wo ich mich gleich mit Vampirismus ansteckte), eine Rätselei im Kopf des wahnsinnigen Ex-Kaisers Pelagius, der Kampf gegen die wieder auferstandene Totenbeschwörerin und Wolfskönigin Potema oder die verwirrte Argonierin, die dem Spieler eine als Zwergenlexikon bezeichnete Box überreicht und bittet, sie nach Avanchnzel zurückzubringen, wo sie das Lexikon in einer gescheiterten Mission erlangt hat und nun von dessen Wissen übermannt wird.

Avanchnzel stellte sich als einer der seltsamen im Stil des Steampunk entworfenen Dungeons der Dwemer (Zwerge) heraus, die voll sind von metallen-mechanischen Gerätschaften, aus denen unentwegt Dampf wie aus Dampfmaschinen entweicht. Die Gegner, mechanische Spinnen und roboterartige Sphären, die von den im Spiel wichtigen Seelen angetrieben werden, ließen mich darüber hinwegsehen, dass die Zwerge in *Skyrim* aus der Welt verschwunden sind und ich sie folglich auch nicht als Rasse für meinen Charakter wählen kann.

Aber sie zeigen sehr gut, wie Bethesda ihre The-Elder-Scrolls-Saga mit einer Geschichte angereichert hat, die umso plausibler erscheint, weil der Spieler nirgendwo auf Gewissheiten trifft. Es gibt zwar Geschichtsbücher ohne Ende zu lesen, doch das Spiel lässt den Spieler an den eigenen Dokumenten zweifeln, wenn er im Zuge der Bardenakademie-Quest "König Olafs Vers" davon erfährt, wie der namensgebende Herrscher dafür sorgte, dass sich die Nachwelt positiv an ihn erinnerte.

Für fast alle kritischen Fragen im Spiel gibt es keine klare Aussagen, sondern viele Perspektiven der NPCs, die alle nachvollziehbar sind. So hat das Kaiserreich mit den Thalmor, einem Elfenbund, einen Waffenstillstand geschlossen, bei dem sie im Ausgleich den von den Einwohnern *Skyrims* zum Gott Talos erhobenen ehemaligen Kaiser und Drachenblut Tiber Septim abschwören. Was für die Kaiserlichen das unter Schmerzen erkaufte Ende eines Krieges ist, sieht aus Sicht der Nord aus wie eine Verleugnung ihrer Geschichte und damit eines wichtigen Bestandteiles ihrer Kultur.

Neben dieser über eine unglaubliche Menge an benannten NPCs mit jeweils eigener Sprachausgabe erzählte Hintergrundgeschichte muss ich auch die Bugfreiheit des Spiels loben, denn Spiele mit vergleichbarer Komplexität (*Gothic III*) haben da unrühmliche Maßstäbe gesetzt. Einzig mit seinen Begleitern muss der Spieler etwas Geduld haben. Deren Wegfindung ist nicht optimal und so läuft der eigene Charakter oft einen Vorsprung heraus und muss öfters warten. Zudem haben meine bisherigen Begleiterinnen die dumme Angewohnheit, Türen und enge Gänge zu blockieren und erst spät zu bemerken, dass ich eigentlich da durch will, wo sie stehen. Dafür haben sämtliche bedienbaren Gerätschaften (Schmieden, Alchemietische, ...) ein Komfortfeature: Ist das Gerät besetzt durch einen NPC, dann entfernen sich diese davon, wenn der Spieler versucht, es zu benutzen.

An anderer Stelle lässt *Skyrim* dafür Komfort vermissen. So gibt es sich sehr faul wenn es darum geht, dem Spieler wichtige Informationen über seinen Charakter zu visualisieren. Wurde der Charakter vergiftet oder hat einen Trank mit zeitlich begrenzter Wirkung zu sich genommen, dann findet der Spieler dies nur heraus, indem er sich tief in die Menüstruktur begibt und unter Aktive Effekte nachschaut. Auf dem Bildschirm selber ist von diesen Effekten nichts zu sehen; allenfalls sind sie bei stark wirkenden Giften zu spüren. Die einzige Anzeige, die Bethesda dem Spieler neben Gesundheit, Magicka und Ausdauer gönnt, ist ein Balken mit den verbleibenden Aufladungen einer verzauberten Waffe, und auch dieser ist nur bei Schlägen zu sehen und wird sonst ausgeblendet. Ganz nervig sind für mich zudem die untoten Draugr-Krieger, welche die Fähigkeit besitzen, meinem Charakter die Waffe aus der Hand zu schlagen. Da ich nicht in der Egoperspektive, sondern in der Third-Person-Variante spiele, bemerke ich während Kämpfen in schlecht ausgeleuchteten Dungeons oft nicht sofort, dass ich plötzlich ohne Schild und Streitkolben dastehe und den Gegner mit Fäusten attackiere. Wenn solche wichtigen Ereignisse einfach mit markanten Einblendungen signalisiert werden würden, wäre das eine deutliche Verbesserung des Spiels. Da lobe ich mir im Vergleich *Drakensang* mit seiner Auskunftsfreudigkeit, die jede spielbeeinflussende Änderung sofort erkennen lässt.

Dass *Skyrim* eher in der von mir ungeliebten Ego-Shooter-Perspektive gespielt werden soll, merkt man auch beim Zielen mit dem Bogen. Je nach Platzierung des Zieles kann sich durchaus der Körper des eigenen Charakters vor das Fadenkreuz schieben und das Zielen damit schwerer machen. Aber das ist ebenso wie das aufgrund des begrenzten Inventars ständig notwendige Micromanagement nur eine kleine Randerscheinung, die vollkommen untergeht neben all den Pluspunkten, die mich inzwischen schon fast 50 Stunden an das Spiel gefesselt haben - und mit Level 28 und noch vielen offenen Quests ist ein Ende nicht absehbar.
