---
title: "Stand der Technik"
date: "2008-01-21T21:45:33"
categories: [gedacht,gefunden]
---

Ein paar Google-Sessions betreffend des Sony-Players aus meinem [letzten Beitrag](/blog/2007/12/20/nicht-ohne-fernbedienung/) haben ergeben, dass dieser statt mit einer Fernbedienung mit einem [Bluetooth-Transmitter](http://www.sonystyle.com/webapp/wcs/stores/servlet/ProductDisplay?catalogId=10551&storeId=10151&langId=-1&productId=8198552921665086641) erweitert werden kann. Sollte dieser zusätzlich zu [A2DP](http://de.wikipedia.org/wiki/A2DP) auch das BT-Profil [AVRCP](http://de.wikipedia.org/wiki/AVRCP) unterstützen, dann hätte ich alle Funktionen beisammen, die ich von einer Fernbedienung verlange: Play/Pause, Vor, Zurück, Lautstärke regeln - im Idealfall sogar ein Ordnerwechsel. Die Kopplung zweier BT-Geräte scheint ja inzwischen so gut zu funktionieren, dass Heise seine [Bluetooth-Datenbank](http://www.heise.de/mobil/bluetooth/db/) nicht mehr aktualisiert. Trotzdem wurmt es mich etwas, dass ich keine Erfahrungsberichte zu Sonys BT-Adapter finde. Mich würde die Qualität der am anderen Ende empfangenen Musik interessieren.

Nachteil dieser drahtlosen Lösung ist der stolze Preis von 50€ zusätzlich zu den Anschaffungskosten für einen entsprechenden BT-Empfänger am Kopfhörer. Andere Player liefern zumindest den Sender schon eingebaut mit und werden damit nicht in die Steinzeit der Akkulaufzeiten zurückgeworfen: Sieben Stunden maximal verspricht Sony, da muss ich den Akku genauso oft laden wie bei meinem aktuellen iRiver-Player nach drei Jahren Dauernutzung. Ganz zu schweigen von den Empfängern, die es scheinbar nicht mit wechselbarem AAA-Akku gibt. Zumindest kann man bei Ausfall der BT-Stromversorgung am Kopfhörerende diese noch in die analoge Buchse des Players stecken und weiterhören.

Eine mögliche Doppelnutzung des Empfängers als Freisprecheinrichtung im Auto scheitert leider momentan noch an meinem Handy, welches A2DP nicht unterstützt (SE W810i). Außerdem bräuchte ich dafür wie für IP-Telefonie am Laptop Kopfhörer mit Mikrofon, welches ich für den MP3-Player definitiv nicht benötige.

Ich werde mir wohl noch einige Wochen den Kopf zerbrechen, bevor ich eine endgültige Entscheidung treffe. Ich vermute nur, dass in den ersten drei Monaten nach Weihnachten weder viele Produktneuheiten den Markt erreichen noch die Preise signifikant nach unten gehen. Aber vielleicht finde ich auch noch irgendwo den Geheimtipp, der in mir den Kauftrieb weckt...

