---
title: "Die zu direkte Demokratie"
date: "2009-05-26T22:21:23"
categories: [gedacht]
---

Ich bin letzten Samstag, parallel zur Abstimmung der Bundesversammlung über unser ~~neues~~ altes Staatsoberhaupt, im Auto nach Berlin gefahren und hatte das zweifelhafte Vergnügen, auf dem [InfoRadio](http://www.inforadio.de/) über eine Stunde Live-Übertragung aus dem Reichstag mitzubekommen. Es gab keine weiteren Programmschwerpunkte, also durften ein paar Moderatoren über das stinklangweilige Geschehen während der hinter verschlossenen Türen stattfindenden Auszählung berichten; Journalismus von der traurigsten Sorte.

[Um **14:11** herum](http://www.tagesspiegel.de/zeitung/Die-Dritte-Seite-Horst-Koehler-Bundespraesident;art705,2805131) soll sich das Ergebnis der Auszählung im Plenarsaal verbreitet haben; die offizielle Verkündigung erfolgte dann nach der Ankunft des wiedergewählten Amtsinhabers gegen **14:30**, was sich mit meiner Erinnerung an die Live-Übertragung deckt. Die Moderatoren des *rbb* amüsierten sich in der Zwischenzeit über Bundestagspräsident Lammert, der vor der Tür nur am Telefon hing und anscheinend Horst Köhler erst aus dem Mittagsschlaf im Schloss Bellevue holen musste.

Nun gibt es heute einen großen [Aufschrei in den Medien](http://www.sueddeutsche.de/politik/316/469868/text/), denn die Bundestagsabgeordnete und damit wahlberechtigte Journalistin Julia Klöckner hat das Ergebnis des Wahlgangs schon um **14:18** per Twitter an alle ihre Follower verteilt und damit quasi öffentlich gemacht. Also fast eine Viertelstunde vor der offiziellen Verkündung. Die *SZ* hält dies für eine Ausnutzung ihrer Funktion als Beteiligte an der Stimmenauszählung und sieht "eines der ehrwürdigsten und wichtigsten Prozedere der Bundesrepublik [...] beschädigt". In der Argumentation kommt es noch schärfer: Wenn Vertraute und Journalisten von Politikern aus wichtigen Sitzungen und Wahlen per SMS informiert werden, dann ist dies ok, weil es kein öffentlicher Vorgang ist, sondern ein gegenseitiges Geben und Nehmen.

Nach dieser Ansicht hat Julia Klöckner für ein paar Wahlkampfsympathiepunkte einen elitären Kreis durchbrochen - nämlich dem gemeinen Volk dieselben Informationen zukommen lassen, die alle anderen in der Bundesversammlung zu diesem Zeitpunkt bereits hatten. Und das Ganze ist nur zum Problem geworden, weil ausgerechnet unser aller Staatsoberhaupt sich nicht an den Zeitplan hielt und zu dem von Lammert angekündigten Zeitpunkt (**14:00**) den Plenarsaal erreichte.

Es gibt also auch in dieser westdeutschen Form der Demokratie noch Menschen, die sind gleicher als andere. Dass es ausgerechnet der Bundespräsident sein muss, dem immer so viel Volksnähe nachgesagt wird, obwohl er wohl das am indirektesten gewählteste Amt des Staates ist, ist dabei nur Ironie am Rande. Ich befürworte die direkte Form der Demokratie der Julia Klöckner, denn sie übt Druck aus auf die etablierten Strukturen im Berliner Machtapparat. Eine so sinnlose verkomplizierte Prozedur wie die Bundespräsidentenwahl kann ruhig eine Modernisierung verkraften, inklusive mehr Disziplin der Wahlberechtigten. Wenn alle das Ergebnis zur selben Zeit erfahren - das beinhaltet Wähler, Gewählte und auch die betroffenen Bürger des Landes - dann kann es zu solchen Situationen gar nicht kommen. Aber das werden unsere Volksvertreter hoffentlich auch noch erkennen...
