---
title: "Donnie Darko"
date: "2007-08-03T23:07:42"
categories: [gesehen]
---

*USA (2001)
Regie: Richard Kelly
Darsteller: Jake Gyllenhaal (Donnie Darko), Jena Malone (Gretchen Ross), Mary McDonnell (Rose Darko), Holmes Osborne (Eddie Darko), James Duval (Frank), Patrick Swayze (Jim Cunningham), Katharine Ross (Dr. Lilian Thurman), Drew Barrymore (Karen Pomeroy), Beth Grant (Kitty Farmer), Maggie Gyllenhaal (Elizabeth Darko), uvm*
[Offizielle Homepage](http://www.donniedarkofilm.com/)

Endlich habe auch ich es geschafft, diesen oft gelobten Kultfilm zu sehen, und bin dafür heute etwas später auf Arbeit gegangen. Doch ich bin froh darüber, bis kurz vor 1h nachts vor dem Fernseher gesessen zu haben, denn Donnie Darko ist einfach ein herrlich bizarrer Film.

Der titelgebende Antiheld ist Collegestudent, Außenseiter und in psychiatrischer Behandlung. Eines Tages fällt aus dem Nichts eine Flugzeugturbine auf das Haus seiner Eltern, genau in sein Zimmer, und Donnie überlebt nur, weil ein menschengroßer, hässlicher Hase namens Frank ihn vorher aus dem Haus gerufen hat. Dieser kommt angeblich aus der Zukunft und kündigt den Untergang der Welt in 28 Tagen an...

Viele Interpretationen des Filminhalts finden sich im Netz, wobei ich mich jetzt an einer von David Lynch inspirierten Traumdeutung wagen will. Der Ansatzpunkt dafür ist zum Einen, dass sich der Turbinenabsturz wiederholt (nur mit dem Unterschied, dass [Donnie am Ende stirbt](http://www.threadless.com/product/844/Spoilt)), und zum Anderen alle Ereignisse dazwischen dazu neigen, entweder Donnies Wunschvorstellungen zu entsprechen oder einfach nur seltsame Zusammenhänge zu bilden.

Zur ersten Kategorie gehört zum Beispiel die Liebesbeziehung zu Gretchen. Erst entwickelt sich diese, wie es sich Donnie nur wünschen kann, und dann wird es immer bizarrer, da sich Gretchens Lust auf ihn genau dann steigert, wenn es ihr schlecht geht. Das gleiche Schema passt auf Lehrerin Karen. In ihrem Kurs ist Donnie der einzige, der mit der leicht anspruchsvollen Literatur zurecht kommt, doch dann fliegt sie von der Schule, da sie von den konservativen Standards abweicht. Donnie selber gefällt sich in der Rolle des Märtyrers: Er stellt den gefeierten Jim Cunningham vor der gesamten Schule und später der Stadt bloß, beleidigt eine verhasste Lehrerin und bekommt dafür auch noch unmissverständlichen Applaus von seinen Eltern. Die Spiele, die er unter der angeblichen Hypnose seiner Psychaterin aufführt, passen auch ganz gut zu seinen etwas kranken Fantasien.

Die merkwürdigen Verbindungen, die ein schlafender Geist bei der Verarbeitung der am Tage gesammelten Erinnerungen zwischen Ereignissen herstellt, manifestieren sich z.B. in dem Umstand, dass die senile Oma Death angeblich das Buch über die [Psychologie des Zeitreisens](http://www.donnie-darko.de/philosophy_of_time_travel.htm) geschrieben hat, dass der Frank aus der Zukunft ein Einschussloch im linken Auge hat, wohin Donnie dann schließlich die Kugel lenkt oder dass seine Mitschülerin hässliche Hasenbilder malt, was zu der grässlichen Maske von Frank führt.

Diese Interpretation lässt dabei bewusst das Thema Zeitreisen / Paralleluniversen aus, welches vom [Regisseur und Drehbuchautoren als Lösungsansatz propagandiert](http://de.wikipedia.org/wiki/Donnie_Darko) wird. Dieser sollte es eigentlich besser wissen als ich, doch ich finde meinen Ansatz ebenfalls recht einleuchtend.

Zu guter Letzt noch ein paar Worte zu der filmischen Umsetzung. Diese lebt vor allem von Hauptdarsteller Jake Gyllenhaal, der den missverstandenen Außenseiter bei seinen Versuchen, die Geschehnisse zu verstehen, mit Leib und Seele ausfüllt. Sein morbides Lächeln, wenn er mit Frank redet, ist das Highlight des Filmes. Dazu kommen der gute Soundtrack und die vorsichtig eingestreuten Special Effects, die den seltsamen Charakter und die düstere Atmosphäre unterstützen.

Fazit: Wer bisher noch nicht die Gelegenheit hatte, diesen Film zu sehen, der sollte dies schnellstmöglich nachholen. Donnie Darko ist einfach ein Highlight der Independentfilmkunst, das zwischen den Genres pendelnd noch am besten mit den Werken von David Lynch zu vergleichen ist - große Interpretationsspielräume eingeschlossen.
