---
title: "Live is live"
date: "2008-08-17T13:13:18"
categories: [gedacht,gelesen]
---

Die olypmischen Spiele stellen die übertragenden Sendeanstalten vor ein großes Problem: Zu viele Entscheidungen finden parallel statt; was also soll den Zuschauern präsentiert werden? Momentan ist diese Wahl bei der ARD auf Leichtathletik gefallen. Aus Sicht der zu maximierenden Einschaltquoten ist dies sicherlich eine vertretbare Entscheidung.

Leider bin ich aber Tennis-Fan und als solcher stark an dem ebenfalls gerade laufenden Finale Nadal gegen Gonzales interessiert. Also habe ich die Sendepläne der digitalen ARD- und ZDF-Programme inspiziert und bin auf den ZDF infokanal gestoßen, den ich zwar nicht übers analoge Kabelnetz empfange, der jedoch in der ZDF mediathek einen Livestream anbietet.

Nach der Auswahl der einzigen technischen Kombination, die auf meinem Rechner ein sich bewegendes Bild zeigt, folgte jedoch die Ernüchterung: Der *Live*stream zeigt nur eine Aufzeichnung des Damenfinales vom Vormittag (MEZ). Da auf dem ebenfalls angebotenen Stream des ZDF dokukanals eine Sendepause herrscht, weiß ich leider nicht, ob nur der Stream nicht überträgt oder ich wirklich das Bild sehe, dass gerade über den Sender läuft.

In letzterem Fall wäre dies schon eine große Enttäuschung, denn die ZDF mediathek ermöglicht sowohl Livestreams als auch Aufzeichnungen anzusehen. Einen Livestream für eine Aufzeichnung zu missbrauchen zeugt davon, dass die verantwortliche Redaktion ihre technischen Möglichkeiten nicht richtig zu nutzen weiß. Nadal hat das Finale übrigens gewonnen und gerade berichtet die ARD nachträglich davon; aber live ist für mich etwas anderes.

**Nachtrag:**

Ein weiteres Live-Highlight während dieser olympischen Spiele war der Liveticker auf spox.com, der trotz weiter laufender Entscheidungen Feierabend machte. 
