---
title: "Risen"
date: "2010-10-24T23:08:08"
categories: [gespielt]
---

Mit dem Kauf meines neuen Laptops war es mir endlich möglich, den inoffiziellen Nachfolger meiner Lieblings-Rollenspiel-Serie *Gothic* zu spielen. Also habe ich die Gelegenheit beim Schopfe gepackt und mir die kürzlich erschienene Game-of-the-Year-Edition des Spiels zugelegt. Diese enthält neben der leider ungepatchten Verkaufsversion von *Risen* auch ein Original des bereits 2006 erschienenen *Gothic III* und eine DVD mit Interviews der Macher.

Piranha-Bytes-typisch schlüpft der Spieler wieder in die Rolle eines namenlosen Helden, der weder in Aussehen noch anfänglichen Attributen angepasst werden kann. Dieser hat sich als blinder Passagier auf das Schiff des mächtigen Inquisitors geschlichen und muss mit ansehen, wie das Schiff im Kampf gegen einen Titanen untergeht. Die Titanen in *Risen* sind riesige Geschöpfe aus uralten Zeiten, die mit dem Verschwinden der Götter aus ihrem Schlaf aufgewacht sind und die Menschheit zu zerstören drohen. Der Inquisitor will dies verhindern, und so landet der namenlose Held als Schiffbrüchiger mit diesem auf einer Insel, auf der eine magische Flamme in einem Vulkan die Menschheit wie ein Schutzschild vor den Titanen schützt. Der Spieler muss fortan herausfinden, was es mit dieser Flamme und den seltsamen Tempeln auf der Insel auf sich hat und welche Pläne der Inquisitor verfolgt.

Für mich als *Gothic*-Veteranen fiel der Einstieg in *Risen* nicht schwer. Im Vergleich zu den vorhergehenden Piranha-Bytes-Spielen hat sich nicht viel getan. Es gibt wie immer drei Fraktionen, unter denen der Spieler wählen kann; es gibt drei grundsätzliche Skillrichtungen (Nahkampf, Fernkampf, Magie) und eine Menge Nebenfertigkeiten wie Diebeskunst, Schmieden und Tiere ausnehmen. Wer jemals ein Spiel der *Gothic*-Reihe gespielt hat wird sich sofort zurechtfinden, denn große Unterschiede in der Spielmechanik finden sich nicht.

Dabei hat Piranha Bytes aus den Fehlern des Bug-Ungeheuers *Gothic III* gelernt. Alles ist eine Nummer kleiner und weniger umfangreich als im Vorgängerspiel. Die Spielewelt der nicht näher benannten Insel reiht sich in Sachen Größe zwischen den ersten beiden *Gothic*-Teilen ein. Der teilweise komplex schöne Talentbaum wurde etwas entschlackt, so dass zum Beispiel Upgrades der Waffen durch Schleifen oder Gifte weggefallen sind. Der Kampf mit zwei Schwertern findet sich ebenfalls nicht mehr - ein Leveln von Geschicklichkeit ist somit Geschichte für den Nahkämpfer, da auch Diebesfertigkeiten wie Schlösser knacken oder Taschendiebstahl unabhängig davon sind. Im Vergleich zu anderen Rollenspielen fehlt es *Risen* weiterhin an umfangreichen Ausrüstungsmöglichkeiten. Die Optionen beschränken sich auf eine Rüstung, einen Helm und ein Schild (bei einhändigen Waffen), dazu zwei Ringe und ein Amulett. Und viel Auswahl für diese Slots gibt es nicht.

Dafür sind die grundsätzlichen Kampftechniken (Schwertkampf, Axtkampf, Stabkampf, Bogen, Armbrust) nun in 10 Stufen ausbaubar. Einhand- und Zweihandwaffen werden gleich behandelt bzw ab einer gewissen Stufe sind Zweihandwaffen (Schwert oder Axt) auch einhändig zu tragen. Mir persönlich gefallen Nahkämpfer mit schnellen Waffen meist am Besten, und aus meiner Sicht habe diese einen klaren Vorteil gegenüber Fernkämpfern und Magiern - sie benötigen keine sich verbrauchende Munition wie Pfeile oder Mana. Das für das Erlernen von Zaubern benötigte Attribut Weisheit schließlich hat eine Sonderstellung im Spiel: Es wird von keinem Lehrer gelehrt, sondern nur durch Lesen von Büchern und alten Tafeln gesteigert. Den Maximalwert von 200 hat mein Nahkämpfer so problemlos erreicht.

Beim Thema Lernen blieb ansonsten alles beim Alten. Die durch das Sammeln von Erfahrungspunkten erreichten Charakterstufen werden mit Lernpunkten belohnt, die zusammen mit Münzen bei Lehrern gegen Fortschritte in den Primärattributen oder Fertigkeiten eingetauscht werden können. Gerade im Umgang mit dem Schwert wird der Spieler so flexibler im Kampf, jedoch hatte ich Schwierigkeiten, die neu gelernten Attacken sofort sinnvoll einzusetzen. Die Lehrer erzählen nur, was der Spieler lernt, aber ausprobieren kann man das Erlernte ausschließlich in Kämpfen, was schnell zum Heldentod oder dem Verlust der gesammelten Münzen führen kann. Ich würde mir wünschen, dass die Lehrer stattdessen mit dem Charakter ein Duell bestreiten, bei dem ich gefahrlos die neue Technik ausprobieren kann. 

So fällt der Einstieg leider unnötig schwer. Anfangs fehlt es dem Spieler noch an Geld, um die meisten Aufträge durch Bestechung auszuführen, und an Kraft, um sich mit den Gegnern zu prügeln. Da gerade die Banditen-Storyline teilweise keine anderen Lösungsmöglichkeiten anbietet, ist zu Beginn des Spiels viel Frust angesagt. Ich spiele mittlerweile nur noch im leichtesten Schwierigkeitsgrad, der zwar manchmal zu einfach ist, aber zumindest Spaß macht, da ich nicht ständig sterbe. Schon auf Stufe normal verkommen die Kämpfe ansonsten zu einem endlosen Verstecken hinter dem eigenen Schild und vielen Versuchen, mit einem Schlag die Deckung des Gegners zu durchbrechen. Da erst mit Angriffskombinationen kritische Treffer möglich sind, allerdings die Gegner kaum die nötigen drei Schläge zulassen, musste ich mich anfangs damit begnügen, erst nach Dutzenden von Treffern den Kampf zu gewinnen. Durch einen einfacheren Spieleinstieg hätten die Entwickler einiges an Frust verhindern können.

Aber gut, dies bin ich eigentlich von der *Gothic*-Reihe gewohnt. In Teil II musste der Spieler in der ehemaligen Strafkolonie die Burg erreichen und hatte dabei die Optionen, durch eine Belagerung der zu diesem Zeitpunkt zu starken Orks zu brechen oder durch einen Fluss zu schwimmen, in dem sich genauso tödliche Snapper herumtrieben. Solche Wahlmöglichkeiten zwischen Pest und Cholera gehören einfach nicht ein sorgfältig ausbalanciertes Spiel.

So bleibt regelmäßiges Speichern neben einem guten Autosave Pflichtaufgabe, denn zu oft läuft man aus Versehen in eine Gruppe von überlegenen Gegner und hat nur selten die Chance, den Kämpfen lebend zu entkommen. Dabei ist gerade die offene Spielewelt, die dem Spieler nur Grenzen über solche starken Gegner setzt, die große Stärke von *Risen*. Theoretisch kann man überall hin laufen und jede Höhle, jeden Berg und jede Ruine erkunden. Praktisch ist dies jedoch erst ab Mitte des Spiels sinnvoll, will der Spieler nicht durchgängig Kämpfen aus dem Weg gehen, indem er an der aggressiven Fauna vorbeischleicht, die die Insel in großer Dichte bevölkert.

Wo in Spielen wie der *Elder-Scrolls*-Serie gähnende Leere herrscht und *The Witcher* und die Bioware-Rollenspiele den Spieler durch enge Wege lenken, fasziniert *Risen* durch seine lebendige Welt, die trotz der örtlichen Nähe zwischen Hafenstadt, Vulkanfestung und Banditenlager realistisch erscheint. Als Beispiel für das Funktionieren dieser Welt sei der Spion Doyle genannt, der nach seiner Enttarnung dem Helden verspricht, so zu verschwinden, dass ihn niemand findet. Wer jedoch richtig sucht, kann Doyle schließlich ganz oben an einem Wasserfall auf einer kleinen Ebene entdecken, die nur durch Levitation zu erreichen ist (und 50 Erfahrungspunkte einstreichen). So wie Doyle sind alle Charaktere in die Spielewelt integriert; niemand wirkt deplatziert oder verschwindet einfach. Da kann man auch darüber hinwegsehen, dass es ebenso wie in *Gothic III* bis auf Patty keine relevanten Frauencharaktere gibt und die wenigen weiblichen Figuren zumeist dem Wunschdenken der Programmierer entsprechen mit ihren großen Oberweiten und knappen Outfits.

Ebenso wie mit den Charakteren verhält es sich auch mit Gebäuden und Objekten - alles hat seinen Zweck und simuliert die mittelalterliche Welt sehr authentisch. Ein Schmiedeofen steht nur vor einer der Schmieden, und wenn der Held ein Schwert herstellen will, so muss er Ofen, Amboss, Wassertrog und Schleifstein nutzen. Für alle Fertigkeiten werden zudem Spezialwerkzeuge benötigt, so dass der Jäger neben dem Wissen um das Ausnehmen von Tieren auch Gegenstände wie Kiefernzangen und -meißel im Inventar haben muss.

Insgesamt bleiben technisch wie inhaltlich Innovationen aber Mangelware, wenn auch der Erfolg den Piranha Bytes Recht gibt. Die Rebellen- bzw Söldnerfraktion wird diesmal von den Banditen gestellt, in der Vulkanfestung werden Magier herangebildet und statt den Orks gibt es Echsenwesen, die an grundsätzlichem Körperbau und Stärke ihren Vorbildern in nichts nachstehen.

Spannender als die Dezimierung der weitgehend aus *Gothic* bekannten Tierwelt bleibt dagegen die Erkundung der Handlung und der Welt, in der sie eingebettet ist. Mehr, als dass die Götter verschwunden sind und die Menschheit kurz vor der Vernichtung durch die Titanen steht, erfährt der Spieler lange nicht und muss sich stattdessen mit dem Mikrokosmos der Insel begnügen. Dies erinnert nicht von ungefähr an die Anfänge der *Gothic*-Reihe mit der Gefängniskolonie, die später um die Insel Khorinis erweitert wurde und im dritten Teil schließlich das Königreich Myrtana präsentierte. Da *Risen II* bereits angekündigt ist verwundert es nicht, dass das Spiel mit einer Art Cliffhanger endet und viele Fragen zu den Titanen und Göttern offen lässt.

In Erinnerung bleibt am Ende ein Spiel, das in direkter Fortführung der *Gothic*-Reihe Evolution statt Revolution auf hohem Niveau betreibt. Die Selbstbeschränkung der Entwickler in Größe und Komplexität und eine Betatestphase führten dazu, dass ich nur einen leichten Bug während der immerhin 32 Stunden, die ich zum Durchspielen benötigte, gefunden habe. Ich kann das Spiel also nur weiterempfehlen, da es gerade im Vergleich zu der Demo des vor kurzem erschienen *Gothic 4 Arcania* das rundere Paket abliefert, selbst wenn letzteres den einfacheren Spieleinstieg bietet. Ich warte jetzt sehnsüchtig auf *Risen II*...
