---
title: "Bye Bye Blog"
date: "2014-01-01T18:22:24"
categories: [gedacht]
---

Es ist [wieder](/blog/2010/05/31/blogpause/) so weit. Diesmal vielleicht für immer: Nach einem [enttäuschenden Jahr 2013](/blog/2014/01/01/mein-jahr-2013-in-zahlen/) stelle ich ab sofort die Arbeit an meinem Blog ein.

Das ist eine schwere Entscheidung, aber ich muss diese Konsequenz ziehen. Das letzte Jahr hat gezeigt, dass meine Prioritäten sich verlagern. Ich habe keine Zeit mehr für den zeitraubenden Prozess, meine Gedanken in nachvollziehbare Worte zu fassen. Unzählige Artikelleichen zeugen davon. Die vielen Lücken bei den gesehenen Filmen führen zudem den Sinn dieses Blogs ad absurdum. Ich wollte immer eine Gedächtnisstütze haben, in der ich auch nach Jahren noch nachschlagen kann, was mir nach Sichtung eines Films durch den Kopf ging. 

Diesen Zweck erfüllt der Blog schon jetzt nicht mehr. Also werde ich keine Zeit mehr in etwas investieren, das mich nur halb zufriedenstellt. Da zudem absehbar ist, dass ich künftig noch weniger in das Schreiben investieren kann, lasse ich es lieber bleiben und versuche dafür mehr zu sehen und zu lesen. Der Blog selber wird in seinem aktuellen Zustand bestehen bleiben und vielleicht sogar noch den einen oder anderen Artikel sehen - mehr aber auch nicht.

Deshalb: Bye bye, mein Blog, und dankeschön an alle Leser!
