---
title: "Melancholia"
date: "2011-10-23T12:01:52"
categories: [gesehen]
---

*Dänemark/Schweden (2011)
Regie: Lars von Trier
Darsteller: Kirsten Dunst (Justine), Charlotte Gainsbourg (Claire), Kiefer Sutherland (John), Charlotte Rampling (Gaby), John Hurt (Dexter), Alexander Skarsgård (Michael), Stellan Skarsgård (Jack), Udo Kier (Hochzeitsplaner)*
[Offizielle Homepage](http://www.melancholia-derfilm.de/)

Melancholia ist ein erdähnlicher Planet ohne eigene Sonne, der aus dem Sternzeichen des Skorpion kommend auf dem Weg durch unser Sonnensystem ist. Er wird die Erde in unmittelbarer Nähe passieren, doch es ist ungewiss, ob die Erde den Planeten nicht mit ihrer Schwerkraft einfängt und es zu einer Kollision kommt, dem sogenannten Tanz des Todes, dem Ende alles Lebens. Wer nach Lars von Triers letzten Film [Antichrist](/blog/2009/11/22/antichrist/) noch Zweifel daran hatte, dass der Regisseur schwere psychische Probleme zu bewältigen hat, der sollte nach diesem Weltuntergangsszenario von Handlungsrahmen eines Besseren belehrt sein. Denn von Trier beschreibt durch seine Hauptfigur Justine das Leben als deprimierende Ausnahme im Universum, dem Melancholia ein verdientes Ende setzt.

Bemerken tut Justine dies zum ersten Mal ausgerechnet auf ihrer Hochzeitsfeier. Diese wird von ihrer Schwester Claire und dessen Mann John auf deren mondänen Landsitz am Meer inklusive Stallungen und Golfplatz ausgerichtet. Doch trotz der exquisiten Kulisse ist Justine bald nicht mehr zum Feiern zumute; Visionen des nahenden Weltuntergangs plagen sie während ihre Eltern die Hochzeit zur gegenseitigen Abrechnung nutzen (wunderbar gespielt von Charlotte Rampling & John Hurt) und kein offenes Ohr für die Tochter und ihre Probleme haben. Als auch noch der frischgebackene Ehemann unsensibel auf die Hochzeitsnacht drängt, schlägt die Verzweiflung der Ungehörten in Trotzreaktionen um und am folgenden Morgen ist nicht nur die Ehe aufgelöst, sondern auch Justine in eine tiefe Depression verfallen.

Claire nimmt die Schwester daraufhin zu sich. Während John in technisch rationaler Gläubigkeit das Naturereignis des passierenden Melancholia entgegensehnt und seiner Frau Optimismus vorspielt, lässt diese sich eher von Justines Anschauung anstecken, die wiederum mit fortschreitender Nähe des heranrasenden Planeten immer mehr aus ihrer Lethargie erwacht.

Diese familiäre Figurenkonstellation und der Umgang der einzelnen Charaktere mit dem drohenden Ende der Welt ist der Kern von *Melancholia*. Justine, Claire, John - jeder hat seine eigene Art des Umgangs mit dem absoluten Ende, jeder zeigt andere Reaktionen. Justine ist dabei die Extremste. Zuerst schüttelt sie all den Ballast der Gesellschaft - Ehemann, Familie, Job - in wenigen Handstreichen von sich, um nach der folgenden Depression ob der verbliebenen Leere das Ende wie einen Liebhaber zu empfangen, der sie von der Last der Existenz befreit. Von Trier verdeutlicht dies indem er Kirsten Dunst nackt am Ufer eines Bächleins liegend zeigt, nur illuminiert vom unwirklichen Licht von Melancholia. Bilder der Romantik auf Zelluloid gebannt.

Die von Charlotte Gainsbourg gewohnt souverän verkörperte Claire dagegen mit ihrem geordneten Leben - Haus, Mann, Kind - will anfangs nur zu gerne ihrem Ehemann und nicht Justine glauben, obwohl das Internet ihre Visionen bestätigt. Als schließlich die Zeichen nicht mehr geleugnet werden können, versucht sie trotzdem, die Fassade ihres Lebens bis zu dessen Ende aufrecht zu erhalten und sogar dem Tod aufzuzwingen. John fehlt dazu die Kraft, er zerbricht am Einsturz seines Weltbilds und zieht den Freitod einem Eingeständnis der eigenen Machtlosigkeit vor.

So sitzen zum unabwendbaren Ende schließlich Justine und Claire zusammen mit deren Sohn auf einer Wiese in einem aus Holzästen gebauten Zelt und über sie rollt die Feuerwelle des einschlagenden Melancholia. Dies ist das beeindruckendste Bild des Films, viel stärker als die artifiziell stilisierten, unwirklich wirkenden Bilder in Super-Slow-Motion der ersten Minuten, in denen von Trier wichtige Teile der Handlung vorwegnimmt. Denn bei diesen war ich dank der klassischen Musikuntermalung unangenehm an [Tree of Life](/blog/2011/07/24/the-tree-of-life/) erinnert, dessen Bilder von der Entstehungsgeschichte des Universums ganz ähnlich der kosmischen Katastrophe des Einschlags von Melancholia in die Erde zunächst einmal nicht mehr als leere Projektionsflächen darstellen, da sie (noch) nicht in die Handlung eingebettet sind.

Als Kontrast zu dieser bombastischen Einführung steht die nervöse Handkamera, die den Rest des Films dominiert. Als letztes Überbleibsel aus Dogma-Zeiten hat sie mich weitgehend genervt, weil sie so wenig zu dem an Bilder der Romantik erinnernden Szenenbild passt. Von Trier schreckt auch nicht vor den kitschigsten Bildern zurück (zum Beispiel wenn die beiden Schwestern auf ihren Pferden durch den Morgennebel ausreiten), wenngleich einige davon wie die Ankunft des Brautpaares in einer weißen Limo angenehm ironisch dekonstruiert werden und der am Himmel thronende Melancholia alles mit einer Atmosphäre der Bedrohung überzieht.

Aber ebenso wie das Figurenensemble existiert die optische Brillianz des Film nur, um am Ende zerstört zu werden, und da ist von Trier leider nicht mehr so weit weg von den Katastrophenfilmen hollywoodscher Prägung, die ihre Existenzberechtigung ebenfalls ausschließlich aus der Zerstörung ziehen - *Melancholia* setzt seine Destruktion nur eben eine Ebene höher, auf der künstlerischen Seite, an.

Fazit: So deprimierend der Handlungsrahmen um den alles Leben auf der Erde auslöschenden Planeten Melancholia sich anhören mag, so wenig fühlt es sich schließlich beim Sehen an. Dies liegt zum Einen an dem zumindest in der ersten Hälfte, der Hochzeitsfeier, vorherrschenden ironischen Unterton und zum Anderen an den stark romantisierenden Bildern des Films. Diese genauso wie seine Figuren in einem Weltuntergangsszenario zu zerstören ist dann auch die Stärke des Films, wenngleich er ansonsten keine Relevanz aufweist - zu viel Stil und zu wenig Inhalt lautet am Ende die Bilanz.
