---
title: "Lemony Snicket - Rätselhafte Ereignisse"
date: "2005-10-31T21:05:04"
categories: [gesehen]
---

Nachdem die Filmindustrie erfahren hat, dass man mit fantasievollen Kinderfilmen wie Harry Potter durchaus gutes Geld verdienen kann, war es nur eine Frage der Zeit, bis sie versuchte, mit dem gleichen Schema einen weiteren Kassenerfolg zu landen. Lemony Snicket ist ebenso wie Harry Potter eine Buchserie, deren erste drei Teile nun als Vorlage für diesen Film dienten.

Dieser hat eine wirklich interessante Optik zu bieten und die an Märchen erinnernden Handlungsorte wissen aufgrund ihrer Skurilität zu faszinieren. Das Haus der Tante Josephine direkt am Abgrund oder die Inneneinrichtung der Autos (Telefon, Tonbandgerät, Rückspiegel) erwecken in ihrem spielerischen Umgang mit Elementen aus verschiedenen Epochen eine fantasievolle Parallelwelt zum Leben.

Leider kann jedoch die Geschichte selber nicht mit den Kulissen mithalten. Zum Einen sind Handlung und Dialoge zu deutlich auf die Leseanfänger ausgerichtet, zum Anderen empfand ich die Verbindung von drei Episoden zu einem Film als sehr störend. Zu wenig verknüpft die drei Geschichten miteinander, und zu schnell ist jeweils das temporäre Happy-End erreicht. Ich weiß nicht, ob der Buchstoff mehr Inhalt her gibt, aber im Film wirkt die Story doch recht dünn - wahrscheinlich genau richtig für die jüngsten Kinogänger, die komplexeren Handlungenssträngen noch nicht folgen können. Dafür können sie sicherlich über die eingeblendeten Kommentare von Baby Sunny lachen (so sie denn lesen können), was mir nicht gelang.

Unterhaltsam waren aber die Auftritte von Meryl Streep und Billy Connolly (erinnerte mich sehr an John Cleese), während Jim Carrey seine gewohnte Show abzog. Den Auftritt von Dustin Hoffman hätte man sich aber sparen können, und von Jude Law als Erzähler sieht man nicht mehr als die dunkle Kontur und die Hände. Wenn es keine weiteren Verfilmungen der Serie gibt werde ich wohl niemals erfahren, wer dieser Lemony Snicket überhaupt ist und was er mit den "rätselhaften Ereignissen" zu tun hat...
