---
title: "The Dark Knight"
date: "2008-09-07T15:47:04"
categories: [gesehen]
---

*USA (2008)
Regie: Christopher Nolan
Darsteller: Heath Ledger (Joker), Christian Bale (Bruce Wayne), Aaron Eckhart (Harvey Dent), Gary Oldman (James Gordon), Michael Caine (Alfred), Maggie Gyllenhaal (Rachel Dawes), Morgan Freeman (Lucius Fox) und andere Bürger von Gotham City*
[Offizielle Homepage](http://wwws.warnerbros.de/thedarkknight/)

*The Dark Knight* hat mit einer großen Hypothek zu leben: Es gibt schon eine Verfilmung der Geschichte um Batman und den Joker, und diese ist unter der Regie von Tim Burton und mit Jack Nicholson als Bösewicht eine der besten Comic-Adaptionen aller Zeiten. Warum also nun ein neuer Versuch, sich dem Thema zu nähern?

Vermutlich, weil sich nichts besser verkauft als Plots und Charaktere, die der Zuschauer schon kennt. Fortsetzungen und Remakes sind Garanten an den Kinokassen, weshalb sich der Erfolg dieses Films auch damit erklären lässt, dass er beides zugleich ist. Erschwerend kommt der Tod des Hauptdarstellers hinzu; *The Dark Knight* ist der [letzte fertig abgedrehte Film](/blog/2008/01/23/too-young-to-die/) von Heath Ledger. Aber ist es wirklich so einfach? Kann man Mega-Blockbuster so am Reißbrett entwerfen, oder ist vielleicht mehr dran an diesem Film? Ich bin ins Kino gegangen, um genau dies herauszufinden.

Der Vergleich mit Tim Burtons Werk von 1989 muss trotzdem erlaubt sein, und da versagt *The Dark Knight* in ganzer Linie. Gotham City ist viel zu real geraten, die Stadt wirkt zu hell und positiv selbst im Vergleich zu *Batman Begins* und wird damit dem Comic nicht gerecht. Die 152 Minuten Spiellänge sind einfach zu viel, die Subplots um die Mafia und die Entstehung und endgültige Beseitigung von Two-Face sind zwar gut in die Handlung eingearbeitet, der Film hätte aber auch ohne sie funktioniert. Durch die vielen Handlungsstränge fehlt zudem ein großes Finale; trotz der Kopie des Absturzes des Jokers ist ein sich im Bau befindliches Hochhaus ein nicht halb so theatralischer Handlungsort verglichen mit dem Glockenturm einer gotischen Kathedrale. Diesmal rettet Batman sogar den Joker vor dem Tod, wodurch die Grundaussage des Filmes, den schwarzen Rächer nicht als den Helden dastehen zu lassen, konterkariert wird. Die einzige schlechte Tat des Films auf Seiten Bruce Waynes (Christian Bale hat nur geschätzte fünf Auftritte ohne Maske) ist die Ausnutzung des Handy-Sonar-Gadgets, dessen Benutzung aber Logiklöcher ohne Ende in die Handlung reißt. 1989 ist Batman noch wegen einer Frau in den finalen Kampf gezogen, diesmal darf er den edlen Ritter für Straftäter, Bürger und Geiseln spielen. Diesem Helden geht dementsprechend jegliche Ambivalenz ab, die einen Charakter so interessant machen. 

Und dies zieht sich durch fast jede Rolle des Films - die weiteren Charaktere stehen ähnlich blass in der Geschichte herum wie Bruce Wayne. Maggie Gyllenhall ist zwar verglichen mit Katie Holmes die bessere Rachel Dawes, hat jedoch zu wenig sinnvolle Auftritte, um irgendetwas aus ihrer Rolle zu machen und darf dann sogar den Leinwandtod sterben. Das größte Ärgernis ist jedoch Staatsanwalt Harvey Dent, dessen Charakter sich innerhalb der Filmzeit so stark ändert, dass ihm jegliche Glaubwürdigkeit abgeht. Zudem wurde Butler Alfred noch eine Kriegs-Historie angedichtet, so dass auch diese Figur aus ihrer Rolle fällt, nur um irgendwie in die Choreografie des Films zu passen.

Auf der Technik-Schnick-Schnack-Skala bliebt *The Dark Knight* eher im Mittelmaß; alles muss sich dem stilgebenden Realismus unterwerfen. Neben dem zum Motorrad mutierenden Batmobil betrifft dies auch den Fledermaus-Anzug und generell die Action des Films, die schwach dosiert und routiniert inszeniert sich dem vielen pseudo-moralischen Gequatsche unterwerfen muss.

Doch all dies verblasst hinter dem einzigen Grund, weshalb man sich diesen Film ansehen sollte: Heath Ledger in der besten Performance seiner Karriere als der Joker. Seine Auftritte sind die Highlights im Drehbuch, und der Schauspieler füllt die Rolle mit einer Präsenz, die selbst die Leistung von Jack Nicholson in *Batman* in den Schatten stellt. Zwar fehlt auch dieser Figur die innere Konsistenz, denn im Gegensatz zu seinen Aussagen sind die Aktionen des Jokers von vorne bis hinten durchgeplant, aber zumindest ist er nicht ausrechenbar. Und so entstehen diese überraschenden und witzigen Momente, von denen schon Tim Burtons Film lebte. Als Antikörper zu den restlichen Figuren zieht er damit sogar die Sympathien an sich.

Fazit: Als Film ist *The Dark Knight* recht enttäuschend. In zweieinhalb Stunden passiert zwar viel auf der Leinwand, jedoch werden dafür die bekannten Charaktere zerstört und einige Logiklöcher in der Geschichte hinterlassen. Doch die Rolle des Jokers und die Leistung von Heath Ledger hinter dessen Maske sind durchaus sehenswert. Der erfolgreichste Filmstart aller Zeiten gehört also nicht zum besten Film aller Zeiten; für einen unterhaltsamen Filmabend reicht *The Dark Knight* jedoch.
