---
title: "Men in Black II"
date: "2002-07-30T00:00:50"
categories: [gesehen]
---

*USA (2002)
Regie: Barry Sonnenfeld
Darsteller: Tommy Lee Jones (Agent K), Will Smith (Agent J), Lara Flynn Boyle (Serleena), Rosario Dawson (Rita), Rip Torn (Chief Z), Johnny Knoxville, Michael Jackson und andere Außerirdische ... *
[Offizielle Homepage](http://www.men-in-black-2.de/)

Seitdem Agent K durch Blitzdingsen aus dem aktiven Berufsleben ausschied (und eine Postfiliale übernahm), verschleißt Agent J einen Agenten nach dem anderen als Partner, so dass ihm Frank der Hund zugeteilt wird. Doch gleich ihr erster Fall, die Ermordung eines Außerirdischen durch einen Außerirdischen, lässt sich nur mit Informationen lösen, die allein K weiß. Also müssen die beiden dafür sorgen, dass K seine Erinnerungen wieder erlangt, um eine Zerstörung der Erde zu verhindern...

Hmm, es ist mir seit langem mal wieder gelungen, eine kurze Inhaltsangabe zu schreiben. Doch das ist leider kein Grund zur Freude, denn dieser Umstand signalisert damit auch die große Schwäche des Films: die viel zu dünne Story, die vom Regisseur mit Ach und Krach auf knapp 90 min gedehnt wird. Während Teil 1 (den ich übrigens für nicht so überragend halte) noch mit vielen Neuerungen aufwarten konnte und den Zuschauer zusammen mit Agent J in die MIB einführte, hielt man das bei der Fortsetzung für überflüssig und so findet sich der Zuschauer innerhalb kürzester Zeit in der Hauptgeschichte wieder und genauso schnell auf dem Nachhauseweg.

Damit das Ganze aber nicht zu langweilig ist, wurde die Gagdichte ganz exorbitant erhöht, so dass man auf jeden Fall gut unterhalten wird, auch wenn der eine oder andere Witz mal nicht funktioniert. Ein weiterer Pluspunkt ist die Kontinuität des MIB-Universums, so dass sich die Besucher des ersten Teils sofort wieder zurecht finden werden, was aber auch zur Folge hat, dass z.B. Frank und die wirbellosen Würmer mächtig an Originalität verlieren. Die wenigen neuen Einfälle wie die Schließfachwesen reichen da einfach nicht aus. Tommy Lee Jones und Will Smith brauchen auch nicht lange, um sich wieder in ihren Rollen als Lehrling und Meister zu finden, aus der anfangs umgekehrten Situation macht der Film aber leider viel zu wenig.

Fazit: Eine Fortsetzung, die sich nahtlos an Teil 1 anschließt, der aber leider die Story und die Ideen ziemlich schnell ausgehen. Für einen unterhaltsamen Sommerabend aber immer noch gut genug, schon wegen der großen Anzahl an Gags!
