---
title: "Garden State"
date: "2005-11-08T16:14:32"
categories: [gesehen]
---

Zach Braff, bekannt aus "Scrubs", legt mit "Garden State" sein Debut als Drehbuchautor und Regisseur eines Kinofilms ab. Gleichzeitig spielt er auch noch die Hauptrolle, die er zwar ausreichend ausfüllt, aber auch nicht mehr zeigt, als man von ihm im TV gewohnt ist. Trotzdem lebt der Film von dem Gegensatz des scheinbar ruhigen Andrew Largeman und der seltsamen Welt, in der er lebt. Seit dem von ihm verschuldeten Unfall seiner Mutter wird er von seinem Vater, der Psychologe von Beruf ist, mit Medikamenten ruhig gestellt, während die Menschen um ihn herum sich total ausgeflippt benehmen dürfen.

Ausgerechnet mit dem Freitod der Mutter (in dem eigens dafür renovierten Badezimmer) ändert sich jedoch alles, weil Large bei seiner Rückkehr nach Hause die Tabletten vergessen hat und die alten und neuen Freunde ihm ein Menschen-Ideal zeigen, dass nicht dem seines Vaters entspricht. Sie sind alle etwas skuril und wandeln nicht auf den ehrlichsten Pfaden, aber die Freundschaft mit Ihnen zeigt sich in allen Gesten und Aussagen.

"Garden State" lebt von seinem dezenten Humor und der Selbsfindung des Hauptcharakters, und die melancholischen Momente steigern nur die Wirkung des Films. Natalie Portman als die notorische Lügnerin Sam, die den ruhigen Large genauso als Haltepunkt braucht wie dieser sie, hat einen wichtigen Schritt zu wieder besseren Rollen als in StarWars getan und Ian Holm spielt souverän und eindringlich den Vater. Schade, dass man von dem Stimmtraining, welches er für den New Jersey-Akzent bekam, in der deutschen Synchronisation nichts mitbekommt.

Die geschnittenen Szenen auf der DVD haben mich jedoch fragen lassen, wer den Schnitt bei "Garden State" erledigt hat. Viele inhaltlich wichtige Szenen fehlen, und vieles, was man vorher nur erahnen konnte, wird bestätigt (Selbstmord der Mutter). Zehn Minuten mehr hätten dem Film sicher nicht schlecht zu Gesicht gestanden, aber am Gesamteindruck ändert dieser Schnitt trotzdem nicht viel.
