---
title: "Bowling for Columbine"
date: "2003-06-16T00:00:08"
categories: [gesehen]
---

*USA (2002)
Regie: Michael Moore
Darsteller: Charlton Heston, Marilyn Manson, Matt Stone und anderen Waffennarren oder -kritikern*
[Offizielle Homepage](http://www.bowling-for-columbine.de/)

1999 starben an der Columbine Highschool in Colorado 12 Kinder bei dem Amoklauf von zwei ihrer Mitschüler. Die Medien hatten schnell Schuldige bereit: Marilyn Manson, Computerspiele und Videos sollen die beiden Mittelschichtkids beeinflusst haben. Doch ist es ein Zufall, dass gerade Colorado einer des waffenverrücktesten Staaten der USA ist und in Denver die weltgrösste Waffenfabrik steht? In seinem Dokumentarfilm geht Michael Moore dieser Frage nach, lässt Beschuldigte und Unbeteiligte zu Wort kommen und führt Vergleiche mit anderen Ländern durch...

Dass die Amerikaner spinnen wusste schon Obelix, aber welche Ausmaße dies annehmen kann zeigt Michael Moore gleich zu Beginn: In einer Bank bekommt er zu seiner Konto-Eröffnung ein Gewehr als Prämie dazu und nebenan im Friseurladen kann er die passende Munition bequem während des Haareschneidens auswählen. Nirgendwo ist es leichter an Waffen und Munition zu kommen als in den USA, in denen das Recht auf Waffenbesitz sogar der 2. (!) Artikel der Verfassung ist.

Die Schlussfolgerung, dass es gerade wegen der totalen Verfügbarkeit zu der im Gegensatz zu anderen Ländern um ein vielfaches höheren Mordrate kommt, lässt Moore jedoch nicht gelten - im Nachbarland Kanada herrschen ähnliche Zustände in Bezug auf den Waffenbesitz, und trotzdem erschießen sich kaum Kanadier gegenseitig. Was ist also an Amerika bzw. an seinen Bewohnern so anders? Moore hat eine einleuchtende Erklärung dafür und nimmt sich Zeit, diese dem Zuschauer in dem ungewohnten Format Dokumentarfilm näher zu bringen. Die einfache Antwort ist: Die Amerikaner sind ein durch und durch verängstigtes Volk, dessen Angst vor dem Versagen und alles und jeden sie dazu treibt, schneller als jeder andere zu der Konfliktlösung durch die Waffe zu greifen. Landesintern wird dies durch die Medien und die Wirtschaft geschürt, die sich gegenseitig hochpushen; global spielen sich die USA schon lange als Richter und Vollstrecker über andere Völker auf.

Ersteres präsentiert Moore zusammen mit Matt Stone, einem der Erfinder von 'South Park', in einem kurzen, total überspitzten Zeichentrickfilm über die Geschichte Amerikas, angereichert mit so interessanten Informationen wie dass die Nationale Waffen-Verbindung (NRA) in dem Jahr gegründet wurde, in dem der Ku-Klux-Klan verboten wurde. Und über einem Zusammenschnitt verschiedener amerikanischer Interventionen und Einmischungen der letzten 50 Jahre (unter anderem die Unterstützung des Taliban und Osama Bin Laden im Kampf gegen die UDSSR und die spätere Terroristenjagd auf diesselben oder die abwechselnde Förderung des Iraks und des Irans in deren Konflikt) kommt er zu dem recht unbekannten Fakt, dass am Tag des Amoklaufs in Littleton die USA den größten Bombenangriff im Kosovo-Konflikt flogen. Ist es also nicht vielmehr die Regierung, die die beiden Schüler zu ihrer Tat anregte - oder doch der Bowling-Unterricht, den sie noch am Morgen ihres Amoklaufs an ihrer Schule hatten?

Zu diesen oftmals nicht ganz ernst gemeinten Fragen lässt Moore viele Menschen zu Wort kommen, wobei er sich gerne hinter seinem Schlabberlook und einer gespielten Dummheit versteckt, um dann mit um so intelligenteren Fragen sein Gegenüber auf den Zahn zu fühlen. Dabei wendet er aber auch zweierlei Maß an: Befürworter seiner Theorie lässt er gern ausführlich und ohne Unterbrechung zu Wort kommen; meist sind dies auch wortgewandte Gesprächspartner wie Marilyn Manson, Matt Stone oder ein Professor. Die Waffenlobbyisten jedoch lockt er ein um das andere Mal aus der Reserve und lässt sie sich der Lächerlichkeit preisgeben, während Beteiligte der Tragödien Mitleid heischend schon mal weinen dürfen.

Ansonsten ist aber gerade Moores Gespür für Situationen (z.B. wenn er in kanadische Häuser hineinspaziert um die offenen Türen zu kontrollieren) und die (scheinbar?) zufälligen Ereignisse (wie das Ende des Muntionsverkaufs bei K-Mart), die den Film so unterhaltsam machen, wenngleich die Regie eine durchgehende Linie vermissen lässt.

Fazit: Dieser Film ist nicht nur für Kritiker Amerikas einen Kinobesuch wert, sondern durch seine mal witzige, mal schockierende und oft übertreibende Darstellung der Thematik eine Empfehlung für jeden, der einmal etwas anderes als den Hollywood-Einheitsbrei sehen will und dabei akzeptiert, dass der Film doch sehr parteiisch ist.
