---
title: "Identisches Gerät"
date: "2006-01-18T15:25:52"
categories: [gedacht,gefunden]
---

Bei meinen Eltern stand nach dem Austausch des Monitors nun auch ein neuer Drucker ganz oben auf der Liste der zu ersetzenden Geräte. Der alte Canon BJ-200ex sollte nach elf Jahren mehr oder weniger problemlosen Betriebes einem modernen Gerät weichen.

Aufgrund der teuren Tinten und der nicht vorhandenen Patronenalternativen wurden HP und Lexmark bei der Suche nach einem brauchbaren Gerät gar nicht erst in Betracht gezogen. Da den Eltern außerdem mein Epson-Drucker zu langsam war, fiel die Entschiedung erneut auf Canon. Dessen aktuelle Generation von Druckern (PIXMA iPx200 Serie) setzt aber auch auf neu entwickelte und mit Chips geschützte Tintentanks. So suchte ich nun auf den einschlägigen Preisvergleichsseiten nach seriösen Anbietern für die alten Modelle, bei denen es genügend Anbieter für Ersatzpatronen gibt.

Doch Canon hat es geschafft, innerhalb kürzester Zeit alle alten Modelle aus dem Markt zu nehmen (bzw. die Verbraucher kauften mit Erscheinen der neuen Generation alle Restposten, so lange diese verfügbar waren). So blieb nur noch der [Otto-Versand](http://www.otto.de), der in seinem bis Januar gültigen, alten Katalog noch den [PIXMA iP3000](http://www.canon.de/for_home/product_finder/printers/bubble_jet/pixma_ip3000/index.asp?specs=1) führte. Die Bestellung wurde auch akzeptiert und letzten Freitag kam das Paket nun an. Doch der Hermes-Versand lieferte nicht das gewünschte Gerät, sondern dessen Nachfolger [PIXMA iP4200](http://www.canon.de/for_home/product_finder/printers/bubble_jet/PIXMA_iP4200/index.asp?specs=1) mit folgendem Aufkleber auf dem Karton:

> **Liebe Kundin, lieber Kunde,**

vielen Dank für Ihre Bestellung!

Das von Ihnen gewünschte Gerät ist zur Zeit unter einem anderen Markennamen lieferbar. Es handelt sich hierbei um ein in allen Punkten identisches Gerät.

**Ihre Qualitätssicherung**

Aha, die beiden Geräte sind also identisch? Die fünf separaten Tintentanks PGI-5BK, CLI-8BK, CLI-8C, CLI-8M und CLI-8Y sind in allen Punkten identisch zu den vier Tintentanks BCI-3eBK, BCI-6C, BCI-6M und BCI-6Y? Dies ist eine seltsame Interpretation von Qualitätssicherung.

Zumindest kann man Otto zu Gute halten, dass das neue Gerät theoretisch eine höhere (aber nicht identische) Qualität besitzt und ansonsten im Katalog 30€ mehr kostet als die bestellte Version, deren Preis die Eltern zahlen müssen. Aber einen Hinweis schon bei der telefonischen Bestellung wäre trotzdem sinnvoller gewesen.

Wir haben uns dann dazu entschlossen, den Drucker zu behalten, da der Erwerb eines Gerätes der alten Generation sehr unwahrscheinlich ist. Und bis auf die momentan noch nicht erhältlichen, billigen NoName-Tintentanks überzeugt der IP4200 auch mit seiner Qualität und Ausstattung. Sehr überzeugend fand ich vor allem die integrierte Duplexeinheit und die geschlossene und damit vor Staub geschützte Papierkassette. Außerdem meldet sich der Drucker, wenn das Ausgabefach geschlossen ist. Mein Epson druckt in dieser Situation trotzdem und verstopft sich so selber.
