---
title: "The man who wasn't there"
date: "2002-01-07T00:00:31"
categories: [gesehen]
---

*USA (2001)
Regie: Joel Coen
Darsteller: Billy Bob Thornton (Ed Crane), Frances McDormand (Doris Crane), Michael Badalucco (Frank), James Gandolfini (Big Dave), Katherine Borowitz (Ann), Jon Polito (Creighton Tolliver), Scarlett Johansson (Birdy), Richard Jenkins (Walter), Tomy Shalhoub (Freddy Riedenschneider) und andere Beteiligte*
[Offizielle Homepage](http://www.the-man-who-wasnt-there-film.de/)

Der Friseur Ed Crane lebt ein stilles und wenig aufregendes Leben. Angestellt im Salon seines Schwagers, geht sein Leben in festgeschriebenen Bahnen voran. Bis eines Tages der Geschäftsmann Tolliver von einem todsicheren Geschäft berichtet, der "Trockenreinigung", zu dessen Umsetzung er nur \$10.000 benötige - und Crane läßt sich dazu hinreißen, einmal ein Risiko einzugehen. Doch woher das Geld nehmen? Da kommt es Ed gerade Recht, dass Big Dave, der Chef seiner Frau, mit dieser ein Verhältnis hat und er erpresst ihn um die Summe. Dummerweise kommt dieser dahinter und versucht Ed umzubringen, kommt dabei aber selber ums Leben - und das ist erst der Anfang vom Chaos. Am nächsten Morgen wird nämlich Cranes Frau wegen dem Mord verhaftet, da sie Geld unterschlagen hat...

Alle 2 Jahre ist es wieder so weit und der neue Film der Coen-Brüder kommt in die Kinos. Nach dem Schema "abwechselnd Komödie und Thriller" war diesmal letzteres Genre an der Reihe (wobei man die Filme eigentlich nicht in solche Fächer einteilen kann - meistens enthalten die Filme beides).

Aus dem letzten Drama (*Fargo*) war mal wieder Frances McDormand dabei, ansonsten tauchen aber keine weiteren Coen-Spezies auf, stattdessen darf Billy Bob Thornton zeigen, was er schauspielerisch auf dem Kasten hat. Seine Leistung als der ewig langsame, ständig mit einer Zigarette in der Hand auftretende Friseur Ed, der mit der wahrscheinlich einzigen Entscheidung seines Lebens sich, seine Frau und eine Menge anderer Leute ins Unglück stürzt, ist grandios.

Es ist also wieder die selbe alte Geschichte von einem so einfach erscheinenden Plan, der jedoch bald aus dem Ruder läuft und den Akteur unter sich begräbt. Doch während bei Fargo sich die Ereignisse nur so überschlugen und eine Fehlentscheidung die andere jagt, geht dieser Film, dem "Helden" angepasst (oder etwa ungekehrt?), äußerst langsam bei der Storyentwicklung vor. Ed kommentiert wie im Film Noir üblich die gesamte Handlung aus dem Off und nicht selten kommt es zu einer Situation mit Ed, in der sich die Akteure nur anschweigen und auch die Dialoge mit ihm laufen sehr behäbig ab - der Film verlangt ein hohes Maß an Geduld bzw. es bleibt genügend Zeit für den Zuschauer, die Handlung zu hinterfragen und die nächsten Ereignisse vorherzusehen. 

So gehen auch viele Gags des Films einfach unter und die vielen Enden bewirken nur, dass man den Abspann als vollkommen irreal empfindet und auf die Fortsetzung des Films wartet. Der einzige Lichtblick ist in dieser Hinsicht der Anwalt Riedenschneider, der seine Monologe so schnell führt, dass sie erträglich bleiben. Ansonsten zeigt der Film aber den gewohnten hohen Produktionsstandard der Coen-Brüder, die die 40er Jahre wieder zum Leben erwecken und die Schauspieler zu Glanzleistungen animieren.

Fazit: Nur für Fans. Auch dieser Coen-Film enthält wieder alle Elemente für einen Klassiker, aber sie haben die Story diesmal so weit gestreckt und die Dialoge so verlangsamt, dass es eine Menge Leerlauf für den Zuschauer gibt und einige Handlungsänderungen und Gags untergehen bzw. vorhergesehen werden. Schade, hätte besser werden können!
