---
title: "Der Pianist"
date: "2002-10-26T00:00:50"
categories: [gesehen]
---

*Deutschland/Frankreich/UK/Polen (2002)
Regie: Roman Polanski
Darsteller: Adrien Brody (Wladyslaw Szpilman), Emilia Fox (Dorota), Frank Finlay (Vater), Maureen Lipman (Mutter), Ed Stoppard (Henryk), Julia Rayner (Regina), Jessica Kate Meyer (Halina), Daniel Caltagirone (Majorek), Thomas Kretschmann (Wilm Hosenfeld), Ruth Platt (Janina) uvm*
[Offizielle Homepage](http://www.thepianist-themovie.com/)

Der durch seine Radioauftritte in ganz Polen bekannte jüdische Pianist Szpilman muss mit seiner Familie 1939 den Einmarsch und die Besetzung der Deutschen miterleben. Während die Deutschen den Juden systematisch alle Rechte und die Lebensgrundlage entziehen und sie schließlich sogar in ein Ghetto umsiedeln, versucht Szpilman seine Familie so gut es geht mit seiner Arbeit zu ernähren. Als aber dann der Großteil der Warschauer Juden in Vernichtungslager geschafft wird, überlebt er nur durch die Hilfe eines Bekannten bei der jüdischen Ghetto-Polizei, die mit den Nazis kooperieren. Fortan muss er auf Baustellen für die Deutschen arbeiten und mit der schrecklichen Gewissheit leben, seine Familie nie wieder zu sehen. Nach einer geglückten Flucht verstecken der polnische Widerstand und alte Freunde Szpilman in verschiedenen Wohnungen, wo er total heruntergekommen wie durch ein Wunder auch die Bombardierung Warschaus übersteht. Doch kurz vor der Niederlage der Nazis gegen Russland wird er in seinem Versteck in einer alten Villa noch von einem Deutschen entdeckt...

Roman Polanski, sonst eher ein Vertreter des Mainstream-Kinos, hat diesen Film nach dem Buch von Wladyslaw Szpilman gedreht, einer wahren Geschichte also, denn Szpilman hat genauso wie auch Polanski das Warschauer Ghetto überlebt. Dieser persönliche Aspekt spiegelt sich in der Regie wider, denn Polanski lässt den Zuschauer sehr direkt an den Erfahrungen Szpilmans teilhaben. Die Kamera ist stets nah bei ihm, schaut ihm öfters mal über die Schulter oder auf die Finger beim Klavierspielen. Der Ton scheint genau die Wahrnehmungen Szpilmans wiederzugeben, was sich besonders eindrucksvoll nach dem Einschlag einer Granate direkt neben ihm zeigt, wo plötzlich die gesamte Geräuschkulisse gedämpft und von einem Fiepen überlagert wird. Dazu kommt das fantastische Spiel von Adrien Brody, der die Wandlung des gebildeten jungen Künstler hin zu einem instinktiv handelnden und nur noch ans Überleben denkenden Flüchtling sehr glaubwürdig darzustellen vermag.

Wo momentan vor allem amerikanische Filme mit enormen pyrotechnischen Materialschlachten propagandistisch die Helden des Krieges feiern, zeigt Polanski in aller Drastigkeit der Bilder den Wahnsinn, die Opfer und die Verbrechen. Der Warschauer Widerstand möchte keine Heldentaten verbringen, sondern nur in Würde sterben. Die Ghetto-Polizei leitet die eigenen jüdischen Brüder in die Vernichtungslager und einige Nazis nutzen ihre Position zu unmenschlichen Taten aus. Dies alles dokumentiert der Regisseur exemplarisch aus der Sicht eines Einzelnen, der genauso wie die Menschen um ihn herum anfangs noch einen Sinn zu sehen versucht; nur um dann gnadenlos vom Schicksal mitgerissen zu werden und mit unglaublichen Glück auch noch das letzte Jahr des Krieges lebend zu überstehen.

Dabei möchte ich noch einmal auf die technischen Aspekte des Filmes eingehen. Große und realistische Kulissen und Menschenmassen hat man in ähnlicher Form schon zur Genüge gesehen, aber passend zu der subjektiven Ausrichtung des Filmes spielt sich das Geschehen immer in kleinen Vierteln und Wohnungen ab, von denen Szpilman und damit dem Zuschauer immer wieder Blicke auf Warschau, vor allem während und nach der Bombardierung gegönnt werden. Dies alles kommt zusammen mit den oben erwähnten audiovisuellen Mitteln so eindrucksvoll realistisch daher, dass es einen wirklich tief trifft. Eine fantastische europäische Koproduktion!

Fazit: Ein Film, den man gesehen haben muss! Thematisch eher von schwerem Kaliber und sicherlich nicht leicht verdaulich schafft es Polanski trotzdem, den Zuschauer 2 1/2 Stunden lang an den Kinosessel zu fesseln. Die "Goldene Palme" bekommt nicht jeder Film, aber dieser zu Recht!
