---
title: "Sherlock"
date: "2011-08-08T22:21:30"
categories: [gesehen]
---

Als Kind habe ich in meiner Krimiphase neben Agathe Christie auch die Sherlock-Holmes-Geschichten von Arthur Conan Doyle verschlungen. Dementsprechend war ich alles andere als abgeneigt, mir die Neuinterpretation der [BBC](http://www.sherlock-bbcgermany.de/) anzuschauen, welche versucht die Handlungen in die Gegenwart zu transformieren - und der das sehr gut gelingt.

Dabei halten sich die Drehbücher erstaunlich nah an der Vorlage, was für die Universalität der Motive von Arthur Conan Doyle spricht. Sogar der Kriegseinsatz von Dr Watson in Afghanistan konnte wiederverwendet werden - History repeating. Ansonsten wird aus seinem Tagebuch eben ein Blog und aus Kutschen die modernen Londoner Cabs; Scotland Yard, Obdachlose und die Baker Street gibt es auch heute noch. Daneben bedient sich Sherlock moderner Kommunikationsmittel wie Handy und Internet und hat Freunde in der Street-Art-Szene. Diese neuen Elemente werden jedoch gut in die subtil modernisierten Handlungen integriert. 

Weniger dezent wirkt die Optik der Serie. Fast jeder denkbare optische Schnick-Schnack, der momentan hip und angesagt ist, wird auch eingesetzt: Ein Tilt-&-Shift-Intro, dreidimensionale Schrifteinblendungen im Stile der Augmented Reality, schnelle Schnitte wie in Guy Ritchies Konkurrenz-Adaption und eine Hochglanz-Digicam-Optik verwehren fast den Blick auf die guten Sets und die liebevolle Ausstattung.

Doch die Stärke von *Sherlock* liegt ganz woanders: Es sind die pointierten Dialoge und die Verlagerung der Handlungen in die heutige Zeit. Der Sherlock Holmes von Arthur Conan Doyle war aufgrund seiner Genialität ein anerkanntes Mitglied der Gesellschaft, doch seine moderne Version wird von Polizisten trotz aller Qualitäten als Freak bezeichnet, da er im zwischenmenschlichen Bereich ein Autist ist. Zeitweise verdächtigt ihn die Polizei sogar persönlich, für die untersuchten Verbrechen verantwortlich zu sein, da er so viele Details darüber schlussfolgert. Zudem wird ihm und Watson ständig eine gleichgeschlechtliche Beziehung unterstellt, was zu einer Art Running Gag der Serie wird. Leider leidet die Rolle des Dr. Watson unter der Überspitzung seines Partners; in der ersten Folge ist er kaum mehr als ein Stichwortgeber und Lobpreiser, dem trotz der prominenten Besetzung mit Martin Freeman kaum Sympathien zuteil werden.

Trotzdem funktioniert die Figurenkonstellation dank der Schauspieler hervorragend und bietet den Nährboden für die Dialoge, die sich dem Tempo der Inszenierung anschließen und einfach nur großartig sind. Sherlock wird dermaßen arrogant dargestellt, dass es eine Freude ist, ihm zuzuschauen. Überheblich und selbstsicher muss er in jeder Gelegenheit seinen Mitmenschen deutlich machen, dass er so viel schlauer ist als sie. Dies bewirkt dementsprechende Reaktionen, und die daraus resultierenden Dialoge machen einen Großteil des Unterhaltungswertes der Serie aus.

Nicht durchgängig mithalten kann da das Drehbuch. Bereits in der ersten Folge wusste ich eher als Sherlock, wer der Mörder war. Frei nach dessen eigenem Motto "Wenn man das Unmögliche ausgeschlossen hat, muss das, was übrig bleibt, die Wahrheit sein, so unwahrscheinlich sie auch klingen mag", konnte es nur der Taxifahrer sein. In der zweiten Folge häufen sich diese inszenatorischen Fehler bis zu einem nicht nachvollziehbaren Finale, so dass diese die schlechteste Episode darstellt. Der Abschluss - wie die erste Folge unter der Regie von Paul McGuigan - lief jedoch wieder zu der alten Form auf und bietet mit einer surrealen Kampfszene in einem Planetarium zwischen Sherlock und einem Riesen ein erinnerungswürdiges Highlight.

Obwohl sich also sowohl die Serie *Sherlock* als auch die Verfilmungen von Guy Ritchie um eine Modernisierung des Stoffes bemühen und ähnlich schnell und actionreich inszeniert sind, hat mich die BBC mit ihrem Ansatz mehr überzeugt. Wer die drei Filmepisoden noch nicht gesehen hat, sollte dies im September auf EinsFestival definitiv nachholen!
