---
title: "Portsmouth, New Hampshire"
date: "2011-10-04T22:48:20"
categories: [gewesen]
---

Eigentlich ist Neuengland gar nicht so anders als andere Gegenden an der Ostküste. Und trotzdem erweckte Portsmouth bei mir den Eindruck, dass hier die Welt noch in Ordnung ist. Es fängt damit an, dass die Kirche noch immer das höchste Gebäude der Stadt ist und alles sehr gepflegt aussieht. Die Holzbauweise ist zwar dieselbe wie bei den Eigenheimen in den Suburbs der Großstädte, aber es sind Kleinigkeiten, die den Unterschied ausmachen und ein ganz anderes Bild ergeben. So hängt nicht an jeder Ecke die amerikanische Flagge vor der Tür und die Häuser sind in warmen Farben gestrichen, die wunderbar mit dem Laub harmonieren, wenn der [Indian Summer](http://de.wikipedia.org/wiki/Indian_Summer) über Neuengland hereinbricht. Für dieses Naturschauspiel war ich leider einen Monat zu früh vor Ort, aber auch ohne die herbstliche Farben ist es ein wunderbarer Anblick, wenn man von der Insel New Castle kommend auf Portsmouth zufährt.

Das ist das Land von John Irving, wie es der Autor in fast allen seiner Bücher beschreibt. Er selber wohnt ja direkt um die Ecke in Exeter und ich fühlte mich als aufmerksamer Leser seiner Bücher schnell heimisch in Portsmouth. Dabei sollte aber nicht vergessen werden, weshalb die Gegend so ein Paradies ist. Hier wohnen nur die finanziell potenten Bürger, und diese bürgerlich-konservative Elite weiß zu leben und sich abzuschotten. Dass dies schon immer so war, zeigt die Dichte an Häusern von Unterzeichnern der Unabhängigkeitserklärung. Erkauft wurde diese Exklusivität von den [Gründervätern, die im Namen Gottes die indigenen Ureinwohner vernichteten und vertrieben](http://de.wikipedia.org/wiki/Neuengland#Kolonialisierung).

Dies kann bei einem Besuch der [Strawberry Banke](http://www.strawberybanke.org/) wunderbar ignoriert werden. Dieses Freiluftmuseum mitten in Portsmouth bietet einen Einblick in die erste Besiedlung der Gegend inklusive restaurierten Häusern aus verschiedenen Generationen und der [Neukonstruktion eines Schiffes](http://www.gundalow.org/new-gundalow/under-construction), dessen Typ in der seen- und flussreichen Gegend über Jahrhunderte hinweg üblich war.

Gleich nebenan prägt mit der [World War Memorial Bridge](http://en.wikipedia.org/wiki/Memorial_Bridge_(Portsmouth,_New_Hampshire)) ein Industriedenkmal das Bild von Portsmouth. 88 Jahre lang war sie eine wichtige Verkehrsverbindung über den Piscataqua River, nun können nur noch Fahrradfahrer und Fußgänger die Hebebrücke nutzen. Wer über sie die Stadt betritt, wird nicht nur an die lange Historie von Portsmouth erinnert (die Gründung der Stadt erfolgte bereits im Jahr 1623), sondern kann direkt an Bow und Market Street in eines der Restaurants einkehren, die hier mit Terrassen zum Fluss hin frischen *Lobster* anbieten. Aber Vorsicht: Wer eine [Lobster Roll](http://en.wikipedia.org/wiki/Lobster_roll) bestellt sollte wissen, dass dies nur ein Sandwich mit kaltem Lobsterfleisch ist - typisch amerikanische Küche eben.

[gallery link="file"]
