---
title: "Mary and Max"
date: "2009-12-22T16:31:26"
categories: [gesehen]
---

*Australien (2009)
Regie: Adam Elliot
Sprecher: Toni Collette (Mary Daisy Dinkle), Philip Seymour Hoffman (Max Jerry Horovitz), Eric Bana (Damien), Barry Humphries (Erzähler)*
[Offizielle Homepage](http://www.maryandmax.com)

Mary ist eine australische Schülerin mit dem Hang zu schokoladigen Speisen, der es sowohl an führsorglichen Eltern als auch an Freunden fehlt. Um mehr über die Welt zu erfahren (im Besonderen wo die Kinder herkommen) schreibt sie deshalb einen wildfremden Mann in New York an. Dabei erwischt sie ausgerechnet Max, einem unter dem Asperger-Syndrom leidenden übergewichtigen Mann, in dessen geordnetes Leben so eine Brieffreundschaft anfangs gar nicht passen will. Doch auch Max hat keine Freunde und so werden aus Briefen schnell Pakete, in denen die beiden die kontinentalen Spezialitäten und Schokoladen-Rezepte austauschen.

Aber junge Mädchen wie Mary entwickeln sich schnell - zu schnell für Max - und die Freundschaft wird mehr als einmal auf eine harte Probe gestellt. Als junge Frau studiert Mary Medizin, um für die medizinischen Probleme von Max eine Heilmethode zu finden. Doch sie muss nicht nur lernen, dass es für manche körperliche Probleme keine medizinischen Lösungen gibt, sondern auch erkennen, wie schnell anderer Leute Probleme die eigenen werden können...

Etwas überraschend lief diese Knetfiguren-Animation auf der diesjährigen Berlinale im Jugendprogramm *Generation 14plus*. Überraschend deshalb, weil sich hinter den wenig detaillierten Kulissen, den putzigen Figuren und dem Märchenonkel-haften Erzähler aus dem Off, der fast ausschließlich in kurzen Sätzen ohne Nebensätze spricht, kein Kinderfilm sondern eine Auseinandersetzung mit sehr ernsten Themen versteckt. Diese ist zum Glück dank des rabenschwarzen Humors leicht zu genießen und da der Film auch eine Coming-of-age-Storyline erzählt haben ihn die Programmgestalter wohl in diese Kategorie eingeteilt.

Wie schon angedeutet kann *Mary and Max* in Sachen Animation nicht mit großen Vorbildern wie [Coraline](/blog/2009/09/13/coraline/), [Corpse Bride](/blog/2005/11/13/corpse-bride-hochzeit-mit-einer-leiche/) oder den [Aardman-Studios](/blog/2005/10/31/wallace-gromit-auf-der-jagd-nach-dem-riesenkaninchen/) mithalten. Dafür fehlt es vor allem an Details und Bewegung. Doch als Ausgleich für diesen Mangel hat Regisseur Adam Elliot seine ganz eigene Bildsprache gefunden, die vor allem von Kontrasten lebt. Es fängt an bei den beiden Handlungsorten (düsteres, graues New York versus warmes, braunes Australien) und setzt sich fort bei den Charakteren. Es überwiegen jedoch die dunklen Farbtöne; nur wenige Farbtupfer ragen aus der Eintönigkeit hervor. Als Max zum ersten Mal den Mund aufriss bin ich fast erschrocken, so grell wirkte seine rote Zunge.

Der Film schafft es mit dieser Optik sehr gut, dem Zuschauer die Wahrnehmungen seiner Charaktere nahe zu bringen. Die Art, wie sich Marys Mutter zu Tode säuft, ist so zum Schreien komisch inszeniert, dass man merkt, dass dies zwar ein Begleitumstand ihrer pubertären Probleme ist, aber sie selber ganz andere Probleme in den Vordergrund stellt. So bekommt der Zuschauer sehr schnell ein Bild von dem jungen optimistischen Mädchen aus dem Outback-Kaff und dem introvertierten Einzelgänger in der anonymen Großstadt, deren Lebenswege sich fortan beeinflussen werden.

Während sich Marys Welt fortwährend ändert, bleibt bei Max fast alles gleich. Tote Tiere werden ausgetauscht, Max sitzt beim Briefeschreiben immer vor derselben Schreibmaschine - Konstanz ist das wichtigste Element in Max Leben. Doch durch die Energie des Mädchens lernt er eine gewisse Anpassungsfähigkeit, die er aufgrund fehlender zwischenmenschlicher Beziehungen anders nie erreicht hätte, während er selber dem Kind beim Heranwachsen eine Stütze und ein nicht-autoritärer Ansprechpartner ist und Mary auf die eine oder andere Art sogar in ihrer Lebensgestaltung beeinflusst.

Fazit: Die Kunst dieses Films ist es, die Aneinanderreihung von Tragödien aus den Leben von Mary und Max auf eine komische Art darzustellen, die jedoch jederzeit ehrlich zu den Charakteren und ihren Problemen ist und nichts beschönigt oder verniedlicht. Mit dieser positiven und fast schon pädagogischen Einstellung, dass trotz einer verkorksten Jugend ein glücklicher Mensch entstehen kann, war *Mary and Max* dann doch gut aufgehoben im Jugendprogramm der Berlinale. Und ich wünsche dem Film ein größeres Publikum jenseits der einschlägigen Festivals!

**Update:** Es gibt mit dem 26.08.2010 endlich einen offiziellen Starttermin für Deutschland!
