---
title: "The Green Hornet"
date: "2011-02-05T21:36:06"
categories: [gesehen]
---

*USA (2010)
Regie: Michel Gondry
Darsteller: Seth Rogen (Britt Reid / The Green Hornet), Jay Chou (Kato), Cameron Diaz (Lenore Case), Christoph Waltz (Chudnofsky), David Harbour (Scanlon), Tom Wilkinson (James Reid), Edward James Olmos (Mike Axford) und andere bunte Tiere*
[Offizielle Homepage](http://www.green-hornet.de/filmsite/)

James Reid ist der Besitzer einer großen, unabhängigen Tageszeitung. Doch er hat es nicht geschafft, seinen Sohn Britt zu seinem Nachfolger zu erziehen, so dass dieser eher Karriere als reicher Sohn macht. Als James plötzlich an einem Bienenstich stirbt, muss sich Britt zum ersten Mal in seinem Leben mit einer Verantwortung herumschlagen - der Verantwortung für eine Zeitung, der Verantwortung für deren Mitarbeiter und der Verantwortung der Gesellschaft gegenüber, die informiert werden will.

Da lernt er Kato kennen, der nicht nur ein sehr begabter Mechaniker, sondern auch Kampfsportexperte und ein begnadeter Kaffeemacher ist. Zusammen beschließen sie, dass die Stadt einen Gegenspieler für den Unterweltboss Chudnofsky benötigt. Mit Britts Geld und Meinungsmacht und Katos Fähigkeiten erfinden sie die *The Green Hornet*, der mit seinem Sidekick fortan die Verbrechner aufreibt. Doch der Lebemann Britt bringt sich und Kato damit in größere Gefahr, als er es wahrhaben möchte...

Eine [lange Geschichte](http://en.wikipedia.org/wiki/The_Green_Hornet_(2011_film)#Development) kann die Produktion dieser Neuverfilmung einer TV-Serie nach einem Hörspiel vorweisen. Seit 1992 gaben sich Regisseure (u.a. Kevin Smith), Darsteller und Autoren die Klinke in die Hand und am Ende schrieb Hauptdarsteller Seth Rogen das Drehbuch selber. Als der Film dann schließlich fertig war, kam Sonys Filmvertrieb auf die glorreiche Idee, dass ein paar 3D-Effekte die Einnahmen erhöhen können und verschob den Starttermin um über ein halbes Jahr. Künstlerisch hat diese Entscheidung auf jeden Fall nichts gebracht, denn nur selten wurde mir überhaupt bewusst, einen 3D-Film zu sehen - das typische Ergebnis bei [im Nachhinein konvertierten Filmen](/blog/2010/03/31/alice-in-wonderland/).

Ebenso wenig ist vom Können des Regisseurs zu sehen. Nur selten lassen eine paar außergewöhnliche Kamerafahrten oder -schwenks die kreativen Qualitäten von [Michel Gondry](/blog/2008/04/13/be-kind-rewind/) aufblitzen; meist begnügt er sich jedoch damit, die überwiegenden Actionsequenzen (mit gefühlt 50% nahezu identischen Autoverfolgungsjagden) routiniert in Szene zu setzen. *The Green Hornet* ist also voll und ganz ein Seth-Rogen-Film. Wer mit dem Humor des Schauspielers nichts anfangen kann, sollte einen großen Bogen um diesen Film machen.

Die typische Art von Seth Rogen bestimmt vom Handlungsbogen über die flache Charakterzeichnung bis hin zu den Dialogen alle Aspekte des Films. Dabei stellt er selber Britt Reid zwar als verzogenen Unsympath dar, dem die Rolle als Superheld zufällt, obwohl er sie im Gegensatz zu Kato gar nicht ausfüllt. Doch die Sympathien des Publikums soll gar keiner der Charaktere auf sich ziehen, vielmehr sind sie nur die Grundlage für den Witz des Films, der maßgeblich zu dessen Unterhaltungswert beiträgt. Ob es nun um die typischen Gadgets und Accessoires von Superhelden geht, die Motivation hinter den Masken und Kostümen oder die Beziehungen zu den Heldenhelfershelfern, Seth Rogen lässt keine Gelegenheit aus, sich über die Superhelden-eigene Logik lustig zu machen.

Dies betrifft auch den Gegenspieler der grünen Hornisse, Chudnofsky. Christoph Waltz ist sichtbar unterfordert in seiner Rolle des an seinem Image zweifelnden Gangsters. Er scheint nicht ganz damit klar zu kommen, dass der Film seinen Charakter abwechselnd ernst nimmt und in der nächsten Szene gleich wieder bloßstellt, solange sich ein Lacher damit erzielen lässt. Und diese Ambivalenz ist symptomatisch für den Film. So ist er gleichzeitig die Erfüllung eines Kindheitstraumes, Superheld mit nahezu unbegrenzten Möglichkeiten zu sein, und die dazugehörige Farce, die sich über dessen unrealistische Aspekte lustig macht.

Fazit: *The Green Hornet* ist witzig-unterhaltsames Action-Popcorn-Kino mit geringer Halbwertszeit - also nicht mehr und nicht weniger, als von einem Film von und mit Seth Rogen erwartet werden kann. Etwas weniger Verfolgungsjagden und etwas mehr Hintergrund für die Figuren, und der Film hätte richtig gut werden können. So habe ich mich nur gut amüsiert und warte darauf, dass Michel Gondry wieder bessere Drehbücher ins Bild setzen darf.
