---
title: "Berliner Sechs-Tage-Rennen"
date: "2009-01-27T20:38:56"
categories: [gewesen]
---

Nachdem ich jetzt schon drei Winter in unmittelbarer Nähe zum Velodrom wohne, habe ich es endlich einmal zum [Berliner Sechs-Tage-Rennen](http://www.sechstagerennen-berlin.de/) geschafft - und wurde gleich mit Erik Zabels offiziellen Abschied vom Radsport belohnt.

Trotzdem kam ich in totaler Unkenntnis der Regeln in die Halle mit der 250m-Bahn. Gefahren wird bei [Sechs-Tage-Rennen](http://de.wikipedia.org/wiki/Sechstagerennen) nämlich nicht (mehr) durchgängig, sondern in verschiedenen Ausscheidungen an den Abenden. Und es fahren nicht nur Fahrräder, sondern bei Events wie dem Steher-Preis auch verschiedene Ausbaustufen von Motorrädern vorneweg, um durch ihren Windschatten Geschwindigkeiten von bis zu 80km/h für die Radfahrer zu ermöglichen. 80 Runden bei dieser Wettbewerbsform waren aber zuviel des Guten; selbst wenn man bei nur sechs Pärchen auf der Bahn wenigsten nicht den Überblick verlor.

Dies fiel schon schwerer bei den Doppel-Verfolgungen, wenn ständig alle 36 Fahrer der 18 Teams auf der 250-Meter-Bahn unterwegs sind. Aber gerade zu den Punktausscheidungen ist es dann immer spannend und wenn die Publikumslieblinge Zabel/Bartko einmal den Wechsel verpassten oder eine Panne hatten, dann ging ein Raunen durch die Halle. Als Zuschauer, ob im Innenraum vor der Bühne oder auf den Rängen, ist man in Berlin auf jeden Fall immer nah dran an der Bahn und damit auch an den Sportlern, die im Laufe des Abends so über 100mal an einem vorbeifahren. Im Gegensatz zum Straßen-Radsport also ein deutliches Plus, trotz der gesalzenen Eintrittspreise (ich hatte glücklicherweise Freikarten).

Geboten wird dafür neben viel Werbung und erstaunlich wenig Sport auch ein breites Showprogramm auf Volksfest-Niveau (ICH HABE FRANK ZANDER LIVE GESEHEN!) und viele Siegerehrungen - jeder darf einmal gewinnen. Diesen Mix kann man sechs Abende lang jedes Mal bis weit nach Mitternacht erleben, so es die Halsmuskulatur aushält. Mir hat ein Tag gereicht, aber die Erfahrung kann man durchaus einmal gemacht haben.
