---
title: "Halle und seine Verkehrszählung"
date: "2009-05-10T19:33:27"
categories: [gefunden]
---

Halle arbeitet ebenso wie viele andere Städte an einem Konzept für die Lenkung des seit der Wende deutlich zugenommenen Verkehrsstroms. Eine neuartige Form der Verkehrszählung soll dabei eine objektive Entscheidungsgrundlage liefern. Die [MZ berichtet](http://www.mz-web.de/servlet/ContentServer?pagename=ksta/page&atype=ksArtikel&aid=1241588389406) bewundernd davon, wie die beauftragte Firma an verschiedenen Messpunkten die Kennzeichen aller vorbeifahrenden Autos scannt und speichert. Ziel ist es, den Fahrzeugstrom in ein-, aus- und durchfahrenden Verkehr aufzuspalten, indem die Daten aller Verkehrsknotenpunkte zusammen ausgewertet werden.

Nun sind Kennzeichen an sich keine sensiblen Informationen, allerdings kann man darüber auf die Halter des KFZs rückschließen und erhält so Bewegungsprofile, die nicht die Hände einer privatwirtschaftlichen Firma gehören. Die Stadt Halle hat diesen Punkt mehr Beachtung geschenkt als die MZ und [informiert](http://www.halle.de/index.asp?MenuID=887&NewsID=22370&NewsLocation=7&TotalNews=40), dass die Daten codiert werden und die Datenschutzbeauftragte der Stadt dies abgesegnet hat. Eine vorbildliche Herangehensweise, auf die jedoch seit gestern ein Schatten fällt: Um die verwendete Software zur Kennzeichenerkennung gibt es einen [Rechtsstreit](http://www.pflaster-info-agentur.de/index.php?area=1&p=news&newsid=6015) und der Kläger weist darauf hin, dass es möglich ist, aus den codierten Daten die Kennzeichen wieder zu entschlüsseln.

Ob dies nun der Wahrheit entspricht oder nicht kann ich nicht beurteilen. Aber es ist ein generelles Problem festzustellen, ob eine Software auch wirklich das tut, was der Hersteller verspricht. Deshalb ist es sehr vernünftig, dass Wahlcomputer verboten wurden, da sonst die Herstellerfirmen der Versuchung ausgesetzt wären, Einfluss auf einen der grundlegendsten Prozesse unserer Demokratie zu nehmen. Im Fall der halleschen Kennzeichendaten sind die potentiellen Folgen natürlich nicht annähernd so schwerwiegend, aber ich werde das Thema weiter im Auge behalten.
