---
title: "Guardian of the Spirit"
date: "2010-10-31T23:35:52"
categories: [gesehen]
---

*Guardian of the Spirit* ist eine japanische Animeserie, die in einer Fantasywelt spielt, die dem mittelalterlichen Japan angelehnt ist. Dort trägt der kleine Chagum, der zweite Sohn des Kaisers des Yogo-Imperiums, das Ei eines Wassergeistes in sich. Sein Vater empfindet dies als eine Bedrohung, da die Gründungsgeschichte des Reiches berichtet, dass der erste Kaiser durch den Sieg über so einen Geist an die Macht kam. Um den Sohn zu schützen, gibt ihn seine Mutter in die Obhut der Speerkämpferin und Leibwächterin Balsa.

Die beiden begeben sich zusammen auf die Flucht vor den kaiserlichen Fängern. Freunde von Balsa, u.a. eine alte Schamanin, ünterstützen sie dabei und versuchen mit ihnen herauszufinden, was es mit dem Ei des Wassergeistes auf sich hat. Dabei stellt sich heraus, dass es eine Parallelwelt namens Nayug gibt, die mit der realen Welt eng verbunden ist und sich teilweise überschneidet. Das Ei des Wassergeistes ermöglicht Chagum, zwischen den Welten zu wechseln, denn zur Tag-und-Nacht-Gleiche, wenn die beiden Welten sich so nah sind wie sonst nie, wird der Geist schlüpfen. In Nayug gibt es aber auch Bedrohungen für das Ei und Chagum muss erkennen, dass es sein Schicksal ist, von einem Eierfresser aus Nayug getötet zu werden, damit der Geist leben und die Dürre des Landes beenden kann. Doch Balsa will dies auf keinen Fall zulassen...

Die Geschichte von *Guardian of the Spirit* ist eine angenehme Abwechslung zum üblichen Fantasy-Einerlei. Es gibt keine Zauberei (obwohl die Schamanin Torogai ihre Gegner zu täuschen weiß) und auch keine Zwerge, Elfen, Orks oder sonstige klassische Völker. Vielmehr ähnelt das Setting dem mittelalterlichen japanischen Kaiserreich (inklusive dem Glauben an Geister) und hat als Zugabe die Parallelwelt bekommen. Der reich ausgeschmückten Hintergrund der Geschichte mit den Bewohnern des Yogo-Imperiums bildet dabei ein stimmiges Gerüst, zu der die Parallelwelt Nayug einen starken Kontrast darstellt und somit stärker zur Geltung kommt

Die Charaktere sind ebenso detailliert ausgearbeitet und haben alle nuancierte Lebensgeschichten aufzuweisen. Der Hauptcharakter Chagum altert sogar in der fast ein Jahr umspannenden Story und bekommt ein kantigeres Gesicht, nachdem er anfangs noch die runden Wangen eines Kindes hat. Da die Romanvorlage zur Serie ein Jugendroman ist, finden sich im ruhigeren Mittelteil der 26 Folgen auch einige Episoden, bei denen es um die Sozialisierung von Chagum geht. Als Sohn des Kaisers muss er erst lernen, wie ein normaler Bürger zu leben, sein Essen einzukaufen und sich in die Gesellschaft einzugliedern. Diese feine Sorgfalt in der Gestaltung der Charaktere durchzieht die gesamte Serie und verleiht ihr eine überzeugende Stimmigkeit.

Animationstechnisch ist die TV-Produktion auf höchstem Niveau. Die Hintergründe bestechen duch wunderbar detaillierte Landschaften, die durch eine sehr filmhafte Bildgestaltung mit vielen Totalen sehr gut zur Wirkung kommen. Die Animationen, bei denen auf unpassende 3D-Effekte verzichtet wurde, dafür aber viel mit Tiefenschärfe gearbeitet wird, orientieren sich am um Realismus bemühten Handlungsrahmen und dem ruhigen Storytelling. Die Action, meist in Form von Kämpfen der Speerkämpferin, schließt sich diesem bodenständigen Eindruck an. Zwar springen die acht Krieger des Kaisers in einer Szene durch die Bäume, aber ansonsten ist die zu Grunde liegende Fantasywelt den physikalischen Gesetzen der Realität verbunden.

Ich habe mir die Complete Edition der Serie zugelegt, bei der alle Folgen in einer 5er-DVD-Box enthalten sind. Diese enthält eine gute deutsche Synchronisation, die sogar mit einigen interessanten 5.1-Effekten aufwarten kann. An die Originalstimmen reicht dies nicht ganz heran, doch empfand ich es angenehmer als ständig Untertitel mit zu lesen. Den tollen Soundtrack haben zum Glück alle Sprachfassungen, denn seit *Noir* habe ich keine Musikuntermalung einer Trickserie mehr gehört, die genau den Spagat zwischen Emotionen erzeugender Unterstützung der Handlung und Aufmerksamkeit auf sich ziehender Eigenständigkeit schafft.

Der Bildtransfer ist gelungen und von guter Qualität - bis auf die letzte DVD der Box. Denn dort befindet sich nicht nur eine Folge mehr als auf den vorhergehenden DVDs, sondern auch das gesammelte Bonusmaterial. Dadurch war nicht mehr genügend Platz für eine ansprechende Bitrate, so dass es vereinzelt zu Blockartefakten kommt bzw feine Details wie Farbverläufe am Himmel oder dort fliegende Vögel vermatschen. Schade, mit einer DVD mehr oder einer besseren Aufteilung wäre die Box auch technisch eine Empfehlung gewesen.

Trotzdem ist *Guardian of the Spirit* eine optisch, akustisch wie inhaltlich beeindruckende Serie, die sich durch ihr realistisches Setting und die feine Charakterzeichnung angenehm von anderen Genrewerken abhebt und damit meine Empfehlung verdient.
