---
title: "Metropolis"
date: "2010-01-22T23:08:23"
categories: [gesehen,gefunden]
---

Er war zu seiner Zeit der teuerste Film der Geschichte. Er hat das Genre der Science-Fiction auf der Leinwand quasi begründet und der Tricktechnik im Kino zu einem [Quantensprung](http://www.ikg.rt.bw.schule.de/fh/hydrod/quantenspr.htm) verholfen. Und er bedeutete den Zenit der Babelbergschen Filmproduktionen, bevor die Nazis dafür sorgten, dass Hollywood fortan die Rolle als wichtigste Produktionsstätte einnahm.

Die Rede ist natürlich von *Metropolis*, der Großstadtparabel, Dystopie und Gesellschaftskritik von Fritz Lang aus dem Jahr 1927. Ich habe den Film schon diverse Male gesehen und war immer wieder beeindruckt, welche Leistungen in dieser Pionierzeit des Kinos erbracht wurden. Doch so herausragend der Film aus heutiger Sicht ist - 1927 war die Resonanz keineswegs euphorisch und selbst eine gekürzte und umgeschnittene Fassung konnte den Ruin der Produktionsfirma nicht mehr verhindern (bei 27.000 Statisten kein Wunder).

Der Originalschnitt von Lang galt seit langem als verschollen, und so basierte auch die 2001 restaurierte Version des Klassikers auf der angepassten Kinofassung. Doch vor zwei Jahren wurde in Argentinien eine Kopie des Originals mit den herausgeschnittenen Szenen gefunden und seitdem derselben Restaurierung unterzogen. Im Rahmen der diesjährigen Berlinale kommt es nun am 12.02. zur [Welturaufführung](http://www.metropolis2710.de/de/vorstellungen.html) des neu aufbereiteten "Directors Cut" inklusive einer nach Original-Partituren gespielten Filmmusik, und ich hatte mir berechtigte Hoffnungen auf das Ergattern einer der Premierenkarten gemacht. Leider ist der [Vorverkauf](http://www.berlinale.de/de/service/eintrittskarten/Sondervorverkauf.html) jedoch unabhängig von den normalen Berlinalekarten bereits an diesem Montag gestartet und die Tickets waren schnell ausverkauft.

Zum Glück gibt es aber noch [Arte](http://www.arte.tv). Der Sender [überträgt live](http://de.lifestyle.yahoo.com/07012010/401/zukunft-arte-uebertraegt-welturauffuehrung-metropolis-freitag-12-02-20-45.html) die Uraufführung aus dem Friedrichstadtpalast, so dass ich die Premiere bequem vom Sofa aus verfolgen kann. Da die Stühle im Friedrichstadtpalast maximal unbequem sind könnte dies sogar eine Verbesserung darstellen, je nachdem wie die Bild- und Tonqualität ist (~~leider kann ich Arte noch nicht in HD empfangen~~). Ich freue mich auf jeden Fall riesig über dieses Angebot.

**Offtopic:** Wie jedes Jahr muss ich auch 2010 Werbung für das [Festivalblog](http://www.festivalblog.com/) machen, das nicht nur von der Berlinale berichten und Filme rezensieren wird, sondern momentan auch kurze Rückblenden auf die 59 vorangegangenen Jahre der Jubiläums-Berlinale wirft (zuletzt die für Berlin so spannenden Jahre [1989](http://www.festivalblog.com/archives/2010/01/berlinale_1989_1.php5)/[1990](http://www.festivalblog.com/archives/2010/01/berlinale_1990.php5)).
