---
title: "My first Wordpress-Theme"
date: "2006-01-20T20:44:31"
categories: [getan]
---

Heute habe ich endlich die Arbeiten an meinem eigenen Theme Rin_KO (auf Basis von [Rin](http://www.brokenkode.com/rin)) abgeschlossen und es gleich in meinem Blog eingesetzt. Da das Vorbild unter der [GPL](http://www.gnu.org/licenses/gpl.html) veröffentlicht wurde, habe ich mich an die Regeln gehalten und mein Theme ebenfalls unter diese Lizenz gestellt. ~~Dies bedeutet, dass fortan jeder meine Version downloaden und auch weiterentwickeln kann.~~

Ich habe viele Stunden darin investiert, den HTML- und CSS-Code sinnvoll zu strukturieren und das Layout möglichst unter allen mir zur Verfügung stehenden Browsern identisch zu halten. Nun habe ich eine Basis, auf der ich aufbauen kann, wenn ich auf die neue Version von Wordpress upgrade.

Vielleicht wage ich mich in naher Zukunft auch an ein vollständig eigenes Layout, aber momentan geht erst einmal die Diplomprüfung vor, welche in fünf Wochen ansteht.
