---
title: "Berlin - Frankfurt - Singapur - Australien und zurück"
date: "2012-06-10T23:05:37"
categories: [gedacht,gewesen]
---

Ich bekenne freimütig: Ich trauere dem Aus des Flughafens Tegel hinterher, auch wenn es sich gerade ins nächste Jahr verschoben hat. Den langweiligen und überall auf der Welt zum Verwechseln gleichen Glas-Beton-Palästen der heutigen Zeit fehlt es einfach am Charme des Berliner Sechseckbaus mit seinen kurzen Wegen, aber auch seiner geringen Kapazität. Dennoch wird der neue Großflughafen in Schönefeld eine Verbesserung mitbringen, die Tegel als Kind seiner Zeit nicht vergönnt war: Eine vernünftige Anbindung an den ÖPNV.

Tegel wurde in einer Zeit gebaut, in der Westberlin seinen Nahverkehr auf die Straße verlagerte. Mit großem Tamtam wurde damals [die letzte Straßenbahn verabschiedet](http://khd-blog.net/Heimat/B/Bln/Living_in_a_City_03.html#Tram). Heute steht das Straßennetz Berlins vor dem Kollaps (und [wird leider von den Grünen weiter torpediert](http://www.n-tv.de/politik/Berlin-Kompromiss-koennte-kippen-article4402376.html)) und es werden ab nächsten März sicherlich mehr Menschen die Bahn zum Flughafen nutzen als momentan mit dem Bus nach Tegel fahren.

Der Bus hat nämlich den Nachteil, dass er schlecht geeignet ist, um Koffer und andere Flugbegleiter zu transportieren. Viel schlimmer wiegt aber, dass er im Berufsverkehr selten pünktlich ist (und allgemein sehr langsam). Wäre ich gleich am Alex in den TXL eingestiegen, hätte ich insgesamt eine Stunde von der Haustür bis Tegel benötigt. So bin ich mit der Ringbahn bis Beusselstraße gefahren - und durfte erst einmal warten, denn der Bus kam nicht pünktlich. Als er schließlich ankam, hat nur ein kleiner Teil der wartenden Fahrgäste noch hinein gepasst, da der Bus total überfüllt war. Die Krönung war aber der Busfahrer, der ein paar Personen wieder aus dem Bus warf und behauptete, der nächste sei direkt hinter ihm. Dieser Bus direkt hinter ihm kam dann 10min später (genau im Takt, wenn auch mit derselben Verspätung wie sein Vorgänger) und zeigte, wie dreist der erste Fahrer doch war - um Diskussionen aus dem Weg zu gehen hat er einfach gelogen.

Ich freue mich also, wenn der der neue Flughafen endlich eine der deutschen Hauptstadt würdige Anbindung an den öffentlichen Nahverkehr erhält. Meine Reisen der letzten Jahre haben gezeigt, dass jede größere Stadt so etwas besitzt (New York, Barcelona, Singapur, Sydney, Brisbane) und gerade Touristen gerne darauf zurückgreifen.

---

Umsteigen in Frankfurt kann nervig sein. Um von den Lufthansa-Gates A zum Singapore-Air-Gate B zu kommen, musste ich gefühlte 4km durch einen Tunnel zurücklegen. Da können 80 Minuten Umsteigezeit ganz schön knapp werden - mein Gepäck hat den Umstieg zum Glück auch geschafft.

---

Der Airbus 380 wirkt von innen gar nicht so groß, wie er in Wirklichkeit ist. Ich habe zu keiner Zeit gemerkt, dass unter mir in einer weiteren Etage noch 420 Menschen saßen...

---

Singapore Airlines ist ein Kind seines Staates - sogar vor den Filmen wird Werbung eingespielt und eine Reportage über den Staat bestand zu 100% aus Reklame für bestimmte Hotels und Restaurants. Zu den Filmen und zum Staat später mehr.

---

Eine Konstante aller bereisten Flughäfen ist die Steve-Jobs-Biografie. Was sagt das über unsere Welt aus?

---

Ich habe keine Flugangst und fange nicht an zu schwitzen, wenn das Flugzeug in Turbulenzen gerät. Aber als Software-Entwickler malte ich mir plötzlich die grauenvollsten Szenarien aus, als der Kapitän der Lufthansa-Maschine kurz vor dem leicht verspäteten Start durchsagte, dass die Verzögerung auf ein schnell noch eingespieltes Software-Update zurück zu führen sei...
