---
title: "Wall-E has landed"
date: "2012-08-06T11:56:48"
categories: [gefunden]
---

> It once was one small step... now it's six big wheels.

Die NASA weiß, was Marketing ist. Und so trägt [das leicht übergewichtige Fahrzeug](http://mars.jpl.nasa.gov/msl/multimedia/interactives/learncuriosity/index-2.html) der aktuellen Marsmission nicht nur den schönen Namen Curiosity (Neugierde), sondern hat auch seinen eigenen [Twitter-Account](http://twitter.com/marscuriosity), auf dem es aus seiner Sicht von der komplizierten Landung berichtet hat. Weitere Nachrichten und vor allem Bilder sollen folgen, und die breite Berichterstattung mit all den Hintergründen dieses wissenschaftlichen Projekts führt dazu, dass ich inzwischen mit dem an [Wall-E](/blog/2008/09/28/wall-e/) erinnernden Marsrover und seiner spannenden Mission mitfiebere. So oder ähnlich müssen die Zuschauer sich 1969 vor den Fernsehern gefühlt haben, als die ersten Menschen medial begleitet den Mond betraten. Kein Wunder, dass die NASA mit dem oben zitierten Spruch genau diese Assoziationen erwecken will...
