---
title: "Urlaubs-Blog-Update"
date: "2007-08-28T15:06:35"
categories: [getan]
---

Manchmal braucht es einfach den Urlaub, um sich an so ein heikles Thema wie das eigene Theme heranzuwagen. Ich habe zwar ziemlich schnell aufgegeben, ein komplett neues Theme zu entwerfen (mein Dank geht dabei an die Browserhersteller, die HTML und CSS alle anders interpretieren), habe dafür aber ein paar kleine Korrekturen an rin_KO vorgenommen.

Außerdem habe ich mir mein eigenes kleines Widget **Warteliste** gebastelt, welches mich daran erinnert, wann vorgemerkte Bücher, CDs oder Filme den freien Handel oder das örtliche Kino erreichen. Bei den Büchern lohnt es sich meist, schon ein paar Tage vorher die Buchhändler aufzusuchen, da Erscheinungstermine dort erfahrungsgemäß eher pessimistische Richtwerte sind.

Die Icons stammen übrigens aus dem [Tango Desktop Project](http://tango.freedesktop.org/Tango_Desktop_Project), die ihre Sammlung freundlicherweise unter der [Creative Commons Attribution Share-Alike license](http://creativecommons.org/licenses/by-sa/2.5/deed.de) veröffentlicht haben. D.h. jeder kann diese Icons nutzen und sogar weiterverarbeiten, solange sie unter einer freien Lizenz bleiben. Dies tue ich hiermit und stelle die [drei modifizierten Icons](KO_Tango_Icons.zip) unter dieselbe Lizenz.
