---
title: "Stirb an einem anderen Tag"
date: "2002-12-10T00:00:44"
categories: [gesehen]
---

*USA/UK (2002)
Regie: Lee Tamahori
Darsteller: Pierce Brosnan (James Bond), Halle Berry (Jinx), Rosamund Pike (Miranda Frost), Toby Stephens (Gustav Graves), Rick Yune (Zao), Will Yun Lee (Colonel Moon), Michael Madsen (Damian Falco), Judi Dench (M), John Cleese (Q), Samantha Bond (Miss Moneypenny), Colin Salmon (Charles Robinson), Emilio Echevarria (Raul), Madonna (Verity) und andere Doppelnullen*
[Offizielle Homepage](http://www.jamesbond.com)

Nach dem (scheinbar) erfolgreich ausgeführten Auftrag, in Nordkorea einen General aus den Weg zu räumen, gerät James Bond in die Gefangenschaft der Koreaner. Nach 14 Monaten Folter wird er überraschenderweise gegen den Kriegsverbrecher Zao ausgetauscht und Bond ist sich sicher, dass irgendwer im IM6 ein schlechtes Spiel mit ihm spielt. Also verfolgt er Zao nach Kuba und macht dabei die Bekanntschaft der amerikanischen Agentin Jinx. Trotz beider Bemühungen gelingt Zao zwar die Flucht, doch Bond kann eine Verbindung zwischen dem Koreaner und dem neureichen Diamantenhändler Graves ausmachen. Und so trifft 007 auf der Präsentation von Graves neuestem Weltraumprojekt in Island nicht nur Jinx und Zao wieder, sondern auch die Doppel-0-Agentin Miranda Frost, die von M auf Graves angesetzt wurde. Doch wer ist nun genau auf Bonds Seite, wozu dient der Sonnenspiegel, den Graves stolz präsentiert, und was suchen nordkoreanische Generäle so weit im Norden Europas...?

Es hat so lange gedauert wie selten zuvor, bis endlich der neue, inzwischen 20. Bond-Film in die Kinos kam, und dementsprechend groß war meine Erwartung - erst Recht nach dem sehr enttäuschenden "Die Welt ist nicht genug". Und so möchte ich mit den typischen Bond-Eigenschaften meine Bewertung beginnen.

1.) James Bond himself: Das klassische "Bond, James Bond" wird zum ersten Mal von Pierce Brosnan richtig interpretiert, die Oneliner ziehen fast alle, doch der Robinson-Verschnitt und die mangelnde Fähigkeit zum Ausbruch aus der koreanischen Folter lassen einen zwiespältigen Eindruck zurück.
2.) Die Anfangssequenz: Einer unmotivierten Surfeinlage, deren Sinn sich mir nicht ganz erschließt, folgt eine spannende Verfolgungsjagd auf Luftkissenfahrzeugen, die mit einem trockenen Oneliner endet - und der Festnahme Bonds (!). Fazit: gesundes Mittelmaß.
3.) Das Bondthema wird erfrischenderweise mit der Handlung (die Folterung Bonds) verbunden und überzeugt trotz des schlechten, 007-untypischen Dance-Sounds. Fazit: Besser als bei den Vorgängern!
4.) Die Bösewichter: Zao darf meistens nur weglaufen und ist ein eher schlechter Handlanger. Graves dagegen ist ein klassischer Bond-Gegenspieler mir eigenem Eispalast und Killer-Satelliten und kann deshalb positiv überzeugen.
5.) Action und Autos: Routinierte, aber an Innovationen arme Action-Szenen und eine optisch gelungene, aber trotzdem langweilige Verfolgungsjagd im Aston Martin Vanquish sind eigentlich unter Bond-Standard.
6.) Girls und Technik: Alle Frauen scheinen neuerdings mindestens einer Geheimorganisation anzugehören, fallen aber ingesamt in ein gesundes Bond-Mittelmaß. Dagegen hat Q wohl zu viel StarTrek geschaut, denn seine Tarnvorrichtung und das Holodeck kommen mir seltsam bekannt und deshalb auch reichlich unpassend vor. Fazit: Unter dem Durchschnitt.

Für einen Bond-Film fällt die 20. Inkarnation also nicht so berauschend aus. Dazu kommt, dass viele Elemente einfach aus älteren Bonds geklaut wurden - ich sage nur die Laser! Die Computereffekte sind die schlechtesten, die ich seit Jahren gesehen habe und außerdem scheint dem Film eine wirkliche Story zu fehlen. Auch nach der Auflösung im (nachgeschobenen) Ende (warum ist der Film in Island nicht zu Ende sondern hat Überlänge?) passen die einzelnen Teile nicht zu 100% zusammen, und warum man Halle Berry als weiblichen Bond mit eigenem Endkampf einführen muss ist mir auch nicht ganz schlüssig (nur wegen dem Oscar?). Vielleicht sollten die Produzenten nach 2 schlechten Filmen mal einen größeren Schnitt wagen und mehr Sorgfalt bei Drehbuch und Regisseur walten lassen - und vielleicht auch beim Hauptdarsteller!

Endgültiges Fazit: Endlich wieder Bond! Doch leider fehlt "Die another day" auf der Suche nach dem Mittelweg zwischen klassischen 007-Tugenden und Annäherung an moderne Kinokonventionen einiges zu einem guten Film. Fans werden zumindest gut unterhalten, alle anderen sollten sich lieber "Goldeneye" mal wieder anschauen.
