---
title: "7 Zwerge - Männer allein im Wald"
date: "2004-11-03T00:00:55"
categories: [gesehen]
---

*Deutschland (2004)
Regie: Sven Unterwaldt jr.
Darsteller: Otto Waalkes (Bubi, Trompeter, Bubis Eltern), Heinz Hoenig (Brummboss), Mirko Nontschew (Tschakko), Martin Schneider (Speedy), Markus Majowski (Cookie), Boris Aljinovic (Cloudy), Ralf Schmitz (Sunny), Cosma Shiva Hagen (Schneewittchen), Nina Hagen (Königin), Hans Werner Olm (Spliss), Atze Schröder (Hofnarr), Christian Tramitz (Jäger), Norbert Heisterkamp (achter Zwerg), Rüdiger Hoffmann (Spiegel an der Wand), Mavie Hörbiger (Rotkäppchen), Helge Schneider, Tom Gerhardt, Hilmi Sözer, Harald Schmidt, Helmut Zerlett und weitere Comedians*
[Offizielle Homepage](http://www.7zwerge-derfilm.de/)

Das arme Schneewittchen hat es nicht leicht: Als Waise im Kinderheim aufgewachsen, muss sie kurz vor ihrem 18. Geburtstag sogar um ihr Leben bangen, da sie hübscher als die Königin ist und diese das ganz und gar nicht akzeptiert. Also flüchtet das Mädchen in den Unterwald, wo die 7 Zwerge hausen - allesamt Männer, die von den Frauen enttäuscht wurden und deshalb beschlossen, abstinent von der holden Weiblichkeit zu leben. Dort räumt Schneewittchen erst einmal richtig auf, doch gerade als sich die Zwerge an sie gewöhnt haben taucht die böse Königin im Wald auf...

Nachdem seine Nachfolger in diesem Jahr schon ordentlich an den Kinokassen abgeräumt haben ([(T)Raumschiff Surprise](/blog/2004/07/22/traumschiff-surprise-periode-1/) und [Der Wixxer](/blog/2004/06/03/der-wixxer/)), gibt es nun auch einen neuen Film von dem Komiker, der als erster den Sprung auf die Leinwand wagte und damit den Weg bereitete für alle nach ihm: Otto!

Nach der großen Enttäuschung mit dem Katastrofenfilm änderte der Ostfriese nun sein Konzept und verpflichtete eine große Reihe von sogenannten Comedians, damit nicht nur er im Vordergrund steht. Außerdem versuchte er sich erneut am Erfolgsrezept der deutschen Komödie und drehte deshalb eine Parodie - auf deutsches Märchengut, wodurch er sicherlich auch den einen oder anderen jüngeren Zuschauer für den Film gewinnen wollte. Damit steht er aber nun thematisch in direkter Konkurrenz zu Shrek (Teil [1](/blog/2001/07/10/shrek/) + [2](/blog/2004/07/01/shrek-2/)), der die Messlatte ganz schön hoch gelegt hat.

Trotz der Vielzahl an verschiedensten Komödianten merkt man dem Film deutlich die Handschrift von Otto Walkes an. Die englischen Wortspielereien am Anfang, das infanile Grinsen und Herumgehopse und die hohe Stimme sind altbekannt und können keinen Kinogänger mehr hinter dem Ofen hervorlocken. Zu wenig neue Ideen erweitern das alte Konzept (und werden deshalb ständig wiederholt) und so bin ich froh, dass ich den Ostfriesen nicht die ganzen 90 Minuten ertragen muss. Denn neben den 7 anderen Zwergen (einer wird erst am Ende ein richtiger Zwerg) bevölkern ganze Heerscharen von bekannten Gesichtern die Handlung. Neben einschlägig bekannten Seriendarstellern und Alleinunterhaltern haben jedoch auch Heinz Hoenig, Boris Aljinovic und Nina und Cosma Shiva Hagen für den Film unterschrieben. Während Mutter Hagen mit sichtlicher Freude die Rolle der bösen Königin vollkommen überspitzt interpretiert (und dabei nicht einmal die Mutter von Schneewittchen darstellt - Ironie der Wirklichkeit), muss die Tochter dem Drehbuch entsprechend das Schneewittchen als naives Mädchen darstellen, dass mit Barbie-Puppen (von Atze Schröder!) ihre Träume vom Märchenprinzen nachspielt - nicht gerade eine anspruchsvolle Rolle.

Alle anderen Darsteller machen den ganzen Film über nur eine Sache: Sie spielen sich selber. Mirko Nontschew ist noch immer die selbe Nervensäge wie zu "Samstag Nacht"-Zeiten, Martin Schneider kann außer dem langsamen Hessen wahrscheinlich nichts anderes darstellen, Christian Tramitz setzt die Schwächen seiner eigenen Serie fort (die Bullyparade ist nur mit allen dreien zusammen witzig), Rüdiger Hoffmann bringt wie immer sein "Ich weiß nicht ob Sie es schon wussten, aber ..." und Atze Schröder ist natürlich Atze und erzählt fast ausschließlich Blondinenwitze. Der einzige Aspekt, der die altbekannten Rollen witzig macht, ist die Tatsache, dass alle wie in Märchenfilmen kostümiert sind. So erst wird aus Rüdiger Hoffmann und dem Spiegel ein Lacher und aus Atze ein schlechter Hofnarr, der nach einer Straftoupierung seine Originalfrisur erhält. Der Einzige, der in dieser Reihe positiv auffällt ist Hans Werner Olm, der in seiner Rolle vollkommen aufgeht und so das Prädikat Schauspieler verdient!

In weiteren Kurzrollen treten auch Tom Gerhardt und Hilmi Sözer auf; Helge Schneider parodiert in einer der stärksten Szenen des Film den Zauberer Gandalf aus Der Herr der Ringe - [Die zwei Türme](/blog/2002/12/18/der-herr-der-ringe-die-zwei-turme/) ("Werft den Ring doch einfach ins Feuer!") und Helmut Zerlett darf wie in guten alten Show-Zeiten am Keyboard den Auftritt von Harald Schmidt einleiten - der dann jedoch nur einen Satz sagt und damit leider keinen Beitrag zum Film leistet.

Die Ansammlung von Comedians kann also nicht sehr viel zum Gelingen der Parodie beitragen - das Drehbuch leider auch nicht. Von dem Originalmärchen bleibt nicht viel übrig - die Zwerge sind nicht einmal Zwerge. Auch aus dem Thema Männer-WG wird eigentlich kein Kapital geschlagen und warum andauernd gesungen werden muss (meist auch noch sehr mies) ist mir ebenfalls nicht klar. Nur wenige witzige Elemente wie das Pferd können davon ablenken, dass der Film eine Ansammlung von Sketchen mit schlechten Überleitungen darstellt und dem Anspruch einer Parodie nur selten gerecht wird.

Produktionstechnisch kann der Film mit seinen Konkurrenten auch nicht mithalten. Zwar gibt es am Anfang eine schön gezeichnete Karte zu sehen, doch ansonsten sind die Sets einfach zu klein und zu schlecht ausgestattet, um noch realistisch zu wirken. Auch die Kostüme sind eher unter dem Durchschnitt und zeugen mehr von Fantasielosigkeit denn von Einfallsreichtum. Hier wurde wahrscheinlich das Geld gespart, welches die Verpflichtung von so vielen bekannten Namen gekostet hat.

Fazit: Selbst wenn sich Otto weitgehend zurückhält - seine altbekannte Art von Humor dominiert den Film. Da können auch die vielen Auftritte von bekannten Comedians nichts daran ändern (die auch nur ihre bekannten Seiten zeigen). Ein Film also, den man nicht gesehen haben muss, weil man fast alles schon kennt!
