---
title: "Der Friedhof in Prag"
date: "2012-10-03T19:26:22"
categories: [gelesen]
---

*von Umberto Eco,
veröffentlicht vom Carl Hanser Verlag, ISBN 978-3-446-23736-0, 26,00€*

Simon Simonini wird 1830 in Turin in eine aufregende Zeit hineingeboren: Giuseppe Garibaldi ist dabei, die italienischen Fürstentümer zu einem republikanischen Nationalstaat zu vereinen. Sein Vater unterstützt diese Bewegung und heuert bei den Rothemden an, so dass Simon von seinem Großvater, einem Jesuiten und strengen Monarchisten, erzogen wird. So kommt er von klein auf mit Verschwörungstheorien um Freimaurer, Logen, Juden und Satanisten in Kontakt, die er zwar nicht für sich annimmt, die aber doch sein Bild von der Welt prägen.

Nachdem sein Vater und Großvater sterben, geht der junge Simonini bei einem Notar in die Lehre, der sich nebenbei als Dokumentefälscher verdingt. Bald ist Simonini seinem Lehrer auf diesem Gebiet überlegen und kommt so in Kontakt mit dem piemontesischen Geheimdienst, der ihn als Spion auf den Sizilienfeldzug von Garibaldi schickt. Als dieser Auftrag schief läuft, muss er seine Heimat verlassen und nach Paris fliehen. Doch auch dort sind seine Dienste als Fälscher schnell von Nutzen und Simonini erprobt seine Theorie, wonach eine Verschwörung umso glaubhafter ist, je mehr sie den Menschen bereits bekannte "Fakten" enthält, indem er seinen von einer geheimen Versammlung handelnden Text *Der Friedhof in Prag* immer wieder neu verkauft: An Kirche und Sekten genauso wie an Geheimdienste von Deutschland über Frankreich bis nach Russland.

Voller realer Geschichte steckt dieser Roman, und (fast) alles ist verbrieft und verbürgt. Die handelnden Personen und aufgeführten Ereignisse und Dokumente hat es wirklich gegeben - mit einer Ausnahme: Der Hauptakteur Simon Simonini ist erfunden, und damit auch die Verbindung zwischen den Autoren, die dem Antisemitismus im 19. Jahrhundert mit dem Aufgreifen der Weltverschwörung durch die Juden und ihrer geheimen Treffen und Rituale zum Durchbruch verhalfen. Das Thema mündete schließlich in den „Protokollen der Weisen von Zion“, welche Futter für den größten Völkermord des letzten Jahrhunderts waren.

So, wie der Protagonisten seine Theorie einer glaubhaften Verschwörung entwickelt, kann auch der Roman selber aufgefasst werden: Als Vorurteil gegenüber der Geschichte, dass es eine treibende, steuernde Kraft hinter all den komplexen Ereignissen geben muss, die dem Geschehen im Nachhinein Sinn und Ziel gibt. Allen Verschwörungsränken wird so der Spiegel in Form einer Konspiration vorgehalten. Das ist zeitweilig sehr interessant zu lesen, vor allem für mich, der ich parallel mit dem Buch auch die mir bisher wenig bekannte Geschichte des 19. Jahrhunderts um die Vereinigung Italiens oder die Pariser Kommune entdeckte.

Doch als vertraue Eco nicht auf die Spannung des natürlichen Ablaufs der Ereignisse, verpackt er seine Handlung in eine verschachtelte Erzählform um einen Erzähler, dem die Tagebücher von Simonini und eines Abbé Piccola vorliegen, die beide ein und dieselbe Person mit einer temporären Persönlichkeitsspaltung sind. Zudem wird gegen Ende die geschilderte Zeit sehr komprimiert dargestellt, so dass ich irgendwann nicht mehr mit den vielen Akteuren klarkam. Wer war jetzt noch Jesuitenpater und wer hatte erst die Kirche verflucht, nur um sie danach als treuer Christ mit Büchern gegen die Juden zu füttern? Das ist einfach zu viel: Antiheld Simonini hat bei so vielen geschichtlichen Ereignissen die Finger im Spiel, dass die Grundidee des Buchs sich am Ende merklich abnutzt. Was bleibt ist ein interessanter geschichtlicher Exkurs und einige Weisheiten über das Wesen von Verschwörungen inklusive der Metaebene, die *Der Friedhof in Prag* trotzdem lesenswert machen.
