---
title: "Dominant Species"
date: "2011-07-23T18:56:52"
categories: [gespielt]
---

Gestern habe ich zur Abwechslung mal wieder ein Brettspiel gespielt, das zu einem sehr langen und spannenden Spieleabend geführt hat und deshalb hier von mir vorgestellt wird. *Dominant Species*, gerade erst in einer deutschen Fassung zum relativ hohen [Preis von 55€](http://www.milan-spiele.de/dominant-species-deutsch-p-12835.html) erschienen, ist von der Spielmechanik her das komplexeste Spiel, das ich je gespielt habe (allein [die Anleitung umfasst 20 Seiten](http://www.gmtgames.com/domspecies/DomSpec_Rules_FINAL.pdf)). Sieht es auf den ersten Blick mit seinen sechseckigen Kacheln auf dem Spielfeld und den auf den Ecken zu platzierenden Elementen aus wie eine Variation der *Siedler*, ergeben sich schnell Unterschiede zu dessen Spielprinzip. So ist das Spiel vollkommen unabhängig vom Zufall eines Würfels, sondern generiert seinen unvorhersehbaren Lauf allein aus der Komplexität, die bei mehreren Mitspielern sofort dazu führt, dass eine Runde zwar geplant werden kann, aber niemals so wie erwartet abläuft.

Aber alles der Reihe nach. Zuerst will ich <del>kurz</del> erläutern, wie das Spiel gespielt wird. Es lässt sich vielleicht am Besten als rundenbasiertes Aufbaustrategiespiel beschreiben, jedoch ist es damit nicht vollständig zu erfassen. Als Handlungsrahmen dient die Zeit vor der letzten Eiszeit, als viele Spezies ihren Lebensraum verloren und vor der Wahl standen, sich an die neuen Bedingungen anzupassen oder auszusterben. Da alle Tierarten durch die Nahrungskette miteinander verbunden sind, war dies ein recht komplexer Prozess. *Dominant Species* greift sich exemplarisch sechs Tierarten heraus (Säugetiere, Reptilien, Vögel, Amphibien, Spinnen & Insekten) und lässt die Spieler damit gegeneinander antreten. Sieger ist am Ende diejenige Spezies, die die meisten Siegpunkte gesammelt hat.

Jede der Tierarten ist von einer bestimmten Nahrung abhängig, im Spiel Elemente genannt. Von denen gibt es ebenso sechs verschiedene Arten (Gras, Larven, Fleisch, Samen, Sonne & Wasser), die auf dem Spielfeld verteilt sind. Dieses stellt die prähistorische Erde vereinfacht als Feld von Kacheln dar, bei denen jede Kachel für eine Vegetation steht (Gebirge, Wüste, Wald, Dschungel, Savanne, Sumpf und Meer). Wird ein Gebiet (= eine Kachel) von einem Gletscher überrollt, bleibt nur noch eine Tundra übrig, die sich im Laufe des Spiels weiter ausbreitet. Diese hat zwar nur geringe Auswirkungen auf die Nahrungselemente (diese wachsen dort auch weiterhin), aber Tundra-Felder geben weniger Siegpunkte als normale Vegetationsfelder.

Gestartet wird das Spiel mit einem Grundaufbau, bei dem jede Tierart auf einem zu ihr passenden Vegetationsfeld startet, dessen Ecken mit Nahrungselementen ausgestattet sind, an die die Spezies angepasst ist. Im Laufe des Spiels kann und muss der Spieler seine Tierart an andere Nahrungselemente anpassen, um neue Spielfelder zu erobern. Landet ein Spielstein, ein kleiner farbiger Würfel, auf einem Feld, an dem kein Nahrungselement vorhanden ist, an das die Tierart angepasst ist, dann stirbt dieses Tier am Ende der Runde auf dem Feld aus.

Auf jedem Spielfeld gibt es zwei Typen der namensgebenden Dominanz: Das Feld kann qualitativ von der am meisten angepassten und auf dem Feld vertretenen Spezies dominiert werden, und quantitativ, d.h. die Tierart mit den meisten Steinen auf dem Feld dominiert. Am meisten angepasst ist eine Spezies dann, wenn sie die beste Kombination aus eigenen Abhängigkeiten und den am Spielfeld vorhandenen Nahrungselementen besitzt (die genaue Rechnung erspare ich mir hier; sie hat gestern aber wiederholt gezeigt, dass Informatiker nicht zwangsweise fit in den Grundrechenarten sein müssen).

Damit sich auf dem Spielfeld etwas verändert, wird jede Runde eine Reihe von Aktionen in festgelegter Reihenfolge durchlaufen. Diese insgesamt 11 Aktionen reichen von Anpassung an die Nahrungselemente, Rückbildung derselben, Vermehrung, Wanderung und Migration bis hin zum Konkurrenzkampf und Vergletscherung. Die Spieler besitzen jeweils eine Anzahl von Aktionsfiguren, die sie in der Reihenfolge der Nahrungskette auf die Aktionen verteilen können. Jede Aktion ist dabei auf eine bestimmte Anzahl begrenzt, pro Runde können sich zum Beispiel nur drei Spezies anpassen. Jeder Tierart hat zudem bei jeweils einer Aktion einen Artenvorteil; so dürfen sich die Insekten pro Runde immer vermehren, egal ob sie eine Aktionsfigur auf die Vermehrenaktion gesetzt haben oder nicht.

An dieser Stelle erklärt sich die Komplexität des Spiels. Jeder Spieler muss sich für eine Taktik entscheiden und versuchen, seine Aktionsfiguren auf die dafür notwendigen Aktionen zu setzen. Da diese limitiert sind, müssen oft Kompromisse eingegangen werden. Zudem können Aktionen wie die Vergletscherung, bei der ein Vegetationsfeld in eine Tundra verwandelt wird, dazu führen, dass der Spieler die eigene Runde umplanen muss. Bei der gestern gespielten Runde gab es so ständig wechselnde Vorteile auf dem Spielfeld; nur die ständige Anpassung des eigenen Spiels an die sich verändernden Begebenheiten bringt den Erfolg.

Ganz zum Schluss jeder Runde gibt es noch die Dominanzrunde. Wer seine Aktionsfigur darauf setzt, darf sich ein Vegetationsfeld aussuchen, auf dem die quantitative Dominanz ermittelt wird. Je nach Vegetation ergibt diese Auswertung eine bestimmte Anzahl Siegpunkte. Wird das Feld gleichzeitig noch qualitativ von der eigenen Spezies dominiert, darf der Spieler eine von fünf am Feldrand ausliegenden Dominanzkarten auswählen und ausspielen. Diese Dominanzkarten sind ein sehr mächtiges Spielelement, das den Spielverlauf eine vollkommen andere Richtung geben kann. Die Karten reichen von positiven Effekten wie mehr Aktionsfiguren über negative Wirkungen (z.B. entferne je ein Nahrungselement, an das die anderen Spezies angepasst sind) bis hin zu der Katastrophenkarte, die ganze Vegetationsfelder leerfegt. Manche Karten zeigen kurzfristige Effekte, andere wirken längerfristig nach; manchmal kann es auch wichtig sein, sich die Karte vor den anderen Spielern zu sichern, um nicht von positiven Effekten ausgeschlossen zu werden und damit einen langfristigen Nachteil zu haben.

Insgesamt sind diese Dominanzkarten wohl der wichtigste Faktor zum Spielgewinn, wenngleich sie nicht immer ausschlaggebend sein müssen. Da manche Effekte zu unterschiedlichen Spielabschnitten unterschiedliche starke Auswirkungen zeigen, ist das Balancing aus meiner Sicht nicht optimal. Auf der anderen Seite kann die richtige Wahl der Karten das Spiel noch einmal drehen, so dass die Spannung erhöht wird. Die letzte mögliche Dominanzkarte, die Eiszeit, beendet schließlich das Spiel. Neben den schon durch Dominanzen erzielten Siegpunkten werden nun noch Punkte für quantitativ dominierte Vegetationsfelder verteilt und diejenige Tierart, welche die meisten Siegpunkte gesammelt hat, zum Spielsieger erklärt.

Mit dieser Beschreibung sollte ich einen ungefähren Eindruck von *Dominant Species* vermittelt haben. Verschiedene kleine Einschränkungen und von mir nicht erwähnte Regeln sorgen dafür, dass es zwar Unterschiede zwischen den sechs Spezies gibt, aber diese sich gegenseitig gut ausgleichen. Durch die große Vielfalt an Möglichkeiten, die sich aus den Aktionen und Dominanzkarten ergeben, muss die eigene Situation auf dem Spielfeld ständig neu analysiert werden. Eine Taktik, die aufgrund der eigenen Tierart die ersten Runden erfolgreich ist, kann im späteren Verlauf ein Nachteil sein und bei anderen Spezies gar nicht funktionieren. Ständige Anpassung und Flexibilität ist also das A&O, und das Salz in der Suppe sind die Taktiken der Gegner, die der eigenen Tierart mal ins Blatt spielen können und in anderen Situationen den Weg verbauen.

Wir haben gestern zwei Runden gespielt. In der Proberunde mit nur zwei Durchgängen musste ich schmerzhaft erfahren, dass Säugetiere aufgrund ihres initial schlechten Status am oberen Ende der Nahrungskette (und damit beim Aktionensetzen an letzter Stelle) zu Beginn des Spiels einen schweren Stand haben. Das zweite Spiel habe ich dann mit den Insekten am anderen Ende der Nahrungskette und einer angepassten Taktik gewonnen, wobei sich mein anfänglicher Vorsprung im mittleren Spielabschnitt schnell aufbrauchte und erst ein paar Entscheidungen der Gegner in der vorletzten Runde den Sieg brachten.

Dieses Spiel zu viert (*Dominant Species* ist für zwei bis sechs Spieler vorgesehen) dauerte am Ende über vier Stunden, obwohl wir nur mit einer Auswahl der verfügbaren Dominanzkarten gespielt haben. Je nachdem, wie viel Zeit sich die Spieler bei der Planung und Durchführung ihrer Aktionen lassen, kann sich die Spielzeit verkürzen oder verlängern, aber ein Spiel für Zwischendurch ist *Dominant Species* auf keinen Fall. Die Spieler müssen definitiv etwas Geduld und einen Hang zum taktischen Planen mitbringen. Gerade kurz vor Schluss war ich sehr angespannt angesichts meiner Siegchancen und damit ungeduldig, wenn sich mein direkter Konkurrent Zeit beim Setzen seiner Aktionsfiguren ließ. Wer aber diese Eigenschaften besitzt und die Gelegenheit hat, das Spiel öfters zu spielen, der sollte nicht vor den für ein Brettspiel hohen Kosten zurückschrecken - ein spannenderes Spielerlebnis hatte ich lange nicht mehr!

Eine Anmerkung noch zu der deutschen Fassung: Bis auf die Vegetationsfelder sind alle Spielkarten, das Spielfeld und die Anleitung komplett übersetzt. Ein paar Rechtschreib- (u.a. leider auch auf dem Feld) und Übersetzungsfehler trüben das Gesamtbild etwas, haben zum Glück aber keinen Einfluss auf das Spielgeschehen. Vor dem ersten Spiel sollte die Anleitung ausgiebig studiert und am Besten eine Proberunde eingelegt werden, um die komplexen Regeln weitgehend zu beherrschen - ansonsten ist die Gefahr falscher Entscheidungen im Spielverlauf groß.
