---
title: "The Legend of Zelda: Breath of the Wild"
date: "2021-10-10T16:01:00"
categories: [gespielt]
---

Vor ungefähr 30 Jahren war Teil 1 der Zelda-Reihe auf dem NES mein allererstes Open-World-Spiel - auch wenn ich den Begriff zu der Zeit nicht kannte. Damals wurde ich als Spieler mit einer sehr rudimentären Handlung in eine Welt geworfen, die ich zwar theoretisch von Anfang an komplett erkunden konnte, die aber schnell aufzeigte, wo der Charakter Link seine Grenzen hat. Erst mit wachsendem Waffenarsenal aus den Dungeons war der Held wirklich für viele Bereiche gerüstet, und einiges im Spiel war so gut versteckt, dass ich ohne einen Spieleführer nicht weit gekommen wäre.

Die Rückkehr der Zelda-Reihe in das Open-World-Genre ließ die Erinnerungen an meinen ersten Ausflug nach Hyrule wach werden. Gerade zu Beginn des Spiels fühlte ich mich verloren in der großen, teilweise unverständlichen Welt. War die knappe Story in den 80ern nicht ungewöhnlich, sind die kargen Happen, die Breath of the Wild dem Spieler hinwirft, heutzutage sehr irritierend, gerade verglichen mit Storymonstern wie RDR oder Skyrim.

In der ersten Spielstunde trifft Link auf genau einen NPC, und dessen Dialoge sind nicht einmal vertont. Dies trifft auf den Großteil der Gespräche im Spiel zu - das ist ganz und gar nicht zeitgemäß. Dieser Charakter erklärt dem Spieler einige Game-Mechaniken, doch schon in dieser Erklärphase des Spiels in einem begrenzten Bereich der Welt zeigt Breath of the Wild, dass es es dem Spieler niemals einfach machen wird. Freie Exploration ist quasi das Grundgerüst des Spiels, nur selten wurde ich explizit irgendwo hingeschickt, um etwas zu tun.

Schnell lernte ich, dass sich die meisten Waffen sehr schnell abnutzen (sehr ärgerlich), dass mit Klettern (und ausreichend Ausdauer) eigentlich jeder Ort von Hyrule erreicht werden kann und dass es kalte, warme und heiße Gegenden gibt, die spezielle Kleidung oder Nahrung erfordern, um dort zu überleben.

Dabei hatte ich gleich meinen ersten Frustmoment im Spiel. Von einem Buch in einer Försterhütte erfuhr ich, dass ich ein Ziel oben auf einem Berg nur mit einem speziellen Gericht gegen die Kälte erreichen kann. Für dessen Herstellung muss ich Wild mit einer unbekannten Zutat mischen. Dumm war nur: An der Jagdstelle wollte lange Zeit kein Wild zum Jagen auftauchen (Bug?). Und dann wusste ich immer noch nicht, was die unbekannte Zutat ist. Dieses "Probieren geht über Studieren" ist ein Grundprinzip des Spiels, aber hier war es zwingend zum Weiterkommen notwendig. Da ich so wenig Wild hatte, ging das nur über Speichern und Neuladen. Nach drei Stunden Frust griff ich deshalb zum ersten Mal nach dem Ratgeber Internet - im erweiterten Intro eines Spiels sollte das eigentlich nicht notwendig sein.

Nach dieser etwas holprigen Einführung wurde es zum Glück besser: Die anfangs leer wirkende Welt hat neben vielen Monstern auch ein paar Dörfer zu bieten und zu meiner Verwirrung ein knappes Dutzend Ställe. Dort finden sich dann endlich auch ein paar Quests abseits der Hauptstory, d.h. es gibt endlich etwas Struktur neben dem freien Erkunden. So kam ich ziemlich schnell zu einem der vier Endbosse - Titanen genannte Riesenmaschinen, die erst in Betrieb genommen werden müssen, um danach einen vom Oberbösewicht Ganon gesandten Fluch zu besiegen.

Bei meinem ersten Versuch, den Wasserfluch Ganons im Titan Vah Ruta zu besiegen, lernte ich aber schnell: Ich war zu früh und unvorbereitet in die Aufgabe gerannt. Denn auch wenn Breath of the wild ein Action Adventure ist und deshalb Erfahrungen sammeln und Fähigkeiten ausbauen kein Spielinhalt sind, so gibt es doch mit den Herzen und der Ausdauer Attribute, die zwingend erhöht werden müssen, um gegen die Endbosse anzukommen.

Und wie kommt man zu diesen Updates? Da kommt wieder die explorative Spielmechanik zum Tragen: In ganz Hyrule sind über 100 Schreine mehr oder weniger gut versteckt, in denen Jahrtausende alte mumifizierte Priester mit für Action Adventures üblichen Rätseln dem Spieler Herausforderungen stellen, deren Lösung mit einem sogenannten Zeichen der Bewährung belohnt wird. Und je vier dieser Zeichen können an Statuen der Göttin Hylia gegen einen weiteren Herz- oder Ausdauercontainer eingetauscht werden.

Warum? Was hat die Göttin mit den Mumien zu tun? Weshalb wurden vor zehntausend Jahren riesige unterirdische Rätsel gebaut? Das wird im Spiel nicht geklärt. Aber wer nachrechnet wird merken, dass einige Schreine gelöst werden müssen, um Link substantiell zu stärken. Ich war am Ende bei 70 Schreinen angelangt. Und da sich die Schreine über die gesamte Karte verteilen, kommt man gar nicht umher, alle Gebiete von Hyrule zu erkunden.

Und beim Erkunden findet man so viel mehr als nur die Schreine, die auch als Schnellreisepunkte dienen. Z.B. die Krogs, kleine Blattwesen, die sich unter Steinen und hinter kleinen Rätseln verstecken, und deren Belohnung wiederum in größere Taschen für z.B. Waffen eingetauscht werden können.

Wo andere Spiele also über Storyquests verlangen, dass ein Spieler bestimmte Anforderungen erfüllt, macht BotW dies sehr indirekt und erwartet gleichzeitig, dass die Spielewelt mit Neugierde erkundet wird. Zu den meisten Seltsamkeiten findet sich irgendwo ein NPC, der etwas dazu zu sagen hat. Leider sind manche Beschreibungen (z.B. von Türmen) sehr mehrdeutig und die Questmarker zeigen auf den Auftraggeber, aber nicht auf das Ziel.

Ansonsten ist Hyrule überaschend zugänglich. Mit der zum Klima passenden Kleidung kann Link durch seine Kletterfähigkeit jeden Berg erklimmen und muss sich deshalb theoretisch nicht an die vorgegebenen Wege durch Hyrule halten. Praktisch entdeckt man die Ställe und Hinweise auf Schreine hauptsächlich an den Wegen, so dass es sinnvoll ist, diese alle einmal abzulaufen. Oder zu reiten - allerdings empfand ich das Fangen und Einreiten wenig motivierend und war deshalb fast ausschließlich per pedes unterwegs.

Und wie bei den meisten Open-World-Spielen nagt dieses alles-erlaufen-können doch merklich an der Glaubwürdigkeit der Spielewelt. Innerhalb weniger Laufminuten wechseln sich nicht nur extreme Klimazonen ab (inkl. Phänomenen wie dass lokal im Sandsturm die Sicht sehr schlecht ist, von weit weg das Gebiet aber per Fernglas eingesehen werden kann), sondern auch sehr unterschiedliche Völker und Dörfer, die die (respawnenden) Monster außerhalb der Tore seltsamerweise kaum tangieren.

Optisch schön ist das Wetter in BotW umgesetzt. Im Regen leidet Links Kletterfähigkeit und bei Gewittern ziehen metallene Waffen Blitze an, aber nur so lange man sie offen am Körper trägt. Sobald sie in der Tasche verschwinden, ist das kein Problem mehr. Allerdings erfordern einige Quests schönes Wetter (die blaue Flamme), und mindestens einmal musste ich minutenlang auf besseres Wetter warten.

Das sind dann die Momente, wo die Spielelemente von BotW nicht so gut ineinandergreifen, wie sie könnten. So toll Link klettern kann, in den Schreinen funktioniert dies nicht - denn dann wären die Rätsel meist einfacher zu lösen. Beim Kochen können nicht nur Gerichte entstehen, sondern auch Tränke, aber wieso es zusätzlich zu den Kochschalen auch noch die Möglichkeit gibt, Zutaten am Feuern zu rösten, hat sich mir nicht erschlossen.

Verbesserungswürdig fand ich auch das User Interface. Die ungenauen Analogssticks fallen eigentlich nur bei den Bosskämpfen negativ auf. Richtig gefreut hätte ich mich aber über mehr Einblick in die Haltbarkeit der Waffen. Erst kurz vor dem Zerbrechen gibt es einen Hinweis darauf. D.h. man schleppt zwar ein Arsenal an Waffen mit sich herum, aber ob es für die anstehenden Aufgaben reicht, kann man nur abschätzen. Zusammen mit den steigenden Preisen für die Erweiterung der Taschen verwaltet man als Spieler eigentlich ständig nur den Mangel und steht gefühlt alle 10min vor der Entscheidung, eine vielleicht bald kaputt gehende Waffe gegen eine schwächere, aber möglicherweise längere haltende Alternative einzutauschen. Wie habe ich mir eine Schmiedeoption gewünscht, um die Haltbarkeit meiner Lieblingswaffen zu verlängern.

Bis knapp vor dem Ende des Spiels war ich auch immer knapp bei Kasse, da die für die verschiedenen Klimazonen wichtige Kleidung ebenso wie deren Aufrüstung Geld kostet und es immer ungewiss bleibt, ob die gefundenen Zutaten im Inventar für Quests benötigt werden oder verkauft werden können - wobei nur weniges wirklich gute Preise erzielt. Dadurch wird auch der eigentlich mächtige Bogen abgewertet, da Pfeile teuer im Einkauf und so ständig Mangelware sind.

Fazit: In vielen Medien wurde BotW als das beste Spiel für die Switch bezeichnet. Außer bei der Grafik kann ich diese Einschätzung nicht nachvollziehen. Ja, es bietet ein tolles Spielerlebnis und hat einen großen Umfang, aber gleichzeitig gibt es viele Ecken und Kanten, die mich frustrierten. Das aufs Erkunden bauende Spielprinzip wird über alles gestellt, und dafür sogar eine motivierenden Story geopfert.