---
title: "Free Rainer - Dein Fernseher lügt"
date: "2007-11-26T23:18:58"
categories: [gesehen]
---

*Deutschland (2007)
Regie: Hans Weingartner
Darsteller: Moritz Bleibtreu (Rainer), Elsa Sophie Gambard (Pegah), Milan Peschel (Phillip), Simone Hanselmann (Anna), Gregor Bloéb (Maiwald), Urs Conradi (Frau Arnim), Thomas Jahn (Bernd), Robert Viktor Minich (Harry), Ralf Knicker (Sebastian), Andreas Brandt (Karl-Heinz), Irshad Panjatan (Gopal) und andere Mediengestalter
[Offizielle Homepage](http://www.freerainer.de/)*

Drei Jahre nach [Die fetten Jahre sind vorbei](/blog/2004/12/20/die-fetten-jahre-sind-vorbei/) schickt Regisseur Hans Weingartner nun einen neuen Film in die Kinos. Wieder geht es um Gesellschaftskritik, doch während der Vorgänger von dem intelligenten Umgang mit der Thematik und der Diskussion darüber lebte, ist Free Rainer zu einer plakativen Utopie über die Macht des Mediums Fernsehen geworden.

Der TV-Produzent Rainer wird von der Schwimmerin Pegah in einen Unfall verwickelt, deren Großvater sich aufgrund eines Fernsehberichtes das Leben nahm. Dadurch ändert sich Rainers Sicht auf die Qualität der von ihm produzierten TV-Sendungen und er versucht, mit anspruchsvollen Sendungen auf Quotenjagd zu gehen. Als dies scheitert, sieht er das Problem in der Ermittlung der Einschaltquoten und macht sich mit Pegah und dem Einzelgänger Phillip daran, diese Wurzel des Übels anzugehen. Sie entwickeln einen Plan, um die Quoten zu manipulieren...

So weit der interessante Ansatz. Der Film ist auch solange gut, wie Rainer und seine Freunde versuchen, zuerst die Lücke im System zu finden und danach diese selber erschaffen. Doch als sie ihr Ziel schließlich erreichen, verliert sich Regisseur Weingartner zu lange in seiner Utopie der intellektuellen Gesellschaft - diese wird ironischerweise wieder über das Medium Fernsehen selber erzählt. Zuletzt schiebt er noch ein vorhersehbares Ende hinterher und lässt seine Helden wie schon bei den *fetten Jahren* einen neuen Schlag angehen.

Neben den Längen ist aber die Hauptfigur Rainer der große Schwachpunkt des Films. Dessen Charakter ändert sich zu oft und zu schnell, als dass man diese Entwicklung als Zuschauer verstehen oder gar nachvollziehen könnte. Die restlichen Figuren sind ebenfalls entweder Abziehbilder oder schwach gezeichnet - selbst für eine Mediensatire ist dies zu wenig. Wenigstens überzeugen die Schauspieler und die Kulissen, so dass sich zumindest die Stimmung des Films auf den Kinosaal überträgt.

Weiterhin bleibt es Weingartners Stärke, einem Film Ecken und Kanten zu geben. Die Charaktere machen alle Fehler und an einigen Stellen verzichtet man bewusst darauf, sich mit dem Publikum so solidarisieren (z.B. der Unfall des betrunkenen Bernd), auch der Humor und die Referenzen überzeugen. Generell sind die Arbeitslosen, die Rainer rekrutiert, das totale Gegenstück zu denen aus dem ähnlich gelagerten [Muxmäuschenstill](http://www.mux-braucht-dich.de/). Trotz aller Klischees sind sie eben nicht nur käuflich, sondern können trotz aller Sperrigkeit in die Gesellschaft eingebunden werden wenn man nicht gerade versucht, alle über einen Kamm zu scheren.

Seitenhiebe dieser Art machen die Filme von Weingartner so sehenswert. Nur leider krankt *Free Rainer* an dem nicht erreichten Ziel der Mediensatire, so dass Schwachpunkte wie das zu lange Verweilen bei der Utopie und die schwache Charakterzeichnung deutlich auffallen. Doch wem *Die fetten Jahre sind vorbei* gefiel, der wird auch hier trotz fehlender Eindringlichkeit gut unterhalten.
