---
title: "Wahlkampf in Sachsen-Anhalt"
date: "2006-02-26T20:46:39"
categories: [gedacht,gefunden]
---

Bunte Plakate an allen Laternenmasten, die nicht rechtzeitig das Weite suchten, können nur eins bedeuten: Das Land befindet sich im Wahlkampf und dem Bürger soll die Qual der Wahl durch markante Sprüche und geschönte Bilder erleichtert werden!

Die [CDU](http://www.cdulsa.de) als regierende Partei um Ministerpräsident "Opa" Böhmer [wirbt mit Kindern](http://cdulsa.eckpunkt.de/landtagswahl/plakate.php?mark=3) und ihren Erfolgen bei der Bildungsreformen, welche sie durch die PISA-Studie bestätigt sieht. Doch die Schwerpunkte der Reformen (Rückkehr zu 12 Schuljahren, Eignungstests für das Gymnasium) sind entweder noch nicht umgesetzt oder noch zu frisch, um bereits Auswirkungen zu zeigen - aber werben lässt sich damit trotzdem prächtig.

Schließlich muss man dem Gegner von der [SPD](http://www.spd-sachsen-anhalt.de/) etwas entgegensetzen, wenn schon der versprochene wirtschaftliche Aufschwung ausgeblieben ist. [Jens Bullerjahn](http://www.jens-bullerjahn.de/) [bewirbt sich nämlich als Alternative](http://www.spd-sachsen-anhalt.de/index.php?option=com_content&task=view&id=319&Itemid=175) für den bisherigen Ministerpräsidenten und will mit seiner Jugend und einem Zukunftsprogramm punkten; richtige Themenschwerpunkte scheint es nicht zu geben. Dafür [bloggen die Jusos](http://blog.jusos-sachsen-anhalt.de/) kräftig gegen alle anderen Parteien.

Die derzeit mitregierende [FDP](http://www.fdp-sachsen-anhalt.de/) sieht das Land auf einem guten Kurs und will weiteres Wachstum - wahrscheinlich nicht nur bei den Artbeitslosenzahlen. Deshalb [plakatiert](http://www.liberal-waehlen.de/) man gegen die Mehrwertsteuererhöhung der Bundesregierung, die das zarte Pflänzchen Wachstum erdrücken könnte (an dieser Stelle ist sich die schwarz-gelbe Koalition in Magdeburg einig, denn auch Ministerpräsident Böhmer forderte ein "Überdenken"). Weiterhin setzt die FDP auf neue Formen der Bürgernähe wie [Foren](http://forum.fdp-bundesverband.de) und [Chats](http://chat.fdp-lsa.de/).

Die [Linkspartei.PDS](http://www.waehlt.dielinkspartei-lsa.de) geht den Wahlkampf dagegen sehr ruhig und mit einer unauffälligen Website an, schließlich möchte man nicht mit in den Strudel um den [Streit in der WASG](http://www.mz-web.de/servlet/ContentServer?pagename=ksta/page&atype=ksArtikel&aid=1139497447610&openMenu=1013016724285&calledPageId=1013016724285&listid=1018881578312) hineingezogen werden. Die üblichen 20% und die drittstärkste Kraft im Lande sollten erneut ein realistisches Ziel sein.

Davon können [Bündnis 90/Die Grünen](http://www.sachsen-anhalt.gruene-partei.de) nur träumen, denn seit acht Jahren ist man nicht mehr im Landtag vertreten. Trotzdem schickt die Partei erneut Inés Brock als Spitzenkandidatin mit einem fast identischen Wahlprogramm in den Wahlkampf - scheinbar fehlen die Alternativen. Mit der Gründung der [grünen Jugend](http://www.gj-lsa.de/) könnte sich dies aber bis zur nächsten Wahl ändern.

Bleibt zuletzt noch die DVU zu erwähnen. Vor acht Jahren zog sie mit rechten Parolen und fast 13% Stimmenanteil in den Landtag ein, wo schnell deutlich wurde, dass hinter der Partei kein politisches Konzept steckt und sich die Fraktion deshalb nach kurzer Zeit auflöste. Für die anstehende Wahl setzt die Partei wieder auf Populismus und Konfrontation. So versuchte sie, über die Meldeämter der Städte und Kreise an die Adressen der jungen, männlichen Wähler zu kommen, die ihre Hauptzielgruppe darstellen. Nur wenige Meldeämter sahen die Interessen einer Partei für wichtiger als die Privatspähre ihrer Bürger an, aber leider gehörte meine Heimatstadt [Halle](http://www.halle.de) dazu. So bekam ich einen Brief, indem der DVU-Vorsitzende Gerhard Frey mich ansprach mit

> Sie sind mir als als Persönlichkeit bekannt, deren Herz für Deutschland schlägt.

Am meisten ärgerte mich an dieser Aktion, dass die Meldeämter damit der Partei halfen, Geld zu sparen, da sie ihre Zielgruppe sehr genau abfragen durfte. Auch bei der Plakatwerbung muss scheinbar gespart werden, denn diese wird auf den ländlichen Raum konzentriert, wo die DVU ein höheres Wählerpotential hat.

Wenn er aber nicht gerade junge Männer anschreibt, damit diese für ihn Propaganda betreiben, sieht sich Herr Frey auch als [Kämpfer für das Vermächtnis der sozialdemokratischen Patrioten](http://www.mz-web.de/servlet/ContentServer?pagename=ksta/page&atype=ksArtikel&aid=1139497445441&openMenu=987490165154&calledPageId=987490165154&listid=994342720546) und wirbt mit den SPD-Größen August Bebel, Friedrich Ebert, Kurt Schumacher und Willy Brandt. Dass er trotzdem nur die der DVU laut Wahlrecht zustehende Anzahl an Wahlwerbespots bekommen soll, will der Unternehmer dagegen gar nicht verstehen.

Für weitergehende Informationen möchte ich zum Schluss auf zwei interessante Seiten verweisen. Zum einen steht wie gewohnt ein [Wahl-O-Mat](http://www.wahl-o-mat.de/st) der [Bundeszentrale für politische Bildung](http://www.bpb.de) bereit, um dem unschlüssigen Wähler an Hand von Schwerpunkten der Wahlprogramme der fünf größten Parteien eine Empfehlung für die Wahl auszusprechen.

Zum anderen hat sich eine neue Plattform im Netz etabliert, welche es erlaubt, den Kandidaten der einzelnen Wahlkreise Fragen zu stellen. Nicht jeder Politiker auf [Kandidatenwatch](http://www.kandidatenwatch.de/) beantwortet die über ein Formular übermittelten Anfragen, aber ich empfinde die Seite als eine angenehme Art der Kommunikation mit den Vertretern im Landtag und befürworte die Nutzung des Internets für mehr Demokratie und Bürgernähe.
