---
title: "Den Göttern dämmert's"
date: "2008-12-05T22:29:28"
categories: [gedacht,gespielt]
---

Zwei Wochen und drei Patches nach dem Erscheinen des Addons [Götterdämmerung](/blog/2008/04/16/kaffeesatzlesen-gothic-iii-bekommt-ein-addon/) für Gothic 3 haben sich [die Wogen über dessen Qualität](http://www.gamestar.de/interviews/1951513/gothic_3_goetterdaemmerung.html) noch nicht geglättet. Also will ich nach ein paar Stunden, die ich bisher in das Spiel investiert habe, auch meinen Senf dazu abgeben.

Die meisten Kritikpunkte kann ich auf jeden Fall bestätigen. Die Performance ist trotz der eigentlich ausgereiften Engine wirklich unterirdisch; ständig friert das Spiel ein und Laden und Speichern dauert jedes Mal eine Minute. Das Intro ist von ganz mieser Qualität und bei vielen NPCs trifft man in Dialogen auf leere oder nicht übersetzte Textboxen; sogar bei einer Quest der Haupt-Storyline musste ich leere Blöcke wegklicken, um weiterzukommen. Diese Nachlässigkeiten bei der Übersetzung setzt sich bei Objekten fort, von denen einige noch ihre technischen oder englischen Bezeichner tragen. Und im Questlog ragen die Namen der Aufträge über den sichtbaren Bereich hinaus; teilweise kann man nicht bis zu den wichtigen Teilen der erinnerten Dialoge scrollen.

Der Schwierigkeitsgrad ist durch den hohen Ausdauer-Verbrauch beim Kämpfen, das anfänglich sehr schnelle Leveln und die schwache KI sehr unausgewogen. Kämpft man in einer Arena und besiegt den Gegner, dann bleibt dieser an Ort und Stelle im Weg stehen. Steht nun der nächste Kampf an, erwischt man im Eifer des Gefechts schnell einmal den alten Gegner und hat nun auch noch diesen gegen sich. Zudem ist die Wegfindung schlecht wie eh und je; ein weggeführter NPC schaffte es zum Beispiel einfach nicht über eine Brücke und muss durch das Flussbett eskortiert werden.

Außerhalb der Siedlungen erscheint das im Vergleich zu *Gothic 3* geschrumpfte Myrtana noch lebloser als im Hauptspiel. Sämtliche Hütten sind verwaist, die brennenden Feuer an Lagerplätzen wirken so noch deplatzierter. Trelis wurde als Zentrum der Orks massiv ausgebaut, doch irgendwie integrieren sich die neuen Gebäude nicht so gut in die Landschaft. Dabei soll extra noch ein Entwickler des vierten Teils am typischen Gothic-Gefühl gearbeitet haben. Doch die Arroganz des Namenlosen Helden gegenüber den anderen Charakteren wirkt irritierend. Er beschimpft seine Auftraggeber und beschwert sich über jeden Job, den er übernehmen will. Da fällt mir die Identifikation schwer - ich will nämlich jede noch so kleine Quest erfüllen, dafür habe ich das Spiel schließlich gekauft.
 
Jowood hat es also geschafft, alle Fehler mit dem Hauptprogramm zu wiederholen. Allein der Gedanke, ein bugverseuchtes Spiel zu veröffentlichen in der Hoffnung, alle Bugs am Tag des Release mit einem Patch zu beheben, gehört bestraft. Die [indische Auftragsarbeit](/blog/2008/08/24/outsourcing-jetzt-auch-bei-pc-spielen/) hat somit bis auf die Kostensenkung keine positiven Auswirkungen gehabt; vielmehr sind dadurch Mehraufwände nach der Veröffentlichung entstanden und das letzte Vertrauen bei den Fans wurde verspielt. Eine gute Seite hat das Spiel aber. Es besitzt keinen Kopierschutz; die DVD muss nach der Installation nicht mehr im Laufwerk liegen. Andere Spiele sind nicht so kundenfreundlich - [gut, dass ich GTA IV bereits für die PS3 gekauft habe](http://www.pcgameshardware.de/aid,669159/News/GTA_4_PC_Schlagende_Argumente_warum_sie_das_Spiel_nicht_zum_Start_kaufen_sollten/).
