---
title: "Die Welt zu Gast in unsicheren Stadien?"
date: "2006-01-10T12:32:37"
categories: [gedacht,gefunden]
---

Mit so viel medialen Echo hat die [Stiftung Warentest](http://www.stiftung-warentest.de) bestimmt nicht gerechnet, als sie in einer Pressemitteilung das schlecht ausgefallene [Ergebnis](http://www.stiftung-warentest.de/online/freizeit_reise/test/1335490/1335490/1336832.html) aus den Tests der deutschen WM-Stadien ankündigte. Sofort sprang die gut geölte Maschinerie aus Organisationskomitee und Stadionbetreiber an, welche ihre wirtschaftlichen Interessen zu schützen versuchten, indem sie die Glaubwürdigkeit der Stiftung Warentest zu untergraben begannen anstatt sich mit der Studie genauer auseinander zu setzen. Den Vogel schoss dabei wieder einmal OK-Chef Franz Beckenbauer in einem Interview mit der [Zeitung mit den vier großen Buchstaben](http://www.bild.t-online.de/BTO/sport/aktuell/2006/01/10/beckenbauer-wm-noergler/beckenbauer-wm-noergler.html) ab.

Hier holt er zu einem Rundumschlag aus gegen das "Heer der Besserwisser und Wichtigtuer, die sich über die WM profilieren wollen". Der Stiftung Warentest, seit Jahrzehnten eine Institution im Verbraucherjournalismus, unterstellt er niedere Interessen und hält die Stiftung für nicht wichtig. Geichzeitig zeigt er deutlich, dass er die Fans nicht versteht:

> Diese Verbraucherschützer stehlen uns nur die Zeit. Wer schützt uns eigentlich vor denen? Sie maßen sich an, im Namen der Fans zu reden. Was ist passiert? Gerade mal ein paar Leute haben ihre Bestellung für die Optionstickets zurückgezogen.

Es kommt ihm gar nicht in den Sinn, dass die WM nicht für ihn, sondern für die Fans veranstaltet wird, die durch die Bedingungen der Ticketvergabe das komplette wirtschaftliche Risiko tragen sollen und keine Chance haben, auf anderem Wege zu Tickets zu kommen. Natürlich zieht kaum jemand seine Bestellung für die Optionstickets zurück, da ja immer noch die Möglichkeit besteht, welche zugeteilt zu bekommen. Der Vergleich der Verbraucherschützer ist in diesem Sinne nicht einmal ein Tropfen auf den heißen Stein.

Ebenfalls Unverständnis zeigt Kaiser Franz dafür, dass die Vergabe von vielen Karten an die Fifa-Sponsoren kritisiert wird:

> Ja, aber die Unternehmen wie z.B. Coca Cola reichen ihre Kontingente an die Fußball-Anhänger weiter. Nicht nur, wer sich Schwarz-Rot-Gold anmalt, ist ein Fan.

Einen Absatz vorher lobt er die Ticketvergabe wegen der gerechten Zuteilung per Losverfahren, und dann ist auf einmal die willkürliche Weiterreichung von großen Kontingenten ebenfalls in Ordnung.

Auf jeden Fall zeugt es nicht gerade von Besorgnis über die Sicherheit der Fans, wie auf die Meldung der Stiftung Warentest reagiert wird. Sicherlich kann man das Vorgehen der Stiftung Warentest besonders bei der Veröffentlichung der Ergebnisse kritisieren. Jedoch ist diese ihren Kunden, den Verbrauchern, verpflichtet und nicht den Stadionbetreibern und dem WM-OK. Der oben verlinkte Artikel zeigt außerdem, dass zum Beispiel im Fall der Flucht über das Spielfeld die Sicherheit vor dem Zuschauer über die Sicherheit der Zuschauer gestellt wurde. Aber das sind die Fans ja von der WM gewohnt...
