---
title: "Meine liebsten Filme 2011"
date: "2012-01-16T21:42:40"
categories: [gedacht,gesehen,gefunden]
---

Was [Quentin Tarantino kann](http://www.tarantino.info/2012/01/14/exclusive-quentin-tarantinos-favorite-films-of-2011-more/), kann ich ebenfalls - eine Bestenliste der gesehenen Filme 2011 aufstellen. Ich war zwar [nur 19mal im Kino](/blog/2011/12/31/mein-jahr-2011-in-zahlen/) und muss mit dem Zeitversatz der deutschen Veröffentlichungen leben, habe aber genug gesehen um eine eigene Top12 aufzustellen (mit nur einer Überschneidung zu Tarantino). Und hier ist sie:

<ol>
	<li>[Scott Pilgrim gegen den Rest der Welt](/blog/2011/03/22/scott-pilgrim-vs-the-world/)</li>
	<li>Sherlock (erste Teil der [BBC-Mini-Serie](/blog/2011/08/08/sherlock/))</li>
	<li>[Midnight in Paris](/blog/2011/09/16/midnight-in-paris/)</li>
	<li>The Social Network</li>
	<li>[Four Lions](/blog/2011/05/22/four-lions/)</li>
	<li>[True Grit](/blog/2011/04/24/movies-on-a-plane/)</li>
	<li>[Biutiful](/blog/2011/06/08/biutiful/)</li>
	<li>[The Guard](/blog/2011/02/15/the-guard/)</li>
	<li>Gainsbourg - Der Mann, der die Frauen liebte</li>
	<li>[The Fighter](/blog/2011/04/24/movies-on-a-plane/)</li>
	<li>The King's Speech - Die Rede des Königs</li>
	<li>[Black Swan](/blog/2011/01/30/black-swan/)</li>
</ol>

Und wenn Herr Tarantino Sonder-Awards vergibt, dann will ich nicht hintenanstehen und vergebe deshalb den Preis für den besten Soundtrack an die Chemical Brothers für ihre beeindruckende musikalische Untermalung von *Wer ist Hanna?*.

Zum Schluss muss ich unbedingt noch [Game of Thrones](http://www.hbo.com/game-of-thrones) als beste TV-Serie des Jahres nennen, die bei der diesjährigen Verleihung der [Golden Globes](http://www.goldenglobes.org/blog/2012/01/peter-dinklage-wins-a-golden-globe/) mit nur einem Award für den besten Nebendarsteller (Peter Dinklage) für meinen Geschmack etwas zu kurz gekommen ist.
