---
title: "Owen Meany"
date: "2009-04-20T22:20:36"
categories: [gelesen]
---

*von John Irving,
erschienen im Diogenes Verlag, ISBN 3-257-22491-5, 12,90€*

Ich habe selten für ein Buch von John Irving so lange zum Lesen benötigt. Und ich kann auch nicht genau mit dem Finger auf den Grund für diese Unlust zeigen, denn das Buch hat doch so viele der typischen Irving-Elemente: Eine lügende Mutter, inzestuöse Beziehungen, Internatsschulen in New Hampshire, Auseinandersetzung mit Literatur und dem Schreiben und natürlich die gewohnt skurilen Charaktere, allen voran die titelgebende Nebenrolle *Owen Meany*.

Doch es gibt auch ungewohnt deutliche politische Aussagen im Speziellen über den Vietnamkrieg und die Regierung Reagan, während dessen Amtszeit das Buch entstand. Ein weiterer Schwerpunkt ist die Auseinandersetzung mit der Religion. Irving beschreibt Menschen, die an Wunder glauben, die keine sind, und solche, die die Wunder vor ihrer Nase nicht als solche erkennen wollen. Er beschreibt Menschen, die für sich reklamieren, die Wege Gottes zu kennen, und solche, die ihren Glauben im Zweifel suchen. Fast jede erdenkliche Stufe der Gäubigkeit findet sich in einem Buchcharakter wieder, und am Ende prophezeit der Ich-Erzähler, dass die USA einen Präsidenten bekommen werden, der die Menschen wie eine Religion leiten wird - da ist Barack Obama ja schon ziemlich nah dran.

Was vielleicht fehlt ist ein durchgängiger Spannungsbogen, ein roter Faden hätte der ersten Hälfte des Buches gut getan. So darf der Leser die Charaktere beim Aufwachsen beobachten und Anspielungen ohne Ende über sich ergehen lassen, aber ein größerer Entwurf wird erst gegen Ende erkennbar. Bis dahin plätschert die Handlung scheinbar ziellos dahin, und ich kam nie richtig in das Buch hinein bis es schlussendlich alle losen Fäden zu einem Ganzen verknotet.

Liegt es nun an der Thematik, am Storyaufbau oder meinem Lesezyklus - *Owen Meany* zu lesen war eine schwere Geburt für mich und leider kein großes Vergnügen wie die anderen Bücher des Autoren. Als nächstes werde ich mich am [Wassertrinker](http://de.wikipedia.org/wiki/Die_wilde_Geschichte_vom_Wassertrinker) versuchen, dessen Inhalt mich deutlich mehr anspricht.
