---
title: "Mr. Monk zurück aus der Sommerpause"
date: "2005-09-28T13:11:54"
categories: [gesehen]
---

Nach "Stromberg" (Pro7, Sonntags nach dem Abendfilm) kommen seit gestern auch neue Folgen von meiner momentanen Lieblings-Krimi-Serie ["MONK"](http://www.usanetwork.com/series/monk/) (RTL, Dienstags, 22:15h). Nachdem RTL die zur amerikanischen Erstausstrahlung recht zeitnah gesendeten Folgen der dritten Staffel im Frühsommer unterbrach - und mir damit die Möglichkeit gab, ein paar der noch nicht gesehenen ersten Folgen nachzuholen - folgen nun die restlichen Episoden ohne Sharona. Deren Schauspielerin Bitty Schram verlangte angeblich zu viel Geld und so wurde ihre Figur von den Produzenten aus der Serie geschrieben. Die Assistentenrolle übernimmt Traylor Howard, die mit einem toten Mann und einer 11-jährigen Tochter einen ähnlichen Background wie Sharona aufweist, wodurch sich sicherlich die meisten der schon geschriebenen und noch nicht abgedrehten Folgen recyclen lassen sollten.

Die gestrige Folge "Mr. Monk und Natalie fischen im Dunkeln" musste nun als Einführung des neuen Charakters dienen und gleichzeitig Sharonas Ausscheiden erklären. Selbst wenn sie glücklicherweise nicht sterben musste, haben die Autoren doch nicht sehr viel Kreativität bewiesen. Die Rückkehr zu ihrem Mann war zwar schon vorbereitet, aber ein letzter Auftritt hätte doch deutlich besser gepasst als diese Aufarbeitung drei Monate danach. Wenigstens wurde die Übernahme des Assistenten-Jobs durch Natalie gut in die Mordgeschichte integriert, wenn auch deren Auflösung sehr simpel war. Generell wirkte alles etwas konstruiert, damit die Verhältnisse am Ende auch geklärt sind und die Serie ihren regulären Fortgang nehmen kann.

Zum Glück rettete Monk selber die Folge, dessen schrullige Neurosen ich mir stundenlang ansehen könnte. Wenn jetzt noch die Fälle wieder besser werden, ist der Dienstag abend bis Weihnachten gesichert!
