---
title: "Einmal Stollen ohne alles, bitte!"
date: "2008-12-14T17:21:01"
categories: [gedacht,gefunden]
---

Ich muss zugeben, dass ich beim Essen sehr <del datetime="2008-12-02T20:31:56+00:00">mäklig</del> wählerisch bin. Ich esse nichts mit dem Namen Leber darin (Leberwurst, Leberkäse, Leber selber), keine Pilze, keinen Rosenkohl, keinen Grünkohl, keine Kapern, keine Oliven und auch keine Rosinen. Und das ist ein Problem zu Weihnachten: Ein Hauptbestandteil von Stollen sind nun einmal Rosinen, so dass ich entweder doppelt so viel Zeit mit dem Rauspulen als mit dem Essen verbringe oder komplett auf dieses Weihnachtsgebäck verzichte.

Nun hat die Firma Bahlsen mich als Zielgruppe entdeckt und verkauft einen Stollen ohne Rosinen, Zitronat und Orangeat, dafür aber mit einer Mandelfüllung. Das Ganze hat mit einem klassischen Stollen außer der Zubereitung und dem Puderzucker nicht mehr viel zu tun, schmeckt aber trotzdem ganz lecker. Und wer etwas gegen Mandeln hat, für den bietet die selbe Firma noch einen Walnussstollen an. Das wird ein leckeres Weihnachten dieses Jahr!
