---
title: "Portugal - Das Essen"
date: "2009-11-29T23:12:52"
categories: [gewesen]
---

Portugal mit seinen weiten Atlantikküsten hat vor allem eine Ressource zur Verfügung: Fisch (*peixe*). Da man privat so viel fischen darf, wie man will, tun dies die Portugiesen auch ausgiebig. Oft sieht man Angelleinen, die von Klippen dreißig Meter weit in den Atlantik geworfen wurden, und ich bin einem Taucher begegnet, der mit Harpunen und sicherlich 10kg Fisch aus dem Wasser stieg.

Dementsprechend steht frischer Fisch weit oben auf den Speisekarten. Dieser wird nur gegrillt und mit wenigen Beilagen - meist Kartoffeln - serviert, und man sucht sich den eigenen Fisch vorher an einer eisgekühlten Theke aus. Sehr beliebt sind auch gegrillte Spieße, wo der Fisch mit weiteren Meeresfrüchten wie Garnelen kombiniert wird. Wo es keine Fischtheke gibt, sollte man sich den Fisch vor der Zubereitung zeigen und wiegen lassen. Dies ist üblich in Portugal und so kann man den Preis abschätzen (Fischpreise sind meist pro kg angegeben) und beurteilen, ob man wirklich frisches Meeresgetier vorgesetzt bekommt oder an einen Touristenfänger geraten ist.

Nationalfisch ist dabei der *Bacalhau* (Stockfisch, eine Art Kabeljau); ebenfalls beliebt ist der Tintenfisch, von dem ich mindestens drei verschiedene [Arten](http://de.wikipedia.org/wiki/Tintenfisch) ausgemacht habe: *Lula*, *Choco* ([Sepien](http://de.wikipedia.org/wiki/Sepien) mit Tinte) und *Polvo* ([Kraken](http://de.wikipedia.org/wiki/Kraken)). Eine lange Tradition hat zudem die (gegrillte) Sardine, die sogar mit einem Sardinenfestival in *Portimão* gefeiert wird.

Die Auswahl an Atlantikfischen ist deutlich größer, als ich hier kurz anreißen kann oder gar probieren konnte. Einen Tipp muss ich aber noch loswerden: Über die Vulkan- und Blumeninsel [Madeira](http://de.wikipedia.org/wiki/Madeira) hat Portugal Zugang zu Tiefseefischen, und ein besonders schmackhafter, aber ebenso hässlicher Vertreter ist der *peixe espada* ([Degenfisch](http://de.wikipedia.org/wiki/Degenfisch)). Im Gegensatz zu Madeira muss man an der Algarve zwar nach Restaurants suchen, die ihn auf der Speisekarte haben - im Supermarkt habe ich ihn aber an jeder Fischtheke gesehen.

In ebensolcher Vielfalt wie den Fisch findet man auch Meeresfrüchte an der Algarve. Garnelen gibt es in jeder Größe (bis zu [Tigerprawns](http://en.wikipedia.org/wiki/Tiger_prawn)), als Vorspeise, Teil von Spießen oder Hauptgerichten. Muscheln (*amêijoas*) sind genauso beliebt und werden gekocht auf Knoblauch serviert; die lokale Auswahl ist unglaublich groß.

Bevor man sich jedoch an die Hauptgerichte macht, steht immer schon eine Reihe von kleinen Vorspeisen auf dem Tisch. Diese sind nicht etwa im Preis inbegriffen, sondern finden sich am Ende als *couvert* auf der Rechnung. Meist handelt es sich dabei um Weißbrot mit Oliven und Pasteten (z.B. Thunfisch oder Sardinen), oft bekommt man auch einen leckeren Käse (*Queijo*) aus dreierlei Milch (Kuh, Schaf, Ziege) angeboten.

Trotz der Fischlastigkeit der Speisenpalette muss man aber nicht auf Fleisch verzichten. Ob Lamm, Rind oder Schwein - Steaks findet man überall. Ich habe mir das *porco preto* (schwarzes Eichelschwein) zum Probieren ausgesucht und kann es nur weiterempfehlen. Die Spezialität der Algarve ist jedoch *frango piri piri*. Dabei handelt es sich um Hühnchen, das in einer Marinade aus roten Pfefferschoten eingelegt wird und dann - wie sollte es anders sein - gegrillt wird. Trotz der roten Signalfarben der kleinen Schoten ist dieses Gericht aber nicht sehr scharf, wer will kann jedoch mit Piri-Piri-Öl nachwürzen (dieses hat es dafür in sich).

Wer nach einer ausgiebigen Mahlzeit einen Digestif benötigt, sollte einmal den *Medronho* probieren. Dies ist ein aus den Früchten des [Erdbeerbaums](http://de.wikipedia.org/wiki/Westlicher_Erdbeerbaum) desillierter klarer Schnaps, den es nur an der Algarve gibt.

Zu guter Letzt will ich noch eine Gebäckspezialität vorstellen. Die *Pasteis de Nata* sind kleine Blätterteigtörtchen gefüllt mit Pudding, die man am Besten warm genießt. Ich habe beim [Spezialisten in Belém](http://www.pasteisdebelem.pt/) gekostet und war begeistert! 
