---
title: "Unseen Academicals"
date: "2010-07-11T16:03:10"
categories: [gelesen]
---

*von Terry Pratchett,
veröffentlicht von Doubleday, ISBN 978-0-385-60934-0, 18.99£*

Passend zur Fußball-WM [habe ich es endlich geschafft](/blog/2010/05/02/terry-pratchett-manhattan-eine-glucklose-verbindung/), Terry Pratchetts letzten Scheibenweltroman zu lesen, der sich um das Thema Fußball dreht. Oder um es mit den Worten des Autoren zu sagen:

> [...] the important thing about football [...] is that it is not just about football.

Um dieses Statement zu untermalen widmet sich Pratchett nicht nur der Geschichte der Sportart und der verwirrend-schwierigen Regelkunde, sondern auch ihrer Stellung in der Gesellschaft: Fans, Hooliganismus, Stadionreporter, Funktionäre, das wirtschaftliche Potential und damit auch die Macht, die man erhält wenn man Einfluss auf die Sportart hat - alles dies sind Themen, die in die Scheibenwelt verpflanzt immer wieder einen amüsanten Seitenblick auf die Mechanismen des Fußballs erlauben, die wir durch die Gewöhnung einfach akzeptiert haben und nur noch selten hinterfragen.

Als wären dies nicht Themen genug, hat *Unseen Academicals* noch eine Nebenhandlung um ein Model für Zwergenmode spendiert bekommen, inklusive einem kometenhaften Aufstieg und der damit verbundenen medialen Aufmerksamkeit. Leider versandet dieser Handlungsstrang trotz Potential etwas unmotiviert, ebenso wie die kurzen Auftritte von meinem Lieblingscharakter Rincewind. Dazu werden mit den Goblins/Orcs weitere klassische Fantasyrassen in der Scheibenwelt eingeführt, von denen wir in zukünftigen Romanen vielleicht noch hören werden. Ich kann nämlich nicht glauben, dass Pratchett der komplexen Geschichte seiner Welt nur für ein gewohnt moralisches Ende ein weiteres Puzzlestück hinzufügt - oder hat er sich mit dem Frieden zwischen Trollen und Zwergen etwa in eine Sackgasse geschrieben?

Durch die Involvierung von so vielen Figuren in die Geschichte (u.a. der gesamte Universitätsstab), unter denen sich kein klassischer Hauptcharakter befindet, liegt der Fokus ganz klar auf dem Fußballspiel, und das hat dem Buch ähnlich wie bei *Moving Pictures* nicht geschadet. Somit ist *Unseen Academicals* der beste Scheibenweltroman seit langem - vielleicht kann sich Terry Pratchett trotz seiner Alzheimererkrankung wieder zu alten Leistungen aufschwingen.
