---
title: "KILL BILL Vol. I"
date: "2003-10-23T00:00:21"
categories: [gesehen]
---

*USA (2003)
Regie: Quentin Tarantino
Darsteller: Uma Thurman (Die Braut / Black Mamba), Lucy Liu (O-Ren Ishi / Cottonmouth), Vivica A. Fox (Vernita Green / Cobra), Daryl Hannah (Elle Driver / California Mountain Snake), Michael Madsen (Budd / Sidewinder), David Carradine (Bill), Julie Dreyfus (Sofie Fatale), Sonny Chiba (Hattori Hanzo), Chiaki Kuriyama (Go Go Yubari) und andere Menschen mit fehlenden Gliedmaßen*
[Offizielle Homepage](http://www.killbill-derfilm.de/)

Die Braut, eine Elitekämpferin aus einer geheimen Kampfgruppe, wird auf ihrer Hochzeit von ihren eigenen Mitstreitern und Bill, dem Vater ihres noch ungeborenen Kindes, fast ermordet. Nach 4 Jahren wacht sie aus dem durch einen Kopfschuss verursachten Koma jedoch wieder auf und ist nur noch von einer Idee besessen: Sie will Rache nehmen an den Gefährten, die sie so einfach verrieten und lässt sich eigens für diesen Zweck ein neues Samurai-Schwert von Meister Hattori Hanzo anfertigen...

Der König des Trash ist zurück. Lange hat es gedauert, ehe Quentin Tarantino nach "Jackie Brown" wieder bei einem Film Regie führte, doch jetzt ist er zurück und zeigt allen Nachahmern der letzten Jahre, wie man wirklichen Trash produziert.

Dies fängt gleich nach der brutalen Einführung mit dem Kopfschuss an: Nicht nur dass der Streifen voller Selbstironie als der vierte Film von Q.T. überschrieben wird, nein gleich danach folgt der Leitspruch für den Rest der Handlung: "Rache ist eine Speise, die man am besten kalt serviert". Doch ein Tarantino zitiert nicht etwa eine alte Weisheit, sondern ein klingonisches Sprichwort, also einen Teil der Fernsehserie StarTrek. Und so geht es dann den Rest des Films weiter. Jede Einstellung ist ein Verweis auf einen anderen Film oder eine Fernsehserie, wobei nicht nur die guten Produktionen ihrer Zunft zitiert werden.

So ist das Ende des ersten Teils ein klassischer Soap-Opera-Cliffhanger, zwischendurch darf einmal ein Kommissar in Dallas-Optik im Fall der toten Hochzeitsgesellschaft ermitteln und der Kampf gegen sicherlich Hunderte von schwarzen japanischen Bodyguards ist eine eindeutige Ansage an die Matrix-Macher: Auch ohne große Computertechnik sind solche Schlachten möglich. Und weil zu den vielen Kämpfen auch viel Blut passt, werden dem Gegner meist ganze Gliedmaßen abgeschlagen, woraus sich dann wie in den Monty-Python-Filmen in übertrieben starken Strahlen viele Liter Blut ergießen.

Neben den erwähnten Zitaten bedeutet Trash aber auch ein schlechtes Drehbuch. Hier punktet Tarantino mit solch abstrusen Ideen wie dem seinen Schwur brechenden Samurai-Schwert-Meister, der Vergewaltigung von Koma-Patientinnen oder dem ständigen Piepsen, falls einmal der Name der Braut genannt wird. Zu genau sollte man der Handlung deshalb auch nicht folgen, denn viele Szenen sind einfach nur auf Optik und Coolness getrimmt. So fährt die Braut in Japan mit einem total in Gelb gehaltenen Outfit auf einem komplett gelben Motorrad durch die Gegend oder kämpft in einer Disko vor blau strahlenden Hintergrundlicht. Auch verliert der Film schon einmal mitten in der Einstellung die Farbe, die dann ganz spontan in einer anderen Szene wieder zurückkehrt. Während des finalen Kampfes scheint dann plötzlich ein Brunnenspiel viel wichtiger zu sein als der Fight und bei einem Schnitt auf eine andere Perspektive ist auf einmal die Hintergrundmusik wie weggeblasen - Tarantino spielt den ganzen Film über mit künstlichen Fehlern und versucht so mit allen zur Verfügung stehenden Mitteln den Eindruck einer Billig-Produktion zu erzeugen - Trash as Trash can!

Im Gegensatz zu seinen bisherigen Filmen jedoch treten diesmal auch die Dialoge und die Verschachtelung der einzelnen Szenen eher in den Hintergrund. Während bei "Pulp Fiction" die Reihenfolge und der Zusammenschnitt der einzelnen Szenen noch einem globalen Muster folgte, ist bei "KILL BILL" das Ganze nur noch Selbstzitat. Bis auf die Überbrückung der 13 Stunden dauernden Konzentrationsübung mit den Zehen (!) mit der Erzählung über die Jugend von O-Ren Ishi und die ständigen Rückblenden auf den Überfall der Hochzeit könnten die Szenen auch chronologisch in dieser Reihenfolge ablaufen; vor allem da die Braut ihr Schwert bei Vernita Green gar nicht benutzt. Und die wenigen Wortwechsel zwischen den vielen Kämpfen sind so klischeelastig ausgelegt, dass man darauf auch noch hätte verzichten können.

Generell ist der Film eine Hommage an die asiatischen Kampfkunstfilme der 70er Jahre. So wird der Schwerpunkt eindeutig auf die der Samurai-Ehre (und der Schwerkraft!) folgenden Duelle gelegt und auch der eingeschobene Anime folgt diesem Motto. Doch darunter leidet leider auch der Film. Zu viel Kampf steht zu wenig Handlung gegenüber (da wirkt sich die Zweiteilung des Filmes als negativ aus), und nicht in jeder Szene kann Tarantino den nötigen Witz dazugeben um den Zuschauer bei Laune zu halten, so dass der Film nur ganz knapp dem Absturz in das Mittelmaß entgeht. Auch die Schauspieler passen sich diesem Schema an und versuchen erst gar nicht, den Figuren Tiefgang zu verleihen; Uma Thurman lässt sich sogar als dummes Blondchen hinstellen.

Fazit: KILL BILL muss man als das sehen, was er ist: Trash in Reinform. Wer nicht in der Lage ist darüber hinweg zu sehen, dass dieser schon sehr brutale Film vom Spaß an Zitaten und dem Spiel mit dem Mittelmaß lebt, wird auch keine Freude daran haben. 
