---
title: "Das Waisenhaus"
date: "2009-04-03T23:55:40"
categories: [gesehen]
---

Diese Woche war die Blu-Ray von *Das Waisenhaus* im Amazon-Osternest günstig zu haben. Da ich den Film schon immer sehen wollte, habe ich nicht lange gefackelt und bestellt.

Gruselfilme im Stil von [The Others](/blog/2002/02/20/the-others/) schaue ich mir aufgrund ihrer Atmosphäre sehr gerne an. Dann wird sämtliches Licht ausgeschaltet, die Anlage aufgedreht und sich ganz auf den Film eingelassen. Auf diesem Gebiet überzeugt auch *Das Waisenhaus*: Eine die Nerven strapazierende Soundkulisse bildet die Grundlage für diese Momente des Schauerns, bei denen es mir kalt den Rücken herunterläuft. Klar, alles ist sorgsam kalkuliert, aber ich gebe diesem klassischen Horror den Vorzug vor irgendwelchen Monster- oder Splatterfilmen.

Inhaltlich bietet der Film anfangs Standardkost: Die Toten wollen nicht ruhen, ein tragisches Ereignis in der Vergangenheit will aufgedeckt werden, und Hauptdarstellerin Laura muss all dies herausfinden um am Schluss zu erfahren, was mit ihrem verschwundenen Sohn passiert ist. Allerdings ist dies die offensichtliche Lesart des Filmes, wenn man ihn nur in den Grenzen seines Genre wahrnimmt.

Interessant sind die vielen Aspekte, die sich um das Drama des Verlustes ihres Sohnes drehen. Da wird eine Selbsthilfegruppe gezeigt, in der Eltern über ihr gemeinsames Trauma des verlorenen Kindes reden und eine Teilnehmerin darauf hinweist, dass es zwar schwer ist, aber man irgendwann loslassen und das Geschehene akzeptieren muss. Da wird die Mutter des entstellten Kindes gezeigt, die selbst dreißig Jahre nach dessen Tod noch einen Kinderwagen mit einer dem Sohn nachempfundenen Puppe spazierenfährt, und man erfährt, zu was für Reaktionen sie fähig war. Und dann ist da Laura, die vermutlich die ganze Zeit weiß oder zumindest vermutet, was wirklich passiert ist und nun zwischen diesen beiden Möglichkeiten pendelt.

Der Film versucht zum Glück gar nicht erst, auf ein überraschendes Ende hinzuarbeiten. Der wahre Ablauf der Geschichte um das Waisenhaus wird zuksessive offengelegt, und viel spannender sind ja die Reaktionen der Betroffenen, vor allem von Laura. In den Szenen mit dem Medium zeigt der Regisseur ganz deutlich: An Übersinnliches muss man glauben, und entweder passiert alles was der Zuschauer sieht wirklich oder wir beobachten nur, wie eine Frau an den Folgen eines selbstverschuldeten Unfalls zerbricht.

Trotz der ständig aufgebauten Spannung wird Laura aber nicht ängstlich dargestellt, sondern stark und souverän im Umgang mit der eigentlich grusligen Situation, dass die Geister der Waisen im Haus umhergehen. Man sieht sie jedoch wiederholt mit ihren Tabletten und ihr Mann zieht häufig eine Psychologin zu Rate, so dass die Vermutung entsteht, dass die vom Film präsentierte Perspektive stark von Lauras Verarbeitung ihres Verlustes geprägt ist. Diese Interpretation passt auch zu dem tragischen, aber folgerichtigen Ende und lässt aus dem Gruselfilm plötzlich eine psychologische Studie werden - die sich aber sehr gut mit dem vordergründigen Gruselfilm tarnt.

Inhalt und die technischen Aspekte der Blu-Ray, Bild und Ton, überzeugen, aber der restliche Inhalt enttäuscht. Trailer für *Das Waisenhaus* und sechs weitere Filme aus dem Senator-Angebot sind alles, was man an Extras findet. Da dies meine erste Blu-Ray mit BD-Live ist, war ich nun gespannt, ob wenigstens dieses Feature genutzt wurde. Und siehe da, Extras, die man sonst auf der Disc findet, können über das Internet nachgeladen werden. Es gibt Informationen über die Schauspieler, Audiokommentare, eine Bildergalerie und weitere Trailer. Zudem kann man sich bei einer Online-Community anmelden, über die dann jeder weltweit sehen kann, welche Blu-Ray man gerade schaut. Die in BD-Live verlinkten Specials (Minispiele, Forum, Playlists) sind jedoch erst nach einer Anmeldung überhaupt nutzbar. Wenn man die Website über den Browser ansteuert, infomiert die Seite freimütig darüber, wie dieses überflüssige Angebot angenommen wird: *There are currently 0 Users online*. Und ich vermute, mindestens ebenso viele Besitzer dieser Blu-Ray füllen die Umfrage von Senator zu ihren Sehgewohnheiten aus.

Wenn BD-Live wie bei *Das Waisenhaus* dazu führt, dass man die (wenigen) Extras nicht mehr auf die Disc packt und ansonsten dem Kunden nur persönliche Informationen entlocken will und einige der Zusatzfeatures erst nach einer weiteren Anmeldung offeriert, dann ist diese Funktion von keinerlei Mehrwert für den Käufer. Ich hoffe, dass sich diese Mode nicht fortsetzt und stattdessen ein paar kreativere Nutzungsideen den Weg auf zukünftige Blu-Rays finden.
