---
title: "Dreileben"
date: "2011-10-03T00:40:27"
categories: [gesehen]
---

Am Anfang stand ein Diskurs. Per E-Mail debattierten Dominik Graf, Christoph Hochhäusler und Christian Petzold über den aktuellen Zustand des deutschen Kinos und speziell über die Berliner Schule. Graf warf seinen beiden Kollegen vor, nur noch "Schneewittchenfilme" zu machen, in denen Menschen leblos hinter Glas präsentiert werden. Er kritisierte das erstarrte deutsche Mainstreamkino, das versucht, sich dem amerikanischen anzugleichen und das Leblose offensichtlich nur wählt, weil es sich so gut gestalten lässt: Wachsfiguren, die manchmal verdammt wertvoll drein schauen (siehe [Ausschnitte beim Revolver](http://www.revolver-film.de/Inhalte/Rev16/html/Berliner.htm)).

In Fortführung der Diskussion um diese Vorwürfe entstand schließlich ein gemeinsames Projekt der drei Regisseure; ein Experiment um die Auseinandersetzung in der Praxis fortzuführen. Zusammen wurde ein Thema (entflohener Sexualstraftäter) und ein Ort (das fiktive Dreileben im Thüringer Wald) gefunden und beschlossen, sich zum Stand des deutschen Kinos jeweils im eigenen Stil zu äußern und das Ergebnis für sich sprechen zu lassen. Dieses Dreigestirn von Konzeptfilmen hatte schließlich auf der diesjährigen Berlinale Premiere und wurden vor kurzem von der produzierenden ARD im Fernsehen ausgestrahlt.

Die Filme tragen den Namen *Etwas Besseres als den Tod* (Christian Petzold), *Komm mir nicht nach* (Dominik Graf) und *Eine Minute Dunkel* (Christoph Hochhäusler). Letzterer erfüllt in seiner Darstellung des entflohenen Straftäters und eines ihn suchenden Kommissars noch am ehesten das Konzept eines Krimis, den man aufgrund der Rahmenhandlung erwarten würde. Doch gerade hier finden sich einige der von Graf kritisierten Punkte, denn die beiden Figuren erweckten bei mir kein Interesse an ihnen. Zu wenig konnte ich in sie hineinsehen, obwohl sie ausgiebig bei ihrem jeweiligen Tagesablauf gezeigt werden. Die meisten Szenen sind aber nur für den Handlungsablauf relevant und werden nicht für die notwendige Charakterisierung genutzt. Diese verlässt sich lieber auf das im Kopf des Zuschauers geprägte Bild vom Kommissar und dem gestörten Sexualstraftäter - wenngleich das Ende mit zumindest einer der beiden Charakterblaupausen bricht.

Im Sinne des ursprünglichen Diskurses sind die beiden anderen Filme die interessanteren Anschauungsobjekte. Denn trotz der Tatsache, dass sowohl Petzold als auch Graf ihrer Linie treu geblieben sind, und trotz der verschiedenen eingesetzten Stilmittel, haben sie bei mir eine ähnliche Wirkung erzielt. Diese lässt sich am Besten mit dem Blick durch ein Fenster beschreiben; einen durch nichts getrübten Blick auf die Handlung aus nächster Nähe, der jedoch eine gewisse Distanz bedeutet, einen Abstand bzw eine unsichtbare Wand darstellt.

*Etwas Besseres als den Tod* erzeugte diese Wahrnehmung durch seine vielen Totalen und wiederkehrenden Bildeinstellungen. Der Akteur der Handlung, Johannes, lernt als Zivi in einem Waldkrankenhaus das Zimmermädchen Ana kennen. Es entwickelt sich eine stürmische Liebe, doch bald wird sichtbar, dass die impulsive Ana und der angehende Medizinstudent nicht viel gemeinsam haben. Petzold verdeutlicht diese Entwicklung durch Reduktion auf das Wesentliche, es gibt bei ihm keine Einstellung und keinen Dialog zu viel. Stattdessen wird durch den seltsam bedrohlich wirkenden Soundtrack und die ausgesuchten Kamerablickwinkel Wert auf eine Stimmung gelegt, die dem Zuschauer vermittelt, dass da im Hintergrund etwas wartet - dass hinter dem gegenseitigen Begehren und der frischen Liebe ein baldiger Konflikt und in der Idylle des Thüringer Waldes der entflohene Mörder wartet. Lebendig wirken die Figuren durch die Fokussierung nicht, aber alle Emotionen und Handlungen sind trotzdem gut nachvollziehbar. Die Charakterisierung ist schlüssig, es werden genau die erforderlichen Wesenszüge dargestellt und so kann von Leblosigkeit keine Rede sein.

Ganz anders Dominik Graf. Er führt die Berliner Polizeipsychologin Jo nach Dreileben, um den entflohenen Straftäter zu finden. Sie übernachtet bei ihrer Studienfreundin Vera und ihrem Mann Bruno, einem Autoren, die zusammen ein Haus restaurieren. In nächtlichen Gesprächen finden die beiden Frauen heraus, dass sie einst den selben Mann geliebt haben und plötzlich brechen Wunden auf, die beide für geheilt hielten. Die Rahmenhandlung um den Polizeifall tritt dabei fast komplett in den Hintergrund, der Fokus liegt klar auf den Dialogen und den aus der Charakterkonstellation entstehenden Konflikten. Um seine Figuren mit Leben zu füllen gestattet Graf dem Zuschauer viele intime, private Einblicke, füllt deren Leben mit Details und lässt in Dialogen genausoviel ungesagt wie in Gesten und Blicken angedeutet wird.

So wirken alle Charaktere unglaublich authentisch, aber dies bringt auch Nachteile mit sich. Denn zum Einen bekommen die Figuren so viele Seiten, so viele Facetten verpasst, dass es anfangs schwerfällt, zwischen Gesagtem und Unausgesprochenem das Verhältnis der Figuren zueinander richtig zu verstehen. Zum anderen hatte ich den Eindruck, zu Besuch bei einer Privatparty zu sein und die Gastgeber nicht zu kennen, die sich gerade über ihre privatesten Details auslassen. Da diese sich auf ihre jahrelang eingeübte Kommunikation verlassen können, bekommt der unbedarfte Zuhörer oft nicht den gesamten Inhalt der Unterhaltung mit. Und dies führte bei mir zu dem Gefühl, als Zuschauer nicht vollständig in die Handlung integriert zu werden und wie durch ein Fenster darauf zu schauen.

Zusammengefasst mag Graf in seiner Kritik sicherlich vorhandene Probleme angesprochen haben, die zu tendenziell schlechteren Ergebnissen wie Hochhäuslers *Eine Minute Dunkel* führen können. Die sehenswerten Filme von ihm und Petzold zeigen jedoch, dass beide Stilrichtungen ihre Berechtigung haben und ganz ähnliche Wirkungen beim Zuschauer hervorrufen können; der Stil also nicht allein für einen guten oder schlechten Film verantwortlich ist.

Schade ist, dass das Filmprojekt *Dreileben* nur auf dieser Konzeptebene funktioniert. Die Filme greifen nicht so gut ineinander, wie sie es könnten; ich hatte das Gefühl, dass sich die drei Regisseure entweder nicht ausreichend abgesprochen haben oder bewusst durchgängige Handlungsstränge torpedieren und so ein nicht lösbares Puzzle erschufen. Gerade *Komm mir nicht nach* und *Eine Minute Dunkel*, die sich stark mit dem geflohenen Sexualstraftäter beschäftigen, müssten viel mehr Einfluss aufeinander haben, als sie es tun. Aber weder die Aufdeckung einer korrupten Polizeitruppe noch die schlussendliche Festnahme des Flüchtenden werden im abschließenden Film thematisiert, so dass der Eindruck entsteht, sie hätten nichts miteinander zu tun.

Da fehlt die Harmonie und deshalb sollten die Filme besser unabhängig voneinander betrachtet werden und nicht als Einheit oder gar Trilogie - und erst Recht nicht als Krimi. Ein verteilter Sendetermin z.B. an drei aufeinander folgenden Abenden hätte dem Format bestimmt besser getan und sich sicherlich auch in den Einschaltquoten niedergeschlagen. Aber qualitativ hochwertige Filme um Mitternacht zu senden hat ja Tradition bei der ARD, und die Zuschauerzahlen auf diesen Ausweichsendeplätzen entsprechen dann als selbsterfüllende Prophezeihung dem nicht vorhandenen Vertrauen in das eigene Programm.
