---
title: "Das Garmin-Desaster"
date: "2011-09-22T00:10:56"
categories: [gedacht]
---

Bei der Anmietung eines Autos für die Reise an der Ostküste der USA hatten wir auf zwei Punkte geachtet. Zum Einen sollte der Wagen einen ausreichend großen Kofferraum für drei Koffer haben und desweiteren ein Navigationsgerät, um uns sicher über die uns unbekannten amerikanischen Straßen zu leiten.

Bekommen haben wir schließlich einen [Dodge Grand Caravan](http://www.dodge.com/en/2011/grand_caravan/index.html) und ein separates [Garmin nüvi 1350](https://buy.garmin.com/shop/shop.do?cID=134&pID=30937), welches mich zu dieser Schmähschrift verleitet hat. Denn das Garmin war das schlechteste Navigationsgerät, das ich jemals in Benutzung hatte.

Die Probleme fingen damit an, dass wir vor der Eingabe der Zieladresse immer erst den Bundesstaat dazu wählen mussten. Für Amerikaner mag dies normal sein, doch für mit der Gegend unvertraute Autofahrer, also der Hauptzielgruppe eines Navis, sollte zumindest eine Suche über alle Staaten möglich sein, auch wenn die Ergebnislisten lang werden können.

Als wir diese Einstiegshürde überwunden hatten, folgten die Probleme im alltäglichen Einsatz. So ist das Kartenmaterial von Garmin und seine Darstellung auf dem Display alles andere als optimal, was das Abschätzen von Entfernungen und das Erkennen der richtigen Kreuzung oder Abfahrt zum Glücksspiel machte. Erschwerend kam hinzu, dass die Ansagen meist viel zu spät kamen, so dass ein notwendiger Spurwechsel gar nicht mehr möglich war.

Ein weiterer eklatanter Schwachpunkt war die  Routenführung. Das Navi hatte des Öfteren Aussetzer, bei denen es uns vom Highway runter lotste und durch kleine Straßen von Städten wie [Lowell](/blog/2011/04/24/movies-on-a-plane/) schickte, obwohl wir auf dem Highway hätten bleiben können. Das war leider keine Ausnahme von der Regel, denn ein anderes Mal sollten wir mitten durch eine Army Base fahren (ein Anwerbversuch der amerikanischen Streitkräfte?) oder über das gesperrte Gelände eines Flughafens. Zum Glück hatte ich vorher eine Karte auf mein Handy geladen, so dass ich uns aus diesen Situationen hinausleiten konnte. Doch wenn wir neben dem Navi noch eine andere Karte zur Navigation benötigen, wofür benötigen wir dann ein Navi?

Ebenfalls nervend waren die langen Denkpausen, die sich die vermutlich unterdimensionierte Hardware dieses Einsteigermodells gönnte. Allein der Start des Gerätes, welches keine Eingaben ohne GPS-Signal ermöglicht, dauerte oft Minuten. Aber auch auf einer Route nahm es sich die eine oder andere Auszeit, was auf Highwaykreuzen sehr nervig sein kann, wenn wir dringend einen Hinweis auf die richtige Ausfahrt brauchten. Dank der Mautstationen reicht es in den Vereinigten Staaten nämlich nicht aus zu wissen, in welcher Himmelsrichtung das Ziel liegt. Alle Richtungen werden durch dieselben Mautabfahrt geleitet und danach wieder aufgeteilt. Teilweise passiert dies so kurz hinter dem Mauthäuschen, dass man sich von vornherein für die richtige Spur entscheiden muss, um danach die richtige Abfahrt zu erreichen.

Alles in allem hatte das Garmin so viele Macken und Probleme, dass wir uns nur darüber geärgert haben und ich es definitiv niemandem empfehlen kann. Wer sich nur auf dieses Gerät verlässt, wird selten gut an sein Ziel gelangen...
