---
title: "So viel Zoom muss sein"
date: "2009-07-19T21:26:26"
categories: [getan]
---

Nach vier fotoreichen Wochenenden will ich nun eine Einschätzung meiner neuesten Errungenschaft abgeben: Die [Panasonic Superzoomkamera TZ7](/blog/2009/04/08/stand-der-technik-v/) ist die Digicam meiner Wahl geworden. Sie erfüllt ganz einfach die meisten meiner Anforderungen und hat keinen so großen Rückstand bei der Bildqualität, wie es einige Labortests vermuten ließen. Mein Dank geht dabei an die vielen Hobbyfotographen, die von allen [Kameras in meiner engeren Wahl](/blog/2009/06/06/stand-der-technik-vi/) so fleißig selbstgeschossene Bilder in diverse [Foren](http://www.dslr-forum.de/forumdisplay.php?f=28) eingestellt haben.

Anfangen will ich mit den negativen Punkten, damit ich diese hinter mir habe. Da ist zu allererst das leichtgängige Moduswahlrad zu nennen, dass sich meist beim Ziehen der Kamera aus der Tasche verstellt (ja, die Kamera passt noch in meine Hosentasche) - wenn ich die Kamera anschalte muss ich immer ein Auge darauf haben. Zum Anderen fährt Panasonic eine dem Kunden gegenüber unverschämte Akkustrategie. Originalakkus kosten im Bereich von 50-60€ und Nachbauten können seit dem Firmwareupdate 1.2 nicht mehr genutzt werden. Da ich aber noch die Version 1.1 auf der Kamera habe und das Update keine weiteren "Verbesserungen" mitbringt, kann ich auch weiterhin meinen 15€-Akku aus China verwenden. Und einen Zweitakku brauche ich definitiv, denn der HD-Videomodus zieht ordentlich Saft, so dass die Kamera bei exzessivem Filmen keinen Tag durchhält. Für Fotos gilt diese kurze Laufzeit zum Glück nicht.

Zu guter Letzt ist die Bedienungsanleitung eine Zumutung. Das beigelegte Heftchen deckt kaum mehr als das Anschalten der Kamera ab und die als PDF vorliegende Vollversion beschreibt zwar alle 30 Modi, die im Szenenmodus aktivierbar sind, aber es gibt nicht einmal eine Aufzählung aller Punkte im Menü. Da diese zum Teil sehr kryptisch benannt sind kann man entweder ausprobieren, was sie bewirken, oder in der Anleitung suchen und hoffen, eine kurze Erläuterung im Kleingedruckten zu finden ist, aus dem die Hälfte jeder Seite besteht. Dort findet sich dann auch der Hinweis, dass man von einem PC aus über die an einem USB-Port angeschlossene Kamera keine Dateien auf der SD-Card löschen kann - es sei denn, man besitzt Windows Vista. Als Alternative bleibt nur das Löschen mittels Kameramenü oder in einem separaten Kartenlesegerät - eine echt seltsame Einschränkung!

Keines dieser Probleme kann jedoch die Stärken der Kamera überspielen. Da ist zum Einen der starke Videomodus, der überraschend guten Bild & Ton in 720p liefert (zum Schnitt bietet sich [KDEnlive](/blog/2009/07/07/stabilitat-und-abhangigkeiten/) an). Der ohnehin nicht besonders schnelle Zoom wird dabei zwar noch einmal verlangsamt, aber ich habe noch keine besseren Videos aus einer Kompaktkamera gesehen. Diese sind dann auch per Mini-HDMI-Anschluss auf HD-Fernseher abspielbar, jedoch ist die Bildqualität über meine [WDTV](/blog/2009/02/21/mein-neues-spielzeug/)-Box besser.

Die Zoomreichweite ist ein weiteres Highlight, gerade in Verbindung mit dem Telemakro. So können relativ weit entfernte Details scharfgestellt werden, als ob sie sich vor der eigenen Nase befänden. In diesen Situationen zeigt auch der Bildstabilisator sein Können, den man nur mit ganz extremen Schüttelbewegungen zu Unschärfe überreden kann.

Der für eine Schnappschusskamera wichtige Vollautomatikmodus arbeitet überzeugend schnell, nur in ganz wenigen Situationen konnte ich ihn nicht zu einem sofortigen Auslösen überreden. Werbefeatures wie die Gesichtserkennung habe ich dabei ausgeschaltet; diese verzögert sonst die Auslösezeiten. Bin ich als Fotograph einmal anderer Meinung als die Kamera, was Blitz und sonstige Einstellungen angeht, dann habe ich noch eine Art manuellen Modus zu Verfügung, in dem ich alle Features dazuschalten kann, wie ich will. Gerade bei wenigem oder Gegenlicht bekommt man so oft bessere Bilder hin als die Automatik, die sich zwar bewusst ist, dass sie viel Licht für weniger Rauschen benötigt, aber dann zu zeitig blitzt und so die Stimmung des Augenblicks verändert.

Schön ist, dass man Belichtungsreihen mit drei Bildern von -1 bis +1 EV schießen kann (wichtig für HDR-Experimente); allerdings benötigt man dann ein Stativ. Finden tut man diese Option durch einen weiteren Knopfdruck auf die manuelle Helligkeitskorrektur, die sogar von -2 bis +2 EV reicht. Allerdings habe ich die Erfahrung gemacht, dass man lieber mit der Bildbearbeitung der Wahl bestimmte Bildbereiche aufhellt, anstatt vorher in der Kamera die ohnehin begrenzte Helligkeitsverteilung zu verschieben. [Die wichtigste Hoffnung](/blog/2009/01/15/das-schwachste-glied-in-der-kette/) hat sich auf jeden Fall erfüllt: Die Anzahl der nachzubearbeitenden Bilder hat sich drastisch reduziert im Vergleich zu meiner alten Sony-Kamera.

Zu den vielen Optionen, für die ich Panasonic dankbar bin, gehört auch die Einstellung der Bildgröße. Ob 3:2 (meine Wahl), 4:3 oder 16:9, es gibt verschiedene Abstufungen von 10MP abwärts, wobei gerade bei ausreichend hellen Szenen die festgehaltenen Details beeindruckend sind. Alles in allem bin ich also sehr zufrieden mit dem Kauf, wenngleich er durchaus etwas preiswerter hätte sein können.
