---
title: "El mal ajeno - For the good of others"
date: "2010-02-28T23:00:33"
categories: [gesehen]
---

[Berlinale-Filmdatenblatt](http://www.berlinale.de/de/programm/berlinale_programm/datenblatt.php?film_id=20100727)

Was ist man bereit zu geben, wenn es um das Wohl anderer Menschen geht? Was würde man opfern, um dafür viele Leben zu retten? Ist man bereit, den eigenen Vater oder die Tochter sterben zu lassen in der Gewissheit, vielen fremden Menschen den Tod zu ersparen? Kann man Leben überhaupt gegeneinander aufrechnen?

Dies ist die zentrale Frage von *El mal ajeno* des spanischen Regisseurs Oskar Santos. Doch für die Formulierung dieser Frage hat er eine ungewöhnliche Form gewählt; nämlich ein Familien- und Ärztedrama mit einem fantastischen Element. Dieses Element ist die Eigenschaft, Menschen nur durch Auflegen der Hand heilen zu können. Der Arzt Diego erhält diese Gabe ungewollt, doch als er das Wunder realisiert muss er ebenso schnell erkennen, dass es auch Schattenseiten mit sich bringt. Denn ausgerechnet den Menschen, denen er am nächsten steht, kann er nicht helfen, und diese müssen gleichzeitig die Konsequenzen dafür tragen, dass Diego fortan über Leben und Tod seiner Patienten bestimmen kann.

Erzählt wird diese ungewöhnliche Story mit einem angenehm humorvollen Unterton in ruhigen Bildern, die sehr viel Platz lassen für die Einführung von Diegos Familienverhältnissen und seinem Verständnis der Arzttätigkeit. Als Betreuer von dem Tode geweihten Kranken hat er eine abweisende Haltung gegenüber seinen Patienten entwickelt; er versucht deren Probleme nicht an sich heranzulassen, damit sie ihn nicht auffressen. Diese Haltung hat sich aber auch auf sein Privatleben übertragen und zu einer Entfremdung von Frau und Tochter geführt. Die Gabe der heilenden Hand lässt ihn nun förmlich auftauen. Endlich kann er seine Patienten an sich heranlassen, kann sich mit ihnen befassen, denn er ist nun in der Lage, ihren Tod zu verhindern, und dies überträgt sich auch auf sein Privatleben.

Doch jede Entscheidung über das Schicksal eines Menschen hat ihre Folgen. Nicht nur, dass Diegos Vater innerhalb einer Woche einen tödlichen Tumor entwickelt und daran stirbt, auch die von ihm Geheilten haben daran zu knabbern, plötzlich wieder eine Chance auf ein Leben zu haben. Am Ende muss Diego erfahren, dass gerade ihm die Gabe der heilenden Hand übertragen wurde, weil er auf Abstand zu den Patienten ging, weil er bereits vorher so arbeitete, wie es die Fähigkeit erfordert. Dies ist die einzige Möglichkeit, überhaupt damit glücklich zu werden. Ein Aufrechnen, so viel macht der Regisseur am Ende klar, kann es bei Menschenleben nicht geben. Es bleibt nur die Hoffnung, mehr Menschen geholfen als geschadet zu haben.

Dass der Film trotz der erst zum Schluss geklärten Frage, wie das seltsam unpassende Element der heilenden Hand in dieses Drama eigentlich passt, und des gemächlichen Erzähltempos überhaupt funktioniert, verdankt er eindeutig den Schauspielern, die die psychologisch gut ausgearbeiteten Charaktere so überzeugend verkörpern, dass die Handlung niemals ins Unglaubwürdige abdriftet. Allen voran der unter dem Vollbart kaum wieder zu erkennende Eduardo Noriega, ein paar Jahre jünger als seine Leinwandrolle Diego, verdient sich hier Bestnoten. Am Ende steht dennoch die Akzeptanz der heilenden Gabe zwischen dem Film und seinen Zuschauern - ein Hinderniss, das sicherlich nicht jeder überwinden wird können.
