---
title: "Im Bann des Jade Skorpion"
date: "2001-12-11T00:00:02"
categories: [gesehen]
---

*USA (2001)
Regie: Woody Allen
Darsteller: Woody Allen (C.W. Briggs), Helen Hunt (Betty Ann Fitzgerald), Dan Akroyd (Chris Magruder), Charlize Theron (Laura Kensington), David Ogden Stiers (Voltan Polgar) und andere Stichwortgeber*
[Offizielle Homepage](http://www.dreamworks.com/jadescorpion/)

New York 1940: Der erfolgreiche Versicherungs-Detektiv C.W. Briggs bekommt nach 20 Jahren in der Firma plötzlich Ms Fitzgerald vor die Nase gesetzt, die die Firma optimieren soll und gerade in seiner Abteilung mächtig durchgreift. Er versteht die Welt nicht mehr, als seine bewährten Methoden plötzlich für veraltet erklärt werden und selbst der Chef hinter der Neuen steht. Während einer Geburtstagsfeier werden jedoch die beiden Streithähne zusammen von dem Zauberer Polgar hypnotisiert, der Ihnen in Trance versetzt einredet, sie seien ein Paar, an was sie sich später jedoch nicht erinnern können. Doch nicht nur das: Der Magier hat auch die Hypnose nicht vollständig aufgehoben und benutzt Briggs des Nachts ohne dessen Wissen, um wertvolle Juwelen aus alarmgesicherten Häusern zu stehlen. Am Tage dagegen jagd er sich praktisch selber, ohne aber die richtigen Schlüsse zu ziehen. Die zieht dafür die ebenfalls beauftragte Detektei Cooper und so landet Briggs, der sich noch immer für unschuldig hält, im Gefängnis. Dank Laura Kensington kann er fliehen und bekommt so mit, wie Ms Fitzgerald seine Rolle weiterspielen muss und endlich wird ihm alles klar...

Bei uns in Halle hat es der neue Film von Woody Allen nicht einmal in die Multiplex-Kinos geschafft. Das war jedoch ein großer Fehler, denn der Regisseur/Drehbuchautor/Hauptdarsteller läuft zu grandioser Komödienform auf. Ein Wortgefecht jagt das andere, der Wortwitz ist unübertroffen und die Story ist einfach zum Schreien komisch. Die Ausstattung trifft voll die 40er, das Musikthema, welches bei jedem Einbruch gespielt wird, passt perfekt und die Reminiszenzen an den Film Noir wie der Trenchcoat oder die umwerfende Charlize Theron treffen auf den sich mal wieder selbst spielenden Allen (was auch sonst) und die immerwährende Kritik an dem schnellen Voranschreiten des Lebens in Form der alles wegrationalisierenden Betty Ann und den Detektiven Cooper mit ihren neuen Methoden wie Fingerabdrücken (!) und Haaranalysen.

Briggs ist auf der einen Seite der erfolgreiche Detektiv, den scheinbar alle in der Abteilung bewundern und der alles mit seinem Mundwerk niederredet und sarkastisch kommentiert, und auf der anderen Seite der Loser in der Liebe, dem die Frauen etwas vor- oder gar als Vorgesetzte das Leben schwer machen. Dabei wird aber so manche Rolle verdreht wie die der Laura Kensington, der Femme Fatale, die ihm nie etwas vorspielt und ihm dann sogar bei der Flucht hilft anstatt ihm in Stich zu lassen, weil er sie in Trance abgewiesen hat (!). Oder die beiden Coopers, "Dick und Doof", die dabei aber den Fall mehr oder weniger richtig lösen. Und die starke Vorgesetzte Ms Fitzgerald ist in Bezug auf Männer dann doch nicht so stark, wie sie von außen wirkt.

Fazit: Ein Film mit Biss; die Wortgefechte sind geniale Schlagabtausche der etwas anderen Art und die Story parodiert so ganz nebenbei ein ganzen Genre - ein Highlight nicht nur für Woody-Allen-Fans!
