---
title: "Death proof"
date: "2007-09-13T21:54:28"
categories: [gesehen]
---

*USA (2007)
Regie: Quentin Tarantino
Darsteller: Kurt Russell (Stuntman Mike), Sydney Tamiia Poitier (Jungle Julia), Vanessa Ferlito (Butterfly), Jordan Ladd (Shanna), Rose McGowan (Pam), Rosario Dawson (Abernathy), Tracie Thoms (Kim), Zoe Bell (Zoë), Mary Elizabeth Winstead (Lee), Quentin Tarantino (Warren), uvm*
[Offizielle Homepage](http://www.deathproof.senator.de)

Ein Soundtrack zusammengestellt aus alten Soundtracks; stylische Verfolgungsjagden in Musclecars; schicke Frauen ("The Girls") in altmodischen Klamotten, die sich weite Teile des Films sinnlos-seichten Unterhaltungen hingeben und dazu ständig die Füße in die Kamera halten; kultige Kneipen mit alten B-Movie-Filmplakaten - dies kann gar nichts anderes als sein als der neueste Quentin-Tarantino-Film.

Ursprünglich mit seinem Busenfreund Robert Rodriguez als erster Teil eines [Grindhouse](http://de.wikipedia.org/wiki/Grindhouse_(Film)  )-Doublefeatures geplant, läuft der Film international auf fast zwei Stunden aufgebläht getrennt von seinem Zwilling in den Kinos. Und dies ist eindeutig zu lang für die handvoll Handlung, die Tarantino in dem Film versteckt.

Hauptcharakter ist Stuntman Mike, der mit seinem titelgebend todessicheren Stunt-Muscle-Car Jagd auf junge Frauen macht, indem er sie in Unfälle verwickelt. Doch dann gerät er an ein Pärchen von Stuntfrauen, die ihm Paroli bieten können...

Death proof ist der erneute Versuch von Tarantino, einen Fanfilm über das Exploitation-Kino zu drehen - diesmal mit dem Schwerpunkt Musclecars und Verfolgungsjagden. Garniert wird dies von den typischen Zutaten: Viele lässige Dialoge ohne wirklichen Inhalt dominieren große Teile des Films, während künstliche Fehler wie Schwarz-Weiß-Sequenzen, Bildfehler und Sprünge im Filmfluss den Eindruck des B-Movies weiter verstärken sollen. Nur leider sind alle Effekte altbekannt und langweilen mittlerweile, während es den Dialogen an jeglichem Witz oder Ideen mangelt. Nur selten packt Tarantino Szenen wie mit den beiden Polizisten im Kino aus, welche während ihres Dialoges über Stuntman Mike ständig durch die selbe Tür des Krankenhauses laufen oder wie die auf jedes Opfer einzeln geschnittene Unfallszene.

Besser gelungen ist da schon die abschließende Verfolgungsjagd, bei der die auch im real life als Stuntfrau arbeitenden Zoe Bell auf der Motorhaube eines Autos hin- und hergeschleudert wird, während Stuntman Mike das Auto ständig rammt. Dies wirkt realistischer als alles, was ich seit langem im Kino gesehen habe und ist alleine schon den Eintrittspreis des Filmes wert. Viel mehr bleibt aber auch nicht in Erinnerung von Death proof - für mich ist er der bisher schlechteste Tarantino, da es ihm einfach an Handlung fehlt.

