---
title: "There will be blood"
date: "2008-08-28T21:48:50"
categories: [gesehen]
---

*USA (2007)
Regie: Paul Thomas Anderson
Darsteller: Daniel Day-Lewis (Daniel Plainview), Paul Dano (Paul / Eli Sunday), Dillon Freasier (H.W. Plainview), Ciarán Hinds (Fletcher), Henry (Kevin J. O’Connor) und andere Ölmänner*
[Offizielle Homepage](http://www.therewillbeblood.de/)

Nun, da mein Full-HD-Equipment vollständig ist, habe ich den ersten Test mit der Blu-Ray von *There will be blood* vollzogen, natürlich in 1080p und 24Hz für echtes Kinofeeling. Der Film mit seinen weiten, kargen Landschaften eignet sich besonders gut für die hohe Auflösung, beeindruckt aber auch durch die Details in den Gesichtern der Darsteller.

Unter denen sticht Daniel Day-Lewis hervor, verdient für diese Rolle als Ölmann Daniel Plainview mit dem Oscar prämiert. Wie so oft sein Gesicht unter Bärten versteckend und dennoch ausdrucksstark ist jede seine Bewegungen, jede Regung durchdacht und eindrucksvoll. Doch auch sein Gegenspieler, Paul Dano (zuletzt als Sohn in *Little Miss Sunshine*), weiß zu überzeugen. Da er allerdings zwei Brüder spielt, die nie gleichzeitig im Bild sind, wirken einige Szenen sehr verwirrend. Ebenso im Unklaren gelassen wird man mit dem Bruder von Daniel: Ist er wirklich ein Fremder, der sich nur als Bruder ausgibt, oder ist es umgekehrt? Mit vielen solchen Fragen wird der Zuschauer in diesem erzählerisch wie musikalisch sehr minimalistischen Film allein gelassen. Wenig wird gesagt oder erklärt; Regisseur Paul Thomas Anderson lässt den Ölmagnaten pur und in aller Gewalt seine Wirkung entfalten. Hilfestellung zur Interpretation wird nicht gegeben.

Schwierig und wenig massenkompatibel ist zudem das Timing des Films. Erst nach fünfzehn Minuten fällt das erste Wort; vorher sieht man ausschließlich hart arbeitende Männer. Dies scheint dem Charakter des Daniel Plainview einen plausiblen Hintergrund zu geben, doch später wird er andere Gründe für seine Menschenfeindlichkeit nennen. Eine etwas straffere Inzenierung hätte da nicht geschadet. Das Ende des Films nach einem größeren Zeitsprung wirkt schließlich zu aufgesetzt, auch wenn die wichtigen Handlungsstränge um Plainviews Sohn und seinen Gegenspieler Eli Sunday beendet werden und dem Titel aller Ehre getan wird.

Fazit: *There will be blood* ist eine beeindruckende Charakterstudie, die durch Bilder und Darsteller die Zuschauer zu fesseln weiß. Allerdings ist der Film auch recht sperrig und gibt wenig Hinweise zur Rezeption, so dass man etwas Ausdauer für die 2,5 Stunden mitbringen sollte.
