---
title: "Harry Potter und die Kammer des Schreckens"
date: "2002-11-25T00:00:20"
categories: [gesehen]
---

*UK (2002)
Regie: Chris Columbus
Darsteller: Daniel Radcliffe (Harry Potter), Emma Watson (Hermine Granger), Rupert Grint (Ron Weasley), Richard Harris (Albus Dumbledore), Maggie Smith (Professor Minerva McGonagall), Kenneth Branagh (Gilderoy Lockhart), Robbie Coltrane (Hagrid), Alan Rickman (Professor Severus Snape), Tom Felton (Draco Malfoy), Jason Isaacs (Lucius Malfoy), Christian Coulson (Tom Riddle) und andere Zauberlehrlinge*
[Offizielle Homepage](http://www.harrypotter.de/)

Harry verbringt die Sommerferien wie alle Schüler zu Hause, doch er möchte aufgrund seiner Stiefeltern so schnell wie möglich zurück nach Hogwarts. Da erscheint die Hauselfe Dobby bei ihm im Zimmer und versucht ihn zu überreden, nie wieder zur Zaubererschule zurück zu kehren, da dies sonst sein Ende wäre. Doch ein Harry Potter lässt sich von so etwas nicht einschüchtern und tritt deshalb gemeinsam mit den Weasleys die Rückreise an. In Hogwarts kommt es dann aber schnell zu seltsamen Ereignissen - einige Mitglieder der Schule werden versteinert aufgefunden und seltsame Drohungen stehen an den Wänden geschrieben. Als man bei Harry dann das Talent entdeckt, mit Schlangen zu reden, steht er auf einmal unter Verdacht, die geheimnisvolle "Kammer des Schreckens" geöffnet zu haben, die das Ende von Hogwarts bedeuten könnte. Zusammen mit Hermine und Ron muss der junge Potter nun die Wahrheit um diese Kammer herausfinden...

Weihnachtszeit ist Fantasy-Zeit im Kino, und so habe ich mir wie letztes Jahr den [Herrn der Ringe](/blog/2001/12/19/der-herr-der-ringe-die-gefahrten/) mit Harry Potter schmackhaft gemacht. Und siehe da, die meisten Argumente für und wider [Teil 1](/blog/2001/12/04/harry-potter-und-der-stein-der-weisen/) wiederholen sich: Zuerst ist Harry P. vor allem wieder ein Film für Kinder, die wichtigen Dialogzeilen werden zum Teil dreimal wiederholt, damit es auch der letzte 6-jährige noch versteht, was die Spielzeit unnötig aufbläht - der Film hätte mit demselben Inhalt auch kürzer ausfallen können! 

Wieder einmal wird mir auch nicht klar, mit wie viel Glück und wie wenig Verstand Harry P. agiert - jeder scheint mehr zu wissen als der kleine Zauberer und unterstützt ihn trotzdem ständig - muss wohl zum Thema kindgerechte Handlung gehören, die sich dem erwachsenen Zuschauer nicht immer logisch erschließt. Die Fantasy-Welt ist immer noch klasse, jedoch lässt sie es diesmal an überraschenden Neuerungen mangeln, allein das seltsame, eigenbrötlerische Auto und die Hauselfe Dobby retten den Film in diesem Punkt.

Auch die Umsetzung wirkt diesmal nicht so detailreich wie noch im [Stein der Weisen](/blog/2001/12/04/harry-potter-und-der-stein-der-weisen/), da hat man dann doch zu viel Wert auf die "düstere" Atmosphäre gelegt. Schauspielerisch kann man zwar eine leichte Steigerung bei Daniel Radcliffe feststellen, aber wirklich überzeugen kann er in seiner Rolle wieder nicht - eine Rolle wohlgemerkt, von der wahrscheinlich jeder Leser etwas anderes erwartet. Gut fügt sich dagegen Kenneth Branagh in Hogwarts ein, der seinen Gilderoy Lockhart angenehm übertrieben darstellt und dabei einen nicht geringen Anteil zur Komik des Filmes beiträgt. Dies ist dann auch die wirkliche Stärke des Films; die vielen skurilen Gestalten der Zaubererschule, allen voran der zur Selbst-Geißelung neigende Dobby und die auf der Mädchentoilette umher geisternde Myrtle, machen "Die Kammer des Schreckens" zu einem weit unterhaltsameren Film für die älteren Zuschauer als noch den Vorgänger.

Zuletzt muss ich aber noch die Frage stellen, wie zum Teufel man im Filmtitel (bzw. vorher im Buchtitel) schon den Inhalt der Kammer der Geheimnisse (so die richtige Übersetzung) vorwegnehmen kann - bis zur ersten Öffnung wusste ja noch nicht einmal jemand, was sich darin befindet...

Fazit: Ein Film für Kinder mit dementsprechender Story, der diesmal zwar etwas düsterer daherkommt, aber gleichzeitig bedeutend lustiger ist!
