---
title: "My son, my son, what have ye done"
date: "2010-11-07T22:55:05"
categories: [gesehen]
---

Man nehme aus einer Fülle von Details der Vorlage ein paar wenige, so dass sie aus dem Kontext gerissen nur noch skuril wirken. Man nehme alle wichtigen Elemente einer Geiselnahme - die ermittelnden Kommissare, die Absperrung der Polizei, die Verhandlungen um Essen und Fluchtwagen, das Anrücken eines Sondereinsatzkommandos - und präsentiere sie als bloße Staffette, als abgehackte, unpassende Enden eines Handlungsrahmens, der eigentlich keine Bedeutung für den Film hat. Man stülpe dem Ganzen noch einen extremen Kontrast über, um die vielen Wechsel zwischen digitalen Handkameras und klassischen Filmkameras zu überdecken. Und heraus kommt: Ein ganz schlechter Film.

Werner Herzog mag es offensichtlich noch immer, zu experimentieren und Sehgewohnheiten hinter sich zu lassen. So lässt er seinen Charakter statt in Pakistan in Peru zum Muslimen werden und dreht eine dazu gehörende Einstellung sogar in China. Manchmal lässt er seine Figuren einfach in der Szene still stehen und filmt dies für einige lange Sekunden. Während in dem Remake von *Bad Lieutenant* die surrealen Szenen mit den Echsen die Auswirkungen der Drogen auf den Hauptcharakter symbolisieren, ist die bloße Häufung solcher Fremdkörper in *My son, my son, what have ye done*, so sie doch zusammen mit der Musik eine dem Muttermord angemessene düstere Atmosphäre schaffen, einfach nur anstrengend.

Ich habe nach einer Weile vollkommen das Interesse an der Handlung verloren. Wenn der Regisseur sich so wenig um seine Geschichte kümmert, dann muss ich ich das schließlich auch nicht. Und wenn er seine Geschichte mutwillig zerstört, dann reicht es auch nicht, dass David Lynch seinen Film produziert hat und einige gute Schauspieler dabei vergeudet werden. Bitte nicht ansehen!
