---
title: "Ein kurzer Musikrückblick 2010"
date: "2010-12-31T16:43:29"
categories: [gehört]
---

Nachdem mein Filmjahr 2010 mit gerade einmal 15 Kinobesuchen (davon knapp die Hälfte allein auf der [Berlinale](/blog/tag/berlinale/)) eher bescheiden ausgefallen ist und ich so wenig Bücher wie lange nicht mehr gelesen habe, will ich mich [erneut](/blog/2005/12/30/meine-lieblingsalben-2005/) daran versuchen, das musikalische Jahr 2010 Revue passieren zu lassen.

Etwas überraschend entwickelte sich 2010 zu einem Jahr der Comebacks. So schaffte es das *Korn*-Album *III - Remember who you are*, die letzten Werke der Band vergessen zu lassen und die Energie der Anfangsjahre mit dem durchaus gereiften Sound der Band zu einer Einigkeit zu verschmelzen, die mit sehr gut gefallen hat.

Eine Phase der Tiefschläge hat auch *Taproot* überstanden, die nach Ausflügen in das Alternative-Genre mit deutlich softerem Sound (und geringem Erfolg) nun auf *Plead the Fifth* wieder den Hardcore der ersten beiden Alben *Gift* & *Welcome* aufgegriffen haben. Sänger Stephen Richards schafft es dabei sehr gut, die Emotionalität der Texte in kraftvolle Schreiparts und ebenso ausdrucksstarken Gesang zu konzentrieren, die in dieser Kombination einzigartig sind.

Mehr einen interessanten Richtungswechsel als ein Comeback haben die *Deftones* dieses Jahr hingelegt. Einst waren sie zusammen mit *Korn* Mitbegründer des Nu-Metal, doch der seltsame Mix aus unter Drogeneinfluss entstandenen psychedelischen Einlagen und dem harten Crossover-Sound verwehrte mir oft genug den Zugang zu den vorangegangenen Alben. Und so wäre es vermutlich auch weitergegangen, wenn nicht kurz vor den Aufnahmen zum neuen Studioalbum der Bassist der Band in einen schweren Unfall verwickelt worden wäre und zeitweise im Koma lag. Dies beeinflusste die restlichen *Deftones*-Mitglieder so stark, dass sie begannen, ein komplett neues Album zu schreiben: *Diamond Eyes*. Darauf ist die Band so melodiös und eingängig wie selten zuvor, ohne dabei an Eindringlichkeit zu verlieren, und schafft es so, ein ganzes Album aus einem Guss ohne einen Durchhänger abzuliefern.

Den großen Durchbruch dieses Jahr haben meiner Meinung nach *Circa Survive* geschafft. Dass ihr Sound irgendwo zwischen Progressive, Emo und Indie zusammen mit der extrem hohen Stimme von Sänger Anthony Green so ziemlich einzigartig auf der Welt ist, dies hatten schon die vorangegangenen Alben gezeigt. Und doch fehlte immer irgendetwas; die ambitionierte Musik litt etwas unter dem bemüht artifiziellen Sound. Dies hat sich nun geändert - endlich zeigt die Band eine Energie, die sie so vorher missen ließ. Wer sich einen Eindruck von *Circa Survive* machen will, der sollte den [kostenlosen Download auf MySpace](http://www.myspace.com/transmissions) ausprobieren, der einen guten Einblick in die Qualität des Albums *Blue Sky Noise* bietet.

Zu guter Letzt will ich noch eine Empfehlung für *The Vitality Theory* von *Rosaline* aussprechen. Diese haben die ausgetretenen Pfade des Post-Hardcore verlassen, um eigene Wege zu gehen, und dabei einen interessanten, fast schon altmodischen Sound kreiert, der die Genregrenzen sprengt. Dazu kommen Texte, die zwar den emotionalen Ansatz des Emo folgen, aber viele technische Bilder finden, um ihre Stimmungen auszudrücken - dies kommt bei mir natürlich gut an.

Damit wünsche ich allen Lesern dieses Blogs einen guten Rutsch in das Jahr 2011.
