---
title: "Der Vorleser"
date: "2009-06-26T20:33:53"
categories: [gesehen]
---

*USA (2008)
Regie: Stephen Daldry
Darsteller: Kate Winslet (Hanna Schmitz), David Kross / Ralph Fiennes (Michael Berg), Bruno Ganz (Professor Rohl), Karoline Herfurth (Marthe), Susanne Lothar (Carla Berg), Matthias Habich (Peter Berg), Burghart Klaußner (Richter), Lena Olin (Rose Mather / Ilana Mather), Alexandra Maria Lara (Ilana Mather), u.a.*
[Offizielle Homepage](http://dervorleser-film.de/)

Der Schüler Michael Berg aus bürgerlichen Verhältnissen lernt in den späten fünfziger Jahren die deutlich ältere Straßenbahn-Schaffnerin Hanna Schmitz kennen. Sie wird seine erste Liebe und zwischen den beiden entwickelt sich eine ungewöhnliche Beziehung: Vor dem Liebesspiel muss er ihr immer aus Büchern vorlesen, denn Hanna ist Analphabetin, was sie aber nie zugibt. Doch eines Tages ist sie plötzlich verschwunden und für Michael, zuvor von seiner geheimen Beziehung vollends in Beschlag genommen, beginnt ein scheinbar normales Leben, er nimmt ein Jurastudium auf.

Als er im Rahmen seines Studiums einen Kriegsverbrecherprozess besucht, muss er mit Erschrecken feststellen, dass auch Hanna auf der Anklagebank sitzt. Sie hat als Aufseherin eines KZ den Tod von mehreren hundert Juden mit zu verantworten und wird zu einer lebenslangen Haftstrafe verurteilt. Während sie diese absitzt, schickt Michael ihr Tonbandaufnahmen der Bücher, die er ihr einst vorlies und ermöglicht Hanna so, das Lesen und Schreiben zu lernen, ohne dass sie ihre Schwäche öffentlich zugeben muss...

Verschiedene Themen kämpfen in *Der Vorleser* um die Vorherrschaft. Da ist zum Einen vordergründig die Liebesgeschichte, wobei Liebe vielleicht der falsche Ausdruck ist. Michael stößt sich nur zu gerne seine Hörner bei Hanna ab, doch schon bald merkt er, dass er seiner Bettgefährtin geistig überlegen ist. Liest er ihr anfangs noch Hochliteratur vor, so werden die Bücher mit der Zeit immer seichter, bis er schließlich bei Comics und Kinderbüchern ankommt. Doch in seinem jugendlichen Leitsinn merkt er nicht, wie sehr er abhängig von dem so erkauften Sex ist; die niemals erlernten Fähigkeiten zum Führen einer echten zwischenmenschlichen Beziehung werden ihm sein Leben lang Schwierigkeiten bereiten.

Dann ist da natürlich noch die Auseinandersetzung um Schuld und Sühne des deutschen Volkes im dritten Reich. Hanna wird zwar zeitweise mehr als Opfer denn als Täter dargestellt, aber so einfach macht es der Film dem Zuschauer nicht. Die fehlende Fähigkeit zum Lesen und Schreiben hat sie in die Arme der SS getrieben und dient somit als Ausrede - sie hat immer nur ihren Job erledigt. Doch gleichzeitig führt sie schließlich dazu, dass Hanna als Anführerin der sechs angeklagten Aufseherinnen verurteilt wird und so zumindest eine Strafe für ihre Taten absitzen muss. Ein individueller Grund, das Regime mitzutragen, führt zu einer individuellen Verurteilung. Und gegen Ende stellt Ilana Mather, die als einzige der Jüdinnen unter Hannas Aufsicht überlebt hat, klar, dass es keine noch so individuelle Entschuldigung gibt für die Greueltaten der Nazis.

Und damit eigentlich für das gesamte deutsche Volk, das beteiligt war am Genozid oder zumindest weggesehen hat. Jeder hatte seine ganz privaten Gründe, das System zu unterstützen; das deutsche Volk war die Basis des Nationalsozialismus. Dasselbe Volk, dass in den sechziger Jahren einen Prozess gegen sechs Frauen führt, weil es eine Überlebende gibt, die anklagen konnte. Da ist die Frage eines Kommilitonen von Michael berechtigt, ob dies nicht nur eine Scheingerechtigkeit ist und wie es ein Volk schaffen konnte, nach 1945 einfach weiterzumachen, als sei nichts passiert. Die Frage nach den Sünden der Väter der ersten Nachkriegsgeneration wird schließlich zu den 68er Studentenunruhen führen, doch dies zeigt der Film nicht mehr.

Vielmehr verfolgt Stephen Daldry weiter den Stil der Individualisierung der Probleme am Beispiel seiner Hauptfiguren. Er zeigt Hanna, wie sie im Gefängnis Lesen und Schreiben lernt und dann kurz vor ihrer Entlassung den Freitod wählt. Sie macht so den Weg frei für eine späte Sozialisation von Michael, dem sie nie schaden wollte, sondern auf gewisse Weise ausnutzte und aufgrund seines jungen Alters unbewusst formte. Ob Kate Winslet ausgerechnet für diese Rollen den Oscar verdiente mag ich nicht entscheiden, aber in ihrer Darstellung der sichtbar gealterten Hanna gibt sie ihrer Rolle genau die richtige Dosis Weiblichkeit um zu verstehen, dass Michael von ihr angezogen ist, während ihre spröde Art die Unsicherheit und Eitelkeit verstecken soll. Dabei blitzt immer wieder eine gewisse Intelligenz und Durchsetzungskraft hervor, die jedoch von den anderen Eigenschaften meist verdrängt wird.

Beeindruckt hat mich die Darstellung der fünfziger und sechziger Jahre, seien es die Kostüme oder Kulissen. Die Wohnung von Hanna, die im Gegensatz zum gutbetuchten bürgerlichen Haushalt von Michaels Eltern nur aus einem Raum mit Küchenecke, Badewanne und Bett besteht, wirkt ebenso authentisch wie die Darstellung von Michaels Studium mit Wohnheimen in der typischen deutschen Nachkriegsarchitektur und dem im Hörsaal rauchenden Professor (hervorragend: Bruno Ganz). Dagegen fällt negativ auf, dass alle Bücher und die Briefe zwischen Michael und Hanna auf englisch sind, obwohl die komplette Handlung in Deutschland spielt. Damit wird der gute Eindruck der Kulissen gleich wieder zerstört.

Fazit: *Der Vorleser* ist eine gut gespielte und ausgestattete Auseinandersetzung mit dem Thema Schuld und Sühne des deutschen Volkes, erzählt an Hand von individuellen Schicksalen. Die gut aus der Romanvorlage übernommenen Charakterbilder tragen den Film und so hinterlässt diese Mischung aus Zeitgeschichte und Beziehungsdrama einen bleibenden Eindruck.
