---
title: "Stolperstufen auf dem Weg zu einem neuen Urheberrecht"
date: "2006-03-22T17:57:10"
categories: [gedacht,gefunden]
---

Viel kann man heute sehen/lesen/hören über den endlich verabschiedeten [Regierungsentwurf für die zweite Stufe der Urheberrechtsnovelle](http://www.bundesregierung.de/-,413.976986/artikel/Privatkopien-bleiben-erlaubt.htm). Viel ändern tut diese zweite Stufe aber nicht, vielmehr werden bisher offene Lücken geschlossen, welche bei der Umsetzung der europäischen Vorgaben in der ersten Stufe zum neuen Urheberrecht entstanden bzw vorgesehen sind.

Ein wichtiges Detail ist aber, dass künftig nicht nur das Anbieten illegal erstellter Kopien strafbar ist, sondern auch die Nutzung solcher Angebote, wenn "es offensichtlich ist, dass es sich um ein rechtswidriges Angebot" handelt. Also sind künftig auch die meisten Downloads in Filesharing-Netzen definitv nicht mehr erlaubt. Dabei macht es sich die Regierung jedoch einfach, indem sie davon ausgeht, dass jede in einer Tauschbörse verfügbare Mediendatei mit einer kommerziellen Lizenz geschützt ist und der gemeine Internetnutzer deshalb sofort in der Lage ist, dies zu erkennen. Das vom [Bundesministerium für Justiz genannte Beispiel](http://www.bmj.bund.de/enid/5ff8f65e11cf75464d8499cb160fb45d,6b1c11707265737365617274696b656c5f6964092d0932343031093a096d795f79656172092d0932303036093a096d795f6d6f6e7468092d093033093a095f7472636964092d0932343031/Presse/Pressemitteilungen_58.html) zeigt dies deutlich:

> Kein privater Internetuser verfügt über die Rechte zum Angebot eines Kinofilms im Internet. Ein Download eines Kinofilms aus Peer-to-Peer-Tauschbörsen ist also offensichtlich rechtswidrig.

Bei Kinofilmen mag dies ja noch in 99,9% der Fälle stimmen (es gibt bereits lizenzfreie bzw. mit einer Lizenz zur Verbreitung ausgestattete Filme), aber schon bei Musikdateien gibt es immer mehr Angebote im Netz, bei denen die Künstler ihre CD-Verkäufe durch die Verbreitung von einzelnen kostenfreien Songs im Netz ankurbeln - Tendenz steigend. Bei Schriftwerken ist das Chaos dann vorprogrammiert, da diese oftmals in verschiedenen Formen und auf unterschiedlichen Medien getrennt veröffentlicht werden. So vielfältig die neue digitale Welt ist, so komplex ist sie auch vom Recht abzudecken. In dieser Hinsicht hat der neue Entwurf die Grauzone zwischen legal und illegal nur verschoben.

Die Privatkopie bleibt weiterhin nur dann ein Recht des deutschen Bürgers, wenn er bei dessen Umsetzung (also beim Kopieren der erworbenen Werke) keine Kopiersperre umgeht. Damit liegt dieses Recht in Zukunft in der Hand der Urheber (bzw deren Verwerter) und sollte deshalb aus meiner Sicht nicht Recht genannt werden. Trotzdem müssen die Verbraucher auch weiterhin bei Geräten und Medien, welche zur Herstellung von Kopien genutzt werden können, eine "Pauschalvergütung als gerechten Ausgleich für die Privatkopie" abtreten, ohne dass ihnen dafür überhaupt ein einklagbares Recht auf eine Privatkopie zugestanden wird - verrückte Welt!

Die sogenannte "Bagatellklausel" hat es aber nicht die Gesetzesnovelle geschafft. Darin sollte die Praxis der Staatsanwaltschaften, geringfügige Verstöße wie seltenes illegales Filesharing strafrechtlich nicht zu verfolgen, als Standard übernommen werden. Dies ist nun zwar nicht geschehen, aber auch in Zukunft können die Staatsanwälte nicht wegen jedem einzelnen Filesharer eine Gerichtsverfahren eröffnen und werden deshalb an dieser Praxis festhalten. Was aber im Umkehrschluss nicht bedeutet, dass diese Vergehen legalisiert werden und es gar keine Verfahren mehr gibt - schließlich kann auch der private Raubkopierer mit bis zu drei Jahren Haft bestraft werden.

Zu guter Letzt hat es die CDU nun geschafft, den Weg der öffentlichen Bibliotheken in die digitale Welt von den Angeboten der Verwerter abhängig zu machen. Sie dürfen zwar von allen ihren Werken digitale Kopien erstellen, die Weitergabe innerhalb der Wissenschaft ist aber nur möglich, wenn es kein kommerzielles Angebot für das Original gibt. Da die Verwerter gerne Mondpreise für einfache digitale Kopien verlangen, wird also auch weiterhin viel Literaturarbeit mit der guten alten analogen Kopie betrieben. Manchmal habe ich das Gefühl, für die CDU sind die Interessen der privaten Wirtschaft wichtiger als eine öffentliche Forschung, die man angeblich fördern will.

Fazit: Viel ist nicht passiert in der zweiten Stufe der Urheberrechtsnovelle, vielmehr wurden hauptsächlich bisherige Ansichten der Regierung und die z.T. schon vorhandene Rechtssprechung in das Gesetz übernommen. Lücken, Grauzonen und Widersprüche gibt es auch weiterhin und die Regierung hat wenig Mut gezeigt, in dem ständigen Streit zwischen Nutzern und Urhebern/Verwertern die eigenen legislativen Freiheiten zu nutzen und eindeutige Vorgaben für ein gemeinsames Miteinander zu schaffen. So werden sich auch weiterhin beide Seiten öfters einmal vor Gericht treffen, um einen Ausgleich für die sich überschneidenden Rechte zu finden.

<ins datetime="2006-03-22T17:18:32+00:00">Update: Etwas mehr Mut [beweisen die Franzosen](http://www.heise.de/newsticker/meldung/71123). Dort müssen künftig alle Hersteller von DRM-Systemen sicherstellen, dass ihre Systeme interoperabel ist, damit alle Verbraucher ihre erworbenen Medien auf allen dafür vorgesehenen Playern abspielen können. Dies läuft entweder auf Player hinaus, die alle DRM-Standards unterstützen, oder auf ein einziges Standardsystem, welches von allen Playern und Contentanbietern genutzt wird. Sollte diese Interpretation richtig sein, könnte dies auch positive Auswirkungen auf andere Länder haben, da die meisten Konzerne ihre Produkte mittlerweile global anbieten. Doch da bin ich bestimmt zu optmistisch; erst einmal bleibt abzuwarten, ob dieses Gesetz in Frankreich überhaupt angenommen wird.</ins>
