---
title: "Seven Wonders"
date: "2012-10-27T13:01:49"
categories: [gespielt]
---

Heute möchte ich eine Kombination aus Brett- und Kartenspiel vorstellen, die mir gestern einen sehr unterhaltsamen Spieleabend beschert hat. [Seven Wonders](http://de.wikipedia.org/wiki/7_Wonders) ist im weitesten Sinne ein Aufbauspiel, bei dem die durch die sieben Weltwunder repräsentierten Kulturen gegeneinander antreten, um die fortschrittlichste unter ihnen zu bestimmen. Diesen Titel erhält am Ende der Spieler, welcher die meisten Siegpunkte gesammelt hat.

Siegpunkte gibt es für verschiedene Leistungen: Den Ausbau des eigenen Weltwunders und anderer Monumente, militärischen Erfolg gegen die Nachbarkulturen, wirtschaftlicher Erfolg im Handel mit anderen, einen großen Vorrat an natürlichen Rohstoffen und den Entwicklungsgrad der eigenen Wissenschaften. Alle diese Leistungen sind im Spiel als Karten abgebildet. In drei Zivilisationsstufen (= Ausbaustufen der Karten = Runden) werden jeweils sieben Karten zufällig an alle Spieler verteilt. Jeder Spieler sucht sich davon eine Karte aus, die er dann sofort spielt, und danach werden die Karten an den Nachbarn weitergegeben.

Jede Karte verbraucht Resourcen, die die Kultur entweder selber aufbringen muss (über Resourcenkarten) oder sich bei den direkten Nachbarn für bare Münze einkaufen kann. Ist eine Karten ausgelegt, hat sie meist einen sofortigen Effekt (Einnahme von Goldmünzen), manchmal einen dauerhaften Effekt (preiswerter Handel mit einem Nachbarn) und schließlich einen Einfluss auf die Siegpunkte.

Die Kartenstapel wandern solange von einem Spieler zum nächsten, bis nur noch eine Karte übrig bleibt. Dann ist eine der drei Runden beendet, es wird Krieg geführt zwischen den Nachbarkulturen und der Aufstieg in die nächste Zivilisationsstufe (sprich Runde) erfolgt. Ganz zum Schluss wird zusammengezählt und der aufgrund der komplexen Wechselwirkungen einiger Karten nicht immer sofort erkennbare Sieger rechnerisch ermittelt.

Diese Schwierigkeit, zu erkennen, wer gerade die meisten Siegpunkte besitzt, ist eine Stärke des Spiels. Denn dies kann sich jede Runde ändern und die Strategien der direkten Nachbarn können einen großen Einfluss auf die eigene Spielausrichtung haben. Die eine zielführende Strategie gibt es dabei nicht, sowohl das Setzen von Schwerpunkten als auch das Bauen in die Breite kann am Ende den winzigen Ausschlag zum Sieg geben.

Da jeder Spieler eigentlich nur mit seinen beiden direkten Nachbarn in Kontakt ist, ob es nun Handel oder Krieg ist, muss nicht der gesamte Tisch ständig überblickt werden. Dabei ist es schon sinnvoll zu schauen, wem eine Karte eventuell nützen würde, die an den nächsten Spieler weitergegeben wird. So sind die Optionen des eigenen Handelns zwar beschränkt, da jeder Spieler immer nur die Wahl zwischen maximal sieben Karten hat. Trotzdem ergeben sich mit jeder Karte neue, spannende Situationen.

Die Karten eines Spielzugs können immer gleichzeitig von allen Spielern ausgespielt werden, da die Situation vor dem Spielzug maßgeblich dafür ist, ob ein Spieler die benötigten Resourcen für das Auslegen der Karte überhaupt besitzt. Dadurch ist ein Spiel relativ schnell zu Ende (wir haben jeweils knapp eine Stunde benötigt), denn lange Wartezeiten auf einzelne Parteien, die das gesamte Spiel aufhalten, entfallen.

Was wirklich Spaß macht an *Seven Wonders* ist die Ungewissheit, ob sich die eigene Strategie wirklich auszahlt. Durch die Interaktionen mit den Nachbarn muss ständig umgeplant werden, was zu jedem Zeitpunkt des Spiels tatsächlich möglich ist. Etwas Kartenglück gehört zwar dazu, aber auch kleine "Fehler" können sich später als Glück herausstellen - das Balancing des Spiels ist aus der Erfahrung von fünf Runden sehr gut gelungen. Es gibt keine übermächtigen Karten, für jede Strategie des Nachbarn gibt es Optionen, sie zum eigenen Vorteil auszunutzen. Deshalb erhält *Seven Wonders* nicht nur eine klare Empfehlung von mir, sondern ich werde es mir sogar selber zulegen.
