---
title: "Moon"
date: "2009-08-30T17:14:24"
categories: [gesehen]
---

*UK (2009)
Regie: Duncan Jones
Darsteller: Sam Rockwell (Sam Bell), Sam Rockwell (Sam Bell) und Sam Rockwell (Sam Bell)*
[Offizielle Homepage](http://www.moon-movie.com/)

Das Energieproblem der Menschheit hat in der Zukunft eine Lösung gefunden. Riesige Maschinen "ernten" auf der Mondoberfläche die von der Sonne aufgenommene Energie und nur ein einziger Mensch ist für die Wartung notwendig. Sam Bell hat sich für drei Jahre verpflichtet, diesen Job zu übernehmen. Drei Jahre Einsamkeit, nur unterbrochen durch Nachrichten, die er mit Frau und Kind auf der Erde austauscht, und der Konversation mit dem Stationsroboter Gerry. Doch kurz vor dem Ende seines Drei-Jahres-Dienstes geht es Sam immer schlechter, er sieht plötzlich überall Bilder seiner Frau und baut schließlich außerhalb der Basis einen Unfall im Mondbuggy und wird dabei bewusstlos. Als er wieder aufwacht, liegt er auf der Krankenliege in der Basis und kann sich an nichts erinnern, doch Gerry versucht mit allen Mitteln, ihn am Verlassen der Station zu hindern...

Wer diesen Film noch sehen möchte, der sollte jetzt besser aufhören mit lesen, denn in der Betrachtung des Inhalts werde ich die wichtigsten Handlungs- und damit Überraschungselemente vorwegnehmen. Allerdings ist bis jetzt kein deutscher Verleiher und damit kein Starttermin in Sicht, so dass sich das Problem relativiert; ich selber habe die Chance genutzt und *Moon* in der Originalfassung auf dem [Fantasy Film Fest](http://www.fantasyfilmfest.com/fantasy/filme2009/Moon.html) angesehen.

Der Film ist eine Auseinandersetzung mit der (noch) utopischen Vision von menschlichen Klonen. Dabei geht es weniger darum, wie ähnlich diese dem Original sind, obwohl auch dieses Thema behandelt wird, sondern vielmehr um den Umgang mit ihnen. Haben Klone dieselben Rechte wie die Menschen oder sind es programmierte Wesen ähnlich Computern und Robotern?

Als Mittel für diese Diskussion dienen zwei Klone des Astronauten Sam Bell, die sich durch ihre doppelte Anwesenheit ihrer geklonten Natur bewusst werden. Dabei sind ihre Reaktionen durch und durch menschlich, schließlich sind sie ja auch Klone mit ausgewählten Erinnerungen ihres Schöpfers. Doch ist es menschlich, ihnen aus Konzerninteressen eine falsche Realität vorzugaukeln und sie mit einem Ablaufdatum zu versehen? Als Kopie eines Menschen sollten sie eigentlich mehr Rechte haben als zum Beispiel der Stationsroboter Gerry, der wiederum programmiert wurde, ihnen die Wahrheit vorzuenthalten.

Dabei zeigt der Film immer wieder auf, dass die Klone dem Roboter überlegen sind. Sieht man ihm anfangs noch beim ausweichenden Antworten und assoziiert Ähnlichkeiten zu [HAL](http://de.wikipedia.org/wiki/HAL_9000) und [Mutter](http://de.wikipedia.org/wiki/Alien_–_Das_unheimliche_Wesen_aus_einer_fremden_Welt), so wird mit zunehmender Filmdauer klar, dass er kein Logikduell gewinnen kann. Durch das Angebot der Selbstabschaltung am Ende erscheint er ganz im Gegenteil äußerst human. Ihm fehlt jedoch der menschliche Wille der Klone, der Situation zu entfliehen.

An dieser Stelle zeigt der Film schön die Doppelmoral. Durch die Flucht eines Klones auf die Erde wird der unmenschliche Umgang mit ihnen auf der von aller Welt abgeschnittenen Mondstation öffentlich gemacht und führt zu einer Debatte über das Thema. Über Gerry den Stationsroboter wird jedoch nicht geredet. Er ist ähnlich programmiert wie die Klone, zeigt ebenfalls menschliche Gefühlsregungen, darf jedoch nicht auf die gleichen Rechte wie seine Schöpfer hoffen.

Eingebettet ist diese Diskussion leider in einem leidlich spannenden Film. Es ist schon witzig, Sam Rockwell in seinen beiden Rollen zu sehen und die Tricktechnik ist trotz der geringen Budgets sehr überzeugend, aber die Handlung plätschert nur so vor sich hin. Alle Wendepunkte werden wiederholt ausgiebig in Dialogen nachvollzogen, so dass man sich als Zuschauer durchaus das eine oder andere Nickerchen gönnen kann, ohne etwas wichtiges zu verpassen.

Fazit: *Moon* ist ein nettes SciFi-Filmchen, in dem es um die Auseinandersetzung mit dem Thema Klonen und die Rechte eines zwar programmierten, aber dennoch menschlichen Wesens geht. Leider versinkt der vielversprechende Ansatz in vielen Wiederholungen und einer zu sehr gedehnten Handlung ohne große Spannungselemente, so dass der Film nicht vollends überzeugen kann.
