---
title: "Ja wo fahren sie denn?"
date: "2007-07-19T20:43:40"
categories: [gedacht]
---

In [Frankreich](http://www.letour.fr/), so viel ist klar. Doch im deutschen Fernsehen hat seit gestern der Familiensender Nr.1, [Sat.1](http://www.sat1.de/sport/sportnews/news/content/22917/), die Übertragung übernommen. Und weil Fußball doch wichtiger ist, darf Schwester [Pro7](http://www.prosieben.de/show_comedy/artikel/41670/) am Samstag das Einzelzeitfahren übertragen.

Doch wie kommen die beiden bekannten Sportsender zu der Ehre? Schuld ist Patrik Sinkewitz, der ~~einen Zuschauer angefahren hat~~ sich anscheinend beim Dopen hat erwischen erlassen. Und weil die öffentlich-rechtlichen Fernsehkanäle wie niemand sonst in Deutschland für [Ehre](http://de.wikipedia.org/wiki/Jürgen_Emig) und sauberen Sport stehen, haben sie natürlich sofort wie vorher angekündigt die Übertragung eingestellt.

Um der Tour der France und dem im Dopingsumpf sich windenden Radsport zu zeigen, wo die Harke hängt. Schade nur, dass dies auch ohne die [ProSiebenSat.1 Media AG](http://www.prosiebensat1.com/pressezentrum/sat1/2007/07/19/25771/) so gut wie keine Auswirkungen gezeigt hätte: Eurosport überträgt weiterhin, und das Geld der deutschen Gebührenzahler bleibt trotz Boykott auf den französischen Konten. Nur wer die [2,6 Millionen Euro pro Jahr für die Übertragungsrechte](http://www.manager-magazin.de/sport/sonst/0,2828,495515,00.html) nicht selber erwirtschaften muss, kann sich solche Aktionen leisten.

Und dann - Überraschung - hat sich sofort noch ein [Sublizenznehmer](http://www.taz.de/index.php?id=start&art=2120&id=497&cHash=9ad3d53c34) gefunden, der aber für die zurückgegebenen Rechte mitnichten an ARD & ZDF zahlt, sondern [an die Tourorganisation](http://www.faz.net/s/RubF773C8143FEC460E8B21A3FC11EEFA68/Doc~ED412610F06604A6B83AB76882C79190F~ATpl~Ecommon~Scontent.html). Diese verdient also doppelt am Ausstieg der Öffentlich-Rechtlichen.

Vielleicht war man aber auch nur froh über den willkommenen Dopingfall - die [Einschaltquoten](http://www.digitalfernsehen.de/news/news_175856.html) hielten sich jedenfalls in Grenzen, und die [Werbeblöcke verkauften sich dieses Jahr auch schlecht](http://www.dwdl.de/article/news_11554,00.html).
