---
title: "Der Polarexpress"
date: "2005-12-28T23:02:34"
categories: [gesehen]
---

Jedes Jahr zu Weihnachten versucht mindestens ein Film, mit einer Adaption des Weihnachtsmann-Themas vor allem Familien in die Kinos zu locken. Letztes Jahr war dies nun "der Polarexpress", welcher außerdem damit werben konnte, als im Computer generierter Animationsfilm Tom Hanks für eine Rolle gewonnen zu haben. Dieser wurde originalgetreu nachmodelliert und sein Charakter auch von ihm selber bzw. von seinem Synchronsprecher gesprochen. Lobenswert an der deutschen Fassung ist außerdem, dass alle lesbaren Schriftzüge im Film eingedeutscht wurden.

Für die Zweitverwertung auf DVD warteten die Produzenten nun bis dieses Weihnachten, wo sie einen höheren Absatz als zu Ostern erhofften. Ich hatte nun das mehr oder weniger freiwillige Vergnügen, mir die DVD-Fassung am zweiten Weihnachtsfeiertag anzusehen.

Die Handlung versucht sich an einer neuen Variation der typischen Geschichte: Junge glaubt nicht an den Weihnachtsmann und wird am Ende eines Besseren belehrt. Dies geschieht diesmal in einem Zug, welcher eine kleine Anzahl von Kindern zum Nordpol bringt. Warum, wird nicht geklärt, und die Auswahl der Kinder erlaubt auch keine Rückschlüsse auf die Gründe der Wahl.

Sei es drum, jetzt kommt der fantasievolle Teil des Films. Die Bahn muss so manches Hinderniss auf dem Weg zum Nordpol überwinden und nicht alles im Zug verläuft auf gewohnten Schienen. Die Abenteuer der Hauptperson (einer von vielen Tom-Hanks-Charakteren) sind aufregend und lustig und stecken voller Ideen.

Doch dann folgt die Ankunft am Nordpol und plötzlich geht dem Film die Puste aus. Langweiliger hätte man sich die Weihnachtsmannwerkstatt nun wirklich nicht vorstellen können, aber Amerika liebt scheinbar große Logistikfilialen und jubelnde Menschenmengen. Und als wäre dies nicht genug, muss die Moralkeule nun im Minutentakt geschwungen werden (Glöckchen, Fahrkarte). Sollen Kinder mit dieser Art von Film wirklich überzeugt werden, dass es den Weihnachtsmann gibt?

Ebenso wie das Drehbuch können auch die Animationen nicht ganz überzeugen. Landschaft und Gegenstände sehen zwar sehr nett aus, aber Menschen und Tiere besitzen zu wenige Details, um realistisch zu wirken. Sogar der Schaffner ist mehr durch seine Stimme, als durch seine Gesichtszüge als Tom Hanks zu erkennen. Auf der anderen Seite ist dies immer noch ein Trickfilm, so dass den Kindern als Zielpublikum diese Schwäche wohl nicht auffallen wird.

Fazit: "Der Polarexpress" hätte ein netter Kinderfilm werden können, aber leider gehen ihm zwischendurch die Ideen aus und es wird zu viel Moral serviert. Da gibt es doch weitaus bessere Weihnachtsfilme ohne amerikanische Wertvorstellungen!
