---
title: "Ladykillers"
date: "2004-07-28T00:00:24"
categories: [gesehen]
---

*USA (2003)
Regie: Joel und Ethan Coen
Darsteller: Tom Hanks (Prof. Goldthwait Higginson Dorr), Irma P. Hall (Mrs. Munson), Marlon Wayans (Gawain MacSam), J.K. Simmons (Garth Pancake), Tzi Ma (der General), Ryan Hurst (Lump), George Wallace (Sheriff Wyner), Diane Delano (Mountain Girl), John McConnell (Deputy Sheriff) und andere Südstaatler...*
[Offizielle Homepage](http://www.movie.de/filme/ladykillers/)

Die streng gläubige schwarze Witwe Mrs. Munson staunt nicht schlecht, als sich ein Professor bei ihr vorstellt um ein Zimmer zu mieten und mit seinen vier Freunden im Keller als Ensemble Renaissance-Musik zu spielen. In Wirklichkeit planen die fünf jedoch einen Tunnel bis zu den Tresoren eines Casinos zu graben und diese leer zu räumen. Trotz einiger Pannen gelingt dieses Unterfangen schließlich auch, doch die Vermieterin hat inzwischen Verdacht geschöpft und so plant die Bande, die alte Dame aus dem Weg zu räumen...

Kein ganzes Jahr ist es nun her, seit die Coen-Brüder ihren letzten Film in die deutschen Kinos brachten. Reichlich wenig Zeit für einen qualitativ hochwertigen Film, mag der Kinobesucher denken. Dank der Freikarten für die Vorpremiere konnte ich mir nun selber ein Bild machen, ob sich das Remake des englischen Klassikers des schwarzen Humors "Ladykillers" in die Reihe der zuletzt eher mäßigen Coen-Filme ([The man who wasn't there](/blog/2002/01/07/the-man-who-wasnt-there/), [Ein (un)möglicher Härtefall](/blog/2003/10/29/ein-unmoglicher-hartefall/)) einreiht oder eine Rückkehr zu alten Qualitäten darstellt.

Ungewöhnlich neben der Arbeit nach einer Vorlage ist für die Coens diesmal auch der Verzicht auf bekanntes Personal - keiner der vielen Spezis bekam auch nur einen kurzen Auftritt. Dafür wurde mit Tom Hanks ein Hollywood-Star verpflichtet, der zumindest mit "Forrest Gump" schon Komödien-Talent bewiesen hat - denn auch das Remake von "Ladykillers" bleibt eine schwarze Komödie, zumindest ganz am Ende. Bis dahin plätschert der Film mehr vor sich hin, als dass er Spannung oder Geschwindigkeit aufbaut. Passend zu der Umgebung des schwülen Missisippi werden in aller Seelenruhe die Charaktere des Films vorgestellt, ohne dass der Zuschauer überhaupt weiß, was es mit diesen auf sich hat. Dabei wird jedoch sofort klar, dass Tom Hanks nicht gerade die Idealbesetzung für den skurilen Professor ist. Er übertreibt es etwas mit der Mimik und lässt die Figur sehr unglaubwürdig erscheinen; das verrückte Lächeln wirkt eher aufgesetzt als eine Marotte und als Kopf der Bande kann er nicht überzeugen. Dies wiederum greift aber das übliche Thema der Coen-Filme auf: Ein Plan, der mit der Zeit vollkommen aus dem Ruder und aus der Kontrolle der handelnden Personen läuft und schließlich im Fiasko endet. In wie weit dies auch dem original "Ladykillers" entspricht kann ich leider nicht sagen, da ich den Film (zumindest im letzten Jahrzehnt) nicht gesehen habe.

Auf jeden Fall ist die Entwicklung entlang dieses Handlungsschemas den Coen-Brüdern diesmal mehr als misslungen. Die Steitereien zwischen Gawain und Garth sind ziemlich altbacken inszeniert, der gelungene Raubzug spart sich jede Spannung aus, der Verlust des Fingers mündet in sorgsam kalkuliertem und deshalb kaum realen Chaos (wenngleich die Diskussion um den Gefahrenzuschlag und des Generals Jagd auf Pickles mit dem Finger doch recht humorig sind) und die Witze um den Reizdarm und HipHop-Musik können nur mit Mühe als solche identifiziert werden. Dazu hat mich der Soundtrack gelinde gesagt ganz schön genervt. Ständige Gospelmusik mag ja zu der Umgebung passen, aber welchen Sinn die recht langen Kirchenszenen für die Handlung haben wollte mir nicht klar werden (da war die Musik in "Oh Brother where are thou" doch deutlich stimmiger). Insgesamt herrscht wenig Harmonie in Sachen Kulissen und Charakterzusammenspiel, so dass die gesamte erste Stunde des Filmes zum Gähnen langweilig ist.

Doch dann kommt doch noch der nicht mehr erwartete Umschwung. Mit der verloren geglaubten Souveränität (und fast schon zu schnell) wird nun der Abgang der fünf Schmalspurganoven von den beiden Regisseuren zelebriert und es fügen sich alle Bruchstücke zusammen, inklusive dem ständigen Edgar-Allen-Poe-Rezitieren des Professors und es endet schließlich alles wie es begann: Auf dem good old river Missisippi, genauer gesagt auf einer surrealen Müllkippeninsel im großen Strom.

Fazit: Was die Coen-Brüder auszeichnet, nämlich den schwarzen Humor, bekommt man erst am Ende des Filmes zu sehen; bis dahin muss man sich als Kinobesucher durch den Film quälen, der einige Fehler in Besetzung, Charaktere und Spannungsbogen aufweist. Der insgesamt schlechteste aller Coen-Filme!
