---
title: "Final Fantasy - Die Mächte in Dir"
date: "2001-08-23T00:00:00"
categories: [gesehen]
---

*Japan/USA (2001)
Regie: Hironobu Sakaguchi
Stimmen im Original: Ming Na (Aki Ross), Alec Baldwin (Gray Edwards), Donald Sutherland (Doktor Sid), James Woods (General Hein), Ving Rhames (Ryan Whittaker), Peri Gilpin (Jane Proudfoot), Steve Buscemi (Neil Fleming) bzw. deren deutsche Synchronstimmen*
[Offizielle Homepage](http://www.final-fantasy-der-film.de)

Die Zukunft, das Jahr 2065. Nach der Invasion einer außerirdischen Zivilisation lebt die Menschheit zurückgezogen in verschiedenen Arealen auf der Erde, verzweifelt gegen ihr Ende ankämpfend und nach einer Waffe forschend, die die Invasoren bezwingen kann. Dr. Sid hat dabei eine neue Theorie entwickelt, in der es um die sogenannten Spirits geht, die jedes Lebewesen und jeder Gegenstand besitzt und deren Zusammenführung die einzig mögliche Rettung scheint. Die junge Assistentin Aki Ross, die seit einem Angriff einen Außerirdischen in sich trägt, macht sich auf die Suche nach den 7 Spirits um ihr Leben zu retten, während die Armee unter Führung von General Hein auf den Einsatz der mächtigsten je entwickelten Waffe drängt, welche jedoch auch Gaia, also die Erde selber, zerstören könnte...

Als realistischster Animations-Film, der jemals im Computer entstanden ist, angepriesen, sollte dieser Film auch eine interessante Story um die 7 Spirits bieten. Doch leider wurden die Geschichte und die Charaktere viel zu eindimensional angelegt und sind die Ereignisse viel zu vorhersehbar; am Ende widerspricht sich der Film sogar selber - aber was sollte man auch anderes von einem Anime erwarten. 

Also bleibt die Technik. FF ist auf jeden Fall der realistischste Trickfilm, der je im Computer geschaffen wurde, aber wirklich real wirkt er auf die Dauer des Films nicht. Am Anfang überlegt man immer noch, doch mit der Zeit werden die Szenen immer zeichentrickartiger; die Anime-Verwandtschaft läßt sich nicht so leicht leugnen. Auch die Charaktere wirken bei Nahbetrachtung künstlich - was nützen 60000 animierte Haare, wenn die Frisur auch nach den größten Anstrengungen aussieht, als käme Aki gerade vom Friseur?!

Fazit: Für Fans der Anime und computergenerierter Filme bietet Final Fantasy eine Menge, alle anderen müssen entscheiden, ob eine mittelmäßige Story und einige Aha-Erlebnisse am Anfang des Films den Eintrittspreis rechtfertigen!
