---
title: "EU bestätigt: It always rains on me"
date: "2008-09-25T18:50:59"
categories: [gedacht,gefunden]
---

~~Amerikanische Wissenschaftler haben~~ [Die EU hat](http://www.mz-web.de/servlet/ContentServer?pagename=ksta/page&atype=ksArtikel&aid=1222235479134&calledPageId=987490165154) herausgefunden, dass meine Heimatstadt Halle unter 258 untersuchten europäischen Städten im Jahr 2004 die absolut meisten Regentage hatte. Und diese Statistik führt Halle überraschenderweise vor Köln und den dort erwarteten Städten von den britischen Inseln an.

Kein Wunder, dass ich eine eher depressive und negative Lebenseinstellung habe. Erst zu DDR-Zeiten [keine Farben außer Grau](http://www.3sat.de/3sat.php?http://www.3sat.de/kulturzeit/specials/68317/index.html) kennengelernt, und dann auch noch selten die Sonne gesehen. Auf der anderen Seite sollte ich mich an den Regen gewöhnt haben und damit umgehen können, was definitiv nicht der Fall ist.

Was unsere Regionalzeitung natürlich nicht erwähnt, ist eine weitere Nennung von Halle in der zitierten [Studie](http://www.europa-kommissionen.dk/upload/application/7fddfa81/ks-sf-08-082-en.pdf). Unter den am stärksten vom Bevölkerungsrückgang betroffenen Städten der Jahre 1999-2004 belegt die Saalestadt den neunten von wieder 258 Plätzen. Die [Abwanderung](http://www.stadtentwicklung-sachsen-anhalt.de/inhalt/situation/) ist also leider immer noch nicht gestoppt; ich selber bin ein Beispiel dafür. Auf der anderen Seite muss man aber auch wissen, dass der Halle komplett umgebende Saalekreis eine der [deutschlandweit am stärksten wachsenden Regionen](http://www.berlin-institut.org/fileadmin/user_upload/Deutschland_2020/sachsen_anhalt.pdf) ist - die Menschen bleiben also in der Region und ziehen nur in die die Stadt umgebenden Dörfer. Und im Gegensatz zu anderen Städten durfte Halle auch nicht eingemeinden. Das Land hält Halle damit künstlich klein und so erscheint die Stadt eben in Statistiken, in die sie eigentlich nicht hineingehört. Wie sagt man so schön: [Traue keiner Statistik, die Du nicht selbst gefälscht hast](http://de.wikipedia.org/wiki/Liste_geflügelter_Worte/T#Traue_keiner_Statistik.2C_die_du_nicht_selbst_gef.C3.A4lscht_hast.)!
