---
title: "It's a bug in the traffic lights "
date: "2008-01-28T22:22:28"
categories: [gedacht]
---

Manchmal kann ich sehr ungeduldig sein. So zum Beispiel jeden Morgen, wenn sich auf dem Weg zur Arbeit die Straßenbahn verspätet. Bei meiner täglichen Wegstrecke bedeuten 10min Wartezeit schon 40% Aufschlag auf die Gesamtfahrtzeit. Heute morgen hatte ich diese 10min Zeit, um ausgiebig die Ampelschaltungen an der Kreuzung Petersburger Straße / Landsberger Allee zu beobachten, denn meine Bahn stand auf der anderen Kreuzungsseite und wartete auf ihre Grünphase, die einfach nicht kam.

Ursache ist ein *Feature* der Ampelanlage: Eine Straßenbahn kann sich ihre Grünphase "klauen", ohne auf die reguläre Schaltung zu warten. Dabei steht die gesamte Ampelkreuzung auf Rot und die Tram bekommt eine exklusive Genehmigung zur Überfahrt. Genutzt wird dies hauptsächlich von der aus meiner Perspektive querenden und deswegen uninteressanten Linie M10. Dass es volkswirtschaftlich gar keinen Sinn ergibt, eine der wichtigsten Berliner Ausfallstraßen und eine Bundesstraße zu sperren, damit eine Bahn 30s Zeit gewinnt, ist die eine Seite. Aber dass dieses *Feature* nicht richtig umgesetzt wurde, ärgert mich wirklich. So lange die Bahn nämlich dieses Exklusivrecht nicht nutzt, erhält keine andere Tram grünes Licht. Und als wäre das nicht genug, bekommt nach dem Nutzen der Sperrung die dazu kreuzende Straßenbahn eine gesamte Ampelphase lang ebenfalls keine Fahrgenehmigung. Heute morgen kamen so fast 10min zusammen, in denen sich vier Bahnen an der Kreuzung aufstauten.

Naja, genug gemotzt - Berlin hat genügend andere Probleme, als einen Bug in einer Ampelkreuzung zu fixen. Und ich kann weiter meine Wartezeiten mit der Analyse der Ampelschaltungen verkürzen...
