---
title: "CampusParty 2008"
date: "2008-06-29T13:21:27"
categories: [gehört,gewesen]
---

Zugegeben, etwas alt habe ich mich schon gefühlt, als ich am 18. Juni zwischen diversen Abi-T-Shirts des Abschlussjahrgangs 2008 auf der Dresdner CampusParty stand. Doch trotz der inzwischen über zwei Jahre, die mein letztes Uni-Semester zurückliegt, war ich zum Glück nicht allein unter den Vollpreiszahlern.

Der Campus der Physik und Chemie der TU Dresden stellte sich als hervorragend geeignet für ein Konzert heraus. Eine lange, von Bäumen gesäumte Rasenfläche, in die bis zu ihrem Untergang die Sonne hineinschien, ließen ausreichend Platz für die vielen Besucher der CampusParty und in den Innenhöfen der angrenzenden Uni-Gebäude konnten sich die Sponsoren so richtig breit machen. Bei einer Tochterfirma der Sparkasse konnte man Tischtennis spielen und die Firma Jägermeister verteilte ihr Getränk gekühlt in Plaste-Reagenzgläsern, die zum Ende der Veranstaltung hin fast den gesamten Boden bedeckten.

Musikalisch ging es mit den männlichen Überresten der glorreichen Guano Apes los. Diese haben sich unter dem Namen **I.O.** einen neuen Sänger gesucht, dem zwar im Gegensatz zu Sandra Nasic während des Konzertes nicht die (soulige) Stimme ausgeht, der jedoch irgendwie nicht ganz zu der altbekannten Musik passen will und das zu diesem frühen Zeitpunkt noch spärliche Publikum nicht vom <del datetime="2008-06-29T11:43:32+00:00">Hocker</del> Rasen riss.

Das taten dafür **Jennifer Rostock**, die mit ihrer Mischung aus Schlager, NDW und Punk für ordentlich Stimmung sorgten. Die Sängerin schaffte es mit ihrer schrillen Stimme und der eigenwilligen Performance problemlos, was I.O vorher noch verwehrt blieb - nämlich für das Publikum (inklusive mir) zu bewegen. Die Band ist wohl der Tipp für die diesjährige Festival-Saison!

Die **Kilians** mit ihrer an den modernen Britpop angelehnten Musik trafen anschließend so gar nicht meinen Musikgeschmack, also ging es hinüber zu der kleinen Bühne. Dort neben dem Zelt mit der Fußballübertragung (Russland führte zu diesem Zeitpunkt schon 1:0 gegen Schweden) standen **Paula** auf dem Programm. Seit deren kleinen Erfolgen um die Jahrtausendwende ist einige Zeit vergangen, und ich war überrascht, dass es die Elektropop-Band überhaupt noch gibt. Da mir aber die Stimme der Sängerin Elke Brauweiler gefällt (das Seitenprojekt **Commercial Breakup** hatte mit *Walking back home* meinen persönlichen Sommerhit 2000 abgeliefert), war ich interessiert, was Paula 2008 ohne Songwriter Berend Intelmann zu bieten haben.

Viel anders als vor sieben Jahren hörten sich die Songs nicht an, selbst wenn einige der textlich minimalistischen Stücke durch den extrem hohen Anteil an Wiederholungen etwas nervten. Doch die Band selber bzw Sängerin Elke sorgten dafür, dass sich immer mehr Zuschauer abwanden. Sowohl technisch (Kabelbruch am Kabel zum Bass) als auch menschlich klappte nicht viel auf der Bühne; hinter den Mikrophonen schrie man sich gegenseitig an und Frau Brauweiler spielte sich auch gegenüber dem Publikum als migränegeplagte Diva auf. So kann man Musik auch zerstören.

Nach diesem traurigen Zwischenspiel standen schließlich die Headliner **Wir sind Helden** auf dem Plan, und vor der Hauptbühne war kein Durchkommen zu den guten (Sicht-)Plätzen mehr. Die vier Berliner, aufgereiht nebeneinander auf der Bühne (auch Drummer Pola) und unterstützt von drei Bläsern, spulten ihre sehr professionelle Show hinunter, machten jedoch für meinen Geschmack zu viele Pausen und spielten ausschließlich Singles. Ich hätte gerne ein paar mehr Lieder vom aktuellen Album gehört. Die Pausen füllten sie mit Dialogen zu den Themen Bildungsmisere und dem Herumhacken auf Studenten, was wenig überraschend vom Publikum der CampusParty wohlwollend aufgenommen wurde. Als die Helden jedoch noch kleinere Bühnen bespielten, gefielen sie mir live noch besser.

Insgesamt hat sich der Besuch gelohnt, da ich zum Einen Jennifer Rostock live bewundern durfte und zum Anderen das Preis-/Leistungs-Verhältnis stimmte. Da auch das Wetter super mitspielte, bleibt mir die CampusParty Dresden 2008 also in sehr guter Erinnerung.
