---
title: "Drei Farben"
date: "2009-10-11T23:24:07"
categories: [gesehen]
---

Eine kleinwüchsige Alte, auf ihren Gehstock gestützt, versucht, eine leere Flasche in die hoch angebrachte Öffnung des Glascontainers zu werfen. Erst im dritten Teil der Filmserie *Drei Farben* von [Krzysztof Kieślowski](http://de.wikipedia.org/wiki/Krzysztof_Kieślowski) wird ihr von der Hauptdarstellerin bei diesem schwierigen Unterfangen geholfen und damit ein Punkt gesetzt unter die Trilogie.

Die drei titelgebenden Farben (blau, weiß, rot) sind der französischen Flagge entnommen und stehen symbolisch für die Motive der französischen Revolution (Freiheit, Gleichheit und Brüderlichkeit) und damit für die zentralen Themen der Filme. Doch eigentlich ist es das vereinte Europa, dem der Regisseur in seinen Filmen die Liebe erklärt. Im ersten Teil, *Blau*, stirbt zu Beginn zwar der Verfasser einer neuen europäischen Hymne, doch seine Witwe und ein Freund nehmen am Ende gemeinsam das Werk wieder auf und triumphieren. In *Weiß* zeigt Kieślowski seine polnische Heimat nach der Wende als aufblühende Volkswirtschaft, die dennoch nicht ihre Wurzeln verliert sondern den Westen bereichert. Und in *Rot* schließlich steht die sprichwörtliche Neutralität der Schweiz im Blickpunkt - wie kann man in einem Geflecht wie den europäischen Staaten mit einer zentralen Lage überhaupt neutral sein? Der alte Richter war es nie, und ist es nicht, und ebenso hat die Schweiz ihren Platz im Herzen Europas.

So ist die Verbindung der drei Filme neben der alten Frau auch ein Fährunglück im Ärmelkanal, bei dem u.a. Franzosen, Polen und Schweizer überleben - nämlich die Hauptpersonen der drei Filme. Was könnte europäischer sein als die gemeinsame Rettung so vieler verschiedener Landsleute?

Neben der formal durchgehend beeindruckenden Farbgebung und Kameraführung der einzelnen Filme sind es die Leistungen der Hauptdarstellerinen, die überzeugen. Juliette Binoche, Julie Delpy und Irène Jacob passen sich mit ihren Charakteren perfekt in das Farbschema ein, in ihnen manifestieren sich die Motive der Filme, wenn auch meist nicht direkt in der Bedeutung der französischen Revolution.

So nimmt sich die von Binoche gespielte Julie Vignon in ihrer Trauer um die verunglückten Mann und Tochter die Freiheit, ihr gesamtes vorheriges Leben hinter sich zu lassen. Sie verkauft das Haus, vernichtet die Anfänge der europäischen Hymne ihres Mannes und lässt auch die Freunde zurück. Sie will nichts mehr an sich heranlassen, weder das alte noch ein neues Leben. Doch eine andere Frau, die sich die Freiheit nimmt als Nachtclubtänzerin in einem bürgerlichen Pariser Wohnhaus zu wohnen, holt Julie schließlich wieder aus ihrer selbstgewählten Verbannung zurück.

Am besten gefallen hat mir jedoch der dritte Teil der Serie, *Rot*. Darin wird mit einer faszinierenden Leichtigkeit eine doppelt-parallele Geschichte erzählt, die immer wieder die Haupthandlung um die fürsorgliche Valentine Dussaut streift. Meist sind es Telefone, dargestellt als moderne Attentäter und Manipulatoren jeglicher Beziehung, die die beiden Handlungen miteinander verknüpfen. Doch mit zunehmender Filmdauer wird immer unklarer, ob der angehende Richter Auguste Bruner nicht einfach eine Projektion der Lebensgeschichte des illegal telefonabhörenden Kauzes sind, mit dem Valentine Bekanntschaft gemacht hat. Oder geht die Brüderlichkeit, die Valentine dazu bringt, der alten Frau am Flaschencontainer zu helfen, so weit, dass der alte Richter dem jungen Richter sein eigenes Leben überstülpt, nur mit Happy End?

*Drei Farben* ist eine unglaublich vielschichtige Filmtrilogie. Dies drückt sich in dem extremen Farb-Formalismus genauso aus wie im ironischen Umgang mit den Leitmotiven und der Leichtigkeit, mit denen die Handlungen inszeniert sind und ineinander übergreifen. Als Einzelwerke sind die Filme vielleicht etwas schwer zugänglich, aber zusammen bilden sie ein großes europäisches Werk.
