---
title: "Sherlock Staffel 2"
date: "2012-02-26T14:12:07"
categories: [gesehen]
---

Es war eine angenehme Überraschung, als ich in meiner Videothek so kurz nach der Ausstrahlung auf BBC die Import-DVDs der zweiten Staffel entdeckte. Weniger überraschte mich dagegen, dass die die drei neuen Folgen genau da weiter machen, wo [die erste Staffel](/blog/2011/08/08/sherlock/) aufhörte. Tempo, Darsteller, Soundtrack und Kamera sind auf demselben hohen Niveau, und inhaltlich haben sich die Produzenten dieses Mal den ganz großen Geschichten gewidmet: "Ein Skandal in Böhmen" (als *A Scandal in Belgravia*), "Der Hund von Baskerville" (*The Hounds of Baskerville*) und "Sein letzter Fall" (als *The Reichenbach Fall*).

Einige der von der Vorlage abweichenden Themenkomplexe der ersten Episoden werden dabei weiter vertieft. So spielt gleich die erste Folge mit dem sexuellen Subkontext um Sherlock. Beschränkte dieser sich in der ersten Staffel hauptsächlich auf das ironische Spiel mit der Annahme, Sherlock und Watson seien ein schwules Pärchen, so macht die Konfrontation mit Irene Adler, die je nach Kontext Dominatrix oder einfach die Frau genannt wird, deutlich, dass der Detektiv von allen Seiten als Autist wahrgenommen wird (ob er einer ist lässt das Drehbuch offen) und dies von verschiedenen Seiten auch angesprochen wird (mehrmals wird er *The Virgin* genannt).

Sehr gefallen haben mir auch die popkulturellen Spielereien mit dem Äußeren von Sherlock Holmes. Die klassische Darstellung zeigt den Detektiv oft mit den ihn prägenden Accessoires: Einer großer Lupe und der markanten Mütze. Die Lupe hat sich nun in moderner Form in die Serie gerettet, die Mütze wird dagegen als Running Gag aufgenommen. Sherlock entwendet sie in einem kurzen Intermezzo aus der Requisite eines Theaters, weil er sein Gesicht vor den Pressefotographen schützen will. Das Blog von Watson und die Medien machen daraus ein Wiedererkennungsmerkmal, auf das Sherlock gereizt reagiert, weil die Mütze ihm zuwider ist - ein netter postmoderner Scherz.

Die zweite Episode (*The Hounds of Baskerville*) nimmt sich die sicherlich am Häufigsten [verfilmte](http://de.wikipedia.org/wiki/Der_Hund_der_Baskervilles#Filme) und zitierte Sherlock-Holmes-Geschichte vor. Mehr als den Namen und das atmosphärische Setting wird aber nicht übernommen; vielmehr ist Baskerville ein geheimes Forschungslabor des Militärs, wo ein Angestellter an einem Virus arbeitet, das Angstzustände hervorruft. Es wird ein wenig mit dem Gegensatz zwischen den klinisch-sauberen und hellen Labors und den dunklen, nebligen Wäldern von Dartmoor gespielt und außerdem klar gemacht, dass solche mysteriös-gruseligen Ecken im modernen England gar nicht mehr existierten sondern als Werbemaßnahmen für den Tourismus inszeniert werden. Dieses vorsichtige Hinterfragen des klassischen Stoffes ist das durchgängige Thema der Episode, die bereits damit beginnt das Sherlock den Fall nur annimmt, weil sein Auftraggeber das heute selten verwendete Wort "Hound" benutzt.

Technisch wird wieder viel mit im Raum platzierten Einblendungen gearbeitet und die Denkprozesse von Sherlock finden eine ähnlich gute Visualisierung. Allerdings sollte deshalb der Film besser in HD gesehen werden; einige Texte sind so klein, dass sie auf DVD kaum zu lesen waren. Und leider leidet die dank klarer HD-Bilder eigentlich überzeugende Optik in den nächtlichen Außenszenen unter starkem Rauschen, das den Gesamteindruck etwas stört.

Die letzte Episode, *The Reichenbach Fall*, übertreibt es schließlich mit der Geschwindigkeit der Inszenierung. In den anderthalb Stunden passiert so viel, dass der Zuschauer genau wie Sherlock nicht zur Ruhe kommt und es schwer fällt, das Geschehen auf sich wirken zu lassen. Dies passt natürlich zu der modernen Fassung von Moriarty mit seiner nervösen, extrovertierten Aggressivität, dem es aus meiner Sicht an einer souveränen Ausstrahlung fehlt, um ein geeigneter Nemesis für Sherlock Holmes zu sein. Aber da auch der Meisterdetektiv für die Serie mit ähnlichen Charakterzügen versehen wurde, passt Moriarty als eine Art Spiegelbild zu seinem Gegenspieler, was gleichzeitig die Grundannahme der Episode unterstreicht, dass Sherlock seine Fälle alle selbst inszeniert hat.

[Zu Pfingsten will die ARD die drei Folgen der zweiten Staffel auch in Deutschland ausstrahlen](http://www.moviepilot.de/news/ard-zeigt-zweite-sherlock-staffel-ueber-pfingsten-114242) - dafür gibt es eine klare Sehempfehlung von mir. Ich freue mich dagegen auf die bereits angekündigte dritte Staffel!
