---
title: "Der Elektromarkt, der Verrückte macht"
date: "2012-01-22T01:25:01"
categories: [gedacht,getan]
---

In einer klassischen Komsumgesellschaft gibt es zwei genau definierte Rollen: Konsumenten und Verkäufer. Wenn beide aufeinandertreffen, dann tauschen im Normalfall Waren und Geld den Besitzer, in einer festgelegten Richtung: Der Konsument gibt dem Verkäufer einen Geldbetrag, und dieser ihm dafür eine vorher vereinbarte Ware. So weit, so einfach.

Kompliziert wird es, wenn das Prinzip umgedreht wird und der Konsument die erworbene Ware zurücktauschen möchte. Diese Erfahrung musste ich zumindest im großen Elektrofachmarkt des [Alexa](/blog/2007/09/12/und-ewig-lockt-das-einkaufszentrum/) machen, als ich ein defektes Weihnachtsgeschenk zurücktauschen wollte. Die Runden, die ich zu drehen hatte und die mich auf drei Etagen des Marktes führten, erinnerten mich frappierend an *Asterix erobert Rom*, als Asterix und Obelix mit der Aufgabe betraut werden, in einem Haus voller Schalter und Beamte einen *Passierschein* zu besorgen.

Meine kleine Odyssee, die ich zur Erhöhung des Schwierigkeitsgrades in der Mittagspause gestartet hatte, begann im Erdgeschoss an der Information, wo ich einen Zettel erhielt, der bestätigte, dass ich einen gekauften und bezahlten Artikel zurück in den Markt brachte. Danach ging es in die TV-Abteilung, wo die erste Hürde darin bestand, einen Mitarbeiter zu finden, der nicht mit einem Kundengespräch beschäftigt war - denn so etwas entspricht der klassischen Rollenverteilung und hat deshalb Vorrang. Als sich eine Fachkraft schließlich für mich zuständig fühlte stellte sich schnell heraus, dass der Service erst den Defekt aufnehmen und das Gerät entgegennehmen muss. So wurde ich zur Abholung meines persönlichen *Passierscheins* eine Etage höher geschickt, wo ein junger Mann eine so intensive Beziehung zu seinem Monitor hatte, dass er sich während der Bearbeitung meines Falles kein einziges Mal davon abwendete.

Nach dem Tausch des Gerätes gegen den *Passierschein* durfte ich zurück in die TV-Abteilung, mich wieder anstellen und erhielt so den nächsten Schein, den ein Mitarbeiter mir ausdruckte und den sein Chef höchstpersönlich abzeichnete. Dieser sollte es mir ermöglichen, an der Kasse den Kaufpreis zurück zu erhalten und damit die Umkehrung des normalen Komsumvorgangs abzuschließen. Aber im Erdgeschoss, nach fast zehn Minuten des Wartens in der Schlange, wurde klar, dass der Bürokratie nach drei Formularen noch nicht Genüge getan war. Denn die Kassiererin teilte mir mit, dass das letzte Formular falsch ausgefüllt wurde und sie mir deshalb kein Geld geben könne.

So drehte ich eine weitere Schleife über die TV-Abteilung und 45 Minuten und vier ausgedruckte DIN-A4-Seiten später hatte ich schließlich das Geld in den Händen, ohne wie Asterix ein neues Formular erfinden zu müssen - wobei ich dafür dem Wahnsinn recht nah war. Aber das war wohl die verdiente Strafe für mein Fallen aus der Konsumentenrolle. Zukünftig werde ich es mir zweimal überlegen, den Elektromarkt, der Verrückte macht, zu betreten.
