---
title: "Jonathan Strange & Mr Norrell"
date: "2007-08-04T20:59:45"
categories: [gelesen]
---

*von Susanna Clarke,
erschienen bei Bloomsbury, ISBN 0-7475-8069-3, 11,20€*

Der Fantasy-Boom, ausgelöst durch die Verfilmung des Herrn der Ringe und die Bücher über Harry Potter, hat nicht nur in Deutschland die Absatzzahlen von Wolfgang Hohlbeins Werken in ungeahnte Höhen getrieben, sondern auch auf der [Insel](http://www.great-britain.co.uk/) mehr Autoren dazu bewegt, sich dieser Thematik zu widmen. So auch Susanna Clarke, deren Erstling mit über 1000 Seiten gleich in tolkiensche Ausmaße vordringt - zum Glück ansonsten aber angenehm originell bleibt.

Der Roman spielt im England des noch jungen 19. Jahrhunderts. Dieses England ähnelt dem uns bekannten England bis auf die Tatsache, dass es dort Magie gibt. Dank derer konnte im Mittelalter John Uskglass, der Rabenkönig, die Herrschaft über den Norden des Landes übernehmen und diesen 300 Jahre lang regieren. Nach seinem Verschwinden begann sich auch die Magie aus England zurückzuziehen, doch die beiden titelgebenden Helden des Buches haben durch das Studium von Büchern und dank ihres Talentes gelernt, Magie zu praktizieren und wollen diese zum Wohl Englands einsetzen. Jedoch haben sie dabei unterschiedliche Vorstellungen davon, wie weit ein Magier gehen darf. Und ganz ungefährlich ist das Zaubern auch nicht, denn die beiden öffnen ungewollt Tore in andere Welten, die das Interesse der magiebegabten Elfen an England wieder erwecken.

Ganz lösen von bekannten Spielarten der englischen Fantasy kann sich auch Susanna Clarke nicht. Schon bei Terry Pratchett sind die Fairies ein verschlagenes und nur an den eigenen Vorteil denkendes Volk. Aber aufgrund der Tatsache, dass sie mit ihrer angeborenen Magie fast alles ohne Arbeit erreichen können, fehlt ihnen auch jeglicher Ehrgeiz. Diese Erfindung einer parallelen Geschichte Englands mit den Magiern (inklusive paralleler Welten) ist die Stärke von "Jonathan Strange & Mr Norrell", vor allem da die Autorin auch viele echte Ereignisse der Geschichte mit einfließen lässt.

Das große Manko des Buches ist aber, dass Frau Clarke scheinbar nicht so viel von einem vernünftigen Spannungsbogen hält. Ständig erzeugt sie spannende Momente, nur um danach mit der Handlung ganz woanders hin zu springen und so den Leser unbefriedigt zurückzulassen mit offenen Fragen und meist auch fehlendem Verständnis der gerade beschriebenen Ereignisse. Spannungs-Sinuskurve trifft es wohl eher, da sich dieses Muster sehr oft wiederholt. Zu viele Details lassen eine fokussierte Storyentwicklung missen (es gibt mehrseitige Fußnoten!) und das Lesen der 1000 Seiten zu einem Kampf werden.

Zudem stellt sich nach einer gewissen Weile eine Sättigung an Ladies und Gentlemen beim Leser ein. Anfangs ist man noch amüsiert über das Verhalten, den Umgang und die Sprache des viktorianischen Adels. Doch dann wird noch ein Gentleman vorgestellt, und danach noch eine freundliche englische Familie, und so geht das weiter bis zum Ende des Buches und die Charaktere türmen sich zu einem fast unüberschaubaren Haufen auf.

Gefehlt hat mir auch der praktische Aspekt des Zauberns. An kaum einer Stelle wird beschrieben, wie die Zauberer ihre Fähigkeit ausüben; meist werden nur die Auswirkungen beschrieben. Auch wird an keiner Stelle erklärt, wieso manche Menschen ein Talent für Magie haben und andere ein Leben lang lernen können, ohne irgendetwas zu erreichen. Dafür sind die Spielarten der Magie sehr ungewöhnlich. Die Zauberer können fast alle Aspekte der Natur verändern; sie können Statuen zum Sprechen bringen, Buchstaben aus Büchern verschwinden lassen und mitten in der spanischen Pampa Straßen erscheinen lassen. Jonathan Strange versetzt sogar das Städtchen Waterloo inklusive Katz und Maus für kurze Zeit nach Amerika.

Fazit: Viele unverbrauchte Ideen und das nette Setting im previktorianischen England sind die Grundlage für diesen guten Fantasyroman. Nur leider ist er mit 1000 Seiten viel zu lang geworden - es fehlt ein durchgängiger Spannungsbogen und zu viele Details lenken von der eigentlichen Geschichte ab. Ich habe deshalb während des Lesens oft die Motivation verloren und bin auf andere Bücher umgestiegen. Wer solche Motivationsprobleme nicht kennt und unterhaltsame Fantasy abseits des Mainstream mag, der sollte ruhig einen Blick wagen.
