---
title: "Sicherheitskontrollen in Singapur und Australien"
date: "2012-10-03T22:37:42"
categories: [gewesen]
---

Wenn es um Recht und Ordnung geht, dann verstehen die meisten Länder keinen Spaß. Singapur und Australien sind da keine Ausnahmen, doch setzen beide Nationen unterschiedliche Schwerpunkte (zusätzlich zu den üblichen Spielchen an den Flughäfen).

Der kleine Stadtstaat in Asien ist bekannt für seine [utopisch hohen Geldstrafen](http://de.wikipedia.org/wiki/Singapur#Strafrecht) für Vergehen wie Fahrradfahren in Fußgängerzonen (1000,- SGD) oder Essen oder Trinken in öffentlichen Verkehrsmitteln (500,- SGD). Entsprechend sauber und geleckt sehen die U-Bahnen und ihre Stationen aus. In einer davon bin ich in die Kontrolle einer singapurischen Sicherheitskraft geraten. Die kleine Asiatin, zwei Köpfe kleiner als ich, stand ziemlich gelangweilt an ihrem Stand und sah in mir als einzigen Passanten wohl eine Abwechslung. Die Neugierde wich jedoch bald der Nervosität, da ich trotz Landessprache Englisch nicht gleich verstand, was sie von mir wollte und sie sich vermutlich der Situation bewusst wurde, dass sie vollkommen allein einem großen Ausländer gegenüberstand - wer weiß wie dieser sich verhält, wenn er gereizt wird ;)

Irgendwann begriff ich, dass sie meinen Rucksack kontrollieren wollte. Den öffnete sie kurz, warf einen scheuen Blick hinein und gab ihn mir postwendend zurück. Als ich fortging war sie sichtlich erleichtert, dass sie die Situation überstanden hatte, die für sie komplizierter geworden war, als sie zuerst gedacht hatte. Eine konsequente Kontrolle sieht jedoch anders aus, so dass ich vermute, dass auch die hohen Strafen abschreckend wirken sollen, aber nicht durchgängig vollzogen werden. Jedenfalls habe ich mich dabei ertappt, wie ich aus Gewohnheit während einer U-Bahn-Fahrt aus meiner Wasserflasche getrunken habe - aufgefallen ist dies niemanden, auch die Einheimischen haben mich keines Blickes gewürdigt.

Der Fokus der Australier bei der Einreise liegt dagegen darauf, dass keine Pflanzen und Tiere oder anderes organisches Material in das Land eingeführt wird - denn damit haben sie [schlechte Erfahrungen](http://www.welt.de/wissenschaft/article1735052/Giftige-Riesenkroeten-geraten-ausser-Kontrolle.html) gemacht. Drogen einzuführen ist ebenfalls verboten und beides wird streng kontrolliert. So mussten bei der Ankunft in Melbourne alle Einreisende durch eine Spürhundkontrolle. Dazu wurde ich mit einer handvoll anderer Fluggäste in einem Flur in einer Reihe aufgestellt und ein Zollbeamter lief mit dem schnüffelnden Drogenhund jeden einzelnen Passagier ab.

Bei meinen beiden inneraustralischen Flügen hatte ich zudem das Glück, jeweils für eine Sprengstoffkontrolle ausgewählt zu werden. Dabei wurde wiederum mein Rucksack kontrolliert, nur diesmal auf technischem Wege: Ein Stab, an dessen Spitze sich ein auswechselbares Plättchen befand, wurde um und in meinen Handgepäck geführt. Danach kam das Plättchen in eine Maschine und die spuckte ein Ergebnis aus - jeweils negativ bei mir.

Was übrig bleibt nach diesen Kontrollen ist leider kein Gefühl höherer Sicherheit. Denn entweder waren die Kontrollen nicht konsequent genug oder vom Zufall abhängig. So nervig und zeitaufreibend die Kontrollen auf internationalen Flughäfen sind - sie sind zumindest einheitlich und damit für alle gleich.
