---
title: "Margarete Steiff"
date: "2005-12-23T23:10:20"
categories: [gesehen]
---

Nach der Werbung von Heike Makatsch gestern abend bei Harald Schmidt habe ich mir heute beim Geschenke verpacken den schwäbischen "Heimatfilm" über die Erfinderin der Teddybären auf ARTE angesehen. 

Dieser passt sehr gut in den aktuellen Trend, Menschen auf Bauernhöfe und Landgüter zu schicken und sie vor laufender Kamera wie ihre Vorfahren schuften zu lassen. Doch im Gegensatz zu diesen Doku-Soaps welche uns zeigen sollen, wie gut es uns geht und das wir nichts ändern können, ist bei "Margarete Steiff" die Zeit des vorletzten Jahrhunderts nur Hintergrund und Auslöser der Geschichte und wird am Ende auch überwunden. 

Durch die Kinderlähmung konnte das Gretel niemals laufen und war deshalb in den Augen der meisten Menschen nichts wert. Mit ihrem eisernen Willen hat sie sich trotzdem durchgesetzt: Gegen die Dorfoberen mit ihrer antiquierten Vorstellung von der Welt, gegen die Kirche mit ihrem Standesdenken und gegen die allgemeinen Vorbehalte gegenüber verkrüppelten Menschen und auch Frauen. Dabei geholfen hat auch der technische Fortschritt, den sich die junge Frau genauso zu Nutze macht wie ihre Fähigkeiten der Ökonomie und der ihr hilft, alle künstlichen und natürlichen Schranken zu überwinden.

Heike Makatsch spielt Margarete Steiff sehr überzeugend und der schwäbische Dialekt sorgt alleine schon für viel Authentizität. Da die Zuschauer wissen, dass Fräulein Steiff am Ende einen Erfolg feiern konnte, beschränkt sich der Regisseur darauf, die Hindernisse auf dem Weg dahin aufzuzeigen. Dazu hätte es aber nicht unbedingt des Aufhängers mit der Bank und dem Kredit benötigt, mit dem der Film anfängt. Die Darstellung der gescheiterten Liebe dagegen hilft, den Charakter der jungen Frau präzise auszuarbeiten.

Insgesamt also eine überzeugende TV-Produktion mit einer Aussage, die erfreulicherweise gegen den Strom der aktuellen Volksverdummung schwimmt. 

Nächste Woche wird der Film dann wie von anderen Produktionen gewohnt in der ARD wiederholt.
