---
title: "Tomb Raider"
date: "2001-07-17T00:00:12"
categories: [gesehen]
---

*USA/UK (2001)
Regie: Simon West
Darsteller: Angelina Jolie (Lara Croft), Iain Glen (Manfred Powell), Daniel Craig (Alex Marrs), Noah Taylor (Bryce), Jon Voight (Lord Croft) und andere Grabräuber*
[Offizielle Homepage](http://www.tombraidermovie.com)

Lara Croft, begeisterte Archäologin wie ihr Vater, lebt seit dessen Tod auf dem Anwesen der Familie. Eines Nachts wird sie von einer seltsamen Uhr geweckt, die scheinbar von ihrem Vater zu dessen Lebzeiten im Haus versteckt wurde. Die Uhr stellt sich als archäologisches Artefakt heraus, hinter dem bald die Gruppe der Erleuchteten, eine geheime Organisation, hinterher ist. Denn es ist ein Schlüssel zur Weltherrschaft, der nur alle 5000 Jahre wirksam wird, wenn alle Planeten des Sonnensystems eine bestimmte Konstellation inne haben. So kommt es zu einem Wettlauf mit der Zeit, um die weiteren nötigen Teile in aller Welt zu finden...

Als Fan des Spiels (aller Teile) ging ich mit gemischten Gefühlen in den Film: Kann man dieses Spiel überhaupt für das Kino umsetzen bzw sollte man besser Distanz wahren und lieber auf Realität setzen? Man hat einen Zwischenweg gewählt, und dies ist nicht der Schwachpunkt des Films. Angelina Jolie als Lara Croft ist in Ordnung, das Haus wurde sehr gut dem Spiel nachempfunden und die namensgebenden Ruinen und Höhlen kommen auch gut rüber.

Aber leider wurde Action-Film-like die Story vernachlässigt, so daß man ständig das Gefühl hat, nur eine schlechte Überleitung zur nächsten Action-Sequenz zu sehen. Und diese können auch nicht alle überzeugen, die Endsequenz ist sogar am ernüchternsten.

Mein Fazit: TR ist leider nur ein mittelmäßiger Actionfilm geworden, dabei hätte man aus dem gegebenen Stoff so viel mehr machen können. Für Fans von Angelina Jolie und Lara Croft selber sehenswert, alle anderen sparen sich den Besuch im Kino!
