---
title: "Harry Potter und die Hüter des Copyright"
date: "2007-08-08T20:38:56"
categories: [gedacht,gefunden]
---

Ich habe das Gefühl, dies wird so langsam ein Harry-Potter-Blog - ich sollte eine neue Rubrik dafür einführen...

Anlass ist [diese Nachricht](http://www.spiegel.de/kultur/literatur/0,1518,498927,00.html): In Frankreich wurde ein 16jähriger Schüler festgenommen und eine Nacht in Untersuchungshaft gesteckt, weil er eine selbsterstellte Übersetzung des siebenten Teils der Buchreihe im Internet auf seiner Website veröffentlich hat.

Früher wäre jeder Lehrer über so viel Engagement erfreut gewesen, doch mit den unbegrenzten Möglichkeiten des Internet und der Angst der Verlage, dieses könnte ihnen die Grundlage ihrer Einnahmen entziehen, folgen solche extremen Reaktionen. Untersuchungshaft für einen Copyrightverstoß mit schwer zu beziffernden Verlusten - da muss man doch fragen, ob nicht mit Kanonen auf Spatzen geschossen wird. Noch dazu, wo die alten Medien krankhaft versuchen, ihre Geschäftsmodelle und Märkte auch in der Zeiten der weltweit verfügbaren Informationen abzuschotten.

Globalisierung ist nur dort erwünscht, wo sie auch hilft, mehr Geld zu verdienen. Der englische Harry Potter wird zwar weltweit verkauft, aber die lokalen Übersetzungen (die auch nur den selben Inhalt enthalten) werden künstlich zurückgehalten in der Hoffnung, so mehr Exemplare zu verkaufen. Bei den Filmverleihern hat dagegen bereits die Einsicht eingesetzt, dass die global gestaffelte Verwertungskette nicht mehr gehalten werden kann und so starten die aktuellen Blockbuster wie der [Simpsons-Film](/blog/2007/07/30/die-simpsons-der-film/) weltweit am selben Tag. Aber dies werden die Verlage trotz der eher geringen Bedrohung durch die Digitalisierung auch noch lernen...
