---
title: "Futurama: Bender's game"
date: "2009-01-31T23:20:12"
categories: [gesehen]
---

Deutschland ist kein Hochtechnologie-Land (mehr). Erst die Pleite der Siemens-Handy-Sparte, dann der Wegzug von Nokia, schließlich die Insolvenz von Quimonda - dass der dritte Futurama-Film hierzulande nur auf DVD und nicht wie in den USA und England auch auf Blu-Ray erschienen ist, ist nur ein weiteres Indiz für dieses Problem. Stattdessen versucht man den deutschen Käufer mit einem Pappschuber für die DVD-Hülle zu befriedigen - ein erbärmlicher Ersatz.

Im ihrem inzwischen dritten Direct-to-DVD-Film beschäftigt die Planet-Express-Crew die dunkle Materie, der Treibstoff der Zukunft. Einst von Professor Farnworth für die Energiegewinnung entdeckt, hat diese Moms globales Imperium begründet. Als sie dieses Monopol schamlos auszunutzen beginnt, will der Professor mit einem die dunkle Materie zerstörendem Kristall dem die Grundlage entziehen. Währenddessen ist Bender dem Spiel Dungeons & Dragons verfallen und hat sich seine eigene Fantasiewelt aufgebaut, in der sich plötzlich durch einen Zwischenfall mit dem Kristall alle Mitglieder der Crew wiederfinden und Rollen in Benders Version des Herrn der Ringe einnehmen müssen...

Nachdem mit Gary Gygax der Erfinder von Dungeons & Dragons letztes Jahr verstorben ist, dachten sich die Futurama-Macher, dass sie ihn am Besten mit einer Parodie seiner Spielewelt und des Herrn der Ringe würdigen könnten. Und damit ist auch die Hälfte des Films schon erzählt, denn sie besteht nur aus einer Aneinanderreihung von Filmzitaten und -anspielungen, die zwar für kurze Lacher sorgen, aber garantiert nicht zum wiederholten Anschauen des Films anregen.

Dagegen bietet die Rahmenhandlung wieder wissenschaftliche und hintergründige Witze (Authentifikation und Autorisation), Anspielungen auf Klassiker des Science Fiction (die Klappsmühle für Roboter ist nach [HAL](http://de.wikipedia.org/wiki/HAL_9000) benannt) und vor allem Seitenhiebe ohne Ende auf das aktuelle Problem der Energiegewinnung aus fossilen Brennstoffen, für dass eine schöne Analogie gefunden wurde. Insgesamt fehlt es jedoch der Story wieder an Inhalt und Substanz, so dass *Bender's game* aus meiner Sicht sogar schlechter als [Die Ära des Tentakels](/blog/2008/09/15/futurama-die-ara-des-tentakels/) ist.

Dafür ist die DVD wieder mit umfassendem Bonus-Material ausgestattet, inklusive einer genialen Bender Anti-Piraterie-Warnung und viel Doku aus der Produktion. Und für alle die es wissen wollen: No Lego was harmed by the production of the DVD!
