---
title: "Rock Harz 2008"
date: "2008-07-22T22:23:34"
categories: [gehört,gewesen]
---

Back from Dreck. Nachdem mein Magen jetzt langsam die Umstellung von der typischen Festivalnahrung (Grillen nach dem Aufstehen und vor den Bands um 12, Grillen zwischen den Bands, Grillen nach den Bands gegen 2h) auf normale, ausgewogenere Essstrategien akzeptiert, kann ich auch vom diesjährigen [Rock Harz](http://openair.rockharz.de/) bei Osterode berichten.

**Wetter & Organisation**

Diese beide Elemente beeinflussen sich beim Rock Harz immer gerne gegenseitig; so auch dieses Mal. Das Wetter ließ sich zu einem Best-Of der letzten beiden Jahre hinreißen und mischte ständige Regenfälle auf Niveau des großen Gusses von 2006 mit dem Wind und der Kälte des Vorjahres. Damit war die Planung der Zeltplätze schon vor Eröffnung des Festivals hinfällig und die Vorsichtsmaßnahme, keine Autos mehr auf den Campingplatz zu lassen, führte zu einer plötzlichen Knappheit an Parkplätzen. Aber spontan, wie das Harzvolk nun einmal ist, entstanden hinter dem Edeka und vor der Mehrzweckhalle neue Campinggrounds, die zumindest bis Freitag noch Camper aufnahmen.

Danach wurden einfach keine Camping-Tickets mehr verkauft. Da es aber keine Kontrollen gab, wer überhaupt auf die Zeltplätze darf, konnte man das um fünf Euro ermäßigte Ticket ohne Camping erwerben und sich trotzdem dort breitmachen. Platz war genügend vorhanden, trotz der angeblich unerwarteten hohen Nachfrage nach Eintrittskarten. Dabei würde ich sagen, dass dieses Jahr weniger Besucher da waren, trotz der erneut größeren Bühne. Da aber die Festivalbändchen nur an genau einer Stelle verteilt wurden, bildeten sich am Donnerstag extrem lange Schlangen vor der Ausgabe.

Zudem mutierte bereits am Freitag die Wiese auf dem Festivalgelände zu einer einzigen wattähnlichen Matschfläche, da konnten auch Holzspäne und Strohballen nichts daran ändern. Die wenigen sonnigen Stunden reichten leider nicht einmal aus, das Campinggelände zu trocknen, so dass ich am Sonntag auch eine Menge des guten Harzbodens mit nach Hause schleppte. 

Das diesjährige Highlight waren aber die Busshuttles, die zwischen Edeka und Festivalgelände verkehrten. In Stoßzeiten drei Busse fuhren die nasse und stinkende Meute durch das Dorf, so dass die Einwohner vom Großteil der Besucherströme entlastet wurden. Ich frage mich aber immer noch, wer auf die Idee kam, die 5000 Camper zwanzig Minuten weg auf der anderen Seite von Förste unterzubringen - die Dorfbewohner hatten sicherlich ihren Spaß.

**Musik**

Viele Bands haben mich dieses Jahr ja nicht angezogen. Aufgrund des weiten Weges vom Camping zur Bühne musste auch immer gut geplant werden, um nicht eine der interessanteren Bands zu verpassen - zu den Mittags-Spielzeiten habe ich es leider nie geschafft. Am Donnerstag legte **Mambo Kurt** mit seiner Heimorgel gleich in zwei Sessions los; was **Knorkator** auf ihrer Abschiedstour nicht vergönnt war. Nur 45 Minuten durften sie auf die Hauptbühne, die zwar sehr kurzweilig waren, aber leider auch sehr kurz.

Ein roter Faden dieses Jahr waren Bands, bei denen (wichtige) Teile der Musik nur aus der Konserve kamen. Es fing an mit den grottenschlechten **Down Below** und ging über die enttäuschenden **Lacrimas Profundere** bis hin zu den Headlinern **Within Temptation**, die trotzdem mein persönliches Highlight waren. Hier waren zumindest bis auf die Streicher alle Instrumente auf der Bühne vertreten und sorgten für ordentlich Druck - die Band ist live deutlich rockiger als aus der Konserve. Sängerin Sharon, inzwischen nicht mehr in voluminösen Ballkleidern auf der Bühne, hat einfach eine einzigartige Stimme, selbst wenn sie nicht jeden Ton trifft und wusste das verbliebene Publikum trotz der heranziehenden Sonntag-Nacht-Kälte auf Temperatur zu halten.

Eine noch bessere Stimme hat ja Liv Kristine, die bei Ehemann Alex Krull zumindest mitsingen durfte und damit die Werk-80-Show von **Atrocity** rettete. Denn Herr Krull selber kam gar nicht gegen die Musik an - ob dies nur am Mix lag oder an seiner Tagesform, weiß ich nicht. So konnte nur die Bühnenshow überzeugen; vor zwei Jahren mit eigenem Material war die Band auf jeden Fall besser.

Weitere Headliner wie Haggard, Saxon, Crematory oder Amon Amarth liefen weitgehend an mir vorbei, dafür fand ich **Burden of Grief** recht gut. Und der Ersatz für Third Moon, ein Gruppe von minderjährigen (!) Death-Metallern namens Hackneyed, machte ordentlich Stimmung, wenn auch die Mitglieder der Band beim weiblichen Teil unserer Truppe eher Muttergefühle weckten.

Alles in allem also ein nettes Festival, dass leider wie jedes Jahr vom Wetter unnötig mitgenommen wurde. Wenn die Veranstalter jetzt noch die Organisation endlich einmal zu 100% hinbekommen, dann könnte sich das Rock Harz durchaus noch in größeren Rahmen entwickeln. Aber eigentlich will ich das gar nicht, und die Bewohner von Förste sicher auch nicht...
