---
title: "Bücher-Kurzbesprechung"
date: "2008-05-28T22:35:10"
categories: [gelesen]
---

Damit meine Bücher nach dem Lesen an ihren angestammmten Platz im Bücherregal wandern, habe ich mir die Selbstverpflichtung auferlegt, zu jedem einen Blog-Eintrag zu verfassen. Doch nicht zu allen Werken finde ich Zugang und verschiedenste Gründe können einen Artikel verhindern, den ich bereit bin online zu stellen. Damit sich kein zu großer Stapel auf meinem Schreibtisch bildet, will ich nun zumindest kurz etwas über zwei Titel schreiben.

**Fiesta: The sun also rises**

*von Ernest Hemingway,
erschienen bei Arrow Books, ISBN 978-0-099-90850-0, 6,99£*

Hemingway ist bis jetzt vollkommen an mir vorbei gegangen. Nun habe ich dieses Buch von einem guten Freund geschenkt bekommen und ziemlich schnell gelesen; den Inhalt jedoch nur an mir vorbeiziehen lassen. Es geht um einige befreundete Amerikaner (Künstler und Journalisten), die sich nach dem ersten Weltkrieg in Paris niedergelassen haben und den Sommer zusammen in Spanien verbringen wollen: Erst Angeln in den Pyrenäen, dann die berühmte Fiesta mit Stierkämpfen in Pamplona. Doch die einzige Frau in der Runde schafft es, die Männer gegeneinander aufzubringen und zieht dann doch mit einem jungen Stierkämpfer von dannen.

So leicht wie sich diese Zusammenfassung schreibt, ist auch das Buch selber geschrieben. Es lebt von dem sprunghaften Schreibstil Hemingways und der Atmosphäre, die Paris und Spanien in den 20er Jahren ausstrahlen. Dem angemessen plätschern die 215 Seiten so vor sich hin; keine Spur von Tragik oder einem großen Finale findet sich und am Ende ist fast alles wie zu Beginn des Romans. Ich sehe mich ehrlich gesagt nicht in der Lage, das Werk ausreichend zu interpretieren und belasse es deshalb bei dieser Kurzbe<del datetime="2008-05-28T21:36:42+00:00">sprechung</del>schreibung.

**Die Filmerzählung - Acht exemplarische Analysen**

*von Eberhard Ostermann,
erschienen beim Wilhelm Fink Verlag, ISBN 978-3-7705-4562-9, 19,90€*

Auf der Suche nach Interpretationsansätzen für Filme wie [Caché](/blog/2008/02/17/die-ganze-kraft-einer-gesellschaft/) oder Swimming Pool bin ich auf dieses Buch gestoßen. Der Autor hat es sich zum Ziel gesetzt, Filme auf der Ebene der Erzählung zu interpretieren, um den Leser zu Ähnlichem anzuregen. Dabei gibt er im Vorwort selber zu, dass eine Herauslösung der Handlung aus dem Gesamtkunstwerk Film diesem niemals gerecht werden kann. Zum Glück hält er diese selbstgesetzte Grenze nicht immer ein, der Schwerpunkt jeder der acht Analysen liegt jedoch immer im Bereich der Erzählung.

Für *Caché* liegt er weitgehend auf meiner Linie, bei *Swimming Pool* dagegen habe ich einige Aha-Erlebnisse beim Lesen gehabt. Auch die Analysen von *Cast away* und *Mystic River* sind interessant, jedoch hatte ich bei beiden Filmbesprechungen das Gefühl, dass der Autor mehr hineininterpretiert hat, als das Material zulässt. Der durchgängige Versuch, Freuds Ödipuss-Komplex in allen Werken wiederzufinden, fällt sogar negativ auf. Trotzdem liest sich das Buch gut und schnell und hat meine Erwartungen erfüllt - für das zeitgenössische Kino sind Werke dieser Art rar gesät.

Ich habe jedoch nach den genannten vier Filmen eine Pause eingelegt, um mich an den berechtigten Hinweis im Vorwort zu halten. Damit eine Analyse wirklich verstanden werden kann, muss man den Film zumindest gesehen haben und im Idealfall danach erneut rezipieren, um das Verständnis zu erhöhen. Bei *Breaking the waves*, *The sweet Hereafter*, *Birth* und *Taste of cherry* ist diese Voraussetzung für mich nicht erfüllt. Mein Festplattenrekorder ist jedoch ständig scharf geschaltet, so dass ich die restlichen Filme bald nachzuholen gedenke.
