---
title: "Die Rückkehr der Sofortbildkameras"
date: "2011-08-21T23:25:25"
categories: [gedacht]
---

Es gab Zeiten, da führte der Weg von der Aufnahme eines Fotos bis zum fertigen Bild, welches man in der Hand hielt, über die Entwicklung eines Films - ein Prozess, der viel Zeit in Anspruch nahm. Schneller ging es mit den von Polaroid hergestellten Sofortbildkameras, bei denen direkt aus der Kamera ein sich selbst entwickelndes Bild kam. Doch mit dem Siegeszug der Digitalkameras und der Möglichkeit, Fotos vom eigenen Drucker sofort auf Papier zu bringen, kam das Ende für dieses Kamerasystem - Polaroid stellte ab 2008 keine neuen Filme mehr her.

Ich selber war nie ein Fan der meist qualitativ fragwürdigen Sofortbilder, doch einige Künstler setzten die Kameras durchaus kreativ ein und sorgten mit ihrer Nachfrage dafür, dass es nun wieder neue Sofortbildkameras gibt - und das nicht nur von Polaroid. Doch warum sollte jemand in Zeiten, in denen es möglich ist, tausende Fotos zu knipsen und kostengünstig zu speichern und katalogisieren, sich freiwillig auf ein teures (1€ pro Foto), unvollkommenes Produkt einlassen?

Es ist vermutlich genau diese weite Verbreitung der Dauerknipserei, die zu einer Verweigerungshaltung führt. Gegen diese Überflutung mit immer perfekter werdenden Bildern von Jedermann kann nur angegangen werden, indem ihnen individuelle Originale entgegengesetzt werden. Kein massenhafte Ansammlung von digitalen Kopien mehr, deren Verbreitung im Internet keine Grenzen gesetzt sind, sondern analoge Einzelstücke, die kein Facebook oder Google nach Gesichtern scannen kann.

Ob diese Flucht vor der gleichmachenden Netzkultur wirklich einen dauerhaften Markt für Sofortbildkameras schafft, bezweifel ich jedoch. Wenn der Hype vorbei ist und auf jeder Party Polaroids geschossen werden, werden andere Lifestyleprodukte ihren Platz einnehmen und die Nachfrage zurückgehen. Dann muss sich Polaroid erneut der Frage stellen, ob sie ein Produkt am Leben erhält, dass so untrennbar mit dem Firmennamen verbunden ist wie sonst kaum ein anderes.
