---
title: "Deutschland, Europa und die Reisepässe"
date: "2008-01-31T19:42:05"
categories: [gedacht,gefunden]
---

Gestern habe ich mich schon kurz über die Tendenz einiger Minister ausgelassen, die demokratischen Hürden der deutschen Gesetzgebung auf europäischer Ebene zu umgehen. Ein weiteres Produkt dieser Taktik sind die biometrischen Ausweise, die seit November 2007 zur systematischen Erfassung der Fingerabdrücke aller europäischer Bürger genutzt werden, ohne dass es einen Bedarf für die angeblichen Sicherheitsgewinne gibt. Zum Einen war der alte Ausweis sehr fälschungssicher, zum Anderen verlangt kein anderes Land diesen biometrischen Standard - die USA nehmen Einreisenden lieber selber die 10 Fingerabdrücke ab - und innerhalb der EU ist er dank Schengen komplett unnötig. Ganz abgesehen von der eingesetzten unsicheren RFID-Technologie und den Möglichkeiten, die digitalen Daten auf dem Ausweis nach einmaligem Auslesen dauerhaft zu speichern - wir liefern jedem anderen Land dieser Welt die Inhalte des Passes auf dem Silbertablett.

Doch diese Argumente haben auf keiner politischen Ebene Auswirkungen gezeigt, und dagegen versucht jetzt die [Schriftstellerin Juli Zeh juristisch vorzugehen](http://blog.zeit.de/bittner-blog/2008/01/31/finger-weg-von-meinen-fingern_21). Sie unterstellt zudem den ehemaligen Innenminister Schily Befangenheit, da dieser nach dem Ende seiner politischen Laufbahn in den Aufsichtsrat einer Firma wechselte, deren Geschäftsmodell auf biometrischer Technologie basiert.

Große Chancen auf Erfolg hat diese Klage zwar aus meiner Sicht nicht, da zumindest die Parlamente von EU und Deutschland dem Gesetzesvorschlag zugestimmt haben und es keine direkten Einschnitte in die Grundrechte der Bürger gibt. Doch vielleicht ringt sich das angerufene Bundesverfassungsgericht zu einer Entscheidung bezüglich der Legitimität des Gesetzgebungsweges über Brüssel durch. Ein Abschaffung der aktuellen Ausweisdokumente als Maximalerfolg wäre jedoch ein Traum - mein Pass als einer der letzten ohne ditigale Inhalte gilt nämlich nicht mehr lange!
