---
title: "Die GEZ ist tot, lang lebe die GEZ"
date: "2010-06-09T22:09:12"
categories: [gedacht,gefunden]
---

Es ist Hochsommer in unserem schönen Land. Die sich im WM-Fieber befindenden Deutschen nutzen dies für ausgiebiges Grillen oder Chillen in den Beachbars. Der ideale Zeitpunkt also für die Regierung, ein Gesetz unterhalb der allgemeinen Aufmerksamkeitsschwelle schnell und ohne breite Diskussion in den Medien durchzubringen.

Nun mag die Gebührenfinanzierung des öffentlich-rechtlichen Rundfunks im Vergleich zum ebenfalls angegangenen Rückbau des Sozialstaates kein spannendes Thema sein, doch zumindest in meinem Bekanntenkreis gibt es eine breite Abneigung gegen diese Behörde und die teilweise angewandten Spitzelmethoden, mit denen Nichtzahler ausfindig gemacht werden. Aus meiner Sicht war eine Reform der Gebührenerhebung längst fällig; ich hätte mir ein einfaches System gewünscht, das gleichzeitig sozial ist, den Bürger so wenig wie möglich seiner Daten preisgeben lässt und die Behörde selber überflüssig macht. Eine Finanzierung als Einkommensteuer wäre ein Beispiel dafür.

So ist es jetzt aber nicht gekommen. Das [neue Finanzierungsmodell](http://www.sueddeutsche.de/medien/rundfunk-neues-gebuehrenmodell-alle-zahlen-und-die-gez-schnueffler-bleiben-daheim-1.956461) sieht nach einem Kompromiss eines typischen Verhandlungsmarathons aus, in dem die ursprünglichen Ziele der beteiligten Parteien nur noch zu erahnen sind. Wichtigstes Ergebnis: Die Behörde bleibt bestehen, wenngleich die Spitzeltätigkeiten gegen einen Datenabgleich mit den Einwohnermeldeämtern ausgetauscht wird. Denn es soll keine Gerätegebühr mehr geben, sondern eine Haushaltsgebühr. Die GEZ muss also fortan nur noch feststellen, was ein Haushalt ist, der Mieter oder Besitzer muss danach für die Gebühr aufkommen. Im Endeffekt wurde eine Kopfpauschale gegen die andere ausgetauscht; und auch weiterhin wird es Probleme geben diejenige Person ausfindig zu machen, die am Ende zahlt. Zudem wurde es versäumt, einen einfachen Weg für die Befreiung von der Gebührenpflicht zu gehen; Bedürftige und sozial schwache Mitglieder der Bevölkerung müssen weiterhin bürokratische Hürden überwinden, die eine Erhaltung der GEZ notwendig machen.

Es wurde somit eine Chance vertan, einen wirklich großen Schritt zu machen. Ob das neue Modell die gesteckten Ziele erfüllt, einfacher und gerechter zu sein, muss ich doch stark anzweifeln. Zumindest sind jedoch die Zeiten der direkten Bespitzelung durch GEZ-Mitarbeiter bald vorüber; indirekt nutzt Vater Staat nun einfach stärker die ohnehin vorhandenen Daten der Einwohnermeldeämter (die m.W. bisher auch an die GEZ weitergeleitet wurden). Für mich als Gebührenzahler ändert sich also nichts - und das ist traurig!
