---
title: "Krefelder Pinguine vs. Kölner Haie"
date: "2005-09-10T00:00:55"
categories: [gewesen]
---

Der [Verein mit dem hässlichen Pinguin](http://www.krefeld-pinguine.de/) als Maskottchen hat mit dem [Königpalast](http://www.koenigpalast.de) eine neue Spielstätte gefunden. Wie nicht weiter verwunderlich in den heutigen Zeiten stammt der Name der Arena von einem Sponsor, der die Anlage bewirtschaftet und leider auch das Bierangebot bestimmt. Ansonsten ist die Halle aber modern ausgestattet und eine sehr schöne Spielstätte (mir fehlt da aber der Vergleich, die Hallenser [Einssporthalle](http://www.eissporthalle.com/) ist alt und marode), wenngleich sie von außen wie ein zu groß geratenes IKEA-Regal aussieht.
Wegen unseren Gastgebern und deren Freunden standen wir mit unseren alten [Haie](http://www.haie.de/)-Trikots mitten im Stehblock der Pinguine, die sich aber alle als sehr fair erwiesen. Beim Fußball hätte ich mir dies nicht getraut. Eine natürliche Feindschaft zwischen den Städten am Rhein existiert zwar, äußerte sich jedoch nur in den "kreativen" Liedern, die meist das Wort "Scheiß" und einen austauschbaren Städtenamen im Refrain enthielten.
Als Laie im Eishockeysport bin ich leider nicht sehr regelfest, und des öfteren wusste ich nicht, wo überhaupt der Puck steckt oder warum gepfiffen wurde oder auch nicht. Generell hatte ich den Eindruck, dass das angenehm schnelle Spiel etwas unter den Regeln leidet. Doch die tolle Stimmung in der Halle (über 6000 Besucher) war ansteckend und als dann 10 Minuten vor Schluss auch noch die Haie beschlossen, sich an dem Spiel zu beteiligen, kochte der Pinguine-Block regelrecht.
Wie es die schlechten Kölner schließlich schafften, dass Spiel noch zu drehen und aus dem sicheren 2:0 der Krefelder ein 2:3 (vier Sekunden vor Abpfiff) zu machen, kann ich nicht sagen. Es hat jedoch riesigen Spaß gemacht, in der Halle zwischen all den Fans zu stehen und es mit zu erleben!
