---
title: "Schöne Scheine"
date: "2007-10-14T22:16:14"
categories: [gelesen]
---

*von Terry Pratchett,
erschienen bei Manhattan, ISBN 978-3-442-54631-2, 19,95€*

Da ist er nun, der neue Scheibenweltroman, und spielt leider wieder in Ankh-Morpork. Terry Pratchett kann scheinbar ohne die Wache oder Lord Vetinari kein Buch mehr schreiben, während mich dies zunehmend anödet. Die Hexen finden nur noch in der parallelen Kinderbuchserie statt und Rincewind oder Tods Nichte sind schlicht nicht mehr existent. So ist es mir zum ersten Mal passiert, dass mich ein Pratchett zu Beginn gelangweilt hat, weil die immergleichen Pfade inzwischen zu ausgetreten sind.

Dies liegt auch daran, dass sich Pratchett mit dem gleichen Thema wie in [Ab die Post](/blog/2005/09/04/ab-die-post/) noch einmal beschäftigt, nur diesmal mit der Beschränkung auf den Bankensektor - also genau die Branche, in der ich mich beruflich herumtreibe. Dies mag einer der Gründe sein, weshalb ich mich nicht über die Darstellung derselben in der Scheibenwelt amüsieren kann. Ich weiß leider, wie seltsam das System funktioniert, und kann deshalb nicht darüber lachen, da ich es eher traurig finde. Zudem tut der Held (erneut Feucht von Lipwig) nichts anderes als schon bei seinem letzten Auftritt - wenn dies so weitergeht, hat er in ein paar Romanen die ganze Stadt saniert.

Bei der Übersetzung des Buchtitels ins Deutsche hat der Verlag erneut nicht einmal versucht, das englische Wortspiel *Making Money* in unsere Sprache zu übertragen (Geld verdienen bzw herstellen) und das Titelbild wurde nicht von der englischen Ausgabe übernommen, sondern <del datetime="2007-10-24T20:08:49+00:00">noch schlechter selbst entworfen</del> leider von der amerikanischen Version. Aber dies hat ja Tradition bei den deutschen Ausgaben der Scheibenweltromane, und der neue Übersetzer reiht sich ein in diese Reihe von qualitativ schwachen Arbeiten. Es wird wohl doch langsam Zeit, auf die Originale umzusteigen, selbst wenn dies einen Bruch in meinem Bücherregal bedeutet.

*Schöne Schein*e ist also der erste Pratchett seit langem, den ich nicht empfehlen kann - zudem in der deutschen Übersetzung kaum noch etwas vom Humor des Originals übrig bleibt. Gleichzeitig fehlt dem Roman die Frische früherer Werke, weite Teile des Buches kommen einem altbekannt vor und der Karikatur der Bankenwelt fehlt es eindeutig an Bissigkeit. Schade, hier haben Terry Pratchett und vor allem der neue Übersetzer viel Potential verschenkt...

