---
title: "Die Liga der außergewöhnlichen Gentlemen"
date: "2003-10-08T00:00:19"
categories: [gesehen]
---

*USA/Tschechien (2002)
Regie: Stephen Norrington
Darsteller: Sean Connery (Allan Quatermain), Stuart Townsend (Dorian Gray), Peta Wilson (Mina Harker), Tony Curran (Rodney Skinner), Shane West (Tom Sawyer), Naseeruddin Shah (Captain Nemo), Jason Flemyng (Dr. Jekyll / Mr. Hyde), Richard Roxburgh (M) und andere  (gewöhnliche) Gentlemen*
[Offizielle Homepage](http://www.die-liga-der-aussergewoehnlichen-gentlemen.de/)

Im Jahre 1899, kurz vor der Jahrhundertwende, versucht der Superschurke "Fantom" die Mächte Europas gegeneinander aufzuhetzen, damit diese für einen Krieg rüsten und seine fortschrittlichen Waffen kaufen. Doch das Empire schickt eine Gruppe aus literarischen Superhelden los, um diesem Fantom Einhalt zu gebieten. Neben dem gealterten Quatermain gehören auch so illustre Gestalten wie Dorian Gray, Captain Nemo, Dr. Jekyll und Tom Sawyer zu dieser Liga, die dem Fantom hinterherjagd und verhindern will, dass dieser einen Anschlag auf ein Treffen der europäisches Staatsoberhäupter in Venedig verübt. Doch der Schurke scheint nicht nur die neuste Waffentechnik zu besitzen, sondern hat es auch geschafft einen Spion in die Liga einzuschleusen...

Dieser Film hat wohl die außergewöhnlichste und fantastischste Idee seit langem: Als Gegenschlag zu den vielen aktuellen amerikanischen Superhelden-Blockbustern geht es hier um eine Gruppe Superhelden aus dem Jahr 1899, die allesamt aus literarischen Vorlagen stammen. Diese Liga von Menschen mit ihren Fähigkeiten, die den Hirnen so berühmter und populärer Autoren wie Jules Verne, Oscar Wilde und Mark Twain entstammen, setze man nun in eine düstere, postviktorianische Zeit vor der vorletzten Jahrhundertwende und lasse sie gegen einen Gegner antreten, der ebenfalls über Fähigkeiten verfügt, die zeitigstens 20 Jahre später in ähnlicher Form überhaupt realisiert wurden.

Diese Geschichte stammt aber mitnichten aus der Feder eines kleinen Schreiberlings in Hollywood, sondern basiert auf einem Comic von Alan Moore, der auch schon die Vorlage für [From Hell](/blog/2002/03/05/from-hell/) lieferte und scheinbar Gefallen am England zum vorletzten Millenium gefunden hat.

So fantasievoll der Ansatz und der Storybogen der Geschichte sind, so misslungen ist deren Umsetzung. Die Geschichte sprintet geradezu von einem Schauplatz zum nächsten und überhäuft den Zuschauer mit Action und Verfolgungsjagden. Die wenigen ruhigen Szenen reichen da bei weiten nicht aus, um die Charaktere besser zu beleuchten und kennen zu lernen. Dabei trifft auch hier die gleiche Feststellung wie bei [X-Men 2](/blog/2003/05/05/x-men-2/) zu: Viele Köche verderben den Brei, und zu viele Hauptpersonen bekommen nicht genügend Raum zur Entfaltung. So hat nur derjenige Freude an den Akteuren, der sie bereits aus den Büchern kennt; an dieser Stelle wurde im Film viel verschenkt. So schafft es auch keiner der Darsteller aus der Drehbuch-Eindimensionalität auszubrechen; allein Sean Connery ragt mit seiner Routine aus dem Ensemble hervor, wenngleich man ihm sein Alter mehr als deutlich ansieht und er langsam aber sicher von Action-Rollen absehen sollte um glaubhaft zu bleiben.

Auch bricht der Film mit verschiedenen Konventionen. Zum Einen gibt es wohl keinen Nemo-Film, in dem dieser als langbärtiger, asiatisch kämpfender Inder dargestellt wird und auch seine Nautilus wurde so noch nie dargestellt; zum Anderen hat man die Figur des Mr. Hyde ein bißchen übertrieben, so dass dieser wie ein schlechter Hulk-Verschnitt aussieht. Dies macht es dem Zuschauer nicht gerade einfacher, mit den Personen klar zu kommen.

Bei der Nautilus und Mr Hyde kommt noch ein weiterer Faktor verschärfend hinzu: Die Spezialeffekte sind einfach grottenschlecht! Die Nautilus hat in der Fernansicht kaum Details; und während sie in London auf der Themse noch Titanic-Ausmaße hat passt sie 20 Minuten später problemlos durch die Kanäle von Venedig. Auch Mr. Hyde kommt nicht sehr überzeugend her, da sehen die Monster in aktuellen Ego-Shootern realistischer aus. Das Ganze setzt sich fort mit grottenschlechten Explosionen, die nicht richtig ins Bild passen, einem Venedig dass scheinbar nur aus simplen Domino-Häusern besteht und einem Matte-Painting von London wie es StarTrek nicht schlechter könnte. Zusammen mit der generellen Detailarmut bleibt nur ein Fazit zu ziehen: Der Film hat die schlechtesten Spezialeffekte seit [Resident Evil](/blog/2002/03/20/resident-evil/)!

Umso ärgerlicher ist es, dass trotzdem so viel Gebrauch davon gemacht wird - weniger, aber dafür gute CGI-Animationen und mehr Dialoge hätten dem Film besser gestanden. So bleibt nach dem "überraschenden" Ende (schön dass auch der Bösewicht eine literarische Figur ist) nur festzustellen, dass man trotz der vielen Unzulänglichkeiten gut unterhalten wurde.

Fazit: Mal wieder wurde eine gute Idee durch ein schlechtes Drehbuch und ein schwache Umsetzung ins Bild verschwendet. Am Ende bleibt zwar ein Film mit Unterhaltungswert übrig, aber ein Kinobesuch lohnt sich dafür nicht.
