---
title: "Kubuntu runs my Playstation"
date: "2008-09-21T16:57:41"
categories: [getan,gespielt]
---

Seit vier Wochen nenne ich eine Playstation 3 mein Eigentum. Dies liegt zum Einen darin begründet, dass mein Full-HD-Fernseher natürlich einen entsprechenden Full-HD-Zuspieler benötigt (und die PS3 ist momentan der beste Blu-Ray-Player) und zum Anderen, dass ich aufgrund meines noch gut laufenden Laptops nicht in neue PC-Hardware für GTA IV investieren wollte. Und was macht ein Informatiker mit seinem neuen Spielzeug? Er installiert erst einmal ein Linux!

Ganz so einfach wie auf einem PC ist dies leider nicht, aber [es gibt genügend Hilfe für das von mir geschätzte Ubuntu](http://psubuntu.com/). Zudem hat Sony die Playstation selber schon für Linux vorbereitet, wenn auch mit abgespecktem Hardware-Zugang. 256MB RAM und keine Grafikbeschleunigung lassen keinen Platz für einen modernen Desktop wie Gnome oder KDE (letzteres ist zum Sterben langsam). Damit ich aber trotzdem eine grafische Oberfläche habe, werde ich wohl auf XFCE wechseln.

Momentan habe ich noch Probleme, die Playstation korrekt zu rebooten - ein manueller Ausschaltvorgang am Netzteil ist notwendig. **[Update]**Wie ich jedoch gerade herausfand, ist dies kein Boot-, sondern ein Shutdown-Problem - Ubuntu lässt sich einfach nicht herunterfahren.**[/Update]** Doof ist auch, dass die PS3 genau 2 USB-Anschlüsse hat. Wenn ich meine externe Platte anstöpsele, muss ich die Maus entfernen, damit mir zumindest die Tastatur zum Arbeiten bleibt.

Gerade habe ich das Anlegen einer Sicherheitskopie einer Blu-Ray-Disk auf Platte nach über einer Stunde und knapp 14GB aufgegeben. [Da geht aber hoffentlich noch mehr](http://rtfm-nub.blogspot.com/2007/11/installing-gutsy-on-ps3-and-musings-on.html). Schließlich will ich noch den Siraxis-Controller und das WLAN zum Laufen bekommen und begutachten, was für Medien man so mit der Hardware abgespielt bekommt - die Unterstützung im PS3-Betriebssystem ist ja leider sehr limitiert.
