---
title: "Eine schwere Entscheidung"
date: "2011-03-14T21:12:41"
categories: [gedacht]
---

Eigentlich wollte ich Anfang April nach Japan fliegen. Die Flüge sind gebucht, Hotels reserviert und ein [Japan Railway Pass](http://www.japanrailpass.net/) gekauft. Doch nun stehe ich vor einer Entscheidung, die mir nicht leicht fällt.

Denn Japan reizt mich als Reisezeil schon sehr. Ich habe mich seit zwei Monaten mit der Kultur der Asiaten auseinandergesetzt und mir Ziele gesetzt, die ich unbedingt sehen will. Ich will in einem Tempel und einem Ryokan übernachten, in Onsen baden und möglichst viele Seiten des Landes kennenlernen.

Doch fliege ich in ein Land, das gerade eine Naturkatastrophe erlebt hat und diese erst verarbeiten muss? Fliege ich in ein Land, in dem es gerade gefährliche Störfälle in Atomkraftwerken gibt, von denen weder ein Ende noch die Auswirkungen bekannt sind? Setze ich mich möglicherweise einer gefährlichen Strahlung aus und einer Nahrungsversorgung, die vielleicht nachhaltig verseucht ist?

Die Entscheidung fällt deshalb so schwer, weil das Risiko nicht abschätzbar ist. Die japanische Regierung versucht natürlich, erst einmal ruhig zu bleiben und keine Ängste zu schüren. Doch wie groß die Gefahr ist, bleibt im Dunkeln. Und ich habe ehrlich gesagt keine Lust, mein Leben und meine Zukunft für einen tollen Urlaub aufs Spiel zu setzen.

Ein wenig Zeit habe ich noch, diese Entscheidung zu treffen. Zeit, um auf mehr Informationen und eine Beruhigung der AKWs zu warten. Bis dahin hoffe ich das Beste, für mich aber vor allem für die Japaner - eine atomare Katastrophe würde das so eng besiedelte Land in einer unvergleichbaren Härte treffen, die ich mir nicht vorstellen will.
