---
title: "And another thing..."
date: "2009-10-30T19:12:10"
categories: [gelesen]
---

*von Eoin Colfer,
veröffentlicht von Hyperion, ISBN 978-1-4013-2358-5, 12,95€*

Es gibt nicht viele Werke der Popkultur, die im typischen Arbeitsalltag eines ITlers so oft zitiert werden wie die Buchserie *Per Anhalter durch die Galaxis*. Die Zahl [42](http://de.wikipedia.org/wiki/42_(Antwort)) als Antwort auf alle Fragen ist zum geflügelten Wort geworden und selbst die [NASA](http://twitter.com/LCROSS_NASA) begleitete ihr [Mondbombardement](http://www.spiegel.de/wissenschaft/weltall/0,1518,654142,00.html) mit einem [Zitat](http://www.guardian.co.uk/books/2009/oct/12/nasa-lcross-hitchhikers-guide-twitter) aus dem *Anhalter*.

Leider ist der Autor Douglas Adams 2001 verstorben, so dass den fünf Teilen der Trilogie (!) kein weiterer folgte. Nun hat jedoch die Witwe von Adams Eoin Colfer die Erlaubnis erteilt, einen sechsten Band zu verfassen, und da musste ich nicht lange überlegen, mir das Buch zuzulegen. Colfer ist bisher hauptsächlich durch die Buchserie [Artemis Fowl](http://de.wikipedia.org/wiki/Artemis_Fowl) in Erscheinung getreten, von denen ich aber noch keines gelesen habe.

Leider kann der neue Band die Qualität der Vorgänger nicht halten. Dies fängt damit an, dass Colfer hauptsächlich Elemente und Zitate aus den anderen fünf Büchern variiert, aber kaum eigene Akzente setzt. Wieder wird die Erde durch die Vogonen zerstört, wieder rettet Zaphod Beeblebrox mit dem Unwahrscheinlichkeitsantrieb die Situation, wieder wird von den Magratheanern ein Planet als Eratz für die Erde gebaut und sogar die Kühe aus dem Milliways haben einen weiteren Auftritt. Dies geht so weit, dass er das Götter-Thema aus [Adams zweiten Dick-Gently-Roman](http://en.wikipedia.org/wiki/The_Long_Dark_Teatime_of_the_Soul) aufgreift. Nur Marvin fehlt (leider) in dieser Ansammlung von Zitaten.

Dafür trifft Colfer ziemlich gut den Humor der Adamschen Werke; Wortwitz und die gewohnten Einschübe mit Informationen aus dem Anhalter überzeugen. Das Highlight des Buches ist ein Bewerbungsgespräch mit Cthulhu um den Job als Gottheit eines Planeten, bei dem sehr geschickt die Mechanismen dieser speziellen Form des Dialogs offengelegt und karikiert werden. Ein wenig mehr technische Gags hätte ich mir jedoch gewünscht, schließlich gehören die Spielereien mit wissenschaftlichen Phänomenen zu einer guten Science-Fiction-Parodie einfach dazu.

So bleibt ein witziges Buch ohne eigenen Charakter übrig, dass in seiner Variation verschiedener *Anhalter*-Zitate zwar die Fans anspricht, aber doch hinter den Erwartungen zurückbleibt und einen faden (vorläufigen) Schlusspunkt unter die Serie setzt.
