---
title: "Sziget 2012"
date: "2012-09-04T00:01:14"
categories: [gehört,gewesen]
---

Seit Freunde von mir Anfang des Jahrtausends auf abenteuerliche Art und Weise mit osteuropäischen Regionalzügen nach Budapest gereist sind, um zu einem der größten Festivals der Welt zu kommen, wollte ich mir ein eigenes Bild von diesem *Sziget* machen, welches eine Woche lang eine Donauinsel mitten in der ungarischen Hauptstadt einnimmt.

Nun habe ich mir diesen Wunsch 2012 endlich erfüllt und bin mit vielen Impressionen zurückgekehrt. Am meisten hat mich wohl die Größe und Vielfalt des Festivalgeländes beeindruckt. Um vom Eingang, einer alten Eisenbahnbrücke, zur letzten der knapp 40 Bühnen zu kommen, war ich knapp 20 Minuten unterwegs, und passierte dabei unzählige Stände, Kunstinstallationen und andere Veranstaltungsorte. Denn das Sziget ist weit mehr als Musik und Camping, und es ist wunderbar international, sowohl was das Lineup als auch die Besucher angeht. Im Olympiapark habe ich mit vielen Franzosen deren erfolgreiches olympisches Handballfinale erlebt und im ungarischen Dorf gab es neben lokalen Spezialitäten auch ungarische Volkstänze zu erlernen.

Das Camping habe ich mir aber gespart und bin auf ein Hotel auf der Pester Seite von Budapest ausgewichen. Das war eine gute Entscheidung, trotz der teilweise sehr idyllischen Campinggrounds. Die meisten Zelte können nämlich in unmittelbarer Nähe der Bühnen unter dem Schutz von Bäumen aufgebaut werden, die nachts von Lampions oder Lichtschnüren bunt illuminiert wurden. Doch da Zelte wie Lebensmittel von den weit entfernt liegenden Parkplätzen geschleppt werden müssen und eine Woche Festival größere Vorräte erfordert, habe ich auf Bequemlichkeit gesetzt und lieber im klimatisierten Zimmer als bei 25°C im Mondlicht geschlafen.

Zudem leiden auch die Zelte unter dem größen Problem des Festivals: Dem Staub. Während Wacken dieses Jahr abgesoffen und im Matsch versunken ist, haben die Besucher des Sziget innerhalb weniger Tage jeden Grashalm der Insel in den Boden getreten. Der vom kontinentalen Sommerklima ausgetrocknete, sandige Boden der nicht befestigten Flächen stieg danach in großen Staubwolken in den Himmel auf, die sich auf Zelte wie Besucher gleichermaßen absenkten. Im Licht des Sonnenuntergangs haben sich so wirklich schöne Bilder ergeben, aber für die Atemwege war die Woche eine große Belastung.

So kam es auch, dass ich ziemlich schnell auf das Dosenbier des Festivals umgestiegen bin. Dieses war zwar teurer als ein frisch gezapfter Becher der gleichen Marke (Dreher), doch eine Büchse hat eine kleinere Öffnung, durch die sich Dreck in das Bier mischen kann. Geschmacklich und preiswert unschlagbar war dagegen das Bier auf der Fähre, dem für mich schnellsten und direktesten Weg vom Hotel auf die Insel.

Das Lineup konnte - vermutlich aufgrund des Absprungs eines der Hauptsponsoren - zum zwanzigsten Jubiläum nicht ganz das Niveau der Vorjahre halten. Zudem wurde entschieden, aus der Metalbühne einen Metaltag zu machen, und das am Dienstag, dem Tag vor der eigentlichen Festivaleröffnung. Ich bin da erst angereist und habe so **Moonspell** verpasst, kam zu **Lacuna Coil** aber gerade rechtzeitig. Eine Verteilung auf die Woche hätte mir besser gefallen, so lag der Schwerpunkt gefühlt eher abseits meines Geschmacks bei der elektronischen Musik.

Gefreut habe ich mich dagegen über die Show von **Placebo**, die tatsächlich an einem neuen Album arbeiten und einen Song daraus (*B3*) vorstellten. Als weiteres Highlight des Sets spielten sie eine Variation von *I know*, so dass ich am ersten Abend glücklich ins Hotel gefahren bin.

Nach langen Jahren der Pause war es schön zu sehen, dass auch die **Sportfreunde Stiller** nichts verlernt haben. Sie hatten ebenfalls ein paar neue Songs an Bord, zu deren Qualität ich mich nach einmaligem Hören nicht äußern möchte, doch am besten kamen die Klassiker bei den größtenteils deutschen Fans vor der Bühne an, so dass die Sportis in ihren Ansagen schnell von Englisch auf Deutsch wechselten. Begleitet wurden sie dabei von vier Frauen an Streichinstrumenten, die in ihren kurzen schwarzen Kleidern echte Hingucker waren.

**Korn** konnten da nicht ganz mithalten. Zum Einen missfiel mir die [strenge Unterteilung der Setlist](http://www.setlist.fm/setlist/korn/2012/obudai-sziget-budapest-hungary-3dcc59b.html), zum Anderen befand sich die Band während des Auftritts gefühlt häufiger hinter als auf der Bühne. Zwischen den Pausen haben sie es trotzdem geschafft, ihre Energie und Jonathan Davis Zerissenheit auf das Publikum zu übertragen. Bei der Auswahl der Songs aus dem aktuellen Album haben sie zudem genau die richtige Wahl getroffen, so dass der Stilwechsel nicht zu extrem ausfiel.

Eine große Lücke in meiner Sammlung der Konzerterfahrungen habe ich schließlich mit dem Konzert der **Beatsteaks** schließen können; gelten sie doch als eine der besten deutschen Livebands. Vor dem Unfall ihres Schlagzeugers Thomas Götz waren sie im Rahmen ihres *TWO DRUMMER SUMMER* mit zwei Drumsets unterwegs, die teilweise synchron oder einander unterstützend für einige spannende Abwandlungen ihrer Songs sorgten.

Weitere Erstkonzerte für mich waren **Maxïmo Park** (ganz gut), **SUM 41** (grauenhaft primitiv wie ihr Publikum), **Mando Diao** (mit starkem Finale) und **The Killers** (routiniert abgespult). Eine interessante Erfahrung war **Kakkmaddafakka**, eine norwegische Indie-Band, die nicht nur mit den zwei Backgroundsängern in Feinrippunterhemden eine ungewöhnliche Bühnenperformance ablieferten, die beim Publikum verdammt gut ankam.

Sehr geärgert hat mich dagegen eine Planänderung, die mit der verspäteten Ankunft der **Roots** zu tun hatte. Als Ersatz haben **Anti-Flag** den Platz auf der Hauptbühne eingenommen, nur leider anderthalb Stunden früher als im Programm angegeben. Zu diesem Zeitpunkt habe ich noch Budapest durchstreift und als ich - eigentlich pünktlich - auf die Óbudai-Insel kam, war der Auftritt schon vorbei. Ärgerlich.

Zum Schluss noch zwei Eindrücke, die gut die Zwiespältigkeit ausdrücken, mit der mir das Sziget 2012 im Gedächtnis bleiben wird. Auf der einen Seite wurden an manchen Tagen so viele Fahnen vor der Bühne geschwenkt, dass selbst ich als großgewachsener Mensch Probleme hatte, durch dieses Meer an Flaggen die Bühne zu sehen. Sehr berührt hat mich dagegen das häufige Spielen des Beastie-Boys-Covers *Sabotage*, mit dem die Bands dem im Mai verstorbene MC Adam Yauch die Ehre erwiesen - auf einem so großen Festival etwas derart familiäres zu erleben zeugt von der großartigen Atmosphäre des Sziget!
