---
title: "Der Kampf um die goldenen Ananasscheiben"
date: "2006-02-17T18:33:06"
categories: [getan]
---

... ist im vollen Gange, und nach sieben Wettkampftagen ist der Medaillenspiegel der [Olympischen Winterspiele](http://www.torino2006.org/ENG/OlympicGames/home/index.html) schon halbwegs aussagekräftig. Also habe ich mir gedacht, dass eine Übersicht der erfolgreichsten Nationen in der Sidebar ein nettes Feature für mein Blog wäre.

Auf [Yahoo](http://sports.yahoo.com/olympics/torino2006/medals) habe ich einen passenden [RSS-Feed](http://sports.yahoo.com/olympics/torino2006/medals/rss.xml) gefunden, welcher jedoch die seltsame Anzahl der acht besten Nationen liefert und diese in Reihenfolge der Gesamtzahl der Medaillen ordnet. Außerdem enthält das gelieferte XML nur HTML in einen CDATA-Block verpackt. Ich glaube nicht, dass dies im Sinne der Erfinder ist und werde deshalb noch nach einer besseren Quelle suchen; der Feed scheint auch nicht sehr häufig aktualisiert zu werden.

Also muss ich das Ergebnis des mit [lastRSS](http://lastrss.webdot.cz/) geparsten Feeds noch nach Medaillenwertigkeit ordnen und gebe momentan nur die drei besten Nationen aus, da diese mit hoher Wahrscheinlichkeit auch unter den Teams mit den meisten Medaillen sind. Gespannt bin ich nun, wie dieses Feature bzw dessen Verarbeitung die Ladezeiten meines Blogs verzögert.

<ins datetime="2006-02-19T20:32:30+00:00">**Update**: Einen besseren Feed habe ich nicht gefunden, dafür aber frei verfügbare Flaggenbilder auf [blogpotato](http://flags.blogpotato.de/). So dürfte der Medaillenspiegel hoffentlich die letzte Woche der Olympischen Spiele überstehen!</ins>
