---
title: "Waltz with Bashir"
date: "2009-01-28T21:16:30"
categories: [gesehen]
---

*Israel (2008)
Regie: Ari Folman
Darsteller: Ari Folman, Boaz Rein-Buskila, Ori Sivan, Ronny Dayag, Carmi Cna'an, Ron Ben-Yishai, Dror Harazi, Shmuel Frenkel*
[Offizielle Homepage](http://www.waltz-with-bashir.de)

Mein erster Film dieses Jahr ist nicht mehr ganz taufrisch, doch in Berlin gibt es zum Glück genügend Kinos und anspruchvolles Publikum, um solche Perlen wie *Waltz with Bashir* auch fast drei Monate nach dem Filmstart noch zu zeigen. Darin geht es um die Aufarbeitung des Regisseurs Ari Folman über seine Beteiligung am [Massaker von Sabra und Schatila](http://de.wikipedia.org/wiki/Sabra_und_Shatila). Er war für die israelischen Armee in unmittelbarer Nähe vor Ort, kann sich jedoch an nichts erinnern. Ein Albtraum eines Freundes und damaligen Weggefährten bringt ihn auf die Idee, seine Kriegskameraden zu befragen, um die verdrängten Erinnerungen zurückzuholen.

Diese Interviews erzählt er dokumentarisch für den Film nach, wählt dafür jedoch den Weg einer Animation, die mit ihrer ungewöhnlichen Form überzeugt. Optisch werden comichafte, grobe Zeichnungen im Vordergrund und detaillierte Landschaften mit digitalen Animationen vermischt. Manchmal wirkt dies unbeholfen (immer dann, wenn Gläser oder Joints an den Mund geführt werden), doch es entstehen auch beeindruckende Kamerafahrten und vor allem die Erinnerungssequenzen haben alle ihren eigenen Farbstil und vermitteln damit die Gefühle und Perspektiven der Interviewpartner.

Am Ende, als dann endlich auch die Erinnerungen des Erzählers zurückkehren und er seine eigenen Träume deuten kann, schaltet der Regisseur auf Originalaufnahmen nach dem Massaker um. Hier trifft es den Zuschauer noch einmal mit voller Wucht: Hinter der experimentellen und expressionistischen Fassade des Films verstecken sich echte Erinnerungen an reale Kriegsverbrechen; der Comic ist bittere Realität.

Und dies sind Erfahrungen, die Generationen von jungen Israelis machen mussten und noch immer müssen. Sie werden von der Regierung unvorbereitet von einem Krieg in den nächsten geschickt und müssen mit dem Erlebten klarkommen. So kommt es zu den verschiedenen geschilderten Verdrängungmechanismen der Kriegskameraden: Manche können das Erlebte einfach in ihrem Kopf verschließen, manche plagen ein Leben lang Albträume, andere fliehen davon in andere Länder; wiederum andere steigern die Erinnerung zu heldenhaften Taten.

Ari Folman hat Erinnerungen nur an die Heimaturlaube, an ein Israel, dass weiterlebte als würde man ein paar Kilometer im Norden nicht Krieg führen. Die Jungen habe Liebesprobleme und Rock'n'Roll im Kopf und erfüllen ohne Nachzufragen die ihnen aufgetragenen Unterstützungsaufgaben im Kampf um die politische Macht im Libanon, ohne die Hintergründe zu verstehen oder gar auf Tod und die anderen Greuel des Krieges vorbereitet worden zu sein. Die Führungskräfte unterstützen auch noch die Sicht des Urlaubs und leisten damit der Fehleinschätzung des Krieges Vorschub, doch was diese Erfahrungen in den Köpfen der jungen Männer anrichten, darüber machen sie sich keine Gedanken.

Erschreckend ist auch, dass Israel trotz dieser Aufarbeitung nach zwanzig Jahren immer noch mit gewisser Regelmäßigkeit Krieg führt und seine jungen Soldaten an die Front schickt. In Südamerika leben ganze Städte davon, dass die entlassenen Soldaten nach drei Jahren Dienst ihren Sold auf den Kopf hauen und die verpassten Jahre nachholen wollen, doch so einfach lassen sich manche Erinnerungen nicht immer unterdrücken.

Fazit: *Waltz with Bashir* ist eine mutige Aufarbeitung der israelischen Beteiligung an einem libanesischen Massaker. Die gewählte Form einer animierten Dokumentation weiß mit beeindruckenden Bildern zu überzeugen und wirft eine ungewohnte Perspektive auf das Geschehen. Sehr empfehlenswert!

**Update**
Der Regisseur arbeitet momentan an der Verfilmung von [Stanislaw Lem](/blog/?s=stanislaw+lem&submit=+%3F+)s Buch *Der futurologische Kongress* in derselben Animationstechnik. Ich bin begeistert und kann es kaum erwarten!
