---
title: "Midnight in Paris"
date: "2011-09-16T05:30:36"
categories: [gesehen]
---

[Woody Allen](/blog/?s=Woody+Allen) ist auf seiner Reise durch die [schönsten](/blog/2009/08/22/scoop-der-knuller/) [Städte](/blog/2008/12/24/vicky-cristina-barcelona/) Europas inzwischen in Paris angekommen und legt eine Hommage an die 20er Jahre der französischen Hauptstadt vor, die den für Allen-Verhältnisse enttäuschenden *Ich sehe den Mann deiner Träume* vergessen lässt. Dabei kopiert er die Charakterkonstellation des letzten Films (Autor in künstlerischer wie privater Krise) und reichert sie nur mit einer geradezu simplen Aussage und vorhersagbaren Story an. Warum also ist der der Film dann so viel besser als sein Vorgänger?

Dies liegt vor allem an seinem leichtfüßigen Spiel mit den Referenzen, die *Midnight in Paris* zu einem Schaulaufen der großen Künstler machen. Hauptakteur Gil Pender, mit Owen Wilson als Allens Alter Ego gut besetzt, ist durch Zufall in Paris auf die Möglichkeit gestoßen, jede Nacht in der Zeit zurück zu reisen. In den 1920er Jahren tummelte sich alles, was Rang und Namen hatte, in der Stadt an der Seine, und so trifft Gil auf seine großen Vorbilder Hemingway, T.S. Eliot und F. Scott Fitzgerald, lässt seinen Roman von Gertrude Stein begutachten und feiert Partys mit Salvador Dalí, Picasso und Luis Buñuel. Zudem fängt er eine Beziehung mit Picassos Geliebten Adriana an, die jedoch im Gegensatz zu Gil gar nicht so viel von ihrer eigenen Zeit hält. Sie würde lieber in der Bel Epoque leben und als sich ihr die Möglichkeit bietet, ebenso wie Gil die Zeit zu wechseln, folgt sie diesem Impuls und Gil muss seine eigenen Wünsche hinterfragen.

Wie gesagt, die Geschichte ist sehr einfach gehalten und dient eigentlich nur als Aufhänger, um den Film mit Anspielungen auf die Kunst- und Literaturgeschichte vollzustopfen. So ist Hemingway ständig auf Reisen (einmal auf Safari in Kenia, einmal mit einer [Freundin, die in einen Torrero verliebt ist, in Spanien](/blog/2008/05/28/bucher-kurzbesprechung/)) und Buñuel bekommt von Gil den Tipp, was man [mit einer Rasierklinge und einem Rinderauge](http://de.wikipedia.org/wiki/Ein_andalusischer_Hund) alles ausdrücken kann. In den Rollen der Künstler geben sich Filmstars wie Kathy Bates und Marion Cotillard die Klinke in die Hand, wobei mir Adrien Brodys witzig-überspitzte Darstellung von Dali am Besten gefallen hat.

Dazu kommen tolle Bilder wie aus einem Touristenführer (ich liebe [dieses Filmplakat](http://www.midnight-in-paris.de/)) und der übliche Woody-Allen-Humor verpackt in schnellen, sich gegenseitig überlagernden Dialogen. Dabei bekommt auch die Tea-Party-Bewegung in den USA ihr Fett weg, was den Film gleich noch sympathischer macht, als er in seiner mit Details vollgestopften Inszenierung ohnehin schon ist. Wer sich also nur ein wenig in Paris und mit der Kunst der 20er Jahre auskennt und den Humor von Woody Allen mag, der muss sich unbedingt *Midnight in Paris* und wird großartig unterhalten.
