---
title: "Mr. Monk macht wieder Pause?"
date: "2005-12-06T23:35:47"
categories: [gedacht]
---

Da freut man sich über den nahtlosen Übergang von der dritten zur vierten Staffel von Monk auf RTL, und plötzlich folgt der Bruch und nächste Woche kommt wieder eine Folge mit Sharona. Welchen Zweck dieser Ausstrahlungsrythmus wohl hat? Kommt die für die Synchronisation zuständige Firma nicht hinterher mit dem Übersetzen - schließlich hatte man sich bis auf drei Monate an die amerikanische Erstausstrahlung herangearbeitet.

Wenigsten gibt es momentan keine Episoden-übergreifenden Handlungsstränge, so dass dieses Aussetzen kaum auffällt. Und alle Folgen der zweiten Staffel habe ich auch noch nicht gesehen. Also bleibt mein Wunsch an RTL für das neue Jahr: Sichert den Sendeplatz für Monk ruhig mit alten Folgen, aber bald solten auch die aktuellen Episoden wieder folgen.

Ach ja: Man kann um diese Uhrzeit nicht auf RTL.de surfen, ohne von Unmengen von Erotik-Werbung gestört zu werden. Aber RTL wird schon wissen, was das Zielpublikum gerne sieht...
