---
title: "Hörspielkino"
date: "2010-04-18T19:07:46"
categories: [gehört,gewesen]
---

Weiter geht es mit der abwechslungsreichen Berliner Kultur. Im [Zeiss-Großplanetarium](http://www.sdtb.de/Zeiss-Grossplanetarium.25.0.html) in Prenzlauer Berg findet jeweils im Frühjahr und im Herbst die Veranstaltungsreihe [Hörspielkino unterm Sternenhimmel](http://www.radioeins.de/veranstaltungen/hoerspielkino/index.html) statt. Zu hören gibt es dabei ausgewählte Horspiele in der ungewöhnlichen Atmosphäre einer Planetariumskuppel, die während der Vorstellung einen sich langsam bewegenden Sternenhimmel zeigt.

Die Idee dahinter ist, dass die reduzierten visuellen Reize das Zuhören und damit die Aufnahme des Gehörten fördern. Und tatsächlich bietet das sich immer wieder ändernde Himmelszelt eine so noch nicht erlebte Projektionsfläche für das eigene Vorstellungsvermögen und die Akustik im Planetarium eine ungewohnte, aber sehr angenehme Räumlichkeit des Hörspiels. Etwas problematisch sind leider die Klappsessel des Großplanetariums, die über die zwei Stunden hinweg keine bequeme Sitzposition erlauben und damit immer wieder die Konzentration auf sich ziehen.

Warum die Veranstaltung allerdings das Wort *Kino* im Namen trägt hat sich mir nicht erschlossen. Zwar gibt es am Anfang eine an die Kinowerbung angelehnte Vorstellung des Konzepts und der Organisatoren, aber gerade die Möglichkeit der im Rund umherschweifenden Blicke unterscheidet das *Hörspielkino* von einem traditionellen Kinobesuch. Ebenso wird sich das Erlebte von Zuhörer zu Zuhörer deutlicher unterscheiden als bei einem Film, da die optische Wahrnehmung nicht vorgegeben ist und hauptsächlich im Kopf stattfindet. Raum für nachfolgende Diskussionen ist also genug gegeben, und in dem abwechslungsreichen Programm quer durch alle Genres sollte jeder ein Hörspiel nach seinem Geschmack finden!
