---
title: "Wieviel Demokratie hätten Sie denn gerne?"
date: "2008-04-27T20:53:54"
categories: [gedacht]
---

Und wieder hat die CDU lernen müssen, dass man auch mit finanzieller Unterstützung aus der Wirtschaft nicht beliebig Wahlergebnisse kaufen kann. Nach dem [verlorenen Bürgerentscheid um die Umbennung der Kochstraße](http://www.berlin.de/ba-friedrichshain-kreuzberg/verwaltung/org/wahlamt/buergerentscheid2.html) in meinem Bezirk Friedrichshain-Kreuzberg entwickelte sich [erwartungsgemäß](/blog/2008/04/21/jein-zu-tempelhof/) auch der heutige [Volksentscheid um die Erhaltung des Flughafens Tempelhof](http://www.wahlen-berlin.de/wahlen/volksentscheid-2008/Ergebnisse/ve08-proz.asp) negativ für die Initiatoren.

Ironischerweise hat den Entschluss für die Schließung anno 1996 die [CDU mitgetragen](http://www.tagesspiegel.de/berlin/Berliner-Flughaefen-Tempelhof-Konsensbeschluss;art1050,2323859). Aber damals wurden auch noch Volks- und Bürgerentscheide verteufelt, und heute geht es ja außerdem gegen den poltischen Gegner von links, da ist jedes Mittel recht. Dumm nur, dass der Berliner Bürger da nicht mitspielt - Mehrheiten verändern sich eben auch bei Sachfragen nicht so schnell.

Wenn aber selbst solche polarisierenden Themen wie der Flughafen Tempelhof und der riesige finanzielle Einsatz nicht genügend Wähler an die Urne locken, dann stelle ich mir persönlich die Frage, ob es überhaupt einmal zu einem erfolgreichen Entscheid auf Landesebene kommen wird. Oder ist das dahinterstehende Gesetz für direkte Demokratie vielleicht nur ein zahnloser Papiertiger mit Symbolcharakter und das Volk will gar nicht selber mitbestimmen und die Verantwortung auf sich laden?
