---
title: "Star Trek"
date: "2009-05-16T00:36:39"
categories: [gesehen]
---

*USA (2008)
Regie: J.J. Abrams
Darsteller: Chris Pine (James Tiberius Kirk), Zachary Quinto (der junge Spock), Zoe Saldana (Nyota Uhura), Simon Pegg (Scotty), Karl Urban (Leonard McCoy), John Cho (Hikaru Sulu), Anton Yelchin (Pavel Chekov), Eric Bana (Nero), Leonard Nimoy (der alte Spock), Bruce Greenwood (Christopher Pike), Ben Cross (Sarek), Winona Ryder (Amanda Grayson) und andere Sternenflottenabsolventen*
[Offizielle Homepage](http://www.startrekmovie.com/intl/de/)

Vor über sechs Jahren ging mit [Star Trek Nemesis](/blog/2003/01/20/startrek-x-nemesis/) eine Ära zu Ende. Die Qualität des Filmes war sinnbildlich für das gesamte Franchise, das auch im Fernsehen immer weniger Zuschauer anzog und in der Absetzung der [Enterprise](http://de.wikipedia.org/wiki/Star_Trek:_Enterprise)-Serie nach vier Staffeln gipfelte. Einen weiteren Neuanfang im Kino zu versuchen war deshalb eine mutige Entscheidung. Da man jeden Fan als Zuschauer gebrauchen kann, wurde keine neue Crew losgeschickt, sondern auf die bekannten Charaktere um Spock und Kirk zurückgegriffen und die Handlung in die Zeit vor der Originalserie verlegt. Gleichzeitig bekam Regisseur Abrams alle Freiheiten, einen Film nach aktuellem Zeitgeist zu drehen und damit das Zielpublikum zu vergrößern. Der Erfolg an der Kinokasse gibt dieser Strategie Recht, doch ist *Star Trek* wirklich ein so guter Film? Ich als Alt-Trekkie wollte dem natürlich auf den Grund gehen.

Erzählt wird die Geschichte, wie sich die Crew frisch von der Akademie kommend auf der Brücke der Enterprise durchsetzt. Man sieht, wie sich die einzelnen Charaktere kennenlernten und wie sie ihre erste schwere Mission meistern: Ein scheinbar übermächtiges Romulanerschiff ist durch ein schwarzes Loch aus der Zukunft zurückgekehrt und dessen Captain will Rache nehmen an den Vulkaniern und der Föderation, die in einer parallelen Realität die Zerstörung des Heimatplaneten der Romulaner nicht verhindert haben. Duch die Zeitreise nahm die Geschichte jedoch einen anderen Verlauf...

... und führt zu einem gewollten Bruch mit der Kontinuität des *StarTrek*-Universums. Die Zerstörung des Planeten Vulkan passt zum Beispiel gar nicht zu einigen *NextGen*-Folgen, die auf ebenjenem spielen. Doch diese Paralleluniversumsausrede reicht den Drehbuchautoren nicht und so präsentieren sie auch noch eine verworrene Zeitreisegeschichte um ein Superraumschiff der Romulaner, das eigentlich nur ein riesiger Minenfrachter ist und sich 25 Jahre lang im Gebiet der Föderation versteckt, um Logiklöcher ohne Ende in die Geschichte zu reißen (und Leonard Nimoy einen Auftritt in seiner alten Rolle zu bieten).

Dass dieser Schema-F-Plot überhaupt funktioniert liegt an der rasanten Inszenierung. Es wird ordentlich Action geboten, markige Sprüche kennzeichnen die Crew, bei der auch jedes Brückenmitglied Raum für die Vorstellung des Charakters erhält. Die Darsteller schaffen es dabei durchweg, ihre Vorbilder erkennen zu lassen, ohne aber wie Abziehbilder zu wirken. Das hat mich ebenso positiv überrascht wie die vielen liebevollen Anspielungen auf die Originalserie (nach dem ersten Außeneinsatz stirbt natürlich das Crewmitglied mit der roten Uniform). Schade nur, dass Uhura, Chekov und Sulu dabei auf wenige Aspekte beschränkt werden; gerade die dunkelhäutige Kommunikationsoffizierin war in den 60ern ein Aushängeschild als erste schwarze Offizierin im TV, die neue Interpration ist da ein Rückschritt in mit *TNG* überwunden geglaubte Rollenklischees.

Etwas nervig fand ich die Kameraführung. Es gab kaum eine ruhige Einstellung im gesamten Film; ständig wird schnell geschwenkt, umgeblendet oder herumgewackelt - dies hat mich schon beim letzten [Bond](/blog/2008/12/11/olga-in-action/) irritiert. Zudem ist irgendwer auf die Idee gekommen, dass [LensFlare](http://de.wikipedia.org/wiki/Lens_flare)-Effekte so toll sind, dass man sie in 90% aller Szenen einsetzt. Mit der Zeit gewöhnt man sich daran, aber ich hätte an der einen oder anderen Stelle schon gerne mehr von den Schauspielern oder den Kulissen gesehen als verdeckende Lichtreflektionen. So habe ich Winona Ryder gar nicht erkannt in der Rolle von Spocks Mutter und war überrascht bzw geradezu geschockt, dass sie inzwischen Charaktere dieses Alters spielt.

Fazit: *Star Trek* hat tatsächlich den Spagat geschafft einen zeitgemäßen Neuanfang zu bieten und gleichzeitig die Crew der Originalserie wieder aufleben zu lassen. Die schwache Story wird hinter viel Action und einer hypernervösen Kamera versteckt und das Ganze noch mit beeindruckenden aber teilweise auch nervenden Effekten garniert. Die Schauspieler überzeugen zudem in den bekannten Rollen. Bitter aufgestoßen sind mir dagegen die Modifizierungen am *StarTrek*-Universum und die von der Bildung der Crew in den Hintergrund gedrängte verworrene Geschichte um das Romulanerschiff.
