---
title: "Sucker Punch"
date: "2011-04-21T22:23:22"
categories: [gesehen]
---

*USA (2011)
Regie: Zack Snyder
Darsteller: Emily Browning (Baby Doll), Abbie Cornish (Sweet Pea), Jena Malone (Rocket), Vanessa Hudgens (Blondie), Jamie Chung (Amber), Carla Gugino (Dr. Vera Gorski), Oscar Isaac (Blue Jones), Scott Glenn (der Weise), Gerard Plunkett (Stiefvater) und andere Blaupausen*
[Offizielle Homepage](http://www.suckerpunch-derfilm.de)

Nach dem Tod ihrer Mutter erschießt eine junge Frau aus Versehen ihre kleine Schwester, als sie sie vor dem Stiefvater beschützen möchte. Dieser lässt sie deshalb in eine Nervenheilanstalt einweisen und bezahlt dort den Helfer Blue, damit er dafür sorgt, dass an der Stieftochter eine Lobotomie vorgenommen wird. In dieser Aussicht flüchtet sie sich in eine Traumwelt, in der sie mit anderen Insassen der Anstalt in einem Bordell arbeitet und an einem Fluchtplan arbeitet, während sie weiter davon träumt, es in Fantasiewelten als starke Kämpferin mit allen Gegnern aufzunehmen...

Bei Zack Snyder stand schon immer eine vom Comic inspirierte Optik im Vordergrund seiner Filme. *300* und [Watchmen](/blog/2009/09/07/watchmen/) als Comicverfilmungen inspirierten diesen Stil, doch auch in dem erstmals nach eigenem Drehbuch gedrehten *Sucker Punch* bleibt sich Snyder treu und setzt weiter auf die weichgezeichnete, zweidimensionale Darstellung mit ihren losgelösten Blickwinkeln und drehenden Kamerafahrten.

Die Actionsequenzen sind dann auch das Highlight des Films. Unterlegt vom textuell sorgsam ausgewählten, vorantreibenden Soundtrack (u.a. Björks "Army of me", Pixies "Where is my mind") dürfen die leicht bekleideten und gut anzusehenden Heldinnen in von überdrehter Gewalt strotzenden und jeglicher physikalischer Logik entbehrenden Kampfszenen gegen ganze Horden von Robotern, untoten Nazis und Drachen antreten. In ihrer extremen Stilisierung erinnern diese Teile des Films stark an Computerspiele.

Doch leider besteht nicht der gesamte Film aus diesen spektakulären Traum-im-Traum-Sequenzen. Zwischendurch verliert sich das Drehbuch in einer Vielzahl von Dialogen, die die eigentliche Story vorantreiben, es aber nicht schaffen, den Charakteren Tiefe zu geben oder gar eine Bindung des Publikums aufzubauen. Über platte Stereotypen findet *Sucker Punch* nicht hinaus, was jedoch irgendwie zum allgemeinen Stil des Filmes passt.

Dabei übersieht man fast, dass er verglichen mit [Inception](/blog/2010/09/19/inception/) das Thema der Träume als Zufluchtsort und Problemverarbeitungsstrategie viel ehrlicher angeht. Ist die erste Ebene noch recht nah an der Realität angesiedelt und ein Spiegelbild der echten Fluchtversuche, ist die zweite, tiefere Ebene eine Ausgeburt einer zügellosen Fantasie und dementsprechend abgedreht; die Hauptfiguren sind hier Kämpferinnen mit großer Stärke, denen alles gelingt, die sich gegen alle Hindernisse und Übel der Welt durchsetzen können - im Gegensatz zu den fast wehrlosen Wesen in der Realität. In den Grenzen seiner Stilisierung hat Zack Snyder für jede dieser Ebenen eine gute visuelle Umsetzung gefunden, die sie leicht unterscheidbar macht.

Zudem eröffnet das Ende eine weitere Interpretationsmöglichkeit, ausgehend davon, dass nur wenige Minuten des Films überhaupt die innerfilmliche Realität zeigen. Nimmt man nämlich an, dass die junge Frau, die zu Beginn unglücklich ihre Schwester erschießt, ihren Aufenthalt in der Heilanstalt tatsächlich verdient, weil sie sich selbst nicht unter Kontrolle hat und zu Gewaltausbrüchen neigt. Dann finden sich schnell Parallelen in der ersten Traumebene zwischen Baby Doll und Sweet Pea, die den Schluss nahelegen, dass die junge Frau in leichter Schizophrenie Teile ihres selbst auf andere Insassen übertragen hat. So hat auch Sweet Pea eine kleine Schwester, die sie beschützen möchte, und die doch sterben muss. Nur dass im Traum die Schwester sich für sie opfert, was dem unglücklichen Tod im Nachhinein eine gewisse Rechtfertigung verleiht. Beide Geschwister wollen jedoch zurück zu den Eltern, was in der Realität mit einer toten Mutter und einem Stiefvater, der sie aus dem Weg haben will, nur eben ein Wunschtraum ist. Ebenso wie die Vorstellung, dass es auch männliche Vorbilder, Vaterfiguren geben kann, in Form des alten Mannes, der beim Ausbruchsplan unterstützt.

In all dem äußert sich also der Wunsch nach einer heilen Welt, die in krassem Widerspruch zum tatsächlichen Handlungsablauf steht. Die Flucht scheitert, die junge Frau wird lobotomiert - und trotzdem zeigt Zack Snyder eine Art Happy End. Denn zum Einen werden die Vergehen von Blue endlich aufgedeckt, zum Anderen scheint die Lobotomie zumindest für Ruhe im Kopf der jungen Frau geschaffen zu haben, wenn auch zu einem hohem Preis - so jedenfalls interpretiere ich die letzte Szene, in der Sweet Pea endliche entkommen ist und in einem Bus sitzt, den der weise Mann steuert.

Fazit: *Sucker Punch* ist rasant inszeniertes Spaßkino, solange die comichafte Action für Ablenkung sorgt. Den Rest der Zeit dümpelt der Film in seiner Traumrahmenhandlung vor sich hin, die zwar mehr unter der schicken Fassade zu bieten hat, als offen sichtbar ist, aber in ihrer Inszenierung und Dramaturgie weitgehend  langweilt.
