---
title: "The Village - Das Dorf"
date: "2004-11-01T00:00:15"
categories: [gesehen]
---

*USA (2004)
Regie: M. Night Shyamalan
Darsteller: Bryce Dallas Howard (Ivy Walker), Joaquin Phoenix (Lucius Hunt), Adrien Brody (Noah Percy), William Hurt (Edward Walker), Sigourney Weaver (Alice Hunt), Brendan Gleeson (August Nicholsen), Cherry Jones (Mrs. Clack), Celia Weston (Vivian Percy), John Christopher Jones (Robert Percy), Judy Greer (Kitty Walker), Frank Collison (Victor), Fran Kranz (Christop Crane), Michael Pitt (Finton Coin), Jesse Eisenberg (Jamison), Zack Wall (Donald), Pascale Renate Smith (Marybeth) und andere Dörfler...*
[Offizielle Homepage](http://www.movie.de/filme/village/)

Das kleine Dorf Covington liegt friedlich innerhalb eines großen Waldes. Der Wald wird jedoch bewohnt von den Unaussprechlichen, bösartigen Wesen, die die Dorfbewohner dazu zwingen, die Grenzen des Waldes nicht zu übertreten. Der Dorfrat wacht auch eisern über die Regel, dass kein Rot gezeigt werden darf, denn diese Farbe lockt die Unaussprechlichen an. Doch dann kommt es zu einer verhängnisvollen Dreiecksbeziehung zwischen der blinden Ivy, dem introvertierten Lucius und dem zurückgebliebenen Noah, die dazu führt, dass Noah Lucius ein Messer in die Brust sticht. Jetzt kann nur noch Medizin aus der fernen Stadt das Leben des Jungen retten, doch wird dies der Dorfrat erlauben und wer soll die Gefahr auf sich nehmen, den Wald zu betreten...

Da ich die Vorgängerfilme sicherlich das eine oder andere Mal erwähnen werde, verlinke ich gleich zu Beginn die Kritiken zu [Unbreakable - Unzerbrechlich](/blog/2001/01/02/unbreakable-unzerbrechlich/) und [Signs - Zeichen](/blog/2002/09/24/signs-zeichen/). Und als Vorwarnung für alle, die den Film eventuell noch sehen möchten: Ich verrate hier praktisch die gesamte Handlung - also bitte nicht weiterlesen!

Trotz der eher schlechten Erfahrungen mit den letzten beiden Shyamalan-Filmen hatte mich die Vorschau doch so fasziniert, dass ich mir auch den vierten Film des gebürtigen Inders ansah. Und gerade wegen den letzten Enttäuschungen nach dem absoluten Highlight "The Sixth Sense" ging ich diesmal mit anderen Erwartungen ins Kino. Kein Warten auf die finale Pointe sollte den Genuss zerstören, sondern vielmehr der Weg das Ziel sein. Doch dabei tat ich Shyamalan bei "The Village" absolut Unrecht, denn dieser Film bleibt sich seiner Linie die gesamte Spielzeit über treu und führt die Geschichte auch zu einem konsequent logischen Ende (was man bei Signs nicht behaupten konnte), das den einen oder anderen Zuschauer sogar noch überraschen wird.

Bevor ich jedoch noch genauer auf den Inhalt eingehe, will ich kurz das Fachliche bewerten. M. Night Shyamalan hat nicht erst mit diesem Film seine ganz persönliche Handschrift gefunden. Bestimmte Elemente wie die ruhigen Dialoge und das bedächtige, aber zielstrebige Vorantreiben der Handlung (oft auf recht verschlungenen Pfaden) erkennt man sofort wieder; wie auch das Zusammenschneiden wichtiger Gesprächshappen kurz vor der Auflösung am Ende (und das Auftreten des Regisseurs himself innerhalb des Films). Dies kann man altbacken oder auch verwirrend finden (Shyamalan legt viele falsche Fährten wie z.B. den Grabstein mit dem Todesjahr 1897), es trägt jedoch ganz beträchtlich zur Stimmung des Filmes bei. Denn mit der ebenfalls ruhigen Kameraführung und den Adrenalinschübe verursachenden Soundtrack erzeugt "The Village" eine ständige Atmosphäre der Furcht - vor dem Wald, vor den Unaussprechlichen, vor den Geheimnissen des Dorfrates. Es musste erst ein Inder kommen, um auf diesem Spezialgebiet von Alfred Hitchcock wieder Maßstäbe zu setzen! Wie dieser weiß Shyamalan aber auch, wie er das Maximum aus den bereitwillig in seinen Filmen mitspielenden Schauspieler-Stars herausholt. Das gesamte Ensemble liefert eine tolle Vorstellung ab - schade nur dass Sigourney Weaver in einer kleinen Nebenrolle verheizt wurde.

Die oben erwähnte und durch die Inszenierung erzeugte Atmosphäre der Furcht stellt dabei aber nur ein Mittel dar, um den Zuschauer intensiver an der Handlung teilhaben zu lassen und ist nicht nur reiner Selbstzweck. Das Publikum soll merken, welche Angst die erfundenen Unausprechlichen bei den nichtsahnenden Dorfbewohnern auslösen. Dann erst weiß es zu beurteilen, welche Konsequenzen dieses "Experiment" doch hat. Der zwingende Mittelpunkt der Thematik ist dabei die Macht, die eine Gruppe von Menschen über andere hat. Der Regisseur (und natürlich wieder Drehbuchautor) unterstellt dabei nicht einmal böse Absichten - die Gründe für die Isolation waren ehrlich und ehrenwert. Doch reicht dies aus, um anderen Menschen die Freiheit weg zu nehmen? Und muss man anderen Menschen die eigenen Vorstellungen aufdrängen, indem man ihnen andere Wege versperrt?

Um dieses zentrale Thema schlängelt sich die durchaus als politisch interpretierbare Handlung von "The Village". Der Dorfrat, der sich seine eigene Utopie von der idealen Gesellschaft mit Unterstützung der Regierung (!) verwirklich hat, verheimlicht bewusst die Realität vor den unwissenden Kindern und erfindet mit dem Wald der Unaussprechlichen das scheinbar ultimative Mittel zur Abschottung. Dabei schrecken sie selbst vor kostümierten Überfällen nicht zurück, um die Angst in der Bevölkerung wach zu halten. Doch um diese ständige Atmosphäre der Bedrohung aufrecht zu erhalten ist ein großer Aufwand erforderlich (ständige Beleuchtung und Bewachung der Waldgrenze), welcher sich immer mehr zum Selbstzweck entwickelt, denn die Generation um Lucius, Noah und Ivy will im jugendlichen Tatendrang die eigenen Grenzen austesten und ist auf sehr unterschiedliche Art und Weise nicht empfänglich für die Abschreckunsgversuche des Dorfrates. Noch kann der Jugend durch einen getürkten Überfall des Dorfes genügend Angst eingejagd werden, doch es ist abzusehen, dass auch dieses Mittel in Zukunft seine Wirkung verloren hätte. Interessant ist dabei auch, dass die Kinder unterbewusst die Mittel der Eltern kopieren - so versucht Ivy Einfluss über Noah zu bekommen, indem sie einen Raum der Stille für ihn erfindet, vor dem er sich fürchtet und den er nicht freiwillig betritt. Die Macht der Suggestion kann bei schwachen Gemütern wie kleinen Kindern oder Noah sehr stark sein.

Dass das Experiment gescheitert ist, sieht am Ende sogar der Dorfrat ein. Die schlechten Einflüsse der Gesellschaft sind auch in dem künstlichen Mikrokosmos wieder aufgetaucht bzw. wurden sogar durch die abgrenzenden Einschränkungen provoziert. Doch trotz des Misserfolgs kann sich niemand, nicht einmal Edward Walker, von dem einmal beschrittenen Weg trennen und das Projekt beenden. Dabei wird auch verdrängt, dass der Erfolg von Ivys Hilfeaktion zwangsläufig Nachahmer finden wird.

Doch von der Story zurück zur Umsetzung: Wer als Zuschauer genau aufpasst, dem werden schnell einige Ungereimtheiten auffallen. So hat das Dorf z.B. ein großes Gewächshaus aus Glas und beleuchtet die Nacht mit dermaßen vielen Fackeln, dass man sich fragen muss woher diese Rohstoffe alle kommen. Ob nun die Regierung diese dem Dorfrat zukommen lässt oder der Regisseur aufgrund von atmosphärischen Einstellungen das Dorf eher abstrakt erscheinen lässt, bleibt dabei genauso offen wie der Grund für die verbotenen Farbe Rot (um Verbrechen und fließendes Blut zu vermeiden?). Auf jeden Fall kann auch die spannende Szene des Kampfes zwischen Ivy und Noah, die nachweist, dass der Drang auszubrechen auch mit einem Handicap alle Hindernisse überwinden kann, den Zuschauer nicht mehr von dem richtigen Ansatz für die Auflösung abhalten. So bleibt mir nur Herrn Shyamalan zu empfehlen, bei seinem nächsten Film ganz auf die Schlusspointe und die damit verbundenen, falsch gelegten Fährten zu verzichten und sich erneut so stark auf die Thematik zu konzentrieren.

Fazit: Neben der gekonnten Inszenierung hat es M. Night Shyamalan diesmal auch geschafft, eine ansprechende Thematik mit einer guten Bildsprache zu verknüpfen und damit erstmals wieder an "The Sixth Sense" anzuknüpfen, ohne diesen zu kopieren. Nur das zwanghafte Festhalten an der Schlusspointe und die damit verbundenen Ablenkungsmanöver und Logikfehler verhindern eine Bestnote.
