---
title: "Inception"
date: "2010-09-19T23:35:23"
categories: [gesehen]
---

*USA/UK (2010)
Regie: Christopher Nolan
Darsteller: Leonardo DiCaprio (Dom Cobb), Ellen Page (Ariadne), Joseph Gordon-Levitt (Arthur), Tom Hardy (Eames), Ken Watanabe (Saito), Dileep Rao (Yusuf), Marion Cotillard (Mal), Cillian Murphy (Robert Fischer), Tom Berenger (Peter Browning), Pete Postlethwaite (Maurice Fischer), Michael Caine (Miles), Lukas Haas (Nash) und andere Traumgestalten*
[Offizielle Homepage](http://wwws.warnerbros.de/inception/mainsite/)

Dom Cobb ist ein Meister der Industriespionage. Allerdings nicht der klassischen Art, denn Cobb stiehlt die wertvollen Informationen direkt aus den Köpfen der Wirtschaftsbosse. Über eine Maschine können er und sein Team die Träume der Opfer manipulieren, indem sie Traumwelten erschaffen und selber daran teilnehmen. Doch dann hat ein Kunde einen Wunsch, der über das Beschaffen von Informationen hinaus geht: Cobb soll bei einem Konkurrenten des Auftraggebers eine Idee pflanzen, so dass dieser sie für seine eigene hält und danach handelt...

*Inception* ist sicherlich **der** Blockbuster des Jahres. Denn er schafft es wie kein anderer Film, so viele Zuschauergruppen gleichzeitig anzusprechen. Er ist auf der einen Seite ein Actionkracher, der mit Autoverfolgungsjagden, Schusswechseln, Explosionen und dem klassischen Konzept eine Heist-Movies aufwarten kann. Zusätzlich bietet er ein paar an *Matrix* erinnernde Duelle und kann so auch ohne tieferes Hinterfragen der mehrmals verschachtelten Handlung genossen werden. Bei all der rasanten Inszenierung fällt kaum auf, dass *Inception* eine Länge von über 2,5 Stunden hat.

Desweiteren fährt der Film ein Großaufgebot an Stars auf, unter denen sich bestimmt für jeden Geschmack ein Zugpferd finden lässt. Neben einer starken englischen Fraktion um Joseph Gordon-Levitt und Cillian Murphy ist der Film klar auf Leonardo DiCaprio zugeschnitten, der sein Schauspiel verglichen mit seiner Rolle in *Shutter Island* nur um Nuancen variiert. Da die meisten Charaktere sich eher in ihren abstrakten Eigenschaften (Architekt, Apotheker, Auftraggeber, Opfer) definieren und kaum persönlichen Background mitbringen, kann sich keiner der Schauspieler merklich auszeichnen. Es scheint mir sogar, dass Regisseur Nolan bewusst bestimmte Gesichter für die Charaktere ausgesucht hat, damit der Zuschauer die fehlende Ausstaffierung seiner Helden durch die im Hinterkopf sich befindenen Erinnerungen an vorherige Rollen der Schauspieler ausgleicht. So etwas nennt sich wohl postmoderne Figurenzeichnung!

Das eigentliche Highlight des Films ist aber seine Konzept der Traummanipulation. Wie schon kurz angedeutet, gibt es nicht nur eine reale und eine Traum-Ebene, sondern ist es auch möglich, in einem Traum zu träumen und dies rekursiv weiter zu treiben, also ein Traum im Traum im Traum usw. Dabei stellt der Film ein paar Regeln für diese Traumschachtelungen auf, die sich auf die Handlung auswirken. So vergeht die Zeit in jeder tieferen Traumebene schneller als außerhalb davon und der jeweils äußere Traum hat Einfluss auf den inneren Traum. Stürzt zum Beispiel ein Auto mit den Träumenden in die Tiefe, so herrscht in deren Traum plötzlich Schwerelosigkeit.

Nun kann man in diesem Konzept die Logiklöcher suchen und finden, eigene Theorien aus Details des Films spinnen oder sich einfach nur darauf einlassen - der Film erlaubt alles davon, und das ist aus meiner Sicht seine große Stärke. Er offenbart in vielen Dialogen Details, die später durch weitere Details präzisiert oder gar in Frage gestellt werden und damit teilweise die Sicht auf die zurückliegende Handlung ändern. Sich einen Reim auf alles zu machen, ist so äußerst schwer, doch für alle Interpretation lassen sich ausreichend Hinweise im Film finden.

Die Rolle von Ellen Page, die Architektin Ariadne, nimmt dabei die Funktion als Stellvertreter des Zuschauers im Film wahr. Sie wird unwissend in das Unternehmen *Inception* eingeführt und lernt wie das Publikum die Möglichkeiten und Grenzen der Traummanipulation kennen. Die Regeln der Filmwelt werden ihr und den Zuschauern dabei laufend neu erörtert, jedoch immer nur in Erzählungen der Protagonisten - was deren Korrektheit zumindest offen lässt - und gerne unter Verwerfung von vorher vermittelteten Konventionen.

Dabei findet der Film außer ein paar Zeitlupen und den Schnitten kaum Bilder, um diese Konzepte oder die ständigen Wechsel zwischen den Traumwelten zu verdeutlichen. Wie Ariadne feststellen muss bei ihren ersten Versuchen, die Traumwelten fantasievoll zu verbiegen, erlaubt die Filmlogik dies nicht, weil sonst die falschen Träume als eben solche erkannt werden. Dies mag dem wissenschaftlichen Bild eines Traumes widersprechen, sorgt aber dafür, dass die Action bodenständig bleibt und damit der Film den Zuschauer und das Budget nicht überfordert. Ein wenig mehr Eye-Candy hätte ich mir aber trotzdem gewünscht.

Fazit: *Inception* ist Blockbusterkino der besten Sorte. Wer will, kann sich einfach im Sessel zurücklehnen und von der gut inszenierten Action und der rasanten Handlung unterhalten lassen. Wer will kann aber auch die Zeit nutzen, über das vermittelte Prinzip der rekursiven Träume und deren Implikationen nachzudenken, und auch da bietet der Film einiges an Substanz. Nur die weitesgehend fehlende Charakterzeichnung und die sehr bodenständige Optik gibt es zu bemängeln
