---
title: "The Expendables 2"
date: "2012-09-04T23:31:06"
categories: [gesehen]
---

Viel zu sagen gibt es nicht zu diesem Actionfilm der alten Schule. Die Story ist austauschbar, Gegner wie Freunde bleiben blass (was bitteschön soll das Tattoo der schwarzen Ziege?) - aber das kann auch positiv sein. Denn *The Expendables 2* will einfach nur ein leicht selbstironischer Actionschinken sein, und versucht nicht wie noch im ersten Teil große Emotionen zu beschwören und eine Charakterzeichnung vorzugeben, die bei genauerem Hinsehen zerbröselt. So bekommt der Zuschauer genau das, was er erwartet: Herrlich altmodische Action ohne digitale Effekte (die Kamera könnte für meinen Geschmack trotzdem besser sein), massenweise Tote allein in den ersten zehn Minuten (bitte nicht ernst nehmen!) und Auftritte der alten Herrenriege des 80er-Jahre-Action-Kinos. Am Besten verkauft sich dabei noch Chuck Norris, der mit seinem Image spielt und dabei im Gegensatz zum restlichen Cast nicht auf Zitate aus der guten alten Zeit zurückgreifen muss.

Bitte nicht falsch verstehen: *The Expendables 2* ist kein herausragender Film, aber Simon West ist ein routinierter Regisseur und wer ein paar Rentnern dabei zusehen will, wie sie Unmengen von Gegner in den Hintern treten, der macht hier nichts falsch. Punkt.
