---
title: "Welcome to the beach"
date: "2010-04-28T23:22:59"
categories: [gewesen,getan]
---

Sand everywhere - den heutigen Beginn meines Kurses nehme ich zum Anlass für den ersten Beachvolleyballcontent des Jahres. Die Luft war in der Sonne schon angenehm warm, der Sand kühlte nach dem Sonnenuntergang jedoch schnell ab; dennoch war es schön, nach der langen Winterpause endlich wieder im Sand zu stehen und meiner Lieblingssportart zu frönen. Nach dem Techniktraining folgen morgen gleich noch zwei Stunden mit Spielen just for fun.

Da wir noch April haben ist es kein Problem, in [Beach Mitte](http://www.beachmitte.de/) einen Platz reserviert zu bekommen. Doch sollten sich die schönen Tage mehren, wird es wohl wieder Terminprobleme geben. Noch sind auch nicht alle Umbauarbeiten an der Anlage beendet - [ein paar Plätze müssen einem Hochseilgarten weichen](http://www.beachmitte.de/eroeffnung-hochseilgarten-auf-beachmitte.html) - und der Grill bleibt noch kalt, so dass ein Verweilen in der Strandbar nach einem anstrengenden Spiel überlegt sein will.

Wer Beachvolleyball lieber als Zuschauer verfolgen als aktiv betreiben will hat dieses Jahr die Chance, bei den [Europameisterschaften](http://www.o2world.de/event/EUROPEAN-CHAMPIONSHIP-FINAL-2010/691.htm) in Berlin live dabei zu sein. Nachdem das Turnier am Hauptbahnhof im letzten Jahr international abgewertet wurde ist dies ein Schritt zurück nach vorne, wenn auch der Wechsel zur O2-World leider mit Eintrittspreisen am Wochenende erkauft wird - nur noch die Vorrundenspiele werden kostenfrei zu sehen sein. Dennoch sollte man sich die Chance auf hochklassigen Beachvolleyballsport nicht entgehen lassen!
