---
title: "Wassersucher"
date: "2008-09-07T15:48:34"
categories: [gelesen]
---

*von Rick Moody,
erschienen bei Piper, ISBN 978-3-492-25171-6, 12€*

Nachdem mich der Film *Der Eissturm* von Ang Lee nach einem Buch von Rick Moody sehr beeindruckt hat, lag es natürlich nahe, ein weiteres Werk des Autoren auszuprobieren. Ich habe mich dann für *Wassersucher* als eine Satire auf die Medienbranche entschieden.

Darin geht es um den namensgebenden Fernseh-Mehrteiler, den eine Mitarbeiterin einer Produktionsfirma erfindet, um zu verbergen, dass sie einen Fehler gemacht hat. Aus dieser Idee entwickelt sich jedoch schnell die erste Version eines Drehbuchs, das seine Kreise in der Industrie zieht: Es gibt Stars und Sternchen, die gerne mitspielen würden, es gibt mormonische IT-Millionäre, die den Film finanzieren wollen ("um Content zu produzieren") und sogar angebliche Autoren der Vorlage. Doch es ist nur eine Frage der Zeit, bis einer der Beteiligten mitbekommt, dass der Hype eigentlich gar keine Substanz hat und diejenigen hinabreißt, die alles auf das falsche Pferd gesetzt haben...

In diese Geschichte hat Rick Moody sehr viele überspitzte Charaktere eingebettet: Einen Pfarrer, der sich an einer Jugendlichen vergangen hat, einen Fernsehproduzenten, der auf Sex mit behinderten Frauen steht, eine alkoholabhängige Rentnerin, die auf Entzug fremde Handytelefonate in ihrem Kopf hört, Lifting-Partys in Kalifornien; ja sogar einen "Wassersucher" und einen spielsüchtigen Inder, der amerikanische Kultur studiert hat. Sie alle haben eins gemeinsam: Der Autor hat sie mit sehr vielen Details ausgestattet; zu vielen für meinen Geschmack. Denn bei geschätzten 20 Hauptcharakteren ist die Menge an Informationen ein totaler Overkill. Zwar ergeben viele Dinge im Verlauf der Handlung schlussendlich einen Sinn, alles passt genau zueinander, doch da sich das Buch in jedem Kapitel einem einzelnen Charakter widmet muss man schon viel Interesse für jede Rolle mitbringen, um sich durch die Informationsflut zu kämpfen.

Erschwerend kommt die gewöhnungsbedürftige Präsensform der Erzählung hinzu. Die wenigen Auflockerungen wie u.a. ein Kapitel in Tagebuchform oder den Versuch einer Vergewaltigung in Form einer wissenschaftlich-theoretischen Abhandlung helfen da nur unwesentlich. Zudem muss sich der Leser zu Beginn durch ein "Vorspann-Kapitel" quälen, in dem man dem Sonnenaufgang einmal um den Erdball herum folgt, hinweg über die von den Medien geschaffenen Produkte und Bilder wie GodZilla. Dieses Kapitel symbolisiert mit seiner verdrehten Buch-Realität den Vorspann zu einer Fernsehserie, zu einem TV-Mehrteiler; am Ende wird es auch einen Abspann geben und die Kapitel sind die einzelnen Episoden dieser Miniserie. So ist das Buch in seiner Form das Pendant zu seinem wichtigsten Handlungselement; mit einem sorgfältig geplanten Spannungsbogen und einem abrupten Ende auf dem Höhepunkt: So schnell sich der Hype um die "Wassersucher" entwickelt, so schnell folgt auch der Absturz.

Diese Selbstreferenz auf der Meta-Ebene findet sich in ähnlicher Form auch bei der für das Buch erfundenen Fernsehserie "Die Werwölfe von Fairfield County", die den Leser das gesamte Buch über begleitet und deren Nacherzählung der Thanksgiving-Folge den Höhepunkt der Handlung darstellt. In zwei Kapiteln wird zur Abwechslung nicht nur ein Charakter begleitet, sondern ein Überblick gegeben, wo die Handlung alle Akteure hingeführt hat. Ganz Amerika trifft sich an diesem Feiertag mit den Familien, nur um gemeinsam vorm Fernseher eine mittelmäßige Serie zu sehen. Der Inhalt einer Unterhaltungssendung beschäftigt alle Gesellschaftsschichten, das Fernsehen eint eine riesige Nation, doch hinter der Kulissen dieser kranken Industrie gibt es auch noch die verdrängten realen Probleme des Landes, die Moody nadelstichartig immer wieder anspricht: Rassenkonflikte, Ungenauigkeiten bei den Präsidentenwahlen, das Gesundheitssystem.

Ein interessantes Buch also, das jedoch den Zugang über seine konstruierte Form erschwert. Ein Zurücklehnen nach jedem Kapitel ist angesagt, um nicht zu tief hinabzusteigen von der Meta-Ebene in die Handlung hinein. Sonst verfängt man sich in der erzählten Geschichte, hält sie für real und überliest die Überspitzungen und die hier und da hervorblitzende Kritik.
