---
title: "Meine Lieblingsfilme 2005"
date: "2005-12-30T17:53:51"
categories: [gedacht,gesehen]
---

Qualitativ war das Kinojahr 2005 eher durchwachsen; besonders im Sommer konnte kaum eine Produktion überzeugen. Dennoch habe ich acht Filme ausgewählt, welche mir im Rückblick sehr gefallen haben - aufgrund der zeitlichen Nähe befinden sich in meiner Auswahl verstärkt Filme der letzten Monate. Außerdem sind die Hälfte der Filme für Kinder konzipiert. Ich sollte mir vielleicht Gedanken über meine Sehgewohnheiten machen...

<ul>
	<li>**The Aviator** Beeindruckende Biografie von Martin Scorsese, die wieder die Ausdruckskraft des Regisseurs spüren lässt. Sogar Leonardo DiCaprio kann als Hauptdarsteller überzeugen.</li>
	<li>**Sophie Scholl - Die letzten Tage** Der deutsche Beitrag zum Oscar präsentiert sich als klassisches Kammerspiel mit der überzeugenden Julia Jentsch in der Hauptrolle. Ein beklemmendes Stück Geschichte.</li>
	<li>**The Statement** Nach zwei Jahren hat es diese Auseinandersetzung mit der nationalsozialistischen Vergangenheit der Kirche in Frankreich endlich in die deutschen Kinos geschafft. Michael Caine zeigt noch einmal alle Facetten seines Könnens in diesem Thriller klassischer Machart.</li>
	<li>**Alles auf Zucker** Dany Levy ist mit dieser deutsch-jüdischen Komödie endlich auch der Durchbruch an der Kinokasse gelungen. Wundervoll respektlos nimmt der jüdische Regisseur seine eigene Religion und das vereinte Deutschland auf die Schippe und kann dabei auf ein überzeugendes Schauspielerensemble um Henry Hübchen und Hannelore Elsner bauen.</li>
	<li>**Charlie und die Schokoladenfabrik** Tim Burton hat es endgültig zurück zu alter Genialität geschafft. Dieses Fabelmärchen bietet nicht nur einen gewohnt souverän-skurilen Johnny Depp auf, sondern auch Kulissen und Gags der besonderen Sorte. Auch für ältere Semester empfehlenswert.</li>
	<li>**Wallace & Gromit auf der Jagd nach dem Riesenkaninchen** Weiter geht es mit englischem Humor und den Knetfiguren um Wallace und Gromit, welche erstmals in Spielfilmlänge auftreten. Urkomisch und mit vielen Seitenhieben und Filmverweisen bleibt bei diesem Film bestimmt kein Auge trocken!</li>
	<li>**Corpse Bride - Hochzeit mit einer Leiche** Und wieder Tim Burton: In dem inoffiziellen Nachfolger zu *Nightmare before Christmas* schickt uns der Regisseur zusammen mit seinen skurilen Stop-Motion-Figuren in die Welt der Toten, welche ebenso wie die reale Welt so ganz anders ist, als wir sie uns vorstellen. Da verzeihe ich auch die Gesänge wie in Disneyfilmen.</li>
	<li>**Harry Potter und der Feuerkelch** Bleibt zuletzt noch die Verfilmung des vierten Buches rund um den Zauberlehrling und seine Abenteuer an der Zaubererschule Hogwarts. Zusammen mit Harry Potter ist nun auch der Anspruch an den Film gewachsen, der nicht nur sehr düster ist, sondern auch eine komplexere Handlung aufweist. Trotzdem bleibt er natürlich sehr fantastisch und die besten britischen Schauspieler geben sich die Klinke in die Hand. Für mich der bisher beste Film der Serie und deshalb sehr empfehlenswert</li>
</ul>

Das war nun schon mein kurzer Jahresrückblick. Im nächsten Jahr komme ich hoffentlich wieder öfters ins Kino und mit etwas Glück gibt es auch genügend gute Filme, welche mich dazu animieren.
