---
title: "Road to Perdition"
date: "2005-11-20T23:00:48"
categories: [gesehen]
---

Ein sehr düsterer Film im Stil des Film Noir mit guten Darstellerleistungen von Tom Hanks und Jude Law. Sehr gefallen hat mir, wie der Regisseur es schafft, die 30er Jahr wieder aufleben zu lassen. Vor allem die Kulissen in Chicago sind große Klasse. Auch gelungen sind die vielen Seitenblicke auf die Gesellschaft und die Probleme rund um die Mafia: Auf der einen Seite die armen Leute gedrängt in Wartesälen und von den Banken bestohlen, auf der anderen Seite die High Society in ihren exklusiven Hotels, Clubs und Restaurants.

Der Hauptcharakter von Tom Hanks steht da genau in der Mitte. Aus der untersten Schicht kommend, hat er es als rechte Hand eines Mafia-Bosses zu einem eigenen Haus und gewissen Reichtum gebracht - er ist sich seiner schwierigen Stellung und Abhängigkeit jedoch bewusst. Als er dann zwischen die Fronten von internen Mafia-Streitereien gerät, weiß er als Insider sehr genau, wen er treffen muss und welche Auswirkungen dies hat. Denn er will nicht den Menschen schaden, die jeden Cent umdrehen müssen.
Dabei versucht der Film aber niemals, die ausgeführten Morde und die private Rache zu rechtfertigen. So schließt er auch mit einem echten Ende des Gewalt-Spirale, wenngleich der Weg dahin ein sehr düsterer ist und es offen bleibt, ob dies alles einen Sinn hatte.
