---
title: "Meine persönlichen Filmmomente des Jahres 2009"
date: "2009-12-31T17:38:03"
categories: [gedacht,gesehen]
---

Jahresrückblicke sind langweilig. Zumindest dann, wenn sie zu einer reinen Auflistung der besten Filme verkommen. Ich möchte daher das Filmjahr auf eine etwas persönlichere Weise Revue passieren lassen und die Filmmomente vorstellen, die mich am meisten berührt haben. Dabei muss der zu den Szenen gehörende Film nicht zwangsweise gut gewesen sein, aber bestimmte Bilder haben sich in mein Gedächtnis eingebrannt und diese möchte ich jetzt vorstellen.

**The Limits of Control - Streichholzschachtelübergabe mit Tilda Swinton**

Eigentlich war 2009 mein ganz persönliches Tilda-Swinton-Jahr. So viele Filme der Britin wie dieses Jahr habe ich noch nie gesehen: *The Invisible Frame* / *Cycling the frame*, [The Limits of Control](/blog/2009/12/07/the-limits-of-control/), [Der seltsame Fall des Benjamin Button](/blog/2009/02/01/der-seltsame-fall-des-benjamin-button/), *Constantine*, *The War Zone*, *Orlando*, *Young Adam*. Dies mag damit zusammenhängen, dass Frau Swinton und mich die Stadt Berlin verbindet. Gerade die beiden Dokumentationen zur Berliner Mauer zeigen, wie sehr sie sich mit der Stadt auseinandergesetzt hat, und ihre Rolle als Präsidentin der Berlinale-Jury im Jubiläumsjahr der Wende war da nur folgerichtig.

Aber in [The Limits of Control](/blog/2009/12/07/the-limits-of-control/) sieht man sie trotz extremer Maske sehr privat, nämlich als Filmliebhaberin (sie hat ein eigenes Festival auf ihrem Schloss in Schottland begründet). Alle prominenten Darsteller des Films konnten sich aussuchen, über welche Form der Kunst sie einen Monolog halten wollen, und Tilda hat sich natürlich für das Kino entschieden. Da dies gleichzeitig in selbstreferentieller Manier in einem Film passiert, habe ich diese Szene als geradezu magisch und die Grenzen des Mediums sprengend erlebt.

**Inglourious Basterds - Szene im Projektorraum**

Bei diesem Filmmoment [zitiere ich mich einfach selber](/blog/2009/09/13/inglourious-basterds/):

> In der wohl schönsten Szene des Films sieht man Shosanna im Profil vor dem im Projektor durchlaufenden Film; das grelle Licht der Projektorlampe und das rote Kleid der Akteurin führen zu einem wundervollen Kontrast, der mir bis heute als Bild im Gedächtnis hängen geblieben ist. So schön kann Kino sein, und so schön kann man Kino im Kino nur präsentieren, wenn es man liebt wie Tarantino.

**Coraline - Das Auseinanderfallen der aus Puzzleteilen bestehenden Welt**

Animationsfilme haben den großen Vorteil, eine Welt erschaffen zu können, die nicht der Realität entspricht, und kein Zuschauer stellt Fragen. [Coraline](/blog/2009/09/13/coraline/) hat zu diesem Zweck eine wunderbare Kombination aus Knetfiguren und CGI-Effekten benutzt, die mir erst bei dieser Szene so richtig bewusst wurde. Denn wo sich vorher noch ein Hintergrund mit Himmel, Hügeln und Bäumen befand, gab es plötzlich einen riesigen Globus aus Puzzleteilen, der in sich zusammenfiel und eine weiße, endlose Leere präsentierte. Die nur für das Mädchen erschaffenen Parallelwelt der anderen Mutter war einfach nur ein Potemkinsches Dorf, eine Fassade, die beim Auseinanderfallen ihre wahre Natur der fehlenden Substanz, des fehlenden Hintergrunds einer echten Welt offenbarte. Ein optisch wie inhaltlich beeindruckendes Bild.

**The Fall - Das Intro**

Selten habe ich eine so faszinierende Einführung in einen Film gesehen. Was zuerst wie eine Abfolge von SW-Fotos aussieht offenbart sich als eine Reihe Aufnahmen in extremster, fast surrealistischer Zeitlupe. Die Klarheit der Bilder und ihr hoher Kontrast zeigen nach und nach, was vor Beginn der Handlung passiert ist (nämlich ein Unfall eines der ersten Stuntmen des Kinos), doch verstehen tut es der Zuschauer erst im weiteren Verlauf des [Films](/blog/2009/08/03/the-fall/).

(und [Lars von Trier hat es für seinen Antichristen kopiert](/blog/2009/11/22/antichrist/))

**Waltz with Bashir - Der finale Wechsel vom Zeichentrick in reale Aufnahmen**

[Waltz with Bashir](/blog/2009/01/28/waltz-with-bashir/) findet eine Unmenge von beeindruckenden Bildern zur Visualisierung der Schrecken des Krieges für die jungen Israeli, die nur ein Zeichentrickfilm auf diese Weise darstellen kann. Als stärkster Moment bleibt jedoch das Ende in Erinnerung, wo die abstrakte Animation direkt in Original-Dokumentaraufnahmen übergeht und mir mit aller Direktheit klar machte: So persönlich die Erinnerungen an die Invasion für die einzelnen Beteiligten sind, das Massaker hat es wirklich gegeben, und so wie die Bilder den Zuschauer schocken so haben sie auch bei den Figuren Traumata hinterlassen. Ein passendes Ende für einen wichtigen Film.

So, das war auch schon mein persönlicher filmischer Jahresrückblick. Ich wünsche allen Lesern einen guten Rutsch in das neue Jahr und hoffe auf gutes Filmjahr 2010.
