---
title: "Same procedure as every year"
date: "2012-02-09T20:44:05"
categories: [gedacht]
---

Wie sich alles wiederholt: Pünktlich zum Beginn der Berlinale meldet sich der Winter in Berlin zurück, und [wie jedes Jahr](/blog/2011/02/10/die-baren-sind-los/) ist es unglaublich schwer, Karten für das erste Wochenende zu ergattern. Nachdem ich heute den Onlineverkauf um 10Uhr verpasst habe, war im International auch nichts mehr zu holen. Jetzt hoffe ich noch auf die Tageskasse am Sonntag bzw muss mich auf die Arbeitswoche ab Montag beschränken. Beim [Festivalblog](http://www.festivalblog.com/archives/2012/02/kartentricks.php5) gibt weitere Hinweise für die Kartenjagd.

Begeistert bin ich dagegen von der grandiosen [Jury](http://www.berlinale.de/de/das_festival/preise_und_juries/preise_internationale_jury/index.html) dieses Jahr: Mike Leigh, Anton Corbijn, [Charlotte Gainsbourg](/blog/?s=Charlotte+Gainsbourg), [Jake Gyllenhaal](/blog/?s=Jake+Gyllenhaal), [François Ozon](/blog/?s=Fran%C3%A7ois+Ozon) und der Vorjahressieger Asghar Farhadi - das ist eine bunte Mischung von allerhöchster Qualität. Ich beneide sie allerdings nicht um den Wettbewerb, der mich wie in den meisten Jahren gar nicht anspricht, ebenso wie die [Berlinale Shorts](http://www.berlinale.de/de/das_festival/festival-sektionen/kurzfilmprogramm/index.html), wo die tolle Sandra Hüller in der Jury sitzt. Meine Welt ist klar das [Panorama](http://www.berlinale.de/de/das_festival/festival-sektionen/panorama/index.html) - so ich denn Karten dafür bekomme.
