---
title: "Good Bye Lenin!"
date: "2003-03-01T00:00:06"
categories: [gesehen]
---

*Deutschland (2003)
Regie: Wolfgang Becker
Darsteller: Daniel Brühl (Alex Kerner), Katrin Saß (Mutter Christiane Kerner), Florian Lukas (Denis), Chulpan Khamatova (Lara), Maria Simon (Ariane Kerner), Alexander Beyer (Rainer), Michael Gwisdek (Direktor Klapprath), Burghart Klaußner (Vater Kerner), Christine Schorn (Frau Schäfer) und andere Genossen*
[Offizielle Homepage](http://www.79qmddr.de)

Seitdem ihr Mann in den Westen geflüchtet ist zieht Christiane Kerner ihre beiden Kinder alleine in der DDR groß und versucht dabei, parallel eine gute Mutter und Bürgerin des Staates zu sein und gleichzeitig durch gezielte Kritik die kleinen Unzulänglichkeiten des alltäglichen Lebens zu mindern. Als sie dann im Jahre 1989 zusehen muss, wie ihr Sohn Alexander bei einer Friedensdemo festgenommen wird, hält sie dies nicht durch und fällt nach einem Schlaganfall ins Koma, aus dem sie erst nach 8 Monaten wieder erwacht. Die Ärzte verschreiben ihr absolute Ruhe, doch wie soll man der aufopfernden Sozialistin erklären, dass es die DDR inzwischen nicht mehr gibt? Alex erfindet also kurzerhand die Republik neu und baut sie in ihrer Plattenwohnung nur für die Mutter wieder auf, um ihr die letzten Tage ihres Lebens so schön wie möglich zu gestalten. Doch wie soll man die von allen Seiten auf sie einströmenden Einflüsse des kapitalistischen Westens von ihr fernhalten?

Die politische Wende in der ehemaligen DDR ist inzwischen 13 Jahre her, doch der Ostalgie hat dies keinen Abbruch getan, denn aufgrund der Thematik fühlt sich scheinbar jeder "Ossie" verpflichtet, diesen Film anzusehen - selbst wenn er nach der Wiedervereinigung ansonsten noch kein einziges Mal wieder im Kino war. Trotz der geringen Einflüsse von nur 9 Jahren Deutsche Demokratische Republik fühlte ich mich doch dank der Verschusslorbeeren und der recht witzigen Werbung und Story dazu veranlasst, mir nach "Sonnenallee" auch diese "Ostkomödie" anzusehen, wenngleich ich auch sicher wieder einen Haufen Anspielungen aus Unwissenheit verpasst habe und dieser Film sehr viel mehr eine Tragikomödie ist.

Der Regisseur konstruiert dabei eine Geschichte um eine Berliner Familie, die zwischen kleinen und großen Lügen versucht, das Leben in der DDR so angenehm wie möglich zu gestalten. Doch keiner von ihnen ist wirklich auf die Wende vorbereitet und so verläuft der Übergang in den Kapitalismus eher holprig: Die Tochter schmeißt ihr Studium, wechselt zu Burger King und fängt eine Beziehung mit dem Filialleiter an, der Sohn dagegen bekommt eine Anstellung in einer West-Berliner Firma und hat dann doch nichts besseres zu tun, als für seine kranke Mutter den Osten wieder aufleben zu lassen. Dass diese ihre Kinder jahrelang über die Flucht des Vaters im Unklaren gelassen bzw. sogar eine Lüge darüber erfunden hat, gehört zu den sich nun aufrollenden Dramen der Familie. Das Vorspielen der heilen DDR-Welt, für die Alex immer stärker die aktuellen Ereignisse im vereinten Deutschland umschreibt, verliert im Laufe der Geschichte immer weiter an Sinn, doch im Gegensatz zu seiner Mutter kann er nicht so einfach loslassen und hängt viel mehr an der Vergangenheit als seine Mutter dies in Wirklichkeit tut.

Doch leider kann die Story trotz der vielen witzigen Einfälle nicht in allen Belangen überzeugen. Dies ist aber nicht die Schuld des guten Schauspielerensembles, das auf ganzer Linie überzeugen kann und auch nicht der Ausstattung, die die DDR wirklich neu aufleben lässt (und viel authentischer wirkt als die Studiostrasse aus "Sonnenallee"). Viel mehr hat man das Gefühl, dass der Film viel zu stark konstruiert wurde und deshalb an einigen Stellen die Glaubwürdigkeit etwas verloren geht. Doch gegen Ende fängt er sich zum Glück wieder und mit weniger Witz (dafür mehr Tragik) finden schließlich alle auf ihre Weise doch noch den Weg in das neue Deutschland.

Fazit: Ein Film über die Wende aus ostdeutscher Sicht, in dem es um Sozialismus, Kapitalismus, den Übergang dazwischen und den Umgang damit geht. Für Kinder dieser Zeit ein Film, den man gesehen haben muss, als Tragikomödie aber auf jeden Fall auch für alle anderen sehenswert!
