---
title: "Mauritius - Grand Baie und Pamplemousses"
date: "2011-06-04T23:02:31"
categories: [gewesen]
---

Der Nordwesten von Mauritius lebt hauptsächlich vom Tourismus. Von Tamarin über Flic en Flac bis zum Cap Malheureux ziehen sich die schönsten der vom Riff geschützten Badestrände und so finden sich dort auch die meisten Hotels und viele Apartments. Diese verbrauchen neben den das Inland dominierenden Zuckerrohrfeldern den Großteil der Wasserrevoirs der Gegend und sind gleichzeitig die größten Arbeitgeber der Region.

Grand Baie ist eines der touristischen Zentren im Nordwesten und war von unserem Hotel bequem per Rad erreichbar. An einer wunderschönen Bucht mit grünblauem Wasser gelegen wechseln sich an der Hauptverkehrsstraße Restaurants mit den obligatorischen Hotels und ein paar Clubs ab. Die gesamte Bandbreite der mauritianischen Küche lässt sich hier erkunden - von indischen oder kreolischen Currygerichten über Meeresfrüchte und Wild französischer Art, italienischer Pasta bis hin zu asiatischen Fischgerichten und Sushi bleibt kein Wunsch unerfüllt. Mit dem [Café Müller](http://www.mauritius-tipps.de/html/maren_muller.html) gibt es sogar ein deutsches Kaffeehaus im Ort. Ich habe mir einen leckeren Eisbecher mit Blick auf die Bucht im Café am Sunset Boulevard schmecken lassen, einem von Textilläden geprägten kleinen Einkaufszentrum. Ansonsten fällt in Grand Baie aber nur noch ein bunter Hindutempel auf.

Wer die unbewohnten Inseln nördlich von Mauritius besuchen will, kann von der Bucht aus eine Katamaran- oder Segeltour starten. Ein paar Kilometer weiter entlang der Küste folgt schließlich mit dem Cap Malheureux einer der nördlichsten Punkte der Insel. Das Kap verdankt seinen Namen der erfolgreichen Invasion der Engländer, die dort landend schließlich Port Louis und die gesamte Insel einnahmen - aus französischer Sicht natürlich ein Unglück. Dass das Kap trotz der folgenden englischen Kolonialzeit so heißt, zeigt wieder einmal, welchen Einfluss die Franzosen auf Mauritius hatten und haben. Eine kleine weiße Holzkirche mit rotem Dach ist das Wahrzeichen des Kaps - doch bis dorthin habe ich es bei meinem Besuch nicht geschafft.

Dafür hat es mich noch nach Pamplemousses verschlagen. Dort gibt es den nach dem ersten Premierminister Sir Seewoosagur Ramgoolam benannten Botanischen Garten. Dieser wurde einst von Gouverneur Mahé de Labourdonnais (seinen Namen trägt die Stadt Mahébourg mit dem internationalen Flughafen) als Gemüsegarten angelegt, doch die stetigen Erweiterungen durch seine Nachfolger mit dem Fokus auf exportierbare Gewürze und tropische Pflanzen machten den Garten zu dem, was er heute ist.

Neben unglaublich vielen Palmenarten und je einem Rotwild- und Riesenschildkrötengehege ist mir vor allem das Becken mit den Amazonas-Wasserlilien aufgefallen. Diese Riesenseerosenart besitzt Blätter mit einem Durchmesser von anderthalb Metern und einem gezackten, nach oben geknickten Rand ähnlich einer Lochsäge. Trotz der Warnung, keine Gegenstände auf die Seerosen zu werfen, lagen doch etliche der großen 1-Rupien-Stücke auf den Blättern, die so kräftig aussahen, dass ich versucht war auszutesten, ob sie auch mein Gewicht tragen. Doch dank der stehenden Gewässer und dem vielen Schatten im Botanischen Garten muss ich auch hier eine Mückenwarnung aussprechen.

[gallery link="file"]
