---
title: "Shadowmarch – Das Herz"
date: "2011-10-03T22:44:11"
categories: [gelesen]
---

*von Tad Williams,
erschienen bei Klett-Cotta, ISBN 978-3-608-93720-6, 26,95€*

Nun ist es endlich geschafft: Mit *Das Herz* ist der letzte Teil von Tad Williams *Shadowmarch*-Saga in Deutschland erschienen, und natürlich habe ich mich sofort darauf gestürzt, um das lange erwartete Finale und die letzten noch im Dunkeln verbliebenen Geheimnisse um die Südmarksburg zu ergründen.

Nach einer kurzen Zusammenfassung der vorherigen Bücher nimmt sich *Das Herz* etwas Zeit, um den großen Schlagabtausch vorzubereiten. Die Fundlinge müssen sich nach dem unter Führung von Hauptmann Vansen ausgehandelten Waffenstillstand mit den Qars auf die nächsten Eindringlinge vorbereiten, denn der Autarch hält sich nicht lange mit der Belagerung der Oberburg auf sondern will direkt in die unterirdische Höhle vordringen, wo der sterbende Halbgott Krummling kurz davor ist, das Tor zu den schlafenden Göttern wieder frei zu geben. Die direkt von Krummling abstammenden Qar wissen dagegen anfangs nicht, ob sie sich diesem Kampf anschließen sollen, bis plötzlich Barrick Eddon, der die Feuerblume des Qar-Königs übernommen hat, zusammen mit der Qar-Königin auf den Wegen der Götter eintrifft. Seine Schwester stürmt inzwischen mit einer Armee Syanesen und deren Kronprinzen heran, während ihr Vater und Quinnitan als Gefangene im Schlepptau des Autarchen wie fast alle Charaktere einer ungewissen Zukunft entgegen sehen...

Die Hauptaufgabe von *Das Herz* ist, das war vorher klar, die unglaublich vielen parallelen Handlungsstränge endlich zusammen zu führen, nachdem ein Großteil der Verständnisfragen bereits im dritten Teil geklärt wurden. Wie viele Figuren Tad Williams bis dahin erschaffen hat, merkt der Leser erst, als ein erstaunlich großer Teil davon im Finale ein böses Ende nimmt. Alle anderen, denen der Leser im Laufe der Bücher in den Kopf schauen durfte, bekommen zumindest einen Abschiedsauftritt, womit am Ende tatsächlich alle Fäden entwirrt scheinen, die Tad Williams so kunstvoll verknotet hat.

Es scheint mir jedoch, dass dieses letzte Buch einen eigenen, vorher nicht eingeplanten, Spannungsbogen spendiert bekam. Einige der anfänglichen Wendungen und Konflikte wirken aufgesetzt und unnötig - allein wie viele Parteien zeitweise durch die Höhlen unterhalb der Südmarksburg ziehen und sich (nicht) begegnen übersteigt jedwede Vorstellung. So wird die zwischenzeitliche Stärke der geografisch verteilten Handlung zum großen Nachteil des Buches, da gefühlt alle Charaktere auf dem selben Fleck Erde herumwandeln und sich - vollkommen unerklärlich - nicht treffen und die Kräfte bündeln. Als Folge springt die Handlung auf fast jeder Seite und verwirrt mit ihrer nicht immer gegebenen Chronologie. Weniger wäre hier eindeutig mehr gewesen; bei [Harry Potter](/blog/2008/11/23/harry-potter-and-the-deathly-hallows/) haben die Bücher nie unter dem hohen Detailgrad und der Figurendichte gelitten wie bei *Das Herz*.

Ganz krass ist dabei die Auflösung der Nebenhandlung um den reichen Obdachlosen, der durch die Schattenmark des dritten Bandes stolperte. Nachdem er im letzten Teil eingeführt wurde und Tad Williams mit einem weiteren Handlungsstrang den Verdacht auf Shaso (in die Irre) lenkt, darf er am Ende ganz kurz in einen Kampf eingreifen und eine latente Liebesgeschichte beenden und hat seine Bestimmung damit erfüllt. Für meinen Geschmack ist dabei eindeutig zu viel Zufall im Spiel und die lange Vorgeschichte erscheint aufgrund des Kurzauftritts als verschwendet. So viel Mühe für so wenig Wirkung - fast würde ich Tad Williams einen ironischen Humor unterstellen. Doch da der Rest des Buches humorfrei erzählt wird, ist dies wohl eher eine Schwäche in der Planung der Handlung, die ihm am Ende über den Kopf gewachsen zu sein scheint.

Schade auch, dass aufgrund des kriegerischen Szenarios des Bandes immer wieder Ehre und Mut unangenehm in den Vordergrund rücken. In dieser Klischeehaftigkeit sind sich fast alle Charaktere gleich, was die eigentlichen Konflikte und Antriebe in den Hintergrund drängt, die bis dahin so spannend und kunstvoll entwickelt wurden. Keine Figur darf aus dem Korsett der Heldenhaftigkeit ausbrechen und so werden einige Charakterentwicklungen ad absurdum geführt. Als Seiteneffekt dieser Eindimensionalität geraten die wiederholten Schlachten in den Höhlen unterhalb der Südmarksburg trotz ihrer exotischen Kulisse schnell zu einer langweiligen weil abwechslungsarmen Angelegenheit. So etwas bin ich von Tad Williams nicht gewohnt, hier hätte ich mir ein wenig mehr von der Fantasie gewünscht, mit der er seine Welt ansonsten ausgestattet hat. Aber wenigstens das für die meisten Figuren schmerzhafte Ende hebt sich aufgrund des weitgehend fehlenden Happy Ends aus der Masse heraus.

Punkten kann *Das Herz* zudem mit einer Tugend, die schon die ersten drei Bände lesenswert machte: Jede Figur in der Geschichte ist mit ihrer ganz eigenen Denkweise und Sprache ausstattet, die sich gut voneinander abheben. Gerade die in der Schattenmark ortsfremden Charaktere und Völker - ganz deutlich an Quinnitan zu bermerken - benutzen ihre eigenen Vokabeln und Ausdrücke, um die Welt und ihre Wahrnehmung davon zu beschreiben. Diese Perspektivwechsel bieten immer wieder interessante Blickwinkel auf die ablaufende Handlung und ermöglichen erst das Verständnis der Handlungen.

Spannende Ansätze sind weiterhin die Beschreibung der Schlafwelt zwischen dem Diesseits und dem Tod, in der auch die Götter verbannt wurden, und die fantasievolle Idee der Feuerblume, für deren Verständnis erst dieser letzte Band die Vorraussetzungen schafft. Als Folge dessen werden weitere Entwürfe wie die mehrfache Bedeutung der Südmarksburg als titelgebendes Herz deutlich - bis hin zum Grundriss der Festung aus dem Einband, dessen Form dem Organ ähnelt.

Fazit: Fast zerstört Tad Williams mit dem letzten Teil der *Shadowmarch*-Serie, was er vorher so wundervoll aufgebaut hat. Dieses Buch ist in seiner Figurenzeichnung und Kriegsheldenhuldigung nicht besser als der übliche Fantasy-Einheitsbrei. Allein die detaillierte Welt der Schattenmark hat in ihrem umfassenden Entwurf nichts von ihrer Qualität verloren, so dass ich das Buch als Abschluss der Saga akzeptieren kann, wenngleich es als alleinstehendes Werk eine Enttäuschung ist.

*Vorhergehende Bücher:*
<ol>
<li>[Die Grenze](/blog/2005/09/18/shadowmarch-die-grenze/)</li>
<li>[Das Spiel](/blog/2007/10/09/shadowmarch-das-spiel/)</li>
<li>[Die Dämmerung](/blog/2010/10/04/shadowmarch-die-dammerung/)</li>
</ol>
