---
title: "Freiheit für das TV-Programm"
date: "2007-12-17T22:43:58"
categories: [gedacht]
---

Als vor zwei Jahren der Wikipedia-Gründer Jimmy Wales [eine Liste von 10 Dingen aufstellte, die frei sein sollten](http://www.heise.de/newsticker/meldung/62516), staunte man nicht schlecht, als sich darunter auch die Forderung nach freien TV-Listings befand. Hier in Deutschland ist dies so gut wie kein Problem; fast jeder bekommt mit seiner Tageszeitung einmal die Woche auch eine kostenfreie TV-Zeitschrift zugesandt und Dienste wie [TVinfo](http://www.tvinfo.de) bieten einen schnellen Überblick über das aktuelle Tagesprogramm. Für alle darüber hinausgehenden Wünsche bietet der Markt eine breite Palette an Zeitschriften mit Zusatzinformationen an.

Dennoch hatte ich schon früh mit einem TV-Programm-Programm für den PC experimentiert, als [dieses](http://www.tvgenial.com/) noch komplett kostenlos war. Als ich dann von [TV-Browser](http://www.tvbrowser.org) hörte, war ich schnell überzeugt und nutze seitdem die Software. OpenSource, kostenfrei, flexibel, aktuell und auch für Linux verfügbar - was will ich mehr? Zugegeben, aus einem Printmedium kann ich alle nötigen Informationen mit einem Blick erfassen, aber dafür ist TV-Browser genauso flexibel wie ich. Ich reise viel, habe den Laptop immer dabei und damit auch mein individualisiertes TV-Programm inklusive Terminen. Einmal die Woche aktualisiere ich den Datenbestand und bin somit nicht an den Freitag/Samstag-Wechsel der Zeitungsausgabe gebunden - vor die Tür muss ich erst Recht nicht und Müll produziere ich ebenfalls nicht.

Doch leider weckte die wachsende Popularität des Dienstes auch die Interessen der "Produzenten", damit Geld zu verdienen. So verlangt die [VG Media](http://www.vgmedia.de) als Vertreterin der meisten deutschen Privatsender ab 1.1.2008 eine Gebühr für die Nutzung der digitalen TV-Daten auf Internetseiten, weshalb [TV-Browser](http://www.tvbrowser.org/content/view/122/12) diese Sender aus dem Angebot streicht. Das sind in meinem Fall immerhin 12 von 23 Programmen, wodurch die Software für mich quasi nutzlos wird.

Dabei verstehe ich nicht, worauf diese Gebühr eigentlich erhoben wird. Klar steckt Arbeit dahinter, einen Sendeplan zu erstellen - aber kreativ und schöpferisch ist dies aus meiner Sicht nicht, ganz abgesehen davon, dass die Privatsender ein Programm brauchen, um Zuschauer vor die Glotze zu locken und damit ihr eigentiche Einnahmen aus Werbung zu generieren. Für ein paar Euros (0,02 Cent pro Seitenabruf) wird so eine Art kostenloser Werbung abgeschafft - ob das die Kunden bindet, bezweifle ich stark.

Ein Grund für diesen Schritt könnte der zunehmende Wettbewerb sein, der sich auf den Webseiten der Sender abspielt. Während die öffentlich-rechtlichen Sender keinem ökonomischen Zwang unterliegen, müssen bei den privaten Sendeanstalten scheinbar auch die Internetseiten Gewinn erwirtschaften. So sind die Homepages von [RTL](http://www.rtl.de/) oder [ProSieben](http://www.prosieben.de/) fast inhaltsleer aber mit Werbung vollgepflastert - kein Wunder, dass sich Surfer auf der Suche nach dem aktuellen TV-Programm nur selten dorthin verirren und damit kostenlose Angebote wie TV-Browser an Popularität gewinnen. Mit der neuen Gebühr soll nun eine Rückwärtsbewegung stattfinden, damit die Werbeeinnahmen wieder kräftiger sprudeln - ich bezweifle aber den Erfolg der Maßnahme.

Bei mir wird es wohl eine Rückkehr zur preiswerten 2-Wochen-Fernsehzeitung werden, die durch den unübersichtlichen EPG meines DVD-Reorders ergänzt wird. Ich sehe die meisten Sendungen ohnehin nur noch zeitversetzt und damit quasi werbefrei. Doch vermissen werde ich den TV-Browser schon...
