---
title: "Letzte Nacht in Twisted River"
date: "2010-11-17T22:38:09"
categories: [gelesen]
---

*von John Irving,
erschienen im Diogenes Verlag, ISBN 978-3-257-06747-7, 26,90€*

Wenn es in einem Buch um das Ringen, um echte und falsche Bären, um Eltern die ihre Kinder anlügen oder erste sexuelle Erfahrungen mit älteren Frauen geht, dann kann nur John Irving der Autor sein. Sein inzwischen zwölfter großer Roman erzählt die Geschichte eines Vaters und seines Sohnes im Verlauf eines halbes Jahrhunderts.

Dominic Baciagalupo, Koch in einem Holzfällerlager, muss nach dem Tod der Mutter ihren gemeinsamen Sohn Daniel alleine großziehen. Dieser tötet im zarten Alter von 12 Jahren eine Indianerin, weil er sie für einen Bären hält. Sein Vater und er schaffen es, den Unfall zu vertuschen, müssen jedoch vor dem "Cowboy" genannten Constable des Ortes fliehen und landen so in Boston. Während Dominic über mehrere Restaurants hinweg Erfahrungen als Koch sammelt, entwickelt sich Daniel zu einem erfolgreichen Schriftsteller, der autobiografisch die reichhaltigen Erfahrungen seiner Jugend zu Büchern verarbeitet...

Ein Schelm, wer bei dem Charakter von Daniel nicht an den Autoren selber denken muss. Irving überträgt offensiv die häufig geäußerte Kritik, dass er immer nur dieselbe Geschichte erzählt, auf seinen Helden, der damit gleichsam zum Abziehbild des Autoren wird. Dies geht so weit, dass einige der im Buch erfundenen Romane und deren zentrale Themen denen von Irving gleichen (Abtreibung in *Gottes Werk und Teufels Beitrag*, Kindstod durch Autounfall in *Witwe für ein Jahr*). Dabei stellt die Hauptperson stellvertretend für Irving aber auch die Frage, was an autobiografischen Details so verwerfenswert sei und ob man die Romane nicht darauf reduziert und alles Erfundene und Weitergesponnene unter den Tisch fallen lässt. 

*Twisted River* bietet an Neuem vor allem die ausführlichen Beschreibungen der Restaurants, Küchen und Gerichte des Koches Dominic. Weiterhin gefiehl mir die Dopplung vieler Elemente der Geschichte. So gibt es zwei Väter, die jeweils einen Sohn ohne die Mutter großziehen müssen, und es gibt einen doppelten Angriff durch einen falschen Bären. Das Buch selber wird aus einer doppelten Perspektive erzählt, denn der Blickwinkel der Handlung wechselt episodenhaft zwischen den beiden Vätern, die so ihre ganz eigene Sicht auf die Ereignisse einbringen, die stark von den persönlichen Erfahrungen geprägt ist. Dies wirkt sich umso stärker aus, als die Handlung mehrmals fast ein Jahrzehnt nach vorne springt und die verpassten Jahre nur in den Gedanken der Protagonisten als eine Art von Rückblenden reflektiert werden. Die so doppelt erzählten Abschnitte gewinnen über ihre Wiederholung eine manchmal ironische, manchmal überraschende Seite, die eine große Stärke des Buches ist.

Leider gibt es aber auch unglaubwürdige Storylines innerhalb der Geschichte, die anscheinend die einzelnen Abschnitte des Buches miteinander verbinden sollen, aber gerade daran scheitern. Besonders die lebenslange Suche des Cowboys nach Rache, einer der wesentlichen Treiber der Handlung, wird nur wenig motiviert, und die Nacherzählung von 9-11 wird weder dem Ereignis noch dem Buch gerecht.

So ist *Letzte Nacht in Twisted River* ein Buch über das Schreiben desselben geworden - oder doch nicht? Spielt Irving nur mit der Metaebene und seinen autobiografischen Details, oder breitet er dem Leser wirklich seine eigenen Gedanken auf Papier aus? Wenn ein vom Wind gebeugter Nadelbaum in Pointe au Baril als wichtige Stütze des Autoren beschrieben wird, dann fühle ich als Leser doch ganz stark den echten John Irving dahinter, auch wenn er sich ansonsten durch viele Details ausreichend zu verschleiern weiß. Es reicht auf jeden Fall zu einem unterhaltsamen Buch mit einer Stärke in der kunstvoll verschachtelten Erzählstruktur, wenn auch ein paar Schwächen in der Verknüpfung der vielen Handlungsfäden den Genuss trüben.
