---
title: "Watchmen"
date: "2009-09-07T23:00:12"
categories: [gesehen]
---

*UK/USA (2009)
Regie: Zack Snyder
Darsteller: Jackie Earle Haley (Walter Kovacs/Rorschach), Patrick Wilson (Daniel Dreiberg/Nite Owl), Malin Akerman (Laurie Juspeczyk/Silk Spectre), Billy Crudup (Dr. Jon Osterman/Dr. Manhattan), Matthew Goode (Adrian Veidt/Ozymandias), Jeffrey Dean Morgan (Edward Blake/Comedian), Carla Gugino (Sally Jupiter/Silk Spectre) und andere Superhelden*

Ein Film wie eine einzige Rückblende; ein Film wie ein Comic. Die Nähe zur Vorlage - sowohl beim Drehbuch, als auch bei der Bildmontage - führt bei *Watchmen* dazu, dass der Film eine für das Kino ungewohnte Handlungsstruktur hat. Erst nach anderthalb Stunden kommt etwas Fahrt in die Geschichte, davor wird dem Zuschauer über Erinnerungen einiger Charaktere an den verstorbenen Comedian der Hintergrund der *Watchmen* erläutert.

Denn diese sind nicht wie andere Superhelden einfach in unsere bekannte Welt gesetzt worden, sondern haben diese verändert, Geschichte geschrieben und so eine Art Paralleluniversum gegründet. Und während in anderen Comics die Fronten zwischen Gut und Böse klar gezogen sind, so leben die *Watchmen* in einer moralischen Grauzone. Sie haben Superfähigkeiten und nutzen diese - durchaus auch zum eigenen Vorteil. So steckt einer der *Watchmen* hinter der Ermordung von Präsident Kennedy und dank ihnen konnte Nixon in Vietnam triumphieren und vier Präsidentschaften erleben. Dr. Manhattan ist gar ein wichtiger Stützpfeiler im Kalten Krieg durch seine Beherrschung der Atomkraft.

Doch wer Macht hat, kann diese auch missbrauchen. Niemand kann die *Watchmen* überwachen, und so hat sich schließlich die amerikanische Bevölkerung gegen ihre Superhelden gestellt und Nixon sah sich gezwungen, die Gruppe offiziell in den Ruhestand zu schicken.

Diese komplexe Hintergrundgeschichte macht *Watchmen* wohl zu Recht zu einem der erwachsensten Comics. Dabei ist es die kongeniale Verknüpfung von Handlung und Charakteren, die den Film so faszinierend macht. Denn neben der schon angesprochenen Moraldebatte gibt es auch Abstufungen innerhalb der *Watchmen*, die die Auseinandersetzung um dem richtigen Umgang mit den Superfähigkeiten prägen. So hat Dr. Manhattan fast unbegrenzte Macht und ist damit der Stärkste der Gruppe, doch diese totale Überlegenheit gegenüber jedem anderen Menschen hat ihn abgestumpft im Umgang mit ihnen und so verfolgt er stoisch seine eigenen Ziele, passiv in dem aus seiner Sicht unabänderlichen Ablauf von Zeit und Ereignissen. Ozymandias dagegen wird als der Klügste angesehen und hat es durch das eigene Vermarkten zum reichsten Mann der Welt geschafft. Dadurch ist er, wenn auch auf andere Art und Weise als Dr. Manhattan, in der Lage, einen großen Einfluss auf die Menschheit zu nehmen und durchaus gewillt, diesen auch zu geltend zu machen.

Diese Inhomogenität steht im Gegensatz zu klassischen Comicheldengruppen, die oft nach dem Grundsatz funktionieren, mehr als die Summe ihrer Einzelteile zu sein. Die gesamten *Watchmen* und ihre Fähigkeiten haben aber gar nicht zum Ziel, dem wiederkehrenden Schema von Herausforderung und Triumpf in Serie zu entsprechend, sondern sind vielmehr Ausdruck und Symbole einer einmaligen Handlung. Deshalb wird auch nur bei Dr. Manhattan erläutert, wie er zu seinen Kräften kam; bei allen anderen bleibt dies im Dunkeln bzw wird sogar durch die Übernahme der Superheldenrolle von den Eltern ad absurdum geführt. Silk Spectre als Karikatur auf die zumeist vom männlichen Publikum konsumierten Superheldinnen mit ihren knappen Outfits wird quasi auf den zwischenmenschlichen und sexuellen Aspekt einer weiblichen Rolle reduziert, wobei die Tragik ihrer Herkunft auf dieser Grundlage gut funktioniert. Nite Owl schließlich darf als Personifizierung der auch bei Batman schon oft angesprochenen Fragen angesehen werden, ob er sich hinter seiner Maske versteckt oder vielmehr der Mensch nur die Fassade für Night Owl ist. Für diese Debatte findet der Film sehr schöne Bilder und weiß auch den sexuellen Aspekt hinter den Latexkostümen zu versinnbildlichen.

Am Spannendsten ist jedoch die Figur des Rorschach. Er treibt die Handlung voran und ist das Zentrum der Moraldebatte, denn in ihm finden sich all die Zweifel und Fragen wieder, die die anderen Superhelden sich nicht stellen. Wie geht man korrekt mit seinen Kräften um, welche Mittel sind angemessen und was dürfen die Watchmen eigentlich machen; was ist das Ziel der Gruppe und wie kann man verhindern, dass sie zu einem Spielball der Regierung oder sogar eines Mitgliedes wird? Als Ausdruck dieser Zweifel kann seine Maske angesehen werden, denn ein Tintenfleck hat keine eindeutige Interpretation; bei Rorschach wechseln die Kleckse zudem ständig und damit seine Ansichten, doch ohne seine Maske steht er eindeutig Position und dies auch gern in Opposition zu seinen Kollegen.

Diese Einigkeit von Charakteren und Handlung findet schließlich Ausdruck in einem extremen, aber konsequent der Handlung folgenden Finale. Dies ist keine perfekte Comicwelt, und so wenig wie es den eindeutigen guten Helden gibt, gibt es einen positiven Ausgang für alle Beteiligten. Diese bis zum bitteren Ende durchgehaltene Strenge in der Figurenzeichnung in all ihrer Konsequenz hat mich wirklich beeindruckt.

Fazit: *Watchmen* findet eine tolle Form und Ausdrucksweise, um eine Metadebatte über Superhelden (und Moral) in einer Superheldengeschichte zu führen. Man muss sich jedoch auf dieses Experiment einlassen, denn eine anderthalbstündige Einführung in das komplexe, vielschichtige Universum verlangt schon Interesse an der Thematik - dieses wird jedoch reichlich belohnt.
