---
title: "Austin Powers in Goldständer"
date: "2002-10-28T00:00:52"
categories: [gesehen]
---

*USA (2002)
Regie: Jay Roach
Darsteller: Mike Myers (Austin Powers, Dr. Evil, Fat Bastard, Goldständer), Beyoncé Knowles (Foxxy Cleopatra), Michael Caine (Nigel Powers), Verne Troyer (Mini-Me), Seth Green (Scott Evil), Michael York (Basil Exposition), Robert Wagner (Nummer Zwei), Mindy Sterling (Frau Farbissina), Fred Savage (Nummer Drei, "Die Warze"), Aaron Himelstein (der junge Austin Powers), Josh Zuckerman (der junge Dr. Evil), Evan Farmer (der junge Nummer Zwei) + Tom Cruise, Danny DeVito, Gwyneth Paltrow, Quincy Jones, Ozzy Osbourne & The Osbournes, Kevin Spacey, Steven Spielberg, Britney Spears als sich selbst*
[Offizielle Homepage](http://www.austinpowers-derfilm.de)

Für Austin Powers scheint momentan alles bestens zu laufen: Steven Spielberg verfilmt sein Leben und die Queen schlägt ihn zum Ritter. Aber leider fehlt die Anerkennung durch seinen Vater Nigel Powers, seineszeichens ebenfalls Topagent des Empires. Doch dann erfährt Austin dass Goldständer, ein Bösewicht aus den 70ern, den Vater entführt und zurück in seine Zeit verschleppt hat. Also reist Austin ebenfalls dorthin und trifft dabei seine ehemalige große Liebe Foxxy Cleopatra wieder. Gemeinsam erfahren sie, dass Goldständer zusammen mit Dr. Evil in der Gegenwart einen Traktorstrahl entwickelt hat, der einen Kometen in die Antarktis lenken soll. Nach der Befreiung von Nigel und mit Hilfe des übergelaufenen MiniMe muss Austin jetzt die Welt vor der kompletten Überschwemmung retten...

Endlich ist er zurück: Austin Powers, das Schärfste was ihre Majestät zu bieten hat. Bereits zum dritten Mal spielt Mike Myers die Hauptrolle(n) in seiner kultigen James Bond-Persiflage; diesmal verkörpert er neben Austin und Dr. Evil auch wieder den Fat Bastard und ganz neu Goldständer, der als Holländer die ganze Zeit von Nigel Powers sein Fett wegkriegt ("Ich hasse Intoleranz und ich hasse Holländer"). Die Rolle von Austins Vater wurde mit Michael Caine geradezu ideal besetzt, hat er doch in den 60er Jahren ebenfalls einen englischen Geheimagenten gespielt. Dass er dabei seine eigene Rolle auf die Schippe nehmen darf versteht sich von selbst bei einem Austin Powers-Film, denn das ist auch diesmal wieder die Stärke der ansonsten eher mit Witzen unterhalb der Gürtellinie aufwartenden Komödie. Anspielungen über Anspielungen auf sämtliche Bond-Streifen (sogar auf den neuen - als Foxxy den Taucheranzug auszieht, sieht sie aus wie Halle Berry!) und selbst auf die beiden Vorgänger lassen den Agentenfilm-erfahrenen Zuschauer vor Lachen kaum eine Minute zur Ruhe kommen. Dazu kommt die geniale Anfangssequenz, in der Myers nicht nur Mission Impossible sondern auch seine eigene Rolle aufs Korn nimmt - ein Lob für Tom Cruise, Britney Spears und Steven Spielberg, denen ich so viel Selbstironie nicht zugetraut hätte.

Doch ansonsten hat sich das Gagpotential von Austin Powers scheinbar langsam erschöpft. Die meisten Witze aus den beiden ersten Filmen ziehen nicht mehr wie gewohnt - die Rolle von Scott Evil gab schon jetzt nichts mehr her und wurde trotzdem für den vierten Film ausgebaut... Dagegen war ich positiv von Beyoncé Knowles überrascht, die ein famoses Bondgirl abgibt und es vielleicht weiter mit der Schauspielerei versuchen sollte.

Die Story präsentiert sich diesmal noch dünner als üblich, darf aber auch nur als Aufhänger für die vielen Anspielungen und bekannten Situationen (Schattenspiele, verdeckte Bildteile - diesmal mit Untertiteln) angesehen werden. Zieht man jedoch auch noch die Persiflagen ab, bleibt nicht mehr viel Substanz übrig; die ausnahmslos anrüchigen und abartigen Gags sind halt Geschmackssache. Da wünsche ich mir manchmal die unverbrauchten Witze des ersten Teils zurück!

Fazit: Als Bond-Persiflage mit Hang zur Selbstironie funktioniert Austin Powers auch im dritten Anlauf noch, doch langsam machen sich Abnutzungserscheinungen bemerkbar. Nichtsdestotrotz hat mich der Film anderthalb Stunden sehr gut unterhalten. Wer also die ersten beiden Teile mochte, wird auch von Goldständer nicht enttäuscht sein; alle anderen sollten erst einmal auf Video oder DVD die alten Filme antesten!
