---
title: "Evolution"
date: "2001-07-24T00:00:42"
categories: [gesehen]
---

*USA (2001)
Regie: Evan Reitman
Darsteller: David Duchovny (Ira Kane), Orlando Jones (Harry Block), Julianne Moore (Allison Reed), Seann William Scott (Wayne Green) und andere Helden*
[Offizielle Homepage](http://www.evolution-der-film.de)

Bei der Übung zu seiner Feuerwehrmann-Prüfung wird Wayne Green in der Wüste von Arizona von einem Meteoriten überrascht. Die beiden Kleinstadt-Professoren Ira Kane und Orlando Jones übernehmen kurzerhand die routinemäßige Untersuchung des Objektes und entdecken dabei einzellige Organismen, die sich rasend schnell vermehren und die Evolution in wenigen Tagen durchlaufen. Auch die sich einmischende Armee kann sie nicht daran hindern, bald eine Gefahr für die gesamte Menschheit darzustellen und nur Ira Kane, Orlando Jones, Allsion Reed und Wayne Green wissen ein Mittel dagegen...

Zuallererst: Wer physikalisch und logisch korrekte Filme mag, der meide diese Komödie. Denn das kann Evolution nicht bieten und will es auch gar nicht - es ist vielmehr eine geradlinige Parodie mit sehr viel Situations- und Dialogkomik, ohne sich aber auf das Niveau der Teenagerkomödchen wie American Pie herab zu begeben. 

Der Regisseur schickt den Zuschauer lieber auf einen Trip durch Filme wie Jurassic Park oder Akte X und verteilt dabei Sticheleien in alle Richtungen, ob es nun der typische Uni-Professor, sein typischer Student oder die Armee ist - dass man über die Witze nicht nachdenken sollte, erwähnte ich ja bereits.

Fazit: Wer dazu bereit ist, sich einfach nur unterhalten zu lassen, der ist mit dieser temporeichen Komödie gut bedient, allen Beckmessern rate ich dagegen ab!
