---
title: "Harry Potter und das Web 2.0"
date: "2007-07-29T23:18:11"
categories: [gedacht,gefunden]
---

Bei [Carlsen](http://www.carlsen-harrypotter.de/) kann man über das Cover für die deutsche Fassung des letzten Harry-Potter-Bandes abstimmen. Die nette Marketing-Kampagne ist jedoch nicht der Grund für diesen Beitrag, sondern die dazugehörige Website.

Diese sieht nämlich auf den ersten Blick so aus, als hätte mein Opera-Browser Schwierigkeiten beim Rendern der Page bekommen. Viele merkzettelartige Informationsblöcke sind wie zufällig übereinander angeordnet und verdecken sich so teilweise. Irgendwann bin ich auf die Idee gekommen, diese anzuklicken - und siehe da, man kann sie wie Fenster auf dem Desktop verschieben. Das [Web 2.0](http://de.wikipedia.org/wiki/Web_2.0) ist also auch bei den Verlagen angekommen und Carlsen hat gleich die Chance genutzt, mit einer Spielerei die ursprüngliche Idee ad absurdum zu führen. Statt einer besseren Interaktion und einem schnelleren Zugang zu Informationen, muss ich auf dieser Seite aufwendig Zettel beseite schieben, um überhaupt alle mir dargebotenen Informationen aufnehmen zu können.

So habe ich mir das neue Web definitiv nicht vorgestellt, und ich hoffe dass nicht viele Seiten diesem schlechten Beispiel folgen werden...
