---
title: "Machete"
date: "2010-11-29T22:25:26"
categories: [gesehen]
---

*USA (2010)
Regie: Ethan Maniquis, Robert Rodriguez
Darsteller: Danny Trejo (Machete), Jeff Fahey (Michael Booth), Jessica Alba (Sartana Rivera), Robert de Niro (Senator John McLaughlin), Michelle Rodriguez (Luz), Steven Seagal (Torrez), Cheech Marin (Padre Cortez), Don Johnson (Von Jackson), Lindsay Lohan (April Booth), Tom Savini (Osiris Amanpour) und andere B-Movie-Stars*
[Offizielle Homepage](http://www.machete-film.de/index.html)

*Machete* war ursprünglich nichts weiter als ein Fake-Trailer in Robert Rodriguez Beitrag *Planet Terror* des [Grindhouse](/blog/2007/09/13/death-proof/)-Projektes. Doch gerade das markante Gesicht von Danny Trejo lud geradezu dazu ein, aus dem Trailer einen ganzen Film zu machen. Und so muss sich der ehemalige mexikanische Bundesagent Machete nun als illegaler Einwanderer in Texas herumschlagen und wird dabei in ein Attentat auf den zur Wiederwahl anstehenden Senator McLaughlin verwickelt. Zusammen mit Sartana, einer Mitarbeiterin der Einwanderungsbehörde, und Luz, die als She eine Geheimorganisation namens "Netzwerk" leitet, muss er nun die Machenschaften des Senators, seines Beraters Booth und des Bosses eines mexikanischen Drogenkartells aufdecken und dabei ein ums andere Mal um sein Leben kämpfen...

Trash as Trash can. Wie zu erwarten, nimmt Robert Rodriguez auch in *Machete* seinen Film nicht allzu ernst. Ständig muss ich mir als Zuschauer die Frage stellen, ob dies wirklich noch eine Parodie auf B-Movies und Pulpfilme ist, oder die Drehbuchautoren einfach einen schlechten Tag hatten und wirklich Schund geschrieben haben. Die Übergänge sind auf jeden Fall fließend. Die Bandbreite reicht von der grandiosen Eingangssequenz, in der Machete die Köpfe der Gegner mit seinem gleichnamigen Werkzeug gleich reihenweise absäbelt und danach von einer nackten Frau überwältigt wird, bis hin zum schwachen Showdown, dessen Action zahm, langweilig und fast schon familientauglich inszeniert wurde.

Diese Bandbreite zeigt sich auch bei der Besetzungsliste. Neben Danny Trejo, der ein Cousin von Robert Rodriguez ist, und dessen Buddies Tom Savini und Michelle Rodriguez finden sich auch abgewrackte Altfälle wie Steven Seagal und Don Johnson zusammen mit B-Sternchen Marke Lindsay Lohan und Jessica Alba im Cast. Da muss sich Robert de Niro schon etwas seltsam vorgekommen sein auf dem Set, doch er gibt seinen Senator mit der nötigen Arroganz und stellt damit einen guten Gegenspieler dar. Insgesamt ist also nicht viel Schauspielerei zu sehen (dies würde die Trash-Optik konterkarieren); und trotzdem fällt Steven Seagal negativ auf mit seinen schrankartigen Körper, den er nur noch beschränkt bewegen kann.

Thematisch hat sich der Film jedoch mehr vorgenommen, als nur einem markanten Gesicht und Actionhelden zu huldigen. Über die gesamte Laufzeit schwingt unverhohlen Kritik am Umgang der USA mit ihrem südlichen Nachbarn Mexiko mit. Dabei geht es u.a. um die Ambivalenz der Amerikaner, welche die Mexikaner als billige Arbeitskräfte ausbeuten und gleichzeitig rechten Hardlinern ihre Stimme geben, die am Liebsten ihr Land durch einen Zaun von den Einwanderern abschotten wollen. Diese Kritik wird aber so direkt und plakativ vorgetragen, dass sie sich im Trash und den Vorurteilen, denen der Film humorvoll auf Kosten der Latinos frönt, etwas verliert. 

Fazit: *Machete* kann sich aus meiner Sicht einfach nicht entscheiden, was er sein will - Trash, Action, Latino-Exploitation oder gar Sozialstudie? So ist er von allem ein wenig, aber nichts so richtig. Klar will sich Robert Rodriguez nach *Planet Terror* nicht wiederholen, doch gerade die übertrieben-komische Action fehlte mir diesmal weitgehend. Nur selten verfolgt der Film seine teilweise absurden Ideen konsequent weiter; meist bleibt er zu zahm und kurzatmig, um zu überzeugen.
