---
title: "The Elder Scrolls V Skyrim - Mein Tagebuch, Teil 1"
date: "2011-12-26T02:19:30"
categories: [gedacht,gespielt]
---

Bevor ich über meine Eindrücke vom jüngsten Spross der *The Elder Scrolls*-Serie berichte, will ich kurz meine bisherigen Erfahrungen mit *Bethesda*-Spielen schildern, die großen Einfluss auf meine Erwartungen an *Skyrim* haben.

Mein erstes Spiel der Spieleschmiede war *The Elder Scrolls III Morrowind*. Im Jahre 2002 war ich vor allem von der Grafik des Open-World-Rollenspiels angetan. Zum ersten Mal gab es dank Pixelshadern halbwegs realistische Wasseroberflächen zu bewundern und das Spiel erforderte mit dem von NVidia gehypten [T&L](http://de.wikipedia.org/wiki/Transform_and_Lighting) massiv Grafikkartenpower. Ich war zu dem Zeitpunkt noch nicht auf dem RPG-Trip und legte das Spiel nach dem Sattsehen an der Grafik schnell zur Seite.

Erst Jahre später, als ich mit der *Gothic*-Serie Genreerfahrungen gesammelt hatte, wagte ich angestachelt durch den [legendären Speedrun](http://www.youtube.com/watch?v=m1IRxTN-_kU) einen neuen Versuch - und kam nicht sehr viel weiter. So schön und fantasievoll die Welt in Szene gesetzt war, so leer war sie auch. Als Spieler begegnete ich kaum NPCs in der endlos freien, aber auch unbevölkerten Welt. Erst in den Gebäuden liefen Charaktere herum, aber da alle Gebäude von außen ähnlich aussahen und die Open World an den Haustüren mit einem Ladebildschirm endete, fand ich die Welt von *Morrowind* eher steril und nicht sehr spielenswert.

Zudem habe ich ein sehr persönliches Problem mit der Grafikengine: Charaktere und Landschaft bilden keine Einheit und sehen aus meiner Sicht aus wie ein Paar Schuhe, das nicht zusammenpassen will. Die Figuren scheinen über die Oberfläche zu schweben statt zu gehen, die Bewegungen der Füße sehen aufgesetzt aus und nicht so, als würden sich die Figuren wirklich damit bewegen. Durch diese schlechte Kollisionsabfrage büßt das Spiel massiv an Glaubhaftigkeit ein und erschwerte es mir so, Zugang zu der Spielewelt zu finden.

Der Nachfolger *Oblivion* machte an dieser Stelle einen großen Schritt vorwärts, doch scheiterte ich diesmal an der nächsten Hürde: Ich verstand das Spielprinzip einfach nicht. Bei der Charaktererstellung wird vom Spiel nicht erklärt, wie sich die einzelnen Attribute und Völker auf die Spielfigur auswirken. Ich rannte also relativ blind in die ersten Quests hinein, voller offener Fragen zur Charakterentwicklung und mit einigem Groll gegenüber dem grauenvollen User Interface, und landete schließlich zum ersten Mal in der namensgebenden höllengleichen *Oblivion*-Welt. Dort respawnten ständig neue Gegner, und ich fand den Ausgang nicht. Klar gibt es in jedem Open-World-Spiel Gegenden, die man mit einem wenig entwickelten Charakter nicht betreten sollte, da die Gegner zu stark sind. Aber dann sollte es zumindest möglich sein, den Rückzug anzutreten. Ich dagegen hatte das Gefühl, dass ich für die Hauptstory durch das *Oblivion* musste und mich dort plötzlich in einer tödlichen Sackgasse ohne Ausgang wiederfand. Heute würde ich an so einer Stelle nun Google bemühen, damals habe ich das Spiel einfach zur Seite gelegt.

Einen weiteren Anlauf mit *Bethesda* unternahm ich schließlich bei *Fallout 3*. Hier machte ich gleich zu Beginn den Fehler, meinem Charakter falsche Attribute zu geben. Denn auf der PS3 hatte ich einfach keine Maus zur Verfügung, um das Spiel wie einen Egoshooter zu spielen. Für das V.A.T.-System, bei dem der Kampf pausiert wird und auf einzelne Körperteile des Gegers gezielt werden kann, benötigt der eigene Charakter aber vor allem eins: Beweglichkeit. Ohne diese war das Spiel ein ganzes Stück schwerer als es sein musste - und leider konnte dieses Attribut nur sehr eingeschränkt verbessert werden.

Aber ich habe mich trotzdem durchgekämpft und war überrascht, wie gut das Szenario einer zerstörten Welt nach der nuklearen Katastrophe umgesetzt war und wie die Schwäche von *Morrowind*, eine recht leblose Welt zu besitzen, im Szenario von *Fallout* zu einer Stärke wurde. Relativ früh im Spiel lief ich durch eine zerstörte Kleinstadt, als ich plötzlich ein Piepsen vernahm, gefolgt von knatternden Lautsprecheransagen, und aus dem Augenwinkel eine Bewegung wahrnahm. Aus einem sicheren Versteck heraus (Vorsicht ist die Mutter der Porzellankiste - am Anfang starb ich oft schneller, als ich die mutierten Gegner ausmachen konnte) konnte ich schließlich beobachten, wie eine Sonde durch die Straßen des Städtchens patroullierte. Der Schreck, der mir dabei durch die Glieder fuhr, war eine direkte Folge der [stimmigen Atmosphäre](/blog/2011/09/06/washington-d-c-und-die-fallout-brille/) des Spiels.

Und doch habe ich es ebenso wie die beiden Teile der *Elder Scrolls* nicht durchgespielt. Warum? Weil ich wieder in eine Sackgasse geraten bin und mich vom Spiel allein gelassen fühlte. Das wenig aussagekräftige Questlog gab mir nur eine Richtung vor und ich habe mehrere Stunden lang erfolglos nach einem Weg gesucht, ohne ihn zu finden. Google war leider auch keine große Hilfe und so habe ich dann schweren Herzens das Spiel beiseite gelegt, da ich ohnehin keine Zeit mehr zum Zocken hatte.

*Skyrim* soll nun mein erstes *Bethesda*-Spiel werden, welches ich durchspiele. Das habe ich mir fest vorgenommen. Um dies zu erreichen, habe ich mich vorher etwas über die Kampfmechanik informiert und werde versuchen, Probleme wie bei *Oblivion* und *Fallout 3* konstruktiv anzugehen. Ob mir das gelingt, werden die folgenden Beiträge zeigen.
