---
title: "Ethik und/oder Religion?"
date: "2009-04-26T19:43:08"
categories: [gedacht,getan]
---

Berlin macht Dinge gerne anders als andere Bundesländer. So gibt es in der Schule keine Wahl zwischen den Schulfächern Ethik bzw Religion, sondern seit kurzem Ethik für alle und Religionsunterricht auf freiwilliger Basis. Dies ist möglich, weil Berlin 1948 kurz vor dem Verfassen des Grundgesetzes ein eigenes Schulgesetz verabschiedete und dieses über die sogenannte [Bremer Klausel](http://de.wikipedia.org/wiki/Bremer_Klausel#Berlin) geschützt ist. Die Kirchen finden das natürlich nicht so gut und haben das Aktionsbündnis [Pro Reli](http://de.wikipedia.org/wiki/Pro_Reli) ins Leben gerufen und einen weiteren <del datetime="2009-04-26T17:40:11+00:00">Bürgerentscheid</del> [Volksentscheid](/blog/2008/04/27/wieviel-demokratie-hatten-sie-denn-gerne/) erzwungen.

Also bin ich heute nach dem Mittagessen (frischer Beelitzer Spargel) in mein Wahllokal gepilgert und habe abgestimmt - für eine Gleichstellung von Ethik und Religion. Der Entscheid ist erwartungsgemäß an der mangelnden Stimmenanzahl gescheitert, aber meine Meinung habe ich trotzdem kundgetan ([vielleicht muss ich das Kreuz noch ein zweites Mal machen](http://www.tagesspiegel.de/berlin/Pro-Reli;art270,2781799)). Ich selber hatte das Glück, weder Ethik noch irgendeinen Konfessionsunterricht zu erhalten, da an meiner Schule nicht genügend Lehrer zum Unterrichten zur Verfügung standen - die meisten Lehrer waren in der [DDR](http://de.wikipedia.org/wiki/Christen_und_Kirche_in_der_DDR) ausgebildet, die keinen Religionsunterricht duldete. Und so bin ich eigentlich dafür, dass beide Möglichkeiten optional sind, aber dies stand leider nicht zur Abstimmung.

Auf der anderen Seite sehe ich einige [Inhalte des Ethik-Unterrichts](http://www.berlin.de/sen/bildung/unterricht/ethik/index.html) (Humanismus, Werte) als wichtig an, jedoch bedarf es dafür nicht eines extra Unterrichtsfaches (siehe mein Beispiel) und laut Aussagen von Freunden und Kollegen leisten die Religionsfächer dies auch. Atheismus ist nur eine andere Form von Religion (nämlich das Nichtglauben an eine übergeordnete Moralinstanz) und dieses Glaubensvakuum will der Staat natürlich gerne füllen. Damit ist Ethik ebensowenig neutral wie jede andere Konfession und sollte auch ebenso freiwillig sein oder zumindest gleichberechtigt.

Mit der Meinung habe ich mich nun nicht durchgesetzt, aber dies ist halb so wild, da ich keine Kinder habe, die davon betroffen sind. Und der nächste Volksentscheid kommt bestimmt!
