---
title: "TV-Woche Nummer 1"
date: "2006-01-05T23:04:00"
categories: [gesehen]
---

Drei Filme habe ich diese Woche zumindest teilweise gesehen und möchte dazu ein paar Worte verlieren.

Am Dienstag strahlte das ZDF den ersten Teil des "TV-Historiendramas" **Napoleon** aus. Leider konnte der Film jedoch trotz des Staraufgebotes dem Stoff nicht gerecht werden. Dies fing bei der mäßigen Ausstattung an: Viele Kulissen wirkten billig und leer und die digitalen Effekte erkannte man auf den ersten Blick, so dass kaum ein Gefühl für die Zeit aufkam. Der Regisseur hatte das Ensemble auch nicht im Griff und so übten sich alle Darsteller in grauenvoller Selbstinszenierung, ohne ihre Rollen auszufüllen. Passend dazu ließ das episodenhafte Drehbuch Dramaturgie und Spannung missen und die Kamera wirkte statisch wie in billigsten TV-Filmen. Dementsprechend habe ich mir keinen weiteren der vier Teile angesehen...

Mittoch sendete dann 3Sat mit **Komm, süßer Tod** einen Film mit Kabarettist Josef Hader in seiner Antihelden-Rolle als Ex-Kommisar Brenner (zuletzt im Kino mit Silentium). Diesmal schlug er sich als Rettungssanitäter durch und geriet in die Verwicklungen rund um rivalisierende und mordende Rettungsdienste. Nach dem gewohnt schweren Einstieg, in dem man versuchen muss, sich in den Dialekt der Österreicher hineinzuhören, konnte man sehr gut den trockenen Humor des Films genießen und sich den tragikomischen Situationen hingeben. Denn Brenner musste nach jedem erfolgreichen Schritt in Richtung Klärung des Falles erst einmal eine Pause einlegen (Rauchen, Eis essen, etc.), so dass es gegen Ende des Films zu einem Chaos kam, welches als Zuschauer nur schwer zu überblicken war.

Trotzdem hat mir der Film schon aufgrund seiner Antihelden und des österreichischen Flairs sehr gut gefallen. Und der Humor von Hader ist einfach wundervoll schwarz und wird von Regisseur Wolfgang Murnberger mit vielen bekannten Gesichtern hervorragend in Szene gesetzt. Mein absolutes Highlight des Films ist jedoch die Sexszene zwischen den beiden Halbinvaliden Brenner und Klara!

Heute nun brachte VOX **Die Royal Tenenbaums**, welchen ich mir damals im Kino nicht ansehen konnte. Der Film ist schon aufgrund der halbwegs ernsten Rollen des unzertrennlichen Paares Ben Stiller und Owen Wilson bemerkenswert, welche sonst als ehemalige "Saturday Night"-Comedians nicht gerade durch ihre Schauspielkunst auffallen. Neben Gene Hackman, Anjelica Huston, Gwyneth Paltrow, Bill Murray oder Danny Glover mag dies aber einfacher sein als in einer Hauptrolle, welche den Film tragen muss.

Der Film arbeitet viel mit der Musik und einem imaginären Erzähler aus dem Off, welcher vor allem bei den herrlich geschnittenen Rückblenden zu gefallen weiß. Generell lebt der Film von seiner skurilen Erzählweise und den chaotischen Charakteren, welche geschickt den Mangel an einer wirklichen Story überdecken. Deshalb ist der Film zwar sehr sympathisch, reicht aber nicht an die besseren John-Irving-Verfilmungen wie "Garp" oder "Hotel New Hampshire" heran.
