---
title: "More than honey"
date: "2013-04-27T22:20:21"
categories: [gesehen]
---

*Deutschland/Österreich/Schweiz (2012)
Regie: Markus Imhoof*
[Offizielle Homepage](http://www.morethanhoney.ch/)

Als vor einem Jahr ein Kollege auf die Idee kam, mitten in Berlin seinen eigenen Honig zu produzieren, da war ich weniger an den dazu nötigen Bienen als an ihrem süßen Produkt interessiert. Genauer gesagt wusste ich nicht viel mehr über Bienen als dass sie in Schwärmen leben. Das hat sich durch die Beschäftigung mit dem Imkern inzwischen geändert, und *More than honey* hat dem viele interessante Aspekte hinzugefügt. Da er gerade den [Deutschen Filmpreis als beste Dokumentation](http://www.deutsche-filmakademie.de/uploads/media/Preistraeger_2013.pdf) gewonnen hat, schiebe ich mit einem halben Jahr Verspätung diese Kritik nach.

Der Filmer Markus Imhoof ist durch seine Familie Bienen-vorbelastet. Sein Großvater beherbergte als Obstbauer eine große Menge Völker in einem eigens dafür errichteten Haus und kümmerte sich selbst um die Bienenzucht. Imhoofs Tochter wiederum forscht in Australien an Bienenrassen, die immun gegenüber dem aktuell grassierenden Bienensterben auf der Welt sein sollen. Damit hatte Imhoof genügend Vorwissen, um sich auf eine Reise um die Welt zu machen und sich dem Thema von verschiedenen Seiten zu nähern.

Dabei zeigt er neben dem ursprünglichen Leben der wilden Bienen als faszinierend komplexes Kollektiv auch verschiedene Formen der modernen Bienenwirtschaft. Diese reichen von Königinnenzüchtern bis zur kapitalistisch-industriellen Massenhaltung in den USA und der kommunistischen Absurdität in China, wo Menschen die Aufgaben der dank Pestiziden ausgerotteten Bienen übernehmen und in mühevoller Kleinstarbeit die Pollen von den Blüten sammeln und anderswo handbestäuben.

Doch nicht überall leben Biene und Mensch in einer funktionierenden Beziehung nebeneinander. Die sogenannten Killerbienen, die sich gerade über Mittelamerika bis in die USA ausbreiten, sind eine Zuchtrasse, die neben der Immunität gegenüber den meisten Seuchen auch eine Aggressivität mitbringt, welche sie zu einer Gefahr für den Menschen macht. Ob dies der einzige Weg für die Bienen ist, ihrem Aussterben zu entgehen, dass kann *More than honey* natürlich nicht beantworten. Der Film zeichnet aber ein gutes Bild von dem komplexen Geflecht der Natur, in welchem Mensch und Biene über die Jahrtausende eine gegenseitige Abhängigkeit entwickelt haben, und von den vielen Einflussfaktoren, die vielleicht das Ende der Bienen bedeuten können.

Neben der Auseinandersetzung mit der Thematik der aussterbenden Bienen hat sich die Filmcrew vor allem mit der [Visualisierung der Tiere](http://www.morethanhoney.ch/makroaufnahmen) beschäftigt. So gibt es tolle Aufnahmen aus Bienenstöcken und vom Flug der Königin, allerdings waren andere Bilder wie die Verfolgung der Bienen im Flug sehr irritierend für mich, da sie mit 300 Bildern pro Sekunde aufgenommen und dann in 24fps, also wie in Zeitlupe, abgespielt wurden.

Alles in allem ist der Film aber optisch sehr gelungen (fast scheue ich mich, von einer Dokumentation zu sprechen) und zudem sehr informativ. Imhoof vermittelt immer genügend Grundwissen, so dass auch Zuschauer ohne Vorbildung in Sachen Bienen den verschiedenen angesprochenen Problemfeldern folgen können. Ich lehne mich einmal weit aus dem Fenster und behaupte, dass noch kein Film die Biene so umfassend behandelt hat - der Hobbyimker in mir spricht also eine klare Empfehlung aus!
