---
title: "Attack of the unsinkable rubberducks"
date: "2008-10-11T15:03:14"
categories: [gelesen]
---

*von Christopher Brookmyre,
erschienen bei Abacus, ISBN 978-0-349-11881-9, 9,45€*

Jack Parlabane ist tot. Dabei muss er eigentlich noch das Medium Gabriel Lafayette entlarven, der gerade in wissenschaftlichen Tests seine übernatürlichen Fähigkeiten bewiesen hat. Doch wie soll er das tun, wenn er gerade aus dem Fenster seiner eigenen Wohnung gestürzt ist, während Lafayette versucht, durch sein scheinbar nachgewiesenen Fähigkeiten das Bildungssystem von Schottland mit neuen Inhalten anzureichern?

So viel über die Handlung verrät bereits der Buchrücken. Und tut dem Leser damit keinen Gefallen, denn das Ereignis des Todes des Hauptcharakters findet erst 50 Seiten vor Schluss statt. Und ist wie so vieles im Buch auch noch gelogen.

Im Kino finde ich das Prinzip, die Handlung aus bestimmten Perspektiven zu zeigen, die nicht die ganze Wahrheit ausmachen, sehr anregend. Man hat einen überraschenden Moment beim ersten Sehen, schaut sich den Film vielleicht ein zweites Mal an und freut sich über die vielen Andeutungen, die von Anfang an auf den Trick hinwiesen. In Büchern kann ich damit aber gar nichts anfangen. Zum Einen lese ich diese kein zweites Mal, da dies mehr Zeit als die anderthalb Stunden eines Films in Anspruch nimmt. Zum Anderen benötige ich zwei bis drei Wochen für ein Buch, da ich nur unterwegs und abends im Bett lese. Da ist es kein Spaß, wenn man erst bereits gelesene Seiten noch einmal durcharbeiten muss um festzustellen, dass der Autor den Leser durch seine Andeutungen ganz gemein aufs Glatteis geführt hat.

Christopher Brookmyre nutzt dieses Prinzip ausgiebig; nicht nur im Rahmen des Buches sondern auch in den einzelnen Kapiteln. Immer wird die wichtige Information vorenthalten, die das soeben gelesene in einem ganz anderen Licht erscheinen lässt. Ein weiteres Problem stellte für mich dar, dass es drei Ich-Erzähler in der Handlung gibt, und ich immer erst nach ein paar Seiten merkte, dass die handelnde Person gewechselt hatte und die Kontinuität nicht mehr gegeben war. Zudem läuft die Geschichte nur ganz langsam an, da die Idee, alles aus der Perspektive der Buchmitte zu erzählen, mächtig in die Hose geht.

Was am Ende bleibt ist ein zeitweise witziges Buch, dass einem auch noch Einblicke in die Scheinwelt der Parapsychologie bietet. Aber ich mag es als Leser einfach nicht, wenn man mich dermaßen verarscht, wie es Christopher Brookmyre tut, und kann das Buch deshalb nicht weiterempfehlen.
