---
title: "Ein Fernsehabend in der ARD"
date: "2005-10-20T11:24:58"
categories: [gesehen]
---

Das Erste Deutsche Fernsehen hat es mit seinem Programmmix gestern doch tatsächlich geschafft, mich fast ununterbrochen vor dem Fernseher zu halten.

Den Anfang machte der erste Teil einer um eine halbe Stunde zur Kinoversion verlängerten Fassung von **"Der Untergang"**. Wahrscheinlich hat sich die ARD an der Produktion beteiligt, anders kann ich mir die schnelle Ausstrahlung im Free-TV nach nur einem Jahr nicht erklären.

Als der Film in die Kinos kam, gab es großes Geschrei um den Aspekt des Films, die "Bestie Hitler" als Mensch zu zeigen. Wie man diese Rolle jedoch als menschlich bezeichnen kann, erschließt sich mir nicht. Ganz im Gegenteil wird die Riege um Hitler im Führerbunker als eine Menge von Menschen gezeigt, die aus unterschiedlichsten Gründen die nationalsozialistische Ideologie stützten. Die Einen im Wahn nach Größe oder als Vernichter der "Feinde des deutschen Volkes", die anderen als kalkulierende Karrieristen. Der Film verschweigt jedoch nicht die Folgen des Krieges: Die leidende Zivilbevölkerung (vorher Unterstützer des Krieges, wie Goebbels feststellt), die Vernichtung der Juden, die sinnlose Zerstörung von Armeen. Dass der Film auch Helden zeigt und die Sekretärin von Hitler als unschuldige Mitläuferin darstellt, sollte aber zumindest kritisch hinterfragt werden, genau wie die Rolle des deutschen Volkes insgesamt.

Ansonsten weiß der Film den Zuschauer durchaus zu fesseln, schon allein aufgrund des Handlungsortes im Führerbunker kurz vor dem Fall Berlins. Die Handlungsstränge des kleinen Kämpfers aus der Hitlerjugend und des Professors auf humanitärer Mission bilden dazu einen der Tristesse vorbeugenden Kontrast und informieren den Zuschauer gleichzeitig über das "reale" Geschehen außerhalb es Bunkers.

Bei der Ausstattung hat sich Produzent Bernd Eichinger mal wieder voll ins Zeug gelegt. Keine erkennbaren Matte-Paintings im Hintergrund oder dürftige CGI-Effekte zerstören des Bild des belagerten Berlins; viele Originaldrehorte vermitteln größtmögliche Authentizität. Auch die Schauspieler tragen ihren Teil dazu bei, und bis in die kleinsten Nebenrollen treten bekannte Gesichter vor die Kamera (z.B. darf sich Julia Jentsch zu Beginn des Films kurz bei Hitler als Sekretärin bewerben).
Alles in allem also eine sehr gute Produktion, die den Zuschauer zu fesseln vermag, aber an einigen Stellen auch hinterfragt werden sollte.

Passend dazu ging es weiter mit einer Folge der Dokuserie **"Die Zwanziger Jahre"**, die sich mit den Themen Wirtschaft und Forschung dieses Jahrzehnts befasste. Hängen geblieben ist vor allem die schrittweise Entfremdung zwischen den Spitzenkräften der Forschung und der Wirtschaft und dem in der Industrie arbeitenden Volk, dass mit der schnellen Entwicklung nicht immer Schritt halten konnte. Im Sinne von History Repeating konnte sich sogar einer der wenigen Zeitzeugen nicht verkneifen darauf hinzuweisen, dass damals die Wirtschaft mit den gleichen Forderungen wie heute die Löhne zu kürzen vermochte und die Arbeitslosigkeit auf Rekordhöhen stieg. Ironie der Geschichte: Die Wirtschaft förderte den Abbau der Demokratie und unterstützte Hitler, der dann ausgerechnet mit dieser ökonomischen Ungerechtigkeit Propaganda machte - allerdings auf Kosten anderer Sündenböcke, der Juden. Und das Volk heute wie damals glaubte den extremen Meinungen, denn diese sind im Vergleich zu Realität an Einfachheit nicht zu unterbieten. Es ist schon äußerst traurig, wenn der neugewählte Bundestagspräsident als erste Aktion eine neue deutsche "Leitkultur" fordert.

Nach den Tagesthemen kam dann **Harald Schmidt** zum Zuge, der mir vor allem mit seiner "Neue Folgen"-Aktion aus dem Herzen sprach: Wieso blenden die Privatsender bei Serien immer diesen Schriftzug ein? Glauben sie etwa, dass dies den zappenden Zuschauer dazu anhält, bei dem Programm zu bleiben, nur weil es eine neue Folge ist? Da sollten sie es lieber mit etwas mehr Inhalt versuchen, anstatt das Niveau ständig zu senken.

Um 0:35h (also quasi schon heute) folgte schließlich der Abschluss des Abends mit der Zeichentrick-Version von **"Der Herr der Ringe"** aus dem Jahre 1977. Ich bin leider während der Durchquerung von Moria eingenickt, aber kann zumindest über die vorangehende, erste Stunde berichten. Der Film ist mehr ein Trick- als ein gezeichneter Film. Vielen Szenen sieht man an, dass dafür echte Menschen und Pferde vor der Kamera standen und danach in die Szenen "koloriert" wurden (die Ringgeister, der Einführungssequenz, die Kneipe "Zum tänzelnden Pony"). Außerdem kamen bei der Schattenwelt und den Zaubern von Saruman sehr surreale Hintergründe zum Einsatz, die sich wohl mit der Produktion in den 70er Jahren begründen. Aber trotz der ungewohnten Darstellung der Charaktere (Frodo sieht aus wie Pumuckl) und der sehr schnellen, abgehackten Erzählweise kam bald die gewohnte Spannung auf, wie es wohl weitergeht mit Frodo und dem Ring. Bei seiner Rettung kurz vor Bruchtal wendet übrigens auch der Trickfilm einen inszenatorischen Trick an und präsentiert Legolas (in "Die Gefährten" erscheint Arwen) an Stelle von Glorfindel.

Sehr interessant fand ich auch, dass Peter Jackson für seine Trilogie einige Einstellungen scheinbar aus dem Trickfilm übernommen hat. Wie der Ring zu Gollum fand und der Abschied von Bilbo zu seinem Geburtstag zeigen fast exakt die selben Blickwinkel wie in "Die Gefährten".
