---
title: "Burn after reading"
date: "2008-10-12T11:40:59"
categories: [gesehen]
---

*USA (2008)
Regie: Joel und Ethan Coen
Darsteller: Frances McDormand (Linda Litzke), Brad Pitt (Chad Feldheimer), George Clooney (Harry Pfarrer), Tilda Swinton (Katie Cox), John Malkovich (Osbourne Cox), Richard Jenkins (Ted Treffon), David Rasche, J.K. Simmons und andere Amateure*
[Offizielle Homepage](http://www.burnafterreading-derfilm.de/)

Osbourne Cox hat ein Problem: Nicht nur mit dem Alkohol, dass seine Frau Katie sich scheiden lassen will und dass die CIA ihn rausgeschmissen hat. Nein, zwei Angestellte eines Fitnessstudios versuchen ihn mit einer Frühfassung seiner Memoiren zu erpressen in der Hoffnung, dass die darin enthaltenen Informationen politisch brisant und damit wertvoll sind. Die eine Erpresserin, Linda, braucht Geld für Schönheitsoperationen, und bietet die CD mit Osbournes Daten sogar den Russen an. Mitten drin in diesem Spiel der Amateure findet sich auch Harry Pfarrer wieder, Mitarbeiter im Außenministerium, der nicht nur mit Osbournes Frau sondern auch mit Linda schläft. Und als er den Erpresser-Komplizen Chad in Osbournes Haus erwischt, wird die Angelegenheit langsam lebensgefährlich...

Wenn es Eines gibt, was die Coen-Brüder sehr gut beherrschen, dann sind es Filme, in denen scheinbar einfache Pläne in den Händen der Protagonisten so fehlschlagen, dass es am Ende immer Tote gibt. Da macht auch *Burn after reading* keine Ausnahme, obwohl man dem Sammelsurium an amateurhaften Figuren gar nicht zutraut, einen Mord begehen zu können. Das Genrevorbild für den Film sind diesmal Spionagethriller, die mit dem Ende des Kalten Krieges fast ausgestorben sind. Die Coens haben die Handlung trotzdem in die Gegenwart gelegt und kokettieren gewollt mit dem früheren Gegner Russland und der heute lieber die eigenen Bürger überwachenden CIA. Außerdem darf natürlich eine Autoverfolgungsjagd ebensowenig fehlen wie in den Fluss geworfene Leichen.

Doch *Burn after reading* ist nur hintergründig ein Agentenfilm. Im Mittelpunkt stehen eindeutig die Figuren, bei denen sich die Coens an Absurditäten mal wieder selber übertroffen haben - wenn man überhaupt von Figuren sprechen kann, eigentlich sind alle Charaktere total übertrieben, die reinsten Karikaturen und auf maximale Komik ausgelegt. George Clooney als Harry besteht zum Beispiel nur aus Neurosen: Er besitzt unzählige Allergien, einen gut entwickelten Verfolgungswahn, interessiert sich in jeder Situation für Fußbodenbeläge und achtet penibel auf sein Fitnessprogramm. Mit seinem Faible für schnellen Sex über Internet-Datings ist er die zentrale Figur in der Handlung. Zudem hat er früher im Personenschutz gearbeitet, jedoch noch nie jemanden erschossen. Zwangsläufig machen die Coen ihn zum ersten Mörder des Films, was die Figur total zusammenbrechen lässt.

Noch extremer hat es Brad Pitt getroffen. Seine Rolle Chad ist ein in den 80ern mit der geistigen wie frisurentechnischen Entwicklung stehengebliebener Fitnessjunkie. Die Szene des ersten Treffens des Erpressers Chad mit Osbourne Cox wird geradezu zelebriert, wenn Pitt im Anzug und mit Helm auf dem Fahrrad zur Verabredung eintrifft und sich einen Schlag auf die Nase abholt. Er ist unter den Einäugigen im Film der Blinde und darf als Erster das Zeitlich segnen. Seine Komplizin Linda (Coen-Stammkraft Frances McDormand) ist dagegen die treibende Kraft hinter dem sich entwickelnden Chaos. Sie will sich unbedingt liften lassen und schreckt dabei vor nichts zurück: Erst wird Osbourne erpresst, dann die Russen mit hineingezogen und schlussendlich will sie sogar die CIA um das Geld erleichtern, nachdem sie auch noch ihren Chef Ted ins Verderben gestürzt hat.

Während diese drei sich also richtig austoben in ihren Rollen, sind Charaktermime John Malkovich und Tilda Swinton sichtlich unterfordert. Allein die Fliege lässt Osbourne Cox schon fehl am Platz wirken, und dann wankt die Figur auch noch zwischen absolutem Versager und hartem Agenten. Da hätte ich ehrlich gesagt mehr erwartet. Die Rolle der harten Ehefrau neben Osbourne lässt dagegen Tilda Swinton keine Spielräume - sie hat zu wenige Auftritte und versucht gar nicht erst, ihre Rolle so ins Extreme zu steigern wie ihre Filmpartner.

Was *Burn after reading* bei all dem Witz und den kunstvoll ineinander verwobenen Details fehlt ist ein klassischer Spannungsbogen. Es gibt keine sich steigernde Handlung, sondern zwei eher überraschende Höhepunkte, bei denen der ansonsten keine weiteren Auftritte habende Chef der CIA (großartig: [J.K. Simmons](/blog/?s=J.K.+Simmons&submit=+%3F+)) die teilweise beobachteten, teilweise dem Zuschauer vorenthaltene Ereignisse auf eine sehr makabre Art und Weise zusammenfasst. Nach dem Zweiten dieser Höhepunkte ist der 84 Minuten kurze Film dann plötzlich zu Ende. Ohne Vorwarnung, und ohne alle Handlungsfäden aufgelöst zu haben.

Fazit: Die Coens haben mit *Burn after reading* einen sehr witzigen Film gedreht (und endlich wieder selber geschrieben), der gekonnt mit Versatzstücken aus den Agententhrillern des Kalten Krieges spielt. Doch leider fehlt der Handlung ein roter Faden - die extreme Überzeichnung der Figuren und die sich in den Rollen austobenden Stars können den Film nicht vollständig tragen. Nach [Ein (un)möglicher Härtefall](/blog/2003/10/29/ein-unmoglicher-hartefall/) und [Ladykillers](/blog/2004/07/28/ladykillers/) geht es jedoch eindeutig aufwärts mit den Komödien der Coen-Brüder.
