---
title: "The Turing Test"
date: "2011-04-16T22:05:51"
categories: [gelesen]
---

*von Chris Beckett,
veröffentlicht von Elastic Press, ISBN 978-0-9553181-8-4, 7,99£*

Ich weiß gar nicht mehr, auf welcher Website mir Chris Beckett empfohlen wurde. Aber irgendwann rutschte die Zusammenstellung seiner Kurzgeschichten auf meiner Amazon-Bücher-Wunschliste nach oben und so bestellte ich das Buch trotz meiner aus Schulzeiten stammenden Abneigung gegenüber dieser Form der Prosa. Diese rührt vermutlich daher, dass ich ein Mensch bin, der sehr stark auf Atmosphäre reagiert. Die Kürze einer Kurzgeschichte bei gleichzeitig geringer Formalisierung (verglichen mit noch kürzeren Werken wie z.B. Gedichten) führt meist dazu, dass entweder die Atmosphäre zu kurz kommt oder mich der Inhalt nicht anspricht und ich so enttäuscht bin vom Ergebnis.

Bisher haben mich in diesem Genre eigentlich nur [Lem](/blog/?s=stanislaw+lem) und Kafka überzeugt. Bei ersterem waren die handelnden Personen (Ijon Tichy, Pilot Pirx) meist bekannt und eingeführt, so dass eine Hintergrund-Atmosphäre automatisch mitschwang. Bei Kafka dagegen machte oftmals die fehlende Atmosphäre, die vollkommene Ungewissheit über das Funktionieren der beschriebenen Welt, aus dem Manko einen Vorteil und sorgte für eine ganz eigene Atmosphäre.

Bei Chris Beckett dagegen funktioniert keines dieser beiden Muster. Man kann ihm zugute halten, dass er eine breite Auswahl an Themen behandelt, aber dadurch wirkt das Buch auch stark fragmentiert. Zudem ist er ein stark figurenorientierter Schriftsteller, was sich mit sich mit der Form der Kurzgeschichte beißt, da darin die Charaktere nicht in der notwendigen Ausführlichkeit beschrieben werden können.

Wenn sich dann auch noch die meisten Geschichten auf ausgetretenen Pfaden bewegen, dann wird das Lesen schnell zu einer langweiligen Angelegenheit. Deshalb kann ich das Lob in Form des Vorwortes von Alastair Reynolds und des [Edge Hill Short Story Prize](http://www.edgehill.ac.uk/news/2009/07/the-turing-test-wins-the-2009-edge-hill-short-story-prize) nicht nachvollziehen - wenn dieser Band wirklich ein Highlight der zeitgenössischen Science Fiction ist, dann muss ich das Genre für tot erklären.

Denn erst auf Seite 85 hat mich *The Turing Test* zum ersten Mal aufhorchen lassen. Dort mischte sich als überraschende Zutat etwas Umweltschutz in eine Geschichte, die irgendwo zwischen *Matrix* und *The 13th Floor* pendelte. Es wurde eine Welt beschrieben, in der die Menschheit sich aus eigenem Antrieb in eine virtuelle Welt zurückgezogen hat, weil ein in einer Brutstation lebender Mensch mit einem simulierten Leben nur ein Fünftel an Energie und Rohstoffen verbraucht. Ein interessanter Ausweg für unseren Planeten und die Menschheit, wie ich finde.

Bis zum Ende des Buches folgen aber nur wenige weitere Highlights dieser Art. Meist spielen die utopischen Ideen nur die Rolle eines Hintergrundszenarios, um die Auswirkungen auf einzelne Personen zu beleuchten. Da diese aber meist blass und unzureichend gezeichnet sind, hätte ich mir gewünscht, dass aus ein paar der Geschichten richtige Bücher geworden wären und nicht nur Kurzgeschichten - denn interessant und nachdenkenswert sind die Themen schon, aber nicht in dieser starken Komprimierung.

So ist *The Turing Test* eben nur eine Sammlung von im Durchschnitt langweiligen, weil ideenarmen Kurzgeschichten, bei denen die wenigen positiven Ausreißer nicht ausreichen, eine Empfehlung meinerseits auszusprechen.
