---
title: "Männertag 2011 - Wanderung zum Kyffhäuser"
date: "2011-06-05T23:28:02"
categories: [gewesen,getan]
---

1190 starb der deutsche Kaiser Friedrich I., genannt Barbarossa, während des dritten Kreuzugs im Fluss Saleph in der heutigen Türkei. Einer [Sage](http://www.kyffnet.de/Geschichte/Sagen/sagen.html) nach jedoch schläft er nur mit seinen Getreuen in einer unterirdischen Höhle im Kyffhäusergebirge über einen Tisch gebeugt, durch welchen sein roter Bart hindurchgewachsen ist. Alle 100 Jahre schickt er einen Helfer an die Oberfläche um nachzusehen, ob noch Raben um den Berg kreisen. Sollten diese einst verschwunden sein, dann wird er wiederkehren an die Oberfläche und dem Land Ehre und Ruhm zurückbringen.

Eine schöne Geschichte, gerade für eine so lange gespaltene Nation wie Deutschland. Darum ist es nicht verwunderlich, dass mit der Neugründung des Deutschen Reiches unter Bismarck und Wilhelm I. die Nationalisten mächtig Aufwind bekamen und nach dem Tod des Kaisers ihm zu Ehren ein großes Denkmal errichteten. Das *Kaiser-Wilhelm-Nationaldenkmal auf dem Kyffhäuser* vereinigte in seiner Huldigung die beiden Kaiser, und so war nicht lange nach einem geeigneten Platz zu suchen: Da, wo Barbarossa auf seine Rückkehr wartet, auf den Ruinen der [Reichsburg Kyffhausen](http://de.wikipedia.org/wiki/Kyffhausen), soll die Stärke des wiedervereinigten Volkes symbolisiert werden. Architektonisch an die Burgen der Barbarossazeit angelehnt, war sogar eine Erweiterung zu einem deutschen Olympia geplant - doch diese Pläne des Architekten [Bruno Schmitz](http://de.wikipedia.org/wiki/Bruno_Schmitz) wurden niemals umgesetzt.

Ich war zuletzt zu DDR-Zeiten auf dem [Denkmal](http://kyffhaeuser-denkmal.de/web/de/home/home.asp) gewesen und fand, es sei an der Zeit, die Erinnerungen aufzufrischen. Also bin ich mit meiner Männertagsrunde von Berga-Kelbra aus losgezogen, um bei bestem Wanderwetter das Kyffhäuserhügelchen zu erklimmen. Nachdem wir bereits von der nicht betretbaren [Rothenburg](http://de.wikipedia.org/wiki/Rothenburg_(Thüringen)) enttäuscht wurden, mussten wir oben angekommen feststellen, dass auch das Nationaldenkmal eingezäunt wurde und nur gegen ein Eintrittsgeld von 6€ zu betreten ist.

Ein paar Streitereien mit den Personal wegen nicht anerkannter Studentenausweise später hatten wir unser Ziel endlich erreicht. Für unseren Obolus konnten wir nun neben dem Denkmal auch die ausgegrabenen Reste der Oberburg mit ihrem Bergfried und den mit 176m angeblich tiefsten Burgbrunnen der Welt besichtigen. Neben Letzteren gibt es ein weiteres, allerdings neuzeitliches Kuriosum: Einen Steinspender, der es erlaubt, Steine im Wert von 50 Cent zu kaufen. Diese dürfen dann durch ein kleines Loch in den Brunnen geworfen werden, woraufhin sich eine Stimme aus dem Brunnen genau darüber beschwert.

Viel interessanter ist dann doch das Denkmal selber, auch wenn ich einige Bilder des Besuches aus Kindheitstagen korrigieren musste. So war mir nicht mehr bewusst, dass die Reiterstatue von Kaiser Wilhelm die des Barbarossa dermaßen überragt. Und mit der erwähnten Sage im Kopf saß Barbarossa in meinem Gedächtnis immer an einem Tisch, um den sich der Bart wickelte - auch dies ein falsches Bild. Angenehm überrascht wurde ich dagegen davon, dass das Monument über 247 Stufen erstiegen werden und der wahnsinnig tolle Ausblick aus der Kaiserkrone, dem obersten Teil des Denkmalturms, über das gesamte - zugegeben kleine - Kyffhäusergebirge genossen werden kann.

Wer also ein Stück deutsche Geschichte hautnah erleben will, dem sei eine Wanderung zum Nationaldenkmal empfohlen. Fußfaule Menschen können auch bis fast zum Denkmalgelände mit dem Auto oder Motorrad fahren - letzteres haben zum Männertag viele Biker betrieben, doch auf den Wanderwegen kann die Straße weiträumig umgangen werden. Und wer mehr Zeit und Puste hat als ich und meine Wandergruppe, kann noch die [Barbarossahöhle](http://de.wikipedia.org/wiki/Barbarossahöhle) und die [Kaiserpfalz Tilleda](http://de.wikipedia.org/wiki/Pfalz_Tilleda) mit in die Strecke aufnehmen - und hat danach die erlaubte Maximaldosis Barbarossa für einen Tag erreicht.

[gallery link="file"]
