---
title: "Vorurteile"
date: "2009-05-03T21:19:23"
categories: [gedacht,gewesen,getan]
---

Dieses Wochenende war ich in Berlin und Umgebung an Orten unterwegs, die ich mit typischen Klischees und Vorurteilen verbinde; nicht alle habe ich jedoch bestätigt bekommen.

Es fing an mit dem Grillen am 1.Mai im [Tiergarten](http://www.stadtentwicklung.berlin.de/umwelt/stadtgruen/gruenanlagen/de/nutzungsmoeglichkeiten/grillen/de/hier.shtml), das ein Kollege zur Feier seines Abschlusses organisiert hatte. Ich habe vorher nicht geglaubt, wie viele Menschen auf so begrenzten Raum passen; teilweise war der Grillrauch so dicht, dass man kaum ein paar Meter schauen konnte. Und eine meiner Befürchtungen wurde bestätigt: 80% der Griller waren türkische Großfamilien - ich vermute, halb Wedding hielt sich dort auf - die teilweise ganze Wohungseinrichtungen in den Tiergarten geschleppt hatten. Doch alle verhielten sich sehr zivilisiert (im Gegensatz zu den Kreuzbergern) und so nervten nur die Touristen, die unsere Grillgruppe nahe der Straße des 17.Juni für so authentisch hielten, dass sie sie unentwegt fotografieren mussten. Jetzt bin ich also auf dutzenden Bildern von Menschen aus der ganzen Welt abgebildet, die mich für einen typischen Berliner halten...

Wenn es schon so weit ist, dachte ich, kann ich auch gleich noch zur [Werderaner Baumblüte](http://www.baumbluete.de) gehen. Dieses große Volksfest lebt von seinen Obstweinen und den davon schnell angetrunkenen Besuchern, die die Vorurteile gegenüber einem typischen Brandenburger nur zu gerne erfüllen. Doch am heutigen Schlusstag war davon nichts zu sehen. Das Fest neigte sich dem Ende zu, so dass einige Stände schon im Abbauen begriffen waren, und der angekündigte Regen hielt sicherlich auch einige potentielle Gäste vom Besuch ab. Wir konnten ganz entspannt über die Insel und das "Festland" von Werder schlendern und die Anreise von Potsdam aus per Ausflugsschiff über die Havelseen war dank eines gut gelaunten Kapitäns sehr unterhaltsam.

Wir hätten nur nicht auf die Idee kommen sollen, die feuchte Version des Autoscooter auf dem Wasser auszuprobieren. Denn niemand in meiner Begleitung hatte Wechselklamotten dabei, obwohl wir nach dem nur zehnminütigen Vergnügen alle bis auf die Unterwäsche durchnässt waren. So nahm das Fest für uns ein vorzeitiges Ende, da die Sonne schon weg war, das Feuerwerk aber noch drei Stunden entfernt. Also Memo an mich für nächstes Jahr: Eine zweite Hose kann nicht schaden!
