---
title: "Karten auf den Tisch"
date: "2009-01-13T22:12:40"
categories: [gedacht,getan,gespielt]
---

Seit ich die Zahlen auf den Spielkarten lesen kann, spiele ich. Zuerst war es Rommé mit der Familie, danach in der Schule Skat, welches mich in den Bann zog - noch vor den ersten Video- und Computerspielen. In meinem Freundeskreis kam dann irgendwann Doppelkopf dazu, das inzwischen sogar die Urlaube prägt. Ich war jetzt zwei Jahre in Folge mit einer doppelten Doppelkopf-Runde über den Jahreswechsel im Riesengebirge, und wir haben sogar unseren eigenen Pokal (den ich wohl nie erringen werde). Doch auf die Dauer ist nur DoKo zu eintönig, also haben wir dieses Mal ein paar andere Kartenspiele ausprobiert, die ich hier vorstellen möchte.

**Wizard**

Das Spielprinzip erinnert etwas an Skat/DoKo. Es gibt Karten im Wert von eins bis deizehn in vier Farben, dazu vier Zauberer (die höchsten Karten im Spiel) und vier Narren (die niedrigsten Karten im Spiel). Bis auf die Sonderkarten herrscht Bedienpflicht und je eine Farbe pro Runde wird zum Trumpf erklärt. Wer die höchste Karte in einem Stich legt, erringt diesen.

So weit, so langweilig. Jetzt gewinnt aber nicht der Spieler mit den meisten Stichen, sondern derjenige, der nur an Hand seiner Ausgangskarten am genauesten vorhersagen kann, wieviele Stiche er in der Runde macht. Diese Ansagen werden öffentlich gemacht und notiert und am Ende wird abgerechnet. Zudem variieren die Karten, die jeder Spieler pro Runde auf der Hand hält. Man fängt mit einer an und steigert sich, bis es keinen Restkartenstapel mehr gibt. Dann ist das Spiel zu Ende und der Spieler mit den meisten Punkten hat gewonnen.

Das spannende an dem Spiel ist das Abschätzen der Karten der Gegenspieler. Zu Beginn bei nur einer Karte ist es unwahrscheinlich, dass eine Nicht-Trumpf-Farbe den Stich erringt. Mit mehr Karten auf den Händen ändert sich dies jedoch, und irgendwann muss auch in Betracht gezogen werden, wieviele Zauberer sich wohl in der Runde befinden. Dabei ist es ein Vorteil, nicht als Erster seine Ansage tätigen zu müssen, da die Anzahl der erringbaren Stiche pro Runde feststeht und man so gewisse Aussagen über die anderen Blätter treffen kann.

Für mich als jemanden, der gerne alles vorher genau abschätzt, ist dieses Spiel genau das Richtige. Trotzdem ist es natürlich niemals absolut vorhersagbar, und so wird vor jedem Kartenabwurf spekuliert: Wem gehört der Stich bisher, wer kommt nach mir, und kann man jemandem irgendwie den einkalkulierten Stich wegnehmen oder noch besser - jemandem einen Stich zu viel reinbraten. Die Narren- und Zauberer-Karten erlauben dabei den nötigen Spielraum für unterschiedliche Strategien, und leichtes Feintuning der Regeln kann das Spiel noch einmal spannender gestalten. Eine klare Empfehlung meinerseits also.

**Munchkin**

Dieses Kartenspiel ist eigentlich eine Karikatur eines Pen-and-Paper-Rollenspiels. Jeder Spieler hat das Ziel, als Erster die Erfahrungsstufe Zehn zu erreichen, indem er Monster bekämpft und dafür an Erfahrung gewinnt. Reduziert wurde das übliche Spielprinzip auf zwei Kartenstapel: Die Türkarten, die in jeder Runde vom Spieler gezogen werden müssen und entweder Monster oder Flüche enthalten, und Schatzkarten, die man nach Besiegen eines Monsters erhält und auf denen sich Ausrüstungsgegenstände, Rassen-, Klassen- oder Aktionskarten befinden.

Leben tut das Spiel zum Einen von den witzigen Karten, die Rollenspiel-Klischees auf die Schippe nehmen (z.B. die +3-Trittleiter für Halblinge), und zum Anderen dem Prinzip, dass alle Spieler Einfluss auf den aktuell laufenden Kampf haben und entweder das Monster oder den kämpfenden Helden unterstützen können. Denn wenn man einem Monster unterliegt, hat das Konsequenzen bis hin zum Tod des eigenen Charakters (man verliert alle Ausrüstungsgegenstände). Die schlechtesten Eigenschaften der Mitspieler werden so direkt angesprochen und es kommt immer wieder vor, dass sich einfache Kämpfe zwischen Level-3-Helden und Level-2-Monstern auf unmögliche Höhen bis Level 30 steigern.

Das größte Manko von *Munchkin* sind leider die eigenen Regeln. Sie sind ungenau beschrieben und man findet nie sofort die für die eigene Situation gerade in Frage kommenden Hinweise und liest die vier Seiten deshalb wieder und wieder. Nicht umsonst steht in der Anleitung, dass im Zweifel der am lautesten Schreiende oder alternativ der Besitzer des Spiels entscheiden muss. Zudem sind die Karten auch schlecht ausbalanciert, so dass der Zufall mehr Einfluss auf den Ausgang hat als die eigene Strategie. Trotz der witzigen Idee kann *Munchkin* also nicht überzeugen.

**Bohnanza**

Eine Freundin, die Gartenbau studiert hat, brachte passenderweise dieses Spiel mit. Es geht um den Anbau von Bohnen(-karten) auf den zwei Feldern, die jeder Spieler besitzt. Auf jedem Feld kann man genau eine von acht unterschiedlich häufig auftretenden Sorten Bohnen anbauen; jede Runde bekommt man Karten dazu, die man entweder anlegen (bei gleicher Sorte) oder mit den anderen Spielern tauschen kann. Wird man eine Karte so nicht los, muss man eines der Felder opfern und die dort angebauten Bohnen verkaufen. Je nach Sorte und Anzahl der dort liegenden Karte gibt es unterschiedlich viele Geldstücke, am Ende gewinnt der reichste Spieler am Tisch.

Im Gegensatz zu *Wizard* kann man in *Bohnanza* kaum eine Runde vorhersagen; das A & O ist richtiges Tauschen mit den Mitspielern, um die Anzahl der Karten auf den eigenen Bohnenfeldern zu maximieren. Dazu kann man auch Gefälligkeiten verabreden und muss manchmal schlechte Tauschkurse der unterschiedlich wertigen Bohnensorten akzeptieren; das Spiel setzt also im Gegensatz zu *Munchkin* auf Kooperation.

Wir haben leider nur eine unterhaltsame Runde lang gespielt, so dass ich zur Langzeit-Motivation nichts sagen kann. Ebenso wie *Munchkin* kann *Bohnanza* aber noch um Zusatzkarten erweitert werden, die auch mehr Mitspieler erlauben. Für vier Personen reicht jedoch die Grundausstattung des Spiels, die von mir ebenfalls eine Empfehlung erhält.

Fazit: Abseits des klassischen Skat-Blattes sind in den letzten Jahren viele innovative und preiswerte Kartenspiele auf dem Markt erschienen, von denen einige mit Tiefgang und Spielspaß überzeugen können. Allen Interessierten empfehle ich, *Wizard* und *Bohnanza* einmal auszuprobieren; für jeweils sieben Euro ist man schon dabei!
