---
title: "Perfect Sense"
date: "2011-10-31T19:29:28"
categories: [gesehen]
---

*UK (2011)
Regie: David Mackenzie
Darsteller: Ewan McGregor (Michael), Eva Green (Susan), Connie Nielsen (Susans Schwester), Stephen Dillane (Samuel), Ewen Bremner (James) und andere Sinnlose*
[Offizielle Homepage](http://www.sigmafilms.com/films/perfect-sense/)

Susan ist eine Epidemiologin (gibt es das Wort im Deutschen?) an einer Forschungsanstalt in Glasgow. Als ein Truckfahrer eingeliefert wird, der nach spontanen Gefühlsausbrüchen plötzlich nichts mehr riechen kann, glaubt sie zuerst, nicht zuständig zu sein. Doch dann mehren sich überall auf der Welt ähnliche Fälle, und schon bald gibt es keinen Menschen mit Geruchssinn mehr.

Besonders betroffen von diesem Verlust ist Michael, der als Koch in einem Gourmetrestaurant arbeitet und dem nun die Gäste fernbleiben. Als er Susan kennenlernt und sich die beiden ineinander verlieben, tritt das globale Problem erst einmal in den Hintergrund bzw intensiviert ihre Gefühle füreinander. Doch dann rollt die zweite Welle der Pandemie über den Erdball, die einen Verlust des Geschmackssinnes nach sich zieht. Und langsam wird allen klar, dass dies noch nicht das Ende ist...

Eine seltsame Mischung setzt Regisseur David Mackenzie mit *Perfect Sense* dem Zuschauer vor. Auf der einen Seite zeichnet der Film ein interessantes Weltuntergangsszenario, so dass er durchaus in das Programm des [Fantasy Filmfest](http://www.fantasyfilmfest.com/filme/Perfect.html) passte. Doch gleichzeitig nimmt die Liebesgeschichte zwischen Michael und Susan den überwiegenden Teil der Handlung ein. Sie wird stark beeinflusst von den seltsamen Sinnesverlusten, doch nur selten wird der Blick über den Tellerrand der persönlichen Probleme gewagt und gezeigt, wie der Rest der Welt auf die Pandemie reagiert. Der Fokus liegt nicht beim Aufhalten der Apokalypse, sondern auf dem Umgang damit aus der Perspektive der jungen Liebe. 

Diese Verknüpfung der beiden Handlungselemente wird auch von der Erzählerstimme betont, welche die direkten Folgen auf den Menschen der in Etappen verloren gehenden Sinne beschreibt und am Ende zum Schluss kommt, dass die Liebe zwischen zwei Menschen dann am Stärksten ist, wenn sie nur auf direkten Berührungen basiert - dem *Perfect Sense*. Vermitteln kann der Film dies nicht mehr, da er für die Darstellung der Taub- und Blindheit die offensichtliche Umsetzung wählt und so am Ende das Medium seiner beiden an den Zuschauer vermittelten Sinne beraubt ist - bis dahin haben jedoch der emotionalisierende Soundtrack und die vielen Hochglanz-Liebesszenen den Sinnen genügend zu verarbeiten gegeben.

Besonders gefallen hat mir dabei die Dialogvisualisierung, die statt klassischem Schnitt-Gegenschnitt häufig beide Teilnehmer im selben Bild, aber in unterschiedlicher räumlicher Tiefe aufnahm und die Kamera selektiv den Sprechenden scharf stellt. Dies verlieh den Szenen gleichzeitig Ruhe und einen Fluss, der die Gefühle der beiden Hauptfiguren gut transportiert. Im Kontrast dazu stehen wild verwackelte Kamerafahrten vor Fahrrädern, die den Effekt wieder zunichte machen.

Stark ist der Film ebenfalls dann wenn er zeigt, wie die Menschen mit dem Fehlen der Sinne umgehen. Dies wird vor allem an dem Nobelrestaurant deutlich, in welchem Michael arbeitet. So wird nach dem Wegfall des Geruchssinnes zuerst der Geschmackssinn mittels stärkeren Einsatzes von Gewürzen stimuliert. Als dieser wegfällt, wird auf das Erfahren der Geräusche und des Fühlen des Essens in Mund und Speiseröhre gesetzt. Bis zum Schluss versuchen alle, das geregelte Leben irgendwie möglich aufrecht zu erhalten; eine überraschend optimistische Darstellung einer Epidemie.

Insgesamt wirkt der Film für meinen Geschmack aber zu glattgebügelt. War der Regisseur mit seinen vorherigen Werken *Young Adam* und  *Hallam Foe* noch für die schonungslose, aber genaue Darstellung des Unterschichten-Milieus bekannt, so ist er nun in die langweilige Welt der Yuppies mit ihren sanierten Fabrikhallenwohnungen gewechselt, wo jeder Raum wie vom Designer gestylt, aber auch austauschbar aussieht. Als schöner Mensch in schönen Interieurs zu leben schützt zwar nicht vor dem Verlust der Sinne, verhindert aber etwas das Mitfühlen mit den Figuren.

Fazit: So richtig warmwerden kann ich mit *Perfect Sense* nicht. Auf der einen Seite hat er ein interessantes Szenario und einige optische Ideen zu bieten, um es darzustellen. Auf der anderen Seite sorgen die Liebesgeschichte in Hochglanz und einige deplatzierte Effekte dafür, dass der Film zwischen den Genres hängen bleibt, weil die einzelnen Teile nicht zusammen passen wollen.
