---
title: "Wächter der Nacht"
date: "2008-03-24T17:12:46"
categories: [gelesen]
---

*von Sergej Lukianenko,
erschienen bei Heyne, ISBN 3-453-53080-2, 13€*

Eigentlich wollte ich nach der schlechten Erfahrung mit dem [Film](/blog/2005/11/08/wachter-der-nacht/) und dem [letzten Buch](/blog/2007/10/24/weltenganger/) von Lukianenko von der Saga um die Lichten und Dunklem in ihrem ewigen Kampf nichts mehr hören, geschweige denn lesen. Doch dann wurde mir so von dem Buch vorgeschwärmt, dass ich es schließlich bei einer Freundin ausgeliehen und nun auch gelesen habe.

Ein Argument, weshalb man nach dem Film besser noch die Vorlage lesen sollte, hat sich auf jeden Fall bewahrheitet: Die Kinoadaption behandelt nur das erste Drittel des Buches und weicht an vielen Stellen von diesem ab; der Dreh- und Angelpunkt des Romans ist ein anderer Charakter als auf der Leinwand. Um die eigentliche Geschichte zu verstehen, muss man also das Buch gelesen haben.

Darin geht es um die sogenannten *Anderen*: Menschen mit magischen Fähigkeiten wie Magier und Tiermenschen, Hexen und Vampire, Heiler und Gestaltwandler, die außerdem noch eine Zwischenwelt namens *Zwielicht* betreten können. Alle diese *Anderen* folgen entweder dem Licht oder dem Dunkel, je nachdem ob sie die Menschen als Kraftquelle brauchen oder nicht. Die Grenzen dazwischen sind fließend, doch beide Parteien überwachen sich nach einem jahrtausende-alten Vertrag gegenseitig, um ein Gleichgewicht der Kräfte zu erhalten.

In diese Ausgangssituation versetzt Lukianenko seinen Helden Anton, der zwar auf der hellen Seite für die Moskauer Nachtwache kämpft, aber im Laufe der Handlung nicht sicher ist, ob deren Mittel und Wege ohne jeden Tadel sind. Dies ist dann auch der rote Faden, der durch das gesamte Buch führt: Die Überlegungen des Ich-Erzählers zu Moral und Pragmatismus der *Anderen*, wobei er als Spielball der mächtigeren Zauberer immer erst zum Schluss erfährt, welche Rolle im großen Ränkespiel ihm zugeteilt wurde.

Auf die Dauer langweilen diese Monologe Antons etwas, weshalb sich die eingeschobenen Kapitel, in denen der Leser nicht dem Ich-Erzähler folgt, sondern einzelne Szenen aus den Augen von Nebencharakteren sieht, als angenehme Abwechslung hervortun. Dies fühlt sich dann immer komplett anders an als in der Sichtweise des Helden; ein paar mehr dieser Perspektivwechsel hätten dem Buch gut zu Gesicht gestanden.

Im letzten, dritten Teil des Romans fehlt es dann zunehmend an Spannung; die beschriebene Schwüle des Moskauer Sommers legt sich auch auf die Geschichte, die deutlich gegenüber den vorherigen Kapiteln abfällt. Gerade wenn man denkt, jetzt kommt der große Knall mit der Auflösung, widmet sich Lukianenko lieber wieder ausgiebig den Gedankenspielen von Anton anstatt die Handlung voranzutreiben - dabei hatte der Leser inzwischen genügend Zeit zu lernen, den Annahmen des Helden nicht mehr zu vertrauen, da sich diese immer als falsch herausstellten. Im Gegenzug wird das eigentliche Finale auf fünf Seiten abgefrühstückt und lässt den Leser trotz des stringenten Endes etwas überrumpelt zurück.

Der ganz große Wurf ist *Wächter der Nacht* trotz des Erfolges im Heimatland also nicht, und eine große Zukunft ist der Wächter-Serie aus meiner Sicht auch nicht beschieden, denn der Roman ist wie die [anderen](/blog/2007/10/24/weltenganger/) [Werke](/blog/2007/06/24/spektrum/) Lukianenkos zu sehr ein Kind seiner Zeit. Viele Details (z.B. der [MD-Player](/blog/2008/03/12/sackgasse-der-evolution/) des Helden) werden schon in ein paar Jahren nur wenigen Lesern etwas sagen, während die Beschreibung des heutigen Moskau und seiner Bewohner zumindest einen dauerhaften Charme besitzt.

Fazit: Wenig Handlung aber viel Pseudo-Kopfkino bestimmt den ersten Teils dieser russischen Fantasy-Reihe, die dem Genre ein paar neue Ideen verschafft, aber wie bei Lukianenko so üblich hauptsächlich aus popkultureller Spielerei mit bekannten Versatzstücken besteht. Auch die Russen wollen eben unterhalten werden...
