---
title: "Linux ausgesperrt"
date: "2010-03-29T23:30:48"
categories: [gedacht,gefunden]
---

So ganz sicher bin ich mir noch nicht, ob dies nicht ein vorweggenommener schlechter Aprilscherz ist. Doch überall im Netz wird davon berichtet, dass Sony mit dem nächsten Systemupdate 3.21 für die Playstation 3 [die Unterstützung für die Installation alternativer Betriebssysteme entfernen will](http://blog.us.playstation.com/2010/03/28/ps3-firmware-v3-21-update/). Bisher konnte man ein [Linux](/blog/2008/09/21/kubuntu-runs-my-playstation/) parallel zu der Sony-Oberfläche installieren, was oft als wichtigster Grund gewertet wird, dass sich die Hacker nicht auf die PS3 gestürzt haben und bis heute ihr Kopierschutz im Gegensatz zur XBox und Wii nicht geknackt ist.

Zieht Sony die Ankündigung durch, könnte dieses Alleinstellungsmerkmal schnell fallen. Für mich wird sich erst einmal nicht viel ändern; bisher habe ich aufgrund der schwachen Systemleistung mein PS3-Ubuntu nur zum Ziehen von Blu-Ray-Sicherheitskopien verwendet und etwas mit der [Videokodierung](/blog/2009/07/19/videocodierung-mit-der-ps3/) herumexperimentiert. Andererseits war die Installationsmöglichkeit eines Linux durchaus ein Grund, mir die Playstation zuzulegen und nicht die XBox von Microsoft. Und die Firma hinter Yellow Dog Linux und dem CodecSys-Videoencoder, Fixstars, hat ein ganzes Geschäftsmodell auf der Linux-Fähigkeit der Playstation aufgebaut. Die Akzeptanz dieser Maßnahme ist also fraglich.

Für mich ist es auf jeden Fall ein falsches Zeichen. Vor allem, da den seit letzten September verkauften PS3-Slim-Varianten diese Fähigkeit ohnehin fehlt. Warum also die Besitzer der alten Modelle gängeln? Denn leider ist das Update Voraussetzung für die weitere Nutzung des PSN-Networks und den Download von Spiele-Updates. So bleibt [wieder](/blog/2008/10/19/der-glaserne-konsolenbesitzer/) der üble Beigeschmack, dass Sony sich mehr Rechte heraus nimmt, als für den Betrieb der Konsole eigentlich nötig sind. Mir stellt sich zudem die Frage, ob die Japaner nach deutschem Gesetz überhaupt die Nutzung der erworbenen Hardware nach dem Kauf einschränken dürfen.

So oder so ist die Berichterstattung durchgängig negativ, wenn auch auf nicht sehr publicity-wirksamen Kanälen. Sony scheint entweder Angst vor einem PS3-Hack zu haben, wobei diese Aktion die Hacker erst anstacheln dürfte, oder zu viel Oberwasser durch die aktuellen Verkaufserfolge und die Berichterstattung um [Move](http://blog.eu.playstation.com/2010/03/10/introducing-playstation-move/), dass der Konzern dies in Kauf nimmt. Ich bin gespannt, ob die Rechnung aufgeht.
