---
title: "Wall-E"
date: "2008-09-28T19:10:02"
categories: [gesehen]
---

*USA (2008)
Regie: Andrew Stanton
Synchronstimmen: Wall-E (Timmo Niesner), Eve (Luise Helm), Kommandant (Markus Maria Profitlich) und einige andere Roboter*
[Offizielle Homepage](http://www.walle-derfilm.de/)

[Nummer Fünf lebt](http://de.wikipedia.org/wiki/Nummer_5_lebt!)! Das jedenfalls war mein Eindruck, als ich vor einem Jahr den ersten Trailer zu *Wall-E* sah. Die Raupen, die Augen, die Greifarme, die gesamte Maschine erinnert an den Roboter aus den 80ern. Ein Grund mehr, [nach fünf Jahren](/blog/2003/11/27/findet-nemo/) endlich wieder einen Pixarfilm im Kino anzusehen.

Der titelgebende Roboter ist der letzte einer großen Serie, die nach der Totalverschmutzung der Erde und der Flucht der Menschheit ins All zurückgelassen wurde, um den Planeten aufzuräumen. Dies bedeutet für Wall-E, dass er seit 700 Jahren Tag für Tag den hinterlassenen Müll zu kleinen Würfeln komprimiert und danach zu riesigen Pyramiden aufstapelt. Dabei hat die kleine Maschine Neugierde und Individualismus entwickelt; sie sammelt Hinterlassenschaften der Menschen und hat eine Schabe als Freund. Eines Tages landet ein Raumschiff auf der Erde und setzt einen Roboter aus, der beginnt die Gegend zu erkunden. Wall-E versucht, in Imitation eines alten Musikfilms eine Beziehung zu dem anderen Roboter mit Namen Eve aufzubauen. Doch dann entdeckt Eve eine Pflanze, die als Zeichen für die Regeneration der Erde gewertet wird, und das Raumschiff kehrt zur Abholung zurück. Wall-E schafft es, sich an das Schiff zu hängen und gelangt so auf die Axiom, einem riesigen Frachter, in dessen Inneren die Menschheit die letzten 700 Jahre verbracht und auf die Rückkehr auf den Heimatplaneten gewartet hat...

So unglaublich es scheint, aber Pixar hat mit *Wall-E* einen Trickfilm erschaffen, der bis zur Hälfte der Spieldauer komplett auf Sprache verzichtet und trotzdem glänzend unterhält. Bis dahin ist außer auf Videoaufnahmen kein Mensch zu sehen und dementsprechend realistisch ist die Wahrnehmung dieser von Pixar gerenderten posthumanen Erde. Dieser Eindruck wird auch durch den exzessiver Einsatz von [flacher Schärfe](http://www.filmtutorial.de/06-bildgestaltung/2.htm) verstärkt. Die Animationstechnik ist also mittlerweile so weit ausgereift, dass zu Mitteln des Realfilms gegriffen wird, um die Illusion weiter zu verbessern.

Mit Auftauchen der ersten geflüchteten Menschen wird jedoch dieser Eindruck wieder zerstört. Diese wabbeligen Figuren ohne jegliche Hautstruktur sind zwar bewusst zeichentrickhaft gehalten (schön zu sehen an den Portraits der Kapitäne und den Videoübertragungen, dass da deutlich mehr Realismus möglich ist), aber das Fortschreiten der Handlung im Inneren des Raumschiffs Axiom bedeutet einen optischen Bruch im Film - fortan wird auch wieder durchgängig Tiefenschärfe eingesetzt.

Dies ist jedoch das einzige Negative, dass man über *Wall-E* schreiben kann, denn ansonsten ist er perfekte Familienunterhaltung. Es gibt slapstickhaften Humor für die kleinen Zuschauer und viele Seitenhiebe für die Erwachsenen, die den Kindern verborgen bleiben. Umweltschutz ist natürlich ein großes Thema, denn der Film nutzt seine Darstellung einer zukünftigen Erde, um zu mahnen: Sorgt Euch um Euren Planeten, unterstützt ihn bei seiner Selbstheilung, verlasst Euch nicht blind auf die Technik (die Degenerierung der Menschen wird sehr witzig dargestellt) und vor allem gebt den Planeten niemals in die Hände der Wirtschaft; diese hat kein Interesse an dessen Erhaltung. Daneben gibt es Anspielungen auf 2001 (wenn der Kapitän sich erstmals auf seinen eigenen Beinen aufrichtet und Strauss eingespielt wird) und Kritik an der Videofunktion des iPod - ein kleiner Seitenhieb auf CEO Steve Jobs.

Bewunderung verdient, wie viel Ausdruck Pixar aus den Robotern herausgeholt hat - schließlich gibt es keine Synchronisation, die dabei unterstützen könnte. Während bei Eve viel über die Darstellung der Augen erreicht wird (klassisch im Zeichentrick), der Körper aber ansonsten in seiner Form bleibt, hat man sich bei Wall-E so richtig ausgetobt. Allein die Details der Greifarme und der Augen sind beeindruckend, aber in wievielen Variationen Arme, Raupen, Kopf und der würfelartige Körper kombiniert werden können und dabei gleichzeitig eine Stimmung erzeugen - das ist einfach große Animierkunst.

Fazit: Ein witziger und moralischer Film ist *Wall-E* geworden, vollgestopft mit vielen Details die alle Altersgruppen ansprechen. Versteckt unter der Oberfläche der Roboter-Liebesgeschichte gibt es viel Kritik an unserer Gesellschaft zu entdecken und technisch ist Pixar weiterhin das Maß der Dinge. Anschaupflicht also!

(Einen lustigen [Vorfilm](http://www.vkmag.com/videos/videos_pixars_presto) gibt es natürlich auch wieder!)
