---
title: "Dragon Age: Origins – Das Tagebuch, Teil 3"
date: "2009-12-23T01:33:25"
categories: [gespielt]
---

Gerade fing DAO an, so richtig Spaß zu machen. Ich hatte eine halbwegs gut ausbalancierte Party zusammengestellt bestehend aus einem Angriffszauberer, einem Heilzauberer, einem Fernkampfschurken und meinem Kriegerzwerg als Tank für die erste Reihe. Mit Fernzaubern konnte ich die meisten Kämpfe schon vor ihrem Beginn deutlich vereinfachen und der Schurke sorgt mit seinem Bardengesang für mehr Durchschlagkraft im Angriff und kann zudem Bomben werfen. Nur wenige Gegner bereiten so noch Probleme.

Doch dummerweise muss ich in den Tiefen Wegen von Orzammer eine Mission mit einem Zwergen-NPC absolvieren, der nur als (schwacher) Tank eingesetzt werden kann. Das bringt die sorgsam ausbalancierte Party vollkommen durcheinander, denn ich habe für den Zwerg auf meinen Schurken verzichtet, der mit seinen genannten Eigenschaften nun an allen Enden und Ecken fehlt. Jetzt stehe ich vor einem Haufen von Golems und werde trotz aller Rüstung ordentlich verprügelt und meine Magier entfalten bei den steinernen Gegnern kaum eine Wirkung. Ein Wechseln der Party innerhalb eines Levels klappt natürlich auch nicht - DAO ist bei Fehlern gnadenlos.

Spätestens jetzt ist klar, dass Krieger die eindeutig falsche Klassenentscheidung war. Mit Alistar und jetzt Oghren stehen einem als Pflichtcharaktere eigentlich immer Tanks zur Seite, und bereits sehr zeitig im Spiel ist die Auswahl auf dieser Position groß. Da muss man diesen Platz nicht noch selber einnehmen. Zudem habe ich meinen Krieger auf den Kampf mit zwei Waffen geskillt, was neben den Krieger-Attributen Stärke und Konstitution auch Geschicklichkeit erfordert, die wiederum jeder Schurke dringend benötigt. Dies wäre also die richtige Wahl zu Beginn gewesen. Doch während in anderen Spielen die Balance zwischen den Klassen stimmt, haut einem DAO die falsche Entscheidung immer wieder um die Ohren und führt so zu Frustmomenten...
