---
title: "Futurama - Leela und die Enzyklopoden"
date: "2009-04-20T19:52:33"
categories: [gesehen]
---

Zum Abschluss der vier Direct-to-DVD-Veröffentlichungen ist es den Machern um Matt Groening wie schon in [Bender's Big Score](/blog/2008/04/10/futurama-benders-big-score/) wieder gelungen, einen durchgängig guten Film zu produzieren. Ganz ohne ablenkende Nebenplots kann die Story überzeugen, und in anderthalb Stunden gibt es diesmal keinen einzigen Hänger.

Hauptthema in *Leela und die Enzyklopoden* ist die Zerstörung der Natur. Nachdem Amy Wongs Vater den Mars zu einem Spielkasino umgestaltet hat und dabei den halben Planeten planierte, geht er das nächste große Projekt an: Einen Riesen-Minigolf-Kurs durch die Milchstraße, bei dem auch das eine oder andere Sonnensystem weichen muss. Während Leela und Amy sich Öko-Feministinnen anschließen und die Bauarbeiten sabotieren wollen, lässt der Professor sich von Wong dafür schmieren, ökologische Unbedenklichkeitserklärungen zu unterschreiben. Fry dagegen kann plötzlich die Gedanken anderer Menschen lesen und gerät in eine Geheimorganisation von Gedankenlesern, die ihm erklären, dass er (mal wieder) die Rettung des Universums ist, weil niemand in der Lage ist, seine Gedanken zu lesen...

So ein wenig hat man die Thematik Umweltschutz schon im [dritten Film](/blog/2009/01/31/futurama-benders-game/) angeschnitten, als es um nicht erneuerbare Energieresourcen ging. Nun gibt es die komplette Breitseite: Von der Entstehung und dem Aussterben der Arten über deren Lebensräume und Evolution bis hin zum Umgang der Menschheit mit der Natur werden viele Fragen gestellt, nicht beantwortet, aber zumindest mit verschiedenen Argumenten gefüttert und so beleuchtet. Dabei kommt es zu so ironischen Szenen wie einer Leela, die den auf den Mars gefundenen Wurm abwechselnd töten will, weil er als Parasit von ihrem Blut lebt, und dann wieder retten will, weil er das letzte Exemplar einer aussterbenden Rasse ist. Dass Umweltschutz kein leichtes Thema ist und Entscheidungen immer abgewogen werden müssen wird so quasi im Vorbeigehen vermittelt.

Am Ende des Films kommt es schließlich zu einem Showdown. Für das Ende der Serie selber als auch für zwei Ur-Rassen: den Dunklen als Feind allen Lebens und den Enzyklopoden als deren Hüter, die sich seit Ewigkeiten gegenseitig zu übertrumpfen und zu verdrängen versuchen und nun beide vom Menschen bedroht werden. Dieser nimmt quasi den Gegenpol zu Gott als Schöpfer ein und erhebt sich über ihn, indem er dessen Werk vollendet durch die Auslöschung von Pflanzen- und Tierarten.

Neben diesem Hauptthema hält sich der Film an den gewohnten Sci-Fi-Anspielungen merklich zurück (mit der Ausnahme, dass Zapp Brannigan Picards *Make it so* sagen darf). Dafür schafft es Futurama inzwischen problemlos, in eigenen Anspielungen zu schwelgen. Der Anführer des Gedankenleser-Geheimbundes mit der großen [Neun](http://futurama.wikia.com/wiki/Nine) auf dem Hemd ist nicht etwa eine Referenz auf den Oscar-prämierten Kurzfilm 9, sondern ein nie ausgebauter Hintergrundcharakter der Serie und dass Amy ein dickes Kind war, wurde auch schon einmal gezeigt. Es ist also noch genügend Raum im Futurama-Kosmos, um Geschichten über das offene Ende hinaus zu erzählen. Ich hoffe auf [weiteres Material](/blog/2009/02/26/death-sells-oder-doch-nicht/), ob nun als Serie oder auf DVD.

Zu guter Letzt will ich noch auf die Extras der DVD eingehen: Neben den obligatorischen entfallenden Szenen gibt es erneut Anleitungen für das Zeichnen von Futurama-Charakteren, ein Interview mit dem Gaststar Penn Jillette (nie gehört), eine selbstironische Präsentation des Produktionsablaufs der DVDs, eine kurze Dokumentation über den Ausflug von Matt Groening und David X. Cohen in die Schwerelosigkeit und schließlich zwei scherzhafte Anleitungen: Bender erklärt korrektes Verhalten im Kino und Zapp Brannigan erläutert zehn Schritte für ein erfolgreiches Date. Ingesamt präsentiert sich der vorerst letzte Futurama-Film also als überzeugendes Gesamtpaket, nicht für Fans der Serie.
