---
title: "Coraline"
date: "2009-09-13T23:40:28"
categories: [gesehen]
---

*USA (2009)
Regie: Henry Selick
Sprecher: Dakota Fanning / Luisa Wietzorek (Coraline Jones), Teri Hatcher / Bettina Weiß (Mutter Jones), Robert Bailey Jr. / Hannes Maurer (Wyborne "Wybie" Lovat), Keith David / Reiner Schöne (Katze), John Hodgman / Patrick Winczewski (Vater Jones) und andere "andere" Bewohner des Pink Palace*
[Offizielle Homepage](http://www.coraline-film.de/)

Coraline ist ein kleines Mädchen, das mit ihren Eltern in das Mietshaus *Pink Palace* außerhalb der Stadt zieht. Die mit ihren Jobs als Autoren von Gartenkatalogen ausgelasteten Eltern haben kaum Zeit, sich um die Tochter zu kümmern, und so geht diese auf Entdeckungsreise in und um die neue Wohnung. Sie lernt den Nachbarsjungen Wybie mit seiner Katze kennen, die verschrobenen ehemaligen Varietéstars April Spink und Miriam Forcible in deren Kellerwohnung mit ausgestopften Hunden an der Wand und den Springmauszirkusdirektor Bobinsky, der sich jedoch weigert, ihr eine Sondervorstellung zu geben.

Weiterhin entdeckt sie eine kleine verschlossene Tür, von der niemand weiß, was sich dahinter befindet. Eines Nachts findet die unstetige Coraline diese Tür jedoch geöffnet und entdeckt ein Haus, dass dem Ihren zum Verwechseln ähnlich sieht. Nur das dort alles so viel besser ist: Die "anderen" Eltern sind liebevoll, haben Zeit für das Mädchen und verwöhnen es. Wybie nervt nicht, da er keinen Mund zum Quassel hat, April Spink und Miriam Forcible präsentieren ein unglaubliches Showprogramm in einem riesigen Theater voller Hunde und auch der Springmauszirkus hat endlich geöffnet.

Coraline ist so begeistert von dieser anderen, parallelen Welt, das sie am Liebsten gar nicht zurück möchte. Doch dann präsentiert ihr die andere Mutter den Preis für diesen schönen Traum: Sie soll ihre Augen gegen ein paar Knöpfe eintauschen und kann dann für immer bleiben...

Ich mag Stop-Motion-Animationen über alles. Ob dies nun [Filme des Aardman-Studios](/blog/2005/10/31/wallace-gromit-auf-der-jagd-nach-dem-riesenkaninchen/), von [Tim Burton](/blog/2005/11/13/corpse-bride-hochzeit-mit-einer-leiche/) oder eben Henry Selick (*Nightmare before Christmas*) sind; ich lasse mich zu gern von dieser schwierigsten aller Animationsformen ins Kino locken. Nirgendwo sonst bekommt man einen so direkten Eindruck von der Arbeit der Animateure, die neben der üblichen Arbeit im Realfilm, der Bildmontage, auch noch die Puppen oder Knetfiguren zum Leben erwecken müssen. Ein weiterer Grund für meine Vorfreude auf Coraline war der erste Besuch eines 3D-Films im Kino. Was würde die neue Technik bieten; wird sie das Filmerlebnis noch weiter steigern oder handelt es sich nur um eine Spielerei?

Leider bin ich mir auch nach Coraline noch unsicher. Viel stärker als die vorsichtig eingesetzten 3D-Effekte haben mich die zweidimensionalen Bilder fasziniert, die Selick teilweise im Computer hat entstehen lassen, deren Integration jedoch als perfekt anzusehen ist. Wenn sich die von der anderen Mutter erschaffene Welt wie ein riesiges Puzzle auflöst und Coraline schließlich in einem strudelförmigen Spinnennetz nach oben klettert, dann sind dies sehr einprägsame Bilder, die die Stop-Motion-Animation allein kaum hätte erschaffen können.

Ebenso beeindruckend sind die Lichteffekte, die vor allem im Garten der anderen Mutter überraschen. Arbeiten andere Animationen technikbedingt oft mit wenigen Lichtquellen und stark kontrastierenden Schatten, so leuchtet *Coraline* in einem regenbogenfarbigen Lichterreigen, der ähnlich wie bei der [Corpse Bride](/blog/2005/11/13/corpse-bride-hochzeit-mit-einer-leiche/) im krassen Gegensatz zur eher grauen Realität steht (trotz des Namens *Pink Palace*). Optisch ist Coraline also sehr beeindruckend; auch die Charaktere und ihre Bewegungen sind wunderbar gelungen.

Die Vorlage für die Geschichte stammt aus der Feder von Neil Gaiman und behandelt das Thema des Erwachsenwerdens, des Zurücklassens der kindlichen Vorstellungen und des Entwickelns von Verantwortung. Dargestellt in der kleinen Welt rund um das Mietshaus ist die "andere" Welt, die Kopie dieses abgeschlossenen Raumes, die Verbildlichung der Schritte Wunsch und Realisation auf dem Weg zur Adoleszenz, wenn Coraline erstmals begreift, dass man ihr nicht lebtags alles schenken wird.

Fazit: *Coraline* ist eine wunderbare Animation über die Adoleszenz eines Mädchens, die mit ihrer Mischung aus Stop-Motion und dezent eingesetzten Computereffekten plus einigen 3D-Shots zu überzeugen weiß.
