---
title: "Dies ist nur ein Beitrag über Zensur"
date: "2009-04-19T10:03:22"
categories: [gedacht,gefunden]
---

[Wie bereits beschrieben](/blog/2009/02/20/wer-nicht-horen-will/), bin ich seit Februar Kunde bei Kabel Deutschland. Damit sind nicht nur [meine Kundendaten frei im Netz verfügbar](http://www.heise.de/ct/Zeitung-Datenskandal-bei-Kabel-Deutschland--/news/meldung/135426), sondern ich komme demnächst auch in den Genuss der [Internetsperren gegen Kinderpornographie](http://www.heise.de/newsticker/Fuenf-Provider-unterzeichnen-Vertrag-zu-Kinderporno-Sperren--/meldung/136327). Was erst einmal kein Problem ist, da ich solcherart Seiten nicht ansurfe.

Doch wenn man dann die [Berichterstattung](http://www.heise.de/ct/Die-Argumente-fuer-Kinderporno-Sperren-laufen-ins-Leere--/artikel/135867) liest, kommen langsam Zweifel auf, ob hier nicht etwas grundlegend schief läuft. Es fängt damit an, dass die Verträge mit den fünf großen Internetzugangsprovidern geheim sind, d.h. niemand außer den Vertragspartnern weiß, wie die Sperren umgesetzt werden. Nun haben ein paar Beteiligte Aussagen getroffen, die darauf hindeuten, dass das leicht zu umgehende Verfahren der DNS-Sperren eingesetzt wird. D.h. wir haben nun ein [nicht wirksames System](http://www.sueddeutsche.de/panorama/813/465404/text/19/), das Betroffene nicht aufhält, die eigentlichen Straftäter nicht belangt und die Frage stellen lässt: Warum haben wir es dann? Darauf werde ich am Ende zurückkommen.

Was mich persönlich am meisten schockiert ist die Tatsache, dass in diesem Fall sämtliche demokratische Gremien und die komplette Gewaltentrennung umgangen wurden. Kein vom Wähler legitimiertes Parlament hat über die Sperren abgestimmt, kein Gericht hat darüber entschieden oder ist gar in den Prozess eingebunden - es gibt keinerlei demokratische Kontrolle. Frau von der Leyen (vom CCC ironisch nur noch Zensursula genannt) mit ihrem Familienministerium hat sich vor den Karren des BKA spannen lassen und nun haben wir eine Polizeibehörde, die ohne jede gesetzliche Grundlage (mit sehr hoher Wahrscheinlichkeit wird sogar das Grundgesetz verletzt) und vollkommen intransparent Seiten im Internet sperren lassen kann. Welche Seiten gesperrt werden, bleibt natürlich ebenso geheim, und ein Richter schaut vorher auch nicht darüber. Zumindest will das BKA für fälschlicherweise gesperrte Seiten haften. Doch in welcher Form und wer dies in Anspruch nehmen kann, ist unklar - es gibt ja schließlich keine gesetzliche Grundlage und die Verträge sind unter Verschluss.

Damit bleibt zum Schluss noch die Frage, wozu das Ganze. Ebenso wie bei der Vorratsdatenspeicherung, der Videoüberwachung oder der Diskussion über härtere Schusswaffengesetze steht das Wort präventiv groß im Raum: Es soll verhindert werden, dass Bürger zu Tätern werden, indem man den Weg dorthin erschwert. Doch neben der geringen Effektivität der Maßnahmen bleiben leider Grundrechte aller Bürger auf der Strecke; der Trend geht ganz klar zu einem bevormundenden und überwachenden Staat (da haben die Deutschen ja viel Erfahrung gesammelt in den letzten 80 Jahren). Ein Ausgleich der Interessen findet quasi nicht mehr statt, und wenn eine Mehrheit im Parlament für die neuste Maßnahme nicht absehbar ist, dann greift man eben zu undemokratischen Mitteln wie Ministerentscheiden auf EU-Ebene oder privatwirtschaftlichen Verträgen wie in diesem Fall.

Deshalb [Wehret den Anfängen](http://www.lateinservice.de/anthologia/2001/prosestio.htm), damit nicht demnächst ein Innenministerium für jeden Bürger entscheidet, welche Internetseite gut und welche böse ist, sondern weiterhin die gesamte Gesellschaft.
