---
title: "Vorhang auf"
date: "2010-02-11T23:56:16"
categories: [gesehen]
---

Einen runden Geburtstag feiert die Berlinale dieses Jahr, und doch fühlt es sich an wie all die letzten Jahre; von Jubiläum keine Spur. Der Winter hat Berlin fest im Griff und Festivaldirektor Dieter Kosslick hat erneut eine amateurhaft wirkende Eröffnungsfeier inszeniert. Ihm zur Seite stand diesmal Anke Engelke, die bravourös in die Fußstapfen ihrer Vorgängerinnen (inklusive ihrer eigenen) stieg und mit schlechten Kalauern und einer seltsamen Intonierung ihres Englisch irritierte.

Die von mir abonnierte Filmzeitschrift [Ray](http://www.ray-magazin.at/) schreibt dazu passend in ihrer aktuellen Ausgabe über die Berlinale:

> Sie ist das forderndste, ja unliebsamste Festival, weil ihrer Auswahl nicht zu trauen ist. Es gibt dort so viele Kuratoren, dass man sein eigener Kurator werden muss, das Sehenswerte suchen um den Preis oft schmerzhafter Fehlgriffe. Ja, ein paar Lieblingsfilme bleiben schließlich übrig als trotzige Eroberungen. Man gibt sie nicht mehr aus der Hand, weil man so schwer daran gekommen ist. Doch wenn man sie in eine Liste setzt, dann ergeben sie eher ein Bild von uns selbst als das eines großen Festivals.

Und das trifft es ziemlich gut. Die Berlinale will gar nicht die Speerspitze der Hochkultur sein, kein Arthouse oder andere Nischen besetzen, sondern spricht die Allgemeinheit an. Auf keinem anderen Festival gehen mehr Besucher in die Kinos, laufen mehr Filme. Da gibt es keine Elite, keinen Mainstream, sondern eine unglaubliche Anzahl schwer einzuordnender Filme, von denen am Ende alle ihre Besucher finden.

Und das macht die Berlinale gleichzeitig so anziehend und ärgerlich; eine Hassliebe eben wie so vieles in Berlin. Dazu gehört die Eröffnungsgala ebenso wie mein heutiges zwanzigminütiges Anstehen im [Kino International](http://www.flickr.com/photos/tmesis/976086380/sizes/l/) - zum Glück war die Schlange kurz. Der sozialistische Charakter des Ticketsverkauf - für jeden nur maximal zwei Tickets pro Film und die Verkäufe starten immer erst drei Tage vorher - passt da genauso ins Schema.

Für mich ist jedoch das größte Problem, die Qual der Wahl zu haben unter so vielen Filmen, die oft noch nicht in Deutschland aufgeführt wurden und wahrscheinlich genauso oft den Weg in den Verleih nicht finden werden. Außerhalb des Berlinale-Journals finden sich kaum nennenswerte Informationen, so dass jeder Kinobesuch auf der Berlinale aufs Neue ein Experiment ist; immer auf dem schmalen Grat zwischen eigenem Geschmack und dessen Wiedererkennung in den Beschreibungen. Mein Balanceakt startet dieses Jahr am Sonntag mit [David wants to fly](http://www.berlinale.de/de/programm/berlinale_programm/datenblatt.php?film_id=20103917). Ich bin gespannt und werde berichten.
