---
title: "The Handmaid's Tale - Staffel 4"
date: "2022-09-18T09:04:00"
categories: [gesehen]
---

Nun hat also auch The Handmaid's Tale ihren Breaking-Bad-Moment - den Kipppunkt, an dem der Charakter sich für den Zuschauer wandelt vom Sympathieträger, mit dem man mitfühlt, hin zu einem Racheengel, dessen Handlungen man zwar ablehnt, aber dennoch fasziniert folgt.

Leider ist der Weg dahin nicht immer nachvollziehbar. Ich mochte zwar, wie June sich nach und nach im klassischen Try & Error zur Führungskraft entwickelt, aber die Story schlägt doch einige Volten und am Ende ist es einfach nur noch lächerlich, wie oft wichtige Entscheidungsträger aus Gilead die Grenze zu Kanada überschreiten.

Zudem hat die Serie es am Ende geschafft, alle Farben so weit zu entsättigen, dass sie fast bei schwarz-weiß angekommen ist und selbst die weiter häufig eingesetzten Blau- und Rottöne kaum noch zu identifizieren sind. Das ist optisch einfach nur eintönig, und durch die häufigen Gegenlichtsituationen verschwimmt das Bild zudem in grauem oder schwarzen Matsch.

Schade, meine Lust auf Junes Geschichte hat diese Staffel ordentlich abgewürgt.