---
title: "Minimalismus und Details"
date: "2009-04-20T21:45:47"
categories: [gespielt]
---

Dies sind die beiden Extreme, zwischen denen das Tennisspiel *Top Spin 3* auf der Playstation 3 pendelt. Auf der einen Seite kann man nur bewundern, mit wie viel Liebe zum Detail viele Elemente des Spiels designt sind. Da sind die Aufschlag-Animation der nachgebildeten Tennisstars, die man sofort wiedererkennt, realistisch fallende und beleuchtete Hemden und die sehr detailliert nachgestalteten Original-Tennis-Courts (Wimbledon fehlt leider als einziges Grand-Slam-Turnier). In keinem anderen Spiel wurde der Tenniszirkus bisher so realistisch umgesetzt.

Doch gleichzeitig zeichnet das Spiel ein fast schon überheblicher Minimalismus aus. Abseits der Turniere hat *Top Spin 3* nichts zu bieten; selbst diese wirken nüchtern. Der Spieler freut sich nach einem Sieg, und schon landet man auf einem Bildschirm mit dem Text "Du hast gewonnen". Keine Überreichung von Trophäen, kein Siegerfoto belohnt den Spieler, nur in der langweiligen Präsentation angezeigte Punkte für die Entwicklung der Fertigkeiten und zum Einkaufen sind der Lohn. Für das Wechseln der Klamotten und Accessoires muss man zudem den Karrieremodus verlassen, nur um in einer ebenso langweiligen Auswahlliste zu landen. In früheren Teilen der Serie konnte man die Turniere, Shops und Trainingsstätten noch auf einer Weltkugel aussuchen.

Neben diesem Minimalismus nerven auch andere Details. So ist der Schwierigkeitsgrad während einer Partie nicht einstellbar, der aktuelle Spielstand wird immer nur zwischen den Ballwechseln angezeigt und trotz des vielen Platzes auf dem Bildschirm (in 720p) werden alle Spielernamen nur als Dreierkürzel dargestellt. Daneben gibt es abschreckend lange Ladezeiten für den Court vor jedem Match, währenddessen das Bild immer wieder einfriert. Eine gute Präsentation sieht anders aus. Zumindest kann man endlich wählen, dass die Kamera hinter dem Spieler bleibt. Am oberen Bildschirmrand zu spielen ist einfach nur nervig; damit ist das größte Manko der Serie behoben.

An die neue Steuerung gewöhnt man sich nach einer Weile, das Ziel eines realistischeren Spiels wird damit jedoch nicht erreicht. Richtiges Positionieren zum Ball und variables Spiel mit der Schlaglänge sind erste Pflicht. Es ist erstaunlich schwer, die Rückhand zu umlaufen, und da man sich sehr zeitig für einen Schlag entscheiden muss, geht dem Spiel etwas die Spritzigkeit ab. Will man wirklich erfolgreich sein, muss man zudem alle Tasten erlernen - und dies bedeutet wirklich alle Tasten, von R1 bis L2 über beide Analogsticks ist alles mit einer Funktion belegt. Aber auch ohne die Bedienperfektion gelingen dem eigenen Spieler von Anfang an die schwierigsten Longline-Bälle, während die besseren Gegner die unmöglichsten Schläge in der Not auspacken. Von einer Simulation erwarte ich etwas anderes, aber besser als Virtua Tennis ist dies allemal.

Was bleibt ist die grafisch beste Umsetzung eines Tennisspiel, die es bisher gibt. Teilweise ist auch die Spielphysik überzeugend, aber viele nervige Details wie die Steuerung und die minimalistische Präsentation abseits der Matches vermiesen das Vergnügen. Schade, dass es keine wirkliche Alternative auf dem Markt gibt, denn so ist *Top Spin 3* der beste verfügbare Vertreter seines Genres.
