---
title: "Innovativen Techniken zur Verlängerung der Wartezeiten an Getränkeausgaben"
date: "2010-08-15T00:42:38"
categories: [gedacht]
---

In einer idealen Welt würde ich mit meinem Wunsch, ein Bier an einem Ausschank zu erwerben, mich an einer Schlange anstellen, bedient werden und danach einen Zustand erreichen, in welchem ich glücklich bin, weil ich mein Bier habe, und der Verkäufer glücklich ist, weil er mir ein Bier verkauft hat und nun weitere verkaufen kann. Dies ist eines der Grundprinzipien der Marktwirtschaft. Leider lebe ich jedoch nicht in einer idealen Welt, und so habe ich in letzter Zeit oft viel zu lange an (kurzen) Schlangen angestanden, um den beschriebenen Zustand zu erreichen, während die Verkäufer viel weniger Umsatz gemacht haben, als sie eigentlich könnten, da nicht schnell genug bedient wurde. Und wenn ich viel Zeit benötige, um mein Ziel (das Bier!) zu erreichen, dann bin ich zum Einen nicht glücklich und mache mir zum Anderen Gedanken, warum dies so ist. Dieser Artikel ist das Ergebnis dieser Warteschlangenanalysen, die erläutern warum sowohl der Bierverkauf auf dem [Deck 5](http://www.freiluftrebellen.de/deck-5) als auch bei der [Beachvolleyball-EM](http://eurobeachtour.com/) so unbefriedigend für beide Seiten verlaufen ist.

**Fehlende Spezialisierung**

Als Biertrinker bin ich in den meisten Fällen schnell zu bedienen. Entweder gibt es gar keinen frisch gezapften Gerstensaft, so dass nur eine Flasche zu öffnen ist, oder es stehen bereits abgefüllte Biere bereit. Dies ist natürlich sehr unsolidarisch den Cocktailtrinkern gegenüber, bei denen die Zubereitung ihres Getränkes viel länger dauert. Nur so kann ich es mir erklären, dass am Ausschank die selben Personen für die Zubereitung der Cocktails zuständig waren wie für die Bestellungsaufnahme und das Abkassieren. An drei Schlangen warteten so die durstigen Gäste, weil an allen dreien die jeweilige Bedienung Cocktails mixte.

Das ist das klassische Problem des [Schedulings](http://de.wikipedia.org/wiki/Scheduling). Viele Prozesse, die nur eine kurze Abarbeitung benötigen (wie der Verkauf von Bier an mich), müssen warten, weil langlaufende Prozesse (das Cocktailmixen) die begrenzten Ressourcen (die drei Bedienungen) blockieren. Eine Optimierung hinsichtlich des besten Durchsatzes (also zum Beispiel des meisten Umsatzes in einer begrenzten Zeit) findet nicht statt - und Kunde wie Betreiber sind nicht zufrieden gestellt.

**One Queue to rule them all**

Eine andere Variation des selben Problems erlebte ich an einer Grillstation-Bierwagen-Kombination. Aus mir nicht bekannten Gründen konnte man am Grill eine Wurst oder ein Steak nur gegen eine Marke erhalten, die es am Bierwagen zu erwerben galt. Also gab es eine lange Schlange am Bierstand, die als einzelne Ressource sowohl den Bierausschank als auch den Erwerb einer Essensmarke verzögerte. Zudem bestand diese unnötige Zwischenwährung aus kleinen Zetteln, die einzeln vom Block abgerissen und beschriftet werden mussten, damit der Grillstand wusste, ob er eine Wurst oder ein Steak ausgeben durfte.

So mussten alle potentiellen Kunden auf andere Kunden warten, die eigentlich ein ganz anderes Ziel verfolgten. Und während der Verkäufer an einem reinen Getränkestand über die sich entwickelnde Routine mit der Zeit schneller wird, war in meinem Beispiel durch das ständige Wechseln zum Zettel-abreißen-und-beschriften-Prozess eine deutliche Verlangsamung zu spüren.

**Fazit**

Aber da es im Kapitalismus immer mehrere Optionen gibt, den eigenen Gewinn zu maximieren, wird oftmals nicht am fehlerhaften Prozess geschraubt, sondern es werden einfach die Preise erhöht. In beiden Beispielfällen mussten sich die Betreiber keine Gedanken um eine etwaige Konkurrenz machen, so dass unnötig komplizierte Prozesse auch weiterhin den Kunden unzufrieden zurücklassen.
