---
title: "Dosenbier"
date: "2007-07-06T08:37:40"
categories: [gedacht,getan]
---

Da werden Erinnerungen wach: Vor der Einführung des Dosenpfand fuhr man als Festivalbesucher das Bier stiegenweise in Büchsen auf das Campinggelände und ließ die metallenen Rückstände anschließend dort zurück. Nachdem der Pfand jedoch die Biertrinker zwang, die Dosen in der Originalform nach dem Austrinken aufzubewahren, setzten sich schnell wieder die Bierflaschen durch - aus denen es auch ohne Zweifel besser schmeckt.

Nun scheinen die Festivalbetreiber eine Kehrtwende am Markt erreichen zu wollen. Auf immer mehr Festivals sind nämlich Glasflaschen auf dem Campingplatz verboten - damit die nach dem Festival der Originalnutzung wieder zugeführte Kuhweide auch möglichst keinem Rind einen Schaden durch Glasscherben im Futtergras beschert. Doch damit steht man als Besucher vor der schweren Entscheidung: Bierbüchsen oder Plasteflaschen? Da die meisten Biere in Plasteflaschen von Aldi, Lidl & Co vertrieben werden und es damit keine guten Biere in dieser Abfüllform gibt, war die Sache für mich schnell entschieden. Und gleich im zweiten Supermarkt bin ich dann auch fündig geworden: Der E-Center auf der Silberhöhe hatte Jever und Holsten als Dosen im Angebot - das Festival ist gerettet!

Ich bin übrigens nicht beim [Splash](http://www.splash-festival.com/) in Pouch (Pautsch gesprochen, wie die Fetten Brote meinen), sondern im sicherlich auch verregneten [Harz](http://openair.rockharz.de/)!
