---
title: "Upstream color"
date: "2013-03-27T00:18:00"
categories: [gesehen]
---

[Berlinale-Filmdatenblatt](http://www.berlinale.de/de/programm/berlinale_programm/datenblatt.php?film_id=20132176)

"Die Gedanken sind frei" heißt es in einem deutschen Volkslied. Nicht jedoch bei *Upstream Color*, in welchem Maden in der Lage sind, einen Menschen so zu manipulieren, dass er alles tut und glaubt, was ihm gesagt wird. So muss die entführte Kris in ihrer Madenhypnose ihr komplettes Hab und Gut abtreten und ein Buch über zivilen Ungehorsam Seite für Seite abschreiben.

Als sie aus dieser Trance erwacht, hat sie das Gefühl, dass sich noch immer Maden in ihrem Körper bewegen. Hilfe findet sie bei einem Schweinezüchter, der sie in einer Operation von ihren Qualen befreit. 

Doch auch körperlich wieder hergestellt ist sie nicht mehr die Alte; es fällt ihr schwer, ein neues Leben aufzubauen. Da trifft sie auf Jeff und die beiden stellen fest, dass ihre Leben über gemeinsame Erinnerungen verknüpft sind. Und nicht nur dass, auch mit den Schweinen des Schweinezüchters fühlen sie sich übernatürlich verbunden...

So wie sich die Inhaltsangabe nach einem wirren Fiebertraum anhört, dessen innere Logik sich sofort nach dem Aufwachen nicht mehr erschließt, so lässt sich auch dem Film wie einem Bewusstseinsstrom folgen, ohne zu verstehen, was da eigentlich genau abläuft. Wie die Madenhypnose mit den Schweinen zusammenhängt und wie diese ein Orchideenwachstum beeinflussen - ich kann es nicht sagen. Doch die Montage setzt dies in einen Zusammenhang, dem man auch ohne Verständnis folgen kann. Ich habe als Zuschauer nur die Wahl, die gezeigte Welt mit ihren unverständlichen Regeln zu akzeptieren oder an dem Film zu verzweifeln

So zurückhaltend der Film mit erklärenden Informationen umgeht, so minimalistisch zeigt er sich auch in den Dialogen. Viel spielt sich in den Gesichtern der beiden Hauptdarsteller ab, die meist in Nahaufnahmen zu sehen sind, bei denen dank extremer Tiefen(un)schärfe der Rest des Bildes in Unschärfe versinkt. Dies alles verstärkt den Eindruck eines Traumes; aus dem Meer der verschwommenen Erinnerungen treten Szenen wie einzelne Ereignisse hervor an die Oberfläche der Leinwand.

Regisseur Shane Carruth hat mit seinem kleinen Film auf jeden Fall geschafft, was nur wenigen Kreativen in der Filmwirtschaft möglich ist: Er hat die vollständige künstlerische Kontrolle über sein Projekt ausgeübt. Neben Drehbuch und Regie war er gleichzeitig auch für Kamera und die zurückhaltende, aber zeitweilig intensive Filmmusik verantwortlich und übernahm zudem eine der beiden Hauptrollen.

Allein dafür sollte man Shane Carruth Anerkennung zollen. Nur leider habe ich mir bis heute keinen Reim auf das Gesehene machen können, so dass ich hin- und hergerissen bin, ob mir der Film aufgrund seiner Stimmung gefällt oder er mich mit seiner schweren Zugänglichkeit abstößt...
