---
title: "Final Destination 2"
date: "2003-03-18T00:00:55"
categories: [gesehen]
---

*USA (2003)
Regie: David R. Ellis
Darsteller: A. J. Cook (Kimberly Corman), Michael Landes (Officer Thomas Burke), Ali Larter (Clear Rivers), T. C. Carson (Eugene Dix), Jonathan Cherry (Rory), Keegan Connor Tracy (Kat), Sarah Carter (Shania), Lynda Boyd (Nora Carpenter), David Paetkau (Evan), Justina Machado (Isabella Hudson), James N. Kirk (Tim Carpenter), Tony Todd (Mr. Bludworth), Enid-Raye Adams (Dr. Kalarjian) und viele eigentlich Tote mehr*
[Offizielle Homepage](http://www.warnerbros.de/movies/finaldestination/)

Kimberly ist mit 3 Freunden zusammen auf der Autobahn unterwegs, als sie plötzlich eine schreckliche Vision von ihrem baldigen Tod bei einem schweren Unfall hat. Total verstört hält sie den Wagen an und entgeht tatsächlich zusammen mit einer Gruppe von anderen Menschen der Katastrophe. Doch bald schon müssen die Glücklichen, die dem Unfall entgingen, feststellen, dass für sie ein anderes Schicksal bestimmt war und einer nach dem anderen kommt unter mysteriösen Umständen doch noch ums Leben. Kimberly wendet sich verzweifelt an die einzige Überlebende eines ähnliches Vorfalls ein Jahr zuvor, doch kann man dem Tod auf Dauer wirklich von der Schippe springen?

Ich habe mir trotz der anfangs sehr interessanten Thematik (wenn man dann aber mal 5 Minuten darüber nachdenkt, ist alles doch vollkommen hirnrissig!) den ersten Teil nicht angesehen und ging mit den sehr geringen Erwartungen an ein TeenScreamMovie in den Film und wurde auf eine sehr morbide Art doch positiv überrrascht.

Zuallererst: Die Story gibt nicht wirklich viel her und wird schon bald aufgrund der Thematik der Lächerlichkeit preisgegeben; die Schauspieler verdienen diese Bezeichnung allesamt nicht, wurden aber auch nur angestellt um möglichst effektiv zu sterben und davor ein bissel nett und verängstigt auszusehen. Dies alles ist jedoch keine Überraschung, denn wie in jedem Teenie-Slasher geht es ja sowieso nur darum, wer wann und wie stirbt (oder auch nicht). Dieses Prinzip hat der Film dann auch gleich zum Selbstzweck erklärt und holt seine einzige Motivation daraus, für jeden Darsteller ein paar Möglichkeiten des Todes aufzuzeigen und dann ganz heimtückisch nach einer scheinbaren Rettung doch noch zuzuschlagen.

Diesem doch etwas morbiden Prinzip muss sich alles andere unterordnen und trotzdem schafft es der Film mit sieben (doppelten) Todesfällen anderthalb Stunden lang das Tempo hochzuhalten. Dabei wird den Opfern auch nichts erspart und die Kamera blendet keinen Augenblick lang weg, so dass man als Zuschauer zwischen widerlich und der durch Abgestumpftheit gegenüber Slasherfilmen und der Absurdität der Tode erreichten Witzigkeit der Szenen schwankt. Mit mir im Kino saßen jedoch allesamt Menschen, die den Film genausowenig ernst nahmen wie ich und in ihrem Leben schon mehr Leinwandblut gesehen haben als Wasser, und dementsprechend war die Stimmung ganz prächtig und alle haben sich gut amüsiert.

Fazit: Wer Slasherfilme und absurd-witzige Tode in allen Facetten mag, der wird mit dieser Fortsetzung gut bedient. Mehr kann man aber bei besten Willen nicht aus dem Film mitnehmen, denn weder Spannung im herkömmlichen Sinne noch eine sinnvolle Handlung findet man hier vor!
