---
title: "The Thing (1982) vs. The Thing (2011)"
date: "2011-12-02T21:30:32"
categories: [gesehen]
---

Vor beinahe dreißig Jahren (1982) drehte John Carpenter mit *Das Ding aus einer anderen Welt* (*The Thing*) das Remake eines Horrorfilmklassikers, welches inzwischen selber zum Klassiker geworden ist. Dieses Jahr nun gab es unter gleichem Namen ein Prequel, was ich mit ein paar Kollegen zum Anlass genommen habe, mir die beiden Filme in einem *The-Thing-Double-Feature* anzusehen.

Die Handlung des 1982er Filmes ist schnell erzählt: Ein außerirdisches Monster, das vorher von Norwegern aus dem ewigen Eis befreit wurde, fällt in eine amerikanischen Forschungsstation in der Antarktis ein. Das Ding hat die Fähigkeit, andere Lebewesen nachzubilden, indem es sie verschlingt und auf Zellebene kopiert. Bald wissen die Wissenschaftler nicht mehr, wer von ihnen noch ein Mensch ist und wer bereits assimiliert wurde, doch sie wissen ganz genau, dass sie das Ding nicht entkommen lassen dürfen, da es eine Gefahr für die gesamte Menschheit darstellt.

Das titelgebende Monster, wenngleich für einige deftige Splatterszenen verantwortlich, steht dabei gar nicht im Vordergrund. Vielmehr wird durch das wachsende Misstrauen der Wissenschaftler untereinander und die menschenfeindliche Umgebung der durch einen Schneesturm von der Außenwelt abgeschirmten Forschungsstation eine bedrohliche Atmosphäre erzeugt, die schließlich in einem heißen Showdown mit offenem Ende kulminiert.

Neben dem Hauptdarsteller Kurt Russell (wie seine Forscherkollegen in Vollbart) ziert ein weiterer berühmter Name den Vorspann. Ennio Morricone wird als Komponist des Soundtracks genannt, doch angeblich war John Carpenter nicht zufrieden mit dessen Arbeit und hat selber ein paar Stücke für den Film geschrieben. So oder so, der Score ist mit seinen Synthiestakkatos ein Kind seiner Zeit und seines Genres, damit aber trotzdem präsenter als sein Gegenstück aus der 2011er Neuauflage.

Diese erzählt quasi die Vorgeschichte zu *The Thing*. Norwegische Antarktisforscher entdecken in hunderttausend Jahre altem Eis ein UFO und bald auch ein Alien, welches das Schiff verlassen hat und dabei gefrostet wurde. Zusammen mit eingeflogenen amerikanischen Forschern (es soll ja nicht nur norwegisch gesprochen werden) soll der Fund analysiert werden. Doch keiner auf der Station hat damit gerechnet, dass das geborgene Alien noch lebt, und bald müssen die Forscher feststellen, dass dieses Ding Menschen kopieren kann.

Eine Stunde lang ergeht sich das Prequel darin, in einer Art respektvoller Verbeugung vor Carpenters Original wichtige Handlungselemente daraus nachzuerzählen und Verknüpfungen zu legen. Dies reicht von der Axt in der Wand und dem Funker mit den aufgeschnittenen Pulsadern, die Kurt Russell 1982 bei der Durchsuchung der norwegischen Station fand, bis hin zu dem versagenden Flammenwerfer und den aus der Arrestzelle fliehenden Gefangenen. Andere Elemente werden leicht variiert (z.B. [die legendäre Bluttestszene](http://www.archive.org/details/TheThingcompleteBloodTestScene)), wobei nicht alle Neuerungen funktionieren.

So waren die Charaktere des Original-Casts markanter als in der Neuauflage; allein Kurt Russell steckt die B-Movie-Darsteller um Mary Elizabeth Winstead und ihre platten Nebenfiguren lässig in die Tasche. Auch das Monster, 2011 zeitgemäß digital animiert, hat einiges an Wirkungskraft verloren. Warum entpackt sich das Ding so langsam hinter der Hauptdarstellerin - in der gleichen Zeit hätte es sie schon längst abgefertigen können. Und eine spätere Verfolgungsjagd wäre erfolgversprechender verlaufen, wenn das Alien erst die Metamorphose beendet hätte. Außerdem scheint es bei späteren Auftritten nicht mehr so schnell zu sein wie beim anfänglichen Ausbruch - da war das Original konsequenter und damit auch bedrohlicher.

Erst zum Ende hin löst sich das Prequel schließlich vom Vorbild und setzt eigene Akzente mit seinem Finale im Inneren des Raumschiffs. Viel interessanter fand ich jedoch die Unterschiede, die einen Rückschluss auf unsere Gesellschaft erlauben. So war die Forschungsstation der Amerikaner 1982 eine reine Männerdomäne, in der im Aufenthaltsraum fleißig geraucht und getrunken wurde. Einen Film ohne Frauen mutet man 2011 dem Zuschauer nicht mehr zu; und so wie das Rauchen langsam aber sicher aus der Öffentlichkeit verbannt wird so sieht man auch in *The Thing* (2011) nur noch eine einzige glimmende Zigarette.

Am Ende war diese Doublefeature gerade durch den Vergleich der beiden Filme eine interessante Erfahrung; die 2011er Version bleibt jedoch zu belanglos um weiterempfohlen zu werden. John Carpenters Original von 1982 spielt dagegen in Sachen Atmosphäre auch aufgrund der Bild- und Tongestaltung in einer anderen Liga und hat so seinen Platz in der Geschichte des Horrorfilms verdientermaßen sicher.
