---
title: "Planet der Affen"
date: "2001-09-04T00:00:47"
categories: [gesehen]
---

*USA (2001)
Regie: Tim Burton
Darsteller: Mark Wahlberg (Leo Davidson), Tim Roth (General Thade), Helena Bonham Carter (Ari), Kris Kristofferson (Karubi), Estella Warren (Daena), Charlton Heston (Vater von Thade) und andere Primaten*
[Offizielle Homepage](http://www.planetoftheapes.com)

Leo Davidson ist Affen-Trainer auf einer Weltraumstation. Als ein von ihm betreuter Affe auf einem Flug durch einen Elektronensturm verschwindet, fliegt er zur Aufklärung hinterher. Doch dabei wird er durch Zeit und Raum geschleudert und muss auf einem Planeten notlanden. Dort haben intelligente Affen die Herrschaft und unterdrücken die ebenfalls da lebenden Menschen. Von dem Menschenfeind General Thade gefangen und von der "Menschenfreundin" Ari zur Flucht verholfen versucht Leo nun, Kontakt mit seiner Station aufzunehmen, wobei er jedoch eine unverhoffte Entdeckung macht und das Geheimnis des Planeten der Affen aufdeckt...

Als Fan des Originals und der bisherigen Tim-Burton-Filme muss ich sagen: Er hat seine Seele an Hollywood verkauft. War das Original seinerzeit in den 60ern eine intelligente Parabel auf die Menschheit mit einer guten Schlusspointe, so ist das Remake einfach nur ein Unterhaltungsfilm mit tollen Affenkostümen, aber keiner Aussage und einem Ende, wie es unlogischer nicht sein könnte - entweder wollte man auf jeden Fall einen ähnlichen Schock wie beim Original erreichen (was sich aber mit dem Film widerspricht), oder es wird gleich wieder eine ganze Serie von Filmen geplant.

Eine gute Seite hat der Film aber: Es wird im Gegensatz zum Original die Entstehung der Affen-Mensch-Situation logisch erklärt, aber auf dem Weg dahin muss der Film jedoch ständig die Affen verdammen und die Menschen hochleben lassen (typisch amerikanischer Patriotismus); Leo erscheint in jedem Teil des Films überlegen und arrogant und es findet keine wirkliche Auseinandersetzung mit dem Problem statt. Stattdessen gipfelt der Film in einem sinnlosen Massaker, wie es einem Schwarzenegger-Schinken alle Ehre gemacht hätte und einem plötzlichen Umschwenk der beiden Parteien auf Friede, Freude, Eierkuchen. Und zu dem endgültigen Schluss muß man wirklich nichts mehr sagen!

Fazit: Tim Burton hat sich kaufen lassen und einen Film gedreht, der zwar eine tolle Optik und tolle Kostüme aufweisen kann, ansonsten aber auf ganzer Linie enttäuscht. Ein Unterhaltungsfilm, nicht mehr und nicht weniger!
