---
title: "Elite-Unis alle im Westen"
date: "2006-01-21T11:13:15"
categories: [gedacht,gefunden]
---

.. titelt heute die MZ zu der [gestern veröffentlichten Entscheidung](http://www.dfg.de/aktuelles_presse/reden_stellungnahmen/2006/exzellenzinitiative_0601.html) der [*Exzellenzinitiative*](http://www.wissenschaftsrat.de/exini_start.html) über die Auswahl der künftig stärker geförderten Universitäten. Sachsen-Anhalts Kultusminister Olbertz nennt es

> "durchaus plausibel", dass über Jahrzehnte gewachsene Zentren besonders berücksichtigt worden seien.

Was steckt allerdings hinter diesen "Elite-Unis"? Es geht um die stärkere Differenzierung der deutschen Hochschullandschaft nach Qualitätsgesichtspunkten, um so die internationale Sichtbarkeit deutscher Universitäten deutlich zu erhöhen. Die besten Unis sollen zwischen 2006 und 2011 mit 1,9 Milliarden Euro zusätzlichen Mitteln gefördert werden, um die Spitzenforschung voran zu treiben.

Dazu werden sogenannte *Graduiertenschulen zur Förderung des wissenschaftlichen Nachwuchses* und *Exzellenzcluster zur Förderung der Spitzenforschung* an den deutschen Hochschulen bestimmt und diese konkurrierend gefördert. Eine Universität, der eine positive Bewertung dieser beiden Förderlinien bescheinigt wird, erhält danach eine weitere Förderung im Rahmen der *Zukunftskonzepte*.

Und unter den Anwärtern für diese *Zukunftskonzepte* befindet sich nun keine einzige ostdeutsche Universität - die meisten werden aber zumindest über eine Förderlinie unterstützt. So erscheint die Aussage von Kultusminister Olbertz logisch: Der Großteil der westdeutschen Hochschulen kann eine vier Jahrzehnte länger andauernde Spitzenforschung und Zusammenarbeit mit der Wirtschaft vorweisen, während in den neuen Bundesländern auch aufgrund der schlechten Finanzlage und der fehlenden Industrie noch nicht einmal jede Universität das eigene Profil vollständig ausgebildet hat. 

Auf der anderen Seite weisen die Titel der Förderlinien darauf hin, dass vor allem Gebiete der aktuellen Forschung gefördert werden (welche 2011 vielleicht schon wieder zum alten Eisen gehören). Hier haben die ostdeutschen Universitäten scheinbar in ihren Finanznöten nicht den Mut und die Mittel gehabt, in die Zukunft zu investieren.

Dies bedeutet aber auch, dass der Vorsprung der besten Unis mit dieser Art der Förderung weiter wachsen wird. In Zusammenhang mit der Tatsache, dass allein die Bundesländer über die Finanzierung der Hochschulen entscheiden, kann dies der Anfang einer Abwärtsspirale sein:

Die ostdeutschen Universitäten werden vom Staat nicht gefördert und die Länder sparen sich tot an ihren Bildungseinrichtungen. Damit sinkt die Wahrscheinlichkeit, in einer möglichen neuen *Exzellenzinitiative* nach 2011 gefördert zu werden, was eine Abwanderung der hochgebildeten Fachkräfte in die spitzengeförderten Zentren nach sich zieht. So bluten die Hochschulen nach und nach aus.

Aus meiner Sicht wird also mit dieser *Exzellenzinitiative* das Teilziel einer

> Anhebung der Qualität des Hochschul- und Wissenschaftsstandortes Deutschland in der Breite

ganz klar zu Gunsten der Spitzenforschung verfehlt. Und dies ist eine sehr traurige Entwicklung, die wahrscheinlich auch eine Abwertung der Abschlüsse an den nicht geförderten Universitäten nach sich ziehen wird. Deutschland verspielt auf diese Weise immer mehr seine Stärke der gut ausgebildeten Fachkräfte in dem unsinnigen Versuch, neue Eliten zu bilden.
