---
title: "Weiße Lilien"
date: "2008-09-18T20:37:32"
categories: [gesehen]
---

*Deutschland/Österreich (2008)
Regie: Christian Frosch
Darsteller: Brigitte Hobmeier (Hannah Schreiber), Johanna Wokalek (Anna), Martin Wuttke (Hauks), Xaver Hutter (Branco), Walfriede Schmitt (Paula), Günther Kaufmann (Mark), Gabriel Barylli (Erik Lasalle), Erni Mangold (Frau Danneberg), Peter Fitz (Ludwig von Auerbach) und andere Neustädter*
[Offizielle Homepage](http://www.weisse-lilien-der-film.de/)

Hannah lebt in einer autarken Hochhaussiedlung namens *Neustadt* und arbeitet dort in einem Callcenter. Ihr Mann Branco, ein Sicherheitsoffizier für *Neustadt*, schlägt sie. Deshalb flüchtet sie in die Arme von Hauks und bezieht eine eigene Wohnung, die gerade aufgrund eines Selbstmordes frei geworden ist. Außerdem freundet sie sich mit Anna an, die anscheinend einer Terrorgruppe gegen den Gründer von *Neustadt*, Ludwig von Auerbach, angehört. Doch dann verschwindet Branco, während gleichzeitig Hannah auserwählt wird, eine Lobrede auf Auerbach zum Jubiläum von *Neustadt* zu halten, und plötzlich weiß Hannah nicht mehr, was Realität und was Traum ist: Hat sie ihren Mann getötet, gehört sie ebenfalls der Terrorgruppe an oder gibt es sogar eine groß angelegte Verschwörung unter den Mächtigen von *Neustadt*?

Was sich nach einer gesellschaftskritischen Zukunftsvision im Stile von 1984 anhört, hat noch viel mehr Seiten. Neben den abstrakt angerissenen sozialen Problemen im abgeschlossenen Raum *Neustadt* (Abgrenzung und unterschiedliche Behandlung der sozialen Schichten, gegenseitiges Aufhetzen unterschiedlicher Volksgruppen, teilweise Mangelwirtschaft) skizziert *Weiße Lilien* auch einen keineswegs sicheren Überwachungs- und Sicherheitsstaates und eine Gesellschaft, in der Individualismus auch bedeutet, dass jeder unbeteiligt wegsieht und -hört. Zudem wird eifrig David Lynch zitiert (Hannah verschmilzt kurz vor Ende zu Anna (beides Palindrome), nie ist klar ob man den Bilder trauen kann) und es gibt viele Kreise in der Handlung und den Figurenkonstellationen: Die Filmhandlung beginnt mit der Feierszene und schließt damit; das Wasser als Bild für die sozialen Gegensätze wird bis zum Schluss ständig bemüht und das Hunde-Kinder-Thema kehrt ebenfalls immer wieder.

Die Inszenierung des riesigen Wohnblocks bleibt dabei unnatürlich kühl, die Figuren und Dialoge sind bewusst steif gehalten. Ich konnte an keiner Stelle des Films die Motivation von Hannah verstehen, zu extrem und expressionistisch sind ihre Handlungen. Einiges davon kann man im Nachhinein noch interpretieren, wenn man akzeptiert, dass Hannah und Anna ein und dieselbe Person sind, doch nicht alles will passen. *Weiße Lilien* will ein Kunstfilm sein und verweigert sich deshalb auch klarer Aussagen und einfacher Zugänglichkeit, doch leider geht die Motivation zum Verständnis aufgrund der Menge an angerissenen Themen und eingesetzten Stilmitteln schnell von dannen.

Fazit: Ein Film, so kunstvoll wie künstlich inszeniert, so vielschichtig wie schwer interpretierbar. Doch während man bei David Lynch noch Freude dabei entwickeln kann, den Film auseinanderzunehmen und hinter die Aussage zu kommen, bleibt unter den vielen Bildern, angeschnittenen Themen und der kryptischen Sprache bei *Weiße Lilien* nichts übrig, was eindeutige Schlüsse zulässt. So werden vermutlich die meisten Menschen so verwirrt wie ich das Kino verlassen - und schlauer bin ich bis jetzt nicht!
