---
title: "Ein halbes Leben"
date: "2009-05-18T22:02:37"
categories: [gesehen]
---

Nach der Tagesschau kurz gezappt. Beim ZDF das Gesicht von Josef Hader erkannt. Und hängengeblieben.

Dieser Fernsehfilm war die eindeutig beste Auseinandersetzung mit dem Thema rückfällige Sexualstraftäter seit [The Woodsman](/blog/2008/02/17/der-damon-in-mir/) - in Zeiten von [Internetsperren gegen Kinderpornographie](/blog/2009/04/19/dies-ist-nur-ein-beitrag-uber-zensur/) eine mutige Entscheidung, den Film zur Hauptsendezeit auszustrahlen. Dabei wurde der Schwerpunkt auf die Zeit nach dem Verbrechen gelegt und das weitere Leben sowohl der Eltern des Opfers als auch des Täters in verschiedenen Zeitabschnitten gezeigt.

Dies läuft zu keiner Zeit auf eine Rechtfertigung hinaus (höchstens zum Ansatz einer Erklärung), und doch ist es den Hauptakteuren Josef Hader und Matthias Habich zu verdanken, dass man als Zuschauer mit beiden Seiten mitfühlen kann. Schließlich hat die Resozialisierung zu weiten Teilen funktioniert; der Täter (Hader) hat eine neue Existenz aufgebaut, ist Vater geworden und gibt seiner älteren Nachbarin Hilfe und Halt. Der Vater des Opfers (Habich) dagegen braucht Jahre, um damit fertig zu werden, seiner Tochter bis zu deren Tod ein schlechter Vater gewesen zu sein. All seine Kontakte in der Polizei können ihm nicht helfen, doch diese plötzliche Unsicherheit verbessert schließlich auch die Beziehung zu seiner Frau.

Und so genau der Film seine Charaktere beobachtet, so geht er auch keinen Kompromiss beim Ende ein - der Täter wird vor Gericht verurteilt. Und die Eltern des Opfers bekommen sowohl den Beweis, dass dieses Urteil nur eine schwache Genugtuung ist, als auch eine neue Chance mit der Tochter des Verbrechers. Ein bisschen Optimismus darf also sein, selbst wenn der Straftäter rückfällig war.
