---
title: "The Illusionist"
date: "2010-03-27T19:42:32"
categories: [gesehen]
---

[Berlinale-Filmdatenblatt](http://www.berlinale.de/de/programm/berlinale_programm/datenblatt.php?film_id=20100073)

*The Illusionist* ist ein ruhiger, melancholischer Zeichentrickfilm des Regisseurs von *Das große Rennen von Belleville*. Dessen eigenwilliger, aber sympathischer Zeichenstil findet sich auch bei *The Illusionist* wieder, in einigen wenigen Szenen durch Computeranimationen unterstützt. Zusammen mit der sehr ruhigen Musikuntermalung des reinen Piano-Scores und dem Fehlen echter Dialoge - manchmal gibt es an genuschelte Sprache erinnerndes Brabbeln einiger Figuren - sticht der Film aus der breiten Zeichentrick-Masse hervor.

Erzählt wird die Geschichte des gealterten Zauberers Tatischeff, der auf den Bühnen der Varietétheater von moderneren Formen der Unterhaltung verdrängt wird und so auf einer tristen, zurückgebliebenen Insel in Schottland landet. Dort beeindruckt er mit seinen Zauberkünsten ein junges Mädchen so sehr, dass sie ihm nach Edinburgh folgt, wo er sich dem unerfahrenen Ding annimmt und eine Art Vaterfigur für sie wird. Er kauft ihr Kleidung und Schuhe, immer in der Illusion, dass er die Geschenke herbeizaubert. Doch ohne festen Job hat der Künstler große Probleme, das gemeinsame Leben zu finanzieren.

Viel Handlung transportiert der Film nicht, bis am Ende aus dem unerfahrenen Inselmädchen eine junge Frau geworden ist. Aber da er seine Geschichte ohne Dialoge erzählen muss und viel Wert auf Details und kunstvoll ausgearbeitete und eingefangene Szenen legt, fällt dies kaum auf. Gleichzeitig fasziniert die Zeichnung der vielen Nebencharaktere, die in ihrer skurilen, teilweise auf Vorurteilen basierenden Darstellung immer wieder für Lacher gut sind und so den melancholischen Grundton in der Schilderung des anachronistisch wirkenden Lebens des Zauberers überspielen.

Ingesamt bleibt aber ein zweigespaltener Eindruck übrig. In jedem Bild gibt es viel zu entdecken, die Charaktere sind skuril-sympathisch, doch die Handlung - aus einer Kurzgeschichte entstanden - weiß nicht über die gesamte Länge des Films zu überzeugen und das Fehlen von Dialogen machte sich zumindest bei mir durch Ermüdungserscheinungen bemerkbar.

Die Vorlage des Drehbuchs lieferte übrigens [Jacques Tati](http://de.wikipedia.org/wiki/Jacques_Tati), der nicht nur mit bürgerlichen Namen Tatischeff hieß, sondern auch mit seiner berühmten Leinwandfigur Monsieur Hulot die Vorlage für den Zauberer stellt. Dies würdigt der Film mit einer Szene, in der der Zeichentrick-Tatischeff in ein Kino stolpert, in dem ein Film des Originals läuft. So versteht sich *The Illusionist* in seiner nostalgisch wirkenden Debatte um Illusion und Wirklichkeit als eine Hommage an Tatis Filme - bei gleichzeitiger Vorlage durch den Franzosen ein doppelbödiges Spiel, das mir in seiner referentiellen Art gefallen hat, wenngleich ich die Zusammenhänge erst in der anschließenden Recherche erfahren habe.

Der bei der Berlinale gezeigt Version des Films fehlte übrigens noch der Abspann - dieser war nicht rechtzeitig zum Filmfestival fertig geworden. Schön, dass *The Illusionist* trotzdem gezeigt werden konnte!
