---
title: "Rückkehr von den Sternen"
date: "2008-01-09T23:04:33"
categories: [gelesen]
---

*von Stanislaw Lem,
veröffentlicht von List, ISBN 978-3-548-60146-5, 8,95 €*

Seit fast zwei Jahren ist Stanislaw Lem, polnischer Utopist und Philosoph, nun schon [tot](/blog/2006/03/27/stanislaw-lem/). Zeit für mich, endlich die wenigen Lücken in der Bibliothek meines Vaters aufzufüllen. Von den dreizehn utopischen Romanen fehlten nur zwei in der Sammlung, und so nahm ich mir zuerst die *Rückkehr von den Sternen* vor.

Der Held des Buches, Hal Bregg, war über 100 Jahre auf einer Weltraumexpedition, die ihn dank [Einsteins Theorie](http://de.wikipedia.org/wiki/Relativitätstheorie) nur 10 Jahre ältern ließ. In dieser Zeit hat sich die Erde grundlegend gewandelt. Mittels eines Eingriffs wird den Menschen schon als Kind die Aggressivität quasi herausoperiert, wodurch sich eine Gesellschaft ohne Kriege gebildet hat, der es aufgrund der technischen Entwicklung an scheinbar nichts fehlt. Hal Bregg versucht nun, sich in diese neue Welt einzufügen, die sich so stark von allem unterscheidet, was er gewohnt ist...

Wieder einmal hat sich Lem mit diesem Roman von 1961 daran versucht, eine zukünftige Gesellschaft anhand einer Idee zu entwerfen. Dazu nimmt er sich eine unfertige Figur wie den Piloten Bregg und wirft sie mitten hinein - weder versteht dieser die Welt, noch sie ihn. Doch Bregg ist nicht zum Scheitern verurteilt, obwohl er massive Schwierigkeiten hat, sich anzupassen. Denn er hat noch diesen Trieb, diese Aggressivität, die den Menschen vorantreibt und die der neuen Gesellschaft so fehlt.

Und während seine Hauptperson grobschlächtig durch die Handlung stolpert, philosophiert Lem über die Auswirkungen der aggressionslosen Gesellschaft, thematisiert die (technischen) Voraussetzungen für deren Erfolg und analysiert die Reaktionen der Menschen. So präsentiert er eine Droge, die Aggressionen verursacht, geht auf einem aufgrund des mangelnden Antriebs dopinglosen Sport ein, der sich auf wenige Sportarten beschränkt und beschäftigt sich mit der Aufgabe des Tötens, die an die Roboter delegiert wurde.

Der zentrale Diskussionpunkt aber, zu dem Bregg und seine Weggefährten immer wieder zurückkehren, ist die Raumfahrt. Lem erfindet wissenschaftliche Abhandlungen über den Unsinn von Weltraumreisen, vermischt diese mit den Erfahrungen des Hauptcharakters und zieht trotzdem den Schluss, dass es sich lohnt. So sehr, dass bis auf Bregg alle Expeditionsteilnehmer eine neue Reise starten wollen.

Etwas schwieriger als das Ende des Buches gestaltet sich jedoch der Einstieg. Fast siebzig Seiten lang hetzt Lem den Leser durch Beschreibungen der zukünftigen Erde; man bekommt beim Lesen fast schon die Schwindelgefühle des Helden und hat mindestens ebensolche Verständnisschwierigkeiten. Doch dann findet Bregg und mit ihm der Leser immer mehr Fixpunkte, und es beginnt der philosophische Exkurs mit einigen überraschend präzisen Voraussagen aktueller Techniken - das Buch ist immerhin fast 50 Jahre alt. 

Fazit: Bereut habe ich den Kauf nicht und lege das Buch (bzw das Gesamtwerk Lems) allen ans Herz, die sich für Utopie und Science-Fiction in der ursprünglichen Bedeutung des Wortes interessieren.
