---
title: "Play Berlin!"
date: "2010-03-20T00:35:21"
categories: [gewesen,gespielt]
---

Ich war diese Woche auf Einladung meines Arbeitgebers zum ersten Mal zum Wii-Zocken im [Play! Berlin](http://play-berlin.de/Alexanderplatz/) am Alex. Dahinter verbirgt sich eine Art After-Work-Lounge, die voll auf das Spielen mit Nintendos Konsole ausgelegt ist. Man mietet sich einen Tisch oder eine Loge, die jeweils mit Fernseher, angeschlossener Konsole und vier Controllern ausgestattet sind, und kann sofort anfangen mit spielen. Eine lange Liste von etwa siebzig Wii-Titeln steht zur Verfügung inklusive eventuell benötigtem Zubehör wie zum Beispiel den Lenkrädern für *MarioKart*. Hat man keine Lust mehr auf das aktuelle Spiel, bestellt man bei der Bedienung einfach ein Neues.

Passend zu der Konsole ist auch die Einrichtung der Lounge in weiß gehalten und könnte einem aus dem IKEA-Katalog bekannt vorkommen. Wer nicht gerne vor den Augen aller anderen Besucher herumturnt hat die Möglichkeit, eine der Logen zu mieten, die jedoch fast schon zu klein für ein Vier-Spieler-Tennismatch ausfallen. Verzichtet man auf diesen Luxus, ist man mit 8€ die Stunde für einen Tisch dabei. Bei vier Spielern macht das 2€ pro Stunde und Person, das ist aus meiner Sicht ein fairer Kurs. Etwas schlecht ausgerüstet ist die Bar leider in Sachen Bierangebot. Es gibt kein Fassbier und an Pils nur Carlsberg aus der Flasche; aber deshalb nennt sich das Ganze auch Lounge und nicht Kneipe - und leert sich dementsprechend zeitig am Abend.

Wer also das Geld für eine eigene Konsole nicht ausgeben will und etwas exhibitionistisch veranlagt ist, hat im Play! Berlin die Chance, in loungiger Atmosphäre nach der Arbeit noch eine Runde Wii zu zocken. Mit der richtigen Begleitung kann dies sehr viel Spaß machen!


