---
title: "Me & Monkey Island"
date: "2010-09-11T22:21:03"
categories: [gedacht,gespielt]
---

Viele Computerspieler werden auf die Frage, an welches Spiel sie besondere Erinnerungen haben, wohl einen der ersten beiden Teile der *Monkey Island*-Serie nennen. Dies ist bei mir nicht anders, und anlässlich der [Veröffentlichung der Special Edition des zweiten Teils, LeChuck's Revenge](http://www.lucasarts.com/games/monkeyisland2/), will ich kurz über meine Erfahrungen berichten.

Angefangen hat es 1990. Die DDR war gerade Geschichte, ich neun Jahre alt und noch leicht zu beeindrucken. Dies war den Betreibern des Computerkabinetts der Schule wohl klar, denn auf deren PCs liefen während eines Besuchs ausschließlich Spiele. Ich hatte bis dahin noch nie einen Computer gesehen, und so faszinierte mich sogar das auf einem Rechner laufende [Snake](http://de.wikipedia.org/wiki/Snake). Doch den bleibensten Eindruck machte auf mich ein Spiel namens *Monkey Island*. Dort konnte man eine Figur vor einem für damalige Zeiten unglaublich detaillierten Hintergrund bewegen, und das indirekte Steuerungskonzept fand ich unglaublich interessant.

Doch die folgenden Jahre sollten zunächst einmal Erfahrungen mit Spielekonsolen bringen. Erst 1995 entschieden sich meine Eltern, einen Computer zu erwerben (und damit meine Berufswahl maßgeblich zu beeinflussen). Eine meine ersten Aktionen auf diesem PC war die Installation von *Monkey Island II*, das in einer Ausgabe der Zeitschrift [Bestseller Games](http://de.wikipedia.org/wiki/Bestseller_Games) nur 9,99 DM kostete. Mit etwas Verspätung wurde so mein Interesse für die Adventures von LucasArts geweckt, denn bis dahin hatte ich nichts vergleichbares gespielt. Diese Mischung aus Rätseln und dem leichtfüßigen, augenzwinkernden Humor fesselte mich an den Rechner.

Dazu kamen viele witzige Einfälle, die mit dem Genre selber spielten, wie das Rätsel mit dem Einsiedler Herman Toothrot, der eine Antwort auf die Frage möchte, welche Farbe ein Baum hat, wenn er im Wald umfällt und ihn niemand dabei sieht. Der Spieler musste so lange auf die als Antworten angebotenen Farben klicken, bis schließlich "Alle gleichzeitig?" als Option erschien. Die richtige Lösung konnte man also nicht durch Nachdenken oder geschicktes Navigieren im Dialog erhalten, sondern einfach durch stupides Klicken auf irgendwelche Farb-Antworten. Die immer aberwitzigeren Optionen und die entsprechenden Reaktionen von Herman Toothrot machten das Rätsel aber zu einer sehr unterhaltsamen Angelegenheit. Diese und andere Szenen haben sich so tief im popkulturellen Gedächtnis eingegraben, dass wenn darauf angesprochen fast jeder Computerspieler einen entrückten Blick annimmt und selig "Ja, damals" murmelt.

Mit dieser Erfahrung gesegnet und auf der Suche nach ähnlichen Spielehöhepunkten holte ich die nächsten Jahre alle die Adventures nach, mit denen LucasArts die erste Hälfte der 90er Jahre geprägt hat: *Indiana Jones IV*, *Day of the Tentacle* (mein bis heute Alltime-Favorite des Genres), *Sam & Max*, *Full Throttle*, *The Dig* - allesamt Spiele, die auf einer immer weiter entwickelten Engine namens [SCUMM](http://de.wikipedia.org/wiki/Script_Creation_Utility_for_Maniac_Mansion) basierten. Teil 3 der Serie, *The Curse of Monkey Island*, sollte schließlich das letzte Spiel von LucasArts sein, das diese Engine verwendet. Mit einer überzeugenden, hochaufgelösten Comicgrafik und dem von den Vorgängern gewohnten hohen Standard in Story, Witz und Rätseln konnte ich erneut begeistert und stundenlang an den PC gefesselt werden.

Danach folgte der große Umbruch in der Adventure-Welt: SCUMM wurde aufs Altersteil gesetzt, Pixelgrafik gab es nicht mehr. Die bei *Grim Fandango* eigentlich gut funktionierende 3D-Technik wirkte jedoch in *Flucht von Monkey Island* nach der detaillierten Cartoongrafik des dritten Teils deplatziert, und die Steuerung mit Tastatur oder Gamepad brachte einige Probleme mit sich. Der eigentliche Grund, weshalb ich das Spiel schließlich entnervt zur Seite legte, war jedoch ein derber Bug: Auf Lucre Island konnte ich in eine Ecke hinter einer Parkbank laufen, wo mir dann ein Bewohner der Insel mit schlechter KI den Rückweg versperrte. Dies war dann der Tropfen, der das Fass zum Überlaufen und mich zum Abbrechen des Spiels brachte, obwohl zumindest die Story an die Qualitäten der Vorgänger anknüpfen konnte.

Viel besser machte es nun der fünfte Teil, [Tales of Monkey Island](/blog/2010/09/11/tales-of-monkey-island/). Nachdem mich die *Sam & Max*-Fortsetzungen vor allem durch das Rätseldesign nicht ansprachen, wurde nun dank der Mitarbeit von Ron Gilbert der Standard der ersten drei Teile der Serie wieder erreicht. Und wie es vor 15 Jahren *Monkey Island II* schaffte, mich überhaupt erst dem Adventure-Genre näher zu bringen, so hat nun der fünfte Teil nach vielen Enttäuschungen dafür gesorgt, dass ich wieder Spaß an Adventures habe. Und solche einschneidenden Erfahrungen haben nur sehr wenige Games bei mir bewirkt - etwas besseres kann über ein Spiel nicht gesagt werden.

P.S.: Einer der Gründe, weshalb ich den ersten Teil der [Pirates of the Carribean](/blog/2003/09/04/fluch-der-karibik/)-Serie so gemocht habe, ist die Anlehnung des Settings an die *Monkey Island*-Reihe - wobei Ron Gilbert als kreativer Kopf hinter dem Spiel zugibt, von der Disneypark-Attraktion inspiriert worden zu sein, welche die Vorlage für die Filme ist. Doch egal wer hier von wem kopiert hat, die Atmosphäre beider Werke ähnelt sich so sehr, dass ein Spaßvogel aus dem Film einen [Trailer für einen *Monkey Island*-Film](http://www.youtube.com/watch?v=_unbVaCe8a4) erstellt hat.
