---
title: "Scrum und Schokolade"
date: "2008-03-10T21:21:36"
categories: [gedacht]
---

Eigentlich dient der [Scrumprozess](http://de.wikipedia.org/wiki/Scrum) ja zur agilen Softwareentwicklung, aber nach meinem Geburtstag stehe ich nun vor einem Problem, welches ich mit den gelernten Mitteln aus der Projektarbeit lösen will: Geschätzte drei Kilogramm Schokolade türmen sich auf meinem Tisch auf, und ich muss jetzt entscheiden, wie ich dieses Backlog abarbeite.

Als Product Owner ist es mein erstes Ziel, dass die Schokolade so schnell und effizient wie möglich vernichtet wird. Da ich alle Sorten gleich gern esse, ergibt sich die Priorität ganz automatisch aus der Mindest-Haltbarkeit der Produkte. Glücklicherweise bin ich in meiner Rolle als Team sehr ehrgeizig und verspreche mir als Product Owner, dass ich alle Schokolade aus dem Backlog in der nächsten Iteration schaffen werde.

Damit wäre die Sprintplanung abgeschlossen. In den kommenden 30 Tagen werde ich das Team, also mich, als Scrum-Master bei den täglichen Scrum-Meetings leiten und darauf achten, dass die geplanten Ziele erreicht werden (3kg Schokolade in 3kg Hüftspeck zu verwandeln). Als Erstes nehme ich mir die Packung [Chez Hachez](http://www.hachez.de/main.php?typ=artikel&id=82) vor, die mir eine liebe Freundin geschenkt hat, und schätze den Restaufwand auf einen Tag. Ob ich meine Ziele erreiche, auf welche Probleme ich stoße und was sich aus Review und Retrospektive ergibt - dazu später mehr an dieser Stelle!
