---
title: "The A-Team"
date: "2010-07-31T23:33:36"
categories: [gesehen]
---

*USA (2010)
Regie: Joe Carnahan
Darsteller: Liam Neeson (John "Hannibal" Smith), Sharlto Copley (Murdock), Bradley Cooper (Templeton "Faceman" Peck), Quinton "Rampage" Jackson (B.A. Baracus), Jessica Biel (Charisa Sosa), Patrick Wilson (Lynch), Gerald McRaney (General Russell Morrison), Brian Bloom (Brock Pike) und andere Serienhelden und -bösewichter*
[Offizielle MySpace-Seite](http://www.ateam-derfilm.de/)

Am Donnerstag fand in Berlin parallel in mehreren Kinos die Deutschlandpremiere des *A-Team*-Films statt. Ich hatte das Glück, über einen Freund eine Karte im Cubix zu ergattern, in dem vor Filmstart auch kurz die sich auf Promotiontour befindenden Hauptdarsteller vorbeischauten und sich und den Film in den Himmel lobten.

Diese spielen in der Kinoneuauflage der 80er-Jahre-TV-Serie eine kleine, vierköpfige Spezialeinheit des amerikanischen Militärs, die bei einem Auftrag des CIA im Irak hintergangen wird und im Gefängnis landet. Doch Hannibal als Anführer und Stratege der Gruppe, der immer einen Plan parat hat, gelingt der Ausbruch und nachdem er sein Team ebenfalls befreit hat machen sich die Vier daran, den Verrat aufzudecken und ihre Akten reinzuwaschen...

Nun wurde also eine weitere TV-Kultserie einer Frischzellenkur unterworfen und fit für die große Leinwand gemacht. Dies äußert sich vor allem in einer neuen Besetzung und der Anpassung der Action an den aktuellen State-of-the-Art: Schnelle und hektische Schnitte, CGI-Effekte und ein deutlich höherer Materialaufwand sind die aus Produzentensicht wohl unverzichtbaren Elemente eines modernen Blockbusters.

Viele andere Aspekte des Originals wurden aber beibehalten. Da ist neben der klassischen Figurenzeichnung und -konstellation an vorderster Stelle die gnadenlos bis ins Absurde übertriebene Action und Handlung zu nennen. Mit einem Panzer aus einem Flugzeug abzustürzen, einen überdimensioniertes Hütchenspiel mit Containern im Frachthafen zu spielen und Dollarnoten-Druckplatten von Saddam zu stehlen sind nur ein paar Beispiele, die die erfolgreiche Portierung dieser Aspekte der Serie aufzeigen. Zudem gibt es viele Verweise auf das Original oder deren Darsteller: Der CIA-Gegenspieler trägt den Namen Lynch, bei der Befreiung von Murdock aus der Nervenklinik läuft der Vorspann der TV-Serie, in dem allerdings der Rollenname des Murdock-Schauspielers Dwight Schultz in StarTrek TNG, Reginald Barclay, eingeblendet wird.

So weit könnte man der Leinwandadaption also einen Erfolg attestieren. Doch leider ist aus diesen Zutaten kein guter Film geworden. Das liegt zum Einen daran, dass die Serie aus heutiger Sicht nicht mehr als eine verklärte Kindheitserinnerung ist. Da sich die Verfilmung eng an das Original hält, gilt dies ebenso für diese. Die Auffrischungen an aktuelle Sehgewohnheiten und den Zeitgeist durch Hinzunahme der CIA als allmächtigen Regierungs-Gegenspieler und des Handlungsteils während des Irakkriegs sind dabei eher kontraproduktiv, da sie zu inkonsequent eingesetzt werden. Der Film bleibt mittendrin stecken zwischen ironischer Übertreibung und Annäherung an die Realität.

Dazu bei trägt auch die unmotivierte weibliche Hauptrolle, verkörpert von Jessica Biel. Ihr Anteil an der Handlung ist unbedeutend, aber mit ihrer Beziehung zu Faceman zerstört sie dessen Funktion innerhalb des Teams als Ladykiller und nimmt die von der Serie so geliebte Leichtigkeit - nach der Episode ist alles so wie immer, keine Beziehung dauert längert - aus dem Film. *The A-Team* nimmt sich an Stellen wie dieser zu ernst, und die fehlende Unbeschwertheit verhindert, dass aus dem TV-Klassiker ein Kino-Highlight wurde.

Fazit: Eine aus heutiger Sicht trashige Kultserie aus den 80ern wurde behutsam in einen Kinofilm transformiert; viele Details und Anspielungen werden vor allem Fans des Originals erfreuen. Doch die Mischung aus der massiven Übertreibung des Originals und den Annäherungen an Zeitgeist und modernen Sehgewohnheiten geht nicht auf; der Film unterhält zwar in seinen zwei Stunden, ist aber noch schneller verdaut und vergessen.
