---
title: "Escapado im Cassiopeia"
date: "2008-05-27T21:22:28"
categories: [gehört,gewesen]
---

(Gute) Hardcore-Bands, die auf deutsch <del datetime="2008-05-27T19:26:04+00:00">singen</del> schreien, gibt es ja leider nicht viele. Also habe ich die Chance genutzt, die rühmliche Ausnahme [Escapado](http://www.escapado.com/) bei mir um die Ecke im [Club mit dem schlechtesten Kicker der Stadt](http://www.cassiopeia-berlin.de/) für schlappe 8 Euronen zu sehen. So billig bin ich seit einem Deichkind-Konzert für 11DM anno 2000 nicht mehr davon gekommen.

Zudem gab es zwei lokale (Hardcore-/Progressive-) Vorbands, die leider den Escapado-Auftritt auf die für die arbeitende Bevölkerung unglückliche Zeit Sonntag abend kurz vor Mitternacht verzögerten. Von weitem kaum auseinander zu halten, war die erste Band [Laura Mars](http://www.myspace.com/lauramarshq) deutlich besser als die [Nummero Zwo](http://www.itisimperative.de/); doch zumindest hatte niemand Probleme mit dem Sound und auch aufgrund der sehr guten Lüftung kann man das Cassiopeia als Konzert-Location nur empfehlen.

Zehn vor Zwölf kamen dann die vier Mannen von Escapado auf die Bühne und zeigten schnell den Unterschied zu ihren Vorgängern auf. Das tragende Gitarrengeschrammel, die zwischen intensivem Gesang und Geschrei wechselnde Stimme und die erprobte Bühnenerfahrung inklusive Rumpoken in der ersten Reihe - da macht den Nordlichtern so schnell niemand etwas vor. Nach vier, fünf Liedern von der aktuellen Platte (die ich nicht kenne, die mich aber auch nicht vom Hocker rissen) gingen sie dann schnell zu den "alten" Songs von *Hinter den Spiegeln* über und heizten das Publikum ordentlich auf. Nach nur einer Stunde inklusive Zugabe war das Konzert dann aber schon zu Ende, so dass ich noch einige Stunden Schlaf vor der neuen Arbeitswoche tanken konnte.

Wer Escapdado also noch nicht gesehen hat und auf Hardcore steht, dem lege ich ein Konzert der Band ans Herzen. Noch ist das Preis-/Leistungs-Verhältnis einfach genial!
