---
title: "Ab die Post"
date: "2005-09-04T21:31:05"
categories: [gelesen]
---

... heißt der kürzlich auf deutsch erschienene, neueste Scheibenweltroman von Terry Pratchett. Da ich alle anderen Bücher der Serie schon im Regal stehen habe, bin ich am Erscheinungstag los und habe mir das Buch bei Thalia gekauft. Amazon ist ja ganz nett und der Bücherversand auch kostenlos, aber man weiß vorher nie, welche Schäden die Verpackungsmaschinen hinterlassen. Da begutachte ich den Gegenwert für die 20€ doch lieber persönlich vor dem Kauf.

Da der gute Josh Kirby je leider verstorben ist, stammt das Umschlagsbild wieder von Paul Kidby, der bis jetzt jedoch leider nicht die Qualität seines Vorgängers erreicht. Während Kirby es verstand, eine Szene aus dem Buch zu nehmen und ein Gemälde mit einer Vielzahl von Details zu schaffen, sind Kidbys Bilder meist sehr plakativ auf einen Aspekt des Buches ausgerichtet und langweilen mich auch aufgrund der realistischeren Darstellung. Dafür ist die Übersetzung des Titels aber diesmal gelungen (im Original "Going Postal").

Im Buch selber überrascht Terry Pratchett diesmal mit der Einteilung in Kapitel - und die deutsche Ausgabe mit einem fehlendem Inhaltsverzeichnis. Ob dies nun eine sinnvolle Neuerung ist oder nicht mag ich nicht entscheiden. Trotzdem habe ich mich dabei erwischt, das Buch kapitelweise zu lesen und nicht wie bisher bis zum nächsten großen Absatz. Auf die Kurzinformationen über das Kapitel unter dessen Überschrift kann ich dagegen gut verzichten, da sie in mir keinerlei Spannung aufbauten und ich sie spätestens nach einer Seite meist schon wieder vergessen hatte.

Ansonsten ist *Ab die Post* für mich der beste Scheibenweltroman seit *Der Zeitdieb*. Dies ist alleine schon in der Thematik begründet: Die "Klacker" genannte Nachrichtenübermittlung auf der Scheibenwelt ist eine Karikatur auf die gesamte IT-Branche, und diesmal bekommt auch der Neoliberalismus in Form der neuen Klacker-Betreiber von Pratchett sein Fett ab. Es ist schön zu beobachten, wie Pratchett bestimmte Themen in mehreren Büchern kontinuierlich aufbaut, um sie dann plötzlich und unerwartet zum Hauptthema eines Romans zu machen. Diese Kontinuität ist es, welche mich jedes neue Buch der Serie verschlingen lässt.

Denn ansonsten verläuft die Story in gewohnten "Scheibenwelt"-Bahnen: Ein Verlierer oder unfreiwilliger Freiwilliger wird für eine Aufgabe auserkohren, die eigentlich viel zu groß für ihn ist. Doch die Handlung bekommt immer eine eigene Dynamik nach Pratchetts Prinzip, dass eine Rolle ihren Träger formt. Am Ende geht dann schließlich alles gut aus, weil es immer Lebewesen auf der Scheibenwelt gibt, die dieses Rollendenken abstoßen können und so am Ende triumphieren.

Damit aufgrund der vielen neuen Figuren eine Verbindung zur bestehenden Scheibenwelt erhalten bleibt, dürfen neben einem kurzen Auftritt der Wache auch Erzkanzler Ridcully und Ponder Stibbons in mehr oder weniger handlungsrelevanten Szenen ins Geschehen eingreifen (und eine schöne Anspielung auf den Herrn der Ringe liefern). Alles in allem also ein gelungener Scheibenwelt-Roman, der mir vor allem aufgrund seiner Anspielungen auf das aktuelle Weltgeschehen gefallen hat!
