---
title: "Der Wixxer"
date: "2004-06-03T00:00:01"
categories: [gesehen]
---

*Deutschland (2004)
Regie: Tobi Baumann
Darsteller: Oliver Kalkofe (Chief Inspector Even Longer), Bastian Pastewka (Inspector Very Long / Rosenverkäufer), Tanja Wenzel (Miss Pennymarket), Thomas Fritsch (Earl of Cockwood), Eva Ebner (Miss Drycunt), Christoph Maria Herbst (Butler Hatler), Olli Dittrich (Dieter Dubinsky), Anke Engelke (Doris Dubinsky), Thomas Heinze (Rather Short / Der Wixxer), Antoine Monot jr. (Der taube Jack), Oliver Welke (Dr. Brinkman), Lars Rudolph (Smeerlap), Andre Meyer (Pommi), Daniel Steiner (Fritti), Wolfgang Völz (Sir John), Die Wildecker Herzbuben, Achim Mentzel, Günter Jauch und andere Londoner Verbrecher*
[Offizielle Homepage](http://www.weristderwixxer.de/)

Die Londoner Unterwelt ist geschockt: Ein maskierter Verbrecher namens "Der Wixxer" ermordert immer mehr seiner Kollegen mit dem Ziel, die Herrschaft über das Verbrechersyndikat vom Earl of Cockwood zu übernehmen. Doch Mord sieht Scotland Yard gar nicht gerne und setzt deshalb das Ermittlerduo Even Longer und Very Long auf den Fall an. Während Even Longer seine Ermittlungen im Blackwhite Castle, dem Schloss des Earl of Cockwood, führt, muss Very Long den wichtigen Zeugen Dieter Dubinsky aus Bitterfeld beschützen....

Bevor ich mit meiner Einschätzung des Films beginne, muss ich gestehen, dass ich weder jemals einen der legendären Edgar-Wallace-Filme gesehen habe noch das Frühstyxradio kenne, auf dessen Vorlagen diese Parodie basiert. Ich habe mich jedoch ein wenig schlau gemacht nach dem Kinobesuch und kann sagen, dass es eigentlich nichts an meiner Meinung über "Der Wixxer" ändert, selbst wenn es wichtige Informationen sind und dieses Wissen das Erlebnis des Films sicherlich steigert.

Aber fangen wir von vorne an. "Der Wixxer" sieht sich in erster Linie als Parodie und hat dafür ähnlich wie Bullys [Der Schuh des Manitu](/blog/2001/08/15/der-schuh-des-manitu/) eine erfolgreiche Filmserie der Wirtschaftswunderjahre unserer Republik als Vorlage. In den Edgar-Wallace-Krimis ging es damals um Londoner Scotland-Yard-Kommisare, die es mit den größten Verbrechern der Unterwelt aufnahmen. Diese hatten meist sehr sprechende Namen wie der "Frosch mit der Maske" oder "der Mönch mit der Peitsche", was das Autorenduo Kalkofe/Welke mehr als einmal zum Anlass nimmt um sie so richtig durch den Kakao zu ziehen - wenn z.B. der Frosch tatsächlich ein Kermit in Menschengröße ist, die Bitterfelder Dubinskys (Anke Engelke und Oliver Dittrich) den eben genannten Mönch mit anderen Superverbrechern verwechseln (alle Wallace-Originale) oder der Earl of Cockwood meint, dass ein Mönch ohne Peitsche einfach nicht dasselbe ist. Mit den sächselnden Bitterfeldern bin ich auch schon bei einem meiner Kritikpunkte am Film: Das man nach 14 Jahren immer noch mit den selben Ossi-Witzen aufwartet ist schon erbärmlich, weshalb für mich die beiden Rollen einfach überflüssig sind.

Generell sieht man dem Film jedoch an, dass es ihm an guten Schauspielern fehlt. Die versammelte erste Mannschaft der deutschen Komiker spielt ihre Rollen routiniert, jedoch ohne Aha-Effekte (außer natürlich der Hitler-Parodie) - der einzige Sinn und Zweck der Figuren ist die Parodie von so vielen Elementen der alten Filme wie möglich. Doch genau hier liegt dann die Stärke des Films: Von den Namen (Miss Pennymarket) über die Spurensuche am Tatort, der Verfolgungsjagd auf Fahrrädern (!), den unmöglichen Familien- und Besitzverhältnissen der englischen Oberschicht bis hin zu der Auflösung wird wohl jeder Aspekt der Originale gekonnt auf die Schippe genommen.

Der Film bietet dem Zuschauer jedoch nicht nur die oberflächliche Story an; ständig passiert im Hintergrund irgendetwas und an jeder Ecke findet man als aufmerksamer Beobachter viele kleine, witzige Details, von denen man beim ersten Schauen wohl gar nicht alle erfassen kann. Das Schloß Blackwhite Castle ("das letzte englische Schloss in Schwarz-Weiß" - die alten Wallace-Filme waren alle in SW gedreht) mit seinen Mops-Statuen an allen Ecken ist einfach herrlich englisch (und hat einen "bunten" Flügel als Zugeständnis an die Frauen - "Sie wissen nicht wie schwer es ist, sich in Schwarz-Weiß zu schminken"), die Autos wirken zeitgemäß, der Hafen kommt so richtig verkommen daher - die Ausstattung und die Produktion sind scheinbar die Stärken deutscher Parodien.

Neben einer fast schon obligatorischen DSDS- und Dieter-Bohlen-Anspielung (ein Casting von entführten Frauen für den Girl-Group-Schmuggel - leider zog die Befreiung der "No Angels" im Film nicht) werden aber auch schon einmal über Ministerpräsidenten oder Hitler Witze gemacht, wobei der Butler Hatler für mich das Highlight des Films war. Während trotz der hohen Gagdichte viele Witze einfach nicht funktionierten (wobei trotz der Namen erfreulicherweise auf Fäkal- und pubertären Humor verzichtet wurde), war jeder Auftritt von Christoph Maria Herbst einen Lacher wert - endlich wurde eines der letzten Tabus der deutschen Comedy gebrochen!

Neben den Komikern haben sich aber auch andere Fernseh-"Promis" in den Film verirrt, die offensichtlich alle ihre Parodien in Kalkofes Mattscheibe als das angesehen haben, was sie sind, und sich damit recht witzige Rollen verschafften. Von den arrivierten Schauspielern bekommt leider keiner die Chance, wirklich zu glänzen, selbst wenn zumindest alle Rollen optisch gut besetzt sind. Dass man trotzdem wie schon bei Bully kurz vor Ende unbedingt singen muss will ich jedoch nicht gutheißen...

Fazit: Wieder einmal zeigt die deutsche Comedy was sie wirklich kann, nämlich Parodien. Dass nicht alle Witze und Ideen ganz taufrisch sind und die Schauspielleistungen den Namen nicht verdienen kann man verzeihen, weil trotzdem noch mehr als genug Substanz übrig bleibt! Voraussetzung ist jedoch wie immer: Man muss den Humor von Kalkofe/Welke/Bastewka/Engelke/Dittrich mögen, um zu lachen. Ich habe mich jedenfalls köstlich amüsiert.
