---
title: "Spider-Man"
date: "2002-06-06T00:00:41"
categories: [gesehen]
---

*USA (2002)
Regie: Sam Raimi
Darsteller: Tobey Maguire (Peter Parker), Willem Dafoe (Norman Osborn), Kirsten Dunst (Mary Jane Watson), James Franco (Harry Osborn), Rosemary Harris (Tante May Parker), Cliff Robertson (Onkel Ben Parker), Richard C. Everbeck (Eddie Brock) und andere Comic-Figuren*
[Offizielle Homepage](http://www.spider-man-der-film.de/)

Peter Parker ist ein schüchterner junger Mann, der seit dem Tod seiner Eltern von Tante und Onkel aufgezogen wird. Bei einem Schulausflug wird er jedoch von einer genetisch aufgebohrten Spinne gebissen und muss bald feststellen, dass dies auch sein Erbgut verändert hat. Plötzlich braucht er keine Brille mehr, bekommt über Nacht Muskeln, kann Wände hinaufgehen und stark belastbare Spinnenfäden verschießen. Am Anfang noch darüber beunruhigt lernt er nach und nach mit seinen neuen Fähigkeiten umzugehen. Doch dann wird sein Onkel bei einem Überfall getötet und Peter nutzt seine Spinnensinne, um den Mörder zur Stecke zu bringen.

Fortan ist er in seinem selbsterstellten Kostüm Spider-man, der Held New Yorks, und kommt mit seinem alten Ego auch näher an Mary Jane heran, in die er verliebt ist. 
Doch jeder Superheld hat auch seinen Superschurken, in diesem Fall der Großindustrielle Harry Osborne, der sich selber einem Kraftverstärker-Experiment ausgesetzt hat und seitdem als der Grüne Kobold seine Feinde aus der Geschäftswelt ums Leben bringt. Doch im Kampf der beiden Supermenschen hat Osborne einen wichtigen Vorteil: Er weiß, wer unter der Maske des Spinnenmannes steckt...

Für mich gibt es nur zwei gute Comicverfilmungen: Zum Einen natürlich die beiden ersten Batman-Teile von Kultregisseur Tim Burton und dann noch der erste X-Men-Film von Bryan Singer. Alle 3 bestachen durch die äußerst düstere, und damit realistisch erscheinende Inszenierung einer eigentlich komplett irrealen Welt. Doch schon die ersten Trailer zu Spider-man zeigten, dass Sam Raimi den entgegengesetzten Weg gegangen ist, nämlich den der kunterbunten Kostüme, aber dafür eine klasse Besetzung verbuchen konnte. Also bin ich gleich am ersten Tag ins Kino gerannt und hier nun meine Kritik.

Wie der Splatterregisseur und der Charaktermime für diesen Film zusammengefunden haben, wird mir auf ewig rätselhaft bleiben, geschadet hat es auf jeden Fall nicht. Tobey Maguire verkörpert den pubertierenden Peter Parker ohne größere Anstrengungen, und auch William Dafoe ist sichtlich unterfordert - einen Teil seiner Dialoge darf er gar gänzlich von der Kobold-Maske verdeckt führen. Und da bin ich auch schon beim Hauptkritikpunkt: Die Kostüme sind kunterbunt, sehen nicht sehr realistisch aus und lassen in einigen Szenen echtes PowerRangers-Gefühl aufkommen. Dies unterstützen auch einige der Animationen, wo man dem Spinnenmann die Herkunft aus dem Computer eindeutig ansieht. Auch die Häuserschluchten New Yorks sind bei den Peter verfolgenden Kamerafahrten zu simpel dargestellt, um realistisch zu wirken - ein Comic bleibt doch ein Comic, auch im Kino.

Dafür nimmt sich der Film aber relativ viel Zeit zur Charakterentwicklung und dosiert die Action-Szenen sehr geschickt, so dass eigentlich nie Langeweile aufkommt. Ab und zu ein Druck auf die Tränendrüsen rundet schließlich den Gesamteindruck ab, dass sich dieser Film kaum Schwachpunkte leistet und so ziemlich jeden Kinogänger anspricht - so viele Amerikaner können sich doch nicht irren...

Fazit: Nicht die beste, aber auch nicht die schlechteste Comic-Verfilmung, die die ganze Familie anspricht und nicht langweilt - aber mehr auch nicht!
