---
title: "StarTrek X Nemesis"
date: "2003-01-20T00:00:41"
categories: [gesehen]
---

*USA (2002)
Regie: Stuart Baird
Darsteller: Patrick Stewart (Jean-Luc Picard), Brent Spiner (Data / Bevor), Tom Hardy (Shinzon), Jonathan Frakes (William T. Riker), Marina Sirtis (Deanna Troi), LeVar Burton (Geordi La Forge), Michael Dorn (Worf), Gates McFadden (Beverly Crusher), Ron Perlman (Viceroy), Dina Meyer (Donatra), Whoopi Goldberg (Guinan), Kate Mulgrew (Kathryn Janeway) und andere neu entdeckte Androiden*
[Offizielle Homepage](http://movies.uip.de/st-nemesis/)

Troi und Riker planen ihre Hochzeit auf Betazeth. Da Riker auch endlich ein eigenes Kommando übernommen hat, chauffiert Picard seine beiden Ex-Offiziere zum Abschied mit der Enterprise. Doch auf dieser Reise findet das Flaggschiff der Sternenflotte nicht nur die Überreste eines Vorgängers von Data (den man natürlich sofort wieder aufbaut), sondern wird auch mal schnell mit der Mission betraut, plötzliche Friedensgespräche mit den Erzfeinden der Föderation, den Romulanern, auf deren Heimatplanet zu führen. Dort angekommen stellt sich heraus, dass der gesamte romulanische Senat in einem Staatsstreich getötet und das Reich von den Remanern unter Führung von Shinzon übernommen wurde. Dieser stellt sich zu allem Überfluss als ein Klon von Picard heraus, der einst von Romulus verbannt wurde. Doch ist Shinzon Picard wirklich so ähnlich wie er behauptet? Kann man seinen Freidensbemühungen glauben und war es wirklich reiner Zufall, dass man den zerlegten Bruder von Data gerade jetzt fand...

Vier lange Jahre (und ein paar Wochen Starttermin-Verschiebungen hier in Deutschland) hat es gedauert, ehe endlich der lang erwartete 4. Film der TNG-Crew ins Kino kam, der nun leider auch der letzte (vielleicht der ganzen Serie) sein wird. Einiges von dem, was ich vorher hörte (Thema Romulaner, ein ST-fremder Regisseur, "gerade Filmnummer") erzeugte richtig Appetit auf den Film in mir, einiges andere schreckte aber auch ab (neue Rasse mit neuem Superraumschiff, extra viel Action, Hauptdarsteller schreiben am Drehbuch mit).

Also ging ich mit gespaltenen Gefühlen ins Kino, um meiner Lieblings-ST-Crew noch ein letztes Mal zuzusehen und kann zumindest behaupten, dass sie sich besser geschlagen hat als im Vorgänger. Dies liegt vor allem an der wieder etwas düsteren Story um die Romulaner und die Bewohner ihres Zwillingsplaneten Remus, die ständig in der Dunkelheit leben. Diese Gegebenheit nahm der Regisseur zum Anlass, fast alle Szenen ziemlich dunkel zu halten, wodurch die schon so nicht sehr noble NCC-1701-E noch viel schäbiger wirkt und das neue, megagroße, superstarke Raumschiff von Shinzon wie eine Kopie der Schatten aus Babylon 5 wirkt. Generell kamen mir die meisten Plot-Elemente ziemlich bekannt vor und so kann der Film mit nichts wirklich neuem oder überraschenden aufwarten - Picard bekommt sogar einen richtigen Kirk-Bösewicht-Endkampf. Da bleiben mir doch lieber die hervorragenden Drehbücher der Serie im Gedächtnis, wenn ich an TNG denke.

Brent Spiner hat sich jetzt endlich wie versprochen aus der Crew geschrieben, aber nicht ohne sich ein ziemlich großes Hintertürchen offen zu halten, doch gerade das Spiel von ihm und Patrick Stewart ist wie eh und je hervorragend, nur mussten mal wieder alle anderen Crewmitglieder darunter leiden. Dr. Beverly durfte kein einziges Wort sagen, Worf und Geordi waren nur zum Befehle-Ausführen da und Troi muss sich geistigen Vergewaltigungen aussetzen, "solange sie es noch aushalten kann". Dafür darf sich ihr künftiger Ehemann eine halbe Stunde lang in engen Röhren mit einem ziellosen Remaner rumprügeln, und verpasst dabei das Wichtigste. Als Ausgleich für diese schwache Rollenverteilung unter der Crew gibt es aber in der Startszene Anspielungen zu Hauf auf alte Episoden der Serie und Gastauftritte von Guinan, Janeway (als Admiral) und Wesley Crusher (sollte der nicht irgendwo im All als Reisender umherfliegen?). Als Bösewicht kann dafür Tom Hardy wirklich überzeugen und die Dialoge mit Picard sind anfangs das Highlight des Films, nur irgendwann verliert der junge Klon dann scheinbar die Übersicht über sein Handeln und alles läuft schief. Wenn die Föderation nur solche Feinde hätte wäre sie sicherlich glücklich (und dann könnte man auch Picard pensionieren, der ja nur Schiffe verschrottet!).

Tricktechnisch gehört der Film sicherlich zum Besten, was man an Weltraum-Action geboten bekommen kann (eine teilweise aufgerissene Brücke ist schon toll), aber ansonsten musste man scheinbar sparen. Von Romulus bekommt man nur einen Saal mit Ratsmitgliedern und 2 Schiffe zu sehen, andere Bewohner oder politische Gruppierungen scheint es nicht mehr zu geben. Von den Remanern sieht man auch nicht mehr als eine Hand voll und die Gänge ihres Raumschiffes sind leer wie die der Enterprise - hier hatte sogar die Fernsehserie mehr an Ausstattung zu bieten! Alles in allem hinterlässt der Film also auch hier gespaltene Gefühle.

Fazit: Der wahrscheinlich letzte StarTrek-Film ist leider auch der schwächste der geradzahligen Teile, leidet er doch an so vielen typischen Fehlern, die wir so ähnlich schon aus dem letzten Film kennen. Doch durch die teilweise interessante Story und das ansprechende Spiel der Hauptcharaktere kommt zumindest etwas Spannung und das TNG-Feeling auf, was den Film besser als den Vorgänger macht. Doch Vorsicht: Nur für Fans zu empfehlen!
