---
title: "Futurama: Die Ära des Tentakels"
date: "2008-09-15T22:15:53"
categories: [gesehen]
---

[Fünf Monate](/blog/2008/04/10/futurama-benders-big-score/) nach dem ersten Film ist endlich auch in Deutschland die zweite DVD der neuen Futurama-Film-Serie erschienen, die dank Amazon pünktlich am 12. bei mir war. Film Nummer Drei - Veröffentlichung der amerikanischen Version ist Anfang November - erwarte ich dann auf [Blu-Ray](http://www.futurama-area.de/index.php?newsid=88) in Full-HD.

Aber bis dahin heißt es weiterhin SD bei *Die Ära des Tentakels*, wenn auch im 1:78-Format. Der Film schließt nahtlos an den ersten Teil an, in dem ein riesiges Dimensionsloch in das Universum gerissen wurde. Dieses ermöglicht den Übergang in ein anderes Universum, welches von einem riesigen und unheimlich einsamen Tentakelwesen bewohnt wird. Als der liebeskranke Fry sich in dieses andere Universum hinüberbegibt, regt er damit das Tentakelwesen an, sich in unseres aufzumachen und alle Lebewesen mit seiner Liebe zu beglücken...

Im Vergleich zur ersten Film-Episode fällt die *Die Ära des Tentakels* storytechnisch leider total ab - zu ausgetreten sind die Pfade, auf denen sich die Handlung abspielt. Dafür ist diesmal das Gag-Level deutlich höher, vor allem die vielen kleinen Details im Hintergrund überzeugen. Trotzdem hatte ich die gesamte Zeit das Gefühl, nur eine Folge im Fernsehen zu sehen. Eine immerhin kurzweilige, aber dramaturgisch nicht auf Film-Niveau spielende Folge. Dazu fehlt deutlich ein zentrales Thema und vor allem ein roter Pfaden. Keine SciFi-Verarsche, nur ab und zu ein paar politische Spitzen, das ist einfach zu wenig für meine hohen Erwartungen an Futurama. Ein Glück, dass es noch Bender gibt, der anarchistisch wie immer den Film rettet.

An Bonusmaterial sticht diesmal neben ein paar Informationen aus der Produktion eine neue Episode heraus, die aus den Videosequenzen des [Futurama-Spiels](http://en.wikipedia.org/wiki/Futurama_(video_game)) zusammengeschnitten wurde. Bleibt zu konstatieren, dass *Die Ära des Tentakels* nicht so gut wie *Benders Big Score* geworden ist, aber zumindest anderthalb Stunden mit viel Witz überzeugen kann.
