---
title: "The Convoy"
date: "2012-02-18T20:54:18"
categories: [gesehen]
---

[Berlinale-Filmdatenblatt](http://www.berlinale.de/de/programm/berlinale_programm/datenblatt.php?film_id=20123849)

Ignat, ein Hauptmann der russischen Armee, ist ein harter Mensch - zu sich selbst wie zu allen anderen Menschen. Zudem gibt er sich die Schuld am Tod seiner Tochter und leidet unter schwerer Migräne, die zu Anfällen mit Halluzinationen führt. Nachdem er in einem solchen Anfall drei Jugendliche krankenhausreif geprügelt hat, wird er mit einem Sergeant auf Strafmission geschickt: Er soll zwei Deserteure ausfindig machen und zusammen mit dem Geld, welches diese haben mitgehen lassen, in ein Gefängnis in Moskau einliefern.

Der erste Flüchtling nimmt Ignat die Arbeit ab, indem er sich durch Suizid der schweren Strafe entzieht. Der zweite, das naive Muttersöhnchen Artyom, lässt sich jedoch trotz großer Angst vor der Rückkehr in die strengen Hierarchien der Armee widerstandslos festnehmen. Bei einem weiteren Migräneanfall von Ignat auf dem Moskauer Bahnhof entwendet der Sergeant jedoch das eingesammelte Geld, so dass der Hauptmann den Deserteur nicht abliefern kann ohne selbst in den Verdacht der Veruntreuung zu geraten. Also muss er im ihm verhassten Moloch der russischen Hauptstadt einen Weg finden, das Geld aufzutreiben und damit seine Mission zu beenden.

Was nun folgt ist eine Odyssee durch die dunkelsten Ecken der Stadt, durch Wohnungen von Schleusern und ihren Prostituierten, durch Reviere der korrupten Polizei und privaten Sicherheitsdienste - und immer wieder treffen sich die Wege in einer Wartehalle des Bahnhofs, von der es jedoch nicht weitergeht. *The Convoy* präsentiert dem Zuschauer einen Ausschnitt aus der Gesellschaft, der ausschließlich aus verdorbenen Menschen besteht, die vor keiner Anwendung von Gewalt zurückschrecken, um ihr Ziel zu erreichen. Geld ist das Schmiermittel, das diese düstere Welt zusammenhält und gleichzeitig Ursache für ihren Konfliktreichtum ist. Die Machtverhältnisse sind dabei diffus; fast scheint es als spielen alle Beteiligten *Stein, Schere, Papier* und wer eben noch die Oberhand besaß kann im nächsten Moment ein Opfer sein.

Ignat passt oberflächlich betrachtet ganz gut in diesen Bodensatz der Gesellschaft hinein, doch wendet er die Härte, die er ausstrahlt, auch konsequent an sich selber an und vermeidet so Gewalttaten gegenüber anderen Menschen. Trotzdem sind seiner Autorität als Mitglied des Militärs Grenzen gesetzt und mit jedem neuen Migräneanfall verschlechtert sich seine Position in dem Spiel, in das er bei der Ausführung seiner Mission geraten ist.

Das störrische Beibehalten seiner Strategie hat jedoch System bei Ignat. Wenn er in seiner beschränkten Kommunikation immer wieder stoisch die gleichen Sätze anwendet ("Ich werde mich nicht entschuldigen", "Du hast mich nicht verstanden"), dann zeugt dies auch von der später gegenüber seiner Frau geäußerten Angst, sich zu verändern, sich anzupassen, obwohl er selber weiß, dass er es muss, um weitere tragische Ereignisse wie den Tod seiner Tochter zu verhindern. Gleichzeitig ist er aber trotz aller Umwege erfolgreich in seinem Vorgehen und kann am Ende seine Mission abschließen.

An dieser Stelle, kurz vor dem Ende des Films, habe ich die Handlungen Ignats nicht mehr nachvollziehen können. So setzt er sich zwar dafür ein, dass Artyom nicht in das Gefängnis muss. Doch als er nichts dabei erreicht spricht er dem jungen Mann, der ihn in seinem tiefsten Inneren getroffen hat, Mut zu wider besseren Wissens, dass diesem im Moskauer Gefängnis ohne den Schutz eines Typen wie Ignat eine harte Zeit bevorsteht.

Dem Sergeant dagegen, der ihn in jeder möglichen Situation beraubt und betrogen hat, signalisiert er am Ende Gnade. Diese Szene, in welchem er versucht, sich nach dem Vorbild Artyoms humoristisch zu geben, zeugt zwar davon, dass Ignats harte Schale durchbrochen wurde, doch dass gerade der Sergeant unverdient Nutznießer davon wird hinterlässt einen bitteren Nachgeschmack.

Wie sein Ende hat mich der gesamte Film nicht überzeugen können, was vermutlich daran liegt, dass *The Convoy* mit seinen Figuren und Bildern so hart umgeht wie Ignat mit seinen Mitmenschen und damit einen deprimierenden Eindruck hinterlässt. Es gibt keinerlei Sympathieträger unter den wichtigsten Charakteren, allein mit Artyom mag der Zuschauer so etwas wie Mitleid entwickeln - eine Hoffnung, die zum Schluss konsequent enttäuscht wird. Wie die Figuren jedoch zu solchen Unsympathen werden konnten, das verschweigt der Film. Wer wie *The Convoy* von der russischen Filmförderung unterstützt werden will, darf wohl keine offene Kritik an den gesellschaftlichen Verhältnissen üben.

Da muss es reichen, dass sich die Figuren ausschließlich in Räumlichkeiten bewegen, die ebenso heruntergekommen sind wie sie selber. Ob es die Wartehalle des Bahnhofs ist, die Essenssäle der Armee oder das Revier der Polizei, der Umkleideraum des Gefängnisses (wo bis auf einen Haken alle weiteren fehlen) oder die Industrieanlage zu Beginn des Films - jede Einstellung des Films zeugt überdeutlich von einer Mangelwirtschaft, die Erinnerungen an die Zeiten des Kommunismus weckt. Unter diesem Mangel leiden alle Charaktere und er bestimmt auch ihr Verhalten; allein ein Ausbruch aus den Verhältnissen scheint nicht möglich, auch wenn es alle versuchen.
