on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload changed files to kingoli.net
        env:
          SFTP_HOST: w012899b.kasserver.com
          SFTP_USER: ${{ secrets.FTP_USER }}
          SFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u "$SFTP_USER","$SFTP_PASSWORD" "sftp://$SFTP_HOST" <<EOF
          set cmd:fail-exit yes
          set sftp:auto-confirm yes
          set net:max-retries 2
          set net:reconnect-interval-base 5
          set net:timeout 20
          mirror --reverse --delete --verbose ./docs/ .
          bye
          EOF
