---
title: "Angemessene Reaktionen"
date: "2009-03-11T18:00:37"
categories: [gedacht,gesehen]
---

Muss denn erst ein Amoklauf passieren, damit ein Musiksender Musik spielt? [MTV](http://www.mtv.de/news/Tiefe-Betroffenheit/20047403) hat [aus aktuellem Anlass](http://www.netzeitung.de/vermischtes/1296100.html) alle Sendungen des Tages abgesagt und spielt ausschließlich dem Thema angepasste Videos. Keine moderierten Shows, keine billigen, untertitelten US-Import-Formate, kein Zeichentrick und keine Handy-Download-Werbung stören das Programm - nur ein durchlaufender Kondolenz-Text und im Videotext der Verweis auf ein eingerichtetes Diskussionsforum. Damit tut der Sender ausnahmsweise einmal das, was ich von ihm erwarte. Bin ich also kaltherzig und fehlt mir das Mitgefühl, wenn ich der Situation eine positive Seite abgewinne? Schließlich habe ich schon lange nicht mehr so viele Musikvideos am Stück sehen können...

**Update**

Die ganze Aktion ist eine zweieinhalbstündige Endlosschleife; die Videos wiederholen sich gerade in exakt derselben Reihenfolge. Auf VIVA läuft zumindest eine andere Auswahl, also kann man sogar zappen.
