---
title: "Herr Schmidt sieht fern"
date: "2006-01-10T11:54:47"
categories: [gesehen]
---

Der [WDR](http://www.wdr.de) feiert seinen 50. Geburtstag momentan mit diversen Sendungen, welche die Highlights des Senders Revue passieren lassen. Während bei Götz Alsmann am Sonntag in "Mit Götz, Maus und Melone" die Kindersendungen im Mittelpunkt standen, hatten sich gestern Elke Heidenreich und Harald Schmidt zusammengesetzt, um die besten WDR-Shows in ["Herr Schmidt sieht fern"](http://www.wdr.de/comedy/sendungen/schmidtfern.phtml) zu präsentieren.

Leider scheinen jedoch diese Rückblicke darauf hinzudeuten, dass die große Zeit des WDR vorbei ist und man sich im Licht der alten Erfolge sonnt. Anders ist dieser Doku-Beitrag nicht zu erklären, welcher Ausschnitte aus alten und neueren Shows mit einem anderhalbstündigen Dialog der beiden Gastgeber zu einem schwer verdaubaren Gesamtbild mixte. Dies lag zum Einen an Schnitt und Regie, denn die eingespielten Aufzeichnungen wurden meist mit einer durchgehenden und nicht immer passenden Hintergrundmusik versehen und die Dialogfetzen von Frau Heidenreich und Herr Schmidt gingen teilweise unverständlich in die Einspieler über.

Das Gespräch selber konnte auch nicht überzeugen. Die beiden Moderatoren bemühten sich zwar, mit eigenen Anekdoten die ungünstige Auswahl der Beiträge etwas aufzulockern, jedoch kam nie ein richtiger Dialog zu Stande. Dazu fehlte einfach die Chemie zwischen Frau Heidenreich und Harald Schmidt, was beim Thema Jürgen von der Lippe gut zu erkennen war. Teilweise wussten die beiden Moderatoren zu einigen eingespielten Ausschnitten auch gar nichts zu sagen. So ging der Sendung am Ende bei den Aufzeichnungen von Shows mit Harald Schmidt oder Elke Heidenreich deutlich die Luft aus.

Wenn dies also ein Abgesang auf den WDR sein sollte, dann ist er traurigerweise gelungen. Aber vielleicht war es auch nur eine schlecht entworfene und ungünstig geschnittene Dokumentation und wir sehen Harald Schmidt bald wieder in neuem Studio und mit alter Klasse.
