---
title: "Tales of Monkey Island"
date: "2010-09-11T22:08:44"
categories: [gespielt]
---

Telltale Games, die Firma hinter dem fünften Teil der *Monkey Island*-Serie, wurde 2004 von ehemaligen LucasArts-Mitarbeitern (u.a. Dave Grossman) gegründet, um ihrem alten Arbeitgeber zwei Dinge zu beweisen: Zum Einen, dass das Genre der Adventures nicht tot ist, und zum Anderen, dass man Spiele nicht nur in Pappkartons an der Ladentheke verkaufen, sondern auch in kleineren Häppchen über das Internet vertreiben kann. Mit *Tales of Monkey Island* haben sie es nun geschafft, auch mich von diesen Ideen zu überzeugen.

Zuvor hatte ich zwar diverse Demos zu den *Sam & Max*-Fortsetzungen ausprobiert, aber der Funke wollte nie richtig überspringen. Für *Tales of Monkey Island* hat sich die Zusammenarbeit mit dem kreativen Kopf hinter den Vorgängern, Ron Gilbert, ausgezahlt. Sowohl Rätsel, Grafikstil als auch Humor treffen genau den Ton der Vorgänger, und so stellte sich schnell der Suchtfaktor ein, wie ich ihn lange nicht mehr bei einem Spiel verspürt habe.

Guybrush Threepwood, Mighty Pirate™, hat es diesmal fast geschafft, den Zombiepiraten LeChuck zu besiegen. Mit einem nicht ganz nach Anleitung hergestellten Voodooschwert wurde jedoch nur die Bösartigkeit von LeChuck abgespalten, die sich nun als infektöse Wolke über die Karibik verbreitet und alle Piraten infiziert, die damit in Kontakt kommen. Zudem hat ein Teil von LeChuck Besitz von Guybrushs Hand ergriffen, so dass dieser nun mehrere Probleme lösen muss.

Neben den üblichen Aufgaben des Findens eines Schiffes und Rettens seiner Frau Elaine muss er einen magischen Voodoo-Schwamm finden, der die bösartige Wolke aufsaugen kann. Dabei stört ihn jedoch der verrückte, französische Wissenschaftler Marquis de Singe, eine Piratenjägerin namens Morgan LeFlay, seine eigene bösartige Hand und nicht zuletzt der wieder menschgewordene und nur noch auf gute Taten lauernde LeChuck.

Bis der Spieler alle diese Aufgaben erfüllt hat, muss er sich durch fünf Episoden rätseln, die jeweils an unterschiedlichen, in sich abgeschlossenen Plätzen spielen. Ein paar der Handlungsorte werden in späteren Episoden wieder besucht, ohne dass dies negativ als Locationrecycling auffallen würde. Ganz im Gegenteil passt es jeweils sehr gut in die Geschichten, die aufeinander aufbauen und einer Storyline mit großem Finale folgen, aber dank kurzer Einführungen am Kapitelanfang und einer nicht beeinflussbaren Inventarübernahme zwischen den Episoden auch unabhängig voneinander gespielt werden können.

Ein wenig hat mich die technisch strikte Trennung zwischen diesen Episoden auf der PS3 gestört. Denn obwohl ich nur die gesamte Staffel zusammen kaufen konnte, landeten doch fünf einzelne Icons in meiner Spieleliste; auch die Trophäen sind voneinander getrennt. Dies bedeutet leider, dass man nach dem Ende einer Episode zurück ins Menü muss, um die nächste zu starten. Das Spielmenü sieht zwar bei allen Episoden gleich aus, aber Einstellungen und Savegames werden nicht übergreifend genutzt. Ein kleineres Ärgernis dagegen sind die Buttons im Menü, die so gestaltet sind, dass man nur schwer erkennt, welcher gerade ausgewählt ist.

Technisch gibt es ansonsten nicht viel auszusetzen. Die Steuerung mit dem PS3-Gamepad ist deutlich angenehmer als mit der Maus-/Tastatur-Kombination am PC, welche ich in einer Demo angetestet habe. Die Grafik kommt über den Status zweckmäßig nicht hinaus, aber der Stil der Serie wird sehr gut getroffen und alles für die Rätsel notwendige lässt sich ohne Probleme erkennen, so dass dies nicht weiter in die Waagschale fällt. 

Mindestens vier, fünf Stunden Spielspaß habe ich pro Episode investieren müssen. Bei einem Preis von 17,99€ für die gesamte Staffel ist die ein hervorragendes Preis/Leistungs-Verhältnis. Der Schwierigkeitsgrad ist nicht zu hoch; nur ab der dritten Episode sammeln sich am Ende ein paar Rätsel, bei denen der eine oder andere Hinweis nicht schlecht gewesen wäre. Doch zum Einen kann im Menü aktiviert werden, dass Guybrush oder andere Figuren ab und zu einen Fingerzeig für einen nächsten Schritt geben, und zum Anderen stellt Telltale Games auf der Homepage zu den Spielen auch Walkthroughs bereit, so dass Gelegenheitsspieler - wie ich es im Sommmer war - nicht frustriert aufgeben müssen.

Für diese ist die Episodenform und auch die Aufteilung innerhalb der einzelnen Kapitel gut geeignet. Es gibt immer wieder Spielsituationen, in denen Guybrush nur in einem begrenzten Areal - z.B. auf dem Deck seines Schiffes, oder in der Bar 41 - agieren kann. Dort kann er durch Dialoge oder Benutzen von Gegenständen andere Charaktere bewegen oder beeinflussen und muss so bestimmte Ziele erreichen. Die möglichen Kombinationen mit dem Inhalt des Inventars sind dabei begrenzt und unnötiges Umherlaufen auf der Suche nach Rätseln entfällt, so dass ich immer wieder motiviert wurde, weiterzuspielen.

Ein typisches Problem fast aller Adventures hat sich aber auch in *Tales of Monkey Island* eingeschlichen: Die Inkonsequenz im Lösen von Puzzles. Ein Beispiel: Der von seinem Voodoofluch befreite LeChuck soll mit einem Stab ein Artefakt aus seiner Befestigung befreien, da Guybrush zu schwach für diese Aufgabe ist. Wenn LeChuck darauf angesprochen wird, antwortet er, dass Guybrush das schon alleine schafft. Gibt ihm Guybrush allerdings den Stab, dann erledigt er die Aufgabe. Es gibt allerdings keine Systematik im Spiel: Mal muss ich einen Charakter ansprechen, mal ihm einen Gegenstand geben. Ich würde mir wünschen, dass entweder beides möglich wäre oder zumindest die Kommentare nicht von der eigentlichen Lösung ablenken. Solche falschen Fährten halten sich aber im Spielverlauf in Grenzen, und irgendwie habe ich mich daran gewöhnt, beides auszuprobieren.

In bester *Monkey Island*-Tradition des Beleidigungsfechtens gibt es diesmal einen Piraten-Grimassenwettbewerb, der sich innerhalb des Spiels sogar zu einem Running Gag entwickelt. Desweiteren tauchen viele bekannte Charaktere (Voodoo Lady, Stan, Murray) aus und Verweise auf die alten Teile auf (allein die Cocktails im Club 41: Blood Island Volcano Shots, Phatt Island Phuzzy Nostril, Scabb Island Sling, Tri-Island Tuna Colada). Man darf verschiedenen Charakteren Lederjacken anbieten und natürlich diese auch mit dem Satz "Ein dreiköpfiger Affe" ablenken.

Gerade diese Stringenz der Serie macht *Tales of Monkey Island* nicht nur zu einem hervorragenden *Monkey Island*-Spiel, sondern auch zum sicherlich besten Adventure, das gerade am Markt verfügbar ist. Ich habe schon lange nicht mehr so viel Spaß beim Spielen eines Adventures gehabt und hoffe auf weitere Spiele dieser Qualität von Telltale Games, um mein wiedererwecktes Interesse am Genre zu befriedigen.
