---
title: "Ein (un)möglicher Härtefall"
date: "2003-10-29T00:00:49"
categories: [gesehen]
---

*USA (2003)
Regie: Joel Coen
Darsteller: George Clooney (Miles Massey), Catherine Zeta-Jones (Marylin Rexroth), Paul Adelstein (Wrigley), Edward Herrmann (Rex Rexroth), Geoffrey Rush (Donovan Donnelly), Billy Bob Thornton (Howard Doyle), Cedric the Entertainer (Gus Petch), Richard Jenkins (Freddy Bender), Julia Duffy (Sara Sorkin), Jonathan Hadary (Heinz, Baron Krauss von Espy), Stacey Travis (Bonnie Donaly), Jack Kyle (Ollie Olerud), Tom Aldredge (Herb Myerson), Irwin Keyes (Wheezy Joe) und andere  Härtefälle*
[Offizielle Homepage](http://movies.uip.de/einunmoeglicherhaertefall/)

Marilyn Rexroth kann ihrem Mann, einem schwerreichen Immobilien-Tycoon, den Ehebruch nachweisen und bekommt doch nach der Scheidung keinen Cent von dessen Vermögen. Schuld daran ist der überaus erfolgreiche Anwalt Miles Massey, der das Gericht im Auftrag von Rex Rexroth überzeugen konnte, dass Marilyn ihn nur wegen seines Geldes geheiratet hat. Doch noch während der Verhandlung verliebt sich der in der Midlife-Crisis steckende Miles in die Prozess-Gegnerin, die sich jedoch sofort nach der Scheidung einen neuen vermögenden Ehemann krallt...

Seit dem letzten Film der Coen-Brüder ([The man who wasn't there](/blog/2002/01/07/the-man-who-wasnt-there/)) sind mittlerweile schon fast 2 Jahre verstrichen und so machte ich mich pflichtbewusst auf um zu sehen, ob auch die neue Komödie hielt was die beiden Vorgänger ("The Big Lebowski" & "Oh Brother where are thou'") versprachen.

Mit nur zwei und dafür auch recht neuen Coen-Spezies (Clooney und Thornton) fiel die Besetzungsliste diesmal doch sehr überraschend aus (wo sind Holly Hunter und John Goodman?), doch der gute George macht dies allein wieder wett: Wie er den eitlen, verliebten und gehörnten Anwalt spielt ist einfach nur klasse; der Running-Gag mit den Zähnen zieht immer wieder und die Parodie auf herkömmliche Liebeskomödien (die Rede auf dem Kongress in Las Vegas) ist wie für ihn geschrieben. Leider funktioniert die zweite Hauptfigur Marilyn dagegen überhaupt nicht; Catherine Zeta-Jones versucht erst gar nicht, mehr Tiefe aus dem Drehbuchcharakter ohne Intention heraus zu holen als schön auszusehen, und so wird dieser Part zum Totalausfall. Aber dafür gibt es auch hier wieder die skurilsten Nebencharaktere wie den Asthma-kranken Auftragsmörder, Baron Heinz Krauss von Espy mit seinem Hund oder der greise Senior-Partner Herb, der in seinem dunklen Versteck in der Kanzlei nur noch von Schläuchen am Leben gehalten wird.

In Abweichung zum sonstigen Coen-Schema geht es diesmal aber nicht um die kleinen Leute, die sich in zu große Sachen einmischen und dann von einer chaotischen Situation in die nächste stürzen, sondern um Mitglieder der High-Society und deren Laster und Vorstellungen vom Leben (die wir aber leider nur zu genau aus der Regenbogenpresse und anderen Anwaltsfilmen und -serien kennen). Miles Massey ist zwar der erfolgreichste Scheidungsanwalt der USA, doch fehlt ihm dazu noch die passende Partnerin, und diese Situation nutzt Marilyn schamlos aus um sich erstens sein Geld zu schnappen und sich zweitens für den verlorenen Rexroth-Prozess zu bedanken. Die nicht sehr komplexe Geschichte mit der vorgetäuschten Heirat kann dem Film jedoch kaum Schwung geben; gerade im Mittelteil hat der Film doch seine Längen und so müssen die Nebencharaktere für das nötige Tempo und den einen oder anderen Witz sorgen. Erst gegen Ende kommt mit dem Auftragsmörder auch wieder das gewohnte chaotische, Slapstick-hafte Element ins Spiel und dann ist der Film nach seiner besten Szene (Asthma-Spray vs. Pistole) und einem etwas unwirklichen Happy-End auch schon zu Ende. Insgesamt fehlt für eine schwarze Komödie, wie man sie von den Coen-Brüdern gewöhnt ist, einfach die Bissigkeit; ein genial herumalbernder George Clooney kann nicht verhindern dass der Film doch einige (schlechte) Eigenschaften von "echten" Liebeskomödien annimmt und auf Hochglanz poliert daher kommt.

Fazit: Trotz allem ist "Ein (un)möglicher Härtefall" immer noch eine überdurchschnittlich gute Komödie mit angenehm skurilen Nebenrollen und teilweise schwarzem Humor, doch einige Längen und die ausgetretene Geschichte verhindern eine Top-Wertung!
