---
title: "Rat Race"
date: "2002-09-10T00:00:18"
categories: [gesehen]
---

*USA (2002)
Regie: Jerry Zucker
Darsteller: Rowan Atkinson (Mr. Pollini), Cuba Gooding Jr. (Owen Templeton), Jon Lovitz (Randy Pear), Seth Green (Duane Cody), Whoopi Goldberg (Vera Baker), John Cleese (Donald Sinclair), Kathy Najimy (Beverly Pear), Breckin Meyer (Nick), Amy Smart (Tracy Faucet), Wayne Knight (Zack), Paul Rodriguez (Gus), Vince Vieluf (Blaine Cody), Lanei Chapman (Merill Jennings), Dean Cain (Shawn), Dave Thomas (Mr. Grisham) und andere bekannte Gesichter*
[Offizielle Homepage](http://www.ratrace-derfilm.de)

Ein skuriler Hotelbesitzer aus Las Vegas veranstaltet ein ungewöhnliches Wettspiel für die Reichen dieser Welt: Er verspricht demjenigen von sechs zufällig in einem Kasino ausgewählten Personen zwei Millionen Dollar, der am schnellsten zu einem Schließfach in Silver City, New Mexico gelangt; und lässt dabei Wetten in Millionenhöhe auf den Sieger dieses Rennens ausstellen. Und so machen sich die sechs Auserwählten mit ihren Begleitungen los, um auf der Suche nach dem schnellsten Weg schon mal den Flughafen lahmzulegen, einen Reisebus und Hitlers Limousine zu stehlen und eine Kuh an einen Ballon zu hängen...

Dass ich in einem amerikanischen Film nicht unbedingt mit trockenen, schwarzen Humor rechnen kann, war mir schon vor Beginn des Films klar. Und trotzdem erwartete ich von Whoopi Goldberg, Mr. Bean und John Cleese zumindest etwas Qualitätsbewusstsein. Doch genau wie die anderen Schauspieler haben sich auch diese drei für eine mittelprächtige Comedy im Stile der letzten Leslie-Nielsen-Komödien hergegeben, der "den Produzenten der Nackten Kanone" (Werbespruch) wohl langsam etwas zu alt wird.

Dabei ist positiv zu bemerken, dass es kaum Witze auf dem Niveau der Teenager-Movies gibt, wobei sich leider die Witze dann auch als das Hauptproblem des Filmes entpuppen - es gibt einfach zu wenige davon. Der Regisseur nimmt sich für jeden einzelnen Gag 5 Minuten Anlaufphase um die Situation herbeizuführen, so dass der Zuschauer meistens schon vorher die Pointe erahnen kann. Eine Ausnahme bilden da die von Hotelbesitzer Sinclair veranstalteten kleinen Wetten, die auch die einzigen wirklichen Brüller darstellen und nicht in anderen Komödien schon tausendfach gesehen wurden.

Nichtsdestotrotz wurde aus dem unzweifelhaft vorhandenen Talent des Komiker-Ensembles zu wenig gemacht: John Cleese muss die ganze Zeit über gezwungen skuril agieren, wobei seine Rolle noch die meisten Lacher auf seiner Seite hat; Rowan Atkinson zieht die gewohnten Mr.-Bean-Grimassen, wird aber durch die unpassende Synchronstimme und ungewohnte Rolle vom Publikum nicht als Italiener akzeptiert (der Charakter Bean ist einfach zu prägend). Der Rest der Besetzung fügt sich ohne große Ausreißer in ein Gesamtkonzept ein, das für die einzelnen Darsteller zu wenig Zeit lässt und am Ende nach einer kurzen Phase trickfilmhaften Slapsticks ein politisch korrektes Happy End findet.

Fazit: Eine Komödie mit geringer Gagdichte, die wohl in einer halbstündigen Trickverfilmung (wie in der animierten Anfangssequenz) besser aufgehoben wäre. Bitte nicht von der Besetzungsliste beeinflussen lassen, hier wäre weniger wohl mehr gewesen!
