---
title: "Die Kunst des negativen Denkens"
date: "2008-09-25T21:21:06"
categories: [gesehen]
---

*Norwegen (2007)
Regie: Bård Breien
Darsteller: Fridtjov Såheim (Geirr), Kirsti Eline Torhaug (Ingvild), Marian Saastad Ottesen (Marte), Henrik Mestad (Gard), Kari Simonsen (Lillemor), Per Schaaning (Asbjørn), Kjersti Holmen (Tori)*
[Offizielle Homepage](http://www.diekunstdesnegativendenkens.de/)

Komödien sind ja so etwas wie ein Exportartikel in Skandinavien, und mit *Die Kunst des negativen Denkens* hat es eine [weitere](/blog/2004/06/27/elling-nicht-ohne-meine-mutter/) in die deutschen Kinos geschafft. Es geht dabei um eine Gruppe von teilweise an den Rollstuhl gefesselten Menschen, die unter Anleitung einer Therapeutin lernen sollen, positiv mit ihrer Situation umzugehen. Gemeinsam fallen sie bei Geirr zu Hause ein, der seit seiner Querschnittslähmung Probleme mit der Beziehung zu seiner Frau hat, sich jedoch partout nicht helfen lassen will. Mit seiner blockierenden Haltung schafft er es ziemlich schnell, die Therapeutin zu vertreiben, und macht sich dann daran, die verdrängten Probleme der Gruppenteilnehmer an die Oberfläche zu holen...

Ganz zum Ende dieses Filmes fällt der Satz, "um positiv zu denken muss man zuerst die Kunst des negativen Denkens beherrschen". Das das Eine nicht ohne das Andere zu haben ist, wird dem Zuschauer vorher anderthalb Stunden lang deutlich gemacht. Der Film schildert dabei nur einen einzigen Tag und spielt fast ausschließlich im Haus von Geirr und Ingvild. Es wird sich voll auf die Figuren konzentriert; die Kamera ist dementsprechend immer nah dran an den Akteuren; verfolgt teilweise ihre Bewegungen, ohne jedoch jemals deren Perspektive anzunehmen.

Der Zuschauer lernt so Geschäftsmann und Sonnyboy Gard kennen, der die Schuld an der Querschnittslähmung seiner Freundin Marte trägt. Desweiteren Asbjørn, der sich nach einem Schlaganfall kaum selber bewegen und artikulieren kann, Lillemor, eine depressive und hypochondrisch veranlagte ältere Frau und schließlich Tori, die mit dem Erfolg ihrer Therapie Aufsehen erregen und so ihr Buch verkaufen will.

Als Gruppe wurden sie von Tori auf positives Denken hin geeicht. Tori ist der Meinung, damit die Lebensqualität ihrer Schützlinge verbessert zu haben. Doch Geirr deckt ziemlich schnell auf, dass dies alles nur Fassade ist; eine zwar schöne und optimistische aber auch einengende und erdrückende Fassade. Gleichzeitig wird jedoch deutlich, dass auch Antiheld Geirr sich hinter seiner abweisenden Art nur versteckt. Die Kunst des negativen Denkens hat er zwar perfektioniert, doch so gut diese provozierende Haltung die inneren Konflikte in der Therapiegruppe aufdecken kann, so schlecht hilft sie bei den Problemen mit seiner Frau.

Als Drama wäre diese Geschichte nur eine unter vielen geworden, doch in Komödienform entfaltet sie ihren wahren Charme. Geirr setzt mit seinen wunderbar trockenen Aktionen die Akzente, die seine Gäste zu immer makaberen Reaktionen bewegen. Dabei werden nebenbei Themen wie Suizid verarbeitet, ohne die Figuren dabei lächerlich zu machen oder die Ernsthaftigkeit der Thematik zu berühren. Dies ist die Kunst des Films: Eine witzige Geschichte zu erzählen und trotzdem moralisch zu bleiben; wenngleich das Happy End zwar zum Film passt, aber die Aussage hinterfragt werden sollte.

Fazit: Eine typisch skandinavische Komödie mit teilweise recht bösem Humor, die gut gespielt und gefilmt es sogar schafft, die Themen rund um eine Behinderung zu behandeln, wenngleich dies eher oberflächlich geschieht.
