---
title: "Die Rückkehr des Drachens"
date: "2005-11-08T15:12:04"
categories: [gelesen]
---

*von Robert Jordan,
erschienen bei Piper, ISBN 978-3-492-70083-2, 16€*

Nachdem Heyne es endlich geschafft hatte, die Bücher aus der Serie *Das Rad der Zeit* nicht mehr nur aufgeteilt auf zwei Bände zu veröffentlichen und die Originaltitelbilder zu verwenden, folgte plötzlich der Verkauf fast der gesamten Fantasy-Sparte an Piper. Scheinbar alle gutgehenden Serien inklusive der Scheibenwelt-Taschenbücher wanderten mit in die neue Heimat, so auch die Werke von Robert Jordan.

Nun setzt Piper die Serie fort bzw hat auch die beiden bereits veröffentlichten Bücher neu aufgelegt. Das Konzept bleibt dasselbe, nur leider wurde das Format etwas verändert und die Bücher haben eine metallisch glänzend anmutende Oberfläche, über deren Optik man sich streiten kann. Auf den letzten Seiten findet sich neben dem üblichen Glossar auch die Karte aus dem ersten Band, allerdings nur in einem Schwarz-Weiß-Druck, der einige Schriftzüge schlecht lesbar macht. 16€ sind dafür ganz schön happig (*Die Jagd beginnt* kostete bei Heyne noch 12€), aber immerhin noch besser, als 2x10€ für die schlanken Taschenbücher auszugeben.

Inhaltlich ist das Buch leider das Schwächste der Serie bis dahin - bis zur Hälfte der Seiten will die Handlung nicht so recht in Schwung kommen. Zu oft wird über das bereits Geschehene berichtet, und die immer gleichen Aktionen (und vor allem unverständlichen Reaktionen darauf) von Nynaeve, Egwene und Elayne nerven ziemlich schnell. Auch die Wanderung von Mat zusammen mit Thom läuft auf ausgetretenen Pfaden, wenngleich sein in diesem Roman nicht geklärtes Spielglück einen interessanten Aspekt darstellt.

Da kann die Verfolgung von Rand durch Moraine und Perrin schon mehr fesseln, vor allem da der Leser endlich mehr über die Verlorenen und Mins Weissagungen lernt. Ganz am Ende erfährt man auch endlich, wer der Habicht ist, der neben dem Falken auf Perrins Schulter sitzt. Zusammen mit der intriganten Lanfear lässt dies auf die folgenden Romane hoffen.

Ganz zum Schluss kommt es dann endlich zu dem erwarteten Showdown und dem Zusammentreffen aller Antagonisten, doch da endet das Buch auch schon und lässt viele Fragen offen. Rand hat wie immer, ohne zu wissen wie, am Ende gewonnen, doch dass ihn alle Verlorenen und Bal'zamon mit Lews Therin Brudermörder anreden lässt vielleicht mehr eine gespaltene Persönlichkeit bei ihm entstehen als das Verdorbene des Dunklen Königs an Saidin.

Alles in allem also eine schwache Episode, in der sich von den Charakteren allein Perrin wirklich weiterentwickelt. Doch es wurden genügend Fäden für die weiteren Bücher gesponnen, so dass ich auf jeden Fall noch den nächsten Band erwerben werde. Ein Höhepunkt der Kreativität ist *Das Rad der Zeit* sicher nicht, aber als netter Zeitvertreib zum Zwischendurch-Lesen durchaus zu gebrauchen.
