---
title: "The Congress"
date: "2013-11-22T23:26:23"
categories: [gesehen]
---

*Israel/Deutschland/Polen/Luxenburg/Frankreich/Belgien (2013)
Regie: Ari Folman
Darsteller: Robin Wright (Robin Wright), Kodi Smit-McPhee (Aaron Wright), Sami Gayle (Sarah Wright), Danny Huston (Jeff), Jon Hamm (Dylan Truliner), Paul Giamatti (Dr. Barker), Harvey Keitel (Al) und andere Trickfilmfiguren*
[Offizielle Homepage](http://congress.pandorafilm.de/)

Robin Wright ist mit Anfang 40 scheinbar am Ende ihrer Karriere als Schauspielerin angelangt. Niemand in Hollywood will sie mehr besetzen; zu viele Rollenangebote hat sie abgelehnt, zu eigenwillig hat sie sich bei den Dreharbeiten verhalten. Also lebt sie mit ihren beiden Kindern in einer ehemaligen Flugzeughalle und kümmert sich hauptsächlich um den Sohn, der an einer Krankheit leidet, die ihm nach und nach erst das Gehör und dann das Augenlicht kosten wird.

Da die Behandlung des Sohnes einiges Geld kostet, lässt sie sich auf einen Deal mit einem Studioboss ein: eine finale, letzte Rolle. Das Studio scannt ihr Äußeres ein und digitalisiert ihre Emotionen mit dem Ziel, künftig beliebig Filme mit einer nicht-alternden, virtuellen Robin Wright zu drehen. Die echte Robin willigt ein, nie wieder vor eine Filmkamera zu treten.

20 Jahre später hat sich die Welt radikal geändert. Jeder Mensch besitzt ein frei wählbares digitales Ich, mit dem er in künstliche Welten flüchten kann. Doch das Filmstudio, welches diese Welten beherrscht, hat revolutionäres vor. Mit Hilfe von synthetischen Drogen soll jeder Mensch die Wahrnehmung der echten Welt seinen Bedürfnissen anpassen können, in seiner ganz eigenen Welt leben können. Deshalb soll Robin einen weiteren Vertrag unterschreiben, in welchem sie die Rechte an ihrem Abbild auf allen Sinnesebenen abtritt.

Für die Unterschrift unter den Vertrag wird sie zum titelgebenden Futurologischen Kongress eingeladen, der im virtuellen Nobelhotel des Filmstudios stattfindet. Doch aus der als triumphale Vorstellung gedachten Veranstaltung wird eine Katastrophe, als Gegner der neuen Technik den Kongress überfallen und alle Beteiligten einem Drogencocktail ausgesetzt werden. Robin wird bei der Flucht aus dem Hotel verletzt und muss eingefroren werden, da niemand sie heilen kann. 

Wiederum 20 Jahre später wird sie aufgeweckt und findet sich in einer Welt wieder, in der fast die gesamte Menschheit in die eigene drogenbasierte Wahrnehmung geflüchtet ist.  Robin macht sich auf die Suche nach ihren beiden Kindern und muss dabei entdecken, was aus der realen Welt hinter der Drogenfassade geworden ist...

Vor fünf Jahren gelang Ari Folman mit [Waltz with Bashir](/blog/2009/01/28/waltz-with-bashir/) einer der besten jemals gedrehten Animationsfilme. Die Kombination aus einem eindringlichen Thema, erzählt aus einer interessanten Perspektive und versehen mit einer neuartigen, perfekt passenden Animationstechnik führte zu einem großen Gesamtkunstwerk. Als ich davon hörte, dass Folman als nächstes das Buch "Der Futurologische Kongress" von Stanislaw Lem verfilmen wollte, war ich dementsprechend sehr gespannt und voller Erwartungen beim Screening im Rahmen des diesjährigen [FFF](http://www.fantasyfilmfest.com/filme/Congress.html).

Umso irritierter war ich im ersten Drittel des Films, als sich die Handlung selbstreflexiv um die Umwälzungen in der Filmwelt am Beispiel von Robin Wright drehte. Keine Animation weit und breit, dafür eine kleine Geschichte mit nur wenigen Charakteren. Damit habe ich nicht gerechnet.

Doch der Futorologische Kongress sollte noch folgen und mit ihm viele Plotelemente, die eigentlich Ijon Tichy erlebt, der Held aus Lems Sterntagebüchern. Geschickt verbindet Folman das Thema von der Entfernung der Darstellung vom tatsächlichen Ich aus der filmbezogenen Storyline um Robin Wright mit der Suche nach der tief unter der Drogenwahrnehmung verborgen liegenden Realität aus der Buchvorlage.

Doch der Film schlägt als Folge seines ersten Drittels den Weg zu einem abweichenden Ende ein. Wo bei Lem zum Schluss alles ist wie vorher und sämtliche Drogenerfahrungen nur im Kopf stattgefunden haben, kommt Folman in seinem Gedankengang einer zuksessiven gesellschaftlichen Umwälzung zu einer anderen Vision der Zukunft: Die Menschheit hat sich fast vollständig in die potemkinschen Dörfer der eigenen Vorstellung zurückgezogen und nur wenige ziehen die Tristesse der Realität einer manipulierten Wahrnehmung vor.

Dies hat natürlich Auswirkungen auf die reale Welt. Die in der eigenen Wahrnehmungswelt versunkenen Menschen sind nurmehr Zombiewesen, deren Körper irgendwie am Leben gehalten werden. Der Unterschied zu der grellbunten animierten Drogenwelt ist extrem. Von den Häusern, deren Einrichtung über die Kleidung bis hin zum Wetter ist alles grau. Es scheint, als hätten sich alle kreativen Menschen aus der Realität geflüchtet und der Rest der Menschheit versucht als stützender Unterbau die Fassade nicht einstürzen zu lassen.

Doch so unreflektiert negativ, wie es anscheinend abgebildet ist, lässt Folman diese Welt der Zukunft nicht stehen. Robins Sohn mit seinen abgestorbenen körperlichen Sinnen kann dank der Drogen wieder Bilder und Geräusche wahrnehmen, wenn auch nur in seinem Kopf und als Reaktion auf andere Sinnesreize. Und Robin schafft es schließlich, dank der aufgelösten Schranken von Raum und Zeit des eigenen Wahrnehmungssystems, zu ihrem Sohn zu finden und mit ihm zu leben. Ein sehr versöhnliches Ende für eine nicht immer positiv gemalte Zukunftsperspektive.

Diese lebt, im Gegensatz zu [Waltz with Bashir](/blog/2009/01/28/waltz-with-bashir/), von ihrer eindeutig als solche zu erkennenden Trickfilmwelt, die nicht nur real gedrehte Szenen verschleiert oder filtert. Alles ist quietschbunt, die Charaktere bedienen sich bei bekannten Bildern aus der gesamten Trickfilmgeschichte. Die Kreativität scheint dabei abhanden gekommen zu sein, da sich viele Figuren wie die von Marilyn Monroe wiederholen. Eine Lesart dieses Details ist, dass die Menschen sich nicht mehr anstrengen, wo sie doch alles sein können, was sie wollen. Es gibt folglich kein Streben mehr und keine neuen Ideen, so dass es den Menschen auch egal ist, wie sie in der echten Welt aussehen und was mit ihren Körpern passiert.

Zusammengehalten werden die verschiedenen imaginären und zeitlich getrennten Welten des Films durch den ruhigen Soundtrack. Ein wiederkehrendes Pianomotiv lässt auch auf dem hektischen Kongress und in der deprimierenden realen Welt der Zukunft noch an das Happy End glauben. Von dem vorher extra angekündigten [Dolby Atmos](http://www.dolby.com/us/en/consumer/content/movie/release/dolby-atmos-movies.html), welches über zusätzliche Deckenlautsprecher verfügt, habe ich aber nicht viel mitbekommen. Dazu ist der Film über weite Teile einfach zu ruhig. Und das ist auch gut so, denn obwohl *The Congress* es nicht schafft, die Buchvorlage adäquat auf die Leinwand zu bringen und verglichen mit [Waltz with Bashir](/blog/2009/01/28/waltz-with-bashir/) den Kürzeren zieht, so hat er doch einiges zu sagen und zu zeigen, über dass es sich nachzudenken lohnt!
