---
title: "Nonpareille n'est pas seulement une police de caractères"
date: "2007-12-17T23:37:12"
categories: [gedacht]
---

Eigentlich sollte dies ein Beitrag über Schokoladenkränze bzw -plätzchen werden, die zu Weihnachten so beliebt sind. Doch beim Naschen der Packung von [Schluckwerder](http://www.schluckwerder.de/) (die Besten am Markt) fiel mein Blick auf das Wort *Nonpareille*, und so öffnete ich schnell die [Wikipedia](http://de.wikipedia.org/wiki/Nonpareille) um herauszufinden, was sich dahinter verbirgt. Aha, eine kleine Schriftart also - that's it, kein weiterer Artikel über eine Backzutat oder Süßwarenart, nothing.

Und trotzdem listet Google die Wikipedia-Seite als ersten Eintrag bei den Ergebnissen der Suchanfrage. Da möchte man ja schon fast an die Verschwörungstheorien glauben, nach denen Google und Wikipedia gemeinsam daran arbeiten, unser Weltbild zu beeinflussen. Dabei ist es natürlich, dass bei der Wikipedia eher zu dem technischen Thema Schriftart einen Eintrag zu finden ist als zu dem Arbeitsmaterial eines Zuckerbäckers. Wenn man noch in Betracht zieht, dass die Wikipedia mit ihrem PageRank alle anderen, möglicherweise relevanteren Ergebnisseiten nach hinten in der Liste verdrängt, erklärt sich auch die Platzierung in der Google-Liste.

Bleibt aber noch das Problem, dass ich auf den ersten Blick im Internet keine Erläuterung dazu fand, was *Nonpareille* nun eigentlich ist. Doch auf der zweiten Ergebnisseite von Google beim [Bundesverband der Deutschen Süßwarenindustrie](http://www.bdsi.de) wurde ich schließlich fündig: Es hat 7,6 Broteinheiten pro 100g und kann mit Streukügelchen oder auch Liebesperlen übersetzt werden.

Wenn man schließlich weiß, was es ist, findet man es natürlich auch in der Wikipedia - im Beitrag über [Liebesperlen](http://de.wikipedia.org/wiki/Liebesperlen). Leider ist es mir nicht gelungen, eine Verlinkung von *Nonpareille* auf diesen Artikel zu setzen. Da muss ich wohl noch etwas die WIKI-Syntax studieren, bevor die zu dieser Jahreszeit vermutlich gar nicht so seltene Suchanfrage endlich zu einem schnelleren Ergebnis führt.
