---
title: "Filmsprache - Einführung in die interaktive Filmanalyse"
date: "2009-07-19T19:26:22"
categories: [gesehen,gelesen]
---

*von Alice Bienk,
erschienen bei Schüren, ISBN 978-3-89472-537-2, 24,90€*

Es gibt verschiedene Wege, sich einem Film für die Interpretation zu nähern. Man kann das Kino wie die Fotographie auf seine optische Darstellung reduzieren, [kann nur die erzählte Geschichte analysieren](/blog/2008/05/28/bucher-kurzbesprechung/) oder den Soundtrack betrachten. Alice Bienk will ein Verstehen auf allen Ebenen des Mediums Films erreichen und liefert mit diesem Buch einen Überblick über die wichtigsten stilistischen Mittel der genannten Aspekte.

Damit hat der *Filmanalyse*-Teil des Buchtitels seine Berechtigung, doch leider ist keine wirkliche *Einführung* daraus geworden. Auf nicht einmal 120 Seiten werden viele Begriffe wie Mis-en-Scène und Montage vorgestellt, aber leider meist nur angerissen. Das Buch liest sich wie eine Enzyklopädie, denn ständig stören Verweise auf andere Begriffe den Lesefluss, so dass man das Werk zum schnellen Nachschlagen verwenden kann, aber nicht zum Erlernen. Zudem sind die Beschreibungen recht kurzatmig und bestehen oft nur aus einer Aneinandereihung von Zitaten aus anderen Büchern oder Zeitschriften.

Dass die Autorin als Lehrerin arbeitet merkt man daran, dass sich an viele Kapitel Aufgaben anschließen. Diese sind mit dem *interaktiven* Teil des Buches, einer DVD mit Filmausschnitten, zu lösen. Erst damit erschließen sich einige der Begriffserklärungen und machen so das Anliegen der Autorin deutlich, einen Film an Hand kleiner Szenen zu analysieren und nicht im Gesamten oder mit einem Protokoll. Die analog zu einem Schulbuch vorhandenen 40 Seiten Auflösung zeigen jedoch, dass man die meisten Aufgaben gar nicht korrekt lösen kann, wenn man nicht schon das Grundwissen besitzt, welches das Buch eigentlich vermitteln will.

Zumindest ist die Auswahl der Filme und Ausschnitte gelungen. Es gibt eine gesunde Mischung aus Klassikern (viele noch in SW) und modernen Highlights, die eine Schülerschaft schon im Fernsehen gesehen haben könnte (z.B. *Sin City*, *Matrix*). In einigen Szenen erinnert die Qualität aber leider an digitalisierte Videotapes - Blockartefakte und knacksenden Ton habe ich schon lange nicht mehr auf einer DVD erlebt. Da es im Buch auch eine kurze Einführung in die digitale Videoverarbeitung gibt liegt die Vermutung nahe, dass es sich wirklich im selbstangefertigte Kopien handelt. Zum Glück sind die verwendeten Stilmittel - bis auf wenige Ausnahmen - trotzdem noch erkennbar.

Fazit: Für eine Einführung ist das Buch zu kurzatmig geraten; wenn man die Filmanalyse wirklich lernen will sollte man besser zum [Standardwerk von Monaco](http://www.rowohlt.de/buch/James_Monaco_Film_verstehen.11072009.5894.html) greifen, welches auch fleißig zitiert wird. Gut ist hingegen die Auswahl der Szenen auf der beiliegenden DVD, die viele der Stilmittel erst verständlich machen. Wer diese jedoch nicht benötigt, muss auch nicht zu diesem Buch greifen.

P.S.: Ich sollte schnellstens meine Bildungslücke *Spiel mir das Lied vom Tod* beseitigen. Die auf der DVD enthaltenen Schnipsel aus dem Film haben definitiv mein Interesse geweckt.
