---
title: "Das Zelt muss stehen"
date: "2009-03-01T23:13:50"
categories: [gefunden]
---

Als ich 2001 in [Wacken](http://www.wacken.com/) war, da dachte ich schon, mehr als die 25.000 Besucher verkraftet das Festival nicht. Doch mittlerweile muss man schon vor Weihnachten bestellen, um eine der begehrten 80.000 Eintrittskarten zu ergattern, und am Besten schon montags in der Festivalwoche anreisen damit die Fußwege zur Bühne nicht zu lang werden.

Aber nicht nur Wacken-Fans haben mit diesem Problem zu kämpfen, und so hatten ein paar Leipziger die ultimative Geschäftsidee: Sie bieten einen Festival-Zelt-Verleih und -Aufbauservice an für alle, die nicht zeitig genug anreisen wollen oder können, um sich einen guten Platz zu sichern. Das Ganze nennt sich passend [Mein Zelt steht schon](http://www.mein-zelt-steht-schon.de) und hat außerdem den Vorteil, dass nach dem Festival Abbau und Säuberung der Schlafgelegenheiten entfallen. Besonders bei verregneten Events hört sich dies sehr verlockend an.

Die Leistung wird momentan für 18 mehr oder weniger bekannte Festivals angeboten. Dies bedeutet für die Organisatoren: Sie verbringen fast den gesamten Sommer auf Campingplätzen, müssen eigentlich nur an zwei Tagen arbeiten (Auf- und Abbau) und bekommen auch noch Geld dafür. Ganz abgesehen davon, dass sie die Festivals gleich noch mit erleben können. Eine tolle Idee, der ich den wirtschaftlichen Erfolg wünsche!
